### ISSUE TITLE
Map orientation: to direction of movement

### ISSUE THREAD

**Issue by deerwood** [streetcomplete/StreetComplete#1040]
I tested the compass mode in StreetComplete ... does not work for me at all! Probably because my smartphone case has magnets to close/open it.

As I am using OsmAnd+ all the time for navigation, I know (and love) their "Map orientation: to direction of movement", obviously not influenced by nearby magnets. I believe it works by using GPS positions (with Kalman filter for smoothing).

With that one always sees what's ahead.

Please add this feature, it would help a lot e.g answering the cycleway quests. And it would be nice for users without compass.

**Comment by rugk** [comment]
That is basically https://github.com/westnordost/StreetComplete/issues/988, I think.

Just seems you want to make it optional and not the default?

**Comment by ENT8R** [comment]
@deerwood Does it work but the map is always spinning around or does nothing happen if you enable the compass mode?

**Comment by deerwood** [comment]
@ENT8R it works essentially, display is rather "nervous", but my driving direction is most often not from bottom of screen to top, as wanted and usefull, but arbitrarily left/right, right/left, backwards (top/down) or any other direction. See the short video I made:

http://tugendbol.de/streetcomplete/Alster-20180430-215134.mp4

Note, that the compass symbol top right points to north correctly; probably because it is tied to the map and not showing my phones compass direction.

And yes, I think this feature request is similar #988, exept that I ALWAYS want to have that mode on, even with slow speeds. As said, because of my case using rather strong neodym magnets NO compass app works on my phone.

But OsmAnd+ demonstrates, that the GPS based direction detection works very well, max 20° deviation even when moving slow. They also dampen a lot more

**Comment by rugk** [comment]
Exactly the same as I requested I think, now. And AFAIK I did not actually limit it to slow speeds.

I just thought you want it optional as a setting.

**Comment by deerwood** [comment]
Just let's have 3 map orientations (as in OsmAnd):
- do not rotate (north always up)
- to compass
- to direction of movement (GPS based)

That way the user can choose what works best for him.

**Comment by ENT8R** [comment]
> to direction of movement (GPS based)

So you want this to be calculated? I think this is too complicated and pretty difficult for low speeds like walking...

**Comment by deerwood** [comment]
@ENT8R yes, I want it to be calculatet. And I don't think it is too complicated, Googling for "calculate direction between two coordinates" gives plenty of results e.g. https://www.movable-type.co.uk/scripts/latlong.html#bearing.

And in OsmAnd it works reliably, see the video I recorded below.

![osmand-path](https://user-images.githubusercontent.com/90085/39500413-8e872db2-4db4-11e8-9755-0acf79578dce.jpg)

I walked slowly (4 km/h) the green path, starting left bottom in direction NNW, made a sharp turn to WSW, turned 180° and walked back the same path. 

Video: http://tugendbol.de/streetcomplete/OsmAnd-GPSDirection-20180501-224848.mp4

Notice how stable the display is. This is, what I want to have in StreetComplete too.

**Comment by rugk** [comment]
That looks great. As such, that thing would be a great feature for StreetComplete.
And maybe one would anyway only enable it for higher moving speeds. If you want to suggest that, one could also name the setting "driving mode" or so.

And to get to that neodym magnet thing again: You always carry some with yourself? So that is your actual problem there?😁
Btw as you can see from my other issue, this also happens without them in some cases.
So an option would certainly be fine.

**Comment by westnordost** [comment]
Whoever is interested is free to experiment around with adding an option to switch to direction-of-movement mode. I am not sure if it can work out on low speeds and unstable GPS signal (the signal from the video is very stable).

**Comment by deerwood** [comment]
I'm not an app developer, but a *user* of SC. Thus it would be hard for me to help implementing this feature (I work with databeses, SQL, PHP, Perl etc). So I ask for help.

@rugk yes, the magnets are always with me; in my phones case;
![magnet1](https://user-images.githubusercontent.com/90085/39558179-b8f1c606-4e8c-11e8-89d6-a81a64be9e44.jpg)
![magnet2](https://user-images.githubusercontent.com/90085/39558237-30924ae6-4e8d-11e8-9dff-bcea5c54f0b8.jpg)
And yes, that is the reason, why I can't use the compass mode in the first place. North is most often, where the case magnets tell the phone sensors.

**Comment by mahdi1234** [comment]
Would be great to add this to be usable when using bycicle ... I tried today, but app is bit cumbersome to use when on bike as map issues appear too late/unexpectedly and well I'm usually not in mood to turn around, but if I'd see it in advance, I would stop and make the change :)

**Comment by rugk** [comment]
@westnordost, if you don't want to implement this by yourself better mark it as "help wanted".

**Comment by westnordost** [comment]
Basically everything that has no high priority for me is.

**Comment by zyphlar** [comment]
This seems to be working somewhat. My compass is always quite off but once I start moving the streetcomplete map seems to orient itself.

**Comment by lenod** [comment]
Just a remark on this topic: already in osmand the default is to use direction of movement. If I swap to compass mode, it gets about as shaky as in SC. I reckon compass is too sensitive for this usage.

**Comment by klawdhfzasjhaa** [comment]
> Basically everything that has no high priority for me is.
> […](#)
> On June 9, 2018 8:46:40 PM GMT+02:00, rugk ***@***.***> wrote: @westnordost, if you don't want to implement this by yourself better mark it as "help wanted".

In my opinion, this should have a higher priority. People are used to maps following their position / view point. With Street Complete things are different, so users get frustrated and leave. See #988.

Could this perhaps be related to LineageOS?

**Comment by riQQ** [comment]
Another reason: some devices don't even have a compass, but they do have GPS.

Quick search on Geizhals.de:
2253 phones with Android
- 99.8% have GPS (2248/2253)
- 79.1% have a compass (1781/2253)

**Comment by mnalis** [comment]
It perhaps might be additional option (if someone is willing to implement), but should not replace compass which is invaluable in finding target: I can rotate toward POI and compass changes immediately, showing target in front of me.
 
For GPS direction you have to move quite a few meters toward target (and that is assuming good GPS reception, which will likely not be there if you are in densely populated area where you usually need it the most).

**Comment by zyphlar** [comment]
It's only invaluable if your compass actually works: my Galaxy S8 is nearly
always off by at least 30-120 degrees and jittery as heck despite doing
every calibration available. So yeah it should definitely be user's choice,
just like other apps.

**Comment by BalooUriza** [comment]
On Fri, Feb 19, 2021 at 2:44 PM Matija Nalis <notifications@github.com>
wrote:

> It perhaps might be additional option (if someone is willing to
> implement), but should not replace compass which is invaluable in finding
> target: I can rotate toward POI and compass changes immediately, showing
> target in front of me.
>
> For GPS direction you have to move quite a few meters toward target (and
> that is assuming good GPS reception, which will likely not be there if you
> are in densely populated area where you usually need it the most).
>
Could it be selectable?  On foot, it's invaluable, but when riding on a
bus, bicycle or in a car, the alternator drives the magnetic compass crazy
on my phone to the point where it's a completely useless way to orient the
map.

**Comment by smichel17** [comment]
Search term: direction of travel

**Comment by westnordost** [comment]
Alright, I'll implement it.

If it works good, maybe this could even be the default. Let's see.

I looked into the docs and tried some things.
The Android LocationManager actually does return a bearing. It does not return a bearing immediately after getting a GPS fix but only after some walking around, which makes sense. However, the first bearings that are returned are horribly imprecise and when taking a turn, they are also very imprecise at first. It is possible to query the precision of the bearing but only starting with Android 8.0. Since Android versions below that are supported, this can't be used.

So probably I'd end up with storing the user's location each time a new location is returned and calculate a bearing + bearing precsion from that instead. Only right now, I have no idea for a good approach for an algorithm. Any links to how other apps do this would help!

**Comment by zyphlar** [comment]
OsmAnd has a pretty good version with the caveat that it needs to ignore positions within a small radius like maybe 5-10m... or perhaps within the radius of calculated accuracy. Maybe it could notice that the accelerometer is stationary and not traveling? Because at a stop, OsmAnd will succumb to GPS inaccuracy and orient your direction of travel randomly and only fix itself when you begin moving again. I wonder if the Android API includes fixes for that, if later versions could just use that API

**Comment by westnordost** [comment]
Does someone have the link to the source code that handles this of OsmAnd?

**Comment by zyphlar** [comment]
It's not the best algorithm in the world but https://github.com/osmandapp/OsmAnd/blob/956825357919c8dbc2dac490bd64a8ac8ba6b290/OsmAnd/src/net/osmand/plus/base/MapViewTrackingUtilities.java#L207

**Comment by westnordost** [comment]
Thanks for the link. So, OsmAnd just uses the bearing from the location manager.

**Comment by westnordost** [comment]
![Screenshot_20211001-130511_StreetComplete Dev](https://user-images.githubusercontent.com/4661658/135614237-c3d66545-045e-4ddb-b653-2871fbfb6cca.jpg)

**Comment by westnordost** [comment]
It is now automatically shown which way you went for better orientation!

**Comment by smichel17** [comment]
On your way to the Suez Canal, it looks like?

**Comment by westnordost** [comment]
I hope it'll fit

**Comment by rugk** [comment]
> It is now automatically shown which way you went for better orientation!

Wait, this is a joke, is not it? Is it already April 1st? You don't really want to make that a production feature?

I may see it could be useful in debug builds, but really in production… drawing random lines where you've been? Is that useful? For whom and why? I cannot imagine it.

Feel free to prove me wrong though, and if you do, I'd propose to have a fade-away UI, so after X m/km or whatever it fades away, i.e. the color gets lighter until you don't see it anymore on the map. So really like a (ski) track…

**Comment by mnalis** [comment]
@rugk see the linked https://github.com/streetcomplete/StreetComplete/issues/2209 for explanation (and especially the second picture and related text, which matches your suggestion).

**Comment by westnordost** [comment]
The tracks will be cleared when the app is restarted. Also,  old tracks will be rendered with less alpha. An old track is a track whose last point was recorded one or more minutes before the oldest point of the current track. 

I initially wanted to have it rendered as a dotted line that slowly loses alpha but that wasn't possible with tangram.

So, the second example in #2209 was not possible to implement and in the end,  showing the whole track walked is more useful anyway. The track doesn't obscure anything important. 

A few months ago,  I did some UX testing with my mom and found out,  that there are indeed people who have issues reading a map. I.e. to project what they see on the map to what they see in the real world and vice versa.

In particular,  the default orientation of North-up. Most people don't intuitively know which direction is North.
Always showing the path walked should, along with the other features, contribute to helping to orient oneself on the map. This is especially helpful when the direction/ rotation of the map matters - in the sidewalk quest, the cycleway quest etc.

The hope is that these people will be enabled to contribute (more) too.

Besides, it is somewhat of a fun feature because it's just cool to see where one all walked today with the app, idk why

Am 2. Oktober 2021 03:59:21 MESZ schrieb Matija Nalis ***@***.***>:
***@***.*** see the linked
>https://github.com/streetcomplete/StreetComplete/issues/2209 for
>explanation (and especially the second picture and related text, which
>matches your suggestion).
>
>-- 
>You are receiving this because you were assigned.
>Reply to this email directly or view it on GitHub:
>https://github.com/streetcomplete/StreetComplete/issues/1040#issuecomment-932661981

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by rugk** [comment]
Great explanation, yeah, I'm looking forward to testing it! :blush:
