### ISSUE TITLE
TimePicker width is cut off in landscape mode

### ISSUE THREAD

**Issue by lzmartinico** [streetcomplete/StreetComplete#1236]
When the app is in landscape mode, the time picker width is cut off, making it impossible to select a time (similarly to [this](https://stackoverflow.com/questions/35494234/android-timepicker-not-displayed-well-on-landscape-mode) Stackoverflow question)
**How to Reproduce**
Add steps to reproduce this behavior
Turn your phone in Landscape mode, select an Opening Hours quest, Select some weekday, the watch is not displayed correctly in either _opening_ or _closing time_ tabs
**Versions affected**
Android 7.1.1, Street Complete 8.2 and previous

**Comment by westnordost** [comment]
This is an Android bug (imo). I already noticed this months ago and tried to workaround this, also consulting stackoverflow, but did not succeed.

So, it is a known problem but can not be fixed.

**Comment by lzmartinico** [comment]
Yes, it's an Android API bug, but it depends on how you use the TimePicker. The default AOSP calendar, for example, does not get cut off in landscape mode. I know they are not using a tabbed view, but maybe this could be useful? https://android.googlesource.com/platform/packages/apps/Calendar/+/master/src/com/android/calendar/event/EditEventView.java

**Comment by HolgerJeromin** [comment]
screenshot for reference:
![rps20181021_005119_990](https://user-images.githubusercontent.com/2410353/47261266-9e0e7f80-d4cb-11e8-8cee-806d149e3b04.jpg)

**Comment by smichel17** [comment]
I checked if I could reproduce this on a Galaxy S6 running Android 7.0 and found a different but similar issue:

![image](https://user-images.githubusercontent.com/6563664/75038964-9840f980-5485-11ea-9277-88ac1bf7b726.png)

FWIW I ran into the same issue on Red Moon and decided not to fix it. The bug occurs in standard usage and is therefore an Android bug that should be fixed upstream, in my opinion.

If someone wanted to fix it downstream, I think it would be better to write a TimePickerDialog library that works in landscape mode, rather than fixing it in each individual app.

**Comment by matkoniecz** [comment]
add phrase to enable finding this issue: opening hours interface

**Comment by westnordost** [comment]
Would be fixed by #3796

**Comment by westnordost** [comment]
Well I now made that particular view scroll. Not great, but at least it is a mitigation.
