### ISSUE TITLE
Consider enabling "Is lit" quest only during night

### ISSUE THREAD

**Issue by matkoniecz** [streetcomplete/StreetComplete#1285]
From https://github.com/westnordost/StreetComplete/issues/1281#issuecomment-443621518

> It's often impossible (!) to solve these quests at daylight time when the lights are out. For example: Does a road light reach the (separately mapped) parallel footway as well? (It often does, but you cannot be sure until it's dark!) So I decided for me to disable this quest also and to deliberately reenable it if I go out for an evening walk in the dark

I do exactly the same thing for the same reasons (I even moved lit quest earlier to make enabling/disabling it easier).

Maybe it would be a good idea to do it automatically? Calculating sunset/sunrise based on a location and date should be available in some library.

**Comment by cyclingcat** [comment]
This was also my first thought - why not show the quest only when the street lights are usually switched on, e.g. from dusk until dawn? However, some cases are absolutely clear (in Germany e.g. town or village roads with visible light post could be tagged as "lit", even if they are currently switched off); if you force the quest to be hidden during daylight time noone can use SC for tagging these kinds of roads quickly (as I did in the past while cycling through some villages nearby).

Maybe some distinction would be helpful? For "highway=residential" and upwards the quest is always shown, for any other kinds of ways it is shown only when it's dark. And the default ist "off". Or three modes? "Always off" (default), "Always on", "Automagic" (as described above)? But maybe this is too complicated, especially if you have to distinguish between countries...

Of course, it's always in the user's responsibility and I'd suggest to implement the option with the lowest risk of errors - better no tags than wrong tags.

Just some thoughts on this quite complex topic... (and it's even more complex without the problem mentioned here: How to tag a longer footway with just two lamps inbetween and thus some very dark areas? I encoutered this problem several times in the past and decided to hide the quest in these cases).

The cycling cat

**Comment by westnordost** [comment]
How would it help if the quest is shown only during nighttime?

**Comment by cyclingcat** [comment]
At least it would be possible to determine reliably if the way is lit or not. There are cases in which you definitely aren't able to determine this when the lamps are switched off. I mentioned an example in https://github.com/westnordost/StreetComplete/issues/1281#issuecomment-443621518 - a segregated footway parallel to a road; I just have to walk 2 minutes from my home to find such a way. The road lamp seems to be positioned intentionally in a way that it lights both the road and the segregated footway. If the light is switched off you have no chance if it will shine onto the footway when switched on or not.

The cycling cat

**Comment by westnordost** [comment]
Why shouldn't a road not be lit at all if there are street lamps physically present? If there is a traffic light (for example, visible on satellite imagery), you would also assume that it is in service, wouldn't you?

The physical presence is the only thing that is easily verifiable for a surveyor. After all, street lamps may be on not from dusk till dawn but only a few hours - quite difficult to verify.

**Comment by matkoniecz** [comment]
> How would it help if the quest is shown only during nighttime?

In some cases check during the night is necessary to check whatever cycleway/footway next to the road is also lit (is it usually not applicable to sidewalks).

Also, during night survey for that is much easier.

For example: path on embankment along road ( https://www.openstreetmap.org/way/647981370#map=18/50.06787/19.88560 ) - there is no way to properly check lit status during day.

Is also sometimes quite easy to miss that road is lit (street lamps are quite hard to miss, but sometimes lamps may be possible to miss)

>  If there is a traffic light (for example, visible on satellite imagery), you would also assume that it is in service, wouldn't you?

In my case I would not do it and I am not mapping `lit=yes` based solely on the presence of street lamps. For example https://www.openstreetmap.org/way/35765567#map=19/50.06859/19.89787 was unlit last time when I was there, despite that street lamps are there.

> After all, street lamps may be on not from dusk till dawn but only a few hours - quite difficult to verify.

In turn this is unusual in Poland and I was not expecting this case.

**Comment by westnordost** [comment]
Well, deciding whether a footway is still lit by a parallel road is quite fuzzy anyway, isn't it?

**Comment by goldfndr** [comment]
>  How to tag a longer footway with just two lamps inbetween and thus some very dark areas?

Is it possible that one or more lamps were "burnt out" and thus in need of replacement? I reported at least a dozen street lamps out to the operator one year (with no more than one on the same street; I was "wardriving" so I saw a lot of different roads).

**Comment by matkoniecz** [comment]
> How to tag a longer footway with just two lamps inbetween and thus some very dark areas?

In the same way as footway with changing surface - split it if parts qualify for lit=no (though in some cases it may be more useful to report issue like @goldfndr mentioned and wait with mapping ).

**Comment by westnordost** [comment]
Ok well, perhaps it would be a nice gimmick but it is not in any way required IMO.

**Comment by cyclingcat** [comment]
As a compromise, I'd suggest to switch the default from "enabled" to "disabled". This way the risk of mistagging by people who aren't aware of the various problems discussed here will be mitigated, while curious people will find the option in the settings and thus be able to reenable this quest deliberately (after having read a short information text like "Beware: You often cannot determine reliably if a way is lit when it's bright outside!" or similar).

The cycling cat

**Comment by HaasJona** [comment]
I just got asked if https://www.openstreetmap.org/way/15239550 is lit. This is difficult to say during the day, the nearby street has lamps, but it's difficult to say if they reach that far.

Maybe consider ignoring short ways that are very near to lit ways for this quest (if possible). Or short ways in general that typically only serve as a connection for routing and aren't really present.

**Comment by DerDings** [comment]
Maybe if a user uses automatic or system given auto-night mode, this could also toggle the "is lit"-quest. This way no extra computing is needed to find out if it is dark at the moment, and the coherence is very easy to see and understand for users.

**Comment by peternewman** [comment]
Being pedantic, as I think I said in one of the related quests, if you checked at night you wouldn't know if it was lit 24/7 or just at night...

**Comment by RubenKelevra** [comment]
Maybe we should just add a quality of street lighting quest?

I mean you can always check the physical presence of street lamps but the quality of the lighting is only visible at night. 

The corresponding tag for this is `lit:perceived` which offers 5 different options:

- none
- minimal
- poor
- good
- daylike

**Comment by cyclingcat** [comment]
Apart from the fact that lit:perceived is rarely used (according to [taginfo](https://taginfo.openstreetmap.org/keys/?key=lit%3Aperceived#values) less than 500×, and "lit:perceived=none" exactly 0×): The whole "lit" thing is getting increasingly complicated with LED street lamps getting more and more widespread. These days old lamps are going to be replaced by LED lamps with "smarter" possibilities: more targeted illumination of ways, brightness dependent on daylight, motion detectors that distinguish between humans and cats, combinations of all this - those of you with reading skills of German could read [this article](https://energiewende.baden-wuerttemberg.de/projekte/kommunen/tuningen-geht-ein-licht-auf-mit-intelligenten-led-strassenlaternen) by the Minstry of Energy of Baden-Württemberg - be prepared to be astonished what's possible and what you can expect in the wild - and as a surveyor it's very hard if not impossible to find out how a lamp really works.

So any tagging more precise than "lit=yes/no" will be more and more a pure guess.

The cycling cat

**Comment by RubenKelevra** [comment]
I live in Germany and never encountered a smart street lamp. I mean, they might exist somewhere... but I doubt they will catch on any time soon.

On the other hand it's easy to categorized the elumination level of a street or a path while it's night time.

I don't see a reason why we shouldn't use a documented tag - regardless of the wide spread use. It's always been the nature of OSM that new tags has to be used before they get accepted wide spread.

And since there's currently no easy to use tool to tag this information, it's obvious that it's difficult to capture this information on the ground. 

On the other hand there are many people who have fear walking in dark roads at night. So an routing app which can route on a brightly lit path could be very helpful.

**Comment by rouelibre1** [comment]
Would it be feasible to increase the frequency of this question being asked again only for users who have enabled this quest only at night ? 

This way it would increase the chance of these users correcting the information by users during the day ?

**Comment by W-T-Developer** [comment]
It might also be a good idea to hide quests for surface during the night.

**Comment by HaasJona** [comment]
> It might also be a good idea to hide quests for surface during the night.

I don't think it's a problem to distinguish surfaces at night at all, especially if the road is lit, but it should be no problem otherwise, too. I mean even if it's super dark, you have a smartphone, which probably has a flashlight. And if you're not seeing anything, might as well disable all quests at night.

**Comment by codeinabox** [comment]
I too would like an option to enable the "is lit" quest only between sunset and sunrise as I find it difficult to accurately answer this question during day time.

**Comment by mnalis** [comment]
@codeinabox you can always go to `Settings` / `Quest selection` and enable `lit` quest only when mapping on night... It's a few clicks (might be even less if one day presets or something similar are implemented)

**Comment by matkoniecz** [comment]
one of things that I considered was how to handle enabling/disabling such quest

- dropdown with three states would be obnoxious, unusual and cruel
- another idea would be to block this quest completely during day (impossible to override this new feature)
- or have two entries in quest setting list - one for night only (enabled by default), one for day only (disabled by default). Maybe second should be for entire day. Maybe even have them implemented internally as two separate quests?
- another idea that allows to configure but is to have additional line "enable only during night" with own checkbox

**Comment by peternewman** [comment]
> "two separate quests, one active 24h, one only during night" are my favorite. Second would require some new extra property with text shown only in a quest enabling/disabling menu.

That seems a sensible fit to me, and would avoid more standalone config which we all know @westnordost hates! 😄 It also immediately fits into presets if someone wants to disable say road surface in the dark as they can't see it.

I'll leave this comment here again regarding disabling entirely during the day:

> Being pedantic, as I think I said in one of the related quests, if you checked at night you wouldn't know if it was lit 24/7 or just at night...

One question, if the two quests overlap (i.e. 24 hours and night only, rather than night and day quests), does the new offline update stuff handle that so you wouldn't get the question asked for a second time immediately afterwards if you're answering it overnight.

Also remember there are separate bus and sports field lit ones which presumably want the same behaviour applied (and might lean more towards a config option rather than needing to toggle multiple quests and duplicate them).

**Comment by matkoniecz** [comment]
> does the new offline update stuff handle that so you wouldn't get the question asked for a second time immediately afterwards if you're answering it overnight

yes, AFAIK it is smart enough to handle invalidation of quest caused by answering a question and changing tags 

> 24/7

In my experience it is clear from context (for example, in tunnels), but tagging scheme is badly invented here anyway AND this distinction is of quite low importance...

**Comment by mnalis** [comment]
>  block this quest completely during day (impossible to override this new feature)

please, anything else! Maybe it's just me, but I very much dislike when app behaviour changes automagically behind users backs (and especially if users cannot override that magic).
 
>   or have two entries in quest setting list - one for night only (enabled by default), one for day only (disabled by default). Maybe second should be for entire day. Maybe even have them implemented internally as two separate quests?

_If it has to be done_ (which I'm not convinced of), I'd tend towards this option only **_if the `lit` was the only quest_** candidate for this, but I actually feel that [now that user definable presets are ready](https://github.com/streetcomplete/StreetComplete/tree/quest-profiles), they alleviate the need for all that added complexity, while offering more functionality at the same time, eg.:

- User wants `lit` quest to be displayed always (or never)? They can simply enable (or disable) it in their default profile
- User wants `lit` quest to only be displayed on night? They can create profiles `day` (which has `lit` quest disabled) and profile `night` (which has `lit` quest enabled) and switch between them at will.
- User wants `lit` quest enabled only during night, and `surface` quests enabled only during day? Same solution as above, two simple profiles.
- User wants `lit` quest enabled only during night, and `surface`  and `roof_type` quests enabled only during day? Same solution as above, two simple profiles.
- User wants to enable night quest after 8pm, or 11pm? With user profiles, it is simply their choice when to switch (instead of having automatics with different options for when to switch, or automatics with override controls etc)
 
The **only extra functionality** That I see that this issue might offer (as opposed to user presets, which are already implemented and work fine, even if not officially released yet) is **possibility of automatic enabling/disabling** (instead of user having to choose which profile they want), but it invokes a lot of problems on it's own:

- are users actually better served by application making changes behind their backs? Are they at least going to be notified (by a dismissable dialog) when entering the app if the setting changed since they last used the app? How about if it happens while they're in the middle of session when such a change happens? If not, it is likely going to very confusing. 
- **when exactly** is the night?  civil/nautical/astronomic night?
- how do different communities turn on/off street lighting (I'm pretty sure it is not the same, even in different parts of Croatia they turn on with at least two-three different standards (one at automatic [twilight](https://en.wikipedia.org/wiki/Twilight) sensor , one on fixed timer which programming only changes twice a year together with DST, and one seems to be at fixed timer which only seems to be on in deep night, not in regular post-dusk / pre-dawn  regimes)
- some `lit` quests can only be answered during the day as mentioned before (like `24/7` and _maybe_ `automatic`).
- how about countries that are closer to the pole (like north of Norway), which don't have real night for several months in a row? And have [nights that last for more 24 hours](https://en.wikipedia.org/wiki/Polar_night)?
- extra options (and thus complexity) so user can override wrong guesses by app

**Comment by georg-d** [comment]
> Why shouldn't a road not be lit at all if there are street lamps physically present? If there is a traffic light (for example, visible on satellite imagery), you would also assume that it is in service, wouldn't you?

For the road below the latern, I usually share your experience, but for other features like driveways, footways, cycleways, sport fields, etc it's a different story. From https://github.com/streetcomplete/StreetComplete/issues/2726#issuecomment-827032302 At day time, I can often not tell "sufficiently reliably" where the latern's light shines to (angel of light emittance and shades by houses/trees/embarkments/...) and sometimes like badly maintaines ways or private ways I can't even predict whether a latern is still in use at all (is it in working state? switched on?). All of this especially in rural areas (globally) and/or poorer regions like Cambodia or India. Hence, I quit/skip maybe a quater of "is this feature lit?" instead of just doing rough guessing.

**Comment by matkoniecz** [comment]
> The physical presence is the only thing that is easily verifiable for a surveyor. After all, street lamps may be on not from dusk till dawn but only a few hours - quite difficult to verify.

Recently I encountered opposite problem - someone wanted to answer `lit=no` for footway because they missed street lamps above it
