### ISSUE TITLE
Highlight roads that have a quest

### ISSUE THREAD

**Issue by misibacsi** [streetcomplete/StreetComplete#1576]
**Use case**

When you have a longer road, and the quest is: "add road material", its icon goes off the screen when you zoom in to add this info.

**Proposed Solution**

Move the quest icon towards the center of the screen, to be visible. It may reside at the edge of the screen.

**Comment by westnordost** [comment]
But why?

**Comment by misibacsi** [comment]
If you use the "position lock" function (I guess most users use it, when walking on the streets), the quest icon disappears, if the icon is a bit far from the center. So you have to zoom-in, unlock position, move the cursor to see the icon, then tap it to use. Then use "position lock" and zoom-out again. 
This process would be unnecessary if I would see the icons all time. 

When you are in a zoom-in state, you see a small portion of the map, so there won't be too much icons on screen.

**Comment by westnordost** [comment]
But why would you want to see the icon of the quest you currently have open? The geometry is already displayed after all.

**Comment by misibacsi** [comment]
When I walk, I see on the map a quest icon. I use "lock position", and zoom-in a bit to see the icons, so when I get closer to the scene, the icon disappears, I cannot tap on it. 

If I would zoom-out to see the icon, the icon disappears, probably because the zoom-level.

So 
1. I have to release the "lock position", 
2. zoom-in, 
3. move the cursor to the probable place of the icon (along the road), and 
4. THEN I can tap the icon to open it

**Comment by flera** [comment]
I agree with @misibacsi. I move on a bike, and sometimes I miss a quest because the road is so long, that the icon does not appear on the screen. I think wrongly that there is no quest for this street. Yet, passing this street (or crossing it at one end) I can easily answer quests associated with this street.

**Comment by westnordost** [comment]
Ah ok, so before you open the quest. But what I still don't understand is why with luck position on, you first see the pin when further away and then not anymore when you are closer.

**Comment by westnordost** [comment]
For certain quests, the pins are shown at the ends of the way, i.e. for the street name quest. For others, like the surface quest, it's shown in the center.

**Comment by flera** [comment]
Maybe the pin position can be flexible and try to position it on the part of the road that is visible depending on the zoom level? and not stuck in the middle of the road?

**Comment by misibacsi** [comment]
I also mean the surface material. Its icon is always stuck at the center of the road, which is not useful. Be it flexible and visible, please.

**Comment by westnordost** [comment]
Ok I understand the issue.

Though, I think this is not solveable for technical reasons.

Making the pin position flexible is unfortunately technically not possible. Showing the quest pin on the border of the screen if it is outside the screen is maybe possible, but not really, because it would be very very slow.
The blocker is a bit the map rendering library I use, though even with Mapbox, it wouldn't be possible in a reasonable way.

**Comment by peternewman** [comment]
Hi @westnordost ,

Firstly I really like the app, it's really neat.

I've hit this too quite a few times. A few questions/thoughts towards a solution?

I'm assuming the current "surface" ones are positioned in the middle of the way, whereas speed limit is positioned just in from the ends at either end of the way?

Can you find the length of the way? If so could you go for speed limit style quests at either end when they way is longer than x metres. Even better if it's also tied into the zoom level. If it's really long you could even add it to ends AND middle.

Can you find how much of the way is on-screen using the library and render the quest at the middle of the on-screen part?

If you can't do anything complicated, rendering them all like the speed limits would generally improve things (or possibly with the ends AND middle, but I appreciate that might get busy for lots of short ways).

My use case is when I walk down a main road, I can see the road surface for the side roads easily from where I'm walking, but it relies on the quest being on my screen at that zoom level to know there is one to answer.

**Comment by westnordost** [comment]
Yes, the speed limit quests are positioned at the ends, the surface one in the middle. It is a setting in the quest type: The street name is usually found at the end(s) of the street, while to be able to answer the surface quest, one usually needs to go through the whole or at least half the way to confirm that the surface is really the same for the whole way. From my experience, when peeking into a street from the main street, it is not possible to see that the surface stays the same even further down the road.

**Comment by peternewman** [comment]
In the UK a lot of the side roads are only a couple of hundred metres long or shorter, so you can easily look down that distance. Even more so for street lighting. You're saying you need to travel most of the length of the street to confirm the surface, but then the speed limit one gives lots of warnings to ensure you've travelled the whole length of the street but still makes it easily visible (I guess because the signs are at the end).

I think the other half of it is visibility of quests as mentioned in #871 . If there is a grid type street layout, I might choose to walk another way to complete a quest if I can see it, and it's not going to take me much longer.

**Comment by rugk** [comment]
> In the UK a lot of the side roads are only a couple of hundred metres long or shorter, so you can easily look down that distance

But in this case, it also hardly makes a difference whether you place the marker at the start or middle of the road, if it is that small anyway.

**Comment by misibacsi** [comment]
**Proposed Solution**

Change the color of the road, if there is active quest on it. 

Color: a lighter blue
(when you press the quest icon, the color of the road changes into a darker blue)

**Comment by westnordost** [comment]
Hmm, this would maybe be possible, but not sure if this wouldn't rather confuse users. Someone would need to try this out.

**Comment by peternewman** [comment]
> But in this case, it also hardly makes a difference whether you place the marker at the start or middle of the road, if it is that small anyway.

Perhaps it's the size of my phone screen 4.6" and 1280 x 720, but if I zoom right in (which I seem to need to do to see some of the node based quests, I can then easily lose a side road that's easy enough to see from the edge.

@misibacsi 's idea sounds like a good solution and presumably simpler than moving the quest icons dynamically, as long as it doesn't slow it down too much.

**Comment by Helium314** [comment]
> Someone would need to try this out.

I've been using this in my personal fork for a while now.
In general I like it a lot, especially for really long ways. But in some areas with many quests it's a bit "too much". And I really can't tell whether it might confuse users...
![1](https://user-images.githubusercontent.com/43007630/155222302-f36f63b7-ed67-4103-a5a0-ed4117efcf96.png)
![2](https://user-images.githubusercontent.com/43007630/155222308-29d88caa-4c1f-45fe-9f77-e493aedeafd2.png)

**Comment by mnalis** [comment]
@Helium314 So ***that's*** what's been going on with all that extra line coloring in your fork! Seem much more useful not that I know what it indicates; I was writing it up to an somewhat eccentric rendering style preference :smile: 

But yeah, I guess it would be confusing to new users, especially if they are in sparsely-mapped areas with lot of way quests.  Another preference to put in [expert mode](https://github.com/streetcomplete/StreetComplete/issues/471), eh?

**Comment by Helium314** [comment]
I have it in the readme, and an option to toggle it, and I thought it would be clear after solving a quest that makes the lines go away :smile: 
But obviously it isn't, even to you who is quite interested in all kinds of additional features... so it would definitely confuse a lot of users!

> But just changing the intensity of the color of the unsolved way would IMHO be much less confusing then this painting new lines over old ones (of possibly different width!), I think.

Less confusing, but maybe still too much...

**Comment by westnordost** [comment]
Hm yes, I too find it confusing. I'd not want to include this in vanilla.

**Comment by matkoniecz** [comment]
Also for me, even if I know exact meaning it is a but confusing.

It would be definitely confusing for someone new.

@Helium314 Big thanks for testing this idea!

**Comment by peternewman** [comment]
> I thought it would be clear after solving a quest that makes the lines go away

Remember that doesn't happen a lot of the time, you solve surface and lighting appears etc.

The multiple pins thing on long ways has been implemented since this at least.

I must admit, I think I'd probably like it. Often ways have been split into non-obvious parts e.g. due to changes along the way for some reason, so trying to tell what's going on from the pins alone is another Kim's Game of memory. Whereas highlighting paths/roads that comprise the unanswered quests would help with the Travelling Salesman Problem aspect of mapping ( https://en.wikipedia.org/wiki/Travelling_salesman_problem ); although you might still need to select each pin to work out which route you need to take at times.

Maybe this would be a good thing for layers ( #2461 )? To highlight all roads without lighting tagged (or whatever), so you could walk them and tag it.

**Comment by Helium314** [comment]
> The multiple pins thing on long ways has been implemented since this at least.

I think multiple pins are only shown on ways of 500 m or more, which were not shown before... but anyway, highlighting still helps a lot with unusually shaped ways, e.g. where a foot path on a crossing is actually the separately mapped sidewalk on both sides of the street (plus the crossing).

Actually on high zoom levels, also areas are highlighted. This is useful to avoid missing quests on houses when the zoom is at maximum for displaying all / most quests in an area with high quest density. But it can be rather annoying for large squares, shopping centers, ... where it's hard to find the 'central quest' to make the blue glow go away.

> Maybe this would be a good thing for layers ( #2461 )? To highlight all roads without lighting tagged (or whatever), so you could walk them and tag it.

UI concept looks like it's planned already.
