### ISSUE TITLE
Ask about surface of sidewalks marked as tag on the road

### ISSUE THREAD

**Issue by matkoniecz** [streetcomplete/StreetComplete#1593]
### General
Affected tag(s) to be modified/added: sidewalk:*:surface tag family - see https://wiki.openstreetmap.org/wiki/Key:sidewalk

Question asked: **what is the surface of sidewalks?**

### Checklist
Checklist for quest suggestions (see guidelines):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary 
- [ ] 💤 Not an overwhelming percentage of elements have the same answer (No spam) - this may be the largest problem
- [x] 🕓 Applies to a reasonable number of elements (Worth the effort)

### Ideas for implementation

**Element selection:** 

**Metadata needed:** 

**Proposed GUI:**

Sides interface, the same as for existence of sidewalks

**Comment by peternewman** [comment]
> Sides interface, the same as for existence of sidewalks

Don't you mean the cycle path one? The sidewalk one is only yes/no.

**Comment by matkoniecz** [comment]
"Is there a pavement along this street?" has sides,

"Are pedestrians prohibited..." is yes/no.

**Comment by peternewman** [comment]
Potentially it could be different on either side though. The cycle path one has the option to select from many choices independently for either side of the road.

**Comment by DerDings** [comment]
> 
>     * [ ]  💤 Not an overwhelming percentage of elements have the same answer (No spam) - this may be the largest problem

In my experience the surfaces of sidewalks vary much more than the surfaces of streets. So if the latter is asked for, I don't see any problem also asking for sidewalks.

**Comment by arrival-spring** [comment]
I've been thinking about implementing this, and I think it could be a disabled by default quest, like smoothness.

However, what to do about roads with incorrect sidewalk tagging. There should be an option for the user to fix it or say that it's wrong.

### Option A
Similar to smoothness: add an option in other answers which shows the current tagging and allows to delete it.

#### Pros
* Similar to smoothness
* Clear, easy

#### Cons
* Means we can't deal with all roads with valid sidewalk tagging (i.e. including sidewalk:left and :right and separate for one side)
* Would therefore require exactly the same element selection as sidewalk quest as otherwise data could be deleted and then not fixed in edge cases where there's a path nearby so sidewalk quest doesn't show (albeit invalid data).

### Option B
Have options in surface list for each side to select either "no sidewalk at all" or "separate" in addition

#### Pros
* Allows to add surface for any road with valid sidewalk tagging
* Allows fixing of sidewalk tagging for any road

#### Cons
* Maybe inconsistent? But it is similar to how cycleway quest works
* Implementation might be a bit more complicated as there would need to be a new type, rather than just using the surface list

### Option C
Change sidewalk quest to allow for sidewalk:left and :right and allow to say that sidewalk is mapped separate for each side individually.

I don't like this option though.

Any thoughts before I do anything?

**Comment by matkoniecz** [comment]
option D: in such case user should leave note

**Comment by Dimitar5555** [comment]
I see a potential problem in some places where a single sidewalk can have more than one surface even in very short segments. For example [the left sidewalk on this street](https://www.google.com/maps/@42.6995829,23.3041785,3a,75y,344.76h,82.67t/data=!3m6!1e1!3m4!1sz_vYU0YQQ6i0NLVrCFhyNQ!2e0!7i16384!8i8192) which goes from asphalt to a few different kinds of paving stones, asphalt again, paving tiles and asphalt (again). The right sidewalk is quite similar but has a less variety of surfaces. You can try to guess how many times you have to cut this road in order to tag the sidewalks correctly. That's the reason why I think that this quest should be disabled by default and have a warning message when it's enabled.

**Comment by matkoniecz** [comment]
In such case user can answer `surface=paved` and fill an explanation.

**Comment by Dimitar5555** [comment]
> In such case user can answer `surface=paved` and fill an explanation.

What should the user do if the surface changes from paved to unpaved after each house? `surface=yes`?

**Comment by matkoniecz** [comment]
In this case I would likely split way. Or, if it is unpaved sidewalk interrupted by paved driveways - ignore driveways.
