### ISSUE TITLE
3D models

### ISSUE THREAD

**Issue by OSM-Galicia** [streetcomplete/StreetComplete#2205]
For the 3d building models you do represent the building:part if they are taller than the main building but if the building:part are lower or have fewer floors (levels) than the main building you do not represent it, it would be fine, I suppose it is something that does not cost a lot and does not affect performance, since they are already represented but not as they should...

Thanks!

**Comment by westnordost** [comment]
Can you post an example building, best with a screenshot?

**Comment by OSM-Galicia** [comment]
For example, the f4 map shows those things well, here an example location: https://demo.f4map.com/#lat=43.3668114&lon=-8.4205919&zoom=21&camera.theta=47.055&camera.phi=-4.896

**Comment by matkoniecz** [comment]
https://www.openstreetmap.org/relation/11696459 https://www.openstreetmap.org/way/853493334 for OSM objects. StreetComplete screenshot is missing for now

**Comment by westnordost** [comment]
![Screenshot_20201029-233132_StreetComplete Dev](https://user-images.githubusercontent.com/4661658/97639489-f2478500-1a3e-11eb-8854-e573389267e0.jpg)

**Comment by westnordost** [comment]
f4 map
![f4](https://user-images.githubusercontent.com/4661658/97639782-903b4f80-1a3f-11eb-89c6-f2f3d9dc8b6a.png)
osmbuildings
![osmbuildings](https://user-images.githubusercontent.com/4661658/97639799-992c2100-1a3f-11eb-9c6e-1888fc8b3352.png)
streetcomplete (tangram-es with jawg map tiles)
![Screenshot_20201029-233352_StreetComplete Dev](https://user-images.githubusercontent.com/4661658/97639826-a5b07980-1a3f-11eb-9fb8-2b812ea76319.jpg)

**Comment by westnordost** [comment]
The building itself is a multipolygon relation with
```
building=public
building:levels=4
```
All the building parts are correct, though a building part for the building part that runs alongside Gregorio Hernandez is missing. f4-Map and OsmBuildings interpret this missing data differently. OsmBuildings concludes that then there can be no building, F4-Map concludes that then it must be also 4 building levels.

@Joxit could this be a problem with the tiles? The data for the tiles look like this:

![jawg](https://user-images.githubusercontent.com/4661658/97640474-1b691500-1a41-11eb-9d15-f1b316a3c0e9.png)
I think if a building part exists, `extrude` should not be true for the building outline?

**Comment by Joxit** [comment]
Hi there,
We try to have as many buildings as possible with different heights. Unfortunately the `height` property is not always present in OSM.
In some areas, contributors use the `building:levels` property because they don't know the actual height of the building.

So we chose to do this to determine the height:
- When `height` is available, we use it
- When `building:levels` is available, the height will be `building:levels` * 3 (because one level ~ 3 meters)
- Default height is 3

This building has 4 levels... So the height will be 3 * 4 = 12.

I don't know when polygon/multi polygon with `building:levels` is a outline or not... So I can't set the `extrude` to false.

> If there is no type=building relation, an application should treat all building parts within the area of the building outline as part of that building.

[from wiki](https://wiki.openstreetmap.org/wiki/Simple_3D_buildings)

We do not do this because it could have a negative impact on the rendering time of our tiles. But we could still investigate and see the real impacts.

**Comment by matkoniecz** [comment]
> I don't know when polygon/multi polygon with building:levels is a outline or not...

Is it feasible to check for `building:part=*` areas inside?

**Comment by Joxit** [comment]
> We do not do this because it could have a negative impact on the rendering time of our tiles. But we could still investigate and see the real impacts.

I will do some research/experiment on this

**Comment by westnordost** [comment]
Here is a performant point in polygon algorithm in case you are looking for one. 

```java
// Copyright 2000 softSurfer, 2012 Dan Sunday
// This code may be freely used and modified for any purpose
// providing that this copyright notice is included with it.
// SoftSurfer makes no warranty for this code, and cannot be held
// liable for any real or imagined damage resulting from its use.
// Users of this code must verify correctness for their application.
// http://geomalgorithms.com/a03-_inclusion.html

static boolean isPointInPolygon(Point p, Point[] v )
{
	int wn = 0;
	for (int j = 0, i = v.length-1; j < v.length; i = j++) {
		if (v[i].y <= p.y) {
			if(v[j].y > p.y) {
				if (isLeft(v[i],v[j],p) > 0)
					++wn;
			}
		} else {
			if(v[j].y <= p.y) {
				if (isLeft(v[i],v[j],p) < 0)
					--wn;
			}
		}
	}
	return wn != 0;
}

private static long isLeft(Point p0, Point p1, Point p)
{
	return (p1.x - p0.x) * (p.y - p0.y) - (p.x - p0.x) * (p1.y - p0.y);
}
```

Though of course if you are going to do something like that, it doesn't matter how performant that algorithm is if you don't sort the buildings first into some kind of spatial data structure (i.e. "spatial index") like a quadtree or raster in order to reduce the number of PIP-checks you need to do

**Comment by westnordost** [comment]
So anyway, I think it makes no sense to leave this issue open. There is nothing that can be done about that in this project. The map tile provider (Jawg) is informed about this problem, maybe they will do something about it, maybe they won't.

I can very well understand if to fix this is not very high on JawgMaps' priority list, [given that MapBox GL JS, a framework on which JawgMaps heavily relies on is no longer open source](http://weeklyosm.eu/archives/14064#wn543_23951), they have other worries right now.

**Comment by Joxit** [comment]
Hi there, I hope you are doing well ! It's been a loooong time I know, 2021 was busy with [partial satellite imagery](https://blog.jawg.io/satellite-imaging/) and 2022 many stuff [about geocoding](https://blog.jawg.io/introducing-jawg-places-js/) and stuff I didn't write about it yet.

Anyway, I had some time for this issue and I published a new version of our streets-v2 tileset. We should support more cases when there is an outline. I don't think we have a 100% coverage, but if we have 80% it's enough for me :smile: 

You may see a difference from 24h to 48h
