### ISSUE TITLE
Scalebar

### ISSUE THREAD

**Issue by adrienandrem** [streetcomplete/StreetComplete#2376]
**Use case**
On areas with not much data, it is difficult to know at which scale the map is displayed and the distance between objects and your position.

**Proposed Solution**
Display a scalebar on the map.

**Comment by matkoniecz** [comment]
Can you give example of a quest where it causing problems? I am not editing in such regions, so I am likely missing something.

**Comment by adrienandrem** [comment]
I don't recall a precise example, nevertheless, [like orientation, scale is quite necessary on a map](https://www.gislounge.com/whats-in-a-map).  
It is displayed on [openstreetmap.org](https://www.openstreetmap.org), JOSM, OSMAnd and MapSwipe for instance.

**Comment by matkoniecz** [comment]
Note that while StreetComplete is using map as significant part of the interface it is not intended to act as a map or navigation software.

It also differs quite significantly from paper maps by 

(a) showing current position of user - what by showing movement acts as substitute for scale.
(b) being extremely limited in available space, paper maps as small as smarphone screen are extremely rare

Due to limited space one of critical parts of mobile design is pruning and removing everything that can be removed.

> https://www.gislounge.com/whats-in-a-map/

Note that title and legend is also missing - because there is no space to fit it.

**Comment by peternewman** [comment]
I was going to open one for this before, I'm not sure I ever found this one though. I was searching for scale.

If you're answering an existence check for example, then scale is important, is it this bench or not (how close is the next one).

> It also differs quite significantly from paper maps by

Also being able to zoom in and out trivially, therefore throwing out any innate knowledge of scale. I got caught out by this on a paper map as they're 1:10k in Luxembourg because the country is so small and I kept overshooting as I was used to 1:25k and therefore roughly where you'd expect things.
