### ISSUE TITLE
Cannot answer both the AddTactilePavingKerb and AddKerbHeight directly one after another

### ISSUE THREAD

**Issue by tapetis** [streetcomplete/StreetComplete#2393]
Answering the `AddTactilePavingKerb` and `AddKerbHeight` quests (in this order) directly in succession leads to the following console output:

```
D/OsmQuestUpload: Uploaded osm quest AddTactilePavingKerb for node #ID
D/OsmQuestUpload: Dropped osm quest AddKerbHeight for node #SAME_ID: Conflict while applying the changes
```

As this output shows, the answer to the `AddKerbHeight` quest is not uploaded successfully and is subsequently dropped.

I think this bug may be related to the following code, which for newly added tags (`barrier=kerb`) only checks if the tag already exists, but does not consider if the actual value is in conflict:

https://github.com/streetcomplete/StreetComplete/blob/b2ad06ab617a032f9f721bd64059d814faafcb4e/app/src/main/java/de/westnordost/streetcomplete/data/osm/changes/StringMapEntryAdd.kt#L6

**How to Reproduce**
Answer the `AddTactilePavingKerb` and `AddKerbHeight` quests directly one after the other for a node that has no previous tags. When the issue first occurred and while reproducing it, I had the automatic upload option turned off.

**Versions affected**
v28-beta2

**Comment by westnordost** [comment]
Awesome that you research that deep into the source code, thank you for this!

**Comment by westnordost** [comment]
`StringMapEntryChange` is like a diff. So if the diff is `ADD barrier = kerb`, but the tag is already there, it is currently counted as a conflict because it is trying to add something that is already there. This is very strict.

I am thinking about making it less strict, so that changes that are already applied in exactly manner are counted not as conflict.

The other solution would be to only let one of these two quests add the `barrier=kerb`.
