### ISSUE TITLE
App crash due to SQLiteException

### ISSUE THREAD

**Issue by sjjh** [streetcomplete/StreetComplete#2423]
When started, the app immediately crashes.

The relevant error seems to be:
`12-27 11:52:59.884 E/AndroidRuntime(25304): java.lang.RuntimeException: Unable to start activity ComponentInfo{de.westnordost.streetcomplete/de.westnordost.streetcomplete.MainActivity}: android.database.sqlite.SQLiteException: duplicate column name: quest_types_on_way (code 1): , while compiling: ALTER TABLE osm_split_ways`
See CatLog excerpt filtered for _streetcomplete_: [2020-12-27-11-52-21.txt](https://github.com/streetcomplete/StreetComplete/files/5744544/2020-12-27-11-52-21.txt)

Note: i haven't used StreetComplete for some time, thus the problem might not lay in the latest update itself.

**How to Reproduce**

Just try to start the app. :)

**Versions affected**

SttreetComplete 28.0
Fairphone 2 with latest Fairphone Open (Android 7.1.2)

**Comment by westnordost** [comment]
Hmm, can't see how it is possible that this happened. On the 12th of July 2020, I added a column to the `osm_split_ways` table and added the necessary code to upgrade existing databases.
- It was all done in one commit to the repository.
- During testing this, there was no problem with it. 
What must have happened in your case is that the database was created with the table already containing the column but the version number of the database suggested that it that table doesn't have that column yet. In other words, the version number of your database was wrong. No idea how this could have happened and very difficult to research this after the fact (after all, this is 6 months back). Because of this, I'll close this.

To solve this, you need to delete the data (or reinstall) the app.

**Comment by sjjh** [comment]
It might be, that I haven't used the app since July. If the upgrade code got lost/refactored and changed behavior in the meantime, maybe that led to the issue.
Thanks for your fast reply, reinstalled the app an can now continue mapping. :)
