### ISSUE TITLE
Don't ask for adress in France

### ISSUE THREAD

**Issue by letypequividelespoubelles** [streetcomplete/StreetComplete#2427]
Hi everyone, 

After  discussion on the french OSM telegram chat, it appears that in France it is prefered that address are put in a node in the polygone, and not put to the whole building/polygone. 

So the quest asking for address would create doublon (adress both in a node and in the building), and is therefore not very usefull in France, so it should be desactivated for France.

Thanks,

**Comment by Atrate** [comment]
Doesn't SC first check whether there's not an address node inside a polygon and if so, doesn't show the quest?

**Comment by matkoniecz** [comment]
> So the quest asking for address would create doublon (adress both in a node and in the building)

It would not, as if there is already address node within building the quest will not be asked.

If it happens - then it is a bug.

**Comment by westnordost** [comment]
How dare you bring the issue count to 80+ again 😭

Seriously, see @matkoniecz . Generally, in the past when people thought they spotted a bug in the app in this regard, it was always that the address node belonging to a building was actually placed just outside the building outline. Thus, an error of the mapper / import.

**Comment by letypequividelespoubelles** [comment]
I didn't want to report a bug, but to say that this quest should be desactivate in France, because the Fr OSM community prefer to have address in a node and not in the polygon. 

>It would not, as if there is already address node within building the quest will not be asked.

Ok, didn't know, but it doesn't change the fact that this quest should be desactivate in France.

**Comment by westnordost** [comment]
How does it not change the fact that it should be dactivated in France? The community in France may prefer to have the address in a node and not in a polygon, yet if there is no address node in the building yet, it is still an improvement to add the address on the building. Community members may later "improve" this data to be on a node within the building outline and the app will still not ask again for the housenumber.

**Comment by westnordost** [comment]
Just a bit of statistics: 16954 housenumbers have been contributed by users in France till now with StreetComplete.

The OSM usernames of those users who contributed more than 100 housenumbers in France are clins, Jean-Louis B, norsud, Antoine Gacioch, user_5589, LE GARREC Vincent, sizeof, Martin Constantino–Bodin, Delhuu, ArnaudJ59, draenog_, lmagreault, Legnac, Elsane62, Lkteru, MadScribble, Valdroff, YogOSM, Zeriss, JerÔÔme, fengalin, postfred, mcorteel, Bigoud' map, kalgan, Landry MINOZA, tbarthelet, lluc, laufor, Zorglub67 (in that order, sorted by contributions).

**Comment by matkoniecz** [comment]
It seems that the actual main problem is different. If I understood right from Telegram discussion, following peculiar tagging is considered as acceptable in France:

https://www.openstreetmap.org/#map=19/48.55114/6.38514

![screen03](https://user-images.githubusercontent.com/899988/103242586-02081a80-4957-11eb-8bd3-552e013100c1.png)

**Comment by westnordost** [comment]
Hm, a pity. If this is commonplace and accepted, then I guess the quest should be disabled for France. Situation is then a bit like in Italy: https://lists.openstreetmap.org/pipermail/talk-it/2018-July/063712.html

Do you have the link to the telegram discussion? (Is this possible?) There should be some public discussion that can be referred to later, f.e. on the mailing list, French forum, OSM forum wiki or any other public platform. See https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/housenumber/AddHousenumber.kt#L23-L29

**Comment by matkoniecz** [comment]
I appeared in https://t.me/osmfr/26367

Discussion seems to start in https://t.me/osmfr/26320

If I understand correctly https://t.me/osmfr/26373 was giving this place as example of a valid tagging (there is a bit of language barrier)

Directly linked message seems to be publicaly viewable, to see context you need to run Telegram and give them your phone number :(

**Comment by pyrog** [comment]
A very short explanation: https://github.com/osmandapp/OsmAnd/issues/9976#issuecomment-751955082

**Comment by cquest** [comment]
Yes, this kind of tagging is OK, and even recommended at least in France.

Why ?

**Addresses and buildings are two completely different things**. In fact, you must add another kind of object in this game: land registry parcels, something missing in OSM which maintains the link between addresses and buildings.

**addresses / buildings / parcels have a 0-N relation between them.**

A building can be linked to no address up to multiples ones.
An address can bring you to several buildings.
etc...

We had this discussions many many times in the french community as we massively worked on addresses in France in OSM since 2014 by creating an open addresses database (BANO) built from extraction of cadastral data, some local opendata and OSM addr:*.
This pushed french authority to partly open the national address database in 2015 then fully last year.

**An "house" number should be in fact considered as a "street" number**, an index on the street path to stop (that why they are generally ordered), in order to move from public area to a private area (parcel) where you'll find building(s) and possibly POIs.

I don't know why the direct relation between addresses and buildings is so prominent in the OSM world, maybe it comes from the first address or building footprint data opened that got imported, or from a dense urban view or because we miss a piece in the puzzle: land registry parcels (I'm not saying we should add them in OSM, just mention them as the missing link).

**Comment by matkoniecz** [comment]
> I don't know why the direct relation between addresses and buildings is so prominent in the OSM world

In many places address is perceived as assigned to building, and people would say "my house has address XYZ", not "my plot has address XYZ".

**Comment by matkoniecz** [comment]
> A building can be linked to no address up to multiples ones.

Multiple nodes solve that, and in general at least all habitable buildings have address. At least in countries known to me, I would expect it to be true in general, at least outside dysfunctional countries (outside slums).

> An address can bring you to several buildings.

Yes, sometimes address must be tagged on area (for example https://www.openstreetmap.org/way/234723781 )

Neither really answers why tagging address outside building would be a good idea - I just want to register that it seems poor and weird decision to me.

**Comment by cquest** [comment]
- "my house has address XYZ", should be "my house is located at address XYZ"... we also say "my address is XYZ" which is very simplified view that everybody understand but doesn't match reality.

- When there is no building at the address (a surface parking)... the address is obviously not a building polygon.

- "All habitable building have address": this is not the case, we still have many municipalities in France in that case (which is causing troubles, and solved VERY slowly)

**Comment by pyrog** [comment]
> Multiple nodes solve that

Of course, yes. So we (try) to do this for each "street number" 😃 


> sometimes address must be tagged on area

In France, **no**.


> Neither really answers why tagging address outside building would be a good idea

This is how address are in France 😉 

In practice, "street numbers" aren't "lost" outside buildings, (in country side) they are on pillar near the gate of the fence.
In cities, they are on the building facade, near the entrance.

Addresses are used by postman, policeman, nurse, fireman, delivery man…
They should be at the real place (where the blue plate is), usually near or on top of the entrance, or near or on letter boxes.

Also an OSM golden rule is "map what you see" : so we map the blue plate as a node 😉 


> I just want to register that it seems poor and weird decision to me.
> But obviously my France knowledge is extremely limited, so maybe I am missing something.

Yes, you miss something.

**Comment by cquest** [comment]
In some countries, addresses maybe be given directly to buildings by the authorities, the logic maybe be different, but don't make it a generality.

The logic in France is really the "index on the street", then a parcel is accessible thru these, then building are located on the parcel, and may have building names or numbers (Bâtiment A/B/C, Bâtiment Einstein/Kelvin...) which are not given by authorities.

OSM address model is flexible enough to allow different logics and editors should respect this flexibility and not put one logic on top of others.

**If StreetComplete cannot support more than the building linked address logic, it should disable this kind of quest in countries where another logic is in use (like France).**

**Comment by pyrog** [comment]
> Yes, sometimes address must be tagged on area (for example https://www.openstreetmap.org/way/234723781 )

In France, hospitals… have a physical address (usually a node at one of it's entrance) and a postal address.
We use `contact:housenumber`… when we want to specify it (i.e. [Centre Hospitalier Saint-Joseph Saint-Luc](https://www.openstreetmap.org/relation/4013062)).

> This pushed french authority to partly open the national address database in 2015 then fully last year.

https://adresse.data.gouv.fr

**Comment by pyrog** [comment]
Thank you very much 😃

**Comment by davidpnewton** [comment]
Well that is an extremely silly way of doing things.

Do house numbers always correspond to a building and one building only? No. Sometimes there are many flats within one building. Sometimes one address covers many buildings. For those circumstances then it's perfectly reasonable to apply the address to an area or to nodes representing particular flats etc.

However those are NOT the situations which apply to most houses. Most houses are a single building which has a single address. 2 bis, rue example is technically the cadastral plot. Practically speaking however the cadastral plot and the building occupying the cadastral plot are one-and-the-same for addressing purposes in the vast majority of cases. In those circumstances the address should be tagged to the building, not some kind of random node. If not tagged to the building, then if the cadastral plot is the entity then tag it to that. Good luck verifying the exact boundaries of a cadastral plot via a survey though.

Extremely silly retrograde step.

**Comment by pyrog** [comment]
> Well that is an extremely silly way of doing things
.…
> Extremely silly retrograde step.

Thank you for your respectful response 🙁

This choice is a **consensus** of the french community after years of discussions around the [national address database](https://adresse.data.gouv.fr) 😉

**Comment by matkoniecz** [comment]
@davidpnewton Feel free to discuss it with a French community but it is a poor place to reach them - see https://community.osm.be/resources/europe/france/

And apparently it was discussed and is considered as a valid tagging, so I would not expect this to be changed just because someone told them that it is silly.

**Comment by Marc-marc-marc** [comment]
>this quest should be desactivate in France, because the Fr OSM community prefer to have address in a node and not in the polygon.

that's 3x not true : 

1. telegram isn't the main osm-fr channel. so 2 ppl talking about that on telegram is not more not less than 2 ppl taliking about that. if this quest is disliked by 2 ppl, those 2 ppl just need to uncheck this quest box
2. a possible problem with this quest was never discussed at the community level, no one ever said that they felt there was a problem and that it needed to be changed
3. node and area are both existing and valid tagging for addr:housenumber. yes some (2) oldold contributors talk about the purity of addrs nodes located in an indeterminate place. others do it on areas because in 99% of the cases it allows to determine the address of a building (which is a common use) and to have a routing that does not depend on the arbitrary position of a node according to the mood of the contributor (very problematic case for big buildings with several access routes, sometimes for several different modes of transport)

for all these reasons, the deactivation of the quest in france seems to me unnecessary and even counterproductive since it would lead users to make a note for each number, which is already seen sometimes... and much more useful than the node<>area debate, given the amount of unsolved notes (sometimes created several years ago), the question that arises is "in osm or not".

**Comment by matkoniecz** [comment]
> telegram isn't the main osm-fr channel

Which one is? I looked at https://forum.openstreetmap.fr/ (based on what is listed in https://community.osm.be/resources/europe/france/ ) and by last post dates it seemed significantly less active.

Note that quest was not disabled due to node vs area, it was disabled based on information that in France placing address node outside building area is considered as OK.

**Comment by Marc-marc-marc** [comment]
> > telegram isn't the main osm-fr channel
> 
> Which one is? 

talk-fr mailinglist (forum interface available via Nabble)

> I looked at https://forum.openstreetmap.fr/ (based on what is listed in https://community.osm.be/resources/europe/france/ ) and by last post dates it seemed significantly less active.

indeed, no real community there, only a few ngo member to reply

> Note that quest was not disabled due to node vs area, it was disabled based on information that in France placing address node outside building area is considered as OK.

yes indeed, it's a poor but valid schema, common in France due to bano-import and cadastre-import :-(
Does this pose a problem of duplication given the impossibility to detect that a floating node is related to this building?
if yes, wouldn't it be possible to simply not ask for an address in an radius around a floating node? it would allow the SC contributor to still add addr:housenumber in the empty zones.

**Comment by matkoniecz** [comment]
>  it's a problem of duplication given the impossibility to detect that a floating node is related to this building?

Yes.

**Comment by westnordost** [comment]
Okay, I suggest that @Marc-marc-marc or @davidpnewton should start a discussion in the (most frequented) discussion platform for France (whichever it is) and make their point there. I'll close this issue again cause this place here is not the right place to discuss it. Feel free to open a new ticket once the discussion came to a close.

Helpful for an argument (in favour of enabling the quest for France again) would be, to collect information beforehand about the current de-facto housenumber situation in France:
- How many addresses are mapped on areas (buildings, other areas) if any, how many on nodes?
- How many addresses float free, not contained in any building?
To gather this information is probably not trivial to do, but I think necessary to have an argument based on statistical facts rather than and opinions (how things should be done) and random samples. Maybe I can help if you can point me to a data source where I can get all elements in France with `addr:housenumber` (overpass would probably run into a timeout?).

For an argument about the tagging guidelines for housenumbers in France, I'd add that 
1. the tagging guidelines as described by @cquest are certainly consistent and make sense
2. but makes it much harder to associate addresses to POIs (shops, offices, amenities, ...) and houses for data consumers. Data consumers such as web maps usually want to show the address of a business or shop you search for, f.e. Google Maps always shows the address alongside the telephone number etc.
3. and makes it much harder to contribute housenumbers cause it is much harder to find out where house numbers are yet missing. (F.e. of course they can't be contributed with StreetComplete then). This wouldn't be a problem if all addresses in France were imported from another source, such is the case in Denmark for example. I didn't quite follow whether the discussion here whether it is the case in France or not.
