### ISSUE TITLE
Street crossing island quests only showing during scan (and on edges of scan area)

### ISSUE THREAD

**Issue by dbdean** [streetcomplete/StreetComplete#2430]
When StreetComplete is scanning for quests, crossing island quests show up in my area, but they mostly disappear before the scanning is over. Sometimes they stay on the boundaries of what appears to be the scanning area though. These quests will disappear if I scan an area closer to them, so they are difficult to actually visit and answer.

From discussions when the island quest was implemented, it may be intentional that they shouldn't show because I have most of the footpaths in my area mapped separately to the roads. However I think they should be showing, as many of these crossing in town do currently have islands and I'd like to survey them.

(Perhaps a separate issue) Can we change the above logic to always ask for crossing islands on roads that aren't one-way, or have more than 1 marked lane, perhaps?

Example, crossings just outside scan area:

![Screenshot_20201229-082252](https://user-images.githubusercontent.com/12725310/103244163-38be4f00-49b0-11eb-9bda-e86001a66b71.jpg)

And after a new scan is run centered on this area:

![Screenshot_20201229-082339](https://user-images.githubusercontent.com/12725310/103244193-52f82d00-49b0-11eb-8cd6-f9c7aa4c908a.jpg)

For reference area is Armidale, NSW, Australia.

**Comment by peternewman** [comment]
From what I can see your middle left one in the top image is this node @dbdean :
https://www.openstreetmap.org/node/5391039082

I'd agree I get the same behaviour on some adjacent ones.

It looks like it's getting excluded because this way:
https://www.openstreetmap.org/way/558914148

Matches the exclusion:
https://github.com/streetcomplete/StreetComplete/blob/b3f41229a93d93e498b346d54f83c4a4501344a3/app/src/main/java/de/westnordost/streetcomplete/quests/crossing_island/AddCrossingIsland.kt#L23-L28

See #2030 for some of the reasoning behind it, but I'd agree it does look rather aggressive at filtering out nodes currently.

As to why the others disappear, I'd imagine the way was outside the search box when it's at the periphery, hence it's shown, until you re-center then the way is also found and it gets dropped.

**Comment by westnordost** [comment]
I also looked at the nodes you mentioned. The quest should not be shown for the mentioned nodes because it is a vertex of a `highway=footway`. Why is it still shown during the download process?

Right now, I have no idea!

@peternewman suggested that the footway might not have been part of the download bounding box. But to my understanding, this is impossible, as the OSM API should return all ways who got at least one vertex in the bounding box. So if the vertex is in the bounding box, the way should also be in the bounding box.

![image](https://user-images.githubusercontent.com/4661658/103298744-43520600-49fb-11eb-97f8-7ac0f6bd0c94.png)

**Comment by westnordost** [comment]
Ah of course, thats' how:

![image](https://user-images.githubusercontent.com/4661658/103306567-24a93a80-4a0e-11eb-98d9-66aa9ec0378e.png)

![image](https://user-images.githubusercontent.com/4661658/103306764-ad27db00-4a0e-11eb-8246-f6083ccc951c.png)

**Comment by westnordost** [comment]
Ok I'd say the solution is to not create quests for elements whose center is outside of the download bounding box.

**Comment by peternewman** [comment]
Heh, so I was 180 degrees wrong then! :smile: 

I had a look through the PR when it was created, but looking at @dbdean 's screenshots IMHO its being rather aggressive at filtering to try and avoid spam in some places, those all clearly look like they have the potential to have islands and aren't part of a crossing mapped in detail.

**Comment by dbdean** [comment]
Thanks for the detective work. Now these quests won't be teasing me anymore. However, I think these quests are reasonable in this circumstance, so I think I'll create a new issue to see if we can work out how they can be included.

**Comment by dbdean** [comment]
New quest requesting change in logic to allow for crossing island quests on roads with connected footways is up at https://github.com/streetcomplete/StreetComplete/issues/2454.
