### ISSUE TITLE
Sidewalk quest don't show up for majority of roads, since the maxspeed quest is not enabled (US)

### ISSUE THREAD

**Issue by RubenKelevra** [streetcomplete/StreetComplete#2448]
**How to Reproduce**
We currently have a filter when to show the sidewalk quest, based on the tagged speed.

This conflicts with the not enabled max speed quest for the US, resulting in no sidewalk quests showing up at all - since many streets are not yet tagged with a max speed.

Something similar is true for the lit-quest, which also doesn't show up.

Do we really need to assume, that there's no sidewalk when there's no maxspeed tag? I thought we just want to filter out ways with very low maxspeed.

**Versions affected**
v29-beta1

**Comment by matkoniecz** [comment]
> This conflicts with the not enabled max speed quest for the US, resulting in no sidewalk quests showing up at all - since many streets are not yet tagged with a max speed.

Sidewalk quest has filtering out `maxspeed < 8`,  `maxspeed =5 mph`, `maxspeed=walk`.

Ways without maxspeed are allowed.

So "resulting in no sidewalk quests showing up at all - since many streets are not yet tagged with a max speed." is not correct.

> I thought we just want to filter out ways with very low maxspeed.

That is what happens.
https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/sidewalk/AddSidewalk.kt#L27

> resulting in no sidewalk quests showing up at all

Please, give link to an affected location. I am betting that sidewalk is tagged or that it is filtered out due to separately mapped footways or more important quests are shown.

**Comment by westnordost** [comment]
> That is what happens.
> https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/sidewalk/AddSidewalk.kt#L27

Hm, looking at the filter now, it is pretty useless. Roads with `maxspeed=5` will not be filtered out.

**Comment by westnordost** [comment]
```
and (
  !maxspeed
  or maxspeed > 8
  or (maxspeed ~ ".*mph" and maxspeed !~ "(1|2|3|4|5) mph")
)
```

Does this make sense?

**Comment by matkoniecz** [comment]
I will also filter `RO:urban`, `RU:urban` and similar (see https://taginfo.openstreetmap.org/keys/maxspeed#values )

**Comment by westnordost** [comment]
Hmmm. Wonder if this isn't overding it a little...

```
or source:maxspeed and source:maxspeed !~ .+zone:?([1-9]|[1-2][0-9]|30)
or maxspeed:type and maxspeed:type !~ .+zone:?([1-9]|[1-2][0-9]|30)
or zone:maxspeed and zone:maxspeed !~ .+zone:?([1-9]|[1-2][0-9]|30)
or maxspeed and maxspeed !~ .+zone:?([1-9]|[1-2][0-9]|30)
```

**Comment by westnordost** [comment]
@matkoniecz Look at the commits I've done just now. You alright with this?

**Comment by RubenKelevra** [comment]
Which feedback is required? :)

**Comment by matkoniecz** [comment]
> Please, give link to an affected location. I am betting that sidewalk is tagged or that it is filtered out due to separately mapped footways or more important quests are shown and hiding it. Try disabling all quests except sidewalk one.

As your stated reason ("conflicts with the not enabled max speed quest for the US") does not really work

**Comment by tapetis** [comment]
The changes in commit https://github.com/streetcomplete/StreetComplete/commit/7e1f7da8f88a285bf388eda2d6536c58100fce88 lead to the `AddCycleway` quest being shown in "Tempo-30-Zonen" in Germany. These residential highways are often tagged as `maxspeed=30` and `maxspeed:source=DE:zone30` (StreetComplete tags these streets in the same way). The `NOT_IN_30_ZONE_OR_LESS` filter should stop this quest from appearing for such highways, but because the `maxspeed` key is included in the `MAXSPEED_TYPE_KEYS` list, the `maxspeed=30` leads to one entry in the series of logical disjunctions being true. This is because the key exists and the regular expression does not match the value (it does not include the word "zone").

https://github.com/streetcomplete/StreetComplete/blob/7e1f7da8f88a285bf388eda2d6536c58100fce88/app/src/main/java/de/westnordost/streetcomplete/quests/bikeway/AddCycleway.kt#L332-L334

https://github.com/streetcomplete/StreetComplete/blob/7e1f7da8f88a285bf388eda2d6536c58100fce88/app/src/main/java/de/westnordost/streetcomplete/data/meta/OsmTaggings.kt#L26-L32

https://github.com/streetcomplete/StreetComplete/blob/7e1f7da8f88a285bf388eda2d6536c58100fce88/app/src/main/java/de/westnordost/streetcomplete/quests/bikeway/AddCycleway.kt#L305-L309

**Comment by westnordost** [comment]
Uff, damn, you are right. Would you like to create a PR for a fix? I think your excellent detective work in the code should also lead to that your work is credited in the changelog. (Also, I am still pondering how this can be fixed...)

**Comment by tapetis** [comment]
I am also not sure how to fix this.

However, I want to additionally note that the used regular expression also matches values like `DE:zone:40` or `DE:zone:1000`, because the first alternative from the capturing group already matches the numbers 1–9 and thus the following digits do not matter.

**Comment by westnordost** [comment]
Are you sure about this? https://regexper.com/#.*zone%3A%3F%28%5B1-9%5D%7C%5B1-2%5D%5B0-9%5D%7C30%29

**Comment by westnordost** [comment]
Ah, misunderstanding. Overpass uses the regex operator "~" for "find in". In StreetComplete, the regex operator "~" means "matches"

**Comment by tapetis** [comment]
Yes, you are correct. I did not know that StreetComplete internally uses Kotlin's `matches` function, which implicitly adds a `^` to the start and a `$` to the end of the pattern.

**Comment by westnordost** [comment]
Hm, I see no other way to easily solve this than to remove `maxspeed` there again. Sorry, Romania, Russia :-|
