### ISSUE TITLE
Feature Request: crossing island quests should show up for crossings with connected footways

### ISSUE THREAD

**Issue by dbdean** [streetcomplete/StreetComplete#2454]
**Use case**

As I have mapped most of the sidewalks in Armidale, NSW, Australia (but not in enough detail to map most islands as road separations), I don't get any crossing island quests because of the decision to not show them for `highway`=`crossing` when there is an attached `highway`=`path|footway|cycleway|pedestrian`. I understand this is to avoid getting spammed with highway island quests (as discussed in https://github.com/streetcomplete/StreetComplete/pull/2030) when the islands are mapped in detail, but I think there might be a better way.

**Proposed Solution**

I believe that the connection of a footpath to a crossing shouldn't matter. The characteristics of the road should be what determine if there could be a crossing. For example, see the following section around https://www.openstreetmap.org/#map=19/-30.51435/151.66405 in Armidale, NSW, Australia:

![image](https://user-images.githubusercontent.com/12725310/103490597-11182c80-4e71-11eb-9cb9-1ab7a4764f26.png)

I think that the crossing quest should show up for the green crossings, but not the blue crossings, and the distinguishing characteristic is that Rusden St (and the small service lane to the right) are single-lane one-way roads.

I propose that the quest is changed to show on all `highway`=`crossing` nodes where the road is not one-way. If the road is one-way, I could also see a potential for including it only if it had 2 or more lanes.

**Comment by dbdean** [comment]
I would be happy to have a go at implementing this myself and testing it out in a PR if the general principle seems ok.

**Comment by westnordost** [comment]
The quest was done by @kmpoppe , the original PR is here #2030

Maybe somewhere in the discussion the reasoning behind this filter can be found. I may have a look at it tomorrow.

**Comment by peternewman** [comment]
> I propose that the quest is changed to show on all `highway`=`crossing` nodes where the road is not one-way. If the road is one-way, I could also see a potential for including it only if it had 2 or more lanes.

Two lanes of one-way traffic will still get some false positives at junctions, see for example:
https://www.openstreetmap.org/node/256794584

Probably also at things like motorway/large A road junctions.

Allowing it for three would probably reduce that further, although generally I'd imagine the number of crossings missed by just ignoring for all one-way roads crossing crossings would be low enough to be acceptable and certainly fewer misses than the current situation.

One way roads was mentioned by @matkoniecz in the issue and a query found:
> Maybe skipping crossings on oneway roads would be way to get rid of them (and also of some valid quests)?

The good Markus Göllnitz provided me with an example from Overpass that'll give you the way a node is on: https://overpass-turbo.eu/s/X8E
I'm guessing that that's not implemented in SC as of yet, so some more work would be needed there I think

_Originally posted by @kmpoppe in https://github.com/streetcomplete/StreetComplete/issues/2030#issuecomment-675028709_

@westnordost seemed to favour the more restrictive model, presumably to avoid false positives:
I have another idea that would be more exclusive of such situations where the intersection is mapped in such detail that `crossing:island = yes/no` is irrelevant/unwanted:
Only show quests for `highway = crossing` nodes on roads that do not cross with another way (are an intersection of footway with road), because that is a strong indicator if not a surefire way of finding out that the road+footways have not been mapped the way as depicted in the screenshot.

_Originally posted by @westnordost in https://github.com/streetcomplete/StreetComplete/issues/2030#issuecomment-675038186_

**Comment by dbdean** [comment]
> Two lanes of one-way traffic will still get some false positives at junctions, see for example:
> https://www.openstreetmap.org/node/256794584
> 
> Probably also at things like motorway/large A road junctions.

I think that should get an answer of `crossing:island`=`no`, as it is a two lane road that does not have an island to stop on. That would be useful information for pedestrian routers.

**Comment by westnordost** [comment]
(@peternewman I took the liberty to mark citations as such in your post. It was very hard to read)

**Comment by peternewman** [comment]
> I think that should get an answer of `crossing:island`=`no`, as it is a two lane road that does not have an island to stop on. That would be useful information for pedestrian routers.

In reality, it's actually a three or four lane road with an island, two lanes one way, and one or two the other, it's just it's been mapped in such a way the island is shown (a bit like `ramp=separate`). Unless you think every road with more than two lanes and a crossing should have an island yes/no tag? Admittedly I'm not personally aware of a way to say this way is the island for a crossing.

> (@peternewman I took the liberty to mark citations as such in your post. It was very hard to read)

Oops, sorry @westnordost, thanks for fixing it. I didn't preview or look at it after posting. Having just copy/pasted most of it from other bits of GitHub I rather assumed they would format it all in a helpful way to begin with!

**Comment by dbdean** [comment]
For now, in my [pull request](https://github.com/streetcomplete/StreetComplete/pull/2455), I've just implemented it to ignore oneway roads. I'd guess that multi-lane one-way roads with islands are rare enough that we don't really need to include them in this quest, making that example moot.

**Comment by matkoniecz** [comment]
Closing as implemented by #2455
