### ISSUE TITLE
AddProhibitedForPedestrians quest leads to bad OSM data

### ISSUE THREAD

**Issue by riiga** [streetcomplete/StreetComplete#2472]
The AddProhibitedForPedestrians quests asks users to answer which roads are prohibited or not for pedestrians. I've seen other people in my area answering the quest which adds `foot=no` to roads which may be unsuitable to walk on but which you legally are still allowed to walk on. This causes bad data in OSM since I've already added all such roads in my area according to what is legally allowed, but now more roads are getting those tags while they really shouldn't. I feel this is a mostly a user error, but I think it also lies in StreetComplete and there needs to be a clarification that there should be a sign prohibiting pedestrians explicitly, otherwise no access tag should be added.

The OSM wiki clearly says `foot=no` is the *legal* accesibility.

> Access values describe **legal** permissions/restrictions and should follow ground truth e.g. signage or legal ruling and not introduce guesswork. It does not describe common or typical use, even if signage is generally ignored. 
-[Key:access](https://wiki.openstreetmap.org/wiki/Key:access)

Here are a few examples of the data being added:
https://www.openstreetmap.org/changeset/92125582 (Industrigatan: [Location](https://www.google.se/maps/@58.4118217,15.586051,3a,75y,2.02h,86.81t/data=!3m6!1e1!3m4!1s6BxNhHohs9EGjCY8CZXDFw!2e0!7i13312!8i6656), [nearest intersection showing no sign](https://www.google.se/maps/@58.4185072,15.5911612,3a,25y,230.35h,88.43t/data=!3m6!1e1!3m4!1sH4jDcRwUAE8z0PQvQETQ6A!2e0!7i13312!8i6656))
https://www.openstreetmap.org/changeset/96803039 (Haningeleden: [Location](https://www.google.se/maps/@58.389732,15.6244885,3a,33.8y,119.04h,86.26t/data=!3m6!1e1!3m4!1sKfuxs3Y6XHjUAIMnqvc9Ow!2e0!7i13312!8i6656), [nearest intersection showing no sign](https://www.google.se/maps/@58.3873158,15.6287043,3a,66.5y,344.01h,83.4t/data=!3m6!1e1!3m4!1svEroB2SdnQB_luIFEVjJng!2e0!7i13312!8i6656))
In previous changeset for https://www.openstreetmap.org/way/326363178 ([Location showing no sign](https://www.google.se/maps/@58.4120845,15.6340776,3a,46.9y,343.81h,88.81t/data=!3m6!1e1!3m4!1ss4kGUV5Mdok8jzq_wL1Qqw!2e0!7i13312!8i6656))

I doubt it lies in the translation, in these examples one user is using en-GB and the other sv-SE.

And here's one of my reverts:
https://www.openstreetmap.org/changeset/92373879

**How to Reproduce**
N/A

**Versions affected**
All versions since this quest was added presumably.

**Comment by matkoniecz** [comment]
The question is (without translation):

> Are pedestrians prohibited from walking on this road here?

See https://github.com/streetcomplete/StreetComplete/blob/fecf35f646745a8c5b29339df3a958bcfd46818a/app/src/main/res/values/strings.xml#L716

The same for GB ( https://github.com/streetcomplete/StreetComplete/blob/fecf35f646745a8c5b29339df3a958bcfd46818a/app/src/main/res/values-en-rGB/strings.xml#L1544 )

Do you think that question is not clear enough?

**Comment by GenericError** [comment]
Although it might be implied by prohibited, I think saying "Are pedestrians legally prohibited from walking here" would be a better way to phrase it imo.

**Comment by riiga** [comment]
Yes, I think it is unclear since this edits a tag that wants the legal access while I think most users would answer "Yes, prohibited" if they felt like pedestrians were prohibited unlike the shape of a roof which is a hard truth. Like @GenericError suggested, asking about the legal access would be better, or asking even more explicitly "Are pedestrians legally prohibited from walking here according to a road sign?"

**Comment by smichel17** [comment]
I might flip it around: "Are pedestrians allowed to walk here?" (Or some variant of that) The answer words would be "Allowed"/"Forbidden".

Actually, just changing to those two words instead of "prohibited" (which could be interpreted as 'prohibited by the terrain') might be enough. I think I prefer the positive framing, though.

**Comment by smichel17** [comment]
"Permitted" is a more formal alternative, but it's longer and I don't think it adds any clarity (also starts with the same letter as Prohibited -> possible to mix up).

**Comment by matkoniecz** [comment]
> I might flip it around: "Are pedestrians allowed to walk here?" (Or some variant of that) The answer words would be "Allowed"/"Forbidden".

See also https://github.com/streetcomplete/StreetComplete/issues/1342

**Comment by smichel17** [comment]
Okay, that's all reasonable. My updated opinions would be:

- Best phrasing: Are pedestrians explicitly forbidden from walking here?
- Best confirmation word: "Forbidden"
- Other option: ???
    - Maybe "No" is okay even though technically it should be "Allowed" or "Not forbidden" or similar.

Is there any different tagging for explicitly vs implicitly allowed?

**Comment by westnordost** [comment]
I think that at least for example #2 and #3 that pedestrians are also **legally** (not only by common sense) not allowed on the road. 

If there is a sidewalk that accompanies a road, pedestrians are not allowed on the road. Both Nya Tanneforsvägen and Haningeleden have such a sidewalk, thus it is forbidden to walk on the road. `foot=no` is not wrong, or better even would be `foot=use_sidepath` and an additional `sidewalk=separate` to denote that the way for pedestrians is a separately mapped one. The Järnvägsgatan carriageways on the bridge also have `foot=no` because the sidewalk is mapped separately.

**Comment by westnordost** [comment]
Also, I must say that personally I am a proponent of a common sense tagging regarding `foot=no`. I mean, what the heck, look at this:

https://www.google.se/maps/@58.4141535,15.6367872,3a,75y,235.93h,79.04t/data=!3m6!1e1!3m4!1spBi14J1CSYV5F4lLIBvTuw!2e0!7i13312!8i6656

Noone with still all his senses would walk on this road. And I am pretty sure the police would see it the same way, if you attempted to walk down this road. Maybe they won't fine you for using a road while not allowed to do so, but at least for traffic obstruction and careless endangerment of fellow citizens.

**Comment by matkoniecz** [comment]
Yeah, https://www.google.se/maps/@58.4141535,15.6367872,3a,75y,235.93h,79.04t/data=!3m6!1e1!3m4!1spBi14J1CSYV5F4lLIBvTuw!2e0!7i13312!8i6656 looks like case where reckless endangerment or something similar would apply (or is it actually legal to walk or push stroller under this bridge)?

Especially as judging by StreetView and https://www.openstreetmap.org/#map=18/58.41457/15.63724 there are footways/cycleways along it (separated enough, but being a clear alternatives).

To be clear, `foot=no` is clearly wrong where it is just "walking is unpleasant". But this seems to be going beyond that.

**Comment by riiga** [comment]
Say what you will about the examples, but according to the law you're still allowed to walk there if you really need to. It's certainly a bad idea and no one in their right mind would do it, but *legally* it's allowed. For it to be unlawful there needs to be a local rule against using the road of which I've mapped all in my city (they're publically available). Perferably there should also be a sign and in most cases there is. [Here's an example of a local rule](https://rdt.transportstyrelsen.se/rdt/AF06_ViewDocument.aspx?ForeskriftId=cd214a95-f718-4496-a8b8-ba8958aaa8e0&NoNavigation=1), on Tullbron which is forbidden to walk on, but the roundabout nearby isn't even if it's a terrible idea to walk there.

**Comment by matkoniecz** [comment]
> but according to the law you're still allowed to walk there if you really need to

But in given examples there are no conceivable routes without footways - is it really possible to have even a theoretical case that would make necessary to walk along say https://www.openstreetmap.org/way/351472764#map=19/58.39030/15.62589 on road itself (except cases like "sidewalk/road were closed and layout changed") ?

**Comment by riiga** [comment]
For the road you linked now there's easily a case: You crossed the road on the unsigned crossing and want to walk from [here](https://www.google.se/maps/@58.3904409,15.6254969,3a,75y,257.27h,78.62t/data=!3m6!1e1!3m4!1sgSV0gFWi4GL6wfXo2iteJg!2e0!7i13312!8i6656) where the footway ends down to the ped- and bike- path by the traffic signals. You're 100 % allowed to do that using the shoulder.

**Comment by westnordost** [comment]
Anyway, back to the app: I think the current wording is already precise enough as it deliberately mentions whether it is "prohibited". Asking if something is signed to be prohibited (🚷) or even "explicitly" prohibited would be wrong, because in some situations (f.e. there is already a sidewalk which is mapped separately) it does not need to be signed explicitly to be forbidden legally.

**Comment by smichel17** [comment]
If nothing else, I suggest changing the word. Prohibited and Forbidden have slightly different connotations. The latter conveys the idea of "not allowed, _regardless of whether it is physically possible_" much more clearly.

> I wanted to walk the usual way, but was prohibited by a giant pile of gravel in the road!

I find this usage unusual, but I would probably just assume it's how the person talks.

> I wanted to walk the usual way, but was forbidden by a giant pile of gravel in the road!

I would assume that "forbidden" was picked intentionally for the imagery it evokes. I would be quite surprised if anyone spoke this way / I would more expect to find this in a story or poem.

**Comment by westnordost** [comment]
Okay, then it's a "translation" issue and I'll just change the wording in English.

**Comment by westnordost** [comment]
_"Are pedestrians forbidden to walk on this road here?"_

**Comment by riiga** [comment]
I still think "legally" should be included.

"Are pedestrians legally forbidden to walk on this road here?"

**Comment by Luzandro** [comment]
I still think that this quest does more harm than good. @westnordost said for himself, that there are hardly ever any signs to forbid pedestrians to to walk on a road. So except for those rare cases, which are probably already tagged, this leaves only the options that in the best case people add loads of useless foot=yes or they add incorrect foot=no and make pedestrian routing actually worse instead of better.

https://www.openstreetmap.org/changeset/103921783

https://www.openstreetmap.org/changeset/94754795

https://www.openstreetmap.org/changeset/97248457

https://www.openstreetmap.org/changeset/96803426

https://www.openstreetmap.org/changeset/99601694

https://www.openstreetmap.org/changeset/96262173

https://www.openstreetmap.org/changeset/97207311

https://www.openstreetmap.org/changeset/102468820

https://www.openstreetmap.org/changeset/101736254

**Comment by westnordost** [comment]
I have no time to review those changesets right now so I'll just reopen the issue first

**Comment by westnordost** [comment]
@Luzandro Short note: Maybe from having and reading the conversations with those that answered it wrong using streetcomplete, you can make a suggestion how the wording could be changed or how the wording of an additional explanatory text that is displayed alongside this quest could look like

**Comment by andrewharvey** [comment]
Perhaps it should instead ask, "Is there a sign indicating prohibited for pedestrians?" If yes then `foot=no`, if no then `foot:signed=no`?

**Comment by Luzandro** [comment]
I don't think that only the wording is the problem, but the task itself. What do you want to achieve with the question, if the answer is almost always, "no it is not forbidden"? The relative proportion of false reports will always be high, alone by the small number of ways, where foot=no is actually missing.

**Comment by matkoniecz** [comment]
> What do you want to achieve with the question, if the answer is almost always, "no it is not forbidden"?

Detect actually inaccessible and forbidden for pedestrians ways, I found some in my city using that quest

**Comment by westnordost** [comment]
Note that it does not necessarily require a sign for a road to be legally `foot=no`. Sometimes it is clear from the context, i.e. the footway-part of the street goes a different way (so, not directly a sidewalk but still clearly belonging to a road). Then, `foot=no` would be correct.

**Comment by Lukas458** [comment]
For finding some locations where foot=no or foot=use_sidepath are correct (mostly meaning use_sidepath, but sometimes also foot=no) it maybe wouldn't make sense to ask for every road that has sidewalk=no(ne), but even more to ask just for roads which have either sidewalk=separate or are "main roads" having a parallel osm-way next to them which is allowed for pedestrians (path, footway...).

I don't know how to make a script for finding the parallel ways, but maybe for setting the cycleway tags there might exist some already.

When looking at https://www.openstreetmap.org/way/150643965#map=17/47.73151/16.24382 and some others, the problem seems to be (in my eyes), that this is a road which has sidewalk=none, but not any parallel osm-ways where pedestrians could walk. And I think, in these cases it is kind of un-probably that those roads of tertiary, unyclassified or secondary are foot=no. Of course at junctions the thing with the parallel osm-ways could be different, but I even think that junctions usually do not have soo much missing foot-tags at all.

**Comment by Lukas458** [comment]
Of course there can be some tunnels where there is no parallel osm-way for pedestrians and foot=no is appropriate, but I don't think that this would be a case where many situations are catches by with this quest.

**Comment by Lukas458** [comment]
For example this changeset:

https://www.openstreetmap.org/changeset/88414856#map=16/50.9965/6.7982

makes even more sense with this quest. A, strictly taken, wrong sidewalk=no was made to sidewalk=separate and a missing foot=use_sidepath was added. But I bet most of the unclasssified, tertiary or secondary roads which are sidewalk=no (I don't mean separate here) and are not tunnel=yes or motorroad=yes, do not even be foot=no because of the sidewalk=no.

**Comment by westnordost** [comment]
It is possible to add a descriptive text below the question that would explain in one to two sentences when a road would be prohibited for pedestrians.

**Comment by westnordost** [comment]
@riiga 

> Roads (in Sweden) where pedestrians are prohibited and which are not already covered by other regulations such as motorways are very uncommon.

This road section for example is rightfully `foot=no` even though there is no sign or anything. The quest is meant to catch not only those roads that have explicit signage, but also cases like these:
https://www.openstreetmap.org/way/206149602#map=19/50.94123/6.95329

**Comment by Luzandro** [comment]
Well the junction is also a good example on how this makes pedestrial routing worse:
https://www.openstreetmap.org/directions?engine=graphhopper_foot&route=50.94156%2C6.95310%3B50.94170%2C6.95293#map=19/50.94134/6.95275

**Comment by matkoniecz** [comment]
should be fixed in https://www.openstreetmap.org/way/206149630 - if that area tags sidewalks as tags on roads then `foot=no` was wrong there

And this foot=no was NOT added by StreetComplete, see https://www.openstreetmap.org/way/206149630/history so this poor routing is not a good example

**Comment by riiga** [comment]
@westnordost It's certainly not advisable for pedestrians to walk there, but they're not legally forbidden from doing it, at least not by our regulations.

I will reiterate my main point from the PR though:

> The biggest issue is not actually adding `foot=no` in error, it's adding `foot=yes` if pedestrians are allowed. By default `foot=yes` is implied for all roads, streets, paths, etc. in Sweden, except motorways, expressways (`motorroad=yes`) and explicit cycleways. Unlike countries like the UK, there is no legal "right of way" that can be restricted and for which adding `foot=yes` is useful. 

Just like adding `cycleway:both=no` is (imho) unnecessary (but I've come to accept it), this is 10 times worse. There is absolutely no reason for adding `foot=yes` to regular roads.

**Comment by westnordost** [comment]
> @westnordost It's certainly not advisable for pedestrians to walk there, but they're not legally forbidden from doing it, at least not by our regulations.

Is there no regulation that if there is a sidewalk, pedestrians must use it instead of walking on the road?

**Comment by riiga** [comment]
In short, it says 

>Pedestrians on a road shall use the footway/sidewalk or the shoulder.
>If there is no footway/sidewalk or shoulder, pedestrians shall use the cycleway or roadway. 

But there's also a part that allows not sticking to the sidewalk or shoulder if you have good enough reasons to do it. And "good enough reasons" can be pretty much anything that doesn't cause an accident.

**Comment by westnordost** [comment]
You may do many things with a good enough reason. See the "proportionality principle".

**Comment by riiga** [comment]
Because OSM follows the ground truth, and signs prohibiting pedestrians means `foot=no` unless otherwise stated. The sensible way to handle emergency would be having the router ignore access tags in an emergency mode. But that's not the issue at hand here. I object to the useless tagging of `foot=yes` if the user selects that pedestrians are allowed (which is the default access pretty much everywhere) and the problematic addition of `foot=no` to roads where it might not be prohibited to walk (with the Swedish translation a step in the right direction to prevent this). Until these issues have been resolved I prefer if the quest can be disabled by default in Sweden, hence my PR that was closed.

**Comment by westnordost** [comment]
So you think to tag `foot=yes` in certain cases is useless and I think it isn't. How do we proceed from here?

**Comment by riiga** [comment]
I think `foot=yes` has its uses, but not on regular roads. And assuming this quest will pop up on any roads that meet certain criteria and are not tagged `foot=*` this will slowly lead to the addition of millions of useless `foot=yes` (or `foot=use_sidepath` which is *slightly better*) in exchange for the discovery of a few roads where pedestrians are prohibited. My solution is to disable the quest in Sweden for now and then see what the general consensus about it in the rest of the world is, it might be useful in other countries, but it certainly isn't where I live.

**Comment by westnordost** [comment]
I find it a bit hard to argue, because you switch the subject. First, it was about that people answer "yes, prohibited" on roads where it is indeed not prohibited. I suggested that an explanatory text could be added (that f.e. explains that in general, it is never implicitly forbidden to walk on a road unless there is a sidewalk or something that should be used instead) and asked for suggestions for a wording.

But then you switched the topic to that it creates a lot of "useless" `foot=yes` taggings. So that means that the original subject is now solved, or what? Anyway, regarding the useless taggings:

> roads that meet certain criteria and are not tagged foot=* this will slowly lead to the addition of millions of useless foot=yes

The criteria are the following:
- it is explicitly tagged that the road has no sidewalk
- it is not tagged that the road has a shoulder (on which pedestrians might walk)
- it is not private
- it is not a motorroad or motorway (because foot=no is implied)
- it is a road with higher classification than residential
- it is paved (=is developed in some way)
- it is either a oneway or a bridge or a tunnel or bicycles are already not allowed or it is lit

The main interesting situations it should catch where I believe you would agree that they are in no way useless are certain road sections within large intersections, overpasses, underpasses, inner segregated lanes of large streets, connecting/linking road way sections and so forth.

Maybe you have a suggestion for adapting the filter, too.

On why tagging "default" tags, see also
https://wiki.openstreetmap.org/wiki/StreetComplete/FAQ#Why_does_StreetComplete_often_tag_the_absence_of_features.3F

**Comment by riiga** [comment]
I didn't switch the subject, I made, after examining the quest more in detail, another point of how this quest leads to bad data in the form of both incorrect `foot=no` and useless `foot=yes`. I stand by this and advocate the removal of this quest in Sweden.

I still think the wording the default text should be changed, I've not said otherwise. I proposed "Are pedestrians legally forbidden to walk on this road here?". I'm satisfied with the Swedish translation which I changed myself and which adds this distinction.

I find the critera to be pretty reasonable, though maybe a little too wide. I would probably change 

> it is not tagged that the road has a shoulder (on which pedestrians might walk)

to 

> it is explicitly tagged that the road has no shoulder

and make sure there is a quest to ask for shoulders on roads (which unlike the cycleway quest could be useful)

I would perhaps also exclude `highway=unclassified` from the quest.

**Comment by matkoniecz** [comment]
> and make sure there is a quest to ask for shoulders on roads (which unlike the cycleway quest could be useful)

#2444

**Comment by westnordost** [comment]
Alright, what about changing it so that it is only asked bridges, for tunnels and places where already bicycles are not allowed?

This would severely "cripple" this quest, as it is not asked for pieces of road on large intersections for example anymore (see https://github.com/streetcomplete/StreetComplete/issues/2472#issuecomment-903114737), which is a shame, but maybe it is too involved to ask StreetComplete users about a legal prohibition on road segments that are arguably "virtual", as in reality there are no single road ways on an intersection, but the whole intersection is a big area.

**Comment by mnalis** [comment]
> Alright, what about changing it so that it is only asked bridges, for tunnels and places where already bicycles are not allowed?
> This would severely "cripple" this quest, as it is not asked for pieces of road on large intersections for example anymore

... unless those pieces of road are (already) marked with `bicycle=no`?

**Comment by matkoniecz** [comment]
@riiga 

Has https://github.com/streetcomplete/StreetComplete/commit/c5b6ef15e17bd2ec990c0edb3438807030d12179 solved this issue?

Is it still causing problems?

**Comment by matkoniecz** [comment]
Closing as the https://github.com/streetcomplete/StreetComplete/commit/c5b6ef15e17bd2ec990c0edb3438807030d12179 seems very likely to be solving problem due to sharp cut on eligible quests.

**Comment by hamishmb** [comment]
Apologies for bumping this. Okay, so I've just arrived at this issue because I'm confused about the quest too.

I've generally been answering from the point of view of "Would it be safe to walk on the road here?" and "Would I want to be directed to walk on the road here?". If the answers to either of those questions was no, I've answered as prohibited for safety reasons. This basically means places like A-roads and dual carriageways in the UK.

It seems I've been doing this wrong, but I'm not sure what to do about that. I could go and revert my changes, but then it would potentially be extremely dangerous to walk along a dual carriageway, so I'm not sure we want to be allowing that for the routing algorithms that use OSM.

Thoughts?

**Comment by westnordost** [comment]
It is always preferable to go back and fix mistakes tagged in the past than to let it rot in the database if you are able. After all, wrong data is worse than no data at all. https://osmcha.org/ may be of great help to find the changesets affected in question.
That having said, I am sure you are not the only one to have ever interpreted `foot=no` to mean "not safe" / "not eligible" rather than a purely legal definition, so any data consumer that evaluates this tag will need to take into account that the tag is "unclean" in that way.

Anyway, some countries actually explicitly forbid pedestrians to access certain types of roads (usually motorways and motorroads), I don't know if the UK is one of them (for dual carriageways). Also, note that if there is a designated parallel footpath near the dual carriageway, walking on that road is also implicitly prohibited (without the need of an explicit sign) because pedestrians are obligated to use a sidepath if there is one in most legislations (doesn't need to be a sidewalk).
Other situations where `foot=no` would be correct too without explicit signage would be road sections in the middle of a large intersection (i.e. on the intersection area) and similar situations where it is common sense that pedestrians are of course prohibited.

**Comment by mnalis** [comment]
I wouldn't think of it as much of a problem. 

If I asked some local people on the street and they told me it is really, really, bad idea to walk on some street and I should take a detour, I wouldn't care much if it was because I'd get arrested and put in jail for the rest of my life _**or**_ if it is just extremely likely I'd get hit by a truck and put in a hospital for the rest of my life -- I'd simply avoid that street when on foot. 

And I'd take a same hint if routing engine advised me to avoid street marked with `foot=no`.

So I wouldn't worry too much about past edits @hamishmb. As noted, different people mark it differently anyway, and any data consumer will have to take that into account anyway, and it will likely remain ambiguous forever.

**Comment by hamishmb** [comment]
Thanks for the comments. On reflection, I'll just leave it as is then, I think, unless an OSM person gets annoyed and tells me to change my edits :)

Mostly, I've been doing these around big multi-lane roundabouts that connect dual carriageways anyway, so probably a non-issue.
