### ISSUE TITLE
[Quest suggestion] What kind of sidewalk does this road have?

### ISSUE THREAD

**Issue by fabiobettani** [streetcomplete/StreetComplete#2487]
### General
Affected tag(s) to be modified/added: covered (https://wiki.openstreetmap.org/wiki/Key:covered)
Question asked: **What kind of sidewalk is this?** (or: **Is this sidewalk covered?**)
Answer: one of the following

* Uncovered (--> covered=no)
* Arcade (--> covered=arcade)
* Colonnade (--> covered=colonnade)

This would be useful in order to mark porticos, which are a common feature in historical city centres in Italy (and much of Europe?).

### Checklist
Checklist for quest suggestions (see guidelines):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary 
- [x] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of elements (Worth the effort)

### Ideas for implementation

**Element selection:**
All elements with highway=footway AND footway=sidewalk.
This could possibly be extended to elements tagged with sidewalk=right, left, or both.

The feature could be activated in selected country: I guess it's quite relevant in Italy, where arcades are common; not so relevant in other countries.

**Proposed GUI:**
Pictures such as
https://wiki.openstreetmap.org/wiki/File:Sidewalk_and_zebra-crossing.jpg
https://wiki.openstreetmap.org/wiki/File:Kanslihusets_arkad.jpg
https://wiki.openstreetmap.org/wiki/File:Laubeng%C3%A4nge_in_Neumarkt.jpg

**Comment by westnordost** [comment]
> 💤 Not an overwhelming percentage of elements have the same answer (No spam)

How many percent of sidewalks are covered?

**Comment by fabiobettani** [comment]
That's a good question. In historical city centres, such as Bologna, I'd guess 50% of sidewalks are covered.
Newly built neighbourhoods in the outskirts of cities have a far lower percentage of covered sidewalks.
To the opposide side of the spectrum, newly built neighbourhoods in minor towns have practically none (as in any European country, I guess).

![image](https://user-images.githubusercontent.com/66837227/104170691-d62e6f80-5401-11eb-80d6-75559f40e5de.png)

Possibly this quest could be restricted to those cases where an arcade or colonnade has already been marked in a radius of ...300-400 m, in order to reduce redundancy for the user?

**Comment by westnordost** [comment]
Well, you mention Bologna city center. But what about outside city center but still in Bologna then? I venture to say that even in Bologna + suburbs, the vast majority of sidewalks will not be covered, making it 
> 💤 Not an overwhelming percentage of elements have the same answer (No spam)

even there. Probably. But let's not split hairs because it hardly matters how the situation would be for Bologna alone because filtering based on location is only possible on a by-country-basis.

I'd suggest that instead, you get together with the local community and you crowd-map that one property of sidewalks in (the city center of) Bologna instead. To collaborate, there are various tools around. To my mind comes
- Simple task manager: https://stm.hauke-stieler.de/ like the HOT tasking manager, only a little simpler
- [MapContrib](https://www.mapcontrib.xyz/) or [MapComplete](https://mapcomplete.osm.be/?) 

Whether a sidewalk is covered or not should also be well visible from satellite imagery, so something that can be done well at home 

> 💵 Valuable Surveyors: Surveyor time is valuable, they shouldn't be asked to complete data that does not require a survey and can more efficiently be done remotely.

In case you end up organizing a mapathon or something of that source, please do post here what tool you used for that and how it went, I am curious about these kind of collaboration on OSM.
