### ISSUE TITLE
Support bicycle=use_sidepath

### ISSUE THREAD

**Issue by tessarakt** [streetcomplete/StreetComplete#2525]
**Use case**
It shall be possible to choose "There is a bicycle path belonging to this road which is tagged separately and mandatory to use.

https://wiki.openstreetmap.org/wiki/Tag:bicycle%3Duse_sidepath

This should affect the question "Is there a cycleway? Which kind".

Currently there are the following options: "none", and several kinds of cycle lanes that are part of the same road.

**Proposed Solution**

- add an option "separately tagged cycleway".
- In a second step, ask: "Is the separately tagged cycleway mandatory to use?" Only if the answer is "Yes", apply "use_sidepath".

Something similar seems to be in place for footpaths, see screenshot here: https://twitter.com/StreetComplete/status/1352995173291196416

**Comment by westnordost** [comment]
Can you link the OSM element for which the question was asked even though it shouldn't have because there was already a separately mapped cycleway?

**Comment by tessarakt** [comment]
https://www.openstreetmap.org/way/116387359#map=17/48.37664/10.00704

By now, I added bicycle=use_sidepath manually.

**Comment by westnordost** [comment]
Hm, the distance between the center of the road and the cycleway is 12.35m (cause of a 3.5m grass verge).
The cycleway quest is not asked if the distance is smaller than `(lanes * 3m) / 2 + 6m`, so in this case 12m.

Looking at the situation on satellite imagery,
- each lane is 3.3m broad
- the cycle lane is 4m broad
- the green verge is 3.5m broad

So this seems to be a quite unusual situation, I think it is not necessary to adapt the formula. Providing an extra answer option seems to make sense, maybe even reduce the formula to `(lanes * 3m) / 2 + 4m` or something then.

**Comment by matkoniecz** [comment]
Note that StreetComplete user may be unable to know whatever answer 

> There is a bicycle path belonging to this road which is tagged separately and mandatory to use

is correct, as cycleways and footways are both shown in the same way.

To check that one would need to look at OSM data using some other tool.

**Comment by tessarakt** [comment]
> 
> 
> Note that StreetComplete user may be unable to know whatever answer
> 
> > There is a bicycle path belonging to this road which is tagged separately and mandatory to use
> 
> is correct, as cycleways and footways are both shown in the same way.

Sorry, I don't get here what you mean. If the question is about a cycleway, the user can look whether the separately tagged cycleway is mandatory to use.

> To check that one would need to look at OSM data using some other tool.

... no need to look at OSM data for that.

**Comment by matkoniecz** [comment]
> ... no need to look at OSM data for that.

How someone may know whatever this cycleway is mapped already as separate way?

Lets say that sepate cycleway exists.

Case 1: it is not mapped at all

Case 2: it is mapped as `cycleway:right=track` (or some other tag from cycleway family)

Case 3: it is mapped as a separate way

Answering "There is a bicycle path belonging to this road which is tagged separately and mandatory to use" would be incorrect in cases 1 and 2 (may happen for resurvey quest).

BTW, some cases where it was necessary to tag it manually that appeared recently:

https://www.openstreetmap.org/note/2508668#map=18/52.21565/20.95841
https://www.openstreetmap.org/note/2508633#map=18/52.22153/20.97323
https://www.openstreetmap.org/note/2508632#map=18/52.22028/20.97423
https://www.openstreetmap.org/note/2508631#map=18/52.22052/20.97300
https://www.openstreetmap.org/note/2508630#map=19/52.22177/20.97829
https://www.openstreetmap.org/note/2508629#map=19/52.21973/20.97123
https://www.openstreetmap.org/note/2508628#map=19/52.21945/20.97056

**Comment by westnordost** [comment]
Whether a separately drawn cyclway is mandatory to use (i.e., it implies that cyclists may not go on the road tagged with `bicycle=use_sidepath`) seems to be a legal category according to my reading of https://wiki.openstreetmap.org/wiki/Tag:bicycle%3Duse_sidepath
In other words, if there is just a cycle path a certain distance from the street and mapped seperately, but a sign like this is missing... 
<img src="https://upload.wikimedia.org/wikipedia/commons/c/cd/Nederlands_verkeersbord_G11.svg" width="50"/>
...then, `bicycle=use_sidepath` should **not** be tagged.

Whether or not such a sign is required for the seperate cycle path to be legally considered as mandatory differs from legislation to legislation. For the average joe that is using this app, it is not really possible to answer this with precision because it cannot be assumed that he knows the specific laws regarding this. And anyway, they can't be required to cycle the whole way up and down to see if at the beginning or end there'll be such a sign.

**It would be better to ask users for physical properties because you'll get a precise answer here.**

For sidewalks, there is `sidewalk=seperate`. The difference to `foot/bicycle=use_sidepath` seems to be that the former exclusively refers to the presence of a seperately mapped sidewalk, while the latter carries additionally a (legal) access restriction.

For cycleways, this attribute (`cycleway=seperate`) exists as well, albeit to a much much less degree:
- `bicycle=use_sidepath`: 141k uses
- `cycleway=seperate` ~7k uses

Considering that `cycleway=seperate` is not really in use (looking at the percentages), there is really no possibility currently to tag on the road-way that there is a seperately mapped cycleway for this road but it is **not** mandatory to use.
The overwhelming prevalence of the `bicycle=use_sidepath` tagging and the lack of use of the version that does not implicate a legal status lets me to the strong suspicion that no matter the definition in the wiki to include the legal status, the actual use of this tag is to record that a cycleway has been mapped seperately. 

But in any case, no matter how far off the actual usage from the wiki-definition already is, it shouldn't justify to use the `bicycle=use_sidepath` tagging wrongly in this app, that is, use it to tag the physical presence of a seperately mapped cycleway.

So, this is a bit of a blocker here:
- `bicycle=use_sidepath` should not be used because of the reasons stated above
- `cycleway=seperate` is not really used that much yet

**Comment by westnordost** [comment]
So, what do you say to that?

**Comment by BalooUriza** [comment]
I'm personally not a fan of `bicycle=use_sidepath`.  If it was mapped correctly, then that's `bicycle=no` and any reasonable router should be able to find the designated cycleway immediately adjacent anyway.  And if it's a situation where bicycle lane use is mandatory but the bicycle lane is the rightmost lane out of three, then `bicycle:lanes=no|no|yes` is the right thing...

Been kicking around the idea of `lanes:total=*` as a more complete answer to `lanes=*`, would obviate possible bicycle lanes if `lanes:total=*` is greater than `lanes=*`, but that's pretty niche.  The primary reason is to hopefully deprecate `lanes=*` entirely as it doesn't accurately count lanes and throws off validators checking turn lane and lane access tags.

**Comment by matkoniecz** [comment]
>  If it was mapped correctly, then that's bicycle=no

Not everywhere, for example in Poland.

**Comment by BalooUriza** [comment]
On Tue, Jan 26, 2021 at 9:03 AM Mateusz Konieczny <notifications@github.com>
wrote:

> If it was mapped correctly, then that's bicycle=no
>
> Not everywhere, for example in Poland.
>

I'm not saying that there aren't places that are radically inconsistent
currently.  I am saying we should work to fixing this inconsistency and use
nonsubjective values for lane and access tags.

**Comment by westnordost** [comment]
So, @tessarakt or anyone else wanting to advance this, this is the next step:
1. discuss on the tagging mailing list or another public frequented OSM discussion space how to best tag the information that the cycleway has been mapped separately without making any assertion about whether that cycleway is mandatory or not
2. after the discussion comes to a conclusion, link it here and I will reopen this ticket.

**Comment by westnordost** [comment]
Ah what gives, I'll leave it open for now.

**Comment by westnordost** [comment]
Since nothing seemed to have happened here, it makes no sense to keep this open.

**Comment by westnordost** [comment]
A wild wiki page appeared: https://wiki.openstreetmap.org/wiki/Tag:cycleway%3Dseparate

**Comment by DerDings** [comment]
> 
> 
> I'm personally not a fan of `bicycle=use_sidepath`. If it was mapped correctly, then that's `bicycle=no` and any reasonable router should be able to find the designated cycleway immediately adjacent anyway. And if it's a situation where bicycle lane use is mandatory but the bicycle lane is the rightmost lane out of three, then `bicycle:lanes=no|no|yes` is the right thing...


`bicycle=no` and `bicycle=use_sidepath` are quite different things.
* `bicycle=no` means that you aren't allowed to cycle a road at all.
* `bicycle=use_sidepath` means that you are allowed to cycle that road, but you have to use the cycle way instead of the carriageway _if possible_. If it is not possible for you to use the cycle way, you may still use the carriageway. For example, this may be the case if the cycle way is only suitable for regular bikes, but you are riding a broader cargo bike or carry a trailer.

A map rendering aimed at cyclists with trailers may show `bicycle=no` because it is important to know where you aren't allowed to ride, but may show `bicycle=use_sidepath` differently or not at all because it is just a matter of _how_ you are using the road, not _if_ you are using it.
