### ISSUE TITLE
My Profile screen is displayed rotated on tablets

### ISSUE THREAD

**Issue by MakiWolf** [streetcomplete/StreetComplete#2534]
My Profile screen is not optimized for tablets. But other screens like Settings or About does not have this rotate issue.

**How to Reproduce**

Open Menu and select My Profile

![issue](https://user-images.githubusercontent.com/73300633/106042987-12d6b800-60de-11eb-9fa5-98f211c13e4f.gif)

**Versions affected**

30.0-beta1

**Comment by matkoniecz** [comment]
I changed title - as it is just "not optimized" (what would be OK), it is a stronger problem.

**Comment by MakiWolf** [comment]
I just found out that also phones are affected when they are rotated.

**Comment by westnordost** [comment]
Yes, the profile screen is only available in portrait mode. I don't really intend to change that though because on a (small) smartphone screen, landscape layout for this view does not really work, too little available vertical space. And it is not possible as far as I know to have landscape mode only be enabled for screens with a minimum vertical screen space.

**Comment by matkoniecz** [comment]
I found https://stackoverflow.com/questions/13157971/have-a-fixed-orientation-based-on-screen-size/13158961#13158961 and https://stackoverflow.com/questions/9279111/determine-if-the-device-is-a-smartphone-or-tablet#9308284 that claim that it at least used to be possible.

Have not tried it and and I am unsure is it worth trying to do this and I have not checked is it blocked by Kotlin.

**Comment by westnordost** [comment]
It is probably possible programmatically. Maybe it is actually not very much effort to enable landscape mode on screens that have a certain minimum height. But then also, it may remain to not look very optimized on landscape mode. Especially on such a huge device @MakiWolf  was testing it.

Also one reason why screen orientation change in that screen is disabled is because in the quest and country statistics screen, there is some interaction with rotating, shaking and tilting the device. It would be very disruptive if the screen is suddenly rotated if one rotates/shakes/tilts too much.

So, I am not going to bother implement it and whoever would like to implement it in my stead must solve the mentioned issue somehow. (F.e. always freeze orientation change when that tab is open)
