### ISSUE TITLE
Clarification for vegetarian quest

### ISSUE THREAD

**Issue by Helium314** [streetcomplete/StreetComplete#2539]
According to the displayed text I am supposed to answer _yes_ for the vegetarian quest only if the place provides 'proper [vegetarian] eating'.
Does this mean that for places that do not offer 'proper eating' (e.g. a café offering only cake, or a bar selling peanuts) the answer is always no? According to the text it is the case, but answering 'no' for such places still feels completely wrong...

**Comment by westnordost** [comment]
Do you have a suggestion how to improve the wording? Current wording:

"Only answer “yes” if the place provides proper eating options for this diet, ignore starters etc."

**Comment by Helium314** [comment]
I thought about it for quite a while, but unfortunately nothing that wouldn't be horrendously long...

**Comment by peternewman** [comment]
Would something around the word choice/selection/range help?

"Only answer “yes” if the place provides a proper choice of eating options for this diet, ignore starters etc."

A cafe only offering cake is fine I'd say, as long as the cake's aren't all topped with bacon (maybe maple cured) for example.

I guess the easier example is if you're answering the vegan quest for a cake cafe, then if there's one cake then yes, if they only sold a vegan cereal bar and no cakes, then no.

**Comment by mnalis** [comment]
@peternewman I was under impression answer would **always** be "no" in cafes and other places which **do not serve full meals**? At least that is what "proper eating" implies to me - no snacks, but a full meal, one which you can eat for lunch and work all day on the calories taken. "ignore starters, etc ." seems to me that it reaffirms that stance. Or maybe I'm getting this wrong? 

It does look it could do with better explanation, if we seem to have understood it differently...

**Comment by westnordost** [comment]
Really? Obviously, if the establishment does not serve "proper meals" at all, but just cakes for example, it is of course eligible for vegetarians.

**Comment by westnordost** [comment]
The current text already mentions "proper options", not "proper meals". Cakes are not starters.

**Comment by mnalis** [comment]
Well, It looks like it is _obvious_ to some, but not others (like original poster and myself). If cafe serves only cakes (made without animal fat?), I agree it does contain food eligible for vegetarians, but it does not seem what the text of the quest is asking for  - to me it **looks like it is explicitly excluding** all places where vegetarian can't get "A full day meal". So if restaurant had only had  pickles or vegetable salad as non-meat things on menu, it would be excluded by that quest definition, wouldn't it? 

I agree that cakes are (usually, but I can think of few exceptions) not starters, but (again, usually, at least in my country) desserts - but in my book that would still enter them in "starters, **etc.**" category (as that "etc." would indicate to me **ALL similar non-main-course additions as are starters**: so not only starters, but also side-dishes, toppings, salads, desserts, drinks etc. **would not count to mark a place as vegetarian**). Is this correct? 

Might be that the root of the confusion is in word "**proper**" -- at least in my case, when I was a kid, after school I would always be denied sweets or snacks until I've eaten "**some proper food**" first (which meant the full lunch/dinner, ie. at least main dish + side dish + salad, and sometimes also included soup before main meal etc). 

"Proper food" as such was opposed to "junk food" (such as roasted and salted potato chips or peanuts, as well as sugary things like candies, chocolate, cakes, or virtually anything that comes packaged in sealed plastic bags)

**Comment by peternewman** [comment]
The note at the bottom of the table helps to clarify it:
https://wiki.openstreetmap.org/wiki/Key:diet#Tagging

It's more about equality, if you can go to the restaurant with the least restrictive diet (e.g. omnivore) and eat three courses, it should offer three vegetarian courses (not just give you two starter salads instead of a normal main).

So if your cake shop only served dessert, then as long as they do a vegetarian one. But if your fish & chip shop only serves main courses and the vegetarian option is just the chips (side) or a pickled egg then a vegetarian will be rather underwhelmed.

**Comment by mnalis** [comment]
@peternewman that wiki description is pretty clear, and makes sense, thanks! Alas, SC users are not provided with wiki explanations... Do you have suggestion how to compact it to short (one sentence) StreetComplete format?  

Current (shared by both all dietType quests?) is 

`Only answer “yes” if the place provides proper eating options for this diet, ignore starters etc.` in english, which I find quite misleading and lacking main "equality" point...

Maybe something along the lines of: `Only answer “yes” if the place provides at least equal eating options for this diet as for other diets (eg. if it provides meat-based main dishes, it should also have vegan main dishes)`, but better worded and generic (not implying vegan or vegeterian or kosher etc) - and hopefully shorter too. (Note: I've put in `at least` since it might be vegan-only with no meat foods for examples)

**Comment by peternewman** [comment]
> @peternewman that wiki description is pretty clear, and makes sense, thanks! Alas, SC users are not provided with wiki explanations... Do you have suggestion how to compact it to short (one sentence) StreetComplete format?

I thought there were links to the wiki somewhere, but I'd agree something immediate in the quest would be better.

> which I find quite misleading and lacking main "equality" point...

I think equality may be too strong, or could be misinterpreted (see below).

> Maybe something along the lines of: `Only answer “yes” if the place provides at least equal eating options for this diet as for other diets

Likewise equal (I guess unsurprising as they're the same base word).

There are very few places I've been who have as broad a range of vegetarian meals as omnivores for example.

My previous offering was:

> Would something around the word choice/selection/range help?

Throwing out some random suggestions:

"Only answer “yes” if the place provides a comparable choice of eating options for this diet"
"Only answer “yes” if the place provides a reasonable choice of eating options for this diet"
"Only answer “yes” if the place provides a good choice of eating options for this diet"
"Only answer “yes” if the place provides a choice of eating options for this diet"

Or swap the word choice for range.

Last time @smichel17 was better at this than me, or we bounced off each other.

**Comment by mnalis** [comment]
Yes, the "comparable" options looks best for me - much better than original text.

**Comment by Helium314** [comment]
> A cafe only offering cake is fine I'd say, as long as the cake's aren't all topped with bacon (maybe maple cured) for example.

Much less obvious: cakes might also contain gelatin. It's not meat, but usually extracted from bones and therefore not suitable for  vegetarians.

**Comment by peternewman** [comment]
> Yes, the "comparable" options looks best for me - much better than original text.

My only worry with that one was someone assumes that because they offer say 10 or 20 omnivore dishes but only two or three vegetarian, that's vegetarian=no as it's not comparable. See some discussion on the wiki page for more on that, but it's probably acceptable, but not great unless you're going there all week.

> cakes might also contain gelatin

I did consider mentioning jelly, I thought I'd make it nice and obvious.

Vegan cakes are even more complicated, so there is a requirement to get the right answer for bakeries too.

**Comment by mnalis** [comment]
> > Yes, the "comparable" options looks best for me - much better than original text.
> 
> My only worry with that one was someone assumes that because they offer say 10 or 20 omnivore dishes but only two or three vegetarian, that's vegetarian=no as it's not comparable. 

Well, to me it is still comparable, it's just that comparison is in favor of omnivores... It still looks like best replacement to me.
So I think we can go with:

- **quest_dietType_explanation** = `"Only answer “yes” if the place provides a comparable choice of eating options for this diet"` 

> > cakes might also contain gelatin
> I did consider mentioning jelly, I thought I'd make it nice and obvious.

Do note that there is EXTRA (ie. in addition to text above) text appended for:

- **vegetarian**: `Vegetarian meals contain no meat, fish, or poultry.`
- **vegan**: `Vegan meals contain no animal products (no meat, fish, poultry, milk products, eggs, …).`
- **kosher**: `Kosher products must be prepared according to special rules, with kashrut certification agencies marking products in compliance.`


> Vegan cakes are even more complicated, so there is a requirement to get the right answer for bakeries too.

Perhaps in interest of clarity **vegan** quest description could also be updated with `honey` and **vegetarian** with `gelatin`, which are two common pitfalls which average SC user might miss (unless they're using that diet). 

But then again, there is little chance that menu in restaurant is going to mention if some cake contains gelatin (they would usually only mention main ingredients and allergens, at least in Croatia), and there is no way we could list all the issues anyway (for example, somewhat counterintuitively, [wine if often non-vegan](https://veganclue.com/why-is-wine-not-vegan/), depending on ingredients used when processing it, and is used not only as a drink but as cooking ingredient too) - so we should perhaps let the user be guided by checking if restaurant menu has "vegetarian"/"vegan" category and trust that.

**Comment by westnordost** [comment]
Many vegetarians still eat things that contain gelantin. There are some gradations to vegetarianism, I think not consuming gelantin would fall into the strictest form, aka veganism. Since there is already `vegan` as a separate tag and it is not strictly defined for `vegetarian`, we can assume it to cover the lax(est) definition, which would be just the avoidance of flesh.

Anyway, I added "honey" and changed the wording like you suggested, uploaded it to POEditor. I marked the translations in other languages as "fuzzy".
