### ISSUE TITLE
Add another answer "House number and a name" which gives a two field form, for house name and house number.

### ISSUE THREAD

**Issue by peternewman** [streetcomplete/StreetComplete#2540]
**Use case**
As per:
https://wiki.openstreetmap.org/wiki/Key:addr#Tags_for_individual_houses

> addr:housename - The name of a house. This is sometimes used in some countries like England instead of (or in addition to) a house number.

There's no way to do a sensible quest, but the existing AddHousenumber one could be extended if one was spotted while surveying.

This would cover both single family homes "Pretty Name Cottage, 5 Small Close" and blocks of flats "Accommodation Towers, 20-25 Busy Road".

**Proposed Solution**
Add an other answer "House number and a name" which gives a two field form, for house name and house number.

Users can pick this option if both are present rather than having to choose one or the other and lose the bit of data they didn't enter, or add a note and then someone have to manually copy it into the object.

**Comment by andrewharvey** [comment]
I'd one further and ask, "Does this building have a name?" in addition to asking for the street address (as two seperate quests), for all buildings of type apartments, office.

**Comment by matkoniecz** [comment]
> for all buildings of type apartments, office.

Where it would make sense? Definitely not in Poland.

**Comment by andrewharvey** [comment]
> Where it would make sense? Definitely not in Poland.

I can only speak for Australia where most (at least 50%) apartment buildings have a signposted name. Most large office buildings also would commonly have a building name.

**Comment by andrewharvey** [comment]
>for all buildings of type apartments, office.
> Where it would make sense?

According to https://taginfo.openstreetmap.org/tags/building=apartments#combinations and https://taginfo.openstreetmap.org/tags/building=office#combinations they have a name tag 7.7% and 40% of the time respectively already in OSM.

**Comment by peternewman** [comment]
> "Does this building have a name?"

That's just a case of extending does this place have a name isn't it?

It would work in the UK too I suspect (without looking at the stats).

I'd particularly like to cover the family homes which have both, which you can't define a sensible query for.

**Comment by andrewharvey** [comment]
> That's just a case of extending does this place have a name isn't it?

Yes, so maybe I should open a separate ticket, I'm not sure if it should be dealt with any different than the scenario you've described (which would involve answering both bits in the same quest, instead of two separate quests).

**Comment by mnalis** [comment]
While I can see `building=office` having a name (it is by definition an office of some company/agency, which will have name) at least in Croatia I don't recall ever seeing an `building=apartments` with a name. So that definitely looks country-specific, so might probably be best served with separate user-selected answer (`has both address and a name`)

**Comment by andrewharvey** [comment]
> While I can see building=office having a name (it is by definition an office of some company/agency, which will have name) 

I was more thinking for buildings that have a name separate to the company, for office buildings with multi-occupancy, ie. no office=* tag on the building.

>  in Croatia I don't recall ever seeing (correctly mapped) building=apartments with a name

Could be country dependent then. Though another problem is to use addr:housename= or name=. I'll open a new ticket for my request to not distract from @peternewman's request which I believe is more for addr:housename + addr:housenumber.

**Comment by andrewharvey** [comment]
I've branched off my request into #2545

**Comment by mnalis** [comment]
Note that `addr:housename` usage is much lower at [0.70%](https://taginfo.openstreetmap.org/tags/building=apartments#combinations) (for `building=apartments`) to [3.37%](https://taginfo.openstreetmap.org/tags/building=office#combinations) (for `building=office`)

**Comment by westnordost** [comment]
Possible to do this, but not sure if worth the effort. I won't implement it at least.

**Comment by peternewman** [comment]
> > That's just a case of extending does this place have a name isn't it?
> 
> I'm not sure if it should be dealt with any different than the scenario you've described (which would involve answering both bits in the same quest, instead of two separate quests).

Ah, I'm assuming you meant a standalone quest asking for the name of all apartments and offices, which wouldn't work for houses (my use case) as it would be far too spammy. If you don't think yours is spammy, then a separate quest is the only way to pick up all the ones which already have one but not the other.

> Possible to do this, but not sure if worth the effort. I won't implement it at least.

Okay thanks @westnordost , hopefully someone will get interested.

**Comment by westnordost** [comment]
The help wanted label is more for things where the app author needs help and/or contribution for this is highly appreciated. Not so much for things that won't be done by me because I consider it of such a low priority. Basically everything here in the issue tracker marked as enhancement is "you are welcome to implement this".

**Comment by peternewman** [comment]
Ah apologies, although that's not how it's used generally, or advised by GitHub, see for example:
http://github-help-wanted.com/

It's also contrary to what's in the repo's own contributing doc:
https://github.com/streetcomplete/StreetComplete/blob/master/CONTRIBUTING.md#development

> If you need to find things where help is especially appreciated have a look at the issues tagged with "help wanted".

Also doesn't it make sense differentiating the stuff you've personally chosen not to do as other people may chose to prioritise that stuff knowing it's got one less developer looking at it?

Or to put it another way, what would you tag for a minor bug (i.e. something which isn't an enhancement) which you didn't think was high enough priority to fix so someone like @FloEdelmann might be able to find it? (Yes I'm really being that shameless :grin: )

For example:
https://github.com/streetcomplete/StreetComplete/issues/1821#issuecomment-766409894 (although perhaps you didn't see it as I re-opened it)
#1635
https://github.com/streetcomplete/StreetComplete/issues/2527#issuecomment-770251421
Or something like https://github.com/streetcomplete/StreetComplete/issues/2384#issuecomment-749131565
#1934

To be clear, so it's not misinterpreted, I’m not expecting someone to fix any or all of the above, but I'm aware from other projects I'm involved with that either there may be minor little niggles people have (which is how I started getting involved with that project), or some people may have a stronger interest to fix something on a more niche platform (in your case perhaps a minor bug in an older Android platform).

**Comment by Lee-Carre** [comment]
Just tuppence;

In Jersey, it's quite common for buildings to have both addr:housenumber and addr:housename. So much so that both are included in the postal address.

It would be pleasing to add both via StreetComplete. At the moment, I use Vespucci in such cases.

There are also times when a house doesn't display a number, but this can be deduced from its neighbours.

**Comment by mnalis** [comment]
@Lee-Carre  I would be against deducing (that is, guessing) the number, as SC is supposed to be primarily tool for **surveying what is on the ground**, not guessing.

For example, in Croatia, using logic to guess the housenumber will quite often give incorrect results... Let's say you have a road with houses marked 18,20,22,24,26,x,30,32,34... One might deduce that x=`28`, but quite often it is actually `26a` or `26/1` or `bb` (or something even stranger and out of line, like `114`), and `28` was either demolished decades ago, or (even worse) is at different location.

**Comment by Lee-Carre** [comment]
@mnalis

> I would be against deducing (that is, guessing) the number, as SC is supposed to be primarily [a] tool for **surveying what is on the ground**, not guessing.

I entirely concur, and didn't mean to suggest otherwise (certainly not when using SC which sets source=survey). I've advocated the point you make, elsewhere, recently.

At most, I was thinking of using the likes of Vespucci and explicitly setting source:housenumber=extrapolation or similar, to make clear that it's an assumption rather than verifiable fact.

I should've made this distinction clearer in my original.

> … One might deduce that x=28, but quite often it is actually 26a or 26/1 or bb (or something even stranger and out of line, like 114), and 28 was either demolished decades ago, or (even worse) is at different location.

I can relate, there are similar oddities here, also. Sometimes the distance interval between numbers isn't even consistent along the same road. That's European countries for you; centuries of paving cow-paths, ad-hoc changes, kludges, hacks, and bureaucratic regulation. Makes me see the sense, sometimes, in how the Yanks design their road-grids.

I was thinking of much simpler, obvious situations, in which there probably **was** a sequential number but has since been removed. For example [Berkeley House, Beach Road](http://www.openstreetmap.org/way/210697286). It's in a series of 5, with its immediate neighbours being #3 and #5. Though, it doesn't **display** a number, only a name.

But, yes; surveying must be verifiable, else all bets are off.
