### ISSUE TITLE
Ask does this building have a name?

### ISSUE THREAD

**Issue by andrewharvey** [streetcomplete/StreetComplete#2545]
### General
Affected tag(s) to be modified/added: [](https://wiki.openstreetmap.org/wiki/Key:name)
Question asked: What is the name of this building?

Applicable to building=office and building=apartments (country specific)

### Checklist
Checklist for quest suggestions (see guidelines):
- [x] 🚧 To be added tag is established and has a useful purpose
Yes established and according to https://taginfo.openstreetmap.org/tags/building=apartments#combinations and https://taginfo.openstreetmap.org/tags/building=office#combinations they have a name tag 7.7% and 40% of the time respectively already in OSM.

- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary 

Yes, signage on the building/entrance.

- [x] 💤 Not an overwhelming percentage of elements have the same answer (No spam)

Could be country specific, but given that 7.7% and 40% already named, enough elements will have a answer that's not no name.

- [x] 🕓 Applies to a reasonable number of elements (Worth the effort)

Yes, lots of apartment or office buildings exist.

I've branched this out from #2540 as I don't want to hijack @peternewman's request which was to ask this as part of the address quest.

My suggestion is to ask this independently of the numbered address and as part of the does this feature have a name quest, since most of the time (at least for around me) all these named buildings will also have a street address number.

**Comment by michaelblyons** [comment]
Just to clarify: is this for adding `name` or `addr:housename`?

**Comment by mnalis** [comment]
That seems to be the crux of the problem with this issue... But both tickets seem to me to address the same problem, it seems to me that this ticket confuses `name` tag with `addr:housename` tag for some reason.

`building=office` with `name=*` tag means it is an office of the company/agency with that name (which is the tag with [39.62%](https://taginfo.openstreetmap.org/tags/building=office#combinations) combinations @andrewharvey mentions). However, if the building ITSELF has a name, as this quest seems to imply, then it is `addr:housename` tag, which is used order or magnitude times less.

If that is the case, then there is no need for new issue, and this issue seems to propose tagging a building of type `building=office` which has not only `addr:housenumber` but also `addr:housename` -- which is used much less often, at [3.73%](https://taginfo.openstreetmap.org/tags/building=office#combinations)

That might still be reasonable for office buildings, if user manually selects `has both housenumber and housename` answer (instead of spamming all users with `does this office building also have a name?`-alike quest).

For `building=apartments`, `addr:housename` is [used only 0.70% times](https://taginfo.openstreetmap.org/tags/building=apartments#combinations), and not 7.73% 

Also, as I mentioned in https://github.com/streetcomplete/StreetComplete/issues/2540, it seems to be somewhat country-specific. While there do exist few office buildings in Croatia that has a building name (as opposed of offices of a company which has a name), that is not a practice with apartments at all.

**Comment by westnordost** [comment]
This does not sound eligible then.

> 💤 Not an overwhelming percentage of elements have the same answer (No spam)

**Comment by peternewman** [comment]
The wiki doesn't seem to be as clear cut:
https://wiki.openstreetmap.org/wiki/Key:addr#Commonly_used_subkeys
Even:
https://wiki.openstreetmap.org/wiki/Talk:Key:addr#addr:housename_vs._name

It's not particularly consistent on OSM either, picking some random examples:
https://en.wikipedia.org/wiki/Eland_House
https://www.openstreetmap.org/way/26869552

https://www.openstreetmap.org/way/179717015

https://en.wikipedia.org/wiki/Canadian_Pacific_Building_(London)
London one doesn't seem to be tagged from a search or browse, but the Canadian one is...
https://www.openstreetmap.org/way/137923156

Also things like university campuses, big or small, such as:
https://www.openstreetmap.org/way/77109286

Or companies with large sites:
https://www.openstreetmap.org/relation/7695843

> This does not sound eligible then.
> 
> > zzz Not an overwhelming percentage of elements have the same answer (No spam)

Do you have a rough ballpark you aim for @westnordost , it might help to add it to the FAQ/template to help others in future.

If I've got the maths right, 1/4 of apartments have housename in the SE of England.

> For `building=apartments`, `addr:housename` is [used only 0.70% times](https://taginfo.openstreetmap.org/tags/building=apartments#combinations), and not 7.73%

But name is used 7.73% @mnalis , which either means there's some name usage I'm not aware of, or people are following the wiki to the letter.

Also to be a fair test, we should really look at the stats for places which have addr:housenumber set (for example), but not housename, otherwise you're also allowing all the places someone has done an initial survey of for example, or just chosen the type from a vehicle or whatever, rather than the ones where they might have gathered comparable data.

**Comment by peternewman** [comment]
> That seems to be the crux of the problem with this issue... But both tickets seem to me to address the same problem, it seems to me that this ticket confuses `name` tag with `addr:housename` tag for some reason.

Specifically/primarily for houses with a name AND number, was my quest, which can't be handled with a new quest as it would definitely be spammy (~0.5% on my street for example), so the only (non-note) option is to answer both at once. Whereas in some places, apartment names are much more common, I'd say quite a few have one but not the other, e.g. a tower block may just have a name in the UK, not a street number.

**Comment by andrewharvey** [comment]
> Just to clarify: is this for adding name or addr:housename?
> That seems to be the crux of the problem with this issue... But both tickets seem to me to address the same problem, it seems to me that this ticket confuses name tag with addr:housename tag for some reason.

My intention was for `name` because generally I didn't see these building names as part of the addressing system. But looking into this further perhaps `addr:housename` is the correct tag. The wiki is not clear as to what is `name` on an apartment of office building vs `addr:housename`.

This issue is specifically about a "building name", is there any discussion or otherwise on if "addr:housename" is for the "building name" and what it would mean to have `building=apartments` with both a `name` and an `addr:housename`?

> building=office with name=* tag means it is an office of the company/agency with that name (which is the tag with 39.62% combinations @andrewharvey mentions). However, if the building ITSELF has a name, as this quest seems to imply, then it is addr:housename tag, which is used order or magnitude times less.

That's certainly not how I understood it. building=office could be an office building with multiple tenants and without an office=* tag then the name tag means the building name.

However if it's a single tenancy building and you have building=office + office=* + name=, then it's not clear if name is the building name or company name and it doesn't look like this is well defined currently.

>> For building=apartments, addr:housename is used only 0.70% times, and not 7.73%
>
> But name is used 7.73% @mnalis , which either means there's some name usage I'm not aware of, or people are following the wiki to the letter.

Exactly. I suspect these two are intermingled thorough the OSM database, so the true number of named apartment buildings is probably 0.7 + 7.73 %.

> Specifically/primarily for houses with a name AND number, was my quest, which can't be handled with a new quest as it would definitely be spammy (~0.5% on my street for example), so the only (non-note) option is to answer both at once. Whereas in some places, apartment names are much more common, I'd say quite a few have one but not the other, e.g. a tower block may just have a name in the UK, not a street number.

One reason why I'm advocating a separate quest is these buildings might already have an address number tagged,  but could still have a yet to be mapped name. If you have a combined quest how would you re-ask about the building name when the address number is already tagged?

**Comment by mnalis** [comment]
> That's certainly not how I understood it. building=office could be an office building with multiple tenants and without an office=* tag then the name tag means the building name.
> 
> However if it's a single tenancy building and you have building=office + office=* + name=, then it's not clear if name is the building name or company name and it doesn't look like this is well defined currently.

Yes, that is exactly what I wanted to show, that using `name` in this case is ambiguous. I'll believe that _some_ of the `building=office` + `name` might have intended it to be building name (but probably only the ones **without** `office=` tag, ie. multipurpose office building for several companies), but majority of them is _probably_ the one-company offices (especially if the `office=` tag is supplied). But there is just no way to know for sure...

So, the number of office building itself having name is somewhere between 3.73% and 39.62%, probably much closer to the lower value (we might get somewhat more precise if we discard entries having `office=` tag or other identifying information like `website`, `phone` etc., but I'm not sure such calculation is worth the effort - at least I don't know of quick and easy way to extract that statistics, it is not foolproof, and it's not guaranteed that uncertainty would be much reduced).

> > Specifically/primarily for houses with a name AND number, was my quest, which can't be handled with a new quest as it would definitely be spammy (~0.5% on my street for example), so the only (non-note) option is to answer both at once. 

I concur, spamminess is definitely my main concern here (if it is proposed as a new quest). Answering both at once in existing housenumer is only realistically looking non-spammy option to me (implemented akin to the current `have no housenumber but has housename` answer).

> One reason why I'm advocating a separate quest is these buildings might already have an address number tagged, but could still have a yet to be mapped name. If you have a combined quest how would you re-ask about the building name when the address number is already tagged?

I'm not sure how the separate quest would work - even if you could somehow select buildings likely to have both a housename and housenumber without being spammy (which I doubt is doable, at least at worldwide level), how exactly do you envision to mark buildings for which the user selects  it has only one or the other (in order not to ask the same question forever)?

**Comment by andrewharvey** [comment]
Similar to how SC adds `nohousenumber=yes` you could add either `noname=yes` or `nohousename=yes` to indicate the negative.

I understand concerns that this might feel spammy, but in some areas of the world where it's quite likely to have a building name, this is very useful data SC could help survey. You could easily only enable it to opt in countries or regions.

**Comment by westnordost** [comment]
I'll close this as will not fix because too few apartment buildings have names that this makes sense to ask.
Maybe it is different in the area you live, but this is how it looks in my area.

Grey are apartment buildings with no name, red/green are apartment buildings with a name:

![image](https://user-images.githubusercontent.com/4661658/106955341-69bf3b80-6735-11eb-997e-f4b1e544b6a0.png)
http://overpass-turbo.eu/s/13ei

And those in that view that do have a name, that's actually only because an amenity inside the building (on ground level) has been mapped on the same object as the whole building.

The area looks like this:

![image](https://user-images.githubusercontent.com/4661658/106955980-43e66680-6736-11eb-99ac-492ba246f244.png)
https://www.google.de/maps/@53.5759125,9.940878,3a,75y,166.84h,100.12t/data=!3m9!1e1!3m7!1sjy7l-vbIDu7cZ2gOUPeq9A!2e0!7i13312!8i6656!9m2!1b1!2i29

And this is a very typical picture of any urban (=not dominated by detached houses) residential district in Europe.

**Comment by westnordost** [comment]
Given, not that it changes much, but most buildings in the residential area mentioned above is about 100 years old.

However, it is not any different for apartment buildings of younger construction date. The name shown on the sign is not hte name of the individual building but of the building project / whole apartment complex. Given that this name is not recorded in OpenStreetMap, I strongly assume that there is not any sign that indicates the name after the construction was finished
![image](https://user-images.githubusercontent.com/4661658/106956795-6927a480-6737-11eb-8fb8-f40c47e342d5.png)
https://www.google.de/maps/@53.5889312,9.9621732,3a,70.4y,336.44h,87.19t/data=!3m6!1e1!3m4!1sdQAm3cmy0sPXJEJ09hrgNg!2e0!7i13312!8i6656

**Comment by andrewharvey** [comment]
> I'll close this as will not fix because too few apartment buildings have names that this makes sense to ask.
> Maybe it is different in the area you live, but this is how it looks in my area.

No problem, it's your call. To be frank I think it's a little short sighted to only look at this from your own personal lens, but this equally holds true for me too. If there are countries that have a lot of apartment or office buildings without names, then SC has good support for only enabling the quest in set regions.

in NSW, AU
834 of 6855 building=apartments with a name.
173 of 424 building=office have a name.
828 addr:housename tags exist.

It's okay though, maybe I'll try to make an effort in surveying more with other apps instead, just much prefer the SC interface it makes mapping on the go so much faster and easier than all other apps I've tried.

**Comment by mnalis** [comment]
@andrewharvey Alternatively, you can enter one piece of data (like `addr:housenumber`) and long-press (leave note) functionality to leave a note for another piece of data (that's what I use when I want to solve addressquest when it's not available yet due to missing prerequisites, for example)

I've taken a look at random part of Sydney, and it does seem that it has more of those names, but they look strangely mapped: for example on http://overpass-turbo.eu/s/13fn it seems it is common to **mark several buildings with a same `name`**; in this example there are 3x `name=Arena`, 2x `name=Soho`, 2x `name=Ashton tower`, etc. They seem to be grouped together though (at least in this case).

It makes me wonder if it should in fact be `landuse=commercial` (or `landuse=residental`) area with `name` tag?

**Comment by goldfndr** [comment]
As an additional data point, I've seen that here locally (US/WA), if a building has an elevator, the building's name (not just address) would be on its periodic certification that they're required to post.

**Comment by peternewman** [comment]
Nice overpass link @westnordost . Here's some other heavily named areas in London:
http://overpass-turbo.eu/s/13fD

Or busier/wider:
http://overpass-turbo.eu/s/13fF

Likewise in a smaller town/city:
http://overpass-turbo.eu/s/13fG

It even happens in Wales:
http://overpass-turbo.eu/s/13fH

Some random bit of France:
http://overpass-turbo.eu/s/13fK

Although I think this is perhaps a fairer comparison, which highlights stuff with a housenumber in blue as well, e.g. in Australia, most of the places without a name are just apartment and nearmap, seemingly no on-the-ground information has been gathered (or possibly height/levels sometimes); I realise this isn't perfect logic, I couldn't work out how to or a few other tags:
http://overpass-turbo.eu/s/13fP

> @andrewharvey Alternatively, you can enter one piece of data (like `addr:housenumber`) and long-press (leave note) functionality to leave a note for another piece of data (that's what I use when I want to solve addressquest when it's not available yet due to missing prerequisites, for example)

That's an option, similar to what I mentioned in #2540 but it's a lot more work all round and more risk of errors/mis-mapping. By that argument, SC development could stop entirely and we could do everything with notes!

> I've taken a look at random part of Sydney, and it does seem that it has more of those names, but they look strangely mapped: for example on http://overpass-turbo.eu/s/13fn it seems it is common to **mark several buildings with a same `name`**; in this example there are 3x `name=Arena`, 2x `name=Soho`, 2x `name=Ashton tower`, etc. They seem to be grouped together though (at least in this case).

I think the two adjoined Arena should probably be building:part (at a guess), and possibly the third too. Looking on satellite/StreetView it looks like Soho is actually one building with an entrance ramp and underground parking. It looks a bit ambiguous on some aerial photography so it's probably mis-mapped.

Regarding the second Ashton Tower ( https://www.openstreetmap.org/way/560426537 ), it's directly on top of:
https://www.openstreetmap.org/way/547858913

Which is the same height, so I'd again suspect mis-mapping. Also not visible on the rendered map unless you really go digging.

> It makes me wonder if it should in fact be `landuse=commercial` (or `landuse=residental`) area with `name` tag?

I would have thought it should perhaps be addr:housename and putting that on an area, rather than the object, would make it a real pain to interpolate.
