### ISSUE TITLE
wrong addition barrier=kerb on a highway=crossing node with a tactile_paving quest

### ISSUE THREAD

**Issue by Marc-marc-marc** [streetcomplete/StreetComplete#2564]
version 5 https://www.openstreetmap.org/node/2922045224/history
SC add a barrier=kerb on a highway=crossing node 
what is even stranger is that the quest of the version 5 is about the presence of tactile_paving.
https://www.openstreetmap.org/changeset/98920503
version 6 is about the kerb.

**How to Reproduce**
no idea

**Versions affected**
30.0

**Comment by matkoniecz** [comment]
That is because someone incorrectly applied `footway=sidewalk` on entire https://www.openstreetmap.org/way/506462525#map=19/43.82731/5.78192 despite that Western section should be `footway=crossing` (but can be caught, I though that I implemented in way that would catch that)

Thanks for catching this and for making a report.

**Comment by westnordost** [comment]
Someone edited the way to have `footway=crossing` now. It is going to be hard to ascertain how the situation looked like when the kerb was tagged.

**Comment by matkoniecz** [comment]
![screen03](https://user-images.githubusercontent.com/899988/107850933-73683380-6e06-11eb-8232-48a17dd1b5e1.png)

`footway=sidewalk` was reach `hioghway=crossing` node and transitioning there into `footway=crossing`

**Comment by westnordost** [comment]
Ah, so that was the same situation as discussed in .... well, I can't find the ticket anymore for the hell of it! I remember it was a long discussion with someone from Italy and in the end, he closed it himself, I think.

In any case, not sure if that was mentioned in that ticket that I can't find right now, but the situation as displayed by @matkoniecz in his last post could be excluded by excluding nodes that are part of any other (road)way.

**Comment by matkoniecz** [comment]
> Ah, so that was the same situation as discussed in .... well, I can't find the ticket anymore for the hell of it! I remember it was a long discussion with someone from Italy and in the end, he closed it himself, I think.

No, that was different. They had mapped `barrier=kerb` and `footway=crossing` not ending it but going farther, and turning into `footway=sidewalk` after kerb, but before reaching `footway=sidewalk` line along road.

**Comment by Helium314** [comment]
> I can't find the ticket anymore for the hell of it!

this one? https://github.com/streetcomplete/StreetComplete/issues/1305#issuecomment-759439593

**Comment by matkoniecz** [comment]
@Helium314 Yes! So it turns out that there was no separate issue :)

See https://github.com/streetcomplete/StreetComplete/issues/1305#issuecomment-761003320 for geometry summary.

**Comment by westnordost** [comment]
Okay right, so it is a different issue.
