### ISSUE TITLE
Entering a large range of street numbers that are only odd or even

### ISSUE THREAD

**Issue by codeinabox** [streetcomplete/StreetComplete#2589]
**Use case**
Many of the streets that I am surveying around London have terrace houses modelled as one big area and most of these have a lot of house numbers that are just odd or even. For example [this change set](https://www.openstreetmap.org/changeset/99439648) was a group of terrace houses with all even numbers starting from 38 and going up to 64. I tried to enter this in the app but the input area was too small for so many numbers so I ended up having to enter them afterwards on the desktop with the iD editor 

**Proposed Solution**
I propose there is a way you can enter a start and finish number and select odd or even only, which will generate a list of comma separated values based on that eg 2 to 8 even only would generate 2,4,6,8

The flow could potentially be something like this for the street number quest

1. Other answers
2. It has multiple house numbers
3. Ask if the numbers are even or odd only
4. Field for start number, end number and toggle for odd or even only

**Comment by westnordost** [comment]
Specifying `2,4,6,8` is only marginally more helpful than `2-8`, the latter is something that the app recommends. But both should only be seen as temporary because the best is of course to add an address node for each address separately. This is simply not possible with this app (yet).
So, the "final" way to solve this is always to edit it with iD later on - both tagging `2,4,6,8` or `2-8` or taking a couple of pictures (leave note) are almost equally helpful for this case. Adding such a range-odd-even-feature would ony complicate the simple interface with only very little, if any, gain.
