### ISSUE TITLE
Use "survey:date" instead of "checked_date"

### ISSUE THREAD

**Issue by tguen** [streetcomplete/StreetComplete#2592]
The "is this still here?" quest adds the `checked_date` tag to objects. According to [the wiki page for `survey:date`](https://wiki.openstreetmap.org/wiki/Key:survey:date), the difference between it and `check_date` is that the latter does not imply a survey (on-site verification). Since StreetComplete is intended to be used on-site (it asks "are you sure" if user location is elsewhere or unknown), `survey:date` seems more appropriate. Alternatively, the app could use `survey:date` only if the user has location services enabled and is known to be located nearby.

**Comment by HolgerJeromin** [comment]
I am surprised that I do not find this tag in the initial discussion #2074
Your suggestion has 800.000 the current used tag only 150.000

But it is parsed for checking:
https://github.com/streetcomplete/StreetComplete/blob/cc7624d2f8c83c037f4a078eb56dadd3b1cd80a2/app/src/main/java/de/westnordost/streetcomplete/data/meta/ResurveyUtils.kt#L67-L72

**Comment by RubenKelevra** [comment]
A check_date means that a mapper has checked that this data is still correct. Which usually requires a survey. How the data was checked is added to the changeset via the source tag.

The check_date on the other hand is limited to the one key its marking, so you can for example check that a shop is still there without having to verify the opening hours. 

A survey:date on the other hand would require a complete check by the user of all tags associated with the POI.

So it's a higher quality check, but on the other hand out of scope in terms of complexity for StreetComplete, since the mapper would need to understand all tags associated with the POI stored in the database.

StreetComplete's approach is to have a very simple UI and braking complex tasks down. So a simple check for existence is usually enough for most objects, as the attributes doesn't change much.

But marking all attributes as "surveyed" when the mapping actually only checked the existence is wrong IMHO.

**Comment by tguen** [comment]
> How the data was checked is added to the changeset via the source tag.

It should be, but often isn't.

> A survey:date on the other hand would require a complete check by the user of all tags associated with the POI.

I've never heard this before. It's safe to assume that the wiki page of such a commonly used tag would be accurate, and it says no such thing. I'm not even sure of a practical way to verify *all* tags on an object. I suppose I could go to osm.org and query a feature to see and verify all of it's tags while on-site, but I'm sure that rarely happens. It's a nice idea, but that's not the way the tag is actually used.

The wiki page for `check_date` says individual tags can be verified by using it as a prefix to the tag, e.g. `check_date:opening_hours`. Using the tag by itself can be assumed to indicate only that the feature exists, not that all tags are accurate. 

Neither tag's page indicates any difference between them except that `survey:date` implies on-site survey, while `check_date` could just be the date on Mapillary images for example.

**Comment by mnalis** [comment]
@tguen note that [survey:date](https://wiki.openstreetmap.org/wiki/Key:survey:date) wiki does say:

> "check_date=* similar but more general tag, does **not** specify that the **information was checked by survey**"


which would imply that main difference is that `survey:date` (as opposed to `check_date`) "**does** specify that the information (ie. not just existance) **was checked** by survey"

**Comment by Helium314** [comment]
One difference between `survey:date` and `check_date` (according to the wiki) is that for `check_date` the use of `check_date:<tag>` is encouraged, while in `survey:date` there is nothing about survey of particular tags.

**Comment by westnordost** [comment]
I chose `check_date` over `survey:date` mostly because of https://github.com/streetcomplete/StreetComplete/issues/2592#issuecomment-782710684

But @mnalis has a point too, the source does not belong in a tag on an element (`source=bing` on roads, anyone?), so `survey:date` reeks a bit of that.

And as @mnalis said, both tags are heavily used, so any software that interprets these tags will need to look at both tags anyway. 
Regarding the usage of `survey:date`, it looks like a few hundreds of thousands at least of it was added due to large imports. So, one needs to be a bit cautious when looking at taginfo alone.

So, I am closing this as I don't see any advantage in changing this.

**Comment by jengelh** [comment]
> I chose `check_date` over `survey:date` mostly because of [#2592 (comment)](https://github.com/streetcomplete/StreetComplete/issues/2592#issuecomment-782710684) [fine-grained timestamping using check_date:<subtag>]

Oh hell naw. Can SC please stop polluting the database with duplicated information? If the user is already at a POI checking one thing, have SC ask them to check all the things so we can do away with this braindead check_date:thing1 check_date:thing2 shit. What's next, `check_date:check_date`?

![Image](https://github.com/user-attachments/assets/17a7c1cb-27cb-492c-8431-8c9f2d9da70b)

**Comment by Cj-Malone** [comment]
Thanks for everyone who worked on this. It brings awareness to the age of data in OSM, and makes data consumers more confident in our data.

If I was consuming OSM, I probably wouldn't even use `opening_hours` if there is no `check_date:opening_hours`.
