### ISSUE TITLE
Suggestion: »How many cars can be parked here?«

### ISSUE THREAD

**Issue by ygra** [streetcomplete/StreetComplete#2595]
### General
Affected tag(s) to be modified/added: [capacity](https://wiki.openstreetmap.org/wiki/Key:capacity) for building=garages (perhaps it might work for smaller amenity=parking or amenity=parking_space as well)
Question asked: **How many cars can be parked here?**

### Checklist
Checklist for quest suggestions (see guidelines):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary 
  - For building=garages at least, the answer is not always obvious from aerial imagery. amenity=parking_space may be debatable, especially when each single space is marked.
- [x] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of elements (Worth the effort)
  - At least in suburbs and other parts where detached houses with garages are common

**Comment by peternewman** [comment]
This feels like it's probably a duplicate of https://github.com/streetcomplete/StreetComplete/issues/1748 or near enough.

Or are you referring to garages with doors where you could count the single or double doors?

**Comment by ygra** [comment]
Sounds similar, but yeah, this would be about those things:

![](https://user-images.githubusercontent.com/1692688/108608485-71364400-73c7-11eb-869d-5f61557f32b2.jpg)

which are quite common, at least here, and it's fairly easy to answer when outside, but isn't always clear from the aerial images.

**Comment by peternewman** [comment]
> Sounds similar, but yeah, this would be about those things:

Ah, I was thrown by this comment:
> perhaps it might work for smaller amenity=parking or amenity=parking_space as well)

Yeah this was what was suggested in the previous issue:
> Counting parking spaces for anything large, like a supermarket parking lot or multi-storey car parks should really not be in scope for this. No idea whether features can be selected by area, so smaller streetside parking amenities could be selected, while larger features would not be.

**Comment by westnordost** [comment]
I've read #1748 again. Yeah, it is not a duplicate, and an argument that could be brought forward is that even with detailed aerial imagery, one can only estimate based on the size how many garages there are because you need to see the garage doors.

However,
1. what is the useful purpose of this information? Garages are usually privately owned, so the `capacity` should not count towards any kind of "parkability index" for an area. And in any case, such index wouldn't need an exact number of capacities for garages anyway, estimating by size is perfectly fine
2. is `capacity` even something that may or should be tagged on a `building`? I think not! Sometimes, surface parking areas are mapped to include the garages in that parking, sometimes they are mapped to not include the garages. If now the capacity is added to both, there potential ambiguity about what the capacity of the whole parking refers to.

**Comment by matkoniecz** [comment]
Also, for private garages it is often hard to estimate actual capacity anyway. At least in Poland it is normal to have something that was originally garage to be converted into a storage space. So something intended as two car garage (and still looking like that from outside) may have space for one or zero.

**Comment by ygra** [comment]
Granted, I haven't thought too much about this; I've filled out the information for those I know in my neighborhood as capacity is a tag that's simply suggested by default by iD for those buildings, so the implication was that it was at least somewhat useful for certain purposes. Perhaps that was not the best assumption ;-) (I see now that the capacity wiki page does not list building:garages as a useful combination as well).
