### ISSUE TITLE
Quest idea: Is wall close to a highway a noise barrier?

### ISSUE THREAD

**Issue by matthiasfeist** [streetcomplete/StreetComplete#2602]
### General
**Affected tag(s) to be modified:** if a [barrier=wall](https://wiki.openstreetmap.org/wiki/Tag:barrier%3Dwall) is in close proximity of a highway
**Question asked:** Is this wall a [noise barrier](https://wiki.openstreetmap.org/wiki/Tag:wall%3Dnoise_barrier)?

### Checklist
Checklist for quest suggestions (see guidelines):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary 
- [x] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of elements (Worth the effort)

### Ideas for implementation

**Element selection:** 
`barrier=wall` without `wall=noise_barrier` in close proximity to `highway=secondary`, `primary` or `motoryway` (maybe max 5 meters from the highway)

**Comment by FloEdelmann** [comment]
Proximity to railway tracks should also be considered.

**Comment by matkoniecz** [comment]
>  Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)

What would be tagged if answer is "no"?

**Comment by matthiasfeist** [comment]
@matkoniecz that is a good question. If the answer is "no" I guess the quest should not do anything at all.

**Comment by matkoniecz** [comment]
In such case it fails mandatory

> Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)

**Comment by matthiasfeist** [comment]
Ah damn. I didn't think of that. I guess then it could be converted in a quest like *"Which type of wall is this"*... But I'm not sure that this is actually interesting enough...

**Comment by westnordost** [comment]
Hmm, just 7% of all `barrier=wall` have a subtag with `wall=*`.

Looking at the wiki page for [`barrier=wall`](https://wiki.openstreetmap.org/wiki/Tag:barrier%3Dwall) though, I think I know why: Because most walls are just "normal" walls and there is just no tag for that. For a subtag to be tagged with StreetComplete, the subtag needs to be defined "completely", meaning that for any wall it must be possible to find a subtag, defining the type of wall.

The wiki page doesn't define that, worse still, it mixes in a separate data point - material. That's not well thought through and I fear, not eligible as a quest in StreetComplete.

**Comment by matthiasfeist** [comment]
Yeah that makes sense. 
Thanks for all the nice input 🙂 I'll close this issue now.
