### ISSUE TITLE
Quest: Gender-segregated toilets

### ISSUE THREAD

**Issue by cloudrac3r** [streetcomplete/StreetComplete#2603]
### General
Affected tag(s) to be modified/added: [gender_segregated](https://wiki.openstreetmap.org/wiki/Key:gender_segregated)
Question asked: **Is XY toilet gender-segregated?**
Answers:
- Yes (entirely gender segregated, `gender_segregated=yes`)
- Mixed/No (some toilets that are not gender segregated are available, `gender_segregated=no`)

### Checklist
Checklist for quest suggestions (see guidelines):
- [x] 🚧 To be added tag is established and has a useful purpose
It is established. One alternative to `gender_segregated` seems to be [`unisex`](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dtoilets#Gender_neutral_toilets), but as the page discusses, this has issues.
It is useful. People whose gender presentation does not fit into the binary of male/female need to use the bathroom too without being harassed. It's similar to knowledge about whether the bathroom has disabled access or not.
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary 
- [ ] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
I don't know the answer to this question. I would be _more than_ willing to spend time surveying bathrooms in my local area and summarising the results, if you'd like hard numbers on how many bathrooms are gender segregated or not.
- [x] 🕓 Applies to a reasonable number of elements (Worth the effort)
Applies to all bathrooms.

### Ideas for implementation

Should work in pretty much the same way as the "does this bathroom have disabled access" quest.

The only main answers needed are listed above. There are no special "can't answer" options needed.

I can create a vector icon image for the map marker if you want.

I do not know how to set up an android development environment, so I cannot code and test the feature on my own phone (unless I can work all that out).

**Comment by matkoniecz** [comment]
Just 119 uses worldwide - https://taginfo.openstreetmap.org/keys/gender_segregated

And there is a history of problematic tagging here: https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dtoilets#Gender_neutral_toilets

Making full scale proposal is not mandatory (though https://wiki.openstreetmap.org/wiki/Proposal_process has some benefits), but have you discussed this tag on place like tagging mailing list or other place with decent amount of people from different locations?

**Comment by cloudrac3r** [comment]
Thanks for the reply.

I hadn't seen the taginfo site before. You're right, 119 is a very small number. `unisex` has been used 61,755 times.

I haven't been on the mailing list. I'm pretty new to the community, I just try to read the help guides to know what the correct meaning of tags I use is. Perhaps it would be better to try to ratify the `unisex` tag on the lists... if that hasn't already been discussed to death.

I'll take a look at the list archives and see what I can find.

**Comment by cloudrac3r** [comment]
I checked back a year in the `Tagging` and `Diversity-talk` lists, searching for `unisex` or `gender` in the subject line, and actually couldn't find any discussions. Do you think it would be best for me to bring up the topic in those lists, and then come back here if any decision is reached?

**Comment by westnordost** [comment]
Hm, to me, unisex seems to be pretty clear what it is. I.e. a "normal" toilet with segregated sexes is not unisex. I read some of the discussion on diversity-talk and some people seem to think otherwise. It seems what has been brought up in the discussion was summarized in the wiki

> 1. unisex=yes always means a gender neutral toilet, gender segregated toilets should be tagged unisex=no+female=yes+male=yes. male=yes+female=yes cannot be replaced with unisex=yes
> 2. unisex=yes is a shorthand for male=yes+female=yes, and can be used for a unisex, gender neutral toilet, or one with separated female & male sections, and if you see something tagged female=yes+male=yes, you can replace them with unisex=yes.
> 3. unisex=yes indicates an entrance/area which is available to all. 'Family toilets' can contain this tag.

Interpretation 2 and 3 make no sense to me.

**Interpretation 2**: If `unisex=yes` was a shorthand for `male=yes` and `female=yes`, there would be no sense to have this tag at all. To save a few characters in the database? Even if that would be a meaningful reason, that doesn't fly because `unisex=no` would then be superfluous as it would carry no meaning in itself but would require another `male=yes` for example to have any meaning. I am sure that this interpretation stems from a misunderstanding about what "**implies**" means. Unisex toilets imply that males and females can use this toilet, but toilets for both males and females don't imply that it is a unisex toilet. 

**Interpretation 3**: Ok, so micromapping toilets. But well, an entrance area of toilets is not a toilet. Noone can answer the call of nature in the entrance area. Or maybe I didn't understand what "family toilets" are supposed to be.

---

In any case, I'd be okay with a quest that asks whether a toilet is unisex and shortly describes what unisex means as defined in the wikipedia and tags `unisex=yes/no`. This quest could be asked for `amenity=toilet` but as the "toilets wheelchair accessible?" quest be disabled by default because it may require one to enter to find out and also very low in priority because the data is not used yet by any data consumer.
In terms of interface, it may be best to combine this with `male=yes` etc. so there are four selections: female only, male only, both sexes (segregated), both sexes (not segregated)

**Comment by matkoniecz** [comment]
> If unisex=yes was a shorthand for male=yes and female=yes, there would be no sense to have this tag at all. 

Sadly we have some tags and tagging schemes that make no sense at all. Though I agree that such tagging would be a clearly bad idea.

**Comment by cloudrac3r** [comment]
> Interpretation 2 and 3 make no sense to me.

I agree, for the reasons you stated, but apparently some people do tag it using those schemes. Since this is the case, would it make the data we collect useless? Since it could be interpreted in multiple ways.

Or, we could set both `unisex` _and_ `gender_segregated` to remove ambiguity while still contributing to the larger tag set.

> ...quest be disabled by default because it may require one to enter to find out and also very low in priority because the data is not used yet by any data consumer.

For sure, that makes sense.

> In terms of interface, it may be best to combine this with male=yes etc. so there are four selections: female only, male only, both sexes (segregated), both sexes (not segregated)

It's possible for a building to have both segregated and non-segregated facilities, so the UI would need to allow several combinations. I think the best way to do it would be a list of checkboxes, and any of them can be ticked or unticked independently: [] Male, [] Female, [] Unisex. Keen to hear other UI ideas!

**Comment by westnordost** [comment]
Yeah, but as stated, `gender_segregated` is not used enough. No new tags should be introduced via this app. This would bypass the community process.
I don't really ... know what to do to clear up this stupid situation that there are three interpretations of the unisex tag documented in the wiki and maybe they are really actually used this way here and there. Maybe the best would be a proposal...

**Comment by cloudrac3r** [comment]
I just found out that iD editor uses a list of _radio_ buttons for specifying the sex of a toilet. If we assume that iD is the most common data entry method for the sexes that can use bathrooms (is this a reasonable assumption? please tell me!) then that pretty much means the `unisex` tag is useless for the purposes described here, and a new tagging scheme is needed.

![image](https://user-images.githubusercontent.com/28467304/109139320-429ddc00-77c0-11eb-9e08-1e8277516f89.png)

Since a new tagging scheme is needed, I'll have to bring up this discussion on the mailing lists, then get back to you here.

**Comment by cloudrac3r** [comment]
Just found these relevant issues in iD:

- https://github.com/openstreetmap/iD/issues/7427
- https://github.com/openstreetmap/iD/issues/8340
- https://github.com/openstreetmap/iD/issues/6569

>  AFAIK it's been this way since iD was launched about 6 years ago.

**Comment by westnordost** [comment]
Jesus. Ok, then the only way forward is a proposal. A pity, cause unisex is such a well known term.

If you want to go ahead with a proposal, regarding the name, I'd suggest sex_segregated cause that still has some similarity to the unisex term and shows up on the wikipedia in the unisex article as the opposite as that:

"Public toilets are commonly sex segregated but if that is not the case, they are referred to as unisex public toilets. "
 https://en.m.wikipedia.org/wiki/Sex_segregation

Am 25. Februar 2021 11:28:21 MEZ schrieb Cadence Ember <notifications@github.com>:
>Just found these relevant issues in iD:
>
>- https://github.com/openstreetmap/iD/issues/7427
>- https://github.com/openstreetmap/iD/issues/8340
>- https://github.com/openstreetmap/iD/issues/6569
>
>>  AFAIK it's been this way since iD was launched about 6 years ago.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/streetcomplete/StreetComplete/issues/2603#issuecomment-785789711

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by westnordost** [comment]
I'll close this issue as this tagging needs to be resolved not-here first and when it is, it is better to create a new ticket that references the old one so that one doesn't need to read through all this again.

**Comment by rory** [comment]
This is a topic I care about and have been doing some work around for several years. I favour the 4 option choice too.

Relevant too: https://wiki.openstreetmap.org/wiki/Diversity_Quarterly_Project/2018_Q2

Over the years I've seen this mistake, so a note to non-native English speakers: The word “unisex” very definitly means “one thing that applies to male and female”. A “unisex” toilet is one toilet that is _not_ gender segreated.

**Comment by westnordost** [comment]
I did not mention an option 4

**Comment by mnalis** [comment]
I read that as "4-option choice"... So not meaning "option number 4" but instead "that option which has 4 choices" which would be:

- only `unisex=yes` (meaning non-segregated toilets, each suited for both males and females)
- only `male=yes` (only male toilets)
- only `female=yes` (only female toilets)
- `male=yes` and `female=yes` (segregated male and female toilets; ie. separate toilets for males, and separate for females)

(which would be Westnordost option number one)

@rory Unfortunately, that fact that some word has some meaning in English dictionary, in often not closely related with how it is documented (much less used!) in OSM - which is ultimately the only thing that counts. 

For example, Webster defines `highway` as `a public way, especially: a main direct road`, while OSM has constructs like `highway=speed_camera` or `highway=street_lamp` which would be completely nonsensical in English, yet have clearly defined meaning in OSM.
(Other tags are even worse, and are actively misleading. For example, English speaking user might assume that `building=fire_station` is for marking buildings currently used by your Fire brigade, eg. for housing firefighting equipment and officers - which is not what that tag means)

**Comment by westnordost** [comment]
@rory, we basically came to the conclusion that iD preset implementation burnt that (`unisex`) tag - or maybe it was misunderstood this way before by people, but the implementation in iD cast this interpretation into concrete. As mentioned on the iD issue tracker, this was done long ago, we can't change the meaning of that tag now, after 5 years or so.

Really the only sensible way forward is to create a new tag, and maybe deprecate the old one.

**Comment by rory** [comment]
Perhaps it's not clear, but "unisex toilet", in english, means a non-gender segregated toilet. It means “all genders together in one 'room'”. I don't understand why you think it was ”burned”

**Comment by westnordost** [comment]
What exactly do you not understand? Did you read this ticket from beginning to end?

**Comment by rory** [comment]
I don't see how iD's radio button makes this tags useless. It's perfectly fine if you're micromapping toilets individually. But it still should be improved.

I'm also not convinced anyone uses `unisex=yes/no` to refer to a shorthand for`male=yes.female=yes`. AFAIK one or two people have stated that maybe others do, and yet without evidence.

I think `unisex=yes` on toilets (or `toielts:unisex=yes`) is a totally fine tag that's already in common use.

**Comment by westnordost** [comment]
Okay, to paraphrase, you don't believe the `unisex` tag is burnt, based on conception that the interface of iD ...
<img src="https://user-images.githubusercontent.com/28467304/109139320-429ddc00-77c0-11eb-9e08-1e8277516f89.png"/>
... did not contribute significantly to the misunderstanding that `unisex=yes` is synonymous to `male=yes + female=yes`.

I'd say this can be verified by looking at the numbers.

Assuming that the vast majority of restrooms are segregated, there should be much more `male=yes and female=yes and unisex!=yes` than `unisex=yes` in the wild. Can someone find out the numbers for this? (I'd usually use sophox, but it is offline... a global overpass query then?!)

**Comment by matkoniecz** [comment]
> Assuming that the vast majority of restrooms are segregated, there should be much more male=yes and female=yes and unisex!=yes than unisex=yes in the wild.

`amenity=toilets and male=yes and female=yes and unisex=yes` - 508 https://overpass-turbo.eu/s/14iC

`amenity=toilets and male=yes and female=yes and unisex` 1 141 https://overpass-turbo.eu/s/14iD

`amenity=toilets` and `unisex=yes` 50 796 https://overpass-turbo.eu/s/14iE

>  (And maybe also find out how many restrooms there are that are female only, male only, just to get a big picture)

How this can be tagged?

`amenity=toilets male=yes female!=yes` or `amenity=toilets female=yes male!=yes`?

Any other method?

**Comment by cloudrac3r** [comment]
(Unsubscribing from this thread. I'll open a new issue if I start a mailing list discussion and have anything related to StreetComplete to report back on.)

**Comment by rory** [comment]
On Mon, 01 Mar 2021  9:27, Tobias Zwick <notifications@github.com> wrote:
> Assuming that the vast majority of restrooms are segregated, there 
> should be much more `male=yes and female=yes and unisex!=yes` than 
> `unisex=yes` in the wild. Can someone find out the numbers for this? 
> (I'd usually use sophox, but it is offline... a global overpass query 
> then?!)

Yes the vast majority of toilets _in bars, cafés, pubs and restaurants etc_ are probably gender segregated. But `amenity=toilets` is for free standing public toilets (or those inside "public" buildings, like train stations, or shopping centres). and in my experience a lot of them are single capacity, unisex facilities, especially newer ones. ([example](https://www.mapillary.com/app/?lat=48.9933551&lng=8.3958341&z=17&pKey=Wb30zHzKLl9xqLhHJ2JRtw&focus=photo&mapStyle=OpenStreetMap)]

> I checked back a year in the Tagging and Diversity-talk lists, searching for unisex or gender in the subject line, and actually couldn't find any discussions.

Mailing list search sucks, but there was discussion:  https://lists.openstreetmap.org/pipermail/diversity-talk/2018-April/date.html

**Comment by mnalis** [comment]
@rory reading that mailing list thread, it would seem to me that conclusion was that it had same problems as this ticket mentions. The best solution I've seen (and the one after the discussion seems to end) was that introduction of new tag `gender_segregated=yes` was the best idea. Notable information I found from thread and tickets was:

- [Key:unisex wiki history](https://wiki.openstreetmap.org/w/index.php?title=Key:unisex&action=history) is interesting, as it shows how the meaning was changed.  
- [JOSM was](https://lists.openstreetmap.org/pipermail/diversity-talk/2018-April/000347.html)  defining `unisex=yes` to mean exactly `female=yes`+`male=yes`. It had changed.
- iD is still (see all links before in thread) either using `unisex=yes` to mean exactly `female=yes`+`male=yes`, or even worse, being totally unclear what it means by that tag (as then the most common occurrence, segregated male+female toilets, is impossible to tag in this most popular OSM editor!)
- there were also https://wiki.openstreetmap.org/wiki/Proposed_features/Toilet_Tagging_Improvements
- use `gender_segregated` instead of just `segregated`, as the "segregated toilets" could also be seen as [having stalls or not](https://lists.openstreetmap.org/pipermail/diversity-talk/2018-April/000354.html)

So, the meaning of `unisex=yes` tag  was all over the place, with result that this tag is now "burned", and should be deprecated as soon as better alternative (eg. probably `gender_segregated=yes`) is accepted. As SC uses only community accepted tags with clear meanings (which `unisex` is not), this issue can only be addressed in SC after the tagging mailing list reaches the conclusion for the new tag.

**Comment by westnordost** [comment]
@matkoniecz Thank you! What about numbers for male and female is both yes but unisex is either missing or no?

**Comment by matkoniecz** [comment]
> Thank you! What about numbers for male and female is both yes but unisex is either missing or no?

https://overpass-turbo.eu/s/14kT 10843

------------------

Looking at https://taginfo.openstreetmap.org/keys/unisex#values it can be simplified to

`amenity=toilets and male=yes and female=yes and unisex!=yes global`

**Comment by RubenKelevra** [comment]
I doubt anyone would use "unisex=yes" on a toilet with two separate restrooms for "male" and "female" intentionally.

I think most restrooms are not mapped at all. The only ones which are mapped individually are those which are a free standing facility like in a public space. Those are usually unisex. 

If we create an quest for this we can just ask if this toilet is unisex and if not, the user can select male or female or "both".

In addition we may want to create a button which opens the note window and removes the gender tags for more complex cases.

**Comment by matkoniecz** [comment]
> I doubt anyone would use "unisex=yes" on a toilet with two separate restrooms for "male" and "female" intentionally.

If editor is showing options "male", "female" and "unisex" as sole options, then it is fairly likely.

**Comment by westnordost** [comment]
Ok to summarize:

| Tags | Description | Count |
|----- |-------------|---------|
|  `unisex=yes` | Unisex Toilet | 50796  |
|  `male=yes and female=yes and unisex!=yes` | Sex-segregated Toilet | 10843 |
|  `male=yes and female!=yes`  | Men-only toilet | 5461 |
|  `female=yes and male!=yes`  | Female-only toilet | 5035 |

By looking at the count of female-only toilets vs the others, we can estimate that more than 4% but under any interpretation of the data, less than 19% of sex-segregated toilets are micromapped (consist of two elements - one for each sex).
I understand that the iD preset is the way it is because iD developers want to encourage such micromapping - but looking at these numbers, this encouragement isn't that effective: **5 up to 25 times** as many segregated toilets are mapped as one object, rather than two.
Thus, this means that for this many more toilet elements, what the preset actually does is to confuse users into tagging `unisex=yes` for any toilets that are for both sexes.

Also the total numbers are askew. Almost 5 times as many toilets are tagged as unisex than not (=segregated but for both sexes). 
@rory , given these numbers, and the additional info that @mnalis provided, do you still stick to the thesis that the meaning of the `unisex` tag hasn't been misinterpreted on a large scale, aided by iD (and JOSM) presets?

**Comment by rory** [comment]
> By looking at the count of female-only toilets

I'm not sure I follow your logic of looking at `female=yes` vs `male=yes`. But you seem to be presuming that if there's a male toilet. there must be a female one (right?). That's not always true https://2016.stateofthemap.org/2016/is-she-a-part-of-your-community/

> Almost 5 times as many toilets are tagged as unisex than not

How much of that tagging is from [the quarterly project](https://wiki.openstreetmap.org/wiki/Diversity_Quarterly_Project/2018_Q2#Statistics). I think a lot of people just didn't add `unisex=no` when they should have. I spent a lot of time going through existing tagged toilets and adding that using things like pic4review. Additionally, since it isn't added by iD, it's unlikely to have been populated. Again, these `amenity=toilets` are nearly always _not_ most publically accessible toilets that people use. I don't know about you, but I nearly always use the toilets in the bar/restaurant/etc that I'm in, not the on-street public toilets. So if you see a figure that's strange, it's unlikely to match your experience of when you use a "public" toilet.

My biggest problem is that you're throwing away 50k tags. You're throwing away _years_ of data added by (probably) thousands of mappers. Why? You don't have a good reason. You're referring to parts of wiki pages _that I wrote_ that attempted to cover every single defintion that could have been used.

Since there was a public gender-related "incident" on the OSM mailing list lately (damnit Frederik!), it's unlikely that people affected by this issue will use the tagging mailing list. Any proposal there would need to show that it actually has feedback from people affected by this, i.e. domain experts, and the "local" community. How are you going to ensure that happens?

**Comment by trigpoint** [comment]
It is quite common in Cafes for there to be a single cubicle, used by both sexes and often disabled people.

Is that unisex in tagging terms?

**Comment by rory** [comment]
> It is quite common in Cafes for there to be a single cubicle, used by both sexes and often disabled people.

I use `toilets:unisex=yes` in that case, to keep it part of the `toilets:` namespace like `toilets:wheelchair`

**Comment by westnordost** [comment]
> I'm not sure I follow your logic of looking at female=yes vs male=yes. But you seem to be presuming that if there's a male toilet. there must be a female one (right?).

No, the other way round. In any case, that's only a few hundred usages difference, so this is not relevant because it doesn't change the big picture in the slightest. Please, let's stick to the relevant part of the discussion.

> Since there was a public gender-related "incident" on the OSM mailing list lately (damnit Frederik!), it's unlikely that people affected by this issue will use the tagging mailing list. Any proposal there would need to show that it actually has feedback from people affected by this, i.e. domain experts, and the "local" community. How are you going to ensure that happens?

Also, please, this is all irrelevant here.

What is relevant here is to **ascertain the data quality of the `unisex` tag**, or more specifically, **whether it been (mis)used on a large scale to be synonymous to `female=yes + male=yes`**.

> How much of that tagging is from the quarterly project. I think a lot of people just didn't add `unisex=no` when they should have

If it is relevant, could you please describe how it is relevant? The numbers presented in the summary did not use `unisex=no` to filter segregated toilets but `unisex!=yes` (so, missing OR not yes).

Here is a taghistory graph, in case you want to make a point. The duration of the quarterly project is marked:
![image](https://user-images.githubusercontent.com/4661658/109709455-cda21c00-7b9c-11eb-8a35-13549891a42d.png)

> My biggest problem is that you're throwing away 60k tags. [...] You don't have a good reason.

Oh come on, Rory. The reason we are having this whole discussion is the supposed bad quality of that data.

**Comment by rory** [comment]
On Tue, 02 Mar 2021 21:21, Tobias Zwick <notifications@github.com> wrote:
> > Since there was a public gender-related "incident" on the OSM mailing list lately (damnit Frederik!), it's unlikely that people affected by this issue will use the tagging mailing list. Any proposal there would need to show that it actually has feedback from people affected by this, i.e. domain experts, and the "local" community. How are you going to ensure that happens?
> 
> Also, please, this is all irrelevant here.

Oh here for this yes. But it's relevant _if_ you want to use tagging mailing list discussion to back up a point.

**Comment by westnordost** [comment]
I didn't

**Comment by rory** [comment]
On Tue, 02 Mar 2021 21:27, Tobias Zwick <notifications@github.com> wrote:
> I didn't

No, you didn't but someone did 

> Since a new tagging scheme is needed, I'll have to bring up this discussion on the mailing lists, then get back to you here.

https://github.com/streetcomplete/StreetComplete/issues/2603#issuecomment-785787713

Anyway that's a side track. 🙂

**Comment by westnordost** [comment]
@rory I understand your frustration with this, but it is not StreetComplete that is throwing the 60k tags away but what we are doing here is just to evaluate the quality of the data (and thus per extension if it makes sense to contribute data using that key).
I think there is no doubt that there are instances where mappers tagged segregated toilets as unisex, believing it is a short for male and female. Only the scale of it is not clear.
I also understand that you were continually trying to rectify this situation, getting JOSM to change their preset, getting iD to change their preset etc.
(Though by the way, documenting in the wiki how else `unisex` could be interpreted without at the same time making clear that this is **wrong** was counterproductive, if it was you who wrote that paragraph.)

---

Maybe we can do something novel here, alternatively. 
How can we distinguish good from bad data? We can't. But we could distinguish data that has been checked to be correct from data that hasn't been checked yet, with the `check_date:unisex` tag.

However, the prerequisite for this are
1. the description in the wiki should be corrected to describe what unisex is supposed to mean. A note for data consumers could include the note that the reliability of this information is unclear due to misunderstandings in the past and certain persisting editor presets
2. Get iD to change the preset to allow for 4 choices (male, female, both but not unisex, unisex). After all, over 100 times more contributions are made with iD than with StreetComplete. Trying to rectify a tag while iD is propagating a different interpretation of the unisex tag (or at least is fueling a misunderstanding what unisex means) is tilting at windmills.

The app could then consider all toilets with a `check_date:unisex < [date that iD fixed their preset]` as to-be-checked again.

**Comment by mnalis** [comment]
Even if such "fixed"  `unixsex` tagging with `check_date:unisex` would take root, I would **still** suggest using **additional** tag like `gender_segregated` to make sure of the intended meaning (ie. using `unisex` mostly for backward compatibility). 

Because, even after iD preset is fixed:
- there are other editors too, some of which are not regularly updated by its users 
- we can't expect data consumers to check changeset editor versions and dates to determine what `unisex` tag is supposed to mean after particular edit
- not all of world population are native English speakers, and _some_ will still misinterpret what _unisex_ means (and hey, even SC had its share of users skipping over short explanation)
- some users might even be previous OSM users, which **might still use old meaning** without checking if it has changed in the meantime

**Comment by mnalis** [comment]
(Also @rory, regarding you comment mentioning issues with some people not feeling welcome, it would be nice to not call out people by name in relation to "incidents". And especially trying to avoid doing it while using [words which certain groups find objectionable](https://www.neverthirsty.org/bible-qa/qa-archives/question/when-is-it-appropriate-for-christians-to-use-damn-darn-doom-drat-and-hell/). Just a friendly heads up, as you may wish to edit that comment - I do not intend to turn this into discussion)

**Comment by westnordost** [comment]
https://www.youtube.com/watch?v=NBGOryiqZZI

**Comment by mnalis** [comment]
I should probably (just in case) clarify that by _"`unisex` tag is burned"_ what I meant is actually _"`unisex=yes` tag is burned for purpose of implying `gender_separated=no`")_. 

So the 60k existing `unisex=yes` tags can still be safely used by data consumers if someone wants to know if they can use some toilet _and they don't care about about gender segregation issue_ (and yes, I do understand that some people do care very much about gender separation, as well as if toilets are shared space or separated into individual stalls etc. as covered by Toilet_Tagging_Improvements wiki mentioned above)

**Comment by rory** [comment]
> So the 60k existing unisex=yes tags can still be safely used by data consumers if someone wants to know if they can use some toilet and they don't care about about gender segregation issue

Not always. There are people who aren't male or feamle, there are people who are of unclear gender presentation, or gender fluid. There are women who need help going to to the toilet and have a male family member as a carer (or vice versa). In all cases, people want to avoid the argument of “You're in the wrong toilet!”. A place which has gender neutral toilets (as opposed to a male & fermale toilet) is much more likely to be LGBTQ* friendly. There are many cases where it's a difference.

**Comment by rory** [comment]
One solution could be to see who adds `unisex=yes` to toilets, and start contacting existing mappers, to find out _what they thought they were doing_. If (using statistics) we can show that nearly everyone thought `unisex=yes` means “All genders mixed in together” that's useful info. (or the opposite).

**Comment by matkoniecz** [comment]
> One solution could be to see who adds unisex=yes to toilets, and start contacting existing mappers, to find out what they thought they were doing. If (using statistics) we can show that nearly everyone thought unisex=yes means “All genders mixed in together” that's useful info. (or the opposite).

If you want to ask that (probably changeset comments would be best) and are unsure how to find places where this tag was added recently - let me know and I can create an overpass query for that.

**Comment by mnalis** [comment]
> > So the 60k existing unisex=yes tags can still be safely used by data consumers if someone wants to know if they can use some toilet **and they don't care about about gender segregation issue**
> 
> Not always. There are people who aren't male or feamle, there are people who are of unclear gender presentation, or gender fluid. There are women who need help going to to the toilet and have a male family member as a carer (or vice versa). In all cases, people want to avoid the argument of “You're in the wrong toilet!”. A place which has gender neutral toilets (as opposed to a male & fermale toilet) is much more likely to be LGBTQ* friendly. There are many cases where it's a difference.

Of course, that's why I said above that current 60k `unisex=yes` are useful **only** if one doesn't care about weather toilets are `gender_segregated` or `gender_neutral` (I've bolded it now in my quote). The groups you mentioned obviously care about that, so `unisex` tag is not (as) useful to them, and they would thus benefit from an new (clearly defined from start!) tag like `gender_segregated` or `gender_neutral`. 

Until such tag appears (and is widely supported!), one who is inclined can (and should, IMHO) use `description` tag to provide that info for consumers. Note that `description` tag is wildly supported, so is much more useful (at this time) to general OSM users than only specialized tags without wide acceptance - for example, current version of popular android app OsmAnd (which I use for navigation, finding POIs etc.) will show `description` but not `unisex` info. 

Of course, to gain most benefit, one should probably map both `gender_segregated` and `description` until such time as `gender_segregated` (or `gender_neutral` or whatever community agrees on) is so well supported that `description` is not needed anymore.

**Comment by rory** [comment]
This thread has encouraged me to actually do what I keep suggesting, and analysing the history of additions of `unisex=yes` to `amenity=toilets`. I think [this user](https://www.openstreetmap.org/user/opendcc) has added 20% of the instances of that (~10k instances) in a series of possibly mechanical edits, e.g. [changeset 789,72,884](https://www.openstreetmap.org/changeset/78972884) (cf. [node 4,801,785,147](https://www.openstreetmap.org/node/4801785147/history)). I will investigate more.

**Comment by westnordost** [comment]
Whoa, this looks indeed quite odd:

![image](https://user-images.githubusercontent.com/4661658/112200852-ef2c7b80-8c0f-11eb-98da-ff739422fb30.png)

**Comment by mnalis** [comment]
Strange indeed. Though, I would not presume to know how much Africa might be different from Europe in that respect. 

Note that they're (at least mostly, didn't click on each and every one) tagged as [toilets:disposal=pitlatrine](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dtoilets) and (undocumented on wiki) `toilets:position=outside`, and all [seems to be grouped](https://overpass-turbo.eu/s/15ln) just in that one part of the city

**Comment by mnalis** [comment]
>>  Or, we could set both `unisex` _and_ `gender_segregated` to remove ambiguity while still contributing to the larger tag set.

> Yeah, but as stated, `gender_segregated` is not used enough. No new tags should be introduced via this app. This would bypass the community process.

This, at least, should be acceptable now, as [ `gender_segregated=*`](https://taginfo.openstreetmap.org/keys/gender_segregated) has grown from only `119` uses (when this was originally proposed), to more than `3.3k` today. 

So, my opinion is that `amenity=toilets` + `unisex=yes` + `gender_segregated=no` should _nowadays_ be a good way to tag _"single toilet area that is usable by all genders at once"_ in an **_unambiguous_** way.

(there is a new issue https://github.com/streetcomplete/StreetComplete/issues/6986 which proposes a quest to allow that to be tagged, among other things)
