### ISSUE TITLE
Existence quest of vending machines

### ISSUE THREAD

**Issue by pl71** [streetcomplete/StreetComplete#2608]
Question like "Is this still here? ()" for a coffee vending machine without a name is slightly confusing. 
The question should include the type of items being sold, taken from the vending tag.
Otherwise, if we have several vending machines in close proximity it would be not so clear which of them is the question for.

**How to Reproduce**
Existence quest near vending machines.

**Versions affected**
30.1

**Comment by matkoniecz** [comment]
Do you remember and are willing to publicly share location where it happened?

**Comment by westnordost** [comment]
Also, what is your system language and did you switch it recently?

Am 24. Februar 2021 15:55:04 MEZ schrieb pl71 <notifications@github.com>:
>Question like "Is this still here? ()" for a coffee vending machine
>without a name is slightly confusing. 
>The question should include the type of items being sold, taken from
>the vending tag.
>Otherwise, if we have several vending machines in close proximity it
>would be not so clear which of them is the question for.
>
>**How to Reproduce**
>Existence quest near vending machines.
>
>**Versions affected**
>30.1
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/streetcomplete/StreetComplete/issues/2608

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by pl71** [comment]
(https://www.openstreetmap.org/node/5569309758)

Yes, my system language is not English. How to switch to English and to check again?

**Comment by westnordost** [comment]
But what is you system lanhuage then? 

Am 24. Februar 2021 16:04:34 MEZ schrieb pl71 <notifications@github.com>:
>(https://www.openstreetmap.org/node/5569309758)
>
>Yes, my system language is not English. How to switch to English and to
>check again?
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/streetcomplete/StreetComplete/issues/2608#issuecomment-785138797

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by pl71** [comment]
Bulgarian language

**Comment by westnordost** [comment]
Okay, the problem is the following:
1. Since some time, the iD **unlocalized** presets from which the names of things are sourced do not contain the English name anymore
2. When downloading the quest, the app checks if that thing (that vending machine) can be named to somehow, i.e. an iD preset for that exists - but not in which language it can be referred to
3. When displaying the name of the thing (that vending machine), it tries to find the name in the user's locale (Bulgarian), if not found, in any other locale the user specified in his system preferences (such list is only available since Android 7.0)
![image](https://user-images.githubusercontent.com/4661658/109206996-dfed1600-77a8-11eb-9632-5dbdcb06adc6.png)
and if nothing is found, it would take the **unlocalized** name. But because of point 1, this is empty now. This is why you see an empty name.

I now solved this by always falling back to English if that language does not show up in the user's list of selected languages instead of falling back to the **unlocalized** version.

![image](https://user-images.githubusercontent.com/4661658/109207444-699ce380-77a9-11eb-9beb-7c1fafd57028.png)

**Comment by matkoniecz** [comment]
And if you want to fix English texts - you can help by translating iD (presets category). More info in https://github.com/openstreetmap/iD/blob/develop/CONTRIBUTING.md#translating

It will also appear in iD and Go Map!!, possibly also other places.

**Comment by westnordost** [comment]
English texts? You mean Bulgarian texts!

**Comment by matkoniecz** [comment]
> English texts? You mean Bulgarian texts!

By "fix English texts" I meant "translate into Bulgarian (or other language) so English will not appear after selecting another language".
