### ISSUE TITLE
Allow adding the name for a node in multiple languages 

### ISSUE THREAD

**Issue by chipilov** [streetcomplete/StreetComplete#2610]
**Use case**
In countries that do NOT use the Latin alphabet, it is common for people to search the names of places using their Latin transliteration, even though the official names are in a non-Latin alphabet. 

For example, a popular restaurant in Bulgaria is called "Щастливеца", however, it is common for tourists and locals to search for it using its transliteration - Shtastliveca (or Shtastlivetsa).

Since OpenStreetMaps allows adding a name in multiple langauges, it would be nice for StreetComplete to also allow this in the UI.

**Proposed Solution**
When completing quests for the names of streets, it is already possible to add the name of the "international" name of the street (I assume this is usually the Latin transliteration of the name of the street).

The same UI could be re-used for names of places.

**Comment by westnordost** [comment]
Sounds reasonable.

**Comment by rhhsm** [comment]
I strongly support this, and would even suggest that for countries using a non-Latin script, the "international name" option should be shown by default so SC users are encouraged to enter the transliterated name too.

**Comment by rhhsm** [comment]
> 
> 
> I strongly support this, and would even suggest that for countries using a non-Latin script, the "international name" option should be shown by default so SC users are encouraged to enter the transliterated name too.

...and on top of that, to ask the "international name" of any object (incl. roads) for which only a name in the local script is available.

**Comment by rhhsm** [comment]
Came across several shops recently which had their names displayed in both Cyrillic and Latin script, and had to make a choice that I didn't want to make... Imagine mappers in areas where more than one script is used in parallel (Serbia for instance). (hope this post pushes up the priority of this enhancement request)
![image](https://user-images.githubusercontent.com/69100427/119876570-b327d680-bf30-11eb-9e96-3e5aabba33fa.png)

**Comment by letypequividelespoubelles** [comment]
It should be the case, not only for non-Latin language countries. For example, in Uzbekistan, it's written both in Uzbek, Russian, and Latin transliteration (three different alphabet). In France, it's in French and, in some region, in the regional language too : Creole, Breton, Occitan, Corsican, Alsatian, etc. .. 

The "add other languages" option should be available for street name and bus stop names quests too, not only for add place name quest.

There should be maybe some kind of wording to say that the first given language must be the official language.

Maybe for a good UX, for each country, there should be a pre selection of most used other languages?  (International/ Latin transliteration, Russian for ex Soviet countries, regional languages, etc. ..).

**Comment by mnalis** [comment]
> Maybe for a good UX, for each country, there should be a pre selection of most used other languages? (International/ Latin transliteration, Russian for ex Soviet countries, regional languages, etc. ..).

Hm, I'm not so sure. While it might work for ex-Soviet countries, for example in Croatia is is much more difficult, as languages spoken are based on smaller regions (counties or less).  Some are relatively bigger, eg. maybe about 5% of Croatia (seaside Istria) might have Italian signage too in addition to Croatian. Others dual-signed areas, are **much** smaller like few villages bordering Hungary might have Hungarian signage. Or in the middle, some places would have signs in Serbian cyrillic script.

Still it does not makes much sense to always ask `name:it` for whole Croatia, if it will never be present in `95%` of the cases (or `99.9%` in cases of less represented minorities). And yet, if it is available in that region, it would be good if one could input it (instead of opting for _"it dual-language signage is not present in at least 50% of the country, ignore that language"_).

But, going to such fine granularities (counties or even smaller, instead of countries) where it would not be spammy is too much work to create such a database of administrative borders and languages spoken in them.

Perhaps button to `add another language` could ask for two-letter country code, or allow one to choose from list of countries (maybe with most-recently-used countries rising to the top of the list?) or something simular? That would allow for adding any language, but is admittedly somewhat more clumsy.

**Comment by smichel17** [comment]
Perhaps the "recently used" languages could be pre-seeded with the most-used languages in that area? And/or the form itself could remember previously used languages, so for whatever town you're in, once you answer one sign, it'll ask you for just those languages until you change it again.

**Comment by westnordost** [comment]
The same mechanism as for street signs would be used

**Comment by westnordost** [comment]
I implemented this. It is not visiually similar to the bus stop quest.

However, maybe you didn't know this - I surely also forgot it: In the "place name" quest, it was actually possible to enter a brand name, like "Mc Donald's" and the app would fill in all the information it got from the name suggestion index for that brand additional to the name.
I had to remove that feature in order for the multi-lang-thing to work. But I think the multi-lang-thing is more important / would actually be used more than the brand-auto-complete because big chain stores usually get mapped already with their name. It is the small shops and/or shops that have names in unknown (to Western tourists) scripts that will be left without a name for starters.
