### ISSUE TITLE
Management of buildings with loggia

### ISSUE THREAD

**Issue by bristow** [streetcomplete/StreetComplete#2632]
Hi !

Here is the view of a building and the associated quests. I have already completed the quests of the buildings but there is still the one corresponding to the loggias / balconies...

What to put ? Shouldn't I hide all these 'small' quests corresponding to the loggias or improve the existing quest ?

Thanks for StreetComplete and your hard work !

![IMG_20210223_173046](https://user-images.githubusercontent.com/1156507/109869800-a1080600-7c69-11eb-894a-517e13d2dff2.jpg)

![Screenshot_20210303-213538](https://user-images.githubusercontent.com/1156507/109869796-9fd6d900-7c69-11eb-8c76-c9a1bd106808.png)

![Screenshot_20210303-214522](https://user-images.githubusercontent.com/1156507/109869937-c85ed300-7c69-11eb-861b-23b39771367e.png)

**Comment by westnordost** [comment]
In this case, you should leave a note, saying that you can't answer this because this is not an own building but just a building part of that apartment block.

It is in reality a tagging mistake, that "loggia" should be, as stated, tagged as a `building:part` with `building:levels=2` but this is nothing you should worry about as a STreetComplete user.

So in short, whenever you are unsure, just leave a note and best attach a photo to that note.

**Comment by HolgerJeromin** [comment]
Do we want to exclude such small building things (smaller than a 1 car garage)? 
Most others of them are sheds in a garden (difficult to see through a wall or fence).
