### ISSUE TITLE
"Does this street has a sidewalk" being asked for very short segments of connecting roads

### ISSUE THREAD

**Issue by mnalis** [streetcomplete/StreetComplete#2634]
"Does this street has a sidewalk?" seems to pop up on very small connecting segments of the road. 

I guess it should've been marked as `highway=tertiary_link` instead of `highway=residential`, but looking at [AddSidewalk.kt](https://github.com/streetcomplete/StreetComplete/blob/392760a7276103801783697a92d101d68b9000b1/app/src/main/java/de/westnordost/streetcomplete/quests/sidewalk/AddSidewalk.kt) it does not look like it would've made a difference.

Is this intentional, and should this question be asked for such a small connecting patches? If so, how should one answer the question? "Horvaćanska cesta" has separately mapped sidewalk, and the triangle in the middle is pedestrian island, so about 50% of the road segment in question have sidewalk, but other 50% doesn't.  

**How to Reproduce**
for example, this note:
https://www.openstreetmap.org/note/2562479#map=19/45.79176/15.91085
![Image7159993859592586525](https://user-images.githubusercontent.com/156656/109879431-d87caf80-7c75-11eb-8977-ee19fed07755.jpg)

(The note has attached picture for more details, and editing in iD will offer "Zagreb 2018" TMS among other backgrounds, which is the best resolution aerial photo for the area).

**Versions affected**
SC 30.0 (Android 10)

**Comment by westnordost** [comment]
Short segments: Well, that's the way the data is. Not going to change that, cause imagine this road, `=` is the road, `-` is the sidewalk:

```
=====================================================
A ----------------------------  ------------------- B
```

Then, any pedestrian router will have problems routing a pedestrian from A to B.

However, I will investigate why the piece is not excluded because there is a nearby footway.

**Comment by westnordost** [comment]
Okay, the road is close enough to the footway. However, the minimum angle difference between the two is 28.0°.

The app considers only angles lower or equal to 25° as "possible separately mapped sidewalk". I think this is fair, we must select **some** max angle.

I will close this because in this case, the user should either leave a note, as you did, or specify in the other answers menu, that the footway is mapped separately as this information seems to be missing. The fuzzy "don't ask if there is a high probability that there is a separately mapped footway"-check is only there because the explicit tag `sidewalk=seperate` is very often missing.

**Comment by matkoniecz** [comment]
> Is this intentional, and should this question be asked for such a small connecting patches? If so, how should one answer the question? "Horvaćanska cesta" has separately mapped sidewalk, and the triangle in the middle is pedestrian island, so about 50% of the road segment in question have sidewalk, but other 50% doesn't.

In this case probably all variants are OK and in use.

(1) map missing sidewalks manually or leave note (I do this because separately mapped sidewalks are standard in my area)
(2) tag entire as having sidewalk
(3) split road in two parts

I would treat it likely from [graph](https://en.wikipedia.org/wiki/Graph_(discrete_mathematics)) view. This side road has sidewalk that is not mapped separately and reaches Horvacanska Cesta that has separately mapped sidewalk.

So I would tag it with `sidewalk=*` tags - variant (2), or do variant (1).
