### ISSUE TITLE
Supply check_date when the feature is mapped for the first time

### ISSUE THREAD

**Issue by Etua** [streetcomplete/StreetComplete#2636]
From what I know when the check_date tag is unavailable, the last edit date of an OSM object is used to trigger the resurvey quest. Yet what surprised me is that when the opening hours are surveyed for the first time no check_date is added. If it makes sense to add or change it each time during resurvey quest wouldn't it also worth it to add it when the feature such as opening hours is tagged for the first time?

This note applies to all quests with corresponding resurvey.

**Comment by westnordost** [comment]
I didn't make this my decision. When I discussed this on the ML, there was a preference with being frugal with `check_date`, i.e. only set it if nothing changed. And actually, **remove** it if the tag value changed.

See ResurveyUtils.kt line 37-45.

I am also not too happy with that, but it is better than nothing and community acceptance is very important.

But you are welcome to open this discussion once again, there are obvious advantages of always setting (and not deleting!) the check date for tags where it makes sense to set a check date in the first place.

**Comment by westnordost** [comment]
If you are going to campaign for a change here, be sure to link it (here)

**Comment by Etua** [comment]
Originally I thought that this may have been overlooked when implementing the resurvey in the first place but knowing the quality of the project I opened this issue to investigate it further. Based on what you say I don't think it makes sense for this thread to stick around unless this discussion is going to resurface and could be linked as you suggested. Unfortunately, for a lack of time I can't promise any further action from my side, at least for now.

**Comment by RubenKelevra** [comment]
@Etua yeah, it makes sense. Since you don't have to have the history or parse the history to understand how old the data is you're dealing with. 

Makes it also much easier to do the resurvey analysis.

I agree with @westnordost that it's important to have a consensus in the community on some stuff. But the project is always open for exploring new ways to use tags to describe the informations.

If some individuals in the community are more vocal and/or more restrictive in some regards to tag uses, they should be ignored IMHO.

There is no central authority to disallow a specific use.

**Comment by mnalis** [comment]
For what it's worth, while I did not participate in that discussion, I do get the reasoning for not wanting to have `check_date=*` (or `source=*` etc.) on all nodes/ways/relations in database. That information is contained [elsewhere](https://planet.openstreetmap.org/pbf/full-history/), and not having redundant (and even possibly out-of-sync) data is usually considered [good database management practice](https://en.wikipedia.org/wiki/Database_normalization). 

Sure, it would be easier for data consumers if all the information was in the same database (changesets + planet + full-history + notes + discussions + uploaded GPS traces) instead of having to have separate databases/APIs to retrieve them. And each data consumer has explanations why it would be **easier** for them to have some of that extra data **redundant in the default database**.

Perhaps there is an interest for a wrapper library/service, compatible with OSM API, which cross-references those other databases and inserts pseudo tags `_last_modified_date`, `_last_modified_user` etc. on all elements?
