### ISSUE TITLE
Add option to change app language independent of phone language

### ISSUE THREAD

**Issue by sr-pimposo** [streetcomplete/StreetComplete#2643]
Some people have their phones set to a specif language for learning or other reasons. Because accuracy is an important requirement for StreetComplete, this may cause a problem with users that are not as comfortable with the selected language, having them change the entire phone's language just to use StreetComplete.

It would be interesting to add an option to dissociate SteetComplete's language to that used in the device. This would allow users to have the app in a more familiar and/or convenient language, without needing to change the whole phone environment to said language. This would be an setting in the normal setting panels, allowing you to choose the interface language from available options.

**Comment by matkoniecz** [comment]
See #1246, #29, #52, #1064

If you are using Android below 7.0 then certain missing feature was added to Android 7.0+ - see https://github.com/streetcomplete/StreetComplete/issues/52#issuecomment-291071982

>  this may cause a problem with users that are not as comfortable with the selected language

Why people would set phone system to language uncomfortable for them?

If it was done for learning purposes then they would recheck anything weird, or not clear.

> It would be interesting

It also would be extremely annoying to implement and maintain, Android expects app to follow system language. There are hacks to work around that, but it is plenty of additional work for exotic setting.

**Comment by sr-pimposo** [comment]
Thank you for the response.
Sorry for the duplicate, didn't check as thoroughly as I thought.

**Comment by mnalis** [comment]
@matkoniecz well, I understand that it would take work to make any feature, and that this specific one might be more problematic than usual. However other apps (like OsmAnd, for example) seem to have implemented it without major problems, and number of tickets on this issue seem to indicate that it is something that is wanted (the fact is that I also would like that functionality).

As for why would people use different language for OS than for some app, I can provide some info I personally encountered (there might be more issues of course) in random order:

- financial/popularity: non-major languages do not get nearly as much love as more popular ones (which leads to nonexistent or incomplete translations). The result is that for less popular languages like Croatian translations are sparse - so you'd be forced to know both languages anyway, and switch back and forth from them all the time, often even while staying in same application. Such constant juggling is actually harder then just sticking to foreign language, even if you don't understand it well.
- closed source: another problem of above is that such OS translations are often not very good. Unfortunately, it is not really possible to improve your manufacturer OS version (either the software or the language support) unless you have the ability and inclination to root your phone (which opens another can of worms) - so you're stuck with whatever manufacturer provided.
- technical: some languages are more verbose. It might be "On/Off" in English, but it is "Uključeno/Isključeno" in Croatian.  And many forms do not handle such variable texts very gracefully (SC being the exception, in most cases). When doing Croatian SC translations, I've been warned all the time about 150% too long texts, even if I tried very hard to use shortest possible forms.
- historical: some languages did not really develop their own useful language translations for computer/IT terminology, especially as they were ignored for a long time (see issue at top). So for example, in Croatian "Wi-Fi" would become "bežićna kućna mreža" and "mobile data" would become "bežična mobilna mreža", which are not only longer, but also not very clear to general population. And as such technical/IT translations are not popular in general population (due to fact at the top of this message majority of time Croatian was not an option, so all learning etc. was and is still being done in English versions). Final result is that many Croatians prefer English for technical terms (which is vast majority of terms in Android OS system settings themselves!), so they stick their OS language on English, and then enable Croatian on per-app basis (where such translations exist and switching is enabled).
 - target audience: SC is geared towards non-advanced users. While Croatian users were forced due to history to learn and use English for basic technical computer terms if they wanted to be able to use them at all, they were not forced to use English for other uses, so they didn't learn it there. So while most Croatians would know what "On/Off/Wi-Fi/etc." mean, they'd be at complete loss (even with nice SC pictures!) what is difference between "Apartment / Shed /  Hut / Detached / Semi-detached" and similar. Add to that that similar-sounding Croatian words mean completely different things (eg. "Apartman" is Croatian means "Guest-house", not "Apartment" !) and you can see why they'd vastly prefer to use Croatian language in SC, but still stick to English in Android OS.  

Fun fact: although I've done Croatian translation for SC, I don't use it personally - not because I think it is not good (I actually think it pretty good, even if I'm somewhat biased), but because I don't want to leave my phone OS in English, nor switch languages constantly. So I only test SC in Croatian (on old phone) when doing new SC translations, and stick to English otherwise. Which is suboptimal, as I'm sure I'd find even better translations if I and my family were using Croatian version of SC (which they refuse to do too, as they don't want to spend time to relearn a complete Android stack in Croatian due to issues mentioned above)

So, you hopefully this could illustrate why I would consider option to change language just for SC (instead for of all of android) useful.

**Comment by matkoniecz** [comment]
Thanks for providing explanation, finally I understand what would be point of such setting!

> However other apps (like OsmAnd, for example) seem to have implemented it without major problems

Note that resources available to for example OsmAnd development are significantly larger than for StreetComplete development.

If this setting is in OsmAnd then it evidence that it can be implemented to work without problems, not that it can be implemented without problems.

**Comment by mnalis** [comment]
> Note that resources available to for example OsmAnd development are significantly larger than for StreetComplete development.

Of course, I did not mean to imply that it is a priority or something that must be done. Just wanted to list reasons why other users or myself might want that feature, and that it is actually not so exotic or eccentric thing for users to want. But free software devs should always do only the things that they want! :heart: 

> If this setting is in OsmAnd then it evidence that it can be implemented to work without problems, not that it can be implemented without problems.

Yes, that was my idea, to point at one open-source program which has a working/stable solution, so it might be looked up as reference implementation (if such feature would be considered sometimes, of course)

**Comment by amenk** [comment]
Same problem from Amharic (Ethiopia) - we contributed to the translation and on some phone vendors it is not usable, because Amharic is neglected in the OS-default-selection :-(
We are planing to promote StreetComplete in Ethiopia and it would be cool, if people see that the app cares about their language even the OS-vendor doesn't.

I vote for reopening that issue (probably tag it as help-wanted), so efforts of contributors who want to implement this are not nipped in the bud ;-)

**Comment by westnordost** [comment]
I re-read @mnalis explanations for reasons why a language chooser may make sense. He makes some good points. I also realized that prior reasonings for closing this issue and others where always (also) based on the assumption that implementing this will result in a complex effort. And I did not actually check if this assumption is true.

I still think though that such an option is not the best way to go as it should be solved on the OS level, so I will still not implement this.

However, developers interested in getting this included in the app are invited to exploratively try to implement a solution so that we can evaluate if a possible solution 
- is compact and not complex, i.e. does not require to refactor every use of displaying a string
- does not have a potential for weird bugs and errors

If a solution like that is possible, I'd lean towards including this feature. At the moment, I don't know if it is.

**Comment by mnalis** [comment]
I'm not an Android developer (GitHub compiles my fork :sweat_smile: ),  but if someone takes a try at this, I'd love to betatest!

This stackexchange answer seems to give a basic advice how to implement it:
https://stackoverflow.com/a/23556454/2600099

Also, this https://github.com/streetcomplete/StreetComplete/issues/2964#issuecomment-862609036 shows a places in OsmAnd source how they do it.

**Comment by Helium314** [comment]
and it actually works when setting e.g.
```
        val cfg = Configuration()
        cfg.setLocale(Locale.GERMAN)
        resources.updateConfiguration(cfg, resources.displayMetrics)
```
in MainActivity `onCreate()`

Although `updateConfiguration` is deprecated, and language resets to default when changing display orientation...

**Comment by amenk** [comment]
In addition there is also this (https://stackoverflow.com/questions/2900023/change-app-language-programmatically-in-android) elaborate StackOverflow Question - we have to go through the proposed solutions and see which one works best. I hope https://stackoverflow.com/a/2900144/288568 works already around the issue with changing the display orientation?

There is also https://stackoverflow.com/questions/40221711/android-context-getresources-updateconfiguration-deprecated which uses a non-deprecated method.

It all does not seem 100% easy and trivial, but at least it seems no refactoring of each string occurrence is needed.
If it is not working on the fly and needs a app-restart (as in OsmAnd), that is completely fine with me.

**Comment by amenk** [comment]
If anyone want's to test-drive the above Proof Of Concept: The debug APK can be downloaded here: https://store.map.et/apps/StreetComplete-LanguageSwitch-POC2.apk

It's hard coding to Amharic and the purpose of the POC is to check if there are any strange bugs when forcing the language. The StackOverflow answer this is based on mentioned problems with the dark theme, but seems also be working as it does for the official version of StreetComplete.

**Comment by mnalis** [comment]
@amenk I had to add extra import https://github.com/mnalis/StreetComplete/commit/631dfa50d6f9506122dd52c1a2861123e767f658 to [get GitHub to compile it](https://github.com/Mestrona/StreetComplete/commit/321bc971b6cc344bb3ebf248a4162d116df76efc#commitcomment-54603318). On quick testing it seems to work fine, clicking on elements and menus, trying autorotate and changing dark/light themes. I'll give it some more testing real-life in days to come, but looks like working proof-of-concept. 

What it obviously misses is language chooser, letting user choose `Automatic (same as Android)` or manually force any of supported languages (and of course saving of that language preference, so it's picked up automatically on subsequent starts).

**Comment by amenk** [comment]
Language chooser is now implemented: https://store.map.et/apps/StreetComplete-LanguageSwitch-POC3.apk
Happy testing :-)

<img alt="Screenshot" src="https://user-images.githubusercontent.com/1087128/130315205-ae600976-56bf-4943-b591-9c15a8c5fa14.png" width="200"/> <img alt="Screenshot"  src="https://user-images.githubusercontent.com/1087128/130315209-883f4db1-26b7-49cd-9d39-4937b7bd0975.png" width="200"> <img alt="Screenshot"  src="https://user-images.githubusercontent.com/1087128/130315211-06c452b6-f259-499f-966b-223f85316cce.png" width="200">

**Comment by westnordost** [comment]
Cool! Would you like to create a PR? Any known issues?

Am 21. August 2021 10:05:39 MESZ schrieb Alexander Menk ***@***.***>:
>Language chooser is now implemented:
>https://store.map.et/apps/StreetComplete-LanguageSwitch-POC3.apk
>Happy testing :-)
>
><img alt="Screenshot"
>src="https://user-images.githubusercontent.com/1087128/130315205-ae600976-56bf-4943-b591-9c15a8c5fa14.png"
>width="200"/> <img alt="Screenshot" 
>src="https://user-images.githubusercontent.com/1087128/130315209-883f4db1-26b7-49cd-9d39-4937b7bd0975.png"
>width="200"> <img alt="Screenshot" 
>src="https://user-images.githubusercontent.com/1087128/130315211-06c452b6-f259-499f-966b-223f85316cce.png"
>width="200">
>
>
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/streetcomplete/StreetComplete/issues/2643#issuecomment-903079434

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by matkoniecz** [comment]
I think that popup with "you need to restart app" would be acceptable. Hopefully people will read this one.

I would change how language selection behaves:

- this is just mockup, and obviously all included languages should be selectable, right now only subset is presented (is requiring manual changes there on adding/removing languages acceptable? Is there a good way to build it dynamically?)
- search box for finding language would be nice (I use it often when selecting languages, with very long list hunting for specific one is annoying) - but it is not a blocker and maybe would be better to do it separately

**Comment by amenk** [comment]
@matkoniecz 

> I think that popup with "you need to restart app" would be acceptable. Hopefully people will read this one.

Yes, unfortunately until restarting, languages might be mixed in different activities

I would change how language selection behaves:

> this is just mockup, and obviously all included languages should be selectable, right now only subset is presented (is requiring > manual changes there on adding/removing languages acceptable? Is there a good way to build it dynamically?)

It's not a mockup ... I used the languages for which StreetComplete currently has translations.

> search box for finding language would be nice (I use it often when selecting languages, with very long list hunting for specific
> one is annoying) - but it is not a blocker and maybe would be better to do it separately

Would be nice to have, won't implement that now, the list is not that super long ... currently it's sorted by language ISO code which might make it a bit confusing.


@westnordost 

> Cool! Would you like to create a PR? Any known issues?

I will create a PR so you can already review. But the auto-restart of the main activity doesn't seem to be perfect - I think when you leave an reenter the app after switching (but not restarting), I might have still the old language. We might use this one: https://stackoverflow.com/a/17166729/288568 but not sure how clean it is.

**Comment by matkoniecz** [comment]
> It's not a mockup ... I used the languages for which StreetComplete currently has translations.

Probably but word - but at least some languages are missing.

**Comment by Helium314** [comment]
> * this is just mockup, and obviously all included languages should be selectable, right now only subset is presented (is requiring manual changes there on adding/removing languages acceptable? Is there a good way to build it dynamically?)

I did not have a closer look, but [this stackoverflow answer](https://stackoverflow.com/a/36047987) adds a gradle task which builds a locale list from translations available in resources

**Comment by mnalis** [comment]
@amenk Yes, all instances where I read say app exit is a must on Android. Few notes on current behaviour (https://github.com/Mestrona/StreetComplete/commit/fdb6df3b43d4cdf7004f9dd669d1eee6e5504cc5) which did not occur in previous version with hardcoded language (which worked fine in all my tests):

- when language is changed in SC settings, it opens a new map with selected language, but pressing back shows old forms in previous language (that stacks, so if you changed language several times, you can press `back` key several times going back through them). Closing app should fix this.
- also when language is changed to `System default` after it was changed to some other language, that does not work; eg. System language is English. I start SC and change language from System (English) to Croatian, which works (with caveat above). Then I change back to `System default`, but the language remains in Croatian. I must close the app (and remove it from cached apps) and start it again to start in `System default` language. I also think forcibly closing app from within might fix that. 

As mentioned on https://github.com/streetcomplete/StreetComplete/issues/2964#issuecomment-862609036, having app exit by itself is what OsmAnd does too (after warning window) with final:
```
android.os.Process.killProcess(android.os.Process.myPid());
```
call, and it does not exhibit any of the problems mentioned above, so I believe that is the way to go too.

**Comment by westnordost** [comment]
> that stacks, so if you changed language several times, you can press back key several times going back through them

This is because starting activities always stacks onto each other. See https://developer.android.com/guide/components/activities/tasks-and-back-stack

When you are in the settings screen, the stack is 
1. SettingsActivity
2. MainActivity

When you exit the settings activity, `MainActitivty` is back to be on the top of the stack. If you just start `MainActivity` from `SettingsActivity` you have this stack:

1. MainActivity
2. SettingsActivity
3. MainActivity

**Comment by amenk** [comment]
I am wondering if we should implement the language override exactly as they do it in OsmAnd?

The LocaleHelper could be copied - License permits it - but they also seem to overwrite on overwriting getResources (https://github.com/osmandapp/OsmAnd/blob/d5a95e28f14709a3f12b9f1416965e78a2fe1996/OsmAnd/src/net/osmand/plus/OsmandApplication.java#L839) and would probably avoid inserting the wrapper in each activity and fragment (https://github.com/streetcomplete/StreetComplete/pull/3199#discussion_r693356887), but I am not sure if that causes new problems.

**Comment by amenk** [comment]
@westnordost Do you know off the top of your head if the approach of overwriting `StreetCompleteApplication.getResources()` could work? And would be a cleaner solution than the one I tried?
Or do you expect a lot of changes to be necessary in the code base?
This is how OsmAnd does it and a very short assessment if this is promising would be great :-)

Note to the others interested in this thread: On the other hand I am a very novice Kotlin and Java programmer and would be very fine with somebody else taking over :-)

**Comment by westnordost** [comment]
Sorry,  I don't know.  I didn't look deeper into this. But if it worked,  it would be somewhat cleaner,  that's for sure. 

Am 19. September 2021 11:19:57 MESZ schrieb Alexander Menk ***@***.***>:
***@***.*** Do you know off the top of your head if the approach of
>overwriting `StreetCompleteApplication.getResources()` could work? And
>would be a cleaner solution than the one I tried?
>Or do you expect a lot of changes to be necessary in the code base?
>This is how OsmAnd does it and a very short assessment if this is
>promising would be great :-)
>
>Note to the others interested in this thread: On the other hand I am a
>very novice Kotlin and Java programmer and would be very fine with
>somebody else taking over :-)
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/streetcomplete/StreetComplete/issues/2643#issuecomment-922442365

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.
