### ISSUE TITLE
Link to Openrouteservice (Wheelchair) is not working

### ISSUE THREAD

**Issue by fraggle-DE** [streetcomplete/StreetComplete#2646]
The URL to Openrouteservice (Wheelchair) is currently https://maps.openrouteservice.org/directions?b=3 but it isn't working. It gives a "Not Found The requested URL was not found on this server." I tested it on my smartphone and my notebook. It's the same result.

**How to Reproduce**
- Open "My Profile"
- Switch to last tab (links to OSM projects)
- Scroll down to entry "Openrouteservice (Wheelchair)"
- Click this entry

**Versions affected**
v31.0

**Comment by matkoniecz** [comment]
https://maps.openrouteservice.org/#/ still works

**Comment by fraggle-DE** [comment]
yup, I forgot to mention that.

**Comment by westnordost** [comment]
Thank you for the hint!

Looks like they disimproved the site so that the selected options and map state are not sharable as links anymore. I tried out the "new" site, it's really not good UX, from several points of view. It's good that they still got the old site around though, the new URL then is https://classic-maps.openrouteservice.org/directions?b=3
