### ISSUE TITLE
"Does X accept cash payment" not available in the UK

### ISSUE THREAD

**Issue by ancarda** [streetcomplete/StreetComplete#2647]
Why does the quest "Does ... accept cash payment?" have a little label below saying "Never shown in United Kingdom"? I'm confused why this would be restricted

**Comment by matkoniecz** [comment]
Because StreetComplete asks only about things that would not be spammy. If answer would be in 99% cases the same then it is disabled.

This specific quest is activated only in Sweden, where cash usage declined to the point that it becomes useful to collect info about it.

Is the same true in UK? How many shops and other places ( https://github.com/streetcomplete/StreetComplete/blob/9cef7f6a9377ca059fbf307527e7031c336c9899/app/src/main/java/de/westnordost/streetcomplete/quests/accepts_cash/AddAcceptsCash.kt#L17 ) reject cash payments?

**Comment by TurnrDev** [comment]
I had wondered this too, cash denial is rare in Kent, I can't speak for the rest of the UK

**Comment by trigpoint** [comment]
Things have changed a lot recently.

In the UK I am coming across businesses accepting cards only, national coffee shop chains, HMV. 

I probably need to survey it a bit better and begin updating POIs.

**Comment by westnordost** [comment]
yes, currently, because and covid and stuff I'd say. Let's see how it is after the crisis is over.

**Comment by matkoniecz** [comment]
> Let's see how it is after the crisis is over.

@trigpoint What is the current state? COVID is still around but unlikely to go away and whatever is still with us caused by it is unlikely to go away either.

**Comment by peternewman** [comment]
> In the UK I am coming across businesses accepting cards only, national coffee shop chains, HMV.

> > Let's see how it is after the crisis is over.
> 
> @trigpoint What is the current state? COVID is still around but unlikely to go away and whatever is still with us caused by it is unlikely to go away either.

In central London some chains seem to have introduced it post-Covid.

This article is a bit old:
https://www.thesun.co.uk/money/19504287/cash-stores-revealed-card-only-payments/

> Government responded
> This response was given on 25 April 2022
> The government does not plan to mandate cash acceptance. Businesses are able to choose the forms of payment they accept. The government’s proposals for legislation support cash acceptance.

https://petition.parliament.uk/petitions/605030

My gut feeling is disabled by default at best for now, or possibly just check for brands/chains for the moment.
