### ISSUE TITLE
Enable maxspeed quest for US-OK

### ISSUE THREAD

**Issue by BalooUriza** [streetcomplete/StreetComplete#2668]
### General
Affected tag(s) to be modified/added: [](https://wiki.openstreetmap.org/wiki/Key:)
Question asked: **Is there an example tag on item XY?**

### Checklist
Checklist for quest suggestions (see guidelines):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary 
- [x] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of elements (Worth the effort)

### Ideas for implementation

If a default speed is selected instead of a numeric limit, another box should ask for detailed input and instead create a note with this information rather than attempt to edit directly.  Zone speed limits are not handed in the EU style fashion of XX:YY:Urban for area zones explicitly stated due to the overwhelming number of possibilities for area zones within Oklahoma and lack of standardized signage as compared to places that use verbally defined zone rules.

**Element selection:** 
Same as is asked for existing speed limit quest.

**Comment by westnordost** [comment]
Sorry but no. I gather you didn't read the earlier tickets regarding speed limits (in the US), so you are maybe not aware of the larger problem (with the tagging scheme) here.

The maxspeed quest is disabled by default for several reasons, one of it is that the EU style tagging XX:urban etc. is not very good / a huge mess / not covering all the use cases necessary. In particular, users of this app should not need to know in which legal zone they are to be able to answer the quest if there is no sign. (F.e. they can answer `maxspeed=30 mph` if there is a sign that says this, but what should the app tag if there is no sign? There is no tag for that specifically, only another tag that implies that there is no sign: `maxspeed:type` etc.)

As you know, the US does in many states not have the distinction urban / rural but other distinctions (business district / residential district / elsewhere) or depending on the state, a mixture of all this. That scheme hasn't been thought through to apply properly for the US. Enabling the quest would require for each US-state individually to represent the different legal speed zones in each a tag (f.e. `maxspeed:type:US-OK:state_park_road`) and build a specific UI for that in the app.

But this tag value and the many others to represent legal speed zones in the US does not exist yet and StreetComplete does not invent tags, plus it would be an unjustifiable effort, also in the UI, anyway.

In my opinion, the only way to really move forward here is to establish a tag that specifically states "there is no sign here", analogous to [`maxweight:signed=no`](https://taginfo.openstreetmap.org/keys/maxweight%3Asigned). Because then, the StreetComplete user can simply specify the maxspeed if there is a sign, or otherwise record, that there is no sign, without having to worry about if he is in or outside of an urban area, residential district, business district, state park road, school zone, slow zone etc etc.
But alas, it doesn't exist (yet) and as I said, StreetComplete does not invent new tags. And I myself didn't find the time or leasure to propose f.e. `maxspeed:signed` to the larger community, since I know that there is a large (German) crowd within the community that doesn't see the problem and thinks the current tagging scheme(s) for implicit speed limits is fine as it is and is opposed to changing anything or adding any new tags in that regard.

I'd very happy if someone else would campaign for (the acceptace) of this because it bugs me that such an important information is not well recorded (using this app).

**Comment by BalooUriza** [comment]
On Mon, Mar 22, 2021 at 9:12 AM Tobias Zwick ***@***.***>
wrote:

> Sorry but no. I gather you didn't read the earlier tickets regarding speed
> limits (in the US), so you are maybe not aware of the larger problem (with
> the tagging scheme) here.
>
I am aware, I was proposing a solution.

> The maxspeed quest is disabled by default for several reasons, one of it
> is that the EU style tagging XX:urban etc. is not very good / a huge mess /
> not covering all the use cases necessary. In particular, users of this app
> should not need to know in which legal zone they are to be able to answer
> the quest if there is no sign. (F.e. they can answer maxspeed=30 mph if
> there is a sign that says this, but what should the app tag if there is no
> sign? There is no tag for that specifically, only another tag that implies
> that there is no sign: maxspeed:type etc.)
>
Which is why I explicitly suggested making a note instead of tagging like
this.

> As you know, the US does in many states not have the distinction urban /
> rural but other distinctions (business district / residential district /
> elsewhere) or depending on the state, a mixture of all this. That scheme
> hasn't been thought through to apply properly for the US. Enabling the
> quest would require for each US-state individually to represent the
> different legal speed zones in each a tag (f.e.
> maxspeed:type:US-OK:state_park_road) and build a specific UI for that in
> the app.
>
I explicitly pointed out that Oklahoma is a mixture of this but the
accepted tagging scheme here is to explicitly use the numerical maxspeed
tags because otherwise it gets *way* too complicated to sort out.  Oklahoma
has over 30 sovereign indigenous tribes, 77 counties, and almost 600 cities
and towns, all of which can set zone-style limits peacemeal over each
other.  So far, just explicitly stating the speed limit where known is the
best way we know to do it.  Hence the need to point out a note since at the
point that you need to explain it, it's probably going to take someone with
local knowledge and JOSM to fix anyway. This at least makes it easier to
bring up that there is a problem.

**Comment by RubenKelevra** [comment]
@BalooUriza 

Hey, thanks for the proposed idea, but as @westnordost pointed out - there are tagging issues to solve first to create real edits.

StreetComplete do allow you to create notes everywhere you like by tapping long on a point on the map. So you can do what you like to do already. 

Or do I miss something here? :)

**Comment by RubenKelevra** [comment]
>  > As you know, the US does in many states not have the distinction urban / rural but other distinctions (business district / residential district / elsewhere) or depending on the state, a mixture of all this. That scheme hasn't been thought through to apply properly for the US. Enabling the quest would require for each US-state individually to represent the different legal speed zones in each a tag (f.e. maxspeed:type:US-OK:state_park_road) and build a specific UI for that in the app.

> I explicitly pointed out that Oklahoma is a mixture of this but the accepted tagging scheme here is to explicitly use the numerical maxspeed tags because otherwise it gets *way* too complicated to sort out. Oklahoma has over 30 sovereign indigenous tribes, 77 counties, and almost 600 cities and towns, all of which can set zone-style limits peacemeal over each other. So far, just explicitly stating the speed limit where known is the best way we know to do it. Hence the need to point out a note since at the point that you need to explain it, it's probably going to take someone with local knowledge and JOSM to fix anyway. This at least makes it easier to bring up that there is a problem.

Is this documented somewhere?

**Comment by smichel17** [comment]
> Which is why I explicitly suggested making a note instead of tagging like this.

I think this may violate the second quest criteria, "Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)"

**Comment by BalooUriza** [comment]
> > > As you know, the US does in many states not have the distinction urban / rural but other distinctions (business district / residential district / elsewhere) or depending on the state, a mixture of all this. That scheme hasn't been thought through to apply properly for the US. Enabling the quest would require for each US-state individually to represent the different legal speed zones in each a tag (f.e. maxspeed:type:US-OK:state_park_road) and build a specific UI for that in the app.
> 
> > I explicitly pointed out that Oklahoma is a mixture of this but the accepted tagging scheme here is to explicitly use the numerical maxspeed tags because otherwise it gets _way_ too complicated to sort out. Oklahoma has over 30 sovereign indigenous tribes, 77 counties, and almost 600 cities and towns, all of which can set zone-style limits peacemeal over each other. So far, just explicitly stating the speed limit where known is the best way we know to do it. Hence the need to point out a note since at the point that you need to explain it, it's probably going to take someone with local knowledge and JOSM to fix anyway. This at least makes it easier to bring up that there is a problem.
> 
> Is this documented somewhere?

If someone documented it, sure, but it's in widespread active use in Oklahoma to use source:maxspeed=* as a plain English explanation for zone limits.  I've personally almost entirely given up on the wiki because documenting live use often gets reverted by people who consider the wiki a proscriptive document.

**Comment by matkoniecz** [comment]
> I've personally almost entirely given up on the wiki because documenting live use often gets reverted by people who consider the wiki a proscriptive document.

If you encounter such cases, please write at https://wiki.openstreetmap.org/w/index.php?title=User_talk:Mateusz_Konieczny&action=edit&section=new (I was unable to check whatever there is something new, as there is no matching username - https://wiki.openstreetmap.org/wiki/Special:Contributions/BalooUriza or easily findable profile https://wiki.openstreetmap.org/w/index.php?search=Baloo+Uriza&title=Special%3ASearch&profile=default&fulltext=1 )

**Comment by RubenKelevra** [comment]
Agreed with @matkoniecz - this should not happen.

`source:maxspeed=*` is a field for exactly this purpose - to describe where the information is sourced from. The usage [documented currently in the wiki](https://wiki.openstreetmap.org/wiki/Key:source:maxspeed) is misusing of an established subtag IMHO.

There was also never a discussion about this. Someone just created a wiki page as he/she started to misuse it.

The best solution would be to use just `maxspeed=DE:urban` as an example for Germany. Do you have an idea how to solve this with machine-readable tags for US-OK?

**Comment by matkoniecz** [comment]
@RubenKelevra Well, OSM Wiki page in that case is describing actual use of a tag... See https://taginfo.openstreetmap.org/keys/source:maxspeed (though mentioning that it mismatches usual use of `source:` prefix may be a good idea)

**Comment by RubenKelevra** [comment]
> @RubenKelevra Well, OSM Wiki page in that case is describing actual use of a tag... See https://taginfo.openstreetmap.org/keys/source:maxspeed (though mentioning that it mismatches usual use of `source:` prefix may be a good idea)

Yeah sure. But there should be a discussion that the current way we tag these information makes them basically useless, since we can't update them properly. As @westnordost described here:

https://github.com/streetcomplete/StreetComplete/issues/1998#issuecomment-676787192
