### ISSUE TITLE
What is the outer surface material of this buildings facade? `building:material`

### ISSUE THREAD

**Issue by andrewharvey** [streetcomplete/StreetComplete#2682]
### General
Affected tag(s) to be modified/added: [building:material](https://wiki.openstreetmap.org/wiki/Key:building:material)
Question asked: **What is the outer surface material of this buildings facade?**

### Checklist
Checklist for quest suggestions (see guidelines):
- [x] 🚧 To be added tag is established and has a useful purpose

More accurate 3D maps.
Maybe useful for people doing analysis on buildings.

- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary 
Yes this tag specifically only asks for the outer surface (eg brick veneer walls would still be tagged as brick as that's the outer surface, so usually can be determined from looking from outside).
While the tag description mentions building walls, they also say facade which is conflicting as facade usually strictly means the front facing part of the building. This tag may need to be clarified, but if we stick with facade as front facing then that usually possible to survey from the street level.
- [x] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
While some localised areas might have the same answer, it does vary a fair bit and you can't usually assume a default.
- [x] 🕓 Applies to a reasonable number of elements (Worth the effort)
Yes applies to most buildings.

### Ideas for implementation

**Element selection:** 

Most building types, though some we could probably exclude (carport, roof, garage).

**Metadata needed:** 

**Proposed GUI:**

**Comment by westnordost** [comment]
> More accurate 3D maps.

I thought I mentioned this somewhere else already, maybe in the quest guidelines, but 3D maps ist not a proper useful purpose because anything could be argued to be useful in 3D maps. Maybe it would have a useful purpose for analysis, but not with this definition:

> this tag specifically only asks for the outer surface (eg brick veneer walls would still be tagged as brick as that's the outer surface, so usually can be determined from looking from outside).

**Comment by andrewharvey** [comment]
> but 3D maps ist not a proper useful purpose because anything could be argued to be useful in 3D maps.

Okay, I see your point. But why do we ask for roof shape? I can't see any other purpose from 3D maps and analysis (which anything could be counted as analysis).

**Comment by matkoniecz** [comment]
Maybe it is difference between "can be used for 3D maps" and "used for 3D maps and of critical importance there"?

**Comment by westnordost** [comment]
Yes, the roof shape quest isn't a very important one. Though,  it can be used for other purposes as well theoretically. For example to guess very roughly the age of a building (Apartment blocks newer than 60 years or so in Hamburg tend top have a flat roof). Also,  the roof shape is a cultural thing. 
-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by smichel17** [comment]
I think in the future there is a place for "useful only for 3d mapping" type quests, which I will call "cosmetic" (and which I would say include building shape — I turn that quest off most of the time).

Right now I have a "problem" where I have finished [almost] all the quests within a 10-20 minute walk of my house (depending on direction), so I am not able to solve as many quests on my walks without driving or biking there first; only a small % of my time is actually spent mapping.

It would be nice if there were a way for SC to show *only a small subset* of cosmetic quests, evenly spaced along my path. Just enough to give me something to do until I get to the area that I actually want to map; showing them all would defeat the purpose, because then I'd run out and have the same problem. I wouldn't want these quests to be shown when there are meaningful quests nearby, though.

I don't see this being implemented soon (thus, have not opened an issue for it); it would come after some other work around quest display density.

**Comment by CloCkWeRX** [comment]
Wall, roof materials, this is slightly useful to the property industry (appraisal/real estate, insurance, energy assessment, etc). Those are likely niche consumers of the data at this time, but example commercial companies that collect this data include folks like https://en.wikipedia.org/wiki/CoreLogic - who then onsell attribute data like this to others.

It's not a huge use case; and not super exciting for the average individual map user; but I'm not really aware of any other free repositories of this kind of information either.
