### ISSUE TITLE
Don't ask housenumber for building in area that has housenumber node on its outline(?)

### ISSUE THREAD

**Issue by westnordost** [streetcomplete/StreetComplete#2686]
I was asked for a housenumber for this building:

https://www.openstreetmap.org/way/55063203

It is on the premises of a school. The school has two house numbers, depending on the gate you enter from. (10 on Telemannstraße or 65 on Heußweg.)

So, maybe the quest should not ask for the housenumber of buildings on areas which are admittedly not tagged with a housenumber themselves, but there is at least one node with a housenumber on its outline.

Opinions?

**Comment by andrewharvey** [comment]
Agreed, for many regions the "housenumber" (street address number) is accociated with the land parcel, not any particular building. Especially for schools etc which have many buildings on the school grounds it makes much more sense to tag the address on the grounds way and not on the buildings.

When this is done, SC shouldn't ask for "housenumber" on any buildings since it's already defined on the surrounding area way. To be honest I thought SC already worked like this, so +1 for fixing this.

**Comment by matkoniecz** [comment]
I think that not asking is preferable in such case, if it possible to implement in a sane way

> SC shouldn't ask for "housenumber" on any buildings since it's already defined on the surrounding area way.

This is implemented already. Note that this issue is about address on **node on outline of** surrounding area
