### ISSUE TITLE
Disable AddCycleway quest in Sweden

### ISSUE THREAD

**Issue by riiga** [streetcomplete/StreetComplete#2730]
For Sweden specifically cycleways as tagged by StreetComplete are very uncommon. Most common are combined paths mapped separately from the main highway. This is also another quest that only adds tag pollution. The default value of a highway is to have no cycleway. If there is a cycleway, someone will add the appropriate tags. There's no need to add `cycleway=no` to every single highway.

**Comment by matkoniecz** [comment]
The same as #2729 - can you link some discussion location used by Swedish mappers with support for such change?

In general some quests were disable at request of local communities, but after it was checked that such change has general support.

**Comment by westnordost** [comment]
The cycleway quest is not shown when a separately mapped foot/cyclepath is nearby. So, the quest does not add `cycleway=no` to every single highway.

**Comment by matkoniecz** [comment]
And to be strict - it adds `cycleway:both=no` / `cycleway:right=no` / `cycleway:left=no` (mentioning this so people will be aware that `cycleway=no` was definitely not tagged by people using StreetComplete)

**Comment by riiga** [comment]
@westnordost Then why all these useless tags on roads clearly having a path beside them? https://overpass-turbo.eu/s/15YL
@matkoniecz You're correct, thanks for clarifying.

**Comment by westnordost** [comment]
Because the distance of the cycleway to the street is above a certain threshold with which it is considered as belonging to that road. As far as the algorithm used is concerned, this cycleway is not part of the near streat anymore but a cycleway on its own.

https://www.openstreetmap.org/way/484771633#map=18/58.42910/15.60570

Yeah, this is fuzzy. If you find this is stupid, and the algorithm shouldn't be that fuzzy, then you are right. It shouldn't be. But it must be, because this is the situation in OpenStreetMap: There is no way to find out with certainty for any given road if there is no cycleway infrastructure or if the cycleway infrastructure simply hasn't been mapped yet.

Or actually, there is. But it hasn't been mapped comprehensively yet: Add `bicycle=use_sidepath` or `cycleway=separate` or `no` to the road. So data consumers (StreetComplete is also a data consumer in this regard) must rely on a fuzzy algoirthm to find out where the information is missing. And this is exactly the part that StreetComplete is trying to fix: By making users explicitly specify whether there is a cyclway or not on the roadway.

**Comment by Discostu36** [comment]
> Or actually, there is. But it hasn't been mapped comprehensively yet: Add bicycle=use_sidepath or cycleway=separate or no to the road. So data consumers (StreetComplete is also a data consumer in this regard) must rely on a fuzzy algoirthm to find out where the information is missing. And this is exactly the part that StreetComplete is trying to fix: By making users explicitly specify whether there is a cyclway or not on the roadway.

Shouldn't it be possible to tag `cycleway=separate` in StreetComplete then?

**Comment by matkoniecz** [comment]
> Shouldn't it be possible to tag cycleway=separate in StreetComplete then?

See #2525 (exactly about this despite the title)

**Comment by matkoniecz** [comment]
@riiga Have you investigated the situation? (is problem caused by a translation, potentially asking mapping community there are they consider `cycleway:both=no` as strictly unwanted etc)

**Comment by riiga** [comment]
It's more of a fundamental way of thinking when it comes to mapping: Just like the `oneway=yes` tag is only added to oneway roads, adding cycleway tags should only be done if there exists a cycleway and if this quest can only continue if that means adding (in my opinion) meaningless data to OSM then maybe it's not a good quest to have? I don't see any quest asking about if a way is oneway or not which is really the same principle when it comes to adding data. (And please don't add such a quest. :roll_eyes: ).

**Comment by matkoniecz** [comment]
> It's more of a fundamental way of thinking when it comes to mapping: Just like the oneway=yes tag is only added to oneway roads, adding cycleway tags should only be done if there exists a cycleway and if this quest can only continue if that means adding (in my opinion) meaningless data to OSM then maybe it's not a good quest to have?

It kind of depends on exact view. For example adding `noname=yes` is accepted for `highway=residential` without names.

Tagging `lit=yes` or `lit=no` is also considered as OK for some selection of roads/paths (it is not asked for all of them, some filters are applied).

See also https://github.com/streetcomplete/StreetComplete/wiki/Adding-new-Quests-to-StreetComplete

> It must be possible to determine whether the quest should reasonably be asked. A quest which is to be answered in 99% of the time with the same answer is not a good quest, don't bore the users. I.e. asking for any road if it is a one-way road, is silly, because the vast majority of all roads will not be one-ways.

that is kind-of-related.

>  I don't see any quest asking about if a way is oneway or not which is really the same principle when it comes to adding data. (And please don't add such a quest. roll_eyes ).

oneway quest is present, but asked solely in cases where there are good reasons to suspect that road is oneway

> meaningless data to OSM

If that opinion about this quest is shared by Swedish community it will be disabled. (and it is already disabled in places unlikely to have cycleways)

**Comment by westnordost** [comment]
> If that opinion about this quest is shared by Swedish community it will be disabled. (and it is already disabled in places unlikely to have cycleways)

Sorry, this is maybe a misunderstanding. Disabling quests on a per-country-basis is done based upon whether it makes sense to collect that data at all in that region. It is not based on if a local community decides that they don't want that data or don't want that data in that format. Examples:

- The housenumber quest is disabled in Norway because all addresses are imported from an official source, individual contributions make no sense
- Asking for street names is disabled in Japan because very few roads in Japan have names and addresses in general refer to blocks
- Asking for bus stop names in the US is disabled because many bus stops do not have names but instead only publicly visible ref codes
- Asking for the roof shape is disabled for buildings with roof levels 0 in many countries with very low rainfall (because they will always be flat)

If it is the country-wide guideline in Sweden to always tag sidewalks and cycleways as separate ways... - that's good! I also prefer it that way, and I hope such guidelines can be established elsewhere too so that the sidewalk and cycleway tags on the roadway itself can slowly be abandoned.
However, then, you need to tag it completely: Tag on the roadway that there is a sidewalk/cycleway, but it is tagged separately so that data consumers may know (without using a fuzzy algorithm) whether there is a sidewalk/cycleway for a given road or not and distinguish between "there is no cycleway" and "the cycleway has not been mapped yet".

**Comment by matkoniecz** [comment]
Sorry for a mischaracterization of a situation, though I trust Swedish community to be objecting only with a good reason.

**Comment by matkoniecz** [comment]
closing due to lack of response
