### ISSUE TITLE
Maxspeed type on trunk roads and living street

### ISSUE THREAD

**Issue by arrival-spring** [streetcomplete/StreetComplete#2750]
`highway=trunk` is included in `ROADS_WITH_DEFINITE_SPEED_LIMIT`, meaning that when the maxspeed quest is answered with "No sign, defaults apply" (implicit speed limit) `maxspeed:type` is set to `GB:trunk` (or whichever country code).

This is not an established tag, and a spot check of some ways (in a few different countries) from taginfo/overpass makes it look like most have been added by SC users.

I don't know enough about other countries to know whether this should just be removed from the `ROADS_WITH_DEFINITE_SPEED_LIMIT` or whether other checks are needed.

In the UK at least it could be removed and the user should be asked if it's dual or single carriageway.

I think that the same can be said for `living_street`, there are tags for that, but at the moment it isn't `GB:living_street` (taginfo shows no uses of that, but a few uses for other countries).

(Turns out that speed limits are quite a can of worms!)

**Comment by westnordost** [comment]
What is wrong with `GB:living_street`, aren't there no living streets in Great Britain?

**Comment by arrival-spring** [comment]
The issue is that it's not an established tag, if no-one else has ever tagged it then SC shouldn't be tagging it.
There are living streets (I think), but I'm not familiar with any so I don't know what the speed limit would be.

**Comment by westnordost** [comment]
> The issue is that it's not an established tag, if no-one else has ever tagged it then SC shouldn't be tagging it.

Well ok, then this can stay as it is. The established tagging here is `maxspeed:type=XX:living_street`, same with motorway.

**Comment by westnordost** [comment]
Regarding trunk, most countries do have legislation for default max speeds that is applicable to roads that are tagged as `highway=trunk` in one way or another (the rules what roads are tagged as trunk are set up by the local communities and differ from country to country because they try to match the category as defined by legislation).

In Germany for example, there is no explicit "trunk" limit but a limit for "single carriageway with 2 or more lanes in each direction", which just so happens pretty much fits the description on how `highway=trunk`s are defined for Germany.
For the UK, I figure, the default speed limits for anything that is tagged as trunk is `nsl_single`, isn't it?

**Comment by arrival-spring** [comment]
> Well ok, then this can stay as it is. The established tagging here is `maxspeed:type=XX:living_street`, same with motorway.

My point was that it is NOT an established tag, `maxspeed:type=XX:living_street` has 191 uses in Poland and 115 uses in the rest of the world combined.
It is not mentioned on the wiki on either maxspeed:type or source:maxspeed either.

**Comment by arrival-spring** [comment]
Likewise with trunk, `maxspeed:type=XX:trunk` has 588 uses worldwide.
`source:maxspeed=PL:trunk` seems to be established (5570 uses), but no significant usage elsewhere.

In the UK, trunk roads could single or dual carriageway, so either `nsl_single` or `nsl_dual`.

**Comment by westnordost** [comment]
![image](https://user-images.githubusercontent.com/4661658/115019256-3a594780-9eb9-11eb-8a35-bacc43e2b4ae.png)

**Comment by arrival-spring** [comment]
Yes, I then saw that, but at the moment SC is adding `maxspeed:type`, not `source:maxspeed` are these tags being treated as synonyms?

**Comment by westnordost** [comment]
yes

**Comment by arrival-spring** [comment]
Poland seems to be the only place with any sort of significant use of `XX:trunk`, so how about removing that from `ROADS_WITH_DEFINITE_SPEED_LIMIT` except for a check if it's in Poland?

**Comment by westnordost** [comment]
Well, as said, trunk is a known category in any country where there are `highway=trunk`, just as living streets are a category. Just because the tag is used a lot in Poland, doesn't mean that Poland is the only country where the tag makes sense.

For example, it is not used that much in Germany, but as said before trunks in Germany actually **do** have a default speed limit that is different than from simply rural roads. Or not trunks as such, but any (rural) roads that have 2 or more lanes in each direction, or (rural) roads with a dual carriageway. So, `maxspeed:type=DE:rural_with_2_or_more_lanes_in_each_direction_or_dual_carriageway` would be more precise, but I'd day all roads that are tagged as `trunk` fulfill these requirements.

See this wiki page: https://wiki.openstreetmap.org/wiki/Default_speed_limits

**Comment by westnordost** [comment]
Anyway, please take a more detailed look at that wiki page, and hopefully you will see how ill-conceived the `maxspeed:type=[XX]:[legal road category]` scheme really is, as basically every country would need own categories to be precise. Which is unmaintainable. Or maybe none at all - f.e. the default speeds for `trunk`s in Germany could simply be derived from looking at the `oneway` and `lanes` tag. Same for Britain, looking at `lit`, looking at `oneway` (=dual carriageway or not).

**Comment by westnordost** [comment]
The only information that is shared amongst pretty much all countries is:
1. different speed limits apply for rural / urban areas
2. if there is a sign, it overrides the default speed limit (duh!)

Why do I say that the above scheme is ill-conceived? Because it is **not** possible to tag just information # 1 independent of information # 3. Maybe the only reason why I didn't  `(╯°□°）╯︵ ┻━┻` yet and simply delete the maxspeed quest is that there is at least some information value in collecting the information whether a road with no maxspeed signs is within or outside a built-up area, even if the tags may not be so precise/fitting for all countries.

**Comment by westnordost** [comment]
A good (start for a) tagging would be to let the users determine if there is a maxspeed sign or not, if yes, specify the speed limit, if not, simply record this information. Maybe with `maxspeed:signed=no`. But this tag is not used at all yet, so meh 🤷 

And then, as a second step (another quest), one could look at in which country that road with no maxspeed sign is located and see if any additional information is required to be able for software to infer a default speed limit. The road is in Germany and a motorway and a trunk? No further information required. The road is a residential road in Germany? -> Determine if it is rural or not. Oh boy, but we also do not have a tag for that, so meh 🤷

**Comment by arrival-spring** [comment]
Yeah, I see how much of a mess maxspeed is then.
I guess I'm not quite sure about `maxspeed=GB:trunk` being tagged when not established, but `nsl_single` or `nsl_dual` can mostly be implied by `oneway=*` (except if a road is just splitting at a roundabout).

Remove trunk, or just close this?

**Comment by westnordost** [comment]
You mean, remove trunk for all countries or remove trunk for GB?

**Comment by arrival-spring** [comment]
Not sure about other countries, but possibly at least for GB

**Comment by westnordost** [comment]
Hmwell, I try to keep the code as free as possible from such special cases, but looking at the code, it seems it would only be 1-2 lines of code more.

**Comment by arrival-spring** [comment]
Are you going to add that or I'm happy to and open a PR?

**Comment by westnordost** [comment]
A PR would be cool

**Comment by peternewman** [comment]
> What is wrong with `GB:living_street`, aren't there no living streets in Great Britain?

Not by that name in UK legislation:
https://www.legislation.gov.uk/all?text=%22living%20streets%22

There's a charity trying to get people to walk more:
https://www.livingstreets.org.uk/

It looks like they are Home zones in the UK, so perhaps we just need to update the translation:
https://en.wikipedia.org/wiki/Home_zone

We also have pedestrianised areas and pedestrian priority in some places I think, I'm not clear if these are quite the same thing.

**Comment by westnordost** [comment]
The translation is already correct
```
    <string name="quest_maxspeed_answer_living_street">"It is a home zone"</string>
```
