### ISSUE TITLE
mention that standalone nodes are removable?

### ISSUE THREAD

**Issue by matkoniecz** [streetcomplete/StreetComplete#2761]
https://github.com/streetcomplete/StreetComplete/wiki/Adding-new-Quests-to-StreetComplete was written before a new features were added

> no elements can be added or removed.

not sure how it can be clarified, without muiddling it. Maybe

> generally no elements can be added or removed.

or 

> no elements can be added or removed (except removal of standalone nodes).

or

> no elements can be added or removed[1]

and

> [1]except removal of standalone nodes

placed below?

----------------------------------------

Or just ignore that as unimportant?

**Comment by westnordost** [comment]
Yes, ignore as unimportant, because the ability to remove POIs is very specific to that answer option and very specific to POIs.

It is true that in the future, after the architecture refactor is merged, it becomes somewhat easier to do more complex things, but nothing I would want to advertise in the quest guidelines because it is still a lot of work.
