### ISSUE TITLE
Add "no markings, clear lane count'

### ISSUE THREAD

**Issue by matkoniecz** [streetcomplete/StreetComplete#2774]
**Use case**
In many cases there are no lane markings, but lane count is very clear. (I can attach Street View examples)

**Proposed Solution**
Add one more option to leave quest. It should not cause invalid data appearing, as there is a clear escape hatch with existing "no markings" option

I will definitely implement it, not sure should I push it to fork only or also open StreetComplete PR

**Comment by westnordost** [comment]
Hmm, might be confusing. If you are going to implement it anyway for your fork, you could post a screenshot of the finished implementation here and we can see if it is ok.
I am a bit worried that there are then too many choices. The "no markings, clear lane count" option would also need to be similar to the "different lane count for each direction option", wouldn't it? F.e. the road might be broad enough for 3 lanes.

**Comment by Cj-Malone** [comment]
Potentially this could be another quest, with asked after the current lane quest. If the user says no marked lanes on the current quest the new quest wouldn't be asked (due to `lane_markings=no`). But if the user answers with a lane count then `lanes` is set, and `lane_markings` isn't, the new quest could be a simple "Are the lanes here marked?" with `lane_markings=yes` vs `lane_markings=no`. The current quest may be edited to place less emphasis on the lanes being marked.

**Comment by smichel17** [comment]
@Cj-Malone See https://github.com/streetcomplete/StreetComplete/issues/2299 for context on why markings are emphasized

**Comment by westnordost** [comment]
So,

**pro**:
- Add lane count even if it is unmarked can help routers to estimate road throughput in absence of the `width` tag

**con**
- adding another item (so in total 4) to the UI will clutter it more

**comment**
- if the `width` tag is set, `lanes` (on roads without marked lanes) is much less useful. Letting users measure the road width is on the to do list

**Comment by matkoniecz** [comment]
![screen02](https://user-images.githubusercontent.com/899988/115595651-79cbcd80-a2d7-11eb-9dbb-14e8791ce941.png)


After implementing it and thinking about "there is no obvious lane count AND lane count is clear AND there is a different lane count in each direction" case...

Maybe have "one lane in each direction, no markings" case instead? But it would fail for case of oneway road with one clear lane and no lane markings.

**Comment by matkoniecz** [comment]
And yes, some better icon would be nice - maybe some faint tire marks? Like at real roads https://www.openstreetmap.org/edit?editor=id#map=22/50.10950/19.88422

![screen03](https://user-images.githubusercontent.com/899988/115596298-3cb40b00-a2d8-11eb-842f-fcba2f3f5e1d.png)

**Comment by westnordost** [comment]
Or a car

**Comment by matkoniecz** [comment]
https://github.com/matkoniecz/Zazolc/commit/14c2267baa50256b28634d2ce8e7d4d164d3b4b5 has a preliminary implementation (tested on single place so far, will cotinue testing while using it)

**Comment by matkoniecz** [comment]
Let me know if PR would be welcomed, if you think that it will not be improvement - please close that issue

**Comment by westnordost** [comment]
Or another possibility that avoids presenting so many choices would be that when tapping on "no marked lanes", it asks if the lane count is obvious.

Though, thinking about that, ... the whole concept of "lane count on roads without marked lanes" is maybe a bit unintuitive and would need to be explained. Didn't the original implementation not also have an info text for that that was being improved several times?

**Comment by RubenKelevra** [comment]
I feel like we should abandon the idea to guesstimate a lane count on unmarked roads. There are just too many different possibilities, especially if you look internationally.

The best solution IMHO is to ask for the smallest width for the section of the road and tag this with "maxwidth:physical=*".

This would be useful for routers of larger vehicles and also emergency vehicles and can be easily obtained by "shoe measurements" or by AR apps, like discussed in https://github.com/streetcomplete/StreetComplete/issues/698. 

This approach obviously excludes special lanes like a bus lane, taxi lane as well as parking spaces. But since they can be obstructed, it's fair for routers to assume that they are all the time, to avoid that a large vehicle get stuck.

**Comment by matkoniecz** [comment]
> I feel like we should abandon the idea to guesstimate a lane count on unmarked roads.

I opened this issue because in many cases there is 100% clear `lanes=2` or `lanes=1` despite lanes not being marked, and I think that option to tag this would be useful.

Option for lack of clear lane count would not disappear.

**Comment by matkoniecz** [comment]
In actual use I noticed that larges value is for `lanes=1` (what requires changing interface a bit to allow that answer)

Both for chokepoints where road narrows (and router would try to avoid) and to detect nice small roads  for cyclists.

![IMG_20210429_173143](https://user-images.githubusercontent.com/899988/117131339-9b31bc80-ada1-11eb-85d0-f63aff36742e.jpg)

https://www.google.pl/maps/@50.1159869,19.9154418,3a,75y,241.87h,79.55t/data=!3m6!1e1!3m4!1sBMTPX9emM6bjTQA_R80SqQ!2e0!7i13312!8i6656

![screen06](https://user-images.githubusercontent.com/899988/117131466-c2888980-ada1-11eb-92c5-a9cd71048936.png)

**Comment by westnordost** [comment]
See comment in PR
