### ISSUE TITLE
[v32.0-alpha] newly-visible quests disappear after brief delay

### ISSUE THREAD

**Issue by smichel17** [streetcomplete/StreetComplete#2775]
**How to Reproduce:**
- Answer a building-type quest for a detached house, which does not yet have building levels entered.
    - Building-levels quest appears immediately (released version has a short delay) :tada: 
- Wait a small amount of time (maybe a second, I did not time it).
    - Building-levels quest disappears (even if the form is open) :frowning_face:
- Refresh data (scan for quests here)
    - Building-levels quest appears again (usually — there was one for house number which did not appear again) :neutral_face:

**Versions affected**
- Android 7.0, Galaxy S6 (SM-G920A)
- StreetComplete v32.0-alpha1 (commit bb3452465b7a7073535c21b96828a59f548c7a78)

I can get debug logs & share a specific element, I just wanted to open this issue before I forgot :)

**Comment by westnordost** [comment]
Is auto-sync on or off?

**Comment by smichel17** [comment]
On

**Comment by smichel17** [comment]
If you'd like to look at specific elements, it happened on these houses: https://www.openstreetmap.org/#map=19/42.32503/-72.67109

**Comment by smichel17** [comment]
If you'd like, on my walk today I can create some notes for buildings which are detached houses and probably don't have building levels tagged, so you can pan over there and answer the quests in SC to reproduce.

**Comment by westnordost** [comment]
> I can get debug logs & share a specific element

That would be very helpful! Best the log immediately when solving that quest.

**Comment by westnordost** [comment]
Can reproduce, I don't need a log

**Comment by westnordost** [comment]
Ok, found it. Thank you for testing the new version early, these kind of bug reports are exactly what I hoped for in the phase before the beta release!

So the issue was the following:

1. when solving a quest, an edit that represents this is added. When an edit is added, that edit is applied to a local version of the OSM map data and thus, for the element(s) the edit applies to, it is re-checked what quests are available for these. This works completely offline before upload. This is why you see it immediately.

2. when uploading an edit, the edit is marked synced (=will not be applied to a local version of the OSM map data anymore) and the updated element(s) as they are returned from the OSM API are put into the local version of the OSM map data. The geometry of the updated element(s) is also re-created as the geometry of the updated element(s) might have been changed (for example due to a split-way). However, the necessary information to re-construct the geometry of an element is not included in the OSM API response of the upload - only the changed element is included, f.e. the way itself but not the nodes that make up its geometry. This is why the app takes the missing data from the local copy of the OSM map data.

Now, in that algorithm was a bug, which basically made it work only for relations but not for ways.
