### ISSUE TITLE
[v32.0-alpha] crash after answering first quest

### ISSUE THREAD

**Issue by Helium314** [streetcomplete/StreetComplete#2786]
What I did:
* reset the app ("clear storage" in _App info_)
* have no WiFi
* start the app
* switch auto-upload to off
* get WiFi connection
* manually scan for quests
* answer roof shape quest
* notice crash

I was not able to reproduce this, so maybe some steps are missing.

<details>
 <summary>log</summary>

```
Thread: main
App version: 32.0-alpha1
Device: samsung  serranods, Android 9
Locale: en_GB
Stack trace:
java.lang.NullPointerException: null cannot be cast to non-null type de.westnordost.streetcomplete.controls.UploadButton
	at de.westnordost.streetcomplete.controls.UploadButtonFragment.getUploadButton(UploadButtonFragment.kt:33)
	at de.westnordost.streetcomplete.controls.UploadButtonFragment.updateCount(UploadButtonFragment.kt:89)
	at de.westnordost.streetcomplete.controls.UploadButtonFragment$unsyncedChangesCountListener$1$onIncreased$1.invokeSuspend(UploadButtonFragment.kt:36)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```
</details>

**Comment by westnordost** [comment]
Was the upload button displayed before?

**Comment by Helium314** [comment]
I don't know... only thought about looking after the crash and reading the log.
When trying to reproduce it, the button was always shown (and no crash)

**Comment by westnordost** [comment]
So the `uploadButton` is not-null after the view has been created (`onViewCreated`).
The `unsyncedChangesCountListener` wich ultimatively calls `updateCount` is only registered on `onStart`, so after that.

When you entered the setting, the  `unsyncedChangesCountListener` is unregistered (`onStop`).

I think the only possible explanation is that somehow that listener was not correctly unregistered on `onStop` and when the count then did change, the listener called a fragment that was already removed and had no view anymore.

**Comment by westnordost** [comment]
However, I tested it right now: No, the listener is correctly removed on `onStop`.

Also, the `UploadButtonFragment` is never removed from the `MainFragment` programmatically, so I don't see how `UnsyncedChangesCountSource` could refer to an old `UploadButtonFragment` - there should never be an old one. 

It is true that on configuration change, for example when rotating the display, the Android system will destroy all fragments and activities and recreate them (with the new configuration) from their saved instance state. So this is a situation where fragments that never get removed programmatically do get removed. But in case of StreetComplete, the configuration change for rotating the display is handled by the app itself, so the fragments don't get re-created then. And anyway, see the first sentence of this post.

I also tested what happens if the fragment(s) are recreated by the Android system. (Removed `android:configChanges="orientation|screenSize"` from the Android manifest and rotated the screen). Also, can't reproduce it. The listener is always removed on `onStop`.

**Comment by Helium314** [comment]
I tried several times, but still could not reproduce the crash...

**Comment by Helium314** [comment]
Not sure, but I also might have switched the theme... at least I usually want to have a fixed theme instead of auto-switch.

**Comment by westnordost** [comment]
Well I found a possible race condition:
If the fragment lifecycle reaches `onStart` and then immediately reaches `onStop`, then it is theoretically possible that the listener is removed and after that added (instead of the other way round). So I fixed that. This should make it watertight.
