### ISSUE TITLE
[v32] Edits are not correctly applied when successively splitting a way

### ISSUE THREAD

**Issue by tapetis** [streetcomplete/StreetComplete#2800]
The app does not upload quest answers correctly when the same way is successively split into multiple parts. That is, by using the "Differs on the way..." feature several times in a row and answering one of the newly created quests in between. When uploading, (some of) the later answers and split actions are dropped with the following log messages:

```
Dropped a UpdateElementTagsAction: Element geometry changed substantially
Dropped a SplitWayAction: Way #ID has been changed and the conflict cannot be solved automatically
```

**How to Reproduce**
Different things happen depending on the number of splits. For example, the steps below apply when splitting a way twice:

1. Turn off automatic uploads.
2. Split a way with an unanswered sidewalk|lit|surface|... quest.
3. Answer the quest for one of the two new parts.
4. Split the other part again.
5. Answer the quests for both remaining parts.
6. Click the upload button.
7. The answers for the latter two parts are dropped.

**Versions affected**
App built from the master branch (https://github.com/streetcomplete/StreetComplete/commit/a4032f6d51c9876e071da7fa0c67ae0825133d4a) on April 24, 2021.

**Comment by westnordost** [comment]
Ah ok, so offline it works, but when uploading, the conflicts arise.

It does not really say `Way #ID`, it logs the actual id, right?

**Comment by westnordost** [comment]
So in this case, StreetComplete stumbles over its own conflict-checking. Hmm.

**Comment by westnordost** [comment]
Ok, I think everything is already in place for it to work correctly. The only thing that is missing is that the `ElementEditsDao::updateElementId` needs to update also the ids of the original elements persisted together with each edit. On the `kotlinx-serialization` branch (to be merged into pure-kotlin which itself is to be merged into master), each edit persists the original element the edit was made on. This is done so that the edit can easily check if the element changed in an incompatible way (=> a conflict should be thrown) and also so that in the edit history, the element can be referred to correctly.

So, when an element id is updated because that element has been added to OSM (so, usually updating "-1" to "54656876435" or something), not only the `elementId`s of all the edits referring to that element have to be updated, but all current unsynced edits need to be fetched from the database and potentially updated as for example just one node of an edit made on a way could have been changed.

**Comment by westnordost** [comment]
A cheap solution would be to disregard any elements as potential conflicts that have negative ids, because that means they were added via this app. Not sure if this could have any side-effects.

**Comment by westnordost** [comment]
I think for the cheap solution to potentially lead to a problem (=a real geometry conflict is not treated as one), one would need to
1. split a way
2. answer another quest on that split way
3. upload, but only the splitting of the way
4. extend or split the way in another app
5. finally upload the answer given in step 2

Since step 3 is not really possible - one would need to turn off the phone or enter airplane mode just when the first quest was uploaded, plus step 4 is also not a typical use case, maybe the cheap solution would be feasible here.
