### ISSUE TITLE
Surveillance under Surveillance

### ISSUE THREAD

**Issue by paradx** [streetcomplete/StreetComplete#2816]
The project Surveillance under Surveillance https://sunders.uber.space/ uses the open street map object 
man_made surveillance to tag positions of cameras and other surveillance equipment on open street map. 

One of the initial goals of the project was, to track whether temporary video surveillance during G20 congress in hamburg, was removed after the conference is over. 

Since some of the camera data is not up to date a challenge to tag existing cameras and update the existing cameras with further tags (fixed camera, dome or panning) 

**Use case**
I think many of the tagged cameras are either not existing anymore or are not completely tagged. 

**Proposed Solution**
Add the option to add more information to existing cameras, verify existing data.

**Comment by matkoniecz** [comment]
See #87

**Comment by westnordost** [comment]
Could this be that this ticket is about *re-checking* if a surveillance camera is still there?

If yes, @paradx , what would be a reasonable filter for that? Only outdoor ones maybe?

**Comment by paradx** [comment]
Re-checking would be a very good start. 
 
I think out door ones are the most popular surveillance object in general and it makes sense to filter for outdoor cameras only. 

In some countries it also is a legal difference if you film public space or inside your own home (germany for example)

**Comment by westnordost** [comment]
ok let's start with that. What would be the filter to include that?

**Comment by Helium314** [comment]
`surveillance:type = camera and surveillance ~ public|outdoor`?

**Comment by kjonosm** [comment]
I quite often see `man_made=surveillance` being wrongly added as a property of a feature, like `shop=*` or `amenity=*` instead of it being a single object representing the actual surveillance camera. See e.g. [this](https://overpass-turbo.eu/s/16SM) overpass query.

Is it possible to extract `man_made=surveillance` together with its subtags from the main feature and create a new object within this check?

The newly created `man_made=surveillance` object could then be placed at the same location if the feature is tagged on a node or at the centre of an area feature.

**Comment by westnordost** [comment]
No.

But this is a good hint, we'd want to exclude places like this from the query. How best to do that?

**Comment by matkoniecz** [comment]
> How best to do that?

Mass exclude `tourism=`, `shop`, `craft=` etc like for `barrier=yes` quest?

**Comment by chrt223** [comment]
> Re-checking would be a very good start.

@westnordost : The following characteristics for this quests would be useful:
- **set camera type** (dome / fixed / panning / ALPR ...)
- **set surveillance kind** (public / outdoor / ...)
- **set direction**
- possibly the height or the mount

Why?
Because contributors are likely to mark a camera existence without filling its main characteristics.
