### ISSUE TITLE
New Quest: Inside a built-up area?

### ISSUE THREAD

**Issue by FlorusCiphersmith** [streetcomplete/StreetComplete#2825]
### General
Affected tag(s) to be modified/added: [zone:traffic](https://wiki.openstreetmap.org/wiki/Key:zone:traffic)
Question asked: Is this road inside a built-up area?

A corresponding tag, [zone:traffic](https://wiki.openstreetmap.org/wiki/Key:zone:traffic), was [proposed](https://wiki.openstreetmap.org/wiki/Proposed_features/trafficzone) some time ago. However, in some regions it seems not to be well established.

In Germany, distinguishing between being inside built-up area ("geschlossene Ortschaft") and outside ("freie Strecke") helps to derive traffic rules which are implictely effective in this zone, including speed limits, restrictions on parking, overtaking, and honking.

The [OpenBikeSensor](https://www.openbikesensor.org/)*) project already uses this tag to evaluate the lateral distance of cars overtaking bicyclists: the legal minimum (1.5m or 2m) depends on whether the road lies in-/outside a built-up area and is required to document how often or severe violations are.

The difficulties of deriving the information in this tag from administrative boundaries are partly discussed in the tag [proposal](https://wiki.openstreetmap.org/wiki/Proposed_features/trafficzone). 

It seems like the case zone:traffic=DE:motorway can be derived from highway=motorway|motorway_link. Or should it be added to the quest?

*) Disclaimer: I'm developer in the OpenBikeSensor project.

### Checklist
Checklist for quest suggestions (see guidelines):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary 
- [x] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of elements (Worth the effort)

### Ideas for implementation

**Element selection:** 
All ways
- within German administrative boundaries, AND
- with highway being one of 
trunk|primary|secondary|tertiary|unclassified|residential|trunk_link|primary_link|secondary_link|tertiary_link|living_street|service|track|road, AND
- do not have a zone_traffic tag

**Metadata needed:** 
If this quest is extended to outside Germany, it might be necessary to adapt the highway filter list (see element selection), e.g. based on the [OSM definition](https://wiki.openstreetmap.org/wiki/Key:highway).

**Proposed GUI:**

The selected road  is highlighted on the map, and the user is prompted with the question and the three options of which exactly one can be selected.
Is this road inside a built-up area?
- Yes
- No
- Can not answer

Depending on the user's answer, the tag is set to
Yes: zone:traffic=DE:urban
No:  zone:traffic=DE:rural
Can not answer: (no change)

For illustration of the options, example traffic signs for [entering](https://de.wikipedia.org/wiki/Geschlossene_Ortschaft#/media/Datei:Zeichen_310-50_-_Ortstafel_(Vorderseite)_mit_Kreis,_StVO_1992.svg) and [exiting](https://de.wikipedia.org/wiki/Geschlossene_Ortschaft#/media/Datei:Zeichen_311-50_-_Ortstafel_einseitig,_StVO_1992.svg) the built-up area zone may be used.

The quest icon might be a stylized version of the [you're entering a built-up area sign](https://de.wikipedia.org/wiki/Geschlossene_Ortschaft#/media/Datei:Zeichen_310-50_-_Ortstafel_(Vorderseite)_mit_Kreis,_StVO_1992.svg).

**Comment by westnordost** [comment]
That's sometimes difficult to ascertain on-site. Sure, in the middle of the city, it is of course inside a built-up area. But basically, at least in Germany, you'd need to know if you are past or before a city limit sign.

Wouldn't it be much much easier to ascertain this information by looking at the place from above? I.e. use JOSM?
And actually, if the location of the sign is already mapped, or (at least) the administrative boundary, wouldn't it be quite easy to select in JOSM all roads within that boundary and set `zone:traffic` to `urban`?

**Comment by matkoniecz** [comment]
> Wouldn't it be much much easier to ascertain this information by looking at the place from above? I.e. use JOSM?

In Poland it is utterly impossible as signs are not always placed on edge of residential area. Sometimes signs terminating area are within settlement, with some houses (typically recently build) outside built-up area as far as traffic law is concerned. And sometimes fields between villages are within built-up area.

**Comment by westnordost** [comment]
> In Poland it is utterly impossible as signs are not always placed on edge of residential area.

And how is the built-up traffic zone defined in Poland? I.e. do you need to slow down to 50 when there are houses or do you need to slow down to 50 when there is a city limit sign?

**Comment by matkoniecz** [comment]
Within area delimited by traffic signs. 

D-42 marks start: https://pl.wikipedia.org/wiki/Plik:Znak_d42.svg D-43 marks end: https://pl.wikipedia.org/wiki/Plik:Znak_d43.svg

"when there are houses" would not work due to lack of real planing in land use and sprawl of housing without clear start/end of houses

![screen](https://user-images.githubusercontent.com/899988/116654083-bd35d400-a988-11eb-9e0a-aef2986ded28.png)

**Comment by westnordost** [comment]
Well but in some countries, this is how the law is written. I remember reading som US state legislations that stated that something must be considered a residential area if the house densitity along the street is more than X.

Anyway, taking your example, if you stand somewhere on this road and you don't see a sign in either direction (maybe because there is none, or maybe it is further away in one or the other direction), then you'll be unable to answer that quest.

As said, clearly inside a built-up area and clearly outside, it is easy to answer. But in these areas, it might as well be considered spam - in the sense that the user is bored to always answer this quest with the same question.

What may be better would be to record the location of the city limit sign and from there, tag the zones the right way (using JOSM etc). However, StreetComplete is unfortunately not hte right app for this, as no new nodes can be added
