### ISSUE TITLE
[v32.0-alpha1] Some small bugs

### ISSUE THREAD

**Issue by cyclingcat** [streetcomplete/StreetComplete#2840]
Hi there,

I just installed the freshly released v32.0-alpha1 apk on my devices in order to help find bugs before this version with its major changes will be released to the public. Here are my first observations, I collect them in this ticket. Let me know if you'd prefer one ticket for each issue, I will change it then and close this one.

**Preconditions** 
* My usual two Android devices (smartphone with Android 9.0, tablet with Android 8.1)
* SC v32.0-alpha1 apk downloaded from GitHub and updated from v31.3.

**The issues I encountered so far**

1. Directly after the update the quest count showed a value of 0. However, the information on the "My profile" screen was correct (OSM username, quest count, rankings); after going back to the main screen the number after the star symbol was now correct as well.

2. All the quests I have disabled in my settings were reenabled again! The changed order, however, was preserved.

3. At least some (maybe all) quests I have hidden in the past are visible again.

4. In some quests texts a mysterious number appears. See the following screenshot, (it's [node 4810322593](https://www.openstreetmap.org/node/4810322593)):<br/>
![ref](https://user-images.githubusercontent.com/32601012/116851327-79de9e00-abf2-11eb-9387-6b4f31308e22.jpg)<br/>
The number is the content of a "ref" tag, it seems that this tag is now shown in the text at least for the existence quest if no "name" tag is present for the corresponding node. The node in the screenshot above contains an "operator" tag which would be a better choice for the quest text IMHO as the "ref" tag is often just confusing information for the user. (I have never seen this before with earlier versions. so I'd assume that it has been introduced with v32.)

All of these phenomenons are likely to confuse users, so I'd suggest to find a solution for them. If 2. and 3. are consequences of the architectural change of the app, at least a hint should be presented to the user.

The cycling cat

**Comment by westnordost** [comment]
Thank you for the report! Most of this is not really a bug.

> 1, 2, 3

This is because the whole local database was deleted (replaced), as announced. The statistics, what quests are hidden, what quest types are disabled are all saved in the database.
What is not stored in the database (but in another persistent storage) are your OSM login and the quest order.

So yeah, this might be confusing, but it is likely a will not fix / working as intended.

> 4 

Hm true. I fear it depends on the context if rather `ref` or rather `operator` should be shown. For example, for bus stops, ref is certainly more helpful than the operator. (In the US, many bus stops do not have names but some numbers/identifiers).

**Comment by mnalis** [comment]
Maybe, if name is missing, display both `operator` + `ref` (with empty string substituted for nonexistent tags)? In this case it would result in `Schoko Lädchen 3680` which would be far more understandable and useful to user, and for bus stations it would also show useful text (even if little longer, in case bus stop has both `operator` and `ref` tags).

Alternatively, SC could pick `operator` or `ref` depending on what the main tag is (eg. use `ref` for public transport related tags, and `operator` for others), but that seems like less useful as some information is lost, and more importantly because more exceptions might pop up requiring further tweaking of this check in the future...

**Comment by westnordost** [comment]
Good idea. I looked through the tags and it makes sense for some and does not make things worse for other.

**Comment by westnordost** [comment]
Alright, I adapted the changelog and implemented that operator + ref thing, also for postbox collection times and charging station capacity.

**Comment by cyclingcat** [comment]
Hi there,

I already suspected that 1.-3. would have something to do with the new architecture. So maybe a one-time information screen after the update would be sensible in this case in order to avoid confusion for the users? I'm not sure how many of them will read changelogs...

1. could scare people who fear that their count got lost or something is wrong with their OSM login. 2. could lead to an sudden and unexpected flood of quests (like it did on my devices as I have deactivated house type, root and number of floors quests which now reappeared again), further confusing users who maybe deactivated some quests long time ago, leaving them clueless.

All this together would IMHO justify such an information screen the user will be presented to on the occasion of the first app start after the update, describing which effects he could possibly expect and how to handle them.

The cycling cat

**Comment by matkoniecz** [comment]
If someone is not reading displayed changelog how likely is that they will read changelog displayed in a slightly different form?

(also, note extra implementation effort) 

In theory it could be translated, but likely would be translated in time only for small part of languages.

**Comment by cyclingcat** [comment]
Currently the changelog is hidden behind a button, so the user has to take action. At this time, his confusion could already have begun. My proposed information screen would be present on the main screen _before_ the map and the quests, so the chance will be probably much higher that the user will read it. (Wasn't the changelog shown in a similar way in earlier versions of SC? If it was, would it be able to recycle this code?)

Translation is a point though...

The cycling cat

**Comment by westnordost** [comment]
I usually dismiss changelog or similar screens that pop up when starting an app immediately, almost like a knee jerk reaction I have no control over.

Maybe force of habit from dismissing those cookie / gdpr dislogs or maybe it is because I came opening ithe app with an intent, any side information displayed in between my intent and its execution is perceived as a nuisance. 
Imagine the camera app displaying a message on startup.

I can't be the only one who reacts like that.  So that the changelog is only displayed after a user action is something I added so that more, not less, people read it.

Am 4. Mai 2021 09:05:20 MESZ schrieb cyclingcat ***@***.***>:
>Currently the changelog is hidden behind a button, so the user has to
>take action. At this time, his confusion could already have begun. My
>proposed information screen would be present on the main screen
>_before_ the map and the quests, so the chance will be probably much
>higher that the user will read it. (Wasn't the changelog shown in a
>similar way in earlier versions of SC? If it was, would it be able to
>recycle this code?)
>
>Translation is a point though...
>
>The cycling cat
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/streetcomplete/StreetComplete/issues/2840#issuecomment-831726815

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by cyclingcat** [comment]
> I usually dismiss changelog or similar screens that pop up when starting an app immediately, almost like a knee jerk reaction I have no control over. Maybe force of habit from dismissing those cookie / gdpr dislogs or maybe it is because I came opening ithe app with an intent, any side information displayed in between my intent and its execution is perceived as a nuisance. Imagine the camera app displaying a message on startup. I can't be the only one who reacts like that.

So do I, at least with those notorious and annoying GDPR/cookie warnings. (I even installed [a Firefox add-on](https://www.i-dont-care-about-cookies.eu/) in order to avoid/hide them!) I like to read changelogs though, at least those from applications I like and user on a regular base.

> So that the changelog is only displayed after a user action is something I added so that more, not less, people read it. 

For a pure changelog I fully agree. If a user doesn't care about it, he isn't forced to read it or click an "Ok" button after each update. If a user likes to know what has changed he has the chance to do so (as long as the changelog isn't reduced to commonplace bullshit like "Performance improvements and bugfixes" as often seen).

But here the case is somewhat different. The forthcoming v32 is likely to confuse a lot of users, in particular those who deliberately disabled some quests that would have popped up in a huge number otherwise and those users aren't interested in for some reasons. (Think about the lit quest, the building-related quests or the power pole quest.) Hence my proposal for a one-time information window as an absolute exception.

The cycling cat
