### ISSUE TITLE
Reproducible builds for F-Droid

### ISSUE THREAD

**Issue by rugk** [streetcomplete/StreetComplete#2842]
**Use case**

F-Droid also builds all apps from source ([optionally even reproducible](https://f-droid.org/en/docs/Reproducible_Builds/))-

The aim here would be to prevent the upgrade problem and allow upgrade paths from/to F-Droid:
> Correct, the release from F-Droid is signed by F-Droid, the releases on GitHub and Google Play are signed by me. Installing one over the other is not possible.

I have to admit this is really more of a convenience feature here than a security feature, as this app does not handle very sensitive data – okay, GPS position connected top an OSM account, but well… it publishes that anyway.
So the security aspect of reproducible builds may not be the thing we aim for, but really more convenience. 

**Proposed Solution**

Make it build reproducible, then F-Droid can publish the same release. :smiley: 
See https://reproducible-builds.org/

As I explained, the aim is not a lot, but it would certainly be awesome.
And well… maybe it is not even so hard?

The people from CCTG also managed it and that surprised me as I thought that this would have been quite complex. This is their doc: https://codeberg.org/corona-contact-tracing-germany/cwa-android/src/branch/main/docs/rebuilding.md

**Comment by westnordost** [comment]
> The aim here would be to prevent the upgrade problem

This is not an upgrade problem but a security feature by Android. how would reproducible builds circumvent such a security feature? Asking for a friend

**Comment by westnordost** [comment]
Sorry about that, didn't read the documentation on F-Droid. Will do now.

**Comment by westnordost** [comment]
Alright, read the documentation. It sounds really frickle, in that it is hard to setup and can break at many points. Citation:

> Publishing signed binaries from elsewhere (e.g. the upstream developer) is now possible after verifying that they match ones built using a recipe. Publishing only takes place if there is a proper match. (Which seems very unlikely to be the case unless the exact same tool-chain is used, so I would imagine that unless the person building and signing the incoming binaries uses fdroidserver to build them, probably the exact same buildserver ID, they will not match. But at least we have the functionality to support that.)

... sounds like "theoretically we can achieve that but pratically not".

Anyway, I will not do this as this seems to be some effort and the only gain being that people switching between Google play and F-Droid don't need to uninstall the app in-between. And the additional downside is that this needs maintenance effort because when it breaks, and it can apparently break at many points, then updates on F-Droid will not be published anymore and I have to look into that again.

So, you or anyone is free to try it, but even then I am not sure it should be included as a PR because of that maintenance effort.

**Comment by rugk** [comment]
> ... sounds like "theoretically we can achieve that but pratically not".

Yes, that’s what reproducibility is about. :wink: 

That’s why I linked to CCTG. The usual approach there is a Docker file and actually it did not even look that long, about 20 LOC, so if one wants to get inspired by that, I would suggest that as a starting point.

**Edit:** Actually having a closer look they literally “just” [run/use the F-Droid buildserver](https://git.bubu1.eu/Bubu/fdroidserver). (hopefully in a CI/CD pipeline :wink: )
So yeah, if someone from F-Droid or so reads this and wants to have a look and make this work, that would likely be great.

**Comment by matkoniecz** [comment]
> Yes, that’s what reproducibility is about. wink
No, with sane setups you can actually achieve reproducibility, not just strive toward it.

Until that is actually possible in that case it is likely not worth spending time on it - this is a StreetComplete development project, not a F-droid development project

**Comment by smichel17** [comment]
This is a place where I might be willing to volunteer as an F-Droid **[maintainer](http://kmkeen.com/maintainers-matter/)** of StreetComplete… except that this wouldn't actually solve the problem, because my signature isn't any more compatible than the F-Droid folks'.

Aside, reproducible builds also have the benefit of security/trust — F-Droid will not publish a build you tinkered with privately, and Android's security mechanism prevents them from tinkering with a build — but that's not why @rugk opened this issue, anyway.

**Comment by westnordost** [comment]
Yes, this is advantage of F-Droid. You don't need to trust the developer. Or at least, not trust that developer so much. On the other hand, you need to trust F-Droid. Maybe their build setup is super secure and tamper proof (also from themselves?), but at least you have to trust them that it is.
And of course, F-Droid is a much more juicy target to be attacked or subverted by hackers or other means (independent or secret service backed) than single developers each signing only their own piece of software.

**Comment by westnordost** [comment]
I think what would be best in terms of security if there would be something like "Gentoo-Droid": An app store that instead of installing an APK, downloads the source and compiles it on the local device, then installs it. So, same mechanism as F-Droid but locally on your device. Thoug the disadvantages of that should be clear.

**Comment by smichel17** [comment]
An alternative to address the original issue would be to allow installing the f-droid version alongside the Apk/Play Store version. Implemented as an `fdroid` build flavor that just adds a suffix to the application id, similar to the debug build. You couldn't switch between, but you could install both alongside each other.

**Comment by mnalis** [comment]
Moving to relevant ticket from https://github.com/streetcomplete/StreetComplete/issues/6436#issuecomment-3175227870:

---

> Well, maybe we could have another look at reproducible builds for StreetComplete.

It should not be problematic technically to do, as [SCEE does reproducible builds](https://github.com/Helium314/SCEE): 

> F-Droid releases of SCEE make use of reproducible builds, so releases on F-Droid and GitHub are signed with the same keys. This means you can switch between GitHub and F-Droid releases anytime without needing to uninstall first.

 Works great for SCEE, BTW!

_(reproducible builds are _another_ of F-droid security advantages over Obtainium; just sayin'. As is curated list of apps/no fake pretenders, only listing FOSS apps, etc. So while I'd recommend that @louis-vgn reevalute their stance with better information sources that that article or ask for clarifications, in the end _"trust"_ is a personal and subjective thing and I'm on no crusade here to change people opinions)._

***However***, the problem is that StreetComplete is ***already*** on F-droid signed with different key. Which means that besides importing a few tweaks from SCEE to make SC builds reproducible (easy!), there is a bigger issue of how to make a transition.  

Because, if F-droid just publishes new version signed with @westnordost key (i.e. one used for GitHub builds too), the users who have previously installed the StreetComplete from F-droid will be **unable to upgrade** (they must manually uninstall old and install new version, losing all data in the process). And (maybe) [wouldn't even be notified that the update even exists](https://gitlab.com/fdroid/fdroidclient/-/issues/2974).

While reproducible builds are great idea (security and user-wise), there is **_no painless path to do this transition_** from non-reproducible builds to reproducible builds, and it needs extra code support *and* user interactions. Here is example of how CoMaps [plans to do the transition](https://codeberg.org/comaps/comaps/issues/89#issuecomment-4986753) (but it can't be copy/pasted for StreetComplete, as SC currently uses same appid for both builds). 

Whether SC should still go for Reproducible Builds is thus @westnordost  decision

**Comment by Helium314** [comment]
> Which means that besides importing a few tweaks from SCEE

No tweaks necessary as far as I remember.
At some point I got some weird reproducibility issues, so now I build releases on GitHub as those seem to be always reproducible by F-Droid.

As for the new key: technically _key rotation_ should be possible starting with Android 9 when using [APK signature scheme v3](https://source.android.com/docs/security/features/apksigning/v3?hl=en). But I don't think this works with F-Droid.

**Comment by mnalis** [comment]
> But I don't think this works with F-Droid.

Even if it did, those docs say that _"APK key rotation is **not** recommended for Android 12 (API level 31) and earlier"_ (but I have not delved into reasons why).

**Comment by westnordost** [comment]
Good to know, so maybe in the (somewhat far) future when Android 9 (or 12?) is our minimum API level and F-Droid uses that signature scheme, it may be worthwhile to enable reproducible builds for F-Droid.
