### ISSUE TITLE
[v32.0-alpha1] Sometimes geometry of quest not shown

### ISSUE THREAD

**Issue by westnordost** [streetcomplete/StreetComplete#2862]
When tapping on a quest, very rarely, the geometry is not shown.

What is known:
1. There is not reliable way known yet to reproduce.
2. It occurs only for certain elements, and for those reproducibly
3. Force Stopping the app and restarting solves the issue

**Comment by westnordost** [comment]
@peternewman 

- did you do anything before with the element you can reproduce it with? I.e. split the way, solved another quest etc?
- was the download (or upload) running while you tapped on the quest?
- does it solve the issue if you show the edit history, then close the edit history, then open that quest for which you can reproduce it again?
- instead of force stopping, just ending the app (=removing app from recents) solves the issue too, right?

**Comment by westnordost** [comment]
Related could be another problem that @peternewman reported:

The roof shape quest would not unlock (sometimes) when roof levels was not specified in the building level quest. This would happens if the element at hand has no (valid) geometry.

**Comment by peternewman** [comment]
> @peternewman
> 
> 1. did you do anything before with the element you can reproduce it with? I.e. split the way, solved another quest etc?

Not in this/session or since upgrading to the alpha in either case I don't think. Certainly not splitting. I think just downloading and searching.

> 2. was the download (or upload) running while you tapped on the quest?

Unlikely as I was probably offline. There's a chance it might still have been processing downloaded data as I'd just left WiFi, but I'd probably downloaded it earlier than that (5-10 mins at least).

> 3. does it solve the issue if you show the edit history, then close the edit history, then open that quest for which you can reproduce it again?

I'll try and remember to try that.

> 4. instead of force stopping, just ending the app (=removing app from recents) solves the issue too, right?

Likewise this. I was just jumping to force stop as that's the only way to clear the stuck quest search thing, but maybe that's because it has a notification or is a different type of task.

**Comment by westnordost** [comment]
Please post here if you can still reproduce this with alpha2 or later

**Comment by peternewman** [comment]
I haven't seen it yet on alpha2 although I don't think I've used it quite so much...

**Comment by westnordost** [comment]
I'll close this then
