### ISSUE TITLE
Roof shape quests do not show on buildings with no roof levels without invalidating cache

### ISSUE THREAD

**Issue by Hidooo** [streetcomplete/StreetComplete#2882]
When filling out building:levels, only the ones with roof:levels get the roof:shape quest right afterwards. If there are no roof levels, and you leave that field empty (as instructed, as it is the same as inputting "0" (correct me if I'm wrong)), the roof:shape quest does not come up, if you don't invalidate the cache, or wait for it to invalidate itself.

**How to Reproduce**
1. Tag one building with only building:levels, and one with both building:levels and roof:levels.
2. The one with roof:levels should after a moment get a new quest for roof:shape (if not already tagged, of course), while the other one does not.

**Versions affected**
Android 6.0.1
Streetcomplete 31.3

**Comment by smichel17** [comment]
This part of the code was completely rewritten in v32. You can try out [v32-alpha2](https://github.com/streetcomplete/StreetComplete/releases/tag/v32.0-alpha2) if you'd like (you can install this on top of the play store version; if you're using f-droid you'll need to uninstall first). Otherwise, it doesn't make sense to track this due to the rewrite.

**Comment by Hidooo** [comment]
Well, that's great! I checked the beta program in the Play Store, and it was full. It didn't cross my mind to check Github for newer code :)
