### ISSUE TITLE
32 alpha2: Surface quest asked wrong

### ISSUE THREAD

**Issue by HolgerJeromin** [streetcomplete/StreetComplete#2883]
I was asked AddPathSurface quest for this way

https://www.openstreetmap.org/way/48821604/history

I selected "split way" which was done and uploaded (auto upload). After that I could not select quest (which was shown only on one part). 
Analysing the way I found why I could not select the part.

The way has surface since a few years!

But why was the quest shown in the first place?

**How to Reproduce**

**Versions affected**

v32.0-alpha2

**Comment by Helium314** [comment]
Unpaved surfaces get asked every 4 years. Looks like you have selected the more frequent resurvey intervals, so it gets asked again after 2 years.

The split counts as edit, so now you will have to wait another two years for the quest to re-appear (but actually this behavior should be fixed...)

**Comment by westnordost** [comment]
Should be fixed.... yeah... but can't be fixed. The whole resurvey-stuff is built on a hack because the OSM API does not arrange for the possibility to have an edit date per tag.

If an element is updated - for one reason or another - and there is no `check_date:the_tag_that_I_care_about` on it, then the information that the tag has not been touched for X years is lost, because that information was based on the last edit date of the element.

See https://github.com/streetcomplete/StreetComplete/issues/2861#issuecomment-835806562 onwards.

**Comment by Helium314** [comment]
Is is possible to somehow delay auto-upload of the split for a few minutes?
And would that actually help? Because even without auto-upload, maybe the edit date is changed in the DB, and the ways are not eligible for resurvey any more.

**Comment by westnordost** [comment]
> And would that actually help?

I think not.

**Comment by westnordost** [comment]
I added the mitigation mentioned in #2861, I don't think there is anything else I can do without hackery.

**Comment by HolgerJeromin** [comment]
I would try to use such logic as the following example.
  
  * Have a six year old osm way with `surface=earth` 
  * user split the way
  * create two ways with `check_date:surface=<six years ago (old date)>` (surface only because this was the trigger quest)
  * this way the resulting two ways will retrigger the quest in question, user answers:
  * way 1 will get `surface=concrete` and **no** `check_date:surface`, way 2 will get `check_date:surface=<now>`

The result in the osm db would be exactly the same as without the split (if the user answers both part quests, which is likely).

Or is my `check_date:surface=<six years ago (old date)>` your mentioned hackery?

**Comment by westnordost** [comment]
Hmm, yes, that is the hackery. Not as bad of a hackery I had in mind, but still similar.

Imagine there is a way that has an old `surface=sett` and an old `cycleway=track`. There are quests for both. But if one of them is solved, the other vanishes for the reasons stated. This issue is not limited to splitting a way.

**Comment by HolgerJeromin** [comment]
> This issue is not limited to splitting a way.

But splitting is the most obvious problem to the user.
