### ISSUE TITLE
What is here now - missing some synonyms/matching

### ISSUE THREAD

**Issue by matkoniecz** [streetcomplete/StreetComplete#2928]
**How to Reproduce**
Start iD and create point.

Start SC, select opening hours quest, select does not exists, select "something else"

Fill "Confectionery" in both.

Only iD will list something in matches.

![screen](https://user-images.githubusercontent.com/899988/120062431-a4d9d780-c062-11eb-8aac-eaa830d5cf05.png)

**Versions affected**
API 29 emulator, a0fa130ef

**Comment by westnordost** [comment]
Both the en-GB translation of `craft=confectionery` and en(-US) name of that tag are both "Candy Maker".
"confectionery" is not even mentioned as a term.

I guess this only works in iD because iD falls back to also looking at if the identifier matches the given name. Maybe this makes sense for iD, where users might also input the tag name but for the feature dictionary, I don't think so. That would mean that you could enter "confectionery" in any language and find that preset.

Anyway, this is the wrong repos anyway: https://github.com/westnordost/osmfeatures

**Comment by peternewman** [comment]
FWIW I've fixed the GB translation now.
