### ISSUE TITLE
StreetComplete asks for building type on some buildings that already have types

### ISSUE THREAD

**Issue by Taraxa-OSM** [streetcomplete/StreetComplete#2932]
Examples include way #892479947 (shop=convenience), way #254742465 (shop=optician), and way #891390248 (shop=pet). I thought at first that only shops have this problem, but then noticed that way #892479965 (healthcare=optometrist) has the same issue.

**How to Reproduce**
Scan for quests in Baden, Ontario, and observe the quests for the buildings noted above.

**Versions affected**
StreetComplete v32.0, Android 10
StreetComplete v31, Android 10

**Comment by matkoniecz** [comment]
(1) such tagging (merging shop with building) is relatively common but I would recommend against it - as it merges two distinct elements (shop and building) into one

(2) shop may be in say former church building (`building=church`) but it is relatively rare

(3) buildings with several keys are nevertheless excluded - maybe the same should be done with `shop` and `healthcare` https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/building_type/AddBuildingType.kt#L9-L22

**Comment by Taraxa-OSM** [comment]
> such tagging (merging shop with building) is relatively common but I would recommend against it

I was under the impression that it was explicitly favoured. [Perhaps I misunderstood?](https://wiki.openstreetmap.org/wiki/One_feature,_one_OSM_element)

---

I just tried answering the quest for way #891390248 (pet store "Baden Feed & Supply"), and having StreetComplete tag the building as retail does _not_ destroy information: the "building=retail" tag coexists with "shop=pet", and the building continues to show up as a pet store on iD. This issue is a much smaller concern than I first thought, then.

**Comment by matkoniecz** [comment]
> I was under the impression that it was explicitly favoured. Perhaps I misunderstood?

It kind of depends.

If you consider shop and building as separate elements: then it is discouraged.

If you consider shop and building as a single entity: then it is encouraged.

See for example https://github.com/gravitystorm/openstreetmap-carto/issues/3487 where treating tourism=apartment and its building as a single element was causing unexpected effects.

> and having StreetComplete tag the building as retail does not destroy information: the "building=retail" tag coexists with "shop=pet"

Yes, this quest will typically turn `building=yes` into something more specific (or add historic=yes, abandoned=yes or ruins=yes, in rare case replace by `man_made=silo` or `man_made=storage_tank`), there will be never case when data is removed by it.

**Comment by westnordost** [comment]
Only because there is a shop **in** that building does not mean that the building itself is built as a shop (`building=retail`).

This building is mostly an apartment building, even though it has two shops in the ground floor.
https://www.google.de/maps/@53.5496672,9.9306379,3a,75y,14.96h,99.63t/data=!3m6!1e1!3m4!1s3r1IMwocCOPzn2VK3Rz8jw!2e0!7i13312!8i6656

So anyway, if you find a building that has been constructed as something retail, like your takeaway pizza there
https://www.google.de/maps/@43.4044665,-80.6642359,3a,75y,339.92h,85.29t/data=!3m7!1e1!3m5!1sHm5g0qIfgchSBlXAbao7UA!2e0!6shttps:%2F%2Fstreetviewpixels-pa.googleapis.com%2Fv1%2Fthumbnail%3Fpanoid%3DHm5g0qIfgchSBlXAbao7UA%26cb_client%3Dmaps_sv.tactile.gps%26w%3D203%26h%3D100%26yaw%3D247.50314%26pitch%3D0%26thumbfov%3D100!7i13312!8i6656

then you should simply answer with "Retail building".

**Comment by westnordost** [comment]
By the way, nice town you got next to yours! :-)
