### ISSUE TITLE
Ticket barriers and the barrier quest

### ISSUE THREAD

**Issue by peternewman** [streetcomplete/StreetComplete#2934]
**Use case**
Barrier quest for ticket barriers. From the wiki they should be tagged as turnstile:
https://wiki.openstreetmap.org/wiki/Tag:barrier%3Dturnstile#Ticket_barriers

Even though they don't always turn:
https://www.engadget.com/2019-12-02-tfl-apple-pay-express-transit.html

**Proposed Solution**
Either another image which tags the same thing, or an other answers button.

**Comment by westnordost** [comment]
Is this a theoretical consideration or did you actually stumble upon this and didn't find the right value to select?

**Comment by peternewman** [comment]
It's raised from my real world experience with the new quest (first time I'd seen it):
https://www.openstreetmap.org/note/2690022#map=19/51.44220/-0.18760&layers=N

Until I looked at the wiki I wasn't able to validate that my non-rotary barrier should be tagged as a turnstile (I must admit I assumed there would be a special type for ticket barriers).

**Comment by matkoniecz** [comment]
Alternative photo: https://www.bbc.com/news/uk-england-london-53220111

![screen02](https://user-images.githubusercontent.com/899988/120152524-dfbc4680-c1ed-11eb-8afb-83665e94607e.png)

Is it actually considered as turnstile in general or is it OSM invention/hack to refer to them as turnstiles?

**Comment by harry-wg** [comment]
OSM does consider them to be turnstiles, which is a rather confusing and nasty bodge because they don't bear any resemblance to the recognised dictionary definition of a turnstile or the inituitive understanding of what a turnstile is. Ask a hundred people to draw a turnstile, and I suspect not one of them would draw a TFL ticket gate.

Sadly though, that's all that's available at the moment -- until somebody has some elementary common sense and invents barrier=ticket_gate.

Some people already use that, or a similar variant:
![image](https://user-images.githubusercontent.com/9380304/120167778-0da58900-c1f6-11eb-89d7-a6a7c4e232d4.png)

My preference is ticket_gate because for those with tickets its functionality is more that of a gate than a barrier.

**Comment by matkoniecz** [comment]
So I would say that StreetComplete side "leave note" is the correct solution.

Though it would be likely useful to discuss a new value - though ticket_barrier is also unfortunate. What should be used for ticket barriers that are turnstiles then? Or is it intentional to be used also then? But likely it should be discussed elsewhere.

**Comment by harry-wg** [comment]
Personally I would suggest ticket_gate for all new station ticket gates because:
- even at stations which implement the gate as as a sideways turnstile, its function is that of a ticket gate and its primary purpose is to check the ticket 
- barrier=turnstyle (even where the barrier **is** a turnstyle) doesn't positively imply that the turnstyle is a ticket gate.

**Comment by matkoniecz** [comment]
Either way it is tagging issue, that should be handled before StreetComplete will start using it.

I am putting it on my TODO list (especially as I implemented this quest), but feel free to start tagging discussion about it!

**Comment by westnordost** [comment]
I'd close this then. No need to keep open a ticket here for every issue/incompleteness in OSM tagging.

**Comment by peternewman** [comment]
Yes, apologies, re-reading the wiki I see it says (my emphasis):
> Also used for tagging **some** doors/gates/barriers where you validate your ticket

There are also non-barrier yellow and pink Oyster readers which I guess are similar to ticket validators:
https://tfl.gov.uk/fares/how-to-pay-and-where-to-buy-tickets-and-oyster/pay-as-you-go/touch-pink-card-reader-when-changing-trains
https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dticket_validator

**Comment by matkoniecz** [comment]
Posted to tagging mailing list

**Comment by harry-wg** [comment]
> There are also non-barrier yellow and pink Oyster readers 

... which are neither gates nor turnstiles :)

- The yellow ones are at stations where there isn't room for a ticket gate. They're frequently seen at National Rail stations and London Overground.
- The pink ones are for people to optionally scan to prove they travelled through an approved interchange avoiding a busy zone, and therefore qualify for a reduced fare.

Thus both of these would need to be mapped alongside a way, rather than being a node of that way. And ticket_validator would probably be an appropriate tag for them.

**Comment by peternewman** [comment]
@westnordost having been caught out by this again (or at least not remember the correct answer, despite this thread) and given @matkoniecz mailing list thread didn't get any replies at all, would you accept an additional image for the barrier quest which looks a lot more like an underground/subway gate, but tags the same (currently) correct turnstile tag (until something else is agreed on)?

Potentially one of these could be cropped down:
https://upload.wikimedia.org/wikipedia/commons/8/87/Mansion_House_tube_ticket_hall.jpg
https://upload.wikimedia.org/wikipedia/commons/7/7e/TicketBarriers.jpg

**Comment by matkoniecz** [comment]
Maybe interpret lack of responses as an acceptance? I can also make a proposal and submit it to RFC (without ever going to vote)
