### ISSUE TITLE
existence quest: add option to mark telephones as disused/not working and maybe recheck those

### ISSUE THREAD

**Issue by Lukas458** [streetcomplete/StreetComplete#2956]
**Use case**
For public telephones which get re-checked (existence quest) and maybe other things which might be there, but could be in "not working" status. Public telephones for example get sometimes rerpaired, but other times not or not very quickly. 

**Examples**
Two notes opened by SC users who saw this kind of "problem":
- https://www.openstreetmap.org/note/2585196
- https://www.openstreetmap.org/note/2672764

And here are some more things:
- A public phone which isn't working for years (2017 not, 2018 not, 2019 not) but maybe could get re-surveyed: https://www.openstreetmap.org/node/4838397438/history
- As well as this one: https://www.openstreetmap.org/node/2412235953/
- Here a newspaper article about this issue: https://www.haller-kreisblatt.de/lokal/versmold/22907535_Telefon-ohne-Hoerer-sorgt-im-Versmolder-Rathaus-fuer-Gespraechsbedarf.html

**Proposed Solution**
So don't you think it might be worth to add in the **existence quest** the option, to make an **amenity=telephone** node to an **disused:amenity=telephone** node if the phone is there, but isn't working at the moment?

For example, there could be an option to choose which is called like "phone is there, but isn't working at the moment".

Of course, then disused:amenity=telephone maybe should be added for re-checking, if possible? But maybe this would need another quest, because the question may need to be then something like "is this still there (telephone) and is it working?"

**Comment by mnalis** [comment]
I'm of divided opinion about this. While I see why it would be good (as far as OSM itself is concerned) for telephone to be marked as `disused` (and later as working), by doing it the proposed way we **_reduce the chance the telephone will actually be fixed_**.

So probably it is best as it is now - let the user leave a note (preferably with a photo), and than that same user later (or someone else) will see that note later and contact phone company with locations of broken phones, and ask them to fix it. It should really be citizen duty to report to appropriate institutions things they see broken, IMHO.

**Comment by Lukas458** [comment]
Well, I can see your point, yes.

**Comment by Lee-Carre** [comment]
I've wished for something similar.

In my area, the incumbent telco is decommissioning & removing many public pay-phones (probably on the assumption that ‘everyone has their own phone, now’ or bad old profiteering).

Especially when they were only decommissioned, it was conceivable that they might be restored later. So, disused:* would have been better.

When removed, then removed:* would seem best, instead of outright deletion.

In such cases (and any other non-trivial scenario) I use Vespucci instead.
Part of my rationale was that other, in future, may wish to know where the phone boxes _were_ .

I had a particularly [tricky case with an ATM](http://www.openstreetmap.org/node/1258166321) once; the building was undergoing renovations, and the ground floor was boarded-up. So, it was unclear if its unavailability was temporary or permanent. Thus; neither “yes” nor “no” answers (knowing what each actually does) were applicable. This was another time that using Vespucci was necessary.

**Comment by mnalis** [comment]
@Lee-Carre  for historical purposes, there is https://planet.openstreetmap.org/planet/full-history/ - active database should not contain removed features, but only what is on the ground (unless it is very likely that other mappers will re-add removed features - for examples demolished buildings still visible on latest satellite maps, or vacated shops etc. where they might be _temporarily_ in such lifecycle state)

**Comment by westnordost** [comment]
I also think that it is better to leave a note in that case. I've read the linked notes - a note could actually lead to the damage being reported and fixed.
