### ISSUE TITLE
Cycleway interface didn't recognize one-way road

### ISSUE THREAD

**Issue by westnordost** [streetcomplete/StreetComplete#2959]
For the oneway highway-link seen at https://www.openstreetmap.org/note/2706591 , I was asked if it has a cycleway.

The interface however asked for/showed the left and right side of the road, even though for oneway roads, only the right side should be shown by default.

Can anyone reproduce this for this road?

**Comment by tapetis** [comment]
I can reproduce it with freshly downloaded quests:
![Screenshot_20210613-105709.png](https://user-images.githubusercontent.com/6892794/121801187-5a498500-cc36-11eb-81fb-e70c547e8d5a.png)

**Comment by tapetis** [comment]
I think the reason why both sides are shown is that the two ways ([way1](https://www.openstreetmap.org/way/56701704), [way2](https://www.openstreetmap.org/way/35030956)) are tagged as `highway=residential`, but this value is not included in the following filter:

https://github.com/streetcomplete/StreetComplete/blob/fb4a2954cf84943259c2119e3ddc81c0d496bfa6/app/src/main/java/de/westnordost/streetcomplete/quests/cycleway/AddCyclewayForm.kt#L46-L50

**Comment by Lee-Carre** [comment]
I recall encountering this a few times (though I can't recall any specific examples which would still display the quest, having answered the question literally in each case).

I had assumed that it asked both ways for bicycles, because while the road might be oneway for motor vehicles, that may not be the case for bicycles (just like it often isn't for pedestrians).

None of the instances I encountered, for which I checked the existing tags, stated explicitly that the road was oneway for bicycles.

However, I also recall encountering cycleway quests which asked only for one direction. I assumed, in those cases, that the way was marked as oneway for more than just motor vehicles; though, admittedly, I neglected to check the existing tags.

**Comment by westnordost** [comment]
Okay, I realize now that this is kind of like a feature, not a bug.

The tagging issue here is that there is no `residential_link` or `unclassified_link`.

So, it is not possible to distinguish residential roads and just a turn lane from a residential road (or in micro-mapping cases, even just an island at the traffic lights where the pedestrians cross such as the one in the OP).

And of course, we **do want** to ask for the cycleway on **both sides** for residential oneway roads.

So, if there was an additional tag to denote that a particular road (unclassified or residential) is actually a link, then we could solve this. But it does not look to be the case.
