### ISSUE TITLE
Allow users to change the language

### ISSUE THREAD

**Issue by Diridibindy** [streetcomplete/StreetComplete#2964]
**Use case**
I know 2 languages, English and my native language. I generally prefer English when dealing with programs and UI, but in SC the names of the streets are in my native language and the UI is in English. It creates a sort of disparity and is unconfortable. 

**Proposed Solution**
Adding a simple language switch would be enough. The language switcher could also show how well translated the language is (This could just use the same data as the button in About -> "Help translate this app").

**Comment by matkoniecz** [comment]
See #1246, #29, #52, #1064, #2643

If you are using Android below 7.0 then certain missing feature was added to Android 7.0+ - see https://github.com/streetcomplete/StreetComplete/issues/52#issuecomment-291071982

In general implementing such functionality is possible but extremely annoying as apps are not supported to provide such functionality.

**Comment by cyclingcat** [comment]
> In general implementing such functionality is theoretically possible but extremely annoying as apps are not supported to provide such functionality.

Really? I just checked some very popular open source apps on my phone: Many of them give the user the possibility to either use the system language or use a language of his choice. (Examples are OsmAnd, K-9 Mail, Telegram and Firefox.) I'm not a developer though...

Being German, I don't need this feature myself, but maybe users from countries with less widely used languages (and thus fewer users and translation participants!) would appreciate switching SC to their second language (e. g. French) if the translation to their native languages aren't complete or misunderstandable. For a tool which edits a database it's even more important that the phrases are precise enough in order to avoid systematic tagging errors due to ambiguous translations. (We even discussed details of English and German wordings here!)

The cycling cat

**Comment by mnalis** [comment]
IIRC main argument against it (in other issues) was not 400 millions of dollars worth of complexity (after all, there is sample working code in OsmAnd for example: [GlobalSettingsFragment.java#L104](https://github.com/osmandapp/OsmAnd/blob/master/OsmAnd/src/net/osmand/plus/settings/fragments/GlobalSettingsFragment.java#L104)  and [LocaleHelper.java#L25](https://github.com/osmandapp/OsmAnd/blob/master/OsmAnd/src/net/osmand/plus/helpers/LocaleHelper.java#L25)) but the fact that it is/feels kludgy, as it requires app restart on each change as Android does not support it natively.

However, the argument that the user should use system settings as it is OS-provided also [does not sit well with me](https://github.com/streetcomplete/StreetComplete/issues/2643#issuecomment-792952040) (after all, we do have for example theme selection in  `Settings`, where there is **not only** OS-provided `System default` option, but **user can manually override** to other values for SC specifically - they way I feel language selection should also work: default to system settings, but allow user to override. IMHO language is as least as important, if not more, as the visual theme).

But it is what it is. The devel(s) has several times voiced their opposition to the idea, an although I think the sheer number of times it was suggested might indicate there is need for it, I respect their decision (not to mention knowledge of codebase and complexity issues).

**Comment by mnalis** [comment]
- (ref. related https://github.com/streetcomplete/StreetComplete/pull/5623)
