### ISSUE TITLE
Implement a setting to disable sounds

### ISSUE THREAD

**Issue by AlertSubject** [streetcomplete/StreetComplete#2966]
**Use case**
I often use streetcomplete when I'm on the passenger seat. Most of the time I'm connected to the cars Bluetooth to play music. So being able to turn off the *plop* sounds each would be amazing.

**Proposed Solution**
Implement a setting that let's the user disable sounds

**Comment by Helium314** [comment]
I never had any sounds coming from StreetComplete, independent of any _do not disturb_ or _vibrate_ phone setting. So I guess you can disable it in the _Sound_ category of the system settings (not sure which setting exactly)

**Comment by AlertSubject** [comment]
> I never had any sounds coming from StreetComplete, independent of any _do not disturb_ or _vibrate_ phone setting. So I guess you can disable it in the _Sound_ category of the system settings (not sure which setting exactly)

Same for me before I switched phones
Previously I had a oneplus 6, now I have the oneplus 9 pro

All my phones have always been set to silent (no vibration, no notification sound)
The plop sound effect only occurs when the media volume is turned up
I can't remember ever having heard that on my previous phone

**Comment by westnordost** [comment]
Exactly, the sounds will only be played if [`Settings.System.SOUND_EFFECTS_ENABLED`](https://developer.android.com/reference/android/provider/Settings.System#SOUND_EFFECTS_ENABLED) is on.

If that setting does not exist (always on?) or does not work, this is really not an issue of the app.

**Comment by mnalis** [comment]
Wait, StreetComplete ***has sounds***? When? When quest is solved? (Not that I miss them terribly, but I'm genuinely wondering and would like to try them out)

I've never encountered any sounds from SC on at least 5 different phones (of makers Huawei, Xiaomi, LG, Samsung) neither on stock nor custom ROMs (CyanogenMod / LineageOS). Including the kids phone, which I'd wager has all possible sound settings maxed out all the time :smile: 

Quickly checking closest phone (Huawei P30 Pro with EMUI 11/Android 10), there are 4 Sound settings:
- Ringer, Notifications
- Alarms
- Music, Video, Games
- Calls

and all of them are at least halfway to full, yet I hear no sounds from SC `v32.1`

Can anyone (who has sounds) identify what is the setting called on their phone?

**Comment by Helium314** [comment]
On my phone, `SOUND_EFFECTS_ENABLED` is enabled when enabling _touch sounds_ in settings.
But I still didn't hear anything from SC in a quick test.

**Comment by mnalis** [comment]
Thanks for the pointer @Helium314! 

I've looked around and found extra boolean settings by searching for `touch` and `click` instead of `sound`. It is called `Screen touch` here (which is separate from  `keypad tones` toggle) and it is `System haptics` / `more settings` section. 

It is extremely annoying even in the first few minutes (not just in SC but everywhere - ***every*** touch of the screen produces *click* noise), but it does seem to enable StreetComplete-specific sound effect too (not only *click* noise on every click of course as in OS/other apps, but also different *plop* noise on solving the quest).

Also, in addition to that `Screen touch` boolean setting, it seems that volume of effect **additionally** depends on:
- volume of one of the *click* sounds (of which there appears to be two) seems to depend on `Ringer, Notifications` sound volume slider
- volume of *plop* sounds (when quest solved) seems to depend of `Music, Videos, Games` sound volume slider
- volume of second of *click* sounds seems unaffected by volume sliders
 
With my curiosity satisfied, I'll hurry to disable it again :smiley: 

(I've updated [FAQ](https://wiki.openstreetmap.org/wiki/StreetComplete/FAQ) with pointer)

**Comment by mnalis** [comment]
- (somewhat related sound setting request: https://github.com/streetcomplete/StreetComplete/issues/48)

**Comment by endolith** [comment]
Why can't you just add a checkbox to the setting to disable the sounds?  Why does this need to be so complicated?  We don't want to disable sound for the entire operating system.  We don't want to disable sound for all touch events or all notifications.  We just want to disable sounds for _this particular app_.  Why so much resistance to adding a simple toggle?
