### ISSUE TITLE
Feature: Undo Edits

### ISSUE THREAD

**Issue by pavlukivan** [streetcomplete/StreetComplete#2970]
**Use case**

I'm new to OSM, and today I tried to contribute a bunch. Sadly, I misinterpreted some quest answers and some of the stuff I saw, and ended up submitting the wrong data. I'll now have to fix it manually, but it would've been way easier if the app just had an undo button.

**Proposed Solution**

A simple submission history with an undo button. I assume buffering time needs to be increased to let the user undo the edits too.

**Comment by matkoniecz** [comment]
Is undo button in the bottom left working?

Which questions were unclear? If you are using any language version other than English you may also look whether translation is improvable ( see https://github.com/streetcomplete/StreetComplete/blob/master/CONTRIBUTING.md#translating-the-app ).

**Comment by pavlukivan** [comment]
oh, i haven't seen the undo button... maybe it's just me then, i didn't notice it. As of the questions, it's mostly stuff like not knowing whether an attic should count as a storey, or confusing "bus stop has shelter" and "bus stop has a cover". Other stuff was simply a product of my inattention, confusing 2 similar roof shapes or mislabeling a building as another building nearby.

**Comment by pavlukivan** [comment]
I'll close it then, even if the undo button wasn't discoverable enough for me it does exist.

**Comment by mnalis** [comment]
adding reference https://github.com/streetcomplete/StreetComplete/issues/2973 for confusing "bus stop has shelter" / "bus stop has a cover".

**Comment by mnalis** [comment]
@pavlukivan if you have an idea how it would have been more discoverable for you (while it is fresh in your mind), please feel to comment. (for example for me, I first look for FAQ in Help, and only after that go to Github issues - but [FAQ](https://wiki.openstreetmap.org/wiki/StreetComplete/FAQ) that mentions this issue is not currently linked directly from StreetComplete application, so it would be an improvement)
