### ISSUE TITLE
Convert "Does the bus stop have a shelter?" quest to a grid of responses.

### ISSUE THREAD

**Issue by andrewharvey** [streetcomplete/StreetComplete#2973]
The current quest asks about a Shelter with Yes/No, however hidden under other answers is "Whole stop is covered". I respect like myself many users don't realise this hidden answer and have been randomly answering covered stops as yes/no. Their reasoning being "yes it's sheltered" or "no there isn't a dedicated shelter, even though it's undercover".

To reduce this error, a grid of answers with photos, of no shelter, shelter and undercover (eg under an awning or building) as answers will make it clear to users what options they have to answer.

**Comment by mnalis** [comment]
Interesting, I wasn't even aware that there is an separate option `Whole stop is covered`, for exactly the reason you mention - if some quest asks `yes`/`no` question, and the answer is **obviously** `yes`, I would never try to look in extra options for `"better yes"`. (I would only look into extra options if situation is more like _"It is neither `yes` nor `no`, I can't decide, let's leave the note"_)

Also, quick look at [highway=bus_stop](https://wiki.openstreetmap.org/wiki/Tag:highway=bus_stop) (sections with `shelter` and `covered`) does not indicate to me what this `Whole stop is covered` would actually tag. I'll take a look at the code, but this is usually strange sign if I can't deduce what some answer to SC question would actually tag in OSM (after looking at OSM wiki for that feature and related tags)... Could easily be that the OSM wiki needs updating, though.

**Comment by FloEdelmann** [comment]
> I'll take a look at the code

https://github.com/streetcomplete/StreetComplete/blob/7fa96e37db601c33f70237ad3951eec7a0c71413/app/src/main/java/de/westnordost/streetcomplete/quests/bus_stop_shelter/AddBusStopShelter.kt#L47-L54

**Comment by mnalis** [comment]
Ah, according to [AddBusStopShelter.kt#L46 ](https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/bus_stop_shelter/AddBusStopShelter.kt#L46) and [AddBusStopShelterForm.kt#L10](https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/bus_stop_shelter/AddBusStopShelterForm.kt#L10), it seems that man `yes` / `no` answers set `shelter=yes` / `shelter=no` while the alternative answer `Whole stop is covered`  removes `shelter` and adds (weaker) `covered=yes`

**Comment by smichel17** [comment]
> I wasn't even aware that there is an separate option […] I would only look into ehxtra options if situation is more like "It is neither yes nor no, I can't decide, let's leave the note"

That's basically my reasoning for proposing https://github.com/streetcomplete/StreetComplete/issues/1913#issuecomment-828632563.  
See https://github.com/streetcomplete/StreetComplete/discussions/2789#discussioncomment-889066 for a few other examples of confusion (I know there are more, but I didn't search very hard).

**Comment by westnordost** [comment]
The answer option is in the other answers menu because very very few bus stops don't have an indidivual shelter but are still covered. The answer is for for example bus terminals that have a huge roof that covers all the bus stops situated at that terminal.

If the bus stop is situated at a ridge and you could take shelter there, or is situated at a roofed entrance to a public building, or if there is some other "non-official" shelter directly at the stop, I'd still say that tagging `shelter=yes` is good.

So when the user is asked about whether a bus stop that is covered by a bus terminal's roof has a shelter, neither "yes" nor "no" for shelter shouldn't really present itself. That's when the user should look into the other answers menu. And to be honest, even if he answered "yes", that would be fine / not really wrong too. After all, the purpose of the tag is to indicate if the waiting passenger is protected from the weather. That would be the same for both covered=yes and shelter=yes.

So, I decided to close this but I hope this explanation swayed you.
