### ISSUE TITLE
Suggestion to move away from Poeditor

### ISSUE THREAD

**Issue by mishari** [streetcomplete/StreetComplete#2978]
**Use case**
Poeditor currently used for localization is missing some features, including Glossary and Translation memory, making translation somewhat difficult and inconsistent

**Proposed Solution**
Weblate is a great platform that provides context to refer to so translate and provides support for open source projects, I would like the project to consider moving localization efforts there.

**Comment by westnordost** [comment]
Related: #1035, #1099

I looked at weblate 6 years ago when I started this project but decided to use POEditor. Maybe it changed for the better. In any case, a prerequisite for even thinking about moving to a different platform would be to extract the number of contributions made by each translator in POEditor so that information about who contributed how much to the translations is not lost.

I created the ticket at #2980

**Comment by comradekingu** [comment]
@westnordost So now Weblate can be used?
Poeditor is closed source and has this in its terms of service
"9. Modification

CODE WHALE reserves the right to change the Terms from time to time in its sole discretion without any notifications regarding this matter. "
