### ISSUE TITLE
Comments added to notes outside of SC hide notes inside of SC for owner of comment

### ISSUE THREAD

**Issue by dbdean** [streetcomplete/StreetComplete#3002]
If you are a an SC user and you add a comment (outside of SC) to a note (either yours or someone else's) then that note will no longer show up for you in SC. This means that, for example, if I see a comment by someone else, and add a comment to that note (using the web) - maybe to indicate something I think needs surveying - then that note will get hidden from me in SC.

**How to Reproduce**

Find or create a note (outside of SC). That note will show up for you in SC.

Add a comment to that note (outside of SC). That note will then disappear (for you) in SC.

**Versions affected**

SC v33.0-beta1
Android 10

**Comment by dbdean** [comment]
I still want comments that I make in SC to hide though, to be clear.

**Comment by dbdean** [comment]
Could we have the show logic showing all notes with comments, but add them to the hidden quests as we create them in SC?

Then add some logic to bring them back if a new comment is added?

**Comment by dbdean** [comment]
The closed PR above was suggesting that we add something to SC comments (like 'via StreetComplete') so that SC can differentiate between notes created in SC or otherwise. It did seem to pass muster as the right direction to fix this problem.

**Comment by andrewharvey** [comment]
Agreed, sometimes I'll open a note with SC, then later editing realise I need to survey again so will add a comment to my own note, but I then need that note to show up again in SC so I can add another comment after surveying.

**Comment by smichel17** [comment]
Just brainstorming, not endorsing this idea: We *could* track the "created by SC" metadata outside of official OSM infrastructure. That is, after commenting on a note, the app would ping the SC statistics server and send the note ID, and expose an api to query whether a given comment was stored there.

I don't really like this idea because it's a slippery slope toward becoming dependent on an external server (currently the only non-OSM data is note photos), but it is an option.

**Comment by westnordost** [comment]
Maybe you should not propose ideas you yourself don't like.

I think I will implement simply that a #surveyme nulls out the "don't show comments from yourself" rule
