### ISSUE TITLE
Allow add pictures instead of takeing photo

### ISSUE THREAD

**Issue by Mannshoch** [streetcomplete/StreetComplete#3014]
**Use case**
I try to find a Workflow to enhance Opening Hours for location. Normally I have to stay in front of the store and insert use streetcomplete. For me that's not usable. It's more easy to take a photo and use streetcomplete later.

**Proposed Solution**
Please add a possibility to not only use the camera but also attach a photo from the mobilphone gallery.

1. Tick the opening Our pin.
2. choose a (new) galary icon.
3. choose One photo
4. Show the photo 
5. Allow to cut it to the right size
6. Allow to:
   - Upload the Photo.
   - either overlay the opening hour insert tool to set up instead of upload the photo.

**Comment by westnordost** [comment]
This is a duplicate. See #2813, #1730

In a nutshell: 
Requiring to take a photo instead of the ability to add any graphic  is a soft guarantee that the picture is not copyrighted, illegal or worse and thus keeps me free of any copyright claims etc. I don't have the time to moderate this service.

**Comment by Mannshoch** [comment]
Interesting point. In that case I would propose to allow to this.
> either overlay the opening hour insert tool to set up instead of upload the photo.

**Comment by westnordost** [comment]
I don't understand

**Comment by Mannshoch** [comment]
If I take a photo to tag it later, I need a good possibilty to take the date from a Photo. At moment I have to switch several time between Photo-galery and streetcomplete. So, If I start an edit of the opening time, it would be good to have the possibility to show a photo beside the time.

**Comment by westnordost** [comment]
You can use the split screen feature

**Comment by maper64** [comment]
I agree to the option of selecting a photo from the mobile phone gallery. Auror rights? Who takes pictures of the surface of the road, for example, and claims copyright? Moreover, these photos can be deleted after editing. These photos will not be published anywhere for a long time, they could be deleted after finishing editing. I'm in favor of complying with GDPRS - the ban on displaying people (faces) without their consent, but random pedestrians are just an illustration.

I also don't understand the instructions above.

**Comment by matkoniecz** [comment]
> Auror rights? Who takes pictures of the surface of the road, for example, and claims copyright?

1) copyright is assigned automatically

2) the risk here is that people would upload images that are not actually of place they surveyed but a potentially problematic material

**Comment by westnordost** [comment]
Upload from gallery will be enabled in the app if/when the feature to add pictures to a note comment will be implemented for osm.org itself. 

I remember that one of the admins actually approached me, musing that it is so useful, it may be worth adding to osm notes proper. When I mentioned that these will require a bigger effort for DWG because the chance for misuse is higher than with text-only notes, he seemed less enthusiastic but I don't think it would be a deal breaker, as such things could be mitigated (for example only allowing it for logged in users; adding a report-button to the notes feature in general; rate-limit / picture limit; ...). So, maybe the only thing which is missing is that someone implements it. See https://github.com/openstreetmap/openstreetmap-website/issues/395 (last reply is 5 years old, so I am pretty sure that the restrictions changed)

**Comment by Mannshoch** [comment]
For the Record. The goal is here to set the opening hour from photo. Currently, I use split screen as mentioned. But I do not like it. I would prefer a way of overlay the Clock input over a photo from the gallery.

I second the possible and more easy way to create copyright Problem if using images from the gallery and uploading them is allowed. 
I would solve this problem by cleanup images that are used in an already closed Comment on OpenStreetMap. As far I see Images are still accessible even a Comment where they are used is closed.
