### ISSUE TITLE
answering pavement yes/no by swiping

### ISSUE THREAD

**Issue by JensKorte** [streetcomplete/StreetComplete#3029]
**Use case**
When I get a question about pavement(s) to the street, I need to click many times to answer the questions. I could be faster, if I could answer the 2 questions by swiping.

**Proposed Solution**
The illustration of the street should be like the direction on the map. Swipe the line in the middle of pavement and street to close the pavement. the word pavement could be in grey in the beginning with a ?. If the answer is no, the ~pavement~ could be stroke or only the upper or lower half of it could be visible. If the answer is yes, the word could be black with a !.

Question: Is there a pavement?

```
------------
pavement?         _
------------    no^ * v yes
<- street             -
--- --- ---
street ->        _
------------   yes^ * v no
pavement?             -
------------

------------
pavement !        _
------------    no^ * v YES
street                -
--- --- ---
street             _
------------    yes^ * v NO
~pavement~             -
------------
```

replace the * with a hand or an icon, that show where to grab

**Comment by westnordost** [comment]
Hm no, I think the current solution is better:
- It would be hard to communicate to the user how the proposed UI works.
- it would not really be a lot faster. And it doesn't matter that much, because for a quest like the sidewalk quest, it usually takes longer to check the actual situation than to select the answer in the UI (you have to walk the whole street or at least see it - on both sides - before you can make an answer)
- it is planned to make the boolean option into a three-answers option: yes, no, separate to be consistent with the cycleway form
- the proposed UI would be inconsistent with other places where this kind of side-select UI is used.

**Comment by smichel17** [comment]
Related: https://github.com/streetcomplete/StreetComplete/discussions/2684
