### ISSUE TITLE
Add new point of interest on the map

### ISSUE THREAD

**Issue by cnovel** [streetcomplete/StreetComplete#3032]
**Use case**
As a user, I want to be able to add new point of interest on the map.

It has been suggested on [Reddit](https://www.reddit.com/r/france/comments/ofugho/cartographie_openstreetmap_version_acc%C3%A9l%C3%A9r%C3%A9e/h4g647o/)(FR) that some people are mapping points of interest (drinkable water eg), and the workflow is not ideal currently:

 * Long press on the map -> add new note
 * Back at home, go through notes and add the points with OSM web editor

**Proposed Solution**
Long press has a new option : "Add point of interest".
When clicking on it, we go through categories in order to add new information, then the POI becomes a new quest object. Maybe it would be nice to directly ask questions about it.

I understand this isn't an easy change, because the scroll through categories is difficult to implement due to the very wide range of categories in OSM.

**Comment by cyclingcat** [comment]
Hi there,

this has been rejected before. See for example issue #1945 which includes a major reason for this: You simply cannot tell from the SC map if the POI you want to add isn't already in the OSM database.

But have you ever tried OsmAnd for this? My experiences are quite positive since they added the "Quick Actions" feature which explicitly allows adding POIs. This way I have predefined some buttons which simply add some kinds of POIs without further action: Benches, waste baskets, some kinds of vending machines, cycle parkings, recycling containers, and more. The workflow is simple: Press a button on the map, move the map to the marker, press the quick action button, done. (However, in order to check if the object really doesn't exist yet you have sometimes to zoom the map to a level of ~ 20 m!)

And what's best: If you configure OsmAnd to upload the changes immediately, you can trigger a quest reload in SC after some seconds and you will see the quests for the freshly created POIs! This way I add backrests to benches or the various cycling parking tags while on-site without having to fiddle with tag names on the smartphone display.

For me, OSMAnd is getting more and more a companion app to SC. A well fitting pair.

The cycling cat

**Comment by cnovel** [comment]
Hello Cycling cat,

Thanks for the explanation it makes sense! I'll try with OsmAnd and OSM Go. I'm closing the request then.

Cyril
