### ISSUE TITLE
Eigene Notizen nicht mehr sichtbar

### ISSUE THREAD

**Issue by biketeur** [streetcomplete/StreetComplete#3049]
Seit dem letzten Update werden meine eigenen Notizen nicht mehr angezeigt.

**How to Reproduce**

**Versions affected**

**Comment by smichel17** [comment]
This was intentional — see https://github.com/streetcomplete/StreetComplete/issues/2692#issuecomment-850715112.

If you want the note to be shown anyway, you can add "#surveyme" — see https://github.com/streetcomplete/StreetComplete/issues/3002#issuecomment-870468356

<details><summary>Automatische Deutsch-Übersetzung mit deepl.com</summary>

Dies war beabsichtigt - siehe https://github.com/streetcomplete/StreetComplete/issues/2692#issuecomment-850715112.

Wenn Sie möchten, dass der Hinweis trotzdem angezeigt wird, können Sie "#surveyme" hinzufügen - siehe https://github.com/streetcomplete/StreetComplete/issues/3002#issuecomment-870468356

</details>

**Comment by biketeur** [comment]
Könnte mir bitte jemand aufzeigen, wie man  "#surveyme" in SC einstellt.
Ich finde diese Möglichkeit nicht.
Vielen Dank im voraus.

**Comment by FloEdelmann** [comment]
Einfach #surveyme im Text einer Notiz oder eines Kommentars schreiben, dann wird die Notiz in StreetComplete immer angezeigt.

**Comment by biketeur** [comment]
DankeAm 13.07.2021 09:03 schrieb Flo Edelmann ***@***.***>:
Einfach #surveyme im Text einer Notiz oder eines Kommentars schreiben, dann wird die Notiz in StreetComplete immer angezeigt.
