### ISSUE TITLE
Option disable auto zoom when selecting quest

### ISSUE THREAD

**Issue by mathiash98** [streetcomplete/StreetComplete#3051]
**Use case**
I often use SC as a passenger in car in areas outside of cities there are quite few quests, but when they appear I don't have much time to answer. 

The auto zoom makes the process much less efficient than it could be and is a bit annoying as well. 

**Proposed Solution**
Option to disable auto zoom when selecting quest. 

I'll see if I get time this vacation to implement this myself, but if someone beats me to it, please do 🥇 

Things to do:
- [ ] Add option in settings menu: `preferences.xml`
- [ ] Add translation to default strings file `main/res/values/strings.xml`
- [ ] Add const in `Prefs.kt`
- [ ] Inject `SharedPreferences` in `QuestsMapFragment.kt`
- [ ] Check if `DISPLAY_QUEST_CLICK_FIT_BOUNDS` setting is enabled in `startFocusQuest` function in `QuestsMapFragment.kt`. Something like this below:
```Kotlin
// Auto zoom to quest ways and nodes is an optional setting
if (prefs.getBoolean(Prefs.QUEST_CLICK_FIT_BOUNDS, true)) {
    geometryMapComponent?.beginFocusGeometry(quest.geometry, offset)
}
```

Please add anything that I might have missed.

**Comment by westnordost** [comment]
There are different constraints that will trigger the app to zoom to an element. It does not always zoom. It only zooms (out) if...
- the element is either not completely in view. This should not be changed. The user must (be forced to) always see the full element he is going to supply an answer for
- the element is too far away, i.e. is being displayed too small. This could be adjusted I guess.

I changed it so that the difference at which the app will only zoom in automatically must be 50% greater.
