### ISSUE TITLE
Animist religion for Thai shrines

### ISSUE THREAD

**Issue by mishari** [streetcomplete/StreetComplete#3063]
Many shrines in Thailand should be tagged religion=animist, I would like to request this as an option in the app.

**Comment by westnordost** [comment]
Hmm, animist is not really a religion, as much as "monotheism" is not a religion (but a category of religions).

But ok.

Are you referring to things like all those little spirit houses in front of many buildings? If yes,  I was under the impression that this animist practice was rather looked as as a mere aspect of Thai (folk) Buddhism, not something separate.

F.e., the owner of a house that put up such a little spirit house, if asked about his religion, would he answer "Animist"? Or rather "Buddhist"? I am quite sure it would be the latter. 

After all, isn't it Bhuddist monks that consecrate a new house with their spirit house and isn't it monks that trade with lucky charms at temples? 

Buddhism as practiced by the people differs quite a bit from country to country, incorporates elements of animism, ancestral worship or hinduism here and there. And anyway differs somewhat from the "pure teachings".

But that is completely normal and is the case with every major religion. As Christianity in Europe incorporated some pagan rites, so does Christianity in Central  America incorporate other rituals that are reminiscent of things that came before Christianity.

On July 13, 2021 11:31:14 AM GMT+02:00, Mateusz Konieczny ***@***.***> wrote:
>https://taginfo.openstreetmap.org/tags/religion=animist is used but
>quite rarely, documented at
>https://wiki.openstreetmap.org/wiki/Key%3Areligion
>
>Looking at https://en.wikipedia.org/wiki/Animism reveals that topic is
>quite tricky, I need to learn a bit to have some basic knowledge about
>this topic.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/streetcomplete/StreetComplete/issues/3063#issuecomment-878931813

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by westnordost** [comment]
So I'd rather see this as `denomination=thai_buddhism` or similar, though in Thailand this information is probably not useful as 99.9% places that are Buddhist are Thai Bhuddist

**Comment by mishari** [comment]
@westnordost I did a survey in Thai groups to ask which religion they would identify spirit houses would belong to and 70% responded "local religion" which translates to animism. This is the general consensus in the Thai community forum as well. https://forum.openstreetmap.org/viewtopic.php?id=73213

**Comment by westnordost** [comment]
Cool, thanks for starting a discussion there. Note though that most people active on the forum are farangs. I'll also try to get another opinion from a few acquaintances.

Regarding `religion=animism`, additionally to what I wrote, I am quite wary about adding this:
1. I wouldn't call animism is a religion. And if it was, it is the question if animism in America should be tagged the same as Animism in South East Asia or elsewhere
2. The number of shrines mapped so far, even in Bangkok, is very low, considering in realitity, they are around every corner , see http://overpass-turbo.eu/s/19xz . In the given Overpass link, nearly all of those mapped so far already include the information that they are sprit houses (in description, not `religion`).
3. And this is what I thought: Spirit houses are small enough that they are usually not really visible on aerial imagery. A survey is required. And if this already recorded via a survey, it looks like the surveyors so far already considered right away to mark them as spirit houses in one way or another. So, no real information is gained when religion is added to these nodes.

Maybe StreetComplete should instead not ask for the religion of shrines that have a `description` or `image` set?
Because, is it actually easily answerable if a shrine is dedicated to some hindu god, ancestors or "the spirit of the house"? F.e. I wouldn't be able to tell with this one https://images.mapillary.com/GPXHzoJdNQA0AeZxSQ4E1w/thumb-2048.jpg - would you?

**Comment by nitinatsangsit** [comment]
Although most Thais call themselves Buddhist, I don't think that all of their rituals should be classified as Buddhism, folk Buddhism, or something similar. Most Buddhist monks won't do anything at the spirit house, but a Brahmin (Hindu priest) will. According to some scholars, Thai belief was a mixture of Phut, Phram, and Phi (Buddhism, Hinduism, and Animism).

Although a mixture is common, we can distinguish the main belief at each place of worship. To compare, in Japan we have `religion=buddhist` and `religion=shinto`, while in China we have `religion=buddhist`, `religion=taoist`, `religion=chinese_folk`, and `religion=confucian`. In those two countries, we often see a mixture of beliefs too. In Thailand, thus, using of `religion=buddhist`, `religion=hinduism`, and `religion=animist` makes sense. If we wish to distinguish them from somewhere else, adding a `denomination=*` to them is a better way.

> Because, is it actually easily answerable if a shrine is dedicated to some hindu god, ancestors or "the spirit of the house"? F.e. I wouldn't be able to tell with this one https://images.mapillary.com/GPXHzoJdNQA0AeZxSQ4E1w/thumb-2048.jpg - would you?

This is a shrine of Brahma, a hindu god, so `religion=hindu` is preferable. IMO, adding a `religion=*` to a `wayside_shrine` is at least better than doing nothing.

**Comment by stephankn** [comment]
Look at the large list of "others" in the religion key. So the `religion=*` key is actively in use for spiritual beliefs which are not necessarily classified as religion.

https://wiki.openstreetmap.org/wiki/Key:religion

**Comment by matkoniecz** [comment]
Still `religion=animism` feels like putting  `religion=polytheism`

Even if used widely, `religion=polytheism` or `religion=monotheism` is not something that would be promoted by responsible editing software.

**Comment by westnordost** [comment]
Right, good point, @stephankn , what counts is how the tag `religion` is used, not what would be the definition of a religion.

If animism were to be added, what would be a reasonable icon though? Maybe something with eyes, to symbolize the belief that spirits inhere in things, thus are aware, i.e. see?

**Comment by stephankn** [comment]
The spirit house should come as a preset with a fixed tagging. So no need to select the religion. See google image search for "Thai Spirit House" to get an impression about the typical look.
A line-drawing might look like this non-free: https://www.shutterstock.com/image-vector/wooden-spirit-house-cartoon-vector-illustration-563242879

**Comment by westnordost** [comment]
This Ticket is about the "what religion does this shrine have?" quest that is asked for all shrines in the world that have none tagged.

**Comment by westnordost** [comment]
I.e. your comment is not applicable

**Comment by stephankn** [comment]
Ah, I get the context. Maybe the quest is not fully matching here. So instead of asking for a religion, the right question would be whether that wayside shrine is a Thai Spirit House. And if yes, you would apply the tagging. If not, you could ask for other details.
But probably the quest does not work multi-staged like this, as you are running the same quest also on the wayside_shrine in other parts, right?

Can you make quests location aware? So that a historic=wayside_shrine without religion tag in Thailand results in other questions/order of questions than the same missing tag in for example Germany? In Thailand, they are most probably Spirit houses. So you could ask for this first. In Germany probably something religion=christian. And in that case you might be interested in knowing denomination as well.

**Comment by Helium314** [comment]
Maybe there could be an answer "It's a spirit house", similiar to "It's a picnic table" for the bench backrest quest?

**Comment by westnordost** [comment]
Even though possible, I'd not want to make this that complicated. Basically, it comes down to this question:

**What would a Thai answer to the question _"What is the religion of this shrine?"_ when asked for a spirit house?**
(or better: What would anyone answer? - if possible)

If it is "Animist", then we need to add "Animist" as a religion.

---

In the meantime, I asked someone who graduated in Thai studies. She said that it is a difficult topic as on one hand, also monks participate in things like the inauguration of spirit houses, administer those colorful ribbons around trees, the tattoos and lucky charms but at the same time, she was quite sure that at least the higher ups in the church hierarchy would say that these practices are not at all part of Buddhism. 

She mentioned that exorcism for example was also a somewhat pagan practice and still is somehow attributed to Christianity. Nowadays, at least in Europe, Christians would say that this belief is superstition, but does that change the fact that it was practiced by Christian priests in the past (and elsewhere probably still), i.e. was/is part of the religion? Would a blessing given by a Christian priest, or a crucifix on the door, to ward off demons be considered Animist?

Not so long ago, it was common to put grotesque faces on the facade of buildings in Europe, citation:

> To ward off evil, builders in Europe had grimacing heads of animals, people or fabulous monsters made of stone or wood attached to doors. According to popular belief, the head of envy should ward off calamity and evil (apotropaic act). The evil forces and spirits should not envy the people in the buildings covered with them and should not turn them against the residents. 

\- _[Neidkopf (German Wikipedia)](https://de.wikipedia.org/wiki/Neidkopf)_

In English, also known as Gargoyles and those can be found on churches too, right?

In any case, she said, that it will very likely depend on who is asked. People that somewhat think that such practices are superstition would probably answer that it is an animist practice. But the others, maybe not. She promised me that she would ask a few of her Thai friends - which are all academics though.

**Comment by matkoniecz** [comment]
> She mentioned that exorcism for example was also a somewhat pagan practice and still is somehow attributed to Christianity. Nowadays, at least in Europe, Christians would say that this belief is superstition, but does that change the fact that it was practiced by Christian priests in the past (and elsewhere probably still), i.e. was/is part of the religion? Would a blessing given by a Christian priest, or a crucifix on the door, to ward off demons be considered Animist?

Actually, demons are considered as existing in Catholicism. From https://en.wikipedia.org/wiki/Catechism_of_the_Catholic_Church (official summary of catholic doctrine), part 1673

> 1673 When the Church asks publicly and authoritatively in the name of Jesus Christ that a person or object be protected against the power of the Evil One and withdrawn from his dominion, it is called exorcism. Jesus performed exorcisms and from him the Church has received the power and office of exorcizing.176 In a simple form, exorcism is performed at the celebration of Baptism. the solemn exorcism, called "a major exorcism," can be performed only by a priest and with the permission of the bishop. the priest must proceed with prudence, strictly observing the rules established by the Church. Exorcism is directed at the expulsion of demons or to the liberation from demonic possession through the spiritual authority which Jesus entrusted to his Church. Illness, especially psychological illness, is a very different matter; treating this is the concern of medical science. Therefore, before an exorcism is performed, it is important to ascertain that one is dealing with the presence of the Evil One, and not an illness.177

https://www.vatican.va/archive/ENG0015/__P58.HTM

**Comment by westnordost** [comment]
Ok, interesting. Well, I am not an expert on Christianity. Though I am sure other examples could be found where the Christian church took on pagan (animist, spiritual) practices that existed before or were (before) not really part of Christianity. Also, maybe the Christian church has been more adamant in either incorporating a belief/practice or labelling it as heathen and persecuting it in effect than it is the case in non-monotheistic religions.

**Comment by stephankn** [comment]
Seems we are struggling here with the key "religion", which is according to the wiki already in use for spiritual beliefs which are not really considered a religion.

A spirit house matches very well the definition of a wayside shrine. and as these are in OSM then sub-classified by the religion key, this will then probably the right one to use.

Wikipedia gives some hints. Compare the description of the different languages, as it hints what it is about:
https://en.wikipedia.org/wiki/Spirit_house
https://de.wikipedia.org/wiki/San_Phra_Phum
https://fr.wikipedia.org/wiki/Maison_des_esprits

They all agree that these are from animist beliefs, which are tolerated by Buddhism and coexists in south-east asia.
This led to the consent that religion=animist fits quite well.

They are not Buddhist, even with a larger part of the population having one.
Our house in Chiang Mai doesn't. And setting one up would require a ceremony held by a "specialist". Certainly not by Thai Monks.,

**Comment by nitinatsangsit** [comment]
We can assume that a "spirit house" is an animist shrine.
However, things are a little more difficult. Nowadays, some large buildings or projects are constructing a Brahma shrine (with an inauguration by a Brahmin) instead of a spirit house, or both, with not much different appearance. This custom was inspired by an Erawan Shrine.
For an example, see [https://en.wikipedia.org/wiki/Spirit_house#/media/File:Spirit_houses..JPG](url) . The left one is a spirit house, and the right one is a Brahma shrine. Although they are look alike, I believe we can tell them quite simply. A Brahma shrine must have a statue of Brahma (the Hindu god with 4 faces and 8 hands). Meanwhile, elsewhere, we can see a Buddha shrine, a shrine with a Buddha image. It is not difficult to distinguish them then tag the religion, if not, you can leave it empty.

**Comment by westnordost** [comment]
Ok, so any ideas for an icon? Or just no icon at all?

**Comment by nitinatsangsit** [comment]
I have no idea about an icon. General icon for wayside_shrine might be ok.
