### ISSUE TITLE
StreetComplete 33.1 crashes on start

### ISSUE THREAD

**Issue by FloEdelmann** [streetcomplete/StreetComplete#3070]
* LineageOS 17.1 (Android 10)
* Google Play Store version (via Aurora Store)
* app version 33.0 worked without crash
* logcat via *Logcat Reader* app, filtered by keyword "streetcomplete": ![logcat_07-15-2021_21-56-55.txt](https://github.com/streetcomplete/StreetComplete/files/6825929/logcat_07-15-2021_21-56-55.txt)

**Comment by westnordost** [comment]
Uff, no way... :-(

Though in the google play console, I can't see this crash even though 5000+ users updated to this version already.

**Comment by westnordost** [comment]
So the error means that the app cannot find the resource `ic_star_white_shadow_32dp`, that's the star shown in the upper left corner. I expect this error to only happen if this resource is really not available in the APK.

I suggest you get the app through Google Play store and see if this solves your issue, not sure what the Aurora Store does.

**Comment by FloEdelmann** [comment]
Aurora Store is an open-source reverse-engineered Google Play Store app. You can log into an anonymous or your own Google account and download and install apps from the Play Store.

I just triggered a manual re-download and re-installation of the same app version, and that fixed the issue. It really seems like a one-time issue.

**Comment by westnordost** [comment]
Gotta love those heisenbugs

**Comment by smichel17** [comment]
I have encountered a similar bug with Aurora Store, for a different app. In that case, it had to do with one of Aurora Store's.. *checks* ..**four** methods of installing apks (session installer, native installer, root installer, and aurora services). I believe it was not handling split apk bundles, or whatever Google's new format is, well; switching to a different install method fixed it in my case. I suspect it was the same bug because once I installed the app via the other method (native installer), updates worked fine with the original method (session installer).

(Actually it happened twice, once with Snapchat and once with Lexulous. For the former, I just reverted to an old version that I still had the apk lying around got and stayed there for about a year. For the latter, I finally diagnosed and found it was missing ndk components. Ended up suspecting Aurora Store somehow, tried the other method; when it worked, I dod the same for Snapchat and that worked too).
