### ISSUE TITLE
Ask if certain highways are informal or not

### ISSUE THREAD

**Issue by vehrmann** [streetcomplete/StreetComplete#3071]
### General
Affected tag(s) to be modified/added: [informal](https://wiki.openstreetmap.org/wiki/Key:informal)
Question asked: **Is this an informal way?**

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/wiki/Adding-new-Quests-to-StreetComplete):
- [ ] 🚧 To be added tag is established and has a useful purpose
`informal=yes` is established (72873 at [taginfo](https://taginfo.openstreetmap.org/tags/informal=yes)), while `informal=no` not really (564 at [taginfo](https://taginfo.openstreetmap.org/tags/informal=no)). On the other hand, for many highways it is simply not obvious without survey if they are `informal=no` and should therefore be categorized in that regard.
Useful purposes: e.g. routing esp. during bad weather; analyzing need of street improvement and telling e.g. local administration
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
`informal=yes` and `informal=no`
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary
- [ ] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
I guess a huge amount will be `informal=no`, but the value of the few with `informal=yes` is quite huge I think. A bit like the cycle lane quest.
The quest should only be asked for highways which are potentially informal. Therefore all manmade surfaces can be filtered out. Here my first approach, this could be refined more if someone has a good idea: [overpass-query](https://overpass-turbo.eu/s/19u5)
It is important that only highways with a surface-tag are considered.

- [x] 🕓 Applies to a reasonable number of map data (Worth the effort)

### Ideas for implementation

**Element selection:**
See linked overpass query above for a first idea

**Proposed UI:**
Here a first sketch for an icon (the small black dots are supposed to be shoe prints)
![Sketch for an icon](https://user-images.githubusercontent.com/60914642/125966116-23290772-f91c-41d4-8432-2cd2fb5cb677.png)

**Comment by 10992-osm** [comment]
How does one tell whether a highway is `informal` or not?  [The wiki](https://wiki.openstreetmap.org/wiki/Key:informal "Key:informal — OpenStreetMap Wiki") says it's whether a path is 'official' or not, whether it is maintained.  Is it always possible to tell that?  It seems obvious to me when a path is not `informal`, i.e. when it is paved, signed, where furniture is placed to take account of it's presence (gates, stiles and similar), but is it always possible to tell otherwise?  Depending on the environment, `informal` paths can look very similar (if not the same) as any other.

I'm just trying to think how I decide if a path is `informal` or not.

**Signs of `informal`ity**
- Path is not paved (particularly in an area where most paths are paved)
- Paths goes through a fence where there is no gate/stile, or through a narrow gap in a fence
- Path is obviously a shortcut (for example, it forms a triangle with tow paths that are not `informal`)
- Path goes on odd terrain (for example, up a very steep bank)
- Signs prohibiting all access to an area, yet the path exists (obviously appropriate access tagging should be in place in this situation)
- As an extension of the above, paths generally in places they should or ought not be.
- Path is not wide, or is overgrown (this is not always applicable, particularly with Rights of Way, is even if these are overgrown, the path exists, or at least the right to use it)
- Path does not go to or from anywhere "important".

**Signs that something's not `informal`**
- Path is paved
- Fences, stiles, gates, signs or other [street furniture](https://en.wikipedia.org/wiki/Street_furniture "Street furniture — Wikipedia") seem to take account of the path's presence in their layout (or for signs, the path is signed)
- Path is recorded on an official map (obviously not relevant for StreetComplete, and may not be usable in all cases for OpenStreetMap)

**Comment by mnalis** [comment]
Nicely made suggestion with elaborated points (good work!), but I don't think it would work. 
I've tried to make the query even more restrictive: https://overpass-turbo.eu/s/19uY yet it still:

- gives many results in my neighborhood where I'm not sure how to answer
- I don't think is possible to filter out @10992-osm "Signs that something's not informal" (except the first one - `surface`)
- I don't fell too good to spam the map with too many `informal=no`. While there are good use cases to record non-existence of features (like cycleways), I do not feel this is the case here (I can see the need to very rarely add `informal=no` manually, for example to indicate some path is really an official way even if it is in bad repair  / looks abandoned, but "leave note" is good enough for those very rare cases; I'd definitely **avoid putting it on every unpaved path** that is made on purpose!)
- I'm not so convinced about _"value of the few with informal=yes is quite huge"_. When I add manually `informal=yes` (which is quite rare), it is to more to notify other mappers "please do not delete this way even if its visibility is low and it looks abandoned, as it is very useful". @vehrmann mentions following uses:
    - _"routing esp. during bad weather;"_  - can you elaborate? How would marking path as informal (or not) _hugely_ help with routing in such cases? IMHO if it is about usability for routing due to quality, it should be determined by tags that determine material status/quality like `surface`, `track_type`, `smoothness` etc. and not it's legal/historical status (_"well, yes, there is a track that goes there, but we never planned for it but people made it themselves"_)
    - _"analyzing need of street improvement and telling e.g. local administration"_ - this I agree is the quite useful task, but not really something that should be done in OSM. One should use either app provided by local administration (like https://www.fixmystreet.com/ or similar) to report such issues to them, or leave a [local note for yourself](https://github.com/streetcomplete/StreetComplete/issues/1992) and later contact your administation via e-mail (or whatever they use) with your suggestions on case-by-case basis. Marking ton of ways as `informal=yes` and then calling local administration with "_hey, look at this few thousand informal ways I've marked on OSM as unofficially made - please put some gravel/asphalt on them and add signs/maps to make them official"_ is not something I think would work.

**Comment by FloEdelmann** [comment]
I think it could safely (as in "not spammy") be asked for ways with e.g.  `surface=grass` or `surface=dirt` that run (mostly) on a `landuse=meadow` area. There are likely similar combinations.

However, that's likely relatively difficult to implement, so I doubt that it's worth the effort. Also, I doubt the usefulness of the tag, as routers likely rather use `surface`, `track_type`, `smoothness` etc. tags directly, like @mnalis said.

**Comment by 10992-osm** [comment]
I suppose that `informal=yes` could be used by some routers/renderers as a proxy for `access=*`, since `informal` paths generally won't have any legal right of access, and are probably at best permissive, but often will be technically private or forbidden.  This doesn't make the quest any easier, and I'm not sure if `informal=yes` is currently used in that way.

**Comment by vehrmann** [comment]
Thanks for your thoughts. I guess you are all right that is quite difficult to tell if a path _is_ actually informal and therefore is rather a topic for expert mappers.
I'll close the issue then.
