### ISSUE TITLE
Allow fractional building levels

### ISSUE THREAD

**Issue by infthi** [streetcomplete/StreetComplete#3092]
**Use case**
Buildings with cellar that is half above ground and half below ground.

**Proposed Solution**
Allow the building levels quest dialog to accept fractional values - as of now, it only accepts non-negative integers
There is a bunch of buildings with `building:levels`=1.5, 2.5, etc on [taginfo](https://taginfo.openstreetmap.org/keys/building:levels#values)  so this seems like a de-facto accepted scheme.

**Comment by westnordost** [comment]
- Fractional building levels are not documented, neither on the `building:levels` page nor on the simple 3d buildings page. It is unclear what they are supposed to mean, there is no such thing as half-a-storey.
- Also, less than 0.25% of building levels tagged are fractions, I wouldn't call this "de-facto"

**Comment by infthi** [comment]
> Fractional building levels are not documented
Nor does the documentation state that only integers are allowed; it vaguely says "number". Also "levels that are part-way underground do count" - with a terrible example that does not cover all the possibilities.

> there is no such thing as half-a-storey
here is an example of what I consider "half-a-storey" on Google street view: [link](https://www.google.com/maps/@53.5024101,-2.1806824,3a,75y,209.73h,103.59t/data=!3m6!1e1!3m4!1sHXmlOPkxRSLy0Ghv1g7ySg!2e0!7i16384!8i8192). The cellar is half above ground, half below ground. Or, for example, I have a bunch of such buildings in my local area (including a one-level sports hall half below ground ¯\\_(ツ)_\/¯).

>  Also, less than 0.25% of building levels tagged are fractions, I wouldn't call this "de-facto"
I mean those are still tens of thousands of buildings from many[citation needed] users all around the world (according to overpass-turbo) - so this is not a cryptic long tail either. There are much fewer buildings with >=100 levels - but this won't be a reason to introduce a hard limit of two-digit level number?

**Comment by smichel17** [comment]
I've actually been meaning to start a discussion asking about how to tag this sort of thing (I think?), like https://westnordost.de/p/34246.jpg ([via](https://www.openstreetmap.org/note/2595166)).

**Comment by westnordost** [comment]
Maybe that is what fractional values mean, maybe not. 

This is the problem with things that were never documented. 

In German, this is called "Hochparterre", the English translation is apparently "raised ground floor" (makes sense?). In any case, as such interpretation was never documented, we have to assume that many many `building:level=*` that are **not** fractions are actually buildings with a  _"raised ground floor"_ after all but fractions were not used to represent that. 

Because surely more than 0.25% of buildings have a raised ground floor, right? I'd say, most off-the-shelf apartment buildings have a raised ground floor (i.e. first apartment door in staircase comes after a few steps up)

If at this point, after millions of building levels have been tagged, the definition of `building:level` in the wiki changed to explicitly allow fractional buliding levels (and define that fractional should mean "raised ground floor"), this would then at one stroke make many many (probably in the millions) current taggings of `building:levels` wrong. Wrong, as in, that many buildings that currently have f.e. `building:levels=4` should actually have `building:levels=4.5` according to the redefined wiki definition.

Half-a-storeys don't exist (maybe a coal cellar?). If a building with 4 storeys has a raised ground floor, it means that the basement floor is simply a bit further up, i.e. sticks out from the ground. If we used `building:levels=4.5` to denote that, what's `building:levels:underground` then, `0.5` or what? That would be a really weird definition.

I think that ultimatively the wish to use fractional building levels is "tagging for the renderer": Buildings with a raised ground floor are about half a storey higher than buildings with the same amount of floors that don't have a raised ground floor and (some) people that tag `building:levels` would really like if this showed up (correctly) on maps that display 3D buildings.

The only good way I can think of would be to use a separate tag to define if a building has a raised ground floor (or/and by how much).

**Comment by infthi** [comment]
Problem is - this is confusing. "How should I tag this building? This is more than 1 level, but this is definitely not 2 full levels. looks like 1.5 to me - what do I enter? Oh no, only whole numbers are allowed. Now I have to choose between 1 and 2". Someone will choose 1, someone will choose 2. In any case this contradicts the `Easy answer: Users are out and about and impatient. A quick, straightforward and clear answer must be possible` rule for quests.

Another solution I may suggest is to add a new menu item to the "Other items" menu - e.g. something that says "Something in between" and files a note in a specific format - so that in the future it'd be possible to analyze whether this problem exists in the wild or just in my head.

**Comment by smichel17** [comment]
> new menu item … files a note in a specific format

Or, if this is not desirable, it could work like the Building Type Quest's option, "It has multiple purposes", which opens a dialog explaining that you should pick the primary one.

**Comment by mnalis** [comment]
@infthi sure, it is unclear to me too. I solve it so _"if it looks even a little more than `4`, I map it as `5`"_ (some other people will instead opt for _"if it is not clearly  full `5` stories, I map it as `4`"_, though) 


Problem is, as noted above, that the documentation was unclear from the start. The issue is, even if documentation was improved today and become very explicit (which is not likely: if we allow fractions, how is 5-storey building which has 30% or basement visible above ground be mapped - `5.3`? because it clearly diferent from `5.7` in that other case), it **would not help at all because**:

- all those currently mapped levels should be ignored **forever** <sup>***1**</sup> if we care about precision  (as about 50% of them mapped up to now are incorrect whichever definition you choose, and we have no way of knowing which - so only sane way to fix it is to start over, with a **new tag**), or
- we accept the imprecision that `building:levels` could **always** be `one below` or `one above` the numbers specified in `building:levels`. So, `building:levels=5` actually means _"somewhere between 4 and 6"_

Yes, if is frustrating. One way to work around that (without trying to introduce `building:levels:precise` which would work technically, but would likely result in **"_quick, get the popcorn!"_** reaction on [OSM Tagging mailing list](https://wiki.openstreetmap.org/wiki/Tagging_mailing_list)) is  [height=* ](https://wiki.openstreetmap.org/wiki/Key:height#Height_of_buildings). This is not usable for StreetComplete, though, for obvious reasons.

But @infthi  you do correctly note that this does get kinda afoul of the rule `Easy answer: Users are out and about and impatient. A quick, straightforward and clear answer must be possible`. One might propose to deal with that by disabling this quest by default, thus leaving it up to the users if they want to enable it. (it won't be me, though; even if I don't care much for that data, and I realize it is imprecise, I still map it here and there if there is nothing else better to do)

<sup>***1**</sup> Forever, because all those millions of users who learned previous definition and will never read new definition, will continue to use old definition, so the problem would continue likely forever.

**Comment by rhhsm** [comment]
There are also buildings on a slope which have a floor that is completely underground on one side, and completely above on the other side. I think we have to accept that this quest has an "error margin" of +/- 1 level, so being able to tag fractions of levels is useless.

**Comment by westnordost** [comment]
> There are also buildings on a slope which have a floor that is completely underground on one side, and completely above on the other side.

What counts is the lowest non-basement floor. The illustration provided in the quest form should make that clear, as it shows a building on the roof. 

This is also the rule I follow when deciding in cases I encounter a building with raised-ground-floor and a building with lowered-ground-floor. F.e. this building has 4 levels even though the lowest level is below ground
![aussenansicht_strassenansicht-600x338](https://user-images.githubusercontent.com/4661658/127381163-95d81de9-0ecf-48c8-81ce-88cef8194550.jpg)
and this also
![IMG_4030](https://user-images.githubusercontent.com/4661658/127381565-497eb1dc-ec37-4d71-918f-9f79fc31ba74.jpg)

A basement functionally has a different purpose than a normal building level (=the same as a shed or attic), so I think it makes most sense to make the distinction just there.

**Comment by mnalis** [comment]
How about [this one](https://www.mapillary.com/app/?lat=45.80217884&lng=15.92638533&z=17&pKey=4665591996801605&x=0.38111616809601906&y=0.5806291189130814&zoom=0.4568965517241383) ? The steps lead up to the "raised ground" floor (one with windows), which is really the first (or 0th) floor for residential use; the one visible at the street level (with bars) is actually basement/cellar, even if it is at ground level (and it would make no functional difference if it was built half a meter lower). 

I can see it being counted/mapped both ways... So, yeah, I too don't think we can know exactly what is meant even with whole numbers, much less worry about fractions.

**Comment by matkoniecz** [comment]
https://wiki.openstreetmap.org/wiki/Talk:Key:building:part#re_fractional https://wiki.openstreetmap.org/w/index.php?title=Key:building:part&curid=89059&diff=2180637&oldid=2178423 - fractional building levels just become mentioned at Wiki, though without any clarification (not sure is it related to this ticket)

**Comment by smichel17** [comment]
> What counts is the **lowest non-basement floor**. The illustration provided in the quest form should make that clear, as it shows a building on a slope.

Emphasis mine, let's please get that precise text into the app somehow. It is concise and hugely clarifying for me.

For example, the house I currently live in:

- Is on a slope, similar to the illustration
- Has a half-finished basement (it is split into two rooms).
    - The unfinished part of the basement is mostly below ground (2 small windows near the ceiling, only)
    - The finished part of the basement is mostly above ground, although not *all* the way (there is no door).

I have been unsure how to tag my house for a while. Based on the illustration, I should tag it as 3 levels, since the basement is mostly above-ground. But this just hasn't felt right; I wouldn't describe it as a 3-story house; the basement, while finished, is still a basement.

Knowing that basements should be excluded will make this quest much easier going forward. It is sometimes hard to judge whether the bottom floor of a house on a slope should be counted based on height alone (especially when I am only looking at it from the street), but there are often clues other about whether it is a basement.

**Comment by westnordost** [comment]
Any suggestions?

**Comment by smichel17** [comment]
Maybe change the question text?

- Best: Add to the left side of the box, "regular, non-basement levels (not counting the roof)"
    - I think this would be too long, though. Is "(not counting the roof)" necessary? I would guess it is already communicated by the image (and the separate box for roof levels on the other side).
- Works: Change the question text: "How many non-basement levels does this building have?"

**Comment by infthi** [comment]
> For the purposes of this tag, "ground level" is defined to be the lowest entrance to a building.

What could go wrong with this definition contradicting the main example on that page...

I have three examples here (two are real from my local area, third one is imaginary)
![im3](https://user-images.githubusercontent.com/4579183/127559303-d585552a-ba3f-417a-9409-b13710f24ee9.png)

* A: a one-level sports hall which is half below ground (OK, I lied to you, IRL this is `building:part`, not `building`, so this is not covered by StreetComplete, but `building:levels` works for parts too so the same logic applies). The basketball hoops inside are literally below ground. Is this a ground level? A basement? A 0.5 level building?
* B: a house with only (probably, it's hard to check what's on the other side) entrance through a bridge.  Note that I have no idea whether IRL this house has a fully underground cellar or not but let's assume it does. So I would say this building has `building:levels=2` (this somewhat matches the example on that wiki page) - or is it `building:levels=1` with a level of basement fully above ground according to the "lowest entrance" logic?
* C: an imaginary example of some military complex where buildings are connected with tunnels - and some not having above-ground entrances at all. Is this `building:levels=3` since there are 3 levels starting from the lowest/only entrance to the building? Or is it `building:levels=1`?

I am in dire need of "Falsehoods programmers believe about buildings"

**Comment by westnordost** [comment]
> That's also helpful. Probably best to communicate this by adding door(s) to the image…

Could turn one window into a door...

> regular levels (no basement or roof)

"no basement or roof" sounds odd. It should be "without ... ". Still less clear than "not counting ...". I think your suggestion to change the question is best

**Comment by westnordost** [comment]
> A

SC does not ask for sports hall buildlings how many levels it has. But if it would, I'd say it were "1", because the sports hall itself is not a basement and above ground.

> B

Difficult to say. But I'd say that if the storey below the level with the bridge is used not as a basement, it will certainly have a door (door to the terrace at least). Even if it was a basement, it would probably still have a door. if it is on ground level.

**Comment by westnordost** [comment]
I improved the illustration a bit (see linked commit). Questions (please give me 👍  or 👎 ):

**Comment by westnordost** [comment]
Should the question be changed to "How many **non-basement** levels does this building have?"

May be difficult to translate(?)

**Comment by westnordost** [comment]
Should "regular levels (not counting the roof)" be shortened to "regular levels" to make form less busy?

**Comment by smichel17** [comment]
> May be difficult to translate(?)

"How many levels above the basement does this building have?"
