### ISSUE TITLE
Sticky map scale buttons when value option menu shows

### ISSUE THREAD

**Issue by alexander-mart** [streetcomplete/StreetComplete#3094]
AS-IS:
![image](https://user-images.githubusercontent.com/14993551/126910209-788d6343-f525-4037-bdae-b140bda6e1d6.png)

TO-BE:
![image](https://user-images.githubusercontent.com/14993551/126910206-7d02a23d-7984-45f3-afcf-b571198d88b2.png)

**How to Reproduce**
Open any road surface quest.

**Versions affected**
v33.1

**Comment by westnordost** [comment]
So you want the + / - button to move up, i.e. always be visible also when a form is shown. 

Why do you want that? Also, what if there is not enough space?

**Comment by som89** [comment]
I support the request. Particularly for this kind of quest, it often happens that a too long road segment is selected, so I need to zoom out to see whether the surface I see is relevant for the entire segment, or I should split it.

**Comment by mnalis** [comment]
@som89 Note that there is also "pinching gesture" to zoom in/out as an (already working) alternative; but I do agree that buttons are often easier to use. If there is not enough space to fit them, then they should be dropped, I guess, but otherwise it might be useful if they remained.

**Comment by westnordost** [comment]
I've considered this but opted not to implement this. Reasons:
- it is less easy to do that than it may seem, as the fragment that controls the map and the one that controls the form are completely separate (don't know of each other)
- I find it may look disruptive to move those buttons up, move them around when the user resizes the form and finally make them invisible when they "hit" the compass button
- zooming in further is already possible with one thumb via double-tap on the map, zooming in and out is already possible with the pinch gesture. Why does the +/- button exist at all? Because *while cycling/walking* one may not conveniently have two hands free. When answering quests, the expectation is that the user will (have to) use two hands already. For example, to press "asphalt" and then "OK" on the screenshot provided, it is already necessary to.
