### ISSUE TITLE
Provide answers to batched quests for identical local map items

### ISSUE THREAD

**Issue by j7e** [streetcomplete/StreetComplete#3098]
**Use case**
I currently provide individual quest answers for local map items that have identical characteristics, which can be repetitive (and a tedious experience). For example, a set of local streets share the same surface, pavement and lighting characteristics/configurations, and each street asks the same set of quest questions for them. An alternative example is of a nearby government complex with its own private and uniform car parking around the site, but has been split into multiple car parking quests. There's also the nearby park with interconnected paths, which have multiple, identical quests. 

**Proposed Solution**
Where a group of local map items share identical characteristics and are assigned (or have been split into) individual quests, allow users the ability to select multiple quests to provide the same answer, once. For example, this could be implemented by the user long-pressing a quest marker, perhaps turning it to a highlighted colour to indicate its selection, and then short-pressing other quest markers to select (and highlight) them for batch answering. In this batch selection mode, a button could be displayed which prompts the respective quest answer to select and submit.

**Additional comments**
Whilst this feature might be felt to reduce some of the gamified characteristics of the app by shortcutting interactions, from my perspective I feel that it would be an overall improvement by reducing its repetitive aspects and increasing overall engagement (sustaining interest) and enjoyment (generating a greater sense of progress/achievement by 'clearing' areas).

I understand there could be concerns about the quality of batched answers. The feature could perhaps be limited by, for example, any or all of: requiring users to be logged in to their OSM account; specifying a maximum selection size (e.g. 10 quest markers); or requiring a minimum quest score.

**Comment by matkoniecz** [comment]
The problem is that the feature would be tricky to discover even if existing.

In related news, see #73  #2353 #1303 - is this issue adding something new not covered by existing ones?

Also #2968 

And #2542 #1772 for examples of handling specific quests

**Comment by westnordost** [comment]
I do like the proposed UI - that's how it could work from the UX perspective. However, my concerns about the quality of the batched answers weighs heavier than the promised gain in efficiency and convenience.

Yeah, it could be a feature for err... advanced / trustworthy users. But how to filter? **Certainly** not by quest score. Rather maybe by looking at if the user also uses other (more advanced?) map editors like JOSM or Vespucci, as proof that the user is invested enough in the OpenStreetMap world beyond the "StreetComplete game". However, there is currently no way to find this out easily via an API call or something like that.
So, this is a will not fix for now.

If someone who is able to implement it himself and would like to work on this is reading this. This is how it **could** work:
- get in contact with Pascal Neis and talk about if it would be possible to provide an API for HDYC, what would be the requirements for that
- without an API, a scaper could be written. As a scraper or simply using an API, It could be written in PHP and integrated into https://github.com/streetcomplete/sc-statistics-service/ so that it can be queried by StreetComplete
- the info (that a user is using advanced editors) could also trigger additional achievement(s) that unlock more links that are only interesting for advanced users
- Other more advanced features could also be hidden behind the "JOSM switch"

**Comment by smichel17** [comment]
Thanks for the list @matkoniecz, added to https://github.com/streetcomplete/StreetComplete/discussions/2789#discussioncomment-1083149
