### ISSUE TITLE
Map should also show disused:building=* and abandoned:building=*

### ISSUE THREAD

**Issue by ltog** [streetcomplete/StreetComplete#3103]
**Use case**

Currently, the map won't show buildings tagged as `disused:building=*` or `abandoned:building=*`. Including these buildings would make it easier to navigate around these buildings and get a better correlation between map and real-life surroundings.

**Proposed Solution**

Show these buildings on the map, maybe in a (slightly) different color.

**Comment by matkoniecz** [comment]
Buildings should be tagged with `building=*` - `disused:building=*` or `abandoned:building=*` is a very poor and very rare method that in my opinion does not deserve support.

See also https://github.com/gravitystorm/openstreetmap-carto/issues/4238 https://josm.openstreetmap.de/ticket/19652

**Comment by westnordost** [comment]
And in any way, this is not displayed as a building because jawg doesn't include them in its vector map tiles. @matkoniecz provided the reason why they may not do this.

You are better off with using `building=yes` + abandoned / ruined / disused. I don't recommend `building=ruins`, but even that should render probably.
