### ISSUE TITLE
Building type answer: not listed

### ISSUE THREAD

**Issue by smichel17** [streetcomplete/StreetComplete#3109]
**Use case**

Adding a building type to the list is a commonly-rejected feature request. Usually this is because the building is not common enough. However, even understanding the reasoning, it's still frustrating for me as a mapper to know what kind of building I am looking at but be unable to tag it. Opening a note with "can't say" feels like a kind of hacky workaround, because I *can* say, just not in SC. In the particular case that inspired me to open this issue, the building was a gazebo.

**Proposed Solution**

We can't allow the user to enter the tag value directly because that would require them to understand the tagging schema. However, I think we can add basically the same UX, but create a note instead.

- Add an item in the "other options" menu, "Not listed"
- It opens a dialog with a one-line text box (newlines not allowed)
    - Here, I'd enter "gazebo"
    - Optional: include the full iD preset list in a drop-down menu or similar.
- Submitting creates a note with some unique (searchable) text to the effect of "Building type not one of the StreetComplete options: gazebo"

I think this would be a nice compromise.

- For armchair mappers, this would provide an easy type of note to search for, and enter the correct building type.
    - If this becomes a common enough activity, tooling could be built around it. E.g. a "StreetComplete desktop companion" JOSM plugin.
- For armchair mappers who do NOT want to do other people's busy work (I recall "opening notes for others to solve is bad form"), these notes could be automatically filtered out.
- As a mapper (especially someone who almost only uses SC) I would feel like I I provided the info as precisely as I could.

**Comment by mnalis** [comment]
If we implement full searchable iD list, couldn't we then just automatically use it to **tag the element directly** as `building=gazebo` ? That would be much better then leaving pre-filled note in my opinion (both for armchair mappers who do not like note, as well as the end user who contributed directly and does not need to do postprocessing later in JOSM)

**Comment by smichel17** [comment]
We *could*, but it seems to contradict streetcomplete's design, where the user answers in plain language and SC picks the tag. I actually thought "user does not need to understand tagging schemas" was a rule, but to my surprise, the quest suggestion template is actually, "🐿️ Easily answerable by everyone from the outside but a survey is necessary". So, **if** there are no unintuitive taggings ("Building type X is actually tagged as Y for historical reasons") then I suppose it is not *technically* against any rule. But I still think that kind of feature would be a better fit for a version of [SC for experienced mappers](https://github.com/streetcomplete/StreetComplete/discussions/3003); as a casual mapper myself, I'd feel more comfortable knowing that someone else was going to look over my work and make sure I wasn't applying a bad answer. I know there's some version of "I'd like someone to review this" in iD. Not sure how that works, but maybe SC could do something similar.

Also, at that point I think we'd start running into the same arguments for why SC should not include all options as first-class choices. You'll notice from my edit history that I actually added the iD preset suggestion afterwards, and perhaps I shouldn't have. The point of this suggestion was that it's **different enough** from previous suggestions that the previous arguments against it would not apply.

Aside: I imagined that the user could type a free-form value into the box, too, so in those cases we'd want to leave notes anyway.

**Comment by HolgerJeromin** [comment]
Derailing the discussion:
building=gazebo should be imo building=roof :-)

**Comment by mnalis** [comment]
> We _could_, but it seems to contradict streetcomplete's design, where the user answers in **plain language** and SC picks the **tag**

Well, I thought that's what [iD preset](https://github.com/openstreetmap/id-tagging-schema) _is_? eg. mapping between **technical OSM tag** (eg. `building=gazebo`) with its **human-understandable description** in his/hers language of choice  - which in this case for English (by pure luck) is also `Gazebo`; but it need not be. In [Croatian](https://github.com/openstreetmap/id-tagging-schema/blob/main/dist/translations/hr.json) for example it would be offered as `Sjenica`, in German as `Aussichtspavillon (aussichtspavillon,salettl,offene gartenlaube)`, in Italian as `Gazebo (protezione,tetto,palco,palchetto)` etc.

> So, if there are no unintuitive taggings

Well, that's up for debate... In my opinion, whole `building=*` vs. `building:use=*` is unintuitive, even for the quest as it is currently implemented (eg. when I hear `What kind of building is this?` I personally think of _"what kind of purpose does it serve at the moment"_, instead of _"for what original historical purpose it was built"_, which is what is **actually** being asked/tagged) . But I guess you were thinking more in the lines of _"Is id-tagging-schema of good enough quality / understandable / non-conflicting with itself?"_ It seems reasonably good enough to me.

> You'll notice from my edit history that I actually added the iD preset suggestion afterwards, and perhaps I shouldn't have. The point of this suggestion was that it's different enough from previous suggestions that the previous arguments against it would not apply

Eh, didn't look at history. Sure, if that was the point, then perhaps mentioning iD should have been omitted (or at least link to previous discussion should've been included and described how exactly / in what crucial thing does this suggestion differ). 
I at least don't know all previous rejected issues by heart, so including this information would be helpful.

**Comment by mnalis** [comment]
@HolgerJeromin sure - in the same way as  `building=carport` should've been `building=roof`. (Or even more generally, `building=detached` should've been `building=residential` or at most `building=house` - I mean geospatial data itself tells you if it is detached or not). But we digress.

**Comment by westnordost** [comment]
> Submitting creates a note with some unique (searchable) text to the effect of "Building type not one of the StreetComplete options: gazebo"

It is already searchable. Because the note text includes the text that the user was not able to answer the building quest for way xyz. So theoretically, and practically, users can, and do, just write "police station" for example in the note and that note would be usable - both for tagging it later with another editor and for doing some statistical research on that..

Also, I wrote in another ticket today that the app in principle does not pre-fill notes text because we'd open a whole new can of worms with that (amongst other reasons against that).

**Comment by westnordost** [comment]
Regarding using the iD presets idea, I'd say, currently "meh, no", because:
1. the building names and building definitions don't match 100% between StreetComplete and iD presets, for different reasons, but I'd say that the StreetComplete ones are "better"
2. iD presets also do not have every thinkable building type. So a search in these will also sometimes not turn up anything, which would be a somewhat stupid UI: "Can't find what you are looking for? Just input the name here! ... oh, nothing found... do you want to create a note instead?"
