### ISSUE TITLE
Bollard type: Foldable or removable with key?

### ISSUE THREAD

**Issue by westnordost** [streetcomplete/StreetComplete#3116]
It is unclear how to answer the bollard quest for foldable bollards that are foldable with a key.

![20210803_184143](https://user-images.githubusercontent.com/4661658/128053793-447ed2fc-9b8a-4cce-9555-45ff984e21b2.jpg)

**Comment by westnordost** [comment]
@FloEdelmann

**Comment by FloEdelmann** [comment]
I've also noticed this while surveying. We could solve this similar to the "removable with key" and "removable without key" options that both tag `bollard=removable`:

https://github.com/streetcomplete/StreetComplete/blob/6b86eb09260f06858dd927e56c28939dbfe0961e/app/src/main/java/de/westnordost/streetcomplete/quests/bollard_type/BollardType.kt#L3-L10

So, split the current "foldable" option into:

* "foldable with key" (with a new image that has both the foldable part and the keyhole/lock in detail) which tags `bollard=foldable`
* "foldable without key" (with the current "foldable" image) which also tags `bollard=foldable`

@RubenKelevra what do you think?

**Comment by westnordost** [comment]
Ah, it's actually not a tagging problem then... maybe, why not remove the "with a key" option and just write "removable (with or without key)", same with foldable?

**Comment by RubenKelevra** [comment]
Foldables are always removable with a key. :)

Or have you encountered one which is foldable without a key?

**Comment by RubenKelevra** [comment]
The main issue is actually that bollards removable without key are actually pretty hard to remove by hand. So it takes more time to remove them than those which can be unlocked with a key. :)

**Comment by westnordost** [comment]
Sure, but if whether it requires a key or not doesn't matter for the tagging, then this shouldn't be made a subject for the user.

**Comment by mnalis** [comment]
> Sure, but if whether it requires a key or not doesn't matter for the tagging, then this shouldn't be made a subject for the user.

But if it requires a key, then it **_should_** matter for the tagging - eg. it is implicitly `access=private` (one wishing to pass would have to either own a key, or go find someone ask them to borrow you the key).

**Comment by RubenKelevra** [comment]
Well, the key in this case is not a real key but a utility key. Fire fighters etc have this one to put them down.

**Comment by matkoniecz** [comment]
> it is implicitly access=private

At least `access=private` `bicycle=yes` `foot=yes`

**Comment by RubenKelevra** [comment]
@matkoniecz actually no. You're fine to drive through them with your motorcycle. They only omit traffic that is too wide to pass by.

Only signs disallow specific traffic to pass by law.

So the only thing you can obviously tag is "maximal width" :)

**Comment by westnordost** [comment]
Okay, so is there actually any reason for having two pictures in the quest, one "removable with key" and one "removable without key"? If the reason was to avoid confusion, well, I was confused.

**Comment by Helium314** [comment]
There were some bollards where I didn't answer the quest _because_ I didn't know whether a key is required for removal. If it doesn't go into any tag, I don't want to bother checking for a lock...

**Comment by mnalis** [comment]
> > it is implicitly access=private, as one wishing to pass would have to either own a key, or go find someone and ask them to borrow the key
> 
> At least `access=private` `bicycle=yes` `foot=yes`

`motor_vehicle=private`, then? (still not "perfect", but maybe good enough).

**Comment by Helium314** [comment]
Is `private` correct if it's for emergency services only? That would apply to several locked bollards I found.

**Comment by matkoniecz** [comment]
Only emergency services? Then `private` is rather too wide (I would expect at least people owning flats and their guests to be allowed by `private` - in other words routing can use `private` roads on a final approach)

**Comment by mnalis** [comment]
[Wiki](https://wiki.openstreetmap.org/wiki/Tag:access%3Dprivate) describes it as _**"The feature is not to be used by the general public**"_, and expands on that with:
> Note that access=private records that access is restricted, not whether or not the object is privately owned. Use ownership=private or operator:type=private to record this kind of status. Privately owned road with public access may be tagged like any other road with public access - without access=* tag, or with the explicit access=permissive. 

And [wiki](https://wiki.openstreetmap.org/wiki/Key:access) for `access=*` also notes:
> emergency=* (category: emergency motor vehicles; e.g., ambulance, fire truck, police car). Note that emergency vehicles are generally not restricted by *legal* access rules

which makes sense to me (IMHO fire brigade vehicle would not have any qualms about parking on somebody private lawn if building was on fire, regardless if they had permission from that individual owner or not).

So yes, I would think `motor_vehicle=private` is good enough, as emergency vehicles access is implied as noted above, and `private` does not designate that nearby house residents necessarily have access there, as noted at the top (even if then _often_ might have)

**Comment by westnordost** [comment]
I hid the posts talking about `access=private` because this if off topic - in this quest, the bollard and only the bollard is tagged, not the road "behind" it.

So, my current suggestion would be https://github.com/streetcomplete/StreetComplete/issues/3116#issuecomment-892018168 . Are there any better ideas or counter-arguments?

**Comment by mnalis** [comment]
> I hid the posts talking about access=private because this if off topic - in this quest, the bollard and only the bollard is tagged, not the road "behind" it.

Note that sometimes bollards exists even if roads on both sides of it are publicly accessible (for example to prevent cars making turns where it is unwanted, or using short residential road below apartments as "shortcut" between two larger parallel roads,  thus making unneeded noise to residents, etc), or to delineate public road from public footway (protect pedestrians from cars illegally parking or skidding off the road), etc.

So `access=private` on bollard is **not the same** as `access=private` on a piece of road behind it (although that is admittedly often the case). Instead, `access=*` on bollard regulates **who can cross that point** (eg. remove/fold bollard). For example, it may be legal/possible for non-resident car to be on the _one_ side of the bollard, and it may be legal/possible for the non-resident car to be on the _other_ side of the bollard, but still only car of a resident who has a bollard key may pass **over the bollard** (marked with `bollard=removable` + `motor_vehicle=private`).

---
As for the counter-arguments in defense of `motor_vehicle=private` (if it requires a key), note that bollards are a type of `barrier=*`, thus their main (only?) **function is to restrict access** to certain types of vehicles. 
IMHO, talking about bollards with _"but let's ignore to whom they restrict access to"_ mindset is kind of pointless. Why bother?

As for specific type of bollard, eg. [bollard=*](https://wiki.openstreetmap.org/wiki/Key:bollard) tag which this issues is concerned with, it has basically one purpose - to define **when the access restriction that bollard enforces (by its existence) can be _overridden_**:

- `bollard=fixed` - access restrictions that bollard enforces can **never** be overridden
- `bollard=flexible` - **emergency access vehicles** that need to save lives can drive over it with minimal loss of time / damage. Other users are still restricted in non-extreme situation (although one might well imagine someone risking fine and small vehicle damage while driving over it, if they try to flee the flood situation, for example)
- `bollard=rising` - **sometimes** the restrictions can be removed - but it **needs other tags** mentioned at the wiki to be actually usable (mostly `opening_hours` & `fee`) -- this is separate quest(s) idea (_without extra quests this bollard type is of dubious usefulness too_)
- `bollard=removable` and `bollard=foldable` -- pretty much the **same thing** from usability standpoint. However, like `bollard=rising`, they need extra tags for this tag to be even remotely usable. It is rather low value data to note that access restrictions can **sometimes** be lifted, without providing even coarse indication what are the conditions for that.
   And conditions are much simpler than for `bollard=rising`; in vast majority of cases there are just two:
  - you **need the key** to remove/fold the bollard (making it equivalent of `bollard=fixed` if you don't have a key)
  - you **do not need the key** to remove/fold the bollard (but just need to exit the car shortly, making it a simple inconvenience instead of hard restriction)  
  
  The advantage here is that StreetComplete can very easily (just extra answers for `with/without keys`) provide that info which makes those two bollard values have **much higher value**. (Yes, this could also be accomplished with an extra quest which would ask for every `bollard=removable` and `bolladd=foldable` if it needs the key, but it would unnecessarily put extra load on the mapper - who could have simply answered it in the one quest like it is now, instead of having to answer two quests).

  Of course, it **does not "have to"**, as @westnordost notes in his comment. But then it is probably time to ask the question _"is this quest about bollard type actually useful? What utility does it provide to some data consumer? How does it benefit some user to know some tiny implementation detail, like is bollard foldable instead of removable, if they **don't even know** if it requires a key to perform that function?"_

**Comment by westnordost** [comment]
Yes, it is useful for emergency services, as they have a key to remove removable and foldable bollards and can drive over flexible ones.

**Comment by mnalis** [comment]
> Well, the key in this case is not a real key but a utility key. Fire fighters etc have this one to put them down.

@RubenKelevra hmmm interesting, but is it? What about [these](https://neutrinometali.hr/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/p/a/parkirn_stup_za_rezervaciju.jpg) or [these](https://pravimajstor.hr/site/_profiles/424/katalog/7/1.jpg)?

Those are much more common here in Croatia, and they do have a custom key (which I'm actually dubious emergency vehicle drivers have a "master" key for). Not at all like for example fire_hydrant utility keys you seem to talk about. 

Wiki for [bollard=removable](https://wiki.openstreetmap.org/wiki/Key:bollard) does actually say _"A bollard which can be pulled out of the ground and removed from its location to allow access, often **only by the person with the key**. Normally in place, and not generally passable. "_

So we may have definition problem here; what is actually meant by `bollard=removable` at all? The one only firefighters can remove, or the one only the owner (and others with copy of key) can remove?

**Comment by RubenKelevra** [comment]
Well removeable means you don't need any tools etc. so you can basically just pull it straight out of the ground. But they get mud/sand/stones wedged in at times, so it CAN be hard to remove.

On the other hand those with general keys the emergency crew has (triangle for example) are extremely quick to remove, since they are not actually in  the ground but only have a hook which hold them.

The ones with private keys are not allowed on public streets here AFAIK. So they might get installed on private properties, but in this case I would consider them as fixed.

A fire/rescue crew can't rely on an owner to have the private key ready. They would just remove it with a grinder.

**Comment by westnordost** [comment]
As no suggestions have been made, I will replace the selections "removable without key" and "removable with key" with "removable (with or without key)" and add "with or without key" to the foldable selection too.
