### ISSUE TITLE
Not possible to specified "unpainted" for just one side of the number of lanes quest

### ISSUE THREAD

**Issue by letypequividelespoubelles** [streetcomplete/StreetComplete#3138]
For the "number of lanes" quest, when we go to "different number of lanes dependinf of the side" it's not possible to say "unspecified" for any lane.  

Imho, it should be possible to say that one side has n lanes (n=1..8) and the other side is unmarked. This is the case for [this way](https://www.openstreetmap.org/way/611974684) for exemple, where it should be n=1 for the south side and unpainted for the north side..

**Versions affected**
v33.2

Thanks all for maintaning SC and OSM.

EDit : put the right way

**Comment by matkoniecz** [comment]
Do you have photo of such case? It would be very useful when documenting this on OSM Wiki. Even if it would be left for "create a note and tag manually" worflow, as this is a really rare situation.

**Comment by letypequividelespoubelles** [comment]
I don't have a photo from the ground (didn't thought of it when I was on the place), but the aerial imagery of the way given as an exemple in my first post is rather good. The north side is unpainted even though usually two cars are going side by side because of the large width. The south side is painted for only one car.

**Comment by peternewman** [comment]
Given it's just been deleted, if anyone wants the location it's here: https://www.openstreetmap.org/changeset/109361431

**Comment by westnordost** [comment]
Anyway, there is no tagging for that. So in this case, I'd say, it is not solvable in STreetComplete (or OpenStreetMap) for that matter. And I think this won't change, because it is a really rare situation.

Users confused by this should leave a note.

What I would do if the usage of that stretch of way is really that there are two cars next to each other on one side, just pretend that it is marked and specify 2 lanes for that one side.
