### ISSUE TITLE
ask about step_count at barrier=stile stile=stepover/ladder

### ISSUE THREAD

**Issue by matkoniecz** [streetcomplete/StreetComplete#3141]
### General
Affected tag(s) to be modified/added: [](https://wiki.openstreetmap.org/wiki/Key:step_count)
Question asked: **How many steps are at the side of this stile? If step count differs on each side, give higher number**

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/wiki/Adding-new-Quests-to-StreetComplete)):
- [x] 🚧 To be added tag is established and has a useful purpose - as discussed at talk-gb and OSM Wiki it is useful for accessibility. Especially for finding hiking routes good for older people who are still mobile, hiking but such steps may be a serious barrier them.
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary
- [x] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of map data (Worth the effort)

### Ideas for implementation

**Element selection:** 
`barrier=stile` `stile=stepover`

**Metadata needed:** No

**Proposed UI:** Reuse one from existing step count quest

**Comment by matkoniecz** [comment]
Pinging @10992-osm as a stile expert :)

**Comment by 10992-osm** [comment]
That seems a good idea for a quest.  I think it would also be useful for `stile=ladder`, as well as `stile=stepover`.

I think the question could better be phrased as

>How many steps does this stile have? If the step count differs on each side, give the higher number.

You could also name the type of stile in the question ("…steps does this step-over stile…" and "…steps does this ladder stile…").

I'm trying to remember what the UI for the step count quest is, but it might be useful to have stile-specific graphics, perhaps showing the profile of a stile with the text box.
This sort of thing:
![Mock-up showing a step-over and ladder stile in profile with a text box and a question about how many steps the stile has.](https://user-images.githubusercontent.com/83511672/128776632-e728f7c6-bb71-4700-b22f-9de25bb1e1e1.png)
I'm not really happy about how the step-over stile looks in my mock-up, because from above, it normally looks more like this:
![Image showing a bird's-eye view of a step-over stile with two steps, arranged like an X](https://user-images.githubusercontent.com/83511672/128776088-62b9b938-0aa2-472d-8742-ddad93f9bfb6.png)
My mock-ups are of course missing the fence/wall that would normally be present.  Also, in a similar vein to #2991, for stone step-over quests, it might be useful to have different imagery:
![Mock-up showing a stone step-over stile](https://user-images.githubusercontent.com/83511672/128777275-c263bb7e-5656-4b77-a0fd-8acf5cdd0185.png)
Again, bad graphics, but you get the idea.  The lighter coloured bits are supposed to be the steps sticking out.

I think stepover stiles (at least the wooden ones) tend to just be two steps on each side, though there are exceptions, but fences tend to be a fairly standard height ([this article in Farmers' Weekly]() suggests that cattle fences need a post that sticks ~115cm out of the ground).

Also, I'm not sure if they're any use, but I found some stile design guidelines (though I'm sure there are plenty of stiles that don't follow these):
- [Standard wood stile](https://www.durham.gov.uk/media/4630/Standard-Stiles/pdf/StileStandard.pdf)
- [Alternative wood stile](https://www.durham.gov.uk/media/4629/Alternative-Stile/pdf/Alternative.pdf)
- [Stile over wire fence](https://www.durham.gov.uk/media/4631/Stiles-Over-Wire/pdf/StileOverWire.pdf)
- [Stiles for drystone walls](https://www.durham.gov.uk/media/4632/Stone-Wall-Stile/pdf/StileStonewall.pdf)

**Comment by matkoniecz** [comment]
>  I think it would also be useful for stile=ladder

I was thinking about it but not 100% sure :)

**Comment by peternewman** [comment]
The "if the step count differs" is definitely required, I found one ladder style which was essentially just a ladder, with the ground level at wall level on one side!

Also another :+1: for asking for ladder stiles.
