### ISSUE TITLE
Allow to change shop type when answering for name of a shop

### ISSUE THREAD

**Issue by arrival-spring** [streetcomplete/StreetComplete#3150]
I'm not sure if this is easily possible, but when you are asked for the name of something and something else is there instead your only option is to leave a note.

e.g. What is the name of this place (butcher)?
I want to say that it's not a butcher, it's a flower shop now but can't do that all from the app

Can the `isReplaceShopEnabled` simply be enabled on that quest only when the item is a shop?

**Comment by westnordost** [comment]
> Can the isReplaceShopEnabled simply be enabled on that quest only when the item is a shop?

This is currently not possible, no.

Also, if the name is not known, it is hard to identify a shop, **especially** if it has been replaced by another.

If you can't see a butcher but you see a flower shop there, it doesn't mean that on that node, the flower shop should be added. Because maybe the flower shop is already mapped, but just a few meters to the left. This is why in such situations, it is better if a note is created, best with a photo.

So, the current behavior is quite deliberate and not only because the name quest is also asked for non-shops.

**Comment by arrival-spring** [comment]
Fair enough, although surely the same could be said of the other situations in which you can change what's there?
e.g. when answering opening hours: "It does not exist"

**Comment by westnordost** [comment]
Yes but less so, because at least the name (of the old shop) is displayed when the quest is asked.

**Comment by arrival-spring** [comment]
Good reasons for it not being enabled, closing
