### ISSUE TITLE
Improve power pole material quest with man_made utility poles

### ISSUE THREAD

**Issue by flacombe** [streetcomplete/StreetComplete#3185]
StreetComplete already has a quest to encourage people to look for power=pole's material.
The point here is to complete this existing quest.

### General
Affected tag(s) to be modified/added: [man_made=utility_pole](https://wiki.openstreetmap.org/wiki/Tag:man_made%3Dutility_pole)

This tag was recently reviewed and approved.

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/wiki/Adding-new-Quests-to-StreetComplete)):
- [X] 🚧 To be added tag is established and has a useful purpose
- [X] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [X] 🐿️ Easily answerable by everyone from the outside but a survey is necessary
- [X] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
- [X] 🕓 Applies to a reasonable number of map data (Worth the effort)

### Ideas for implementation

**Element selection: 
* power=pole
* man_made=utility_pole

It may be necessary to add a possibility for composite poles replacing wooden ones nowadays.

**Comment by peternewman** [comment]
`power=pole` was introduced way before a more general solution appeared and it's too late to move it toward newer `man_made=utility_pole`.
`power=pole` should be `man_made=utility_pole + utility=power`.

_Originally posted by @flacombe in https://github.com/streetcomplete/StreetComplete/issues/3169#issuecomment-899875054_

So adding that to the existing quest is just another way of tagging the same type of node as we're already querying.

Although @flacombe 's reasoning in #187 and #3169 seemed fairly strong for covering all utility poles to me.

**Comment by matkoniecz** [comment]
Do we need new text and new images? Current one describe it as a power pole, and whole point of `man_made=utility_pole` is to cover non-power poles.

**Comment by westnordost** [comment]
I think it can be the same quest. Maybe the wording needs to be changed.

**Comment by flacombe** [comment]
I don't think images should be changed and yes it's fine to improve existing quest.

It will only require the add material=composite option.
I'll look for an appropriate picture

**Comment by westnordost** [comment]
What is composite? How can it be told apart from other materials?

**Comment by matkoniecz** [comment]
Personally, on such question and images for something that is not a power pole I would open a note.

But my tendency to open notes on all spotted invalid OSM data (or likely to be invalid) is not usual and I am a huge, huge outlier as far as OSM notes go.

![screen](https://user-images.githubusercontent.com/899988/130090253-ee546564-e341-447e-b2c9-c4309983e606.png)

**Comment by peternewman** [comment]
> Do we need new text and new images? Current one describe it as a power pole, and whole point of `man_made=utility_pole` is to cover non-power poles.

If we just added `man_made=utility_pole + utility=power` for now, then we don't need any changes (aside from composite, but that's also missing for the current `power=pole` quest).

But you may want images without the horizontal bars on for e.g. telephone poles.

> I think it can be the same quest. Maybe the wording needs to be changed.

Yeah makes sense to me, "What is the material of this utility pole?" with possibly a specific one for telephone/telegraph (I was trying to decide which is a better fit in the UK; they've even got their own website: https://www.telegraphpoleappreciationsociety.org/ ).

> What is composite?

Something like fibre glass, although I see it's not on the wiki:
https://taginfo.openstreetmap.org/tags/material=composite

It will obviously not be wood/metal/concrete, but you might struggle to differentiate it from plastic if that was used.

Also if they start making it look like wood say (for conservation/acceptance reasons) it could all get complicated.

**Comment by matkoniecz** [comment]
`man_made=utility_pole` + `utility=power` is expected to have also `power=pole` and if it has not got it then it is a tagging mistake

> Also if they start making it look like wood say (for conservation/acceptance reasons) it could all get complicated.

there are already `material=concrete` that are convincing imitation of `material=wood` in Finland

**Comment by peternewman** [comment]
> > If we just added man_made=utility_pole + utility=power for now,
> 
> `man_made=utility_pole` + `utility=power` is expected to have also `power=pole` and if it has not got it then it is a tagging mistake

Yeah apologies, I thought from what @flacombe had said before they were equivalent or possibly migration, but I see the wiki says `power=pole` implies `man_made=utility_pole` + `utility=power`, which presumably makes those tags redundant and my short-term suggestion likewise.

> > Also if they start making it look like wood say (for conservation/acceptance reasons) it could all get complicated.
> 
> there are already `material=concrete` that are convincing imitation of `material=wood` in Finland

Convincing from a distance, or also when you're standing in front of it?

**Comment by matkoniecz** [comment]
> Convincing from a distance, or also when you're standing in front of it?

Initially? Also when standing next to it, I noticed only when one of them had decoration plastic layer damaged.

After that? It was clear that wood grain pattern on each pole is exactly the same and it was obvious.

**Comment by flacombe** [comment]
After a few questions asked and discussion, it turns out that `composite` should be changed in `epoxy`.
`material=concrete` also refers to a composite material for instance and `material=composite` sounds as invalid as `material=masonery`.

I'll document this on wiki and change my recent contributions from material=composite to material=epoxy.
Poles quest could then be improved with `material=epoxy` instead of previous calls for material=composite.

**Comment by mnalis** [comment]
> After a few questions asked and discussion, it turns out that composite should be changed in epoxy.

Can you link to that discussion, @flacombe ?

`material=epoxy` sounds **even more wrong** to me. Epoxy is there actually just a hardening "glue" that holds "main" material together.  That "main" material depends on the usage, but nowdays is mostly either fiberglass (cheap) or carbon sheets, (although it could be anything really). (Note that this "main material" is gross oversimplification too - type and amount of resin used has **huge** effect on characteristics of composite material)
 
It is called [composite material](https://en.wikipedia.org/wiki/Composite_material) because it is made (composed) of two or more materials. So it is by its definition very vague, like saying something is an "alloy" (without specifying "alloy of _what_"). But do note that reinforced concrete is also an composite material, as is plywood for example; so while the OSM usage `material=composite` might be correct, it is IMHO so vague to be in the same vagueness category as `surface=paved`.

Sure, you can be more precise by saying "composite of fiberglass and glycidylamine epoxy", but that is a mouthfull. 

But it is most definitely **not** **_"an epoxy"_**. If anything, one might be tempted to shorten it to just "**fiberglass**", although that is also not really correct, but is somewhat better (akin to saying that bronze  or brass are "copper", just because it is main ingredient, or that "reinforced concrete" is just "concrete"). 

Also note other resins than epoxy are often used, and while even expecting average users to identify if the composite material is containing fiberglass is somewhat problematic, expecting them to differentiate if the resin used was [epoxy](https://en.wikipedia.org/wiki/Epoxy) or [polyester](https://en.wikipedia.org/wiki/Polyester_resin)  or [vinyl](https://en.wikipedia.org/wiki/Vinyl_ester_resin) is downright unreasonable.

But even that might be too much for SC users to handle. Perhaps just stick to metal/wood/concrete and have "leave note" for all "other"? As @matkoniecz said, most users would have hard time differentiating from plastified outer layer of some other material and fiberglass+resin composite.

**Comment by flacombe** [comment]
> Can you link to that discussion, @flacombe ?

It was oral discussion with operators or manufacturers, or in OSM France Telegram group.
Epoxy is described in manufacturer documentation https://poteaux-composites.fr/telechargement/ft-2bcomposite.pdf
![image](https://user-images.githubusercontent.com/5690599/131657575-a900701f-2553-4277-9b22-399c5cea7143.png)
which translates to "Fiberglass + epoxy resin colored with brown pigments. The pole shows a decent wood appearance to allow an aesthetic integration in urban areas".

> akin to saying that bronze or brass are "copper", just because it is main ingredient, or that "reinforced concrete" is just "concrete"

However this is currently what we are doing with material=concrete.
Most buildings or utility poles that appear to be concrete are actually reinforced concrete.

> If anything, one might be tempted to shorten it to just "fiberglass", although that is also not really correct, but is somewhat better

So should we say that reinforced concrete is material=steel just because steel is used to reinforce concrete (which is just a hardening "glue" that holds "main" material together)?

I intend to document all of this on https://wiki.openstreetmap.org/wiki/Tag:material%3Depoxy which will be completed along our discussion here

**Comment by mnalis** [comment]
I was hoping it would be discussed on https://wiki.openstreetmap.org/wiki/Tagging_mailing_list to get more input...
(Single-handedly adding tags without getting more input and some kind of consensus often ends up being suboptimal)
