### ISSUE TITLE
Add "stone" option for surface quests

### ISSUE THREAD

**Issue by biketeur** [streetcomplete/StreetComplete#3189]
Beim taggen von Treppen werde ich zuerst nach der Oberfläche gefragt, kann aber häufig nicht antworten, da die Oberfläche Naturstein oder auch nur Stein (Marmor, Granit, Sandstein, ...) nicht angeboten wird. Auch die weiteren Tags bzgl.  der Treppe bleiben dann unbeantwortet.

Daher mein Vorschlag, zukünftig diese Oberfläche anzubieten.

**Comment by peternewman** [comment]
You can change the order of the quests within the settings, to put surface below the other stair quests if you want.

I think I often tag similar as paving stones.

Terrible auto-translation:
Sie können die Reihenfolge der Quests in den Einstellungen ändern, um die Oberfläche bei Bedarf unter die anderen Treppenquests zu legen.

Ich glaube, ich bezeichne oft Ähnliches als Pflastersteine.

**Comment by matkoniecz** [comment]
See https://wiki.openstreetmap.org/wiki/Tag:surface%3Dpaving_stones - though making it more clear in app could be a good idea.

**Comment by Helium314** [comment]
> See https://wiki.openstreetmap.org/wiki/Tag:surface%3Dpaving_stones - though making it more clear in app could be a good idea.

This is interestingly not the case for the German page, where the description only mentions stones made from concrete or bricks.
I guess this would be another use case for the "additional information" proposed in #1913 

> Auch die weiteren Tags bzgl. der Treppe bleiben dann unbeantwortet.

You can simply use can't say -> hide
Du kannst einfach "Nicht beantwortbar…" -> "Nein, verstecken" auswählen und danach den Rest beantworten

**Comment by matkoniecz** [comment]
> You can simply use can't say -> hide

Or even better, leave a note with a photo.

**Comment by biketeur** [comment]
Danke für die Antworten.

Unter https://wiki.openstreetmap.org/wiki/Tag:surface%3Dpaving_stones
finde ich keine Abbildung, welche nach einer Treppenstufe aus Marmor, Granit oder Sandstein aussehen.

Notiz und Foto hinterlassen?
Bei den dutzenden von Treppen viel Aufwand. Und was soll mit den Notizen geschehen? Soll dann jemand anderes für mich Stone eintragen? Großer Mehraufwand.

Vor etwa 3 Monaten wurde SC um die Oberfläche Holzschnitzel erweitert. Ich kenne in meiner Heimatstadt nur 2 Wege mit Holzschnitzel, aber hundertmal soviele Treppenstufen mit der Oberfläche stone.
Warum sträubt sich die Entwicklung dagegen?
Der Aufwand kann nicht allzugroß sein.

**Comment by westnordost** [comment]
> Notiz und Foto hinterlassen?

Zurzeit, ja, eh.

Magst Du vielleicht mal ein paar Beispielfotos hochladen um einen typischen Fall für Stein-Oberfläche zu zeigen? Wenn es kein Foto ist dass direkt auch eine Treppe zeigt sondern nur das Material an sich, könnte dieses Foto dann auch als Bild für die Auswahl verwenet werden.

**Comment by matkoniecz** [comment]
https://commons.wikimedia.org/wiki/File:Pretty_natural_stone_used_for_paving.jpg

https://commons.wikimedia.org/wiki/File:Pretty_natural_stone_used_for_steps.jpg

may be useful (I taken and uploaded it to document such case at OSM wiki)

**Comment by westnordost** [comment]
Ah, are you sure that this is what is meant for `surface=stone`? I imagined it would be natural stone, e.g. stone slabs.

**Comment by westnordost** [comment]
This is what I thought stone would be:
https://wiki.openstreetmap.org/wiki/File:Stone_Steps_Wide_Angle_Perspective_1933px.jpg

Though, if `stone` was not available, I would probably tag this as paving stones (or sett) still, as they are clearly hewn in form.

**Comment by peternewman** [comment]
> This is what I thought stone would be:
> https://wiki.openstreetmap.org/wiki/File:Stone_Steps_Wide_Angle_Perspective_1933px.jpg

Yeah I'd think of that, or particularly something like these as stone:
https://www.alamy.com/worn-stone-steps-chepstow-castle-wales-uk-image9844213.html
https://www.mostphotos.com/en-us/22928294/old-stone-steps

As found in most old castles and other ancient buildings or their surroundings.

**Comment by biketeur** [comment]
Die Bilder sind gut, bessere kann ich nicht zur Verfügung stellen.
Solche Treppen findet man an alten Kirchen, Rathäusern, Denkmälern, aber auch auf älteren Friedhöfen und in Parks.

**Comment by westnordost** [comment]
Welche davon? Die sind ja jeweils sehr unterschiedlich

**Comment by Oi-sin** [comment]
Das Problem betrifft auch Gehwege. Hier in Dresden werden dafür sehr häufig große Granitplatten genutzt (siehe z.B. Foto in https://www.openstreetmap.org/note/2810474). Steinpflaster ist das für mich nicht. Stufen aus großen Natursteinquadern sind auch üblich, die aus meiner Sicht mit Steinpflaster nicht korrekt beschrieben wären.

**Comment by westnordost** [comment]
Mal in der Wiki nachgeschaut - https://wiki.openstreetmap.org/wiki/Tag:surface%3Dpaving_stones und auch auf der Wiki-Seite zu Key:surface inkludiert die Definition von `paving_stones` auch Pflastersteine aus Naturstein (sowie Ziegelsteinen):

> A relatively smooth surface paved with artificial blocks (block pavers, bricks) or natural stones (flagstones), with a flat top.

Und entsprechende Fotos sind auch vorhanden. Der Tag wird so beschrieben seit `paving_stones` überhaupt beschrieben ist (ca. 2009). Die deutsche Version der Seite erwähnt Natursteinpflaster nicht explizit sondern dort steht nur dass es "meist" Betonpflaster ist. Was ja auch richtig ist. Es ist "meist" Betonpflaster.

Für Natursteinpflaster in der Art wie in der Notiz gezeigt sowie das von @matkoniecz verlinkte ist die Anwort aber also klar: Das ist auch  `paving_stones` . So ist es seit 2009 in der Wiki definiert.

Intuitiv würde ich sagen, dass `stone` eher nur für "nackten Stein", also (relativ ebene oder gar behauene) Felsoberfläche genutzt wird oder werden sollte. (`rock` ist dann eher für nicht ebenen nackten Fels wie 
<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/Cascade_canyon_trail_teton_20190713_095423_1.jpg/640px-Cascade_canyon_trail_teton_20190713_095423_1.jpg"/>
).

**Comment by westnordost** [comment]
So, offer to include `surface=stone` still stands, but we need to find an appropriately licensed representative picture that is clearly neither `rock`, `sett` nor `paving_stones`.

**Comment by mnalis** [comment]
Something like this steps?
![IMG_20210904_163411b](https://user-images.githubusercontent.com/156656/132967457-3b125797-bbee-4235-a1d1-555945e5cf1b.jpg)
 Although it could still be classified as extremely large [surface=sett](https://wiki.openstreetmap.org/wiki/Tag:surface=sett), I guess.

**Comment by westnordost** [comment]
Yeah, but it would be better to have a picture of a larger stone surface (or at higher resolution / zoomed in on one step), maybe cleaned a bit from the cigarettes and needles. Did you make this photo?

**Comment by westnordost** [comment]
Did you make this photo, @mnalis ?

To continue here, we would need a nice picture of natural stone. This picture might be okay, but better would be a "bare rock" surface that is still halfway smooth, I think this is the understanding of stone, more or less.

**Comment by matkoniecz** [comment]
What about foreground of https://commons.wikimedia.org/wiki/File:Rock-Hewn_Churches,_Lalibela-107577.jpg

Maybe something else in https://commons.wikimedia.org/wiki/Category:Cave_churches_by_country ?

(one idea: cheat by taking picture of a monolithic stone wall)

**Comment by mnalis** [comment]
> Yeah, but it would be better to have a picture of a larger stone surface (or at higher resolution / zoomed in on one step), maybe cleaned a bit from the cigarettes and needles. Did you make this photo?

Ooops, sorry @westnordost , I somehow missed the original notification on this. Yes, I made that photo. Unfortunately I've left that place a week ago, and only other picture I've made is even more zoomed-out (and made on the same lower-quality phone - didn't have my newer phone on me at the time). 

Perhaps if this issue is still unsolved by my next-summer vacation I could retake better pics :face_with_head_bandage: :smiley: 

> To continue here, we would need a nice picture of natural stone. This picture might be okay, but better would be a "bare rock" surface that is still halfway smooth, I think this is the understanding of stone, more or less.

I'm not sure I completely follow; do you mean something like this: https://en.wikipedia.org/wiki/Rock_(geology)#/media/File:DirkvdM_rocks.jpg? I was going mostly by [this definition](https://www.thefreedictionary.com/stone), especially _"3. Rock or a piece of rock shaped or finished for a particular purpose"_. Because, IMHO, if it is _not sufficiently shaped by humans_, then even if it is relatively flat it would be just `rock` instead (eg. https://wiki.openstreetmap.org/wiki/File:Coastal_rock_formation.jpg) , and not a `stone`. Of course, the opposite is also true: if cut/polished _too much by humans_, it might become `paving_stone` instead.

**Comment by biketeur** [comment]
Hier 2 Fotos mit Stein-Oberflächen:Am 07.10.2021 14:43 schrieb Tobias Zwick ***@***.***>:
Here are two more pictures


l

**Comment by westnordost** [comment]
Sett ist MEIST quaderförmig und Pflastersteine sind MEIST aus Beton.

Pflaster ist doch nicht kein Pflaster mehr nur will es nicht die richtige Form hat. Entscheidend ist dass es aus Stein zu Pflastersteinen behauen wurde.

Am 17. Oktober 2021 09:36:33 MESZ schrieb biketeur ***@***.***>:
>Im OSM-Wiki wird sett wie folgt beschrieben:>
>Behauenes Steinpflaster (Pflastersteine): Diese Steine sind ebener als
>(unhewn_cobblestone) und haben annähernd eine Quaderform. Pflaster aus
>diesen Steinen sind daher wesentlich angenehmer zu gehen oder zu
>befahren.	Entsprechendes Bild:>
>https://wiki.openstreetmap.org/wiki/File:Granite_Setts.jpg>
>Also, ich sehe keine Quaderformen bei meinen Bildern.>
>>
>Im OSM-Wiki wird paving_stones wie folgt beschrieben:>
>Pflastersteine meist aus Beton gefertigt mit gleichmäßiger,
>regelmäßiger Form. Sie haben daher bei der Verlegung nur schmale
>Zwischenräume.>
>Entsprechende Bilder:>
>https://wiki.openstreetmap.org/wiki/File:Surface_paving_stones.jpg>
>https://wiki.openstreetmap.org/wiki/File:Dscf1620-800.jpg>
>Auch das Bild in SC zeigt nur (verschiedene) Pflastersteine aus Beton.>
>Die Treppenstufen des 2. Bildes sind nicht aus Beton, haben zwar an den
>Längsenden glatte Flächen und bilden dort eine Fuge, an der Vorderkante
>haben sie jedoch gehauene, abgerundete Flächen und könnten dort nicht
>mit schmalen Fügen verlegt werden.>
>>
>-- >
>You are receiving this because you were mentioned.>
>Reply to this email directly or view it on GitHub:>
>https://github.com/streetcomplete/StreetComplete/issues/3189#issuecomment-945065781

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by mnalis** [comment]
Is this still interesting? I'm wondering because:
- I personally haven't _really_ been needing such option since last year when this issue was opened almost a year ago
- it usually can be answered with `paving_stones` or `sett`
- If there is still interest; would this updated images of those [stone steps](https://github.com/streetcomplete/StreetComplete/issues/3189#issuecomment-917522606) which were indicated as interesting [before](https://github.com/streetcomplete/StreetComplete/issues/3189#issuecomment-922493232) help?
![small_IMG_20220528_162623](https://user-images.githubusercontent.com/156656/172748738-8f2ecef4-a9a4-4817-959d-5062bd235931.jpg) ![small_IMG_20220528_162515](https://user-images.githubusercontent.com/156656/172748746-d257e99f-2f59-4f0d-a7ca-4c6ffd648e9c.jpg)
- I'm not sure if "flat rock" qualifies as "stone" if it has [not been flattened by humans](https://github.com/streetcomplete/StreetComplete/issues/3189#issuecomment-937325741). If it does, would something like this help?
![small_IMG_20220603_192402](https://user-images.githubusercontent.com/156656/172748470-9c865bf8-0089-45a0-94ce-edf43e219884.jpg) ![small_IMG_20220603_192341](https://user-images.githubusercontent.com/156656/172748477-d41df2b1-8894-4b27-b423-9ee24ae3d517.jpg) ![small_IMG_20220531_184308](https://user-images.githubusercontent.com/156656/172748480-c801591e-64b8-4953-aa86-2ca7ee02a09c.jpg)

I can provide all those images in better resolution in few days, just let me know which ones you want (I'm currently on metered network connection). Or I can retake the images from different angles or whatever is required.

**Comment by westnordost** [comment]
Hmm, I think this should be closed. While an option for `surface=stone` is still open (but `surface=rock` has been added),
- `surface=stone` is not documented, so we can only make a(n educated) guess what the difference to `surface=rock` would be. That this tag is really always used in the way we argue(d) here is wishful thinking, as the words "rock" and "stone" is often used interchangibly
- if `surface=stone` is really the pure "naked rock surface", it is very narrow definition because as soon as there are also some pebbles and other small loose rocks, it would need to be `surface=rock` again. Since we are talking about nature, and not about inner-city-micromapping, I find it unmaintainable to map such precise distinctions
- the distinction to `surface=rock` is not that important I believe, despite the perceived difference in smoothness, because even if it is smooth rock surface, it will not be even

**Comment by georg-d** [comment]
To whom it may concern: Besides potentially applicable answers mentioned above, also https://wiki.openstreetmap.org/wiki/Tag:surface%3Drock (EN rock / DE Fels) can be applicable – and is offered as answer in SC 🙂 https://github.com/streetcomplete/StreetComplete/issues/5094 is about making photo and/or wording more clear what it includes.
