### ISSUE TITLE
[GB only?] Does this place accept American Express?

### ISSUE THREAD

**Issue by Cj-Malone** [streetcomplete/StreetComplete#3219]
### General
Affected tag(s) to be modified/added: [payment:american_express](https://wiki.openstreetmap.org/wiki/Key:payment)
Question asked: **Does this place accept American Express?**

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/wiki/Adding-new-Quests-to-StreetComplete)):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [ ] 🐿️ Easily answerable by everyone from the outside but a survey is necessary
  - This quest should indoor/disabled by default.
- [x] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of map data (Worth the effort)

### Ideas for implementation

**Element selection:** Some shops and amenities, with `payment:credit_cards=yes`, (and potentially filter out `brand:wikidata`).

In GB because of the dominance of Visa and Mastercard places are often tagged as `payment:credit_cards=yes` `payment:debit_cards=yes`, and not broken down into `payment:mastercard=yes` `payment:visa=yes`.
The only thing people ever ask is "Do you accept Amex?", it can't be assumed like Visa and Mastercard.

Arguably `payment:credit_cards=yes` and `payment:debit_cards=yes` should be assumed defaults for all places in GB, but that's a conversation for another time.

Filtering out `brand:wikidata` is based on the assumption that they are more likely chain stores, where the data would be better in [defaults](https://wiki.openstreetmap.org/wiki/Proposed_features/Defaults), bulk edits, NSI, Wikidata or some other place. Asking it for chains is unnecessary and spammy.

**Comment by Lee-Carre** [comment]
If this quest is implemented (and, here, I'm not commenting either way on if it should or not) then please also enable it for (the island of) Jersey (and probably the other Channel Islands (Guernsey, etc.)).

In Jersey, there's very little predictability for if payment:american_express is accepted or not.

Having spoken with some operators about this, an oft cited objection is the higher fees. This correlates with the observation that, generally, only larger establishments (likely using major payment-processing agents) tend to accept more than payment:visa & payment:mastercard (and their corresponding debit card equivalents), while the smaller ones (which aren't part of a chain / franchise) do not (unless their payment processor happens to accept American Express already, anyway; e.g. [SumUp](http://support.sumup.com/hc/en-us/articles/115008338507-Accepted-Cards)).

As for the nature of the quest; might I suggest that this be about payment methods in general (lest there end up being a quest per payment method). Regardless, I can see the utility of asking this question in Europe.

**Comment by andrewharvey** [comment]
+ Ask in Australia where many places accept and many places don't. Then eventually after the tagging support it (maybe with `payment:american_express:fee=yes/no`) you could ask is there a fee for using Amex, some places don't change any fee, other places +1-3% on top of the bill when using Amex so it would be good to capture this.

**Comment by mnalis** [comment]
Same situation in Croatia, `Visa` / `Mastercard` / `Maestro` are accepted at all places that accept credit/debit cards but `American Express` (and `Diners`) are not accepted in some places. But I don't think we even have a quest if the place accepts any card payments? 

So perhaps it would be wisest for quest to ask something like `Does this place accept cards for payment? Which ones?`. It might be able to reuse some code from [AddAcceptsCash.kt ](https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/accepts_cash/AddAcceptsCash.kt)

**Comment by kmpoppe** [comment]
> So perhaps it would be wisest for quest to ask something like `Does this place accept cards for payment? Which ones?`. It might be able to reuse some code from [AddAcceptsCash.kt ](https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/accepts_cash/AddAcceptsCash.kt)

I'd also be in favour of specifically asking which cards are accepted (there's a whole load of payment options in the Wiki, I wonder if these could be put into SC sensibly, maybe as a multi-layered, multiple choice quest 🤔 ).

**Comment by mnalis** [comment]
Uh, there are definitely more than I though listed at https://wiki.openstreetmap.org/wiki/Key:payment#Keys :cry: 

I don't know what would be a good solution. Perhaps offer only `major debit cards`, `major credit cards`, `both credit & debit cards`, `no cards` and `something else / it's complicated`, where `something else / it's complicated` would allow leaving a note with picture, so it can be postprocessed at desktop? 

Or just have a list of several major ones (`mastercard` / `visa` / `american express` / `diners` / `JCB` / `Discover` for credit cards, `Visa debit` / `Maestro` / `Girocard` for Debit)? That might be on the verge of doable. Maybe split into two quests, one for debit cards, one for credit cards?

Note that Debit/credit distinction is important there, as there are places which don't allow credit cards (smaller places, or frequent fraud ones?), as well as those who don't allow debit cards (hotels, car rentals). 

Otherwise, having users to wade through list of dozens of cards all at once does sound problematic (at least in StreetComplete which strives for quick and simple answers!)

**Comment by kmpoppe** [comment]
I'm currently checking whether I can make something work from how the Recycling Materials quest was built.

And yes, it's a complicated move between quick answers and detailled answers.

Lemme see if something can be done :)

**Comment by kmpoppe** [comment]
So, this is how the new quest looks plain:
![grafik](https://user-images.githubusercontent.com/24451207/133855639-8219eac4-abca-4b04-9a44-14383ed7640c.png)
Any specific payment methods from Credit Cards, Debit Cards or Cash can be selected
![grafik](https://user-images.githubusercontent.com/24451207/133855696-6605b6ec-0460-4a36-b026-d7b002bce3ed.png)
If any of the `no` methods are selected, those from the same area are deselected, likewise, `no` is deselected if you select a more specific payment
![grafik](https://user-images.githubusercontent.com/24451207/133855816-6171402f-dfcd-4350-b1ee-f0d3469aa912.png)

What y'all think, @westnordost as well, could this quest replace the "Is cash accepted here?" quest and work for all countries? @Cj-Malone would this be sufficient for you to mark "this place doesn't accept AMEX"?

I'm out on holiday for the next week, if there are more Ayes then Noes I'll make a WIP PR because there needs to be some refinement that I know of already ;-)

**Comment by Discostu36** [comment]
I like the idea. I think that the quest should have two different versions: Countries that have the "is cash accepted here" quest disabled now should not get the last row of options.

**Comment by Cj-Malone** [comment]
That doesn't seem great for the UK. 99% of the time you'd be selecting every single item.

**Comment by westnordost** [comment]
Oof, it is never a good idea to start working on a new quest that hasn't been accepted yet. Sorry, the way you imagine it will not be accepted. And likely not even the original suggestion.

Because when looking at the unusual card providers (and payment methods), there'll be many. But how to know if they simply haven't been tagged yet or if they are not accepted? (Same problem with recycling materials and fuel)
Additionally, I'd say that many shops and businesses that accept cards in general maybe don't know or don't advertise exactly which credit card(s) they accept. They just have this portable card reader thing.

**Comment by westnordost** [comment]
Ah sorry, I didn't really read this ticket before, it doesn't look like this came out of nowhere

**Comment by andrewharvey** [comment]
@kmpoppe Looks good, I think it will need a fair bit of regional variation, ie. each region has their own configuration. Because for me I've never seen a distinction between credit and debit cards made, either it'll accept amex or not, visa or not, mastercard or not based on those logos.

**Comment by Lee-Carre** [comment]
> I don't think we even have a quest if the place accepts any card payments?

> So perhaps it would be wisest for quest to ask something like Does this place accept cards for payment?

Excellent point. I'd be strongly in favour of asking for basic info first (does this place accept payment:credit_cards (and/or payment:debit_cards)?) before quests trying to tackle the litany of specific payment types (e.g. individual cards).

That should be simpler to implement, and provide usable info quicker.

Though, preferably not just cards, but other categories:
* contactless
* cash (if deemed applicable per country)
* cryptocurrencies
* electronic purses
* digital wallets

Later, we can ask for e.g. types of cards, etc.

If others want to refine the data in the meantime, then they can easily find places with only payment categories since an osmose issue is generated in such cases.

**Comment by Lee-Carre** [comment]
A note on the proposed implementation mockup:

Having done a fair bit of payment:* tagging (via Vespucci), my understanding of the cash-related tags is that payment:cash means both payment:notes & payment:coins .

payment:notes / payment:coins are used when only one is accepted but not the other.
For example public telephones or vending machines, which accept payment:coins but not payment:notes (thus payment:cash would be inappropriate / misleading).

Though I suppose this could be handled internally by SC (rather than complicating the UI), much like for other quests, so that if the user selects both notes & coins, then payment:cash=yes is set (instead of payment:notes=yes & payment:coins=yes).

**Comment by kmpoppe** [comment]
@Lee-Carre as far as I understand the Wiki, those generic tags **should** _only_ be used, if a whole group of payment methods is NOT available.

Tagging those with `yes` will have OsmOse tell you for each object that the tagging is too generic.

If we do this anyway, we would need more quests that as what credit cards are available (albeit there are only 8 listed in the payment-key wiki, so the list in the mockup is extensive). Then what debit cards are available. The what electronic purses aso.

K

**Comment by matkoniecz** [comment]
> OsmOse tell you for each object that the tagging is too generic.

Osmose has many invalid complaints (see say #3118) so I would not treat it as a problem

**Comment by Cj-Malone** [comment]
I tag `payment:credit_cards=yes` and `payment:debit_cards=yes` semi regularly, even though it is flagged. I consider it valid tagging in GB.

I would also argue against a quest along the lines "Does this place accept cards?" with `payment:credit_cards=yes/no` answers. It's spam for GB, and probably most of the world, we should just concentrate on defining reasonable assumptions for each part of the world.

If we go back to "Does this place accept Amex?" yes/no there could be an "other answer" with something like "this place doesn't take any cards" that would tag `payment:credit_cards=no` `payment:debit_cards=no`.

**Comment by mnalis** [comment]
> I would also argue against a quest along the lines "Does this place accept cards?" [...] It's spam for GB, and probably most of the world

Maybe if you change that assumption to _"most of the **1st-class** world"_. 

I'd be quite surprised if I could buy things everywhere I felt like it in rural Africa by waving a peace of plastic, for example. 
Even in parts of EU like Croatia and its neighbors, there are quite many places which would take cash only - almost all [shop=farm](https://wiki.openstreetmap.org/wiki/Tag:shop%3Dfarm), majority of standalone icecream stands and fast food joints (excluding few big incorporated ones like McDonalds), most of marketplaces (especially open ones in smaller places, many of which don't have electricity, much less card processing capability), many kiosks, bakeries, pubs and cafes, and often even rural convenience shops and some restaurants. Many of the guest house renters will take cash only too. If fact, few of the categories above are even exempt by law so they don't even have to give you a receipt of any kind.

> If we go back to "Does this place accept Amex?" yes/no there could be an "other answer" with something like "this place doesn't take any cards" that would tag payment:credit_cards=no payment:debit_cards=no.

There is also debit/credit distinction. For example, in Canada they refused to rent a car to my friend at several places unless paying with credit card  (they refused VISA debit card, as well as leaving cash deposit or any other combination). Same thing happened a few years back to me in German hotel, where they didn't want to take debit cards but credit cards only. (I guess the reason is capability of credit cards to use two-part payment processing; eg. "reserve" much more money than you intend to charge later if everything is OK, in order to cover possible loses - like hotel guest clearing the minifridge and then refusing to pay exorbitant prices, or damaging the rented car or whatever)

**Comment by kmpoppe** [comment]
> I would also argue against a quest along the lines "Does this place accept cards?" with `payment:credit_cards=yes/no` answers. It's spam for GB, and probably most of the world, we should just concentrate on defining reasonable assumptions for each part of the world.

If you ever tried paying with a Credit Card in Germany, you'd know these answers: No 1: CASH ONLY! No 2: NUR EC-KARTE (it's actually called `payment:girocard` but all those top-level merchants aren't able to distinguish between that and the former which was abandoned almost 20 years ago) No 3: Sure you can pay by credit card, but you have to spent at least 20€.

So, in Germany, it is not spammy to ask if a place accept cards. Sadly.

That's why I was going for an explicit list of cards (and cash, @Lee-Carre same argument as with the cards. Cash=no means no cash at all, most vending machines for Public Transport or Parking tickets in Germany only accept coins, no notes, hence the separation) accepted.

K

**Comment by mnalis** [comment]
@kmpoppe I agree there are a lot of places where the distinction cash and specific debit/credit cards is needed. Two issues with suggested proposal, mostly mentioned before in one form or another:

- How to distinguish between "Place does not accept AmEx" and "it is not marked weather it accepts AmEx or not" ?
  JOSM for example does it by having a three-state checkboxes, for example (checked box for `yes`, unchecked white box for `no`, and unchecked grey box for `unknown` eg. "do not add a tag for that case at all"), but such UI perhaps might not translate well for mobile use.
- one tempting "solution" to above problem would be "user must answer ALL cards that are accepted", but it does not really work well because place might not advertise all payment methods, so users only know it accepts what they tried to pay with - "VISA Debit" for example, so it would be useful contribution, and after several users the quest would be finally solved. We could hide it locally for that device maybe, but it would still show for everyone else as unsolved unless ALL the payments methods are selected, and that is not possible unless we have a distinction between "AmEx is NOT accepted" and "We have no information on AmEx acceptance"
- to compound the problem above ("when would the quest finally stop popping up for users as not fully solved?"), some regions do not really have some cards in circulation. For example, in Croatia it might take a loong time for someone to answer "UnionPay" card is (or is not) accepted, as it is quite probable that even the cashiers in most places have never seen an UnionPay card in their life, much less tried to see if it machine accepts it.

**Comment by Lee-Carre** [comment]
> I would also argue against a quest along the lines "Does this place accept cards?" with payment:credit_cards=yes/no answers. It's spam for GB, and probably most of the world, we should just concentrate on defining reasonable assumptions for each part of the world.

For English-speaking Europe, probably. I didn't think about the no-spam rule for quests.

Seems that the question of payment:* tagging is somewhat tricky for SC, and since I use Vespucci a lot, lately, that's probably influencing my mindset. So, I'll bow out of that discussion topic. I may well not be the target user-group any longer.

I do agree that figuring out what's sensible, per-region (since they vary wildly), does seem to be key to achieving sane quest usability. Devil's in the details.

> I tag payment:credit_cards=yes and payment:debit_cards=yes semi regularly, even though it is flagged. I consider it valid tagging in GB.

At the risk of going off-topic; my own thinking is comparable (if not similar).

There are enough places (in Jersey) that have varying payment options, that assumptions may only be loosely applied (or only under certain conditions). Not only types of cards (if any) but various other methods. Some places I've surveyed didn't match my expectations at all. Some places are surprised that others don't accept more methods, and vice versa. Thus I avoid assuming, and take an explicit approach to tagging.

Besides making things explicit (rather than default assumptions), setting payment:[generic_category]=yes is to make it easier for data-parsers when they simply want to know if anything within an entire category is accepted or not (rather than having to know about all card types and parse & process all those tags to determine the more general answer). However,  whenever I can, I also add the specific sub-types (individual cards, or whatever else). So, both-and rather than either-or.

Similar to setting opening_hours:signed=*, habitually. That might help those doing a resurvey in future.

Osmose still flags elements specifying both general & specific payment:*=yes as an issue. I mark those as false-positives.
Really, bug reports should be submitted to fix the matching criteria. There are some other similar bugs (producing false-positive alerts) in Osmose, too.

Interestingly, I don't recall Osmose flagging payment:cash=yes (in absence of payment:(note|coin)s=*) as a problem. It certainly does for payment:(credit|debit)_cards=yes though, even when the more specific tags (for individual cards) are already present.

There's also the possibility that tagging of accepted cards isn't exhaustive (maybe because the sign didn't specify, and I'm not in the mood to go ask). American Express being a good example, here; since the place accepts other cards, they might accept AE too, but the tag being absent should be interpreted as ‘unknown’.

I'm reminded of one instance when it was made clear that payment:apple_pay was the only digital wallet accepted; none others (including payment:google_pay). So I set all the others to payment:*=no rather than leave it be ambiguous.

This is probably part of why I use Vespucci more; too many weird cases than would an reasonable for SC to handle. Though SC is definitely still useful.

**Comment by smichel17** [comment]
"Does this place accept cards?" Seems unnecessary when you can jump straight to "What cards does this place accept?" and add an option for "None (it does not accept credit cards)."

On September 19, 2021 9:21:27 PM UTC, "Lee Carré" ***@***.***> wrote:
>> I would also argue against a quest along the lines "Does this place accept cards?" with payment:credit_cards=yes/no answers. It's spam for GB, and probably most of the world, we should just concentrate on defining reasonable assumptions for each part of the world.
>
>
>
>For English-speaking Europe, probably. I didn't think about the no-spam rule for quests.
>
>
>
>Seems that the question of payment:* tagging is somewhat tricky for SC, and since I use Vespucci a lot, lately, that's probably influencing my mindset. So, I'll bow out of that discussion topic. I may well not be the target user-group any longer.
>
>
>
>I do agree that figuring out what's sensible, per-region (since they vary wildly), does seem to be key to achieving sane quest usability. Devil's in the details.
>
>
>
>> I tag payment:credit_cards=yes and payment:debit_cards=yes semi regularly, even though it is flagged. I consider it valid tagging in GB.
>
>
>
>At the risk of going off-topic; my own thinking is comparable (if not similar).
>
>
>
>There are enough places (in Jersey) that have varying payment options, that assumptions may only be loosely applied (or only under certain conditions). Not only types of cards (if any) but various other methods. Some places I've surveyed didn't match my expectations at all. Some places are surprised that others don't accept more methods, and vice versa. Thus I avoid assuming, and take an explicit approach to tagging.
>
>
>
>Besides making things explicit (rather than default assumptions), setting payment:[generic_category]=yes is to make it easier for data-parsers when they simply want to know if anything within an entire category is accepted or not (rather than having to know about all card types and parse & process all those tags to determine the more general answer). However,  whenever I can, I also add the specific sub-types (individual cards, or whatever else). So, both-and rather than either-or.
>
>
>
>Similar to setting opening_hours:signed=*, habitually. That might help those doing a resurvey in future.
>
>
>
>Osmose still flags elements specifying both general & specific payment:*=yes as an issue. I mark those as false-positives.
>
>Really, bug reports should be submitted to fix the matching criteria. There are some other similar bugs (producing false-positive alerts) in Osmose, too.
>
>
>
>Interestingly, I don't recall Osmose flagging payment:cash=yes (in absence of payment:(note|coin)s=*) as a problem. It certainly does for payment:(credit|debit)_cards=yes though, even when the more specific tags (for individual cards) are already present.
>
>
>
>There's also the possibility that tagging of accepted cards isn't exhaustive (maybe because the sign didn't specify, and I'm not in the mood to go ask). American Express being a good example, here; since the place accepts other cards, they might accept AE too, but the tag being absent should be interpreted as ‘unknown’.
>
>
>
>I'm reminded of one instance when it was made clear that payment:apple_pay was the only digital wallet accepted; none others (including payment:google_pay). So I set all the others to payment:*=no rather than leave it be ambiguous.
>
>
>
>This is probably part of why I use Vespucci more; too many weird cases than would an reasonable for SC to handle. Though SC is definitely still useful.
>
>
>
>-- >
>You are receiving this because you are subscribed to this thread.
>
>Reply to this email directly or view it on GitHub:
>
>https://github.com/streetcomplete/StreetComplete/issues/3219#issuecomment-922538764
-- 
To respect your time, I try to write short, functional emails.

**Comment by kmpoppe** [comment]
>     * How to distinguish between "Place does not accept AmEx" and "it is not marked weather it accepts AmEx or not" ?
>       JOSM for example does it by having a three-state checkboxes  (checked white box for `yes`, unchecked white box for `no`, and unchecked grey box for `unknown` eg. "do not add a tag for that case at all"), but such UI perhaps might not translate well for mobile use.

While the GUI is currently not equipped for a tri-state Image-Selector, we could always go for:
* not selected (no answer is given)
* first tap selects it green (answer is yes, accepted)
* second tap selects it red (answer is no, not accepted)
* next tap deselects the option

This is a method we use in MapSwipe and it works fine, there'll just need to be some more work on the form classes to get that going (alas, "no cards accepted" must be two-state only while the others are tri-state, that could be tricky).
 
>     * one tempting "solution" to above problem would be "user must answer ALL cards that are accepted", but it does not really work well because place might not advertise all payment methods [...]

Answer ALL is always complicated, no disagreement there. Currently, the quest that I built (leant from the recycling materials) only gets asked if there's literally no `payment:*=*` whatsoever (or if older than 2 years), so any change in the acceptance later will be caught by SC's QA process.

>     * to compound the problem above ("when would the quest finally stop popping up for users as not fully solved?"), some regions do not really have some cards in circulation. For example, in Croatia it might take a loong time for someone to answer "UnionPay" card is (or is not) accepted, as it is quite probable that even the cashiers in most places have never seen an UnionPay card in their life, much less tried to see if it machine accepts it.

SC has a built-in functionality to check whether a quest should be asked according to the country. I believe that could also be used to determine what cards would be shown as they are in "frequent circulation" (I have honestly never seen Diners or Discover here in Germany, let alone UnionPay or JCB).

**Comment by kmpoppe** [comment]
Closed by #3953 I think?!

**Comment by Cj-Malone** [comment]
That doesn't solve the original issue, `payment:credit_cards=yes` can't be used to infer `payment:american_express=yes` in GB.

**Comment by westnordost** [comment]
This issue is so long TBH I didn't read through it again and don't know its current status.

**Comment by Cj-Malone** [comment]
Yeah lots of comments on this and it changed directions a few times. But I think the original request still stands.

"Does this place accept American Express?" Yes/No

Asked on shops and amenities with `payment:credit_cards=yes` without `brand:wikidata`.

**Comment by trigpoint** [comment]
> Yeah lots of comments on this and it changed directions a few times. But I think the original request still stands.
> 
> "Does this place accept American Express?" Yes/No
> 
> Asked on shops and amenities with `payment:credit_cards=yes` without `brand:wikidata`.

I am not sure that I understand the relevance of brand:wikidata.

**Comment by Cj-Malone** [comment]
> I am not sure that I understand the relevance of brand:wikidata.

> Filtering out `brand:wikidata` is based on the assumption that they are more likely chain stores, where the data would be better in [defaults](https://wiki.openstreetmap.org/wiki/Proposed_features/Defaults), bulk edits, NSI, Wikidata or some other place. Asking it for chains is unnecessary and spammy.

I've not got a strong opinion though.
The new "AcceptsCards" quest filters out objects with `brand` `wikipedia:brand` or `wikidata:brand`.

**Comment by trigpoint** [comment]
> > I am not sure that I understand the relevance of brand:wikidata.
> 
> > Filtering out `brand:wikidata` is based on the assumption that they are more likely chain stores, where the data would be better in [defaults](https://wiki.openstreetmap.org/wiki/Proposed_features/Defaults), bulk edits, NSI, Wikidata or some other place. Asking it for chains is unnecessary and spammy.
> 
> I've not got a strong opinion though. The new "AcceptsCards" quest filters out objects with `brand` `wikipedia:brand` or `wikidata:brand`.

The issue that came to mind here is that Petrol Stations will have a brand:wikidata based on the oil company, but that doesn't mean that the owner cannot make their own decisions on Amex.

My local petrol station does not accept Amex.

**Comment by westnordost** [comment]
I am sorry, but I've now decided that any tagging of `payment:*` where * is a specific payment service, from bitcoin, to paypal, to google pay, to mastercard, to debit card, shall not be done with this app. Generally.

The reasons are:

- **💵 Valuable surveyors:** Whether or not a shop accepts certain payment methods is a very volatile information that may change frequently or even without the shop's knowing. Volatile data necessitates more frequent re-checking which further draws on the limited resource of OpenStreetMap surveyors time.

- **🕵️ Publicly accessible on foot:** Especially non-hype currency is often not advertised on the outside. One may occasionally see a handwritten note sticked to the shop door "no card payment", or nothing, or the waiter telling you that card payment is (currently?) not possible, some may have a sticker with logos of accepted cards on their door, but not all. Plus, if e.g. google pay is missing from that sticker, it doesn't mean that it is not available, it just means that they didn't put the sticker there (yet).

- **🪧 Advertisement / 🚧 Established tags only:** Shops that accept hype currency such as the various cryptocurrencies or start-up payment processors are usually so few when compared to the total number of shops that mapping these at all feels like doing advertising for these

- **💤 No spam:** ... and of course, the answer the user gives will almost always be the same: no.

- **💵 Valuable surveyors:** Hype currency aside, every shop uses some kind of payment processor that accepts certain services, which may change over time. The number of payment processors in an area is much smaller than the number of shops. I find it questionable if tagging all payment services accepted _on each shop_ is the right approach here at all as the tagged information becomes wrong as soon as the payment processor used by the shop changes which services are accepted or the shop changes the payment processor. I am not advocating for tagging the payment processor instead, because this is even less 🕵️👨‍💻 publicly accessible, 

- **🤷 Useful purpose:** To be useful, the data has to have a certain coverage and needs to be kept up to date. However, I strongly doubt there will ever be a good enough coverage that the data will be useful because frankly, the effort involved in keeping this data correct and up to date is just too much. Maybe not if there was just one or two payment services on earth, but...

- **💵 Valuable surveyors:** It is a bottomless pit. There is an ever-growing mass of payment services out there, tagging them all and _keeping them up-to-date_ in OpenStreetMap is unrealistic. At most, what would be realistic is to make the distinction "card payments" / "cash payments", without specifying which kind of cards - cause that is rather dependent of the region you are in right now than the specific shop you are in. However, looking at taginfo, there is not really any single established value for specifying that unspecified "cards" are accepted

**Comment by FloEdelmann** [comment]
See also https://github.com/streetcomplete/StreetComplete/issues/5097#issuecomment-1609335274
