### ISSUE TITLE
Add a drop-down for switching between presets

### ISSUE THREAD

**Issue by matkoniecz** [streetcomplete/StreetComplete#3228]
At least in my case my initial attempt was to click on the preset name ("Preset: Default") as shown in quest selection menu
![screen01](https://user-images.githubusercontent.com/899988/131369980-5ae62e48-029d-4823-8825-fa9fda364976.png)

**Comment by westnordost** [comment]
Not sure if this is possible (without hack)

**Comment by westnordost** [comment]
But if it is clickable, I think what may be closer to the user expectation would be a popup menu where you can quickly select a preset? (Maybe replacing the selection-mechanism on the "manage presets" page?)

**Comment by matkoniecz** [comment]
> Not sure if this is possible (without hack)

I think it should be, is there any reason why standard solution like #1478 would not work? (I have not looked at code for now! Just wanted to answer question asked on POEditor)

**Comment by matkoniecz** [comment]
> I think what may be closer to the user expectation would be a popup menu where you can quickly select a preset?

At least I would expect regular preset menu... Note the first use when no other presets are existing except default...

**Comment by smichel17** [comment]
Ref: https://github.com/streetcomplete/StreetComplete/discussions/3216#discussioncomment-1247446

What I said in https://github.com/streetcomplete/StreetComplete/issues/3034#issuecomment-880043722 still holds, I'm willing to implement something like I describe there (or https://github.com/streetcomplete/StreetComplete/issues/3034#issuecomment-880513976).

Due to the way the settings are constructed, there's no *easy* way to add a click listener to the {sub}title text. All settings screens are under a single [`FragmentContainerActivity`](https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/FragmentContainerActivity.kt), so they all use the same [layout](https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/res/layout/activity_fragment_container.xml) which includes a generic [toolbar](https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/res/layout/toolbar.xml) as the actionbar/appbar/whatever-Google-wants-to-call-it-now-bar. Compared to https://github.com/streetcomplete/StreetComplete/pull/1478 where there was a unique layout for that screen. Of course it's _possible_ to refactor, it's just more work.

**Comment by mnalis** [comment]
While I too agree it would be nice and logical shortcut, I think it is important to **also keep** the current  `...` / `Manage Presets` (it is less confusing for users when all features can be accessed via _standard_ interface too, even when there are other ways).

**Comment by westnordost** [comment]
Hm well, I am a proponent of that there should be **one** way to do something in an app, not several options. See also what @rugk posted in that other issue: https://github.com/streetcomplete/StreetComplete/issues/48#issuecomment-908606005

**Comment by mnalis** [comment]
@westnordost and I would wholeheartedly agree to have only one way to access a feature, **if** the proposed change was to use _standard / well known Android_ interface. But IMHO it is **not** (at least I don't think I've often been in situations when clicking on the text of titlebar of some window produced dropdown selection list). 

Thus I'm afraid it might be **not discoverable** for average user if non-standard way was the **only** way to access the feature.

(I know you don't usually like what-aboutism, but it looks to me kind of like when "two-finger drag" to change tilt in SC is not very discoverable, so we have click-on-compass-icon-to-tilt as extra way to do it)

While I don't feel that having additional shortcut to access some feature is same as adding more preferences (which is what https://github.com/streetcomplete/StreetComplete/issues/48#issuecomment-908606005 talks about - I seem to remember that even Gnome, which the article is based on as do-not-have-much-preferences example, has two ways to access Settings menu - via topright triangle, and via right-click context menu - but I digress) I do acknowledge that it is **preferable to have only one way to access most features**.  

The question is does the non-standard UI warrants that the feature can **also** be accessed via standard UI.

Maybe if non-standard UI was made to look more like regular UI (eg. adding a triangle in menu is it looks like dropdown menu) might help somewhat? (IMHO it still looks too hackish and non-intuitive to new users, and implementation would also be somewhat hackish)

---
Cleaner solution which keeps **_only one way to access  the feature_** would be to **rearrange the UI a litle so it only uses standard Android UI** (even it uses a little more screen estate), like moving Preset name from title to a more standard dropdown element below it. For example see @FloEdelmann mockup in https://github.com/streetcomplete/StreetComplete/issues/3034#issuecomment-880513976 looked fine in that respect to me. (even if you don't want to adopt the rest of suggested changes due to "too much work").

Doing it that way would additionally preserve useful info we previously had in the title (eg. `86 of 111 enabled`), which we lost in current quest preset branch (as it was replaced with `Preset: xxxx` text).

**Comment by Helium314** [comment]
> Doing it that way would additionally preserve useful info we previously had in the title (eg. `86 of 111 enabled`), which we lost in current quest preset branch (as it was replaced with `Preset: xxxx` text).

Actually (for me) the number of enabled quests is shown below the selected preset, so nothing was lost.

**Comment by westnordost** [comment]
Well let's say the preset selector would be a dropdown below the title.

Then, to select the currently active preset wouldn't make sense in the separate screen.

So the only functionality that remains in that screen is to add new presets and delete presets. _(And renaming presets, if anyone is going to implement that. Any takers, @mnalis perhaps; or who proposed that? It's easy to implement, but I decided I spent enough time on this particular feature already. If you guys want improvements on this feature, it would be nice if you showed you are invested in it.)_ Hm well, fair enough, I guess.

Does anyone have any arguments for not moving the current-preset selector into the quest-selection screen?

**Comment by smichel17** [comment]
I maintain my offer to implement the dropdown… (although I'd be happy if @mnalis or @Helium314 wanted to help :wink:)

One question: right now the preset isn't shown unless you have more than one. In the case where people only have one preset, should we hide the dropdown and add an "add preset" option to the overflow menu?

**Comment by westnordost** [comment]
Sure, go ahead! The comment targeted at @mnalis at all was referring to renaming presets.

Yeah, in that case, the dropdown should not be shown. I imagine the "Manage presets" item would remain in the overflow menu. As said, in that screen, one can still add, delete (and rename) presets.

**Comment by smichel17** [comment]
Okay. No promises about exactly when I will get around to this, as I have a couple of other projects on my plate (and am job searching). I will post here when I begin implementation, so it's safe if someone else wants to start on this.

**Comment by mnalis** [comment]
@westnordost sure, I can give it a try at adding `rename` functionality after @smichel17 does the dropdown rewrite (doing complete rewrite myself is waaay above my head, as someone whose only experience in Android programming has been copy/paste so far :smiley:). And of course, I can help with testing.

**Comment by smichel17** [comment]
Adding search terms & clarifying: I plan to add the ability to rename filters when I do this. But still no ETA, and I'm starting a new job this week so my time may be more limited going forward.

**Comment by NotSoImportant** [comment]
Once I had created some presets I noticed I need to see which one is currently selected on the main screen. So could we - maybe only in case not the Standard is selected - have the current profile shown on the main screen (maybe middle top) and be able to quickly change them on a tap?

**Comment by mnalis** [comment]
@NotSoImportant I would also like that very much, but see also https://github.com/streetcomplete/StreetComplete/issues/3827

**Comment by westnordost** [comment]
I'll close this as the quest presets management screen is now directly accessible from the settings menu (not hidden in some context menu within the quest selection screen)

**Comment by NotSoImportant** [comment]
Not sure, but I cannot find this in 48.0
Could you show a screenshot, please?

**Comment by FloEdelmann** [comment]
It will be part of v49, see https://github.com/streetcomplete/StreetComplete/commit/9eee41fc624c3965bc4ff3fec0d69c2d09a7d3f1

**Comment by NotSoImportant** [comment]
V49 beta 
![IMG_20221030_230711](https://user-images.githubusercontent.com/35758921/198903829-714db7a6-8bfc-4b80-962d-1c798d1dcd63.jpg)
