### ISSUE TITLE
Adapt app behavior when power saving mode is enabled

### ISSUE THREAD

**Issue by smichel17** [streetcomplete/StreetComplete#3243]
My phone's battery is old and terrible, so I'm quite sensitive to battery-draining features. StreetComplete in particular is hard on the battery, because it requires turning up the brightness to see the phone outside, uses gps, and frequently accesses the network, at least when auto-upload is enabled. I get a little over an hour of active mapping on a full charge.

The brightness is unsolvable, it's just needed to use the phone outside. Network access has an easy solution (turn off auto-upload and download data in advance). GPS may have room for improvement.

Now that we've dropped support for api<21, we can able to use [`PowerManager#isPowerSaveMode()`](https://developer.android.com/reference/android/os/PowerManager#isPowerSaveMode()) to check whether power saving is enabled. In that case, perhaps we could lower the frequency of gps updates (and maybe *slightly* decrease the accuracy?).

**Comment by westnordost** [comment]
> I get a little over an hour of active mapping on a full charge.

Whoa. I think you should get a replacement battery to be honest.

> PowerManager#isPowerSaveMode() 

Okay, ... I am not sure if this is going to have any effect on the battery though.

So in general: Sure, we can think about looking for features to turn off in power saver mode. But:
- it must not look like a bug if that feature "does not work" then.
- it must be researched what exactly has an effect on the battery

If you would like to dive into that, I'd suggest to first look at disabling the compass (sensor).

**Comment by Helium314** [comment]
In my experience lowering GPS frequency has more than just a slight effect on GPS accuracy, but this might heavily depend on the phone model.
Generally I have the impression that GPS only has a small effect on power consumption, but out of interest I just started a small test that should find some effect: SC with GPS on vs SC with GPS off, just being idle.

Switching to the dark theme was a massive improvement for me, the phone definitely gets less warm. Of course this only helps for OLED displays.
Disabling auto-upload also helps a lot: data connection is used much less and CPU load is reduced (if I remember correctly from my v32 tests,  quests are generated on solving _and_ on uploading)

Maybe auto-download could use smaller areas in power save mode, but when moving a lot it might make things worse.

**Comment by mnalis** [comment]
For OLED, special theme where majority of screen is totally black (RGB `#000000`) instead of just "dark" might yield even more improvements, so you might want to play with that.

Disabling auto-rotation of map might help somewhat with CPU/GPU usage too.

But I must say I'm not a big fan of using auto-detection of system settings for this purpose -  better to make if SC-specific preference if your testing shows that it is worthwhile. Because, I usually enable system-wide powersaving mode, and then exclude StreetComplete / OsmAnd from it **exactly** so I would get maximum runtime when mapping (so email, RSS, chat programs, all of android syncers, and all others zillions of programs are disabled from running in background and especially from trying to use data) and thus get all the features from GPS mapping apps.

And `isPowerSaveMode()` looks to be system-wide; I don't know if there exist per-app power-save detection (especially one that isn't tied to specific manufacturer!) which could be used instead.

---
Unreleated for this suggested SC improvement, but related to your use case specifically, if possible I would suggest pre-downloading all area you are going to map while on charger, and then completely disabling android mobile data. 
That helped me a lot in the past on some phones, as it seems something is always slowly nabbing at the data connection if it exist.

Also, does you phone allows to change screen resolution? If it does, lower resolutions do seem to use less power.

**Comment by smichel17** [comment]
I am going to convert this issue to a discussion, since:

- It needs more research about what would be most useful to implement
- I have already volunteered to help with other things and will not get around to this for an indeterminate amount of time  
   and
- It's not even totally clear that reacting to the system setting is desired.

Also I can reply directly to @mnalis' tangent about my phone without disrupting the flow of the main conversation :)
