### ISSUE TITLE
Check for crossings when a path meets but does not cross a road

### ISSUE THREAD

**Issue by arrival-spring** [streetcomplete/StreetComplete#3245]
With the changes introduced from #3205, would it be suitable to also ask for case '4' (second row on the left) of here:
https://github.com/streetcomplete/StreetComplete/issues/398#issuecomment-868544484
? i.e. when a path meets a road but does not cross it

When a path meets a road, there is often a crossing. Most often in urban environments and where there is a pavement (sidewalk) on the other side. Not sure f it's easy to check for the latter though.

**Comment by westnordost** [comment]
So, this case

![image](https://user-images.githubusercontent.com/4661658/132040472-305ae270-51d2-4c14-9940-90a5a567c88e.png)

Hmm to be honest, the implementation is quite complex, I don't want to change anything here for now. I am not sure if it can be cleanly separated from this case:

![image](https://user-images.githubusercontent.com/4661658/132040653-278f9c31-3703-4aea-8906-d55ef9edb0c6.png)

**Comment by arrival-spring** [comment]
Yes, that's the case I meant.

I wonder how common that other case is? But I suppose that also in that case in an urban situation with pavement on the other side, there could well be a crossing.

This new quest is catching lots more crossings as is, which is great, so fair enough not wanting to change it much now

**Comment by westnordost** [comment]
It would enormously simplify the code though if it is not checked for crossing the road anymore. On the other hand, I think some/many situations exists where there is a (foot and cycleway) path that branches of a street and the kerb is lowered at that position.
But it is not lowered at this position because there is a crossing, but it is lowered so that cyclists can enter this path from the street and so that service vehicles (gardeners etc.) can enter the path.

So in cases like these, the app would still add `highway=crossing` to the node, which is considered as incorrect by some (because it is not an "official" crossing).
