### ISSUE TITLE
Background Map not updating unless i reinstall

### ISSUE THREAD

**Issue by joshinils** [streetcomplete/StreetComplete#3260]
I have added separate sidewalks, they did not show up in the map, quests for kerb etc. however did.

**How to Reproduce**
Look at portion of map in SC without a future (to-be-added) sidewalk,
add a separate sidewalk way to OSM,
look at map in SC again (even after a week), the sidewalk is not visible,
delete SC, reinstall SC, look at same portion of map with new sidewalk, which is now visible.

Separate sidewalks I added yesterday are not visible after the re-install, i do not know how long it takes for SC to show new data on the map.
Quests for the sidewalks I added yesterday are already there, though.

I did delete my cache in the settings, that did not update the underlying map, only the re-install did.

**Versions affected**
v33.1

**Comment by joshinils** [comment]
to be fair, it may just be that I am too impatient, but i did not find any other issue regading this. maybe a bit of info on how fast the displayed map shows new ways could help here.

**Comment by Helium314** [comment]
If you scan for quests manually (menu -> scan for quests here) the map should be updated. But deleting cache should also help...
If you delete the cache in in the Android app settings, map will be deleted too and thus freshly downloaded.

(I just had to think of @smichel17's comment https://github.com/streetcomplete/StreetComplete/issues/3235#issuecomment-910150758, it's definitely happening)

**Comment by mnalis** [comment]
@Helium314 I think (I could be wrong, but see #3256) that `Scan for quests here` currently only updates the quests, and **not** the Jawg base map, so it won't help. 

One could go to `Android system Settings` / `Apps` / `Apps` / `StreetComplete` / `Storage`  select `CLEAR CACHE` instead of uninstall/install, I think - see https://github.com/streetcomplete/StreetComplete/issues/3133#issuecomment-899877608. (the exact menus might differ by manufacturer and Android version, of course)

**Comment by westnordost** [comment]
> Separate sidewalks I added yesterday are not visible after the re-install, i do not know how long it takes for SC to show new data on the map.
>Quests for the sidewalks I added yesterday are already there, though.

Yeah, the map simply needs some time before it is updated.

**Comment by joshinils** [comment]
> If you scan for quests manually (menu -> scan for quests here) the map should be updated. But deleting cache should also help...

That's what I meant, my android is set to German, so I had to haphazardly translated. 

> One could go to `Android system Settings` / `Apps` / `Apps` / `StreetComplete` / `Storage` select `CLEAR CACHE` instead of uninstall/install, I think - see [#3133 (comment)](https://github.com/streetcomplete/StreetComplete/issues/3133#issuecomment-899877608). (the exact menus might differ by manufacturer and Android version, of course)

Thank you, that is much easier. Now some of my new sidewalks appear at some zoom levels and looking at some locations and disappear upon zooming in, I guess expected since they are new.

**Comment by HolgerJeromin** [comment]
even easier:
Long press on the app icon on the launcher or app list. Click on the `(i)` or `App-Info` (at least on my motorola android 10). Then the known `Storage` => `clear cache`

**Comment by mnalis** [comment]
> Long press on the app icon on the launcher or app list. Click on the (i) or App-Info (at least on my motorola android 10).

That is nice option if it exists, but I'm afraid it is heavily dependent on specific manufacturer UI and launcher used... I remember seeing that on previous phones, but for example neither my stock Xiaomi (MIUI 10, Android 6) nor stock Huawei (EMUI 11, Android 10) offer that shortcut. 

(in MIUI long-press enables moving of icon to rearrange screen, including drag&drop to `Uninstall` placeholder only, and on EMUI long-press offers only `Uninstall`  - and even that only if screen is unlocked, otherwise you only get `Screen is locked` message on long-press). 

One could install different launcher I guess, if this shortcut was often needed... But still it only solve some percentage of cases (when StreetComplete has cached old version, but Jawgmaps has **already** updated a tile - a process which is also not instantaneous)

**Comment by smichel17** [comment]
> when […] Jawgmaps has **already** updated a tile - a process which is also not instantaneous

Does SC have any way to tell when tiles are updated? e.g. an etag response when we retrieve them

**Comment by mnalis** [comment]
Although people did report in https://github.com/streetcomplete/StreetComplete/issues/3124#issuecomment-894569422 that they required to clear ALL DATA (not just CACHE) in order to force tiles to redownload...

@smichel17 I'm not sure if StreetComplete has much control about how Tangrem-ES (which handles tiles) works, see https://github.com/streetcomplete/StreetComplete/issues/3256#issuecomment-913218990

**Comment by Helium314** [comment]
> Although people did report in [#3124 (comment)](https://github.com/streetcomplete/StreetComplete/issues/3124#issuecomment-894569422) that they required to clear ALL DATA (not just CACHE) in order to force tiles to redownload...

Tiles are stored in [internal storage]/Android/data/de.westnordost.streetcomplete/cache/tile_cache. If the tiles don't exist in the tile cache, they can't be shown (and will be downloaded).
If there are Android versions that don't delete the tile_cache folder when clearing cache, then it's a bug of Android.

**Comment by smichel17** [comment]
@mnalis Yes, but on manual download there's some info at least

https://github.com/streetcomplete/StreetComplete/blob/5086daf6234a86fd69099b79ab9e1492c4aab074/app/src/main/java/de/westnordost/streetcomplete/data/maptiles/MapTilesDownloader.kt#L85-L95

**Comment by riQQ** [comment]
@Cj-Malone see my experience as documented in #2479.

**Comment by matkoniecz** [comment]
From https://discord.com/channels/413070382636072960/429092644438802432/896889394877853707

> For content relating to my issue, these two buildings I mapped two months ago. 

> Well the usual update method threw an error, but uninstalling and installing the update has got most of the stuff apart from the new areas mapped in the past month.
