### ISSUE TITLE
Searching for quests remove access to already loaded ones

### ISSUE THREAD

**Issue by Scafir** [streetcomplete/StreetComplete#3269]
When searching for quests, all already displayed quests disappear for some time. I find this to be a problem, because in cases of slow internet, I find myself to be stuck often when I could be completing quests that were displayed a few seconds ago. I suspect this might be somehow linked to #2967.

**How to Reproduce**
1. Have a few quests displayed
2. Trigger a quest search (either automatic or manually through "Scan for quests here")
3. The quests disappear some time (a few seconds to ~15s in the worst case) during the search

**Versions affected**
Android 11 (lineage 18.1-20210903-microG-FP2), StreetComplete v33.2

**Suggestion**
Having a list where quests are added dynamically would be awesome, as quests would be available as soon as possible and looking for new quests would never get in the way of existing ones.

**Comment by westnordost** [comment]
This is not solveable. They actually don't disappear but are replaced by the new quests and the view is refreshed. But that refreshing takes some time. Might be solved by #3123

**Comment by Helium314** [comment]
I had a look at this, and I don't think it will be solved with a different map library.

What happens is that once notes are downloaded and persisted, [quests are invalidated](https://github.com/streetcomplete/StreetComplete/blob/a3569b1e8ab787ae5a3e36c1d476b691fc2bb2ea/app/src/main/java/de/westnordost/streetcomplete/data/osm/osmquests/OsmQuestController.kt#L127-L129), which results in quest pins being [cleared and reloaded](https://github.com/streetcomplete/StreetComplete/blob/a3569b1e8ab787ae5a3e36c1d476b691fc2bb2ea/app/src/main/java/de/westnordost/streetcomplete/screens/main/map/QuestPinsManager.kt#L121-L124).
Reloading quest pins may take quite a while, because first quests need to be reloaded from the database. But at the same time the database is busy persisting a lot of downloaded data, and thus loading quests may take a while.

Some ideas what could be done:
* _don't clear pins when invalidating `QuestPinsManager` (as pins will be reloaded anyway)_: this will keep the quests visible during that period, but actually is a mostly cosmetic change, as then loading quests when scrolling or selecting a pin will be slow.
* _don't invalidate quests after downloading notes_: this should work, as quests will anyway be updated a little bit later as part of the download. But the information whether notes were updated as part of a download or because of other user interaction is not available.

**Comment by westnordost** [comment]
> don't invalidate quests after downloading notes: this should work, as quests will anyway be updated a little bit later as part of the download. But the information whether notes were updated as part of a download or because of other user interaction is not available.

Right, so every quest download invalidates all quests twice. However, the download of notes is usually done much earlier than the download of map data + creation of quests, so I am not sure if this would make things really any faster.

**Comment by Helium314** [comment]
Actually invalidation happens only once, and only if notes were updated.

Not invalidating after downloading notes would not be much faster. It only saves querying all quests in view from database once, which is usually rather fast by itself.
But if the timing is right, this query happens during a phase of high database activity and may take quite long to complete. Until it's complete, pins are not updated (which usually means no pins are shown, as pins were cleared as part of invalidate).

So not invalidating should allow the user to answer quests during download by avoiding
> The quests disappear some time (a few seconds to ~15s in the worst case) during the search

**Comment by Helium314** [comment]
Persisting the OSM data only after creating the quests might also help here...
