### ISSUE TITLE
Quest "AddMaxSpeed" does not actually add a speed limit

### ISSUE THREAD

**Issue by Zverik** [streetcomplete/StreetComplete#3281]
I've noticed that on some roads there are just `maxspeed:type=<country>:urban` tags. They have no meaning by themselves, since they describe values in `maxspeed` tags. Which are absent.

Looking at [changeset metadata](https://www.openstreetmap.org/changeset/111056821), I saw "StreetComplete 34.0" and "AddMaxSpeed" quest. And indeed, [the source code](https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/max_speed/AddMaxSpeed.kt#L58) shows that for implicit restrictions, `maxspeed` tag is not set.

So what we get is a quest that looks meaningful for a user, but does not make any meaningful changes to the map.

Could anybody please fix this?

**Comment by matkoniecz** [comment]
See #2450 #2415

Is there anything new not covered by this issues?

> They have no meaning by themselves

AFAIK all ones used bt SC clearly imply maxspeed (though I think that tagging also maxspeed would be nice)

**Comment by mnalis** [comment]
I think this comment summarizes the behaviour (without one having to go down the rabbithole of linked issues): https://github.com/streetcomplete/StreetComplete/issues/492#issuecomment-326080750

**Comment by westnordost** [comment]
The current behavior is deliberate.

`maxspeed:type=<country>:<traffic zone>` is tagged to record the information that the user did not find a maxspeed sign on-site, so in other words that there is no signed speed limit on the given road. There is no tag like `maxspeed:signed=no` for that and StreetComplete doesn't invent new tags. So `maxspeed:type` is used for that.

The app doesn't make its users input the speed limit if it is unsigned manually because this would require its users to know the [local traffic laws regarding default speed limits](https://wiki.openstreetmap.org/wiki/Default_speed_limits) to contribute **any**  speed limits (also signed ones).

The app also doesn't try to automatically infer the implicit speed limit and tag `maxspeed` itself because `maxspeed:type=<country>:<traffic zone>` is up to interpretation for data consumers, not editors. If an editor would add this kind of information automatically, it could be considered a mechanical edit, which StreetComplete also doesn't do. The app always only tags exactly what the user reported what he saw on-site and doesn't try to be "smart".

**Comment by westnordost** [comment]
> They have no meaning by themselves
> So what we get is a quest that looks meaningful for a user, but does not make any meaningful changes to the map

Also, I'd disagree here. Not only can the maxspeed be inferred from that by data consumers (so, some may say that tagging an explicit `maxspeed` here is duplication), in which kind of traffic zone a road is located is in itself meaningful. Data consumers may use this information to best-guess other properties of a road (if it is not tagged), such as
- whether a road is lit (roads outside of settlements are usually not lit)
- whether it has a sidewalk, a cycleway, a bicycle lane (same)

This information thus can in turn be used by StreetComplete itself, so that the app does not ask for every single country road whether it has a sidewalk or not, for example, because the app should only ask questions where there is a reasonable chance that the answer will not always be the same.
