### ISSUE TITLE
Tactile paving spam

### ISSUE THREAD

**Issue by smichel17** [streetcomplete/StreetComplete#3294]
Recently (since some time this year, I don't remember exactly when) I've been seeing a lot more tactile paving and curb quests. I'm not sure if this is because of a change to the app, someone in my area doing more satellite mapping, or both. In some cases, though, this quest is asked far too much.

In a (semi-)rural area, there are never going to be tactile pavings where a driveway crosses a sidewalk. Okay, *maybe* if we're talking about a house in/near the center of town, but even then I'd be surprised. Here's one example: https://www.openstreetmap.org/note/2857706. Consider this picture attached to the note (and see #3293 for why it isn't):

![35b75a25-fb7f-4d8a-b295-d042c45e8911](https://user-images.githubusercontent.com/6563664/133868172-7463a099-9a4e-4377-9a0f-8fb47a7ae426.jpg)

This one happens to be mis-mapped: it's a walking path, not a driveway. I just didn't realize that when I was mapping. But if you open this location in SC, you can see a row of quests like it, on correctly-mapped driveways.

**Proposed Solution**
At the very least, we should not ask when a walking path crosses a driveway which is off of a `highway=residential`. Or perhaps we can widen that to exclude any path crossing a driveway (this would simplify the filter).

**Comment by matkoniecz** [comment]
Do you think that excluding crossings on `service=driveway` would be enough?

And yes, it appears that someone mapped driveways, with crossings - see https://www.openstreetmap.org/node/8830730760/history

**Comment by westnordost** [comment]
I think iD suggests adding highway=crossing also for driveways. This,  this tagging is found in the wild.

Am 18. September 2021 08:30:49 MESZ schrieb Mateusz Konieczny ***@***.***>:
>Do you think that excluding crossings on `service=driveway` would be
>enough?
>
>And yes, it appears that someone mapped driveways, with crossings - see
>https://www.openstreetmap.org/node/8830730760/history
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/streetcomplete/StreetComplete/issues/3294#issuecomment-922213436

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by Helium314** [comment]
Yes, iD automatically adds crossings when connecting roads and paths via the "connect the features" solution of detected issues

**Comment by smichel17** [comment]
@matkoniecz I think that would be enough. I don't know if it would be too much; maybe there are some driveways in urban areas which have tactile pavings on the crossing? I can only say for sure that it would not happen in a residential area. Overall I think it would be fine to exclude crossings on `service=driveway` and then if it turns out they are useful in some places, we can add the more advanced filter to re-enable those quests.

**Comment by Helium314** [comment]
Are those crossings even "real" crossings?
I usually wouldn't call them crossing, and I often see notes of other SC users claiming there is no crossing.

But OSM tags sometimes are different from common use of the word...

**Comment by westnordost** [comment]
No of course they are no real crossings in the common sense of the word.

 Exception may be e.g. the crossing of a sidewalk with a military base, industrial estate or similar large property where the entrance road is tagged as highway=service an indeed has no raised kerb towards the public road.

But alas, as far as I know,  there is no way to tag a crossing of a footway with a roadway as "not a real crossing" / "raised kerb towards the public road"

We have to work with the data as it appears in the wild.
I think this situation is often tagged as an unmarked crossing. 

Am 18. September 2021 13:07:54 MESZ schrieb Helium314 ***@***.***>:
>Are those crossings even "real" crossings?
>I usually wouldn't call them crossing, and I often see notes of other
>SC users claiming there is no crossing.
>
>But OSM tags sometimes are different from common use of the word...
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/streetcomplete/StreetComplete/issues/3294#issuecomment-922260254

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by Helium314** [comment]
> But alas, as far as I know, there is no way to tag a crossing of a footway with a roadway as "not a real crossing" / "raised kerb towards the public road"

Here I think the question is whether such a non-crossing is ok in OSM and SC should just ignore crossings with driveways, or whether they actually aren't crossings and thus shouldn't be tagged as such.
In the latter case probably the crossing tag should be removed and SC could be used to find such wrong tagging.

**Comment by westnordost** [comment]
> whether they actually aren't crossings and thus shouldn't be tagged as such.

You are German, aren't you? In the frame of the "Is there a crossing here?" (Renamed to "Are there kerbs here? What type?") quest, I kicked off this discussion in June: https://forum.openstreetmap.org/viewtopic.php?id=73140

Long story short, many German forum users at least think that vertices at the situations you described should not be tagged with anything since they are not real crossings. In fact, not only crossings of footways with service roads / driveways but any crossings of footways with any roads that are neither marked nor have some kind of physical structure present that make it obvious that it is a dedicated  crossing (signs, traffic calming, lowered kerbs, ...)

But also long story short, looking at how `highway=crossing` + `crossing=ummarked` specifically is used in the wild disagrees with that view, especially in areas where it is common to always map sidewalks as separate ways (where thus at every intersection, there are 4 `highway=crossing`s). 
This kind of tagging is pushed by the iD validator's behavior to add `highway=crossing` to such nodes. https://github.com/openstreetmap/iD/issues/8463

So in any case, whatever the original meaning of `highway=crossing` was, due to vague documentation and a liberal interpretation of the definition being pushed by iD, data consumers must expect that `highway=crossing` is also tagged on intersections of footways with driveways and this is what counts.

---

One solution might be to not ask for crossing properties for `highway=crossing` nodes that are on a `highway=footway + footway=sidewalk` because that would be an indicator that this is not a real crossing:
- sidewalks are mapped separately, but
- the section in question is not tagged as `footway=crossing` as should be the case for "real" crossings 

But on the other hand, the smarter StreetComplete filters these out, the smarter any other data consumer would need to filter these out as well. A better solution would be if it was possible to somehow tag them as "not real crossings". Offering to delete the `highway=crossing` in case of such situation can however not be the solution as long as iD has this behavior.

**Comment by matkoniecz** [comment]
> the section in question is not tagged as footway=crossing as should be the case for "real" crossings

Note that it is relatively common to have `highway=footway` sidewalks are mapped separately without `footway=sidewalk` or `footway=crossing` tags.

**Comment by smichel17** [comment]
> the smarter StreetComplete filters these out, the smarter any other data consumer would need to filter these out as well. A better solution would be if it was possible to somehow tag them as "not real crossings".

`highway=crossing` + `crossing=imaginary`? :D

An alternative solution would be to split StreetComplete's OSM filtering logic (e.g. `Crossing.isImaginary()`) out into a general purpose library which other projects can use. If it's pure Kotlin, it would compile to enough targets that it could be widely used. But it's more work and _perhaps_ less sustainable long-term.
