### ISSUE TITLE
Arabic/Persian font

### ISSUE THREAD

**Issue by Ahmadhosseinbor** [streetcomplete/StreetComplete#3303]
Use **Vazir** Persian font instead of the default font for Persian, Arabic, Urdu, etc.

**Comment by matkoniecz** [comment]
1) Is it [this font](https://github.com/rastikerdar/vazir-font)?

2) I am not sure is it possible to do language-based fonts in Tangram

**Comment by westnordost** [comment]
Why?

**Comment by westnordost** [comment]
You liked your own post, @Ahmadhosseinbor

**Comment by westnordost** [comment]
Closing based on past unresponsiveness of this user (all his tickets mostly consisted of just one sentence and were closed because they were duplicate, so he was also not willing to search the issue tracker).

Ahmadhosseinbor , in the future, we will close any feature request you create unless you create a proper description for it, including elaborating on your use case and why you think this feature would help you.
