### ISSUE TITLE
New building type: Sauna

### ISSUE THREAD

**Issue by vranki** [streetcomplete/StreetComplete#3322]
**Use case**

In Finland's residential areas and lakesides there are a lot of private sauna huts. In some areas almost 
every house has one. Currently there is no building type for it and saunas are left unmapped.

**Proposed Solution**

Add new building type "Sauna". This could be enabled only in countries where saunas are popular (Finland, Sweden, Estonia, Russia..).

Typical Sauna building: https://www.karhunpiilo.fi/wp-content/uploads/2018/11/saunarakennus.jpg

Icon could be a hut with a smoke stack and a bath broom. Typical bath broom image:
https://www.rakentaja.fi/artikkelit/img/200611/637.jpg.pagespeed.ce.A0jfFCNSY3.jpg

Tag for the building should probably be leisure=sauna (https://wiki.openstreetmap.org/wiki/Tag:leisure%3Dsauna)

**Comment by westnordost** [comment]
Looks like a cabin

**Comment by mnalis** [comment]
I agree that it looks like [building=cabin](https://wiki.openstreetmap.org/wiki/Tag:building%3Dcabin). 

To explain @vranki: `Building type` quest, as asked in StreetComplete and documented at [building=*](https://wiki.openstreetmap.org/wiki/Key:building), is (_somewhat confusingly_) **not** about actual building use. It is more about architectural type of building, as seen from outside, if such explanation helps - eg. `building=greenhouse` is half-cylindrical reinforced plastic/glass looking "building", while `building=cathedral` is tower-like ornamented structure (even if it is currently being used as a pub!), etc. 

There is additional [building:use](https://wiki.openstreetmap.org/wiki/Key:building:use) key as well as various `amenity`, `shop`, `leisure` etc.  for defining what is the **actual current use of that building**, but as it is actually not a good idea to tag building polygon itself with its use (preferred method is to put a use as a node inside or on the building outline, as it avoids ambiguity when tags that can apply to both the building and amenity inside it are present - like [start_date](https://wiki.openstreetmap.org/wiki/Key:start_date) for example), StreetComplete in general does not ask for **_use of the building_**.

If you want to map missing elements (like missing shop, or missing sauna, etc), you can use long-press in StreetComplete to leave Notes with pictures, but StreetComplete only adds/improves tags on existing elements, and can not create new elements for amenities/shops/leisure etc. 
Alternatively, you can use some other editor like [Vespucci](https://wiki.openstreetmap.org/wiki/Vespucci) if you want to be able to create new elements yourself instead of just leaving Notes.

**Comment by matkoniecz** [comment]
> If you want to map missing elements (like missing shop, or missing sauna, etc), you can use long-press in StreetComplete to leave Notes with pictures

note that it should be done only after you verified that it is not mapped already - StreetComplete will not mention or show (for now) any saunas - also mapped ones - or a fully tagged shop. StreetComplete will show buildings on maps but it does not mean that shops/saunas/POIs are mapped or not mapped

**Comment by vranki** [comment]
Maybe this would involve adding a new building key for saunas then? They are structurally different from cabins and they cannot be converted to other use in sane amount of work. I'd compare them to for example garage type building which is also different than hut or cabin, although may look like one.

Here is a indoor photo of a typical sauna hut https://img.ilcdn.fi/4fj4fMLBA03UUb5xxxeKBXQU0QE=/full-fit-in/612x0/img-s3.ilcdn.fi/d2c7ef6653dae0b48c524ca5553cfaee5e3f51b2c2c6e0bcb6a96bcef5052a2d.jpg

I'm not expert on tagging as you see, but fact is that there are lot of saunas in some areas and currently they are pain to map.
There are also lot of saunas inside residential buildings and cabins. For them adding a new node with amenity=sauna sounds like correct way and that's what I've been using. This issue is about buildings that are specifically built as saunas.

**Comment by matkoniecz** [comment]
I am not very familiar with saunas and not sure should it be treated like garage - but for now usage seems really low https://taginfo.openstreetmap.org/tags/building=sauna

BTW, I am also a bit frustrated by lack of entry for 

![external-content duckduckgo comb](https://user-images.githubusercontent.com/899988/134886886-1fe20f32-a005-4f45-8152-719de3a931af.jpeg)
![external-content duckduckgo coma](https://user-images.githubusercontent.com/899988/134886893-7f0ec6a5-720f-4666-967f-1bcfb944b642.jpeg)
![external-content duckduckgo com](https://user-images.githubusercontent.com/899988/134886899-4eb2147e-930c-40f0-b677-d4f9e1a7f21e.jpeg)


but usage is also really low https://taginfo.openstreetmap.org/tags/building=trash_shed


the same for
![Guard_booth_20190426_135110](https://user-images.githubusercontent.com/899988/134886483-fdfb77ac-116f-4da2-97fe-06ee21f39945.jpg)


https://taginfo.openstreetmap.org/tags/building=guard_shed


So if that are distinct building types for now I would leave notes

**Comment by westnordost** [comment]
If there wasn't trash inside, it would just be a shed.

Anyway if there is a sauna on private property, it shouldn't be mapped at all as leisure=sauna or whatever.

**Comment by matkoniecz** [comment]
> If there wasn't trash inside, it would just be a shed.

not really, there would be still extremely strong ventilation - unlike in regular sheds (but maybe it is only local distinction and elsewhere it is common to use nonsolid shed also for other purposes)? Like this one?
![external-content duckduckgo com](https://user-images.githubusercontent.com/899988/134890273-7fb62da8-0fb0-48e4-94bc-144958b5bac3.jpeg)

**Comment by westnordost** [comment]
A shed is not defined by its ventilation.

**Comment by westnordost** [comment]
The depictured shed could easily be a bicycle shed

**Comment by matkoniecz** [comment]
> The depictured shed could easily be a bicycle shed

Could thing too now, in such case I will just tag that as `building=shed` in future

**Comment by westnordost** [comment]
Well so anyway, I'll close this.
