### ISSUE TITLE
What kind of cycle barrier is this?

### ISSUE THREAD

**Issue by ygra** [streetcomplete/StreetComplete#3361]
### General
Affected tag(s) to be modified/added: [cycle_barrier](https://wiki.openstreetmap.org/wiki/Key:cycle_barrier) 
Question asked: **What kind of cycle barrier is this?**

Basically similar to the question about bollard type.

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/wiki/Adding-new-Quests-to-StreetComplete)):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary
  - Sometimes answerable from aerial imagery as well, but that doesn't necessarily preclude asking here.
- [x] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
  - `double` is perhaps the most common one, but there are still other options
- [?] 🕓 Applies to a reasonable number of map data (Worth the effort)
  - about 100k instances of `barrier=cycle_barrier`. Is that enough?

### Ideas for implementation

**Element selection:** Nodes on ways with `barrier=cycle_barrier`, but without `cycle_barrier=*`. Possibly similar to how bollards are currently selected for the »What kind of bollard is this?« quest.

**Metadata needed:** Unknown.

**Proposed UI:** Similar to the bollard quest, a selection of options, each with an image (the tag Wiki page has images).

**Comment by kmpoppe** [comment]
Am I misreading the Wiki or has `cycle_barrier=*` not yet been documented, except in this [proposal](https://wiki.openstreetmap.org/w/index.php?oldid=2190485)?

Kai

**Comment by ygra** [comment]
Ouch, I didn't realize the situation around those tags was so dire. Then `cycle_barrier=*` is perhaps less of a problem as it simply states what is visible, instead of a vague intent.

**Comment by smichel17** [comment]
Peanut gallery here: seems like the best way forward would be if someone (not me :P) proposed to deprecate `bicycle=no`, then gradually migrate usages to either `bicycle=dismount` or a new value, `bicycle=forbidden`.

**Comment by ygra** [comment]
I'd probably say that's `triple`. At least for the purposes of the tag, which aims to classify the rough path and number of turns that's needed to traverse the barrier. It is perhaps just a bit friendlier than a 'normal' one in that the handlebars won't snag on the inside (if it's not so narrow inside that it can't be traversed by a bicycle at all). Pedestrians may get away with not following the turns at all and instead use the gap on the left.

**Comment by matkoniecz** [comment]
Feedback welcomed on labels.

First image is survivable but I look for a replacements.

![screen06](https://user-images.githubusercontent.com/899988/140404549-b0f7fa67-5e1d-458b-9f7f-678737aee68a.png)

alternative image for `double` (chicane with two barriers
![barrier_bicycle_barrier_double](https://user-images.githubusercontent.com/899988/140404648-ef9fa189-3df5-4e25-ad21-94989897635e.jpg)
https://commons.wikimedia.org/wiki/File:Pozdawilk_2017(Pasewalk)_(4).jpg)

**Comment by westnordost** [comment]
I think the texts and the images are very good. Both pictures for `double` look ok, maybe the alternative is slightly better

**Comment by ygra** [comment]
Perhaps »diagonal« could use a different text. Something like »at an angle to the path« to emphasize what differentiates it from »double«.

**Comment by riQQ** [comment]
Why not "diagonal to the path"? It's more succinct.

**Comment by ygra** [comment]
I liked the overhead schematics from the Wiki page. Perhaps those could be used or superimposed on the photos to reduce recognizability problems with the photos.

**Comment by matkoniecz** [comment]
> I liked the overhead schematics from the Wiki page. Perhaps those could be used or superimposed on the photos to reduce recognizability problems with the photos.

I was unsure how easy is to interpret that. 

I like maps, schemas, plots and graps and diagrams - and rarely have trouble with interpreting them unless something was really poorly designed. But such kind of thing is surprisingly hard to interpret for many people, and I expect photos to be more likely to work.

**Comment by HolgerJeromin** [comment]
Current quest has
![image](https://user-images.githubusercontent.com/2410353/190348621-423cbdf3-6233-4d8a-b068-45e028fa3256.png)

Where "more than two barriers" is the only one which has no white-red color.
I took 
https://commons.wikimedia.org/wiki/File:Umlaufgitter_Schatten_hoch.jpg
https://commons.wikimedia.org/wiki/File:Umlaufgitter_Sonne_hoch.jpg
and some more https://commons.wikimedia.org/w/index.php?title=Special:ListFiles/Zuse&ilshowall=1

**Comment by westnordost** [comment]
I like them! Would you like to create a PR?

**Comment by HolgerJeromin** [comment]
done

**Comment by HolgerJeromin** [comment]
A problem at https://www.openstreetmap.org/node/7879005619
This is similar to this one, but only blocking half of the street. Will take a photo in the next days.
![image](https://user-images.githubusercontent.com/2410353/191906512-0aff7c86-6fde-46cb-a60b-0fb345100275.png)

The text "passage between two barriers" for `cycle_barrier=single` is very confusing.
![image](https://user-images.githubusercontent.com/2410353/191905978-aafff6ee-7fea-4bfe-9404-70859334802c.png)
The main point is IMO that the barrier has no "depth" which is written in wiki as "where you don't have to go around a chicane".

Better image or text needed?

**Comment by matkoniecz** [comment]
> Better image or text needed?

If you have either: feel free to propose it! Best in form PR but posting new issue with improvement suggestion is also welcome.

In general, if I would have a better idea then I would use it already :)

**Comment by dreua** [comment]
Here is another instance where a user was not sure what to select - I think there are quite a few edge cases which the current tagging scheme can't address. How about changing the text for the first to "Narrow passage"? I think that is the gist of this and @HolgerJeromin 's case as well as the tag "single". It's not about how many barrier parts there are but the way you need to circumnavigate them.

![180922](https://github.com/streetcomplete/StreetComplete/assets/15114715/5d3b3252-1a66-4b12-a371-84da19406b62)

**Comment by mnalis** [comment]
> wide-narrow is a different classification, any of them can have wide or narrow openings.

Yes, but this issue I think is not about that (there are tags on the [wiki](There are some hints on https://wiki.openstreetmap.org/wiki/Tag:barrier=cycle_barrier#How_to_map ) how to map narrowness, which SC doesn't do).

This seems to be only about better text explanation for `cycle_barrier=single`

> I think there are quite a few edge cases which the current tagging scheme can't address

That might be true, but until such cases are defined and documented on the wiki (after wider community discussion), the StreetComplete cannot really tag them, and can only leave notes until then.

> How about changing the text for the first to "Narrow passage"? I think that is the gist of this and @HolgerJeromin 's case as well as the tag "single". 

Perhaps, and we do use similar phrasing for last options (_"narrow passage smaller toward top"_). This might need to be extended how it differs from it in order to not be confusing (otherwise, _"narrow passage"_ would cover both cases, and users often won't read after they find the first match)

> It's not about how many barrier parts there are but the way you need to circumnavigate them.

I'd agree, and also it is somewhat awkwardly named. `cycle_barrier=single` does not mean there is single barrier, nor that there is single direction the bicycle should take (that definition works for single, but fails for double and triple), nor that there is single change of direction (there are 0).

Instead it seems to mean that there is single row  of barriers (perpendicular to direction of bicycle movement). That row can contain two or more barriers themselves.  `double` means there are two rows, and `triple` that there are three. But trying to convey that meaning to the user in few short words is hard.

So, in your picture @dreua  it is complicated because the road ends there. So it could be either `single` (or perhaps even `diagonal`) if user intends to take informal path to the left, or `double` if they intend to take informal path forward.


Also, there are cases like https://commons.wikimedia.org/wiki/File:Fu%C3%9Fg%C3%A4ngerunterf%C3%BChrung_Parkstra%C3%9Fe_(Freising).jpg - is it `single`?

It might seem so to most users, but it also might be considered `double` if we consider _"way you need to circumnavigate them"_, as the cyclist might need to take similar maneuvers if the concrete block on the left was replaced by other metal profile similar to the first.

**Comment by dreua** [comment]
I think the current state really lacks an option for a "narrow" passage between a barrier and another object. I would tag that as "single" because that is what I believe the tag would include. The description "passage between two barriers" is really misleading: It describes the picture but not what the tag means. No offense, this would have happened to me, too, but we should now fix it as the shortcomings become obvious. Call it restricted passage or come up with something better if you have a problem with "narrow".

**Comment by matkoniecz** [comment]
image from https://github.com/streetcomplete/StreetComplete/issues/3361#issuecomment-1845471850 is not described by

> A barrier across the path with a passage where you don't have to go around a chicane.

from https://wiki.openstreetmap.org/wiki/Key:cycle_barrier as you need to go around

(also, comments in old issues are easy to get missed, if there is a problem it is better to create new one if it was not reported as own issue before)

**Comment by matkoniecz** [comment]
In geenral, none of https://wiki.openstreetmap.org/wiki/Key:cycle_barrier clearly fits. I would discuss it at https://community.openstreetmap.org/

**Comment by mnalis** [comment]
> image from [#3361 (comment)](https://github.com/streetcomplete/StreetComplete/issues/3361#issuecomment-1845471850) is not described by

- What I'd probably do is just hide it (i.e. benefit/effort ratio is too low for me for cases that require hard thinking)

- If I was however caring deeply about the situation, or I was encountering it too often (e.g. after re-showing hidden quests in SC), I'd probably leave a note (and then perhaps later add `cycle_barrier=*` and `note=*` explaining it in detail if nobody solved it. And perhaps add a plethora of other documented tags like [maxwidth:physical=*](https://wiki.openstreetmap.org/wiki/Key:maxwidth:physical),  [spacing=*](https://wiki.openstreetmap.org/wiki/Key:spacing), [opening=*](https://wiki.openstreetmap.org/wiki/Key:opening),  [overlap=*](https://wiki.openstreetmap.org/wiki/Key:overlap) if I _really_ cared about it).

- And if I really had to (and I don't see the need really, it's not like that tag is existential) solve it from StreetComplete, I'd tag that picture as `cycle_barrier=double`.  Because, the square-profile red-and-white one is one part, and that `fence_type=chain_link` fence is the other part, _in separate row_ (row closer to the cyclist)

 I.e. if you replace that fence with equivalent another red-and-white square profile of same size and direction, it would clearly be `cycle_barrier=double`. 
  So, to me, `double` would seem to most accurately describe the maneuvers that cyclists would have to make. 

> I think the current state really lacks an option for a "narrow" passage between a barrier and another object

Well, if depends in which "row" is the second barrier: the narrow passage between a barrier and another object could be `single` (if they are on the same row/line perpendicular to the road) or `double` (if they are on two different rows/lines perpendicular to the road). 

**IOW, for any of the StreetComplete pictures you can replace one of the read-and-white metal pieces with a jersey barrier** (or a metal fence, or a hedge, or a natural rock, or whatever) -- **and they would still be the same answer**. Perhaps that could somehow  be clarified in quest if it is confusing?

---

But I agree with @matkoniecz , if there are a lots of such confusing/special-case barriers that you encounter, it might be worth to collect pictures of them @dreua and discuss at https://community.openstreetmap.org/ how they could best be tagged, and then document it at the wiki. After that is done, new StreetComplete issue could be opened to implement that additional community-accepted option.

But if those are one-in-a-thousand kind, then I just wouldn't worry and simply hide them - life is too short. There is no way that SC could offer all possible choices existing (and still remain simple and usable for newbies, which is its primary goal), only the most popular ones - that's why _"leave note"_  answer exists in the first place.

**Comment by mnalis** [comment]
> I.e. if you replace that fence with equivalent another red-and-white square profile of same size and direction, it would clearly be cycle_barrier=double.

e.g. 
![cyclebarrier2](https://github.com/streetcomplete/StreetComplete/assets/156656/bc626205-1121-48eb-ae31-e61d549d3a1a)
