### ISSUE TITLE
Increase contrast of dark theme

### ISSUE THREAD

**Issue by smichel17** [streetcomplete/StreetComplete#3378]
### Use case

Following [these](https://github.com/streetcomplete/StreetComplete/discussions/3251#discussioncomment-1279237) [suggestions](https://github.com/streetcomplete/StreetComplete/discussions/3251#discussioncomment-1279238) for increasing battery life, I tried out StreetComplete's dark theme. Unfortunately, in bright daylight / sunlight it is **not usable** due to low contrast.

The worst offender is the element selection color.

<img alt="screenshot of lit quest in dark mode" src="https://user-images.githubusercontent.com/6563664/137232083-e2a11a9a-6864-4e0d-ad11-e39417a11d23.png" height="500" />

Indoors, it's totally obvious, but in sunlight, it's almost invisible to me.

### Proposed Solution

I think a two-part approach would be good here: both make the selection-orange brighter and the background darker (extra bonus: saves more battery).

Perhaps we could also pull in some changes from @Helium314's fork, as discussed in https://github.com/streetcomplete/StreetComplete/discussions/3003#discussioncomment-959709

#### Question

Just to check— do you agree it would be better to make these changes to the dark theme, vs adding a 3rd, "high contrast dark" theme? I imagine that the current theme looks and works fine at night, and might be more pleasant than a high-contrast dark theme, in that case.

**Comment by matkoniecz** [comment]
And if anyone is interested - this is relatively easy, but time consuming to try various variants.

Most of the style resides at https://github.com/streetcomplete/streetcomplete-mapstyle though element selector is - if I remember well - defined at https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/assets/map_theme/jawg/streetcomplete.yaml#L2

**Comment by matkoniecz** [comment]
Can be done, though main issue ("The worst offender is the element selection color.") would be handled in this repo.

If someone would really want there would be "element selection styling" issue and contrast in general issue. But spending time on making more issues seems a poor idea :)

Especially as https://github.com/streetcomplete/streetcomplete-mapstyle/issues/107 that is already about tweaking contrast (and mentions road) exists already.

> which was never directly answered, but the responses seem to point at trying adjustments first

I would start from improving night mode without considering performance during day and then retest. Tweaking two - even very simple - styles is tricky already, better to do it properly before adding even more.

**Comment by westnordost** [comment]
I'll close this because
- dark theme is not made for the day
- it has pastel colors just as the light theme has pastel colors: Because it is the background map that should not stand out that much. Hence, even a "high contrast" theme would not really make sense
- it is not confirmed that darker colors will actually improve battery life significantly (or at all)

**Comment by smichel17** [comment]
Okay. I have not been mapping all that much as of late, but if/when I return and if I want to re-open, I'll test mapping with a dark theme first (with colors modified enough that I can actually do it during the day, since I rarely map at night) to see if it makes an impact on battery life in actual usage.

**Comment by Helium314** [comment]
> it is not confirmed that darker colors will actually improve battery life significantly (or at all)

Depends on your requirements to confirm...
3 people (including myself) claiming dark mode noticeably improved battery life: https://github.com/streetcomplete/StreetComplete/discussions/4135#discussioncomment-3002208

Anyway, a short test, battery use when leaving the phone on for 1 hour: low birghtness: 6% (theme doesn't matter), 80% brightness: 7% (dark theme), 10% (light theme). Done on S4 mini (OLED display).

**Comment by westnordost** [comment]
That's 3% difference between the screen showing very bright colors and very dark colors.
So, very dark vs very very dark will have almost no effect, but you are welcome to test (S4 mini had OLED? Did that technology even exist back then? )

On August 18, 2022 9:05:18 PM GMT+02:00, Helium314 ***@***.***> wrote:
>> it is not confirmed that darker colors will actually improve battery life significantly (or at all)
>
>Depends on your requirements to confirm...
>3 people (including myself) claiming dark mode noticeably improved battery life: https://github.com/streetcomplete/StreetComplete/discussions/4135#discussioncomment-3002208
>
>Anyway, a short test, battery use when leaving the phone on for 1 hour: low birghtness: 6% (theme doesn't matter), 80% brightness: 7% (dark theme), 10% (light theme). Done on S4 mini (OLED display).
>
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/streetcomplete/StreetComplete/issues/3378#issuecomment-1219842821
>You are receiving this because you modified the open/close state.
>
>Message ID: ***@***.***>
-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by smichel17** [comment]
@westnordost Dark vs very dark is very little effect, but making it darker for darkness's sake is irrelevant to this ticket; it's only about increasing the contrast so it is *possible* to go light -> dark during the day.

@Helium314 The question is not only whether dark theme improves battery life (it does, this is known), but *how much* it improves battery life **relative to other high-battery-drain activities performed by streetcomplete** (gps, network activity, cpu to process data locally). If the other 90% of the battery is drained in one hour of mapping, then an extra 3% is only 1-2 minutes of life. If the battery would last 3 hours of mapping, then it's 9% saved, which would add an extra 15-20 minutes.

**Comment by Helium314** [comment]
> Did that technology even exist back then?

My first OLED device was a Nokia N85 from 2008, so definitely yes.

> how much it improves battery life

It definitely does have a noticeable effect. This is why I switched to dark mode initially. It was the difference between the phone getting noticeably warm or staying cool.
Also note that outdoor usually the brightness is 100%, and not ~80%. I did the tests below maximum brightness because I noticed some burn-in in areas that permanently remain white (i.e. the buttons) and now limit the brightness of my device to ~80%. And I don't want to make things worse by just leaving the screen on maximum for some test.

@thany you said that "darkmode does indeed help battery usage". Do you have some estimate how much?

**Comment by thany** [comment]
@Helium314
It's really hard to tell, because is depends massively on:

* Type of screen - OLED benefits the most, and fortunately it seems to be the way forward. But there's also Quantum Dot and similar technologies that also benefit.
* Size of the screen
* User's preferred brightness
* Resolution - more pixels means each pixel need to emit more light to develop the same overall perceived brightness.
* Colours chosen in the app - blue is perceived brighter than red, for example.

And probably a few more 😀

Safe to say, a darker screen does indeed help, but one can only reliably measure the difference between light mode and dark mode when doing so on a single device, with a constant set of user preferences. And for that, I personally haven't done any measurements, but it shouldn't be too hard to find some professional research on this matter.

**Comment by Helium314** [comment]
One more test: 100% brightness, light theme: 14% in 1 hour.

And since I noticed that the phone can measure battery drain (although power fluctuates a lot, so results are very approximate):
min brightness: ~500 mW
max brightness, dark theme: ~650 mW
max brightness, light theme: ~1100 mW

> shouldn't be too hard to find some professional research on this matter.

Good idea, some links:
Pixel: https://www.techspot.com/news/77340-dark-mode-saves-lot-phone-battery-life-google.html
Moto-X: https://www.greenbot.com/article/2834583/how-much-power-does-a-black-interface-really-save-on-amoled-displays.html
Multiple devices: https://www.purdue.edu/newsroom/releases/2021/Q3/dark-mode-may-not-save-your-phones-battery-life-as-much-as-you-think,-but-there-are-a-few-silver-linings.html

**Comment by westnordost** [comment]
Improving the dark theme colors can certainly be done,  and one thing that can be done is to increase contrast.  However,  it should not end up like those "high contrast" schemes in Windows, it should still look esthetically. Note that the map is supposed to be a background map, just like the light theme, i.e. use slightly pastel colors.

Also, using a #000000 black for the map background is difficult for the same reason why using it for the UI background is difficult: Dialogs in Android, when they pop up,  darken the background and have IIRC a black shadow to stand out from the rest.  If the background is already black, it looks like the dialog is not really floating above which looks weird and wrong. 

It is not possible to change the color of the shadow or the color of the darkening. (E.g. in iOS, issued of darkening,  it blurs the background).

Anyway,  proposals to change the colors should better be done in the repo for the mapstyle.

**Comment by Korb** [comment]
This **design** bug has nothing to do with the battery life of AMOLED screens or the applicability of a particular color theme during the day or night. There is a violation of the `Web Content Accessibility Guidelines` regarding accessibility:

**Buildings**:
> Foreground: `#295B5C`
> Background: `#363054`
> Contrast ratio: 1.608:1
> 1.4.11 Non-text Contrast (AA)
> ❌ Fail for UI components and graphical objects

**Roads**:
> Foreground: `#555699`
> Background: `#363054`
> Contrast ratio: 1.861:1
> 1.4.11 Non-text Contrast (AA)
> ❌ Fail for UI components and graphical objects

---
> Especially as [streetcomplete/streetcomplete-mapstyle#107](https://github.com/streetcomplete/streetcomplete-mapstyle/issues/107) that is already about tweaking contrast (and mentions road) exists already.

>  This repository was archived by the owner on Aug 14, 2024. It is now read-only.

**Comment by matkoniecz** [comment]
> This repository is obsolete. StreetComplete changed its map renderer from tangram-es to MapLibre-native. Development continues in the [repository of the MapLibre map style definition](https://github.com/streetcomplete/maplibre-streetcomplete-style)

https://github.com/streetcomplete/streetcomplete-mapstyle

**Comment by matkoniecz** [comment]
if problem still exists it may make sense to report it there at new repo

personally I am not using night mode, nor planning to use night mode, nor planning to support it as a hobby and I would be OK with it being removed
