### ISSUE TITLE
Improve opening/emptying times picker

### ISSUE THREAD

**Issue by Emilius123** [streetcomplete/StreetComplete#3401]
The current time-picker dialog for opening/emptying hours seems to not be intuitive. I have personally seen many people fail at correctly inputting the times.

While the Android Timepicker in itself is a thing that should be fixed sometime, the problem seems to lie in the way, StreetComplete asks for the times:

1. What days of the week is this open? -- Many will select all days the place is open, even if the times itself are different
2.  When does this open and close? -- Even if the days were given correctly, most will just give the times of total opening and total closure, not including any breaks that might have been.

Adding the times totally correctly is just too complicated, most users might not even notice the "Add opening hours" button.

While this problem might be solved in many ways, my suggestion would be to use a grid-like system, just as the [JOSM OpeningHoursEditor](https://wiki.openstreetmap.org/wiki/JOSM/Plugins/OpeningHoursEditor) does:
![image](https://user-images.githubusercontent.com/47276235/137646923-803afd14-76db-45c4-abe9-c9846fa17cbe.png)

Even if not by default, such a system would probably be very desireable for some.

**Comment by matkoniecz** [comment]
> The current time-picker dialog for opening/emptying hours seems to not be intuitive. I have personally seen many people fail at correctly inputting the times.

Interesting. I am in middle of UX testing and I identified some problems (see say #3364  #3394 #3341) but - to my surprise - people had no problem with opening hours interface.

I wonder what is the cause of difference, I was not expecting significant cultural impact here.

> What days of the week is this open? -- Many will select all days the place is open, even if the times itself are different

Some run into it initially but - again to my surprise - they figured out how to fix it.

> When does this open and close? -- Even if the days were given correctly, most will just give the times of total opening and total closure, not including any breaks that might have been.

In place where I was testing it such places are really rare so I had no opportunity to see it in action.

> While this problem might be solved in many ways, my suggestion would be to use a grid-like system, just as the JOSM OpeningHoursEditor does:

That is not feasible due to screen size.
