### ISSUE TITLE
Switching from network location to precise location draws long trace

### ISSUE THREAD

**Issue by ltog** [streetcomplete/StreetComplete#3484]
Since recently SC draws a blue trace where you have been. When location detection switches from network location to precise (GPS) location (not sure if these are the correct names), then a long line is drawn from one location to the other. I propose to not draw the trace when using network location or at least not draw the trace when switching from network location to precise location (and vice versa).

**How to Reproduce**
Open SC indoor (with bad GPS reception), make sure your (network) location is drawn, then move outside and wait for GPS reception.

**Versions affected**
SC v37.0, Android 10

**Comment by matkoniecz** [comment]
Hmmm, is it even detectable by app that it happened?

Note that there are many cases where such quick jump in a reported location should not cause gap in displayed path.

**Comment by mnalis** [comment]
I also think it would not be easy/possible to detect such cases (eg. entering and exiting the tunnel should continue the track)

Anyway, it should not be a big deal, as the GPS track will fade away in a minute or two anyway.

**Comment by matkoniecz** [comment]
> the GPS track will fade away in a minute or two anyway.

AFAIK it is staying for longer.

**Comment by mnalis** [comment]
Hmmm, now looking at it, it feels like waiting for teapot to boil :smile:, it does not seem to change **at all**. And I quite vividly remember it disappearing quite fast before...

Perhaps it depends not on a time, but on number of acquisition points, or distance moved, or some other factors?

**Comment by matkoniecz** [comment]
> it will be deleted when you close StreetComplete (including clearing it from recent apps).

#3400

**Comment by smichel17** [comment]
I've experienced something similar, even when only using gps, since I use "gps only", vs "high accuracy", which combines gps and network based location data. Especially at the beginning when a fix is just being acquired, there is often awkward drift.

As a compromise: what if sufficiently large or low-precision jumps were shown with a dotted line? So, this would include entering and exiting a tunnel. I actually think that's correct behavior, since the app can't be sure exactly what path you took (unless it snapped to roads in the case of a tunnel, but I'm not proposing that!).

**Comment by westnordost** [comment]
@mnalis 

When you send the app to background and get it back in foreground, the "old" track is displayed with much less alpha.

When you end the app and start it anew, all the previous tracks are cleared.

**Comment by westnordost** [comment]
Regarding the ticket:

It is actually easy to find out from which provider the location has been supplied. However, as noted before, even if no location provider change occurs, the accuracy can vary a lot.

But fret not, it is actually easy to find out the accuracy of the location as well. So the solution I find is the best is to ignore locations returned by a location provider with an accuracy below X. And this is how it is currently solved:
 If the [accuracy](https://developer.android.com/reference/android/location/Location#getAccuracy()) of the location is more than 20 meters, the location is ignored for track-drawing. I don't see what can be improved here.

**Comment by smichel17** [comment]
When using gps only, the first fix is least accurate, and then it gradually gets better. In my experience with this, the line starts to be drawn too early; I would prefer if the accuracy threshold were lowered. However, I've never had a problem with it past the initial fix. I'm not sure if that is because the accuracy is high enough, or because the "drift" behaves differently at the start.

In any case, my earlier proposal was to draw a dotted line when accuracy is less than X and a solid line when it is less than Y. I'm not sure what the exact values of X and Y should be.

It might also work just to lower the threshold slightly (18 meters?), or to add a lower threshold (15m?) just for the very first fix, like speaking-detection in voice chat programs:
![image](https://user-images.githubusercontent.com/6563664/140439568-c83fa1bb-d214-4edb-bc15-4940b4df8508.png)

**Comment by mnalis** [comment]
I'd be vary of lowering the general threshold below `20m`- in cities (and especially if there are high buildings) the accuracy suffers (and small difference between 20m and 18m is _not going to help much_ anyway). 

Adding lower threshold on first fix only might be better, but is also not without problems (ie. your track might **never** turn on if threshold is set low enough, and you live in part of the city with low reception, or alternatively if it is set high enough it might not make much difference - line jumping around by ~`16m` instead of by ~`21m` is not going to be much of an improvement)

<Details>

Note that [DOP](http://wiki.gis.com/wiki/index.php/Dilution_of_precision_(GPS)) is only approximate even in best of cases, and the 68% probability is not very good either. So even if it you lowered the threshold and it said to you that there is 68% chance that your location is accurate within `5m`, there is still rather high chance it is actually off by (for example) `50m`. Especially on first fix or signal re-acquisition, it is more likely that the location error would be higher than reported.

Of course, one could make AI to do sampling on startup (and signal re-acquisition?) and during use and auto-tune threshold depending on consecutive fixes in a period of time in some area (and especially in conjunction with other sensors to detect moving), but it is IMHO waaay too much of an overkill for this (and too much of magic generally). 

</details>

As a simpler workaround, maybe following idea might suffice: 
- On fist app start (ie. not from cache), if GPS signal is not present  set `badgps=true` (else set `badgps=false`) 
- (optionally: if GPS signal was lost during running, set `badgps=true`)
- when GPS signal is (re)acquired, check `badgps` - if it is `false`, draw the track. If it is `true`, set a timer to delay drawing the track for 5-10 seconds (in any case, when you start drawing the track, reset it to `false`).

So then if the GPS signal is present and within current 20m 68% accuracy, the track would continue to be drawn normally as before. However, when signal is first acquired (ie. one just exited from a home) it would be given some time to stabilize. 

<Details>

If the optional second step is also implemented, it would also delay drawing the track during temporary signal loss (like entering and exiting the tunnel). However, that might be problematic  (eg. intermittent GPS signal in the woods would result in no track being drawn at all), so is probably better avoided, as first step should fix reported case (as well as most of the others that can be easily fixed). 

So, if the app can easily detect GPS signal loss / acquisition, as well as when it is not started from cache, I guess it might be doable with reasonable effort. 

Still not sure if it is worth the effort - especially as problem usually only happens on startup, and the users can simply learn to start StreetComplete a few seconds later when they exit the building, and the workaround of restarting the app to clear the track (if they are bothered by that visual artifact) is not too complex.

</Details>

**Comment by ltog** [comment]
> And this is how it is currently solved: If the [accuracy](https://developer.android.com/reference/android/location/Location#getAccuracy()) of the location is more than 20 meters, the location is ignored for track-drawing. I don't see what can be improved here.

Hmm, well, I do use /e/ OS. Maybe there the network location works different than with stock Android? The location I get reported is always at the same position and was between 6 and 8 km off from my real location, where the forementioned issue occurred. To be honest, I do not exactly know, how network location works on other Android versions. Does it use WiFi signals to estimate your location? Does it move when you move? Is it reasonable to expect that it is some of the time more accurate than 20m?

**Comment by westnordost** [comment]
Anyway, simply some line drawn erronously is no reason for me to invest any time in a workaround / tweak or whatever.

**Comment by Helium314** [comment]
> Hmm, well, I do use /e/ OS. Maybe there the network location works different than with stock Android?

Stock Android (AOSP) doesn't have any network location provider. /e/ uses [Mozilla Location Services (via MicroG)](https://doc.e.foundation/what-s-e#degoogling--ungoogling).
So your phone gets network location from nearby WiFis and from radio cells (GSM and the like).

A network location with accuracy < 20 m must come from WiFi, as cells don't give you that kind of precise location. Thus either there is some wrong entry in the Mozilla Location Service database, or your phone reports the wrong WiFis.
I suspect the latter is the case, as it's part of Android since 9 (another one of those questionable power saving features). On Android 10 (and maybe later) you can disable WiFi scan throttling in developer options to fix it.
