### ISSUE TITLE
Streetcomplete sets "disused=yes" but should rather use the prefix "disused:"

### ISSUE THREAD

**Issue by dieterdreist** [streetcomplete/StreetComplete#3496]
currently for drinking fountains, streetcomplete sets disused=yes, but it would be preferable to both, ask for checking disused:amenity=drinking_water (whether it is turned on again), and set the prefix tag rather than the property.

example of a user setting the properties:
https://www.openstreetmap.org/changeset/113247662
https://www.openstreetmap.org/node/266310817

**Versions affected**

**Comment by FloEdelmann** [comment]
`disused=yes` was not added by StreetComplete: https://www.openstreetmap.org/node/266310817/history

**Comment by matkoniecz** [comment]
Closing as it is not added by StreetComplete.

I agree that it is a poor tagging, maybe StreetComplete should ask whether given object has only inactive remains or is it usable? For `disused:` prefixed (as resurvey) and `disused=yes` objects (for retagging) and either remove `disused=yes`/`disused:prefix` or switch to disused prefix?

It would require reviewing is fulfilled https://github.com/streetcomplete/StreetComplete/wiki/Adding-new-Quests-to-StreetComplete and checking how many objects would be eligible, then checking objects is there some unexpected surprise with them.

**Comment by peternewman** [comment]
Should we start for now by excluding asking for items tagged as `disused=yes`?

FWIW I carefully checked and only marked as existing water fountains that actually had water coming out of them and either ignored (when I couldn't check properly) or left a note when there was clearly no water coming out.

**Comment by matkoniecz** [comment]
> Should we start for now by excluding asking for items tagged as disused=yes?

Ones like this are especially likely to be fully gone where StreetComplete would definitely help.

StreetComplete fails to improve situation where

- such object is in use and `disused=yes` should be rather removed
- such object is out of order and should be rather prefixed and mapper failed to leave a note (which is the preferred solution)

but it never makes situation worse.

Excluding would make sense if there would be a dedicated quest for that.

**Comment by peternewman** [comment]
> > Should we start for now by excluding asking for items tagged as disused=yes?
> 
> Ones like this are especially likely to be fully gone where StreetComplete would definitely help.

In which case then shouldn't we add `disused:amenity = drinking_water` etc to the filter too then, so we capture and check even more of them? There's a fairly comparable split of the two schemas for drinking water in Rome.

> StreetComplete fails to improve situation where
> 
> * such object is in use and `disused=yes` should be rather removed
> * such object is out of order and should be rather prefixed and mapper failed to leave a note (which is the preferred solution)
> 
> but it never makes situation worse.

Doesn't that somewhat depend on whether we're asking the existence of a "disused drinking water" or just a "drinking water" though? I've inadvertently confirmed the existence of the former, despite only being asked about the latter. Someone with another app or tool now probably won't choose to re-check this drinking fountain for a few more years as they'll assume my check was valid. Essentially similar to past discussion of check_date, what is actually being checked...

Indeed regarding the note, if I'd been asked "Is this disused drinking water still here?" I'd have left a note saying it's currently working or similar.

> Excluding would make sense if there would be a dedicated quest for that.

Well can't we fairly trivially modify the quest without needing a dedicated one? I think we just need to change the title to fix the quest.

The current string are:
https://github.com/streetcomplete/StreetComplete/blob/3c08b78916f4d16d457db676b382d11d8a36fa7c/app/src/main/res/values/strings.xml#L446-L447

Would adding a prefix and/or suffix cover it for all languages, i.e.:
Is this [disused] [drinking water] still here?

Then by changing the prefix/suffix we could also handle abandoned etc.

Or does it need it's own dedicated string?

**Comment by matkoniecz** [comment]
> In which case then shouldn't we add disused:amenity = drinking_water etc to the filter too then, so we capture and check even more of them? There's a fairly comparable split of the two schemas for drinking water in Rome.

Such objects are not shown in various places as active ones, so deleting ones that are fully gone is far less important.

>  Is this [disused] [drinking water] still here?

Note that "no" would be true for both

> no, it is fully removed

> no, it is now fully active again

while actions are different for both cases (delete node in the first one, remove `disused` for the second one)

**Comment by dieterdreist** [comment]
sent from a phone

> On 11 Nov 2021, at 06:59, Mateusz Konieczny ***@***.***> wrote:
> 
> Such objects are not shown in various places as active ones, so deleting ones that are fully gone is far less important.
> 


right, but readding them as active when they are would be more important/interesting

**Comment by matkoniecz** [comment]
Yes, but that would need a new quest to work well

**Comment by peternewman** [comment]
> > In which case then shouldn't we add disused:amenity = drinking_water etc to the filter too then, so we capture and check even more of them? There's a fairly comparable split of the two schemas for drinking water in Rome.
> 
> Such objects are not shown in various places as active ones, so deleting ones that are fully gone is far less important.

But surely you can't have it both ways, if that's true of `disused:amenity = drinking_water`, it's true of `amenity = drinking_water disused=yes`?

> > Is this [disused] [drinking water] still here?
> 
> Note that "no" would be true for both
> 
> > no, it is fully removed
> 
> > no, it is now fully active again

Personally I'd say "yes, but it's active again", it's an important property of the thing.

Consider:
Is this [office] [building] still here?
Yes
No
No, it's now a hotel building.

The building is still there in both cases. But if you just asked me is this building still here and then tagged the check date and it's completely changed what it does, it feels like a missed opportunity.

> while actions are different for both cases (delete node in the first one, remove `disused` for the second one)

> Yes, but that would need a new quest to work well

Or leave a note for the rare cases when the state has changed.

To put it somewhat bluntly, I feel like I've been wasting my time carefully checking each fountain was flowing (and leaving a note when they weren't), to find some are currently tagged to say they aren't flowing and therefore my time has been wasted (unless I carefully double-check and retag them). I think that's going to be naturally true of most people with most amenities, if I get asked if a bench exists, I'm not going to just say yes if the seat is completely missing and I can't sit on it (philosophical question, is it even still a bench if it's just the two metal/concrete uprights?).

**Comment by matkoniecz** [comment]
> But surely you can't have it both ways, if that's true of disused:amenity = drinking_water, it's true of amenity = drinking_water disused=yes?

`disused:amenity = drinking_water` is already tagged in way that it will not show in reasonable data consumers and validly tagged.

`amenity = drinking_water disused=yes` is not yet tagged in a good way to indicate that it is not usable - it is as good tagging as tagging prison as `tourism=hostel involuntary=yes` ( https://wiki.openstreetmap.org/wiki/Trolltag )

> Personally I'd say "yes, but it's active again", it's an important property of the thing.

And with current quest it would go to "yes" option which would keep tags unmodified. So we would need either additional answers making it unwieldy or a new quest

> To put it somewhat bluntly, I feel like I've been wasting my time carefully checking each fountain was flowing (and leaving a note when they weren't), to find some are currently tagged to say they aren't flowing and therefore my time has been wasted 

I agree that it is a poor situation, but I would rather blame use of `disused=yes` `demolished=yes` `actually_not_existing=yes` `operational_status=closed`, `status=inactive`, `is_existing=not_at_all`, `damage_status=destroyed` and would treat it as a tagging mistake. If for some reason it is not treated as a mistake but as valid tagging then it would be a good reason to change something (feel free to open new issue if someone has actionable idea worth doing)

**Comment by dieterdreist** [comment]
If drinking water fountains are part of a quest, ideally (IMHO) these tags should be looked at:

disused=yes (should be retagged to disused:amenity if disused is confirmed by the user),

similarly abandoned=yes and abandoned:amenity (these are visibly broken fountains, not looked after for a longer time)

For both these states, disused and abandoned, any of the 4 tags should lead to a question (because disused fountains often run again after short time, while abandoned fountains might be removed or replaced).

For amenity=fountain objects it could be asked if drinking water is available (drinking_water=* is missing), i.e. it is not about the water quality in the fountain, but about a possibility to get drinking water there (usually it implies one or more drinking fountains somehow integrated)

**Comment by mnalis** [comment]
As I see it, it seems that currently SC will ignore `disused=yes`/`abandoned=yes` tags, and add `check_date` if the user answers the thing (like water fountain) is still there. It is **bad**, because `check_date` implies that this situation as described by tags was correct at the time (ie. that there was water fountain there which is disused). So if water fountain was fixed in the meantime, `check_date` added by SC would imply that it is still `disused`, which is IMHO worse than if SC didn't ask/modify anything.

Several things could be done to improve situation:

- if SC is modified to ignore objects with `disuses=yes` / `abandoned=yes`, we wouldn't improve situation on those (hopefully rare, as `disused:` prefix is discouraged), but at least we wouldn't make it worse (which adding `check_date` arguably is). Advantage is that it is probably easiest to change. 
- if we change the texts to clarify that we don't only want to know `if it exists` but `if it exists and is in working order`, that would make a quest little harder to solve, but much more useful. We could then also modify code to remove any  discouraged `disused=yes` / `abandoned=yes` tags when users answers `it exists and is in working order`, thus improving the map. The disadvantage is that translations would have to be redone too.
- new quest could be designed, which could look at **all** `disused=yes` or `abandoned=yes` objects (as well as `disused:*` and `abandoned:*` which were last updated more than `x` years ago), and ask if they are still disused / abandoned. If they are, it could add/update `check_date` and also change `disused=yes` + `xxxxx` to `disused:xxxx` to prevent the situation described from reappearing (and if they aren't the `disused`/`abandonded` tag/prefix would be removed). Disadvantage of separate quest is that is would also update the object, so all resurvey quests would be bumped by another `x` years.

**Comment by matkoniecz** [comment]
> Disadvantage of separate quest is that is would also update the object, so all resurvey quests would be bumped by another x years.

But if it would be fully gone user would select "it is gone" option, right? Resurvey immediately after answer that implies it is existing is not really needed

> hopefully rare, as disused: prefix is discouraged

Is there typo here? encouraged, right?

> It is bad, because check_date implies that this situation as described by tags was correct at the time 

`check_date` is about existence of object not all tags (and SC is definitely not giving chance to review other tags). From what I remember there was discussion about it (issue tracker here, OSM Wiki and mailing list)

**Comment by peternewman** [comment]
> `disused:amenity = drinking_water` is already tagged in way that it will not show in reasonable data consumers and validly tagged.
> 
> `amenity = drinking_water disused=yes` is not yet tagged in a good way to indicate that it is not usable - it is as good tagging as tagging prison as `tourism=hostel involuntary=yes` ( https://wiki.openstreetmap.org/wiki/Trolltag )

I think you're being unfair on that tagging, it's very different to your prison example. The wiki feels somewhat ambiguous to me, for example:

> It is better to use simple tag disused=yes as disused building is still a building.

> A simple feature such as an Tag:man_made=adit which is in good condition but is not used is tagged with man_made=adit + disused=yes.

It doesn't seem very clear to me where the line is drawn between the tag and the prefix, after all to paraphrase a disused water fountain is still a water fountain, although I appreciate not very useful for getting water from.

> > Personally I'd say "yes, but it's active again", it's an important property of the thing.
> 
> And with current quest it would go to "yes" option which would keep tags unmodified. So we would need either additional answers making it unwieldy or a new quest

No, I'd go can't say, leave a note, you're incorrectly conflating my English language response with which button I'd press in the app.

> I agree that it is a poor situation, but I would rather blame use of `disused=yes` `demolished=yes` `existing=no` `actually_not_existing=yes` `operational_status=closed`, `status=inactive`, `is_existing=not_at_all`, `damage_status=destroyed`, `opening_hours=closed` (most of this is an actual tagging! only two are jokes!) and would treat it as a tagging mistake.

Unfortunately whether it's a tagging mistake or acceptable practise, it's rife in the real world so we need to deal with it (numbers from my random sample of Rome):
https://overpass-turbo.eu/s/1cWB - 19 - `disused=yes`
https://overpass-turbo.eu/s/1cWC - 25 - `disused:amenity=drinking_water`
https://overpass-turbo.eu/s/1cWD - 1571 - `amenity=drinking_water and not disused=yes`

> If for some reason it is not treated as a mistake but as valid tagging then it would be a good reason to change something (feel free to open new issue if someone has actionable idea worth doing)

I've suggested multiple times, either don't show any disused tagging (prefix or standalone tag), or show the lifecycle (in either form) when asking the question.

> But if it would be fully gone user would select "it is gone" option, right? Resurvey immediately after answer that implies it is existing is not really needed

I assume @mnalis is referring to the more general case of say checking whether it was vacant still/which shop is inside if a disused building.

> > It is bad, because check_date implies that this situation as described by tags was correct at the time
> 
> `check_date` is about existence of object not all tags (and SC is definitely not giving chance to review other tags).

I'd agree it's not all tags, but in terms of priority of tag, whether it's disused or not is right up there with what sort of thing it is; we don't just ask "is this node still here?", we bother to tell the user that it's a drinking fountain. Given you're suggesting it should be tagged as `disused:amenity=drinking_water` to differentiate it from in use `amenity=drinking_water`, would imply they are indeed two different things, and therefore we should show that to the user (otherwise we're back to just asking if the node or amenity still exists, without specifying which one). I accept we don't need to confirm that it's a Nasone ( https://wiki.openstreetmap.org/wiki/Tag:fountain%3Dnasone ) or stone or whatever.

> From what I remember there was discussion about it (issue tracker here, OSM Wiki and mailing list)

There was indeed, definitely on the latter and former.

**Comment by dieterdreist** [comment]
sent from a phone

> On 12 Nov 2021, at 04:50, Peter Newman ***@***.***> wrote:
> 
> I accept we don't need to confirm that it's a Nasone ( https://wiki.openstreetmap.org/wiki/Tag:fountain%3Dnasone ) or stone or whatever.


generally, adding drinking fountain types would be desirable, but I am not sure they would make for a good quest, as likely to encounter types are varying across regions 

Please note that amenity =drinking_water does not imply a drinking  fountain, it’s more generic and could be any source of drinking water

**Comment by matkoniecz** [comment]
I went looking at data - as I considered making a new quest covering just this.

[amenity=drinking_water and disused=yes](http://overpass-turbo.eu/?q=LyoKVGhpcyBoYcSGYmVlbiBnxI1lcmF0ZWQgYnkgdGhlIG92xJJwxIlzLXR1cmJvIHdpemFyZC7EgsSdxJ9yaWdpbmFsIHNlxLBjaMSsxIk6CsOiwoDCnGFtxI1pdMSaPSBkxLdua8S6Z193xJTEkiBhbsSXZMSFdcS_ZD15ZcSGZ2xvYsS8xYjCnQoqLwpbb3V0Ompzb25dW3RpxYzFtsW4MjVdOwovL8SPxJTEnXIgcsWodWx0cwooCiAgxoogcXXEksSaxKNydCBmb3I6IMWIxYrFjG7Fjnk9xZPEusWWbsWYxZrElcaPxZ7FoMWixaTFpsWoxa_GmSBub2RlWyLFi8WNxY8iPSLGssWVxZfFmcWbciLFvseOxrzElseMIsWnc8eVxojGmsWaeceHx4nGrseLx43Hj8a0xrbHk8eVx4fFoXPFo8eZx43HnMeex4HGkWzElGnFvMejxq3Gr8eax6jHkca3xJLHrMeXx6_FpMeax7PGhwopxojGnHDFlMakxpHHr8aUxpbGg8SYx4R5xog-xojIlXNrZcS9cXQ7&c=BPKsPHF7lI) is just 244 objects worldwide.

[man_made=petroleum_well and disused=yes](http://overpass-turbo.eu/?q=LyoKVGhpcyBoYcSGYmVlbiBnxI1lcmF0ZWQgYnkgdGhlIG92xJJwxIlzLXR1cmJvIHdpemFyZC7EgsSdxJ9yaWdpbmFsIHNlxLBjaMSsxIk6CsOiwoDCnCBtYW5fxYxkZT1wZXRyb2xldW1fd2VsxL3FjcSXZMSFdcS_ZD15ZcSGZ2xvYsS8xYjCnQoqLwpbb3V0Ompzb25dW3RpbWXFucW7MjVdOwovL8SPxJTEnXIgcsWrdWx0cwooCiAgxo4gcXXEksSaxKNydCBmb3I6IMWIwpzFjMWOxZDFksWUxZbFmMWaxZzFnsWgIMWiIMWkc8WmxJbFqcWrxbLGnSBub8WRWyLGscWPYcWRIj0ixrXFl8WZxZvFncWfbCLGgSLGv8eBZMeRIsWqc8ebxozGnndheceLx43Gs8ehx5TGt8eXxrrHmsecx57Fp8ehx6PHpceGxpVsxJRpxb_Hq8WNx47HkMeSx6_Hlsa5x5nHm8eLx7XElse3xavHuSnGjMagcMS3bsaoxpXHgMaYxprGh8SYx4l5xow-xozIm3NrxZ_GoXQ7&c=Bg6A9VdhIC) has over 7000 but mostly from imports and here asking rate would be far lower.

Not sure is it really worth making quest here, especially as adding `disused:` prefixes would be pile of problems.

How to prefix 

`disused=yes`
`amenity=drinking_water`
`name=Foobar`

How to prefix 

`disused=yes`
`abandoned:amenity=drinking_water`
`name=Foobar`


How to prefix 

`disused=yes`
`amenity=drinking_water`
`abandoned:name=Foobar`

How to prefix 

`disused=yes`
`amenity=drinking_water`
`name=Foobar`
`demolished:man_made=carpet_hanger`

**Comment by matkoniecz** [comment]
> it's rife in the real world

244 cases for suspect tagging...

I am not sure is it even worth excluding from quests.

**Comment by peternewman** [comment]
> generally, adding drinking fountain types would be desirable, but I am not sure they would make for a good quest, as likely to encounter types are varying across regions

You could always suggest it as a new quest, we've got other existing ones which either restrict or simply change the sort order depending on the country (if such data can be gathered somehow).

> I went looking at data - as I considered making a new quest covering just this.

> [amenity=drinking_water and disused=yes](http://overpass-turbo.eu/?q=LyoKVGhpcyBoYcSGYmVlbiBnxI1lcmF0ZWQgYnkgdGhlIG92xJJwxIlzLXR1cmJvIHdpemFyZC7EgsSdxJ9yaWdpbmFsIHNlxLBjaMSsxIk6CsOiwoDCnGFtxI1pdMSaPSBkxLdua8S6Z193xJTEkiBhbsSXZMSFdcS_ZD15ZcSGZ2xvYsS8xYjCnQoqLwpbb3V0Ompzb25dW3RpxYzFtsW4MjVdOwovL8SPxJTEnXIgcsWodWx0cwooCiAgxoogcXXEksSaxKNydCBmb3I6IMWIxYrFjG7Fjnk9xZPEusWWbsWYxZrElcaPxZ7FoMWixaTFpsWoxa_GmSBub2RlWyLFi8WNxY8iPSLGssWVxZfFmcWbciLFvseOxrzElseMIsWnc8eVxojGmsWaeceHx4nGrseLx43Hj8a0xrbHk8eVx4fFoXPFo8eZx43HnMeex4HGkWzElGnFvMejxq3Gr8eax6jHkca3xJLHrMeXx6_FpMeax7PGhwopxojGnHDFlMakxpHHr8aUxpbGg8SYx4R5xog-xojIlXNrZcS9cXQ7&c=BPKsPHF7lI) is just 244 objects worldwide.

It's at 245 after a week, although I appreciate one is a minor growth rate.

But adding some other things would make it worthwhile, e.g. every `amenity=` we've got a translated name for via the presets stuff, or even multiple primary keys.

> Not sure is it really worth making quest here, especially as adding `disused:` prefixes would be pile of problems.
> 
> How to prefix
> 
> `disused=yes` `amenity=drinking_water` `name=Foobar`

Isn't the whole point that this becomes this (as the amenity is what's disused):
`disused:amenity=drinking_water` `name=Foobar`

Or you could only find items with those pairs of tags, or have an allow or deny list of other tags at which point the question wouldn't be asked due to potential ambiguity.

> How to prefix
> 
> `disused=yes` `abandoned:amenity=drinking_water` `name=Foobar`
>
> How to prefix
> 
> `disused=yes` `amenity=drinking_water` `abandoned:name=Foobar`
> 
> How to prefix
> 
> `disused=yes` `amenity=drinking_water` `name=Foobar` `demolished:man_made=carpet_hanger`

Yeah they're all a mess, but you could just skip anything with other lifecycle prefixes at the start of any tags.

**Comment by dieterdreist** [comment]
sent from a phone

> On 19 Jan 2022, at 03:50, Peter Newman ***@***.***> wrote:
> 
> How to prefix
> 
> disused=yes abandoned:amenity=drinking_water name=Foobar
> 

nothing to do here


> How to prefix
> 
> disused=yes amenity=drinking_water abandoned:name=Foobar
> 

abandoned:name should be name, disused=yes converted to
disused:amenity=….



> How to prefix
> 
> disused=yes amenity=drinking_water name=Foobar demolished:man_made=carpet_hanger
> 


unsure, maybe the disused tag is a leftover from the carpet hanger? I’d rather ask for someone with experience and ground knowledge to fix this
