### ISSUE TITLE
Give hint how to answer wheelchair_access quest

### ISSUE THREAD

**Issue by guerda** [streetcomplete/StreetComplete#3528]
The [wheelchair access quests](https://github.com/streetcomplete/StreetComplete/tree/master/app/src/main/java/de/westnordost/streetcomplete/quests/wheelchair_access) seem innocent from the question, but the implications are quite heavy. In order to enable users to complete the task correctly, I would like to see some hints, what the answers mean.

Based on the [wiki entry on wheelchair](https://wiki.openstreetmap.org/wiki/Key:wheelchair) and [wheelmap.org](https://news.wheelmap.org/FAQ/), some hints could be added:

wheelchair=yes
Wheelchairs have full unrestricted access. Use this tag to mark a feature in the United States as compliant with the Americans with Disabilities Act (ADA).

entry: stepless
rooms: stepless
wheelchair=limited
Wheelchair limited.jpeg
Wheelchairs have partial access (e.g some areas can be accessed and others not, areas requiring assistance by someone pushing up a steep gradient).

entry: has a step but not higher than 7 cm / 3 inch ('width of a hand')
rooms: the most important rooms are stepless
wheelchair=no
Wheelchairs have no unrestricted access (e.g. stair only access).

entry: has a step higher than 7 cm / 3 inch
rooms: the important rooms are not accessible

**Comment by matkoniecz** [comment]
There is hint already. 

> Partially means that there is no more than a single step to access the place and that most rooms inside are wheelchair accessible.

How specifically you propose to change it?

**Comment by guerda** [comment]
Sorry for being imprecise. I think the information about step size (<= 7cm) is quite crucial regarding the outside locations.

**Comment by matkoniecz** [comment]
Do you have an idea how to specifically incorporate into existing texts?

I just tried to check is it maybe a good idea to include it and failed to produce something readable.

What worse I would have no chance to estimate step height.

maybe something like 

> Partially means that there is no more than a single step to access the place and the step is not very high. Additionally, most rooms inside are wheelchair accessible.

**Comment by Helium314** [comment]
Giving some more information would be very helpful.
I initially answered `partially` for almost everything that only has one step (whatever the height) and is otherwise accessible.
This only changed after I read the OSM wiki page.

I find the "one step" limitation somewhat weird, because it clearly means that 2 steps of 2 cm is not accessible.

> Wheelchair limited.jpeg
 
Do you mean there should be example images?

BTW: the [kerb](https://wiki.openstreetmap.org/wiki/Key:kerb) page also has some information about wheelchair access, unfortunately quite inconsistent with the wheelchair page

**Comment by smichel17** [comment]
I think it would be better to share the precise step size information. It may be hard to estimate 7cm step height, but it's even harder to estimate what the author means by *not very high*.

…If we really wanted to, we could add a button to show a ruler on screen, to allow people to measure; I think it's possible to query pixel density in order to show absolute sizes.

**Comment by westnordost** [comment]
Wiki says

> entry: has a step but not higher than 7 cm / 3 inch ('width of a hand')

So let's use that. "Width of a hand". Any suggestions for an updated wording?

**Comment by westnordost** [comment]
I asked in the #language channel on slack and the swiftest suggestion was "anke-high step". 

- There is no really very swift/short way of saying "step as high as a the width of a hand" in English. (In German on the other hand, there is the adjective "handbreit")
- The ankle is very roughly as high as a _handbreit_.  It's also easy to measure.

So I changed
```diff
- Partially means that there is no more than a single step to access it.
+ Partially means that there is no more than a ankle-high step to access it.
```
etc.

**Comment by westnordost** [comment]
Thanks @1ec5

**Comment by guerda** [comment]
Thank you, Tobias, for investigating and changing it! Thanks all for the discussion. Happy mapping.
