### ISSUE TITLE
Allow disabling Note quest

### ISSUE THREAD

**Issue by mnalis** [streetcomplete/StreetComplete#3532]
**Use case**
Now that we have quest presets, the original reason for having `Notes quest` always force-enabled is largely gone.

There are legitimate reasons for having it disabled (eg. in test preset I disable all quest but one, which I want to see on the map to find where it exists, troubleshoot bug/issue with it, finding how it works etc.). Currently, when I cannot disable Notes, the map is also peppered with Notes quests (happens a lot in my areas), it is impossible to do, as one has to zoom in to expand dots to full quests (so it could be checked if it is wanted quest, or unwanted note) then zoom out again, move to another area, zoom in etc.

**Proposed Solution**
- If the user is editing non-Default preset, remove special handling of `Can you contribute anything to this note?` quest, ie. allow disabling it or moving it around.

- (Alternatively, allow disabling `Notes quest` in all presets, perhaps with helpful prompt explaining why that might be a bad idea)

**Comment by westnordost** [comment]
The reason why notes quests are force-enabled has nothing to do with quest presets. It is enabled because notes potentially show a problem with the element they refer to, thus no further questions about it should be asked until that note is solved.

Also by the way, even if the note quest was not shown, quests for elements **at** the position of a note - whether the note is shown or not - are simply not created and this is deliberate for the aforementioned reason.

Remember, you can let the app only display notes that are phrased as questions.

**Comment by mnalis** [comment]
related:
- https://github.com/streetcomplete/StreetComplete/issues/4687
- https://github.com/streetcomplete/StreetComplete/issues/4529
- https://github.com/Helium314/StreetComplete/pull/359
- https://github.com/streetcomplete/StreetComplete/discussions/4700
