### ISSUE TITLE
Split way dialogue covers up map buttons

### ISSUE THREAD

**Issue by timothywashere** [streetcomplete/StreetComplete#3535]
When splitting a way the map buttons are covered up by the text.
When splitting a very long way this can be a problem because it zooms out so I can see the whole way; but I only want to split the section near where I am and I can't use the  Current Location button to get back to where I want

![Screenshot_20211124-144636](https://user-images.githubusercontent.com/87654968/143259973-951ff240-4fc1-47bf-a940-b90f50e8621b.png)

It would be nice if the dialog box was a bit thinner to allow the buttons on the right to still be used

Hope I've made sense 🙂
**Versions affected**

v38.0-beta1
Android 12

**Comment by westnordost** [comment]
Well the quest form also covers the map buttons. Zooming in and out when viewing a quest is just as useful as in this form, so I don't want to break consistency only because it would neatly be possible here.

You can zoom in and out using the two-finger gesture or the double-tap-drag-up-or-down gesture.

You can also rotate your device 90°, then you should also see the +/- buttons

**Comment by timothywashere** [comment]
Whilst you can zoom using finger gestures, there is no gesture for "Go to current location" is there?
On a very long road it's a big pain to zoom and swipe back to where you are

**Comment by smichel17** [comment]
Tap the pin that points back to your location.

**Comment by timothywashere** [comment]
> Tap the pin that points back to your location.

Haha, I never even noticed that blue marker. Thanks for the tip
