### ISSUE TITLE
[Bug] User's location becomes frozen after Street Complete sent to background

### ISSUE THREAD

**Issue by timothywashere** [streetcomplete/StreetComplete#3543]
When first started the user's location dot tracks their position perfectly.
But after SC is sent to the background and brought back again, the location becomes fixed (I believe the user's orientation still changes). 
Using the app switcher screen to close SC and then launching the app again always solves the problem.
Restarted my phone several times and the behaviour is the same.
Other apps (Maps.me) don't seem to have this problem.

May happen when switching apps or when locking phone.

**How to Reproduce**
Load SC, move around to confirm location is working
Press power button to lock screen 
Unlock phone
Location is fixed in SC and doesn't move around.
View open apps, close SC
Re-launch SC
Location tracks fine.

**Versions affected**
Using SC v38  on Android 12 . Pixel 3 phone in the UK.

**Comment by timothywashere** [comment]
See discussion in  #3541 for other people's experiences

**Comment by peternewman** [comment]
I think I've seen this too, at least on the beta. Android 9 on a Sony.

**Comment by timothywashere** [comment]
Happening just when switching apps today as well as when phone is locked

**Comment by mcliquid** [comment]
I had the same problem today with version 38.0 from the AppStore. I thought it was my phone, but after reading this, I want to join this bug issue. It works fine with other apps.

**Comment by mnalis** [comment]
Quickly skimming at the diffs between `v37.2` and `v38.0` (as a non-android programmer),  two things catch my eye as possible culprits:

```diff
-    implementation("com.mapzen.tangram:tangram:0.16.2")
+    implementation("com.mapzen.tangram:tangram:0.17.0")
```

and especially `app/src/main/java/de/westnordost/streetcomplete/location/FineLocationManager.kt` changes (356b719c802554e92e2d93cbd01648340617a021, c288b8e03ef1262d76b721db543911667c69549d)

(I'm not an android developer, though, so I could likely be completely wrong.)

**Comment by smichel17** [comment]
I believe I've spotted the cause. It was indeed introduced by c288b8e and 356b719.
It's because here (called in `onStop`, aka when SC leaves the foreground), we cancel *both* signals:

https://github.com/streetcomplete/StreetComplete/blob/99cbb8fb362223a1f0c32566e5f72c8ace84d6d9/app/src/main/java/de/westnordost/streetcomplete/location/FineLocationManager.kt#L72-L76

And then here, we check whether *either* signal is canceled:

https://github.com/streetcomplete/StreetComplete/blob/99cbb8fb362223a1f0c32566e5f72c8ace84d6d9/app/src/main/java/de/westnordost/streetcomplete/location/FineLocationManager.kt#L34-L36

But when we (re-)register, we only reset the cancelation signals conditionally based on which provider is enabled:

https://github.com/streetcomplete/StreetComplete/blob/99cbb8fb362223a1f0c32566e5f72c8ace84d6d9/app/src/main/java/de/westnordost/streetcomplete/location/FineLocationManager.kt#L53-L57

So, on a device with only GPS or only network provider, you'll end up with one signal which is never reset, so when updates are received, they're skipped. I would expect that everyone who reproduced this has their device's location services set to `GPS only`.

https://github.com/streetcomplete/StreetComplete/pull/3547 should fix it, although I did not test it yet and am not happy with that particular solution.

**Comment by matkoniecz** [comment]
> I would expect that everyone who reproduced this has their device's location services set to GPS only.

I have "improve location accuracy" enabled ("improves location accuracy by using Wi-Fi, mobile networks and sensors to help estimate your location")

**Comment by timothywashere** [comment]
> > I would expect that everyone who reproduced this has their device's location services set to GPS only.
> 
> I have "improve location accuracy" enabled ("improves location accuracy by using Wi-Fi, mobile networks and sensors to help estimate your location")

Same here

**Comment by smichel17** [comment]
Hmm, ok. Well, I've now reproduced in an emulator, so I'll poke around and see what I can find.

**Comment by mnalis** [comment]
I used to have that device set to GPS only, but then few months ago Huawei completely removed that option and forced me to agree to "help improve position accuracy" if I wanted to continue using GPS location at all. Now this option is gone completely, so I'm guessing they're forcing me to always use wifi/mobile towers too :scream:

**Comment by smichel17** [comment]
So it turns out that I'm both wrong and right:

- Right: the bug I identified exists.
- Wrong: the bug I identified isn't the reason you're all having issues

It's a much simpler reason: `requestUpdates` doesn't reset the signal at all! :joy:

https://github.com/streetcomplete/StreetComplete/blob/c288b8e03ef1262d76b721db543911667c69549d/app/src/main/java/de/westnordost/streetcomplete/location/FineLocationManager.kt#L45-L50

**Comment by smichel17** [comment]
Hm. @westnordost I'm poking around for a solution that feels less fragile/hacky. Do you remember any more more context about https://github.com/streetcomplete/StreetComplete/commit/356b719c802554e92e2d93cbd01648340617a021 and https://github.com/streetcomplete/StreetComplete/commit/c288b8e03ef1262d76b721db543911667c69549d?

Because, now that I've looked into it more closely, c288b8e03ef1262d76b721db543911667c69549d doesn't really make sense to me. It's preventing the callback from being called when the signals are canceled, but that code path *should* be deactivated by `locationManager.removeUpdates`, not by the cancellation signal. So now I'm not sure if 356b719c802554e92e2d93cbd01648340617a021 is incomplete (fixes one of the crashes in #3517 but not the other) or whether it is not needed at all (fixes nothing, and c288b8e03ef1262d76b721db543911667c69549d does all the lifting, in which case I'd rather use an explicit `var shouldBeCanceled: Boolean`).

**Comment by RubenKelevra** [comment]
I can confirm this issue for v38 as well. I downgraded to v37.2 and it seems to occur there as well, but much more rarely.

It isn't a "GPS wakeup" issue or something like that, since I had another app running in the background which was using the GPS continuously.

I also had a crash today, shortly after it started happening on v38. Not sure if that's related. @westnordost I think my phone does report crashes to you, have a look if you got one from my Google account.

**Comment by westnordost** [comment]
> Because, now that I've looked into it more closely, c288b8e doesn't really make sense to me. It's preventing the callback from being called when the signals are canceled, but that code path should be deactivated by locationManager.removeUpdates, not by the cancellation signal.

Oh, you are right. I fixed this now.

And I I'd say you found the bug (#3543). The cancellation signals are cancelled on `removeUpdates` but are not refreshed on a new call to `requestUpdates` (because the cancellation signals are supposed to be only for single updates). Thus, on stopping and then restarting, no updates will reach the caller.

**Comment by peternewman** [comment]
Thanks @smichel17 @westnordost . Could we have a v38.1 release with this fix in please? As it has a heavy impact on effectiveness of using the app having to instead manually keep track of where you are.

**Comment by westnordost** [comment]
done, in case you didn't see it. Will take a few days as usual until it appears on F-Droid

**Comment by mcliquid** [comment]
I tried v38.1 yesterday. The bug is fixed for me. Thanks a lot!

**Comment by peternewman** [comment]
Yeah likewise it appeared and its now working perfectly again via Google Play for me thanks @westnordost !
