### ISSUE TITLE
[Cycleway Quest] Answer: Bicycles aren't allowed here

### ISSUE THREAD

**Issue by RubenKelevra** [streetcomplete/StreetComplete#3544]
**Use case**
_Granted this is rare too occur but it would be nice to capture this information if the user is attentive._

Sometimes a street is forbidden to be used by cyclists. While we got a solution to ask for pedestrian's access if there's no sidewalk we don't do this for cyclist (for obvious reasons). 

**Proposed Solution**
Add a "other answers" response the user can choose: 'bicycles are not allowed here' which will set the access and the cycleway tags.

**Comment by timothywashere** [comment]
Under what circumstances would you show this quest?

**Comment by matkoniecz** [comment]
It seems to be supposed to be available in existing cycleway quest, I think.

Though I would consider leaving note as sufficient - unless there is an indication that people often map "no bicycles allowed" as just no cycleway instead of opening note and that recognizable "no bicycles allowed" appears often.

**Comment by riQQ** [comment]
Meta: can someone with the necessary privilege please fix the issue title

**Comment by matkoniecz** [comment]
What is wrong with it?

**Comment by riQQ** [comment]
Double negative
Current: Bicycles aren't forbidden here
Should: Bicycles are forbidden here / Bicycles aren't allowed here

**Comment by RubenKelevra** [comment]
> It seems to be supposed to be available in existing cycleway quest, I think.

Correct :) 


> Though I would consider leaving note as sufficient - unless there is an indication that people often map "no bicycles allowed" as just no cycleway instead of opening note and that recognizable "no bicycles allowed" appears often.

Not sure if that happens, but I don't think an additional point in the "other answers" would hurt.

Adding a note can also be quite cumbersome, if a road/path has multiple sections. So you have to create multiple notes which all have to be processed by another user afterwards.

**Comment by matkoniecz** [comment]
It seems to make sense to me, also because it would make more clear what "no cycleway" actually means

**Comment by 16NoCo** [comment]
> I don't think an additional point in the "other answers" would hurt.

I believe that it would be better to add an option with a pictogram along with the other main options, something like this:

![Screenshot_20220120-114319_Street­Complete](https://user-images.githubusercontent.com/26925557/150325345-10b6c0a9-8001-412a-978e-83d08bddf530.png)

This would make the "no cycleway" option even clearer.
And a street could have a cycleway in one direction while the other direction could be forbidden to bicycles. Adding the option along with the others would allow that (if this can be represented by OSM tags, of course, I haven't looked into that).

**Comment by matkoniecz** [comment]
I opened https://lists.openstreetmap.org/pipermail/tagging/2022-April/thread.html#64324 ( https://lists.openstreetmap.org/pipermail/tagging/2022-April/064324.html ) as there is at least one tricky case where I see no sane tagging.

It is quite rare and I think that losing a bit of info can be OK here, but would be nice to avoid it.

**Comment by westnordost** [comment]
In reply to https://github.com/streetcomplete/StreetComplete/issues/3984#issuecomment-1105588618 :

![](https://user-images.githubusercontent.com/899988/164526656-fa24a4a1-c57c-4cb8-9668-7b4e8db8e522.png)

I see the following issue with the proposed solution of selecting "no cyclists allowed" per side:
This selection is very very rare, yet, I guess in order to be discoverable by users and make the distinction between "no cycleway" clear, @matkoniecz seems to prefer to show it right next to the "no cycleway" option at the very top. This is an issue because it puts a very rare option to the top.

There is already the "cycleway separate" option and this should somewhat cover most of the cases I can imagine where cycling is not allowed in one direction but in the other on the road way (because on one side, cyclists must use the separately mapped sidepath).

So, given that a **real** cyclist prohibition on one side only is very very rare, implementing this as an "other answer" option seems to be more meaningful to me.

**Comment by matkoniecz** [comment]
> yet, I guess in order to be discoverable by users and make the distinction between "no cycleway" clear, @matkoniecz seems to prefer to show it right next to the "no cycleway" option at the very top

Yes, the primary reason for supporting this is to make more clear the difference between "cycling forbidden" (including on oneway roads) and "no specific cycling infrastructure but cycling allowed in this direction" and "cycling allowed in this direction together with cars".

Putting it into "other answer" option seems to be losing this benefit, making this extra option not worth it.

**Comment by Mannshoch** [comment]
For the record, I do not like the current situation. It's not intuitive. The first time I startet with maping cycleways I used the Icon for using together with cars.
![grafik](https://user-images.githubusercontent.com/7795891/176859661-19759468-89f7-4b3e-964c-e841f6cc45c1.png)
At least I would propose to remove at least the big cross and only show a street.

**Comment by westnordost** [comment]
I've decided to close this, this is just a too rare situation that warrants implementation. There is always the possibility to create a note after all.
