### ISSUE TITLE
incorrect side suffix added to cycleway key where there are multiple bicycle lanes

### ISSUE THREAD

**Issue by DerDings** [streetcomplete/StreetComplete#3568]
So this https://osmcha.org/changesets/114297711/ happened: A oneway piece of road which has a bicycle lane in the middle and one on the right was previously tagged `cycleway=lane`. SCs resurvey retagged it as `cycleway:right=lane`. This is not completely correct, since there is also a bicycle lane in the middle.

**How to Reproduce**
solve the cycleway quest on a way tagged like [00062210](https://www.openstreetmap.org/way/300062210/history) , version 11

**Versions affected**
at least 28.0

**Solution**
1. ***tagging***: For any road which has a `bicycle:lanes` tag, don't add side suffixes `*:left` or `*:right`.
In detail:
-- For `oneway` roads without `oneway:bicycle` or `oneway:bicycle=yes`:
  just tag `cycleway=*` without any suffix. If a user selects _other answers ➡ also a cycleway on the other side_, ask them to leave a note.
-- For dual-way roads or roads tagged `oneway:bicycle=no`:
  I see no easy solution for that problem here. There may be a central bicycle lane for one direction and a track for the other direction. So in this case, the quest should be deactivated.
2. ***resurvey***: Currently missing side prefixes lead to immediate resurvey, as far as I know. This needs to be disabled for roads with `bicycle:lanes`. Resurvey after a specific time, or to add  a missing `cycleway:lane=exclusive`/`cycleway:lane=advisory` should still work, as long as _point 1: tagging_ is resolved.

**Comment by matkoniecz** [comment]
I think that skipping very complex cases (with `bicycle:lanes`) would be a good fix.

**Comment by westnordost** [comment]
I don't think it is incorrect.

It is simply different levels of details. I see it as that `bicycle:lanes` can be used in addition to the standard `cycleway` tagging to make it more detailed (in complex situations) but it is not a mandatory part for `cycleway:*`-tagging to be correct.

`cycleway:right` is akin to "cycleway in forward direction" (in right-hand-traffic countries).

And there is one. 

There is certainly no cycle track or lane in contraflow on the North side of that segment (because  that section is not a "real" oneway road but just one side of a road where the carriageway is split into two by a traffic island but no differenciation is made with tags in OSM), i.e. there is no `cycleway:left`. So the information is not incorrect.

**Comment by matkoniecz** [comment]
I was thinking about skipping it not because `cycleway:*` tag is useless but because often it will be confusing or impossible to answer it with SC.

For example there are segments of road with cycleway lane in the middle. Not sure how it would be tagged but `cycleway:right=lane` would be wrong.

https://www.google.pl/maps/@50.0580548,19.9252347,3a,75y,79.24h,81.01t/data=!3m6!1e1!3m4!1s2IjRB6iYdiNIbbbuhtuqTw!2e0!7i13312!8i6656

![screen02](https://user-images.githubusercontent.com/899988/144868591-5ae2ec60-64a4-4203-b148-b80887c52f6c.png)

**Comment by matkoniecz** [comment]
> I don't think so. It is on the right side of the road, i.e. in forward direction.

Oh. It was not how I thought about this tag but it makes sense to me.

OSM Wiki page maybe should mention this if there is clear consensus for such meaning, see for example https://wiki.openstreetmap.org/wiki/Key:cycleway:right (not planning to change that as I am not really sure).

**Comment by BalooUriza** [comment]
I think the long term answer is fixing OSM's broken lane tagging scheme...

**Comment by matkoniecz** [comment]
> I think the long term answer is fixing OSM's broken lane tagging scheme...

This is utterly offtopic on this specific issue - it is how to deal with specific part of an existing tagging schema.

**Comment by BalooUriza** [comment]
Oh, well, then there's no automatable answer for this in the existing
scheme.

**Comment by westnordost** [comment]
So, closing this as will not fix / question.

**Comment by matkoniecz** [comment]
I will change it to the question, as it is "SC tags correctly, there is no bug here" not "SC will not tag correctly in this case, WONTFIX"
