### ISSUE TITLE
Quest list started failing on CI

### ISSUE THREAD

**Issue by matkoniecz** [streetcomplete/StreetComplete#3569]
https://github.com/streetcomplete/StreetComplete/blob/master/.github/generate-quest-list.main.kts started failing, what I noticed in https://github.com/streetcomplete/StreetComplete/runs/4431608400?check_suite_focus=true

I have not investigated exactly what went wrong

Pinging @FloEdelmann as author of that script and let know recent editor of https://wiki.openstreetmap.org/w/index.php?title=StreetComplete/Quests&action=history ( https://wiki.openstreetmap.org/wiki/User_talk:MalgiK#SC_quest_list )

**Comment by matkoniecz** [comment]
Also, maybe at top of this file it would be useful to mention what and why this script is doing? (maybe I will do it later based on commits that created it)

**Comment by westnordost** [comment]
(removing bug label because it is not a bug in the app)

**Comment by FloEdelmann** [comment]
Fixed in #3571. This workflow confirms it's working again: https://github.com/streetcomplete/StreetComplete/actions/runs/1549486148

I also added a comment a the top of the file to explain what the script does. @matkoniecz If it's still not clear enough, feel free to ask here or fix the comment yourself.
