### ISSUE TITLE
Can't solve resurvey quest after changing interval

### ISSUE THREAD

**Issue by Helium314** [streetcomplete/StreetComplete#3588]
**How to Reproduce**
Have resurvey intervals set to`Default`
Have an opening hours resurvey quest displayed that is eligible for `Default` interval, but not for `Ask less often` interval
Set resurvey interval to `Ask less often`
Answer anything except `It does not exist...` or `Can't say...` with leaving a note (those 2 answers work normally)
The quest does not disappear, and is not counted towards solved quests
(Restarting the app does not make the quest disappear)

**Versions affected**
v38.1 on Android 9

**Comment by westnordost** [comment]
The `QuestController` checks on answering a quest if it is actually still applicable. If it is not, I will not do anything. Since the interval changed, it is not applicable anymore. See this comment why this is done.

https://github.com/streetcomplete/StreetComplete/blob/d9de484a1ea94bf913deee4f2837bc977c61cdaa/app/src/main/java/de/westnordost/streetcomplete/data/quest/QuestController.kt#L191-L203

**Comment by smichel17** [comment]
If I read this right, reproducing the bug requires you to change a setting while the form is open?

**Proposed solution:** hide the menu (and upload button) while the form is open. This way it's not possible to change a setting while solving a quest, which might lead to unexpected behavior in general (this might not be the only case).

I was actually thinking of proposing this already, because it would increase the amount of available screen space while solving a quest, and I can't see any reason you'd need to open the menu while the form is open.

**Comment by westnordost** [comment]
> If I read this right, reproducing the bug requires you to change a setting while the form is open?

No. Because the quest will not vanish once you change the setting, because only on download and when solving a quest, it is checked whether a quest is eligible for an element.

**Comment by westnordost** [comment]
What could be done is to delete the memory of the app that it had downloaded any map data before (aka marking all map data downloaded as "old"). This would trigger a re-download at the user's current position if he has an internet connection right now. The side effect of that however is that everything else is also re-downloaded again and while he is waiting for the download to finish, this issue will be reproducible.

**Comment by smichel17** [comment]
Hm, I don't understand. My impression was that we have

1. Tables which store the raw OSM data we downloaded (essentially a cache).
2. Other tables which store a list of quests, generated from the raw data.

When the setting is changed, why can't we clear (2) and then re-generate them from (1), which still remains?

**Comment by westnordost** [comment]
StreetComplete can store an unlimited amount of OSM data locally in the database. The user could have downloaded gigabytes of OSM data. To regenerate the quests from that raw data, it would need to be loaded from the database into memory first.

**Comment by smichel17** [comment]
I see. It still seems like there could be a solution, like: Incrementally re-generate the quests based on what's on screen. Basically, use the same logic as when they are downloaded, but replace the "download & persist in db" steps with "load the equivalent area from the db".

That seems like a lot of work. Maybe instead we could filter based on the interval when we fetch quests from the db instead of when we create them. Meaning,

1. Always create resurvey quests for the longest period.
2. Store the `modification_date` in the quest table.
3. When selecting quests, if the type is a resurvey, add a `WHERE modification_date > ?` (where `?` is the cutoff based on the preference)

**Comment by Helium314** [comment]
> The `QuestController` checks on answering a quest if it is actually still applicable. If it is not, I will not do anything.

Why is the quest not removed if it is not applicable any more?
This would still result in the answer not counting, but at least the quest is gone.

> Maybe instead we could filter based on the interval when we fetch quests from the db instead of when we create them. Meaning,
> 
> 1. Always create resurvey quests for the longest period.
> 2. Store the `modification_date` in the quest table.
> 3. When selecting quests, if the type is a resurvey, add a `WHERE modification_date > ?` (where `?` is the cutoff based on the preference)

I like this idea, It's not really intuitive that I need to re-download to apply changes in resurvey interval (which I use to influence quest density).

Another way how this could be solved is by setting the resurvey interval to the shortest value while checking whether the quest is still applicable.

**Comment by matkoniecz** [comment]
> I like this idea, It's not really intuitive that I need to re-download to apply changes in resurvey interval 

+1, it was also quite confusing to me

**Comment by westnordost** [comment]
The table idea won't work because different quests look on different `check_date:<key>`. The logic to persist quests is independent of the individual quest types.

Removing the quest in that case could work.

Setting the resurvey interval temporarily tto another value wouldn't be clean code in the way the code is currently structured. The multiplier for the interval is a global setting. So, the quest download process might currently be creating quests in a background thread, so we certainly don't want to change the setting right then.

**Comment by smichel17** [comment]
> The table idea won't work because different quests look on different check_date:<key>. The logic to persist quests is independent of the individual quest types.

Hm. I guess also it might be a PITA to query, since different quests use a different duration (or maybe not: make a temporary table of quest types and cutoff dates and then JOIN on the quest tables we're querying).

Slight modification: add a `resurvey_interval` column to the quest table(s), which is an integer from 1-3. On quest generation, we store which interval it matched: short→1, default→2, long→3. Then we select `WHERE resurvey_interval <= ?`.
