### ISSUE TITLE
Add in-app log viewer

### ISSUE THREAD

**Issue by mnalis** [streetcomplete/StreetComplete#3597]
**Use case**
To help debug issues, in-app log viewer would be useful.

**Proposed Solution**
It has been mentioned several times by @westnordost, and that @matkoniecz might want to do it and that the ticket for it would be created, but is seems to have slipped, so I'm opening this one.

See for example https://github.com/streetcomplete/StreetComplete/issues/3290#issuecomment-946175907, https://github.com/streetcomplete/StreetComplete/issues/1892#issuecomment-848214943, https://github.com/streetcomplete/StreetComplete/issues/3406#issuecomment-949252071

**Comment by westnordost** [comment]
I guess this is forthcoming of you, but I don't need a public issue in this tracker for everything I plan to do for this app.

**Comment by westnordost** [comment]
Is this something I can assign to you, @matkoniecz ? I think I rememeber you mentioning you wanted to work on this?

**Comment by westnordost** [comment]
Here is a rough outline how it should look.

## Interface-wise

I think easiest would be to let our `Log` object have the same interface as the Android one, so no code changes other than changing the import are necessary. Roughly it shall look like this:

```kotlin
interface Logger {
  fun i(tag: String, message: String)
  // ... etc
}

object Log {
  var instance: Logger? = null

  override fun i(tag: String, message: String) = delegate?.i(tag, message)
  // ...etc
}

class AndroidLogger : Logger {
  // implement...
}
```
And on application start, `Log.instance = AndroidLogger(...)` is set.
In tests, it is simply not set or some `TestLogger` (or mock) that does some testing is used.

## Implementation-wise

The AndroidLogger should append the logs into a database table. Logs that exceed a certain size (or age) must be deleted. 
Additionally, it could append the log to the system log (as now) but not sure if this is necessary or useful. 

## UI

In the about screen next to the links to reporting a bug etc, there should be a link to a list-view of the log. For the best utility, it should have the following features:
- filter by string
- supply start and end date+time
- dropdown for selecting which severity to display (verbose, debug, info, error), like in Android Studio
- a way to export the filtered log output*

\* since the app should not require file storage permission, exporting to a file in e.g. Downloads directory is out of question. Maybe "copy to clipboard" would work. Or "attach to mail (to streetcomplete_errors@westnordost.de)" would work. Maybe there is a better idea.

Furthermore, whenever a crash report is sent, the part of the log directly preceding the crash should also be attached to the error-report mail.

So, the log messages from the database are 1. displayed in a RecyclerView list and 2. can be converted into a newline-concatenated string

**Comment by westnordost** [comment]
@matkoniecz did not start working on it yet, so for the time being, this is free for the taking / can be done by other people interested in this. If you do, I can assign you to "reserve" this.
