### ISSUE TITLE
Australia: speed up pedestrian crossings entry

### ISSUE THREAD

**Issue by jamescridland** [streetcomplete/StreetComplete#3610]
**Use case**
Australia uses [a standard pedestrian crossing button](https://www.australiangeographic.com.au/blogs/dr-karl-need-to-know/2016/07/the-pedestrian-button/), which is in place at every pedestrian crossing in the country. It does three things:
1. A button to request a walk signal
2. Sound signals for the blind
3. A tactile indication for when it's safe to cross

This is a standard on every pedestrian crossing in the country, and [known as the PB/5](https://theconversation.com/sublime-design-the-pb-5-pedestrian-button-26232). It replaced previous buttons in place since the 1960s which also had sound signals and tactile indications. (They're quite clever, incorporating a microphone for noise ambience, to make the noises it makes audible over traffic noise).

Currently, within StreetComplete, there are three questions asked by default around pedestrian crossings:
1. Do these traffic lights have a button to request a walk signal?
2. Do these traffic lights have a tactile indication for blind people for when it is safe to cross?
3. Are there sound signals for the blind here?

![image](https://user-images.githubusercontent.com/231941/147712288-72ffa5f8-ba78-4392-9e88-291ab117871e.png)

If 1 is true, then automatically 2 and 3 are true. Always. Every single time.

**Issues with the current implementation**

First, it's three questions to answer, rather than one; and second, the availability of the tactile indication isn't very well known by able-bodied people - the help information refers to the rotating cone at the bottom of British crossings, and it could be that users answer this question negatively. The PB/5 features a vibrating touch panel on the front of the unit. In the pictures, it's the bit in the middle of the big tactile arrow.

**Proposed Solution**

Do not bother the user with questions 2 and 3, above. We already know the answer is "yes".

`if
(country="Australia")
and
(these traffic lights have a button to request a walk signal)
then
(these traffic lights have a tactile indication and sound signals)`

**Less good solution**

Amend the help text to read:

_Hint: Often this is a vibrating button or rotating cone on the bottom of the traffic button case, or a touch panel on its front._

**Comment by smichel17** [comment]
Is it be possible for you to take a photo (or find a photo under a suitable license) of such a box, specifically the touch panel? Then we could show that image in Australia instead of the current picture.

**Comment by jamescridland** [comment]
Absolutely! I'll do that, and post it here (and link to a higher-quality version).

If you can set the hint text per country, then perhaps the hint text could be:

_Hint: standard Australian crossing buttons have a vibrating touch panel in the middle of the arrow, and sound signals._

**Comment by smichel17** [comment]
I believe you should be able to just add an `en-AU` (I think that's the right code) translation. You can add it yourself in POEditor, see https://github.com/streetcomplete/StreetComplete/blob/master/CONTRIBUTING.md#translating-the-app

**Comment by jamescridland** [comment]
"Then we could show that image in Australia instead"

is not exactly the same as 

"Then we could show that image for users using an en-AU interface instead"

I guess it's close enough in this instance: but many people use en-GB or en-US all over the world, not just in the countries that it pertains to. Indeed, many devices have no concept of en-AU (just ask my old Android WatchOS smartwatch, which doesn't have that as an option).

This sort of application really needs "then we can show that image when the POI is in Australia", rather than the interface language.

**Comment by smichel17** [comment]
I remember something to do with mobile country codes, which is used for showing localized imagery regardless of which language is selected on the phone. I *think* it was discussed in https://github.com/streetcomplete/StreetComplete/pull/3199 or something related.

**Comment by andrewharvey** [comment]
Your proposed solution sounds good. I was not 100% sure myself that all buttons had the tactile + sound and in every state. I came across some that didn't have sound but I think maybe it was just broken.

**Comment by jamescridland** [comment]
Here's an image I've just taken of a PB/5. The middle of the arrow is the vibrating touch panel.

This is my photograph - the [original is here](https://photos.app.goo.gl/x4dzGn9ngV7BzHve6). I assign this as public domain, and am happy for anyone to use this image however they like.

![image](https://user-images.githubusercontent.com/231941/147720663-6af27e23-4fe4-4d22-80ca-077e141356f4.png)

**Comment by westnordost** [comment]
Hmm, I **think** in Germany, any new crossings installed will also have a vibrating button for the blind. But old crossings don't have this and we don't know how old these are.

My point being: Will really **all** crossings with a "request green light" button have both a vibrating button **and** sound signals? Even those that haven't been modernized since - I don't know - 60 years? Note that the vibrating button part may be integrated in the button, but the sound signals are not, the speakers need to be installed independently on the traffic lights post on the other side of the road.

In general, we need to be very wary of automatisms in StreetComplete that just silently assume certain properties because, well, such assumptions may be wrong and at the same time, the user won't even notice that StreetComplete tags it wrongly. Hence, for such automatisms, we really need to be 1000% sure it is always the case.

What can be done in any case, however, is to show your example image in the second quest instead of the image with the yellow button. By the way, why is there a grid in the sky?

**Comment by westnordost** [comment]
Okay it looks like the speakers are in the button themselves, i.e. the blind should not follow the sound to the other side but just take it as the cue to start walking now. In any case, my concern remain: https://www.youtube.com/watch?v=WQKf8MV-GEw

**Comment by jamescridland** [comment]
The speaker is in the button itself (and is also the thing that makes the vibration). The blind do actually follow the sound to the other side - you know where to walk (thanks to the arrow), and once in the middle you can hear the other side's sound guiding you in.

(That sound, incidentally, is in Billie Eilish's hit "Bad Guy" in the chorus, if you want some pop trivia).

I hear your concern that older crossings may not have been updated, and that automating the three answers into one may not be the correct thing to do. I'll research this a little further, as to whether all pedestrian crossings have been updated. 

"Why, by the way, is there a grid in the sky?" - that's the net keeping the COVID out. The Australian government has put it everywhere. Do you not have it? ;)

But, more seriously - on the left, the very traffic push button I photographed, and the mirrored tower block on the right that, as you can see, does a good job of mirroring the blue summer sky.

![Screenshot_20211230-215213](https://user-images.githubusercontent.com/231941/147749642-041f5ba4-1a6d-489c-a728-41f5e1b1eeeb.png)

**Comment by jamescridland** [comment]
As a pedantic point, my research leads me to discover that there are some pedestrian crossings which do not make noise in the late evening and overnight - mainly in residential areas, where the constant chirping of these buttons is automatically turned off after a certain time. So strictly, we actually don't know if a pedestrian crossing always makes a noise - just that it made a noise (or didn't) when the Street Complete user was there.

Each button is €733 by the way.

**Comment by jamescridland** [comment]
It seems that in parts of the country, [an older style is in use](https://www.reddit.com/r/melbourne/comments/4r60kg/old_style_pedestrian_crossing_button_still_in/?utm_medium=android_app&utm_source=share) - they still make the noises though, but have no tactile vibrating pad.

You learn a new thing every day.

**Comment by peternewman** [comment]
> As a pedantic point, my research leads me to discover that there are some pedestrian crossings which do not make noise in the late evening and overnight - mainly in residential areas, where the constant chirping of these buttons is automatically turned off after a certain time. So strictly, we actually don't know if a pedestrian crossing always makes a noise - just that it made a noise (or didn't) when the Street Complete user was there.

That's the same in the UK, maybe we need some hint text around that. Personally I only tag them when I've heard them chirp. I also wonder if some may only chirp when the button was used to request a crossing, rather than every time if they're on a timer.

What we also get in the UK is if there is a crossroads or other junction and they don't make all directions green for pedestrians simultaneously, they often don't have any sound so you don't hear the wrong sound and cross at the wrong time (but vibrating/spinning bits could still happen). Is that also definitely never the case in Australia?

As the reverse of this, could we build a list of countries where the vibration is built into the button box for example, and therefore tagging it as having no button to request signals would automatically tag it as having no tactile indication, which feels like a far safer approach. After all, as a sighted person, if there is somewhere other than the button box which has tactile indication, I don't know about it so I'll tag it as no anyway.

**Comment by jamescridland** [comment]
Peter - even the old versions (almost all phased out) make a noise here in Aus. They also constantly make a noise, unlike the ones in the UK - they have a quiet chirp to help you find the box, a loud announcement that the lights have changed, and a more urgent chirp to get you to the other side. The British ones just bleep when you can cross.

> if there is somewhere other than the button box which has tactile indication, I don't know about it so I'll tag it as no anyway

Well, indeed. The [spinning cone](https://www.gosocial.co/pedestrian-crossings-have-a-secret-button-this-is-what-its-for/) at the bottom of some (but not all) UK pedestrian crossing buttons is a revelation to most people. I don't know whether the newer one (the one that doesn't have a big light saying "WAIT" on them) has any tactile indication at all - I assume it must do.

**Comment by smichel17** [comment]
> I also wonder if some may only chirp when the button was used to request a crossing, rather than every time if they're on a timer.

This is how they all work in the US. When I answer the quest, I push the button and wait for the signal to see what happens. (Sorry cars)

**Comment by westnordost** [comment]
And I look for the loudspeaker on the other side, it's usually well visible

**Comment by peternewman** [comment]
> Peter - even the old versions (almost all phased out) make a noise here in Aus.

But what about crossings with no button box, or don't you have those in Australia?

> The British ones just bleep when you can cross.

The document linked below says we've got (or had) two styles, but I'm not sure either help you find them.

> > if there is somewhere other than the button box which has tactile indication, I don't know about it so I'll tag it as no anyway
> 
> Well, indeed.

So there aren't tactile indications without button boxes in Australia? Or again are there just no crossings without button boxes?

> I don't know whether the newer one (the one that doesn't have a big light saying "WAIT" on them) has any tactile indication at all - I assume it must do.

I've certainly tagged lots with tactile indication, including I think some newer ones, but I've not paid too much attention to box design.

> This is how they all work in the US (if they make noise). When I answer the quest, I push the button and wait for the signal to see what happens. (Sorry cars)

So it sounds like we should probably add a note, so people don't cross, not hear the noise, and mark it incorrectly as no.

> And I look for the loudspeaker on the other side, it's usually well visible

Unless I've been very unobservant in the UK for all my life, I'm not sure if ours have a discreet speaker.

Indeed this confirms at least some don't:
https://tsrgd.co.uk/pdf/tal/1991/tal-4-91.pdf

> Two types of audible signal are available. The standard unit, located in the pedestrian push button box

**Comment by smichel17** [comment]
To be clear, in the US:

- There are definitely boxes that beep when you touch them and beep when it is time to cross, but do not beep otherwise.
    - It's usually a two-tone beep. There may or may not be a variant that does a one-tone beep to indicate that a signal has been requested; my memory is failing me here.
    - There also exists a variant that talks to you. "Wait" is the only word I remember.
- There are definitely boxes that make no noise, either when the button is pressed or when it is time to cross.
- I am not sure if there are boxes that are silent when pressed but beep when it is time to cross.
- I do not think I have encountered a box which vibrates.
    - Anecdote: It took me a long time to realize how the boxes in Germany work. "If it clicks all the time, how are you supposed to know when it's time to cross?"

**Comment by peternewman** [comment]
Are there any crossings without boxes at all, where there are still audible or tactile indications of when it's safe to cross though @smichel17 ? Or does every crossing have a box with buttons?

**Comment by smichel17** [comment]
There are definitely crosswalks without boxes, with visual signals that are timed with the traffic light. I've encountered these mostly in NYC (Manhattan). I don't remember if they make noise.

**Comment by westnordost** [comment]
Okay, so I decided to not have special per-country rules that automatically assume and tag certain properties of traffic lights etc. for now.

It would involve to maintain a list of in which countries every button can be assumed (100%) to have certain properties. This is a bit much. What could be done instead is to disable these quests for Australia completely if this is really such a non-information because it is always the same.  But then, any data consumer that evaluates this data in Australia or internationally would need to know that in certain countries (such as Australia, etc.), (at least) `button_operated` always implies facilities for the blind. So I'd rather not disable this quest.

Furthermore, maintaining such a list to "smartly" tag additional properties would be a precedent. StreetComplete usually does not tag more than what the user explicitly answered. And I fear this would open a whole new can of worms in regards of maintenance but also liability, because in case there are mistakes (it is not 100%), StreetComplete (that is, I) will be liable for the wrongly inserted data.
It is also a matter of trust (towards the user), that StreetComplete does not tag anything more than explicitly answered by the user and not assume more things.

### However

I'll just take the example picture of the button box and have it displayed for Australia
