### ISSUE TITLE
Misleading changeset log "Add bollard type", even when removing the bollard

### ISSUE THREAD

**Issue by golden-spiral** [streetcomplete/StreetComplete#3632]
**How to Reproduce**
Select "does not exist" on bollard type, changeset log states "add bollard type" while removing the tag.

**Versions affected**
Android 10.0 with StreetComplete 38.2

**Comment by westnordost** [comment]
Not only bollard type - any quest that allows to remove the element if it does not exist. The removals are put into the same changeset (=same message) as any normal answers so that it is clear in which context the bollard (etc.) was removed. Changing the wording to for example "determine bollard type" wouldn't solve it. 
So, this is a will not fix because the alternative would be more work for me and also possibly more confusing/less helpful (e.g. an own changeset for removed things means the context in which it was removed is lost).
