### ISSUE TITLE
Freeze and crash after the launch

### ISSUE THREAD

**Issue by deevroman** [streetcomplete/StreetComplete#3656]
**How to Reproduce**
1. Open SC
2. Wait for the SC to start looking for quests

**Versions affected**
SC: 39.0
Android 5.1.1
Samsung Galaxy J1

[logcat_01-19-2022_19-40-30.txt](https://github.com/streetcomplete/StreetComplete/files/7898941/logcat_01-19-2022_19-40-30.txt)

**Comment by westnordost** [comment]
Hm, it looks as if there is a stack trace in the log you attached, but it is incomplete. Can you tell me the area in which the app looked for quests?

**Comment by deevroman** [comment]
openstreetmap.org/#map=17/59.93703/30.49533

**Comment by deevroman** [comment]
Here are two more different logs. I see OutOfMemoryError there. There really isn't a lot of memory on my device, but it's strange that SC bumped into the memory limit after the update.
[logcat_01-20-2022_00-50-41.txt](https://github.com/streetcomplete/StreetComplete/files/7900819/logcat_01-20-2022_00-50-41.txt)
[logcat_01-20-2022_00-57-32.txt](https://github.com/streetcomplete/StreetComplete/files/7900821/logcat_01-20-2022_00-57-32.txt)

**Comment by westnordost** [comment]
Ah, I see. I tried download that area, it worked without a problem. In fact, the whole download took less than one second on my device, so it can't actually be that much data. The amount of data downloaded varies **a lot** depending on the area.

An out of memory exception is unfortunately nothing I can do much about. I would say that the app definitely uses more memory than your average Android app. After all, it needs to download and parse all that OpenStreetMap data, and that can be a lot. But actually, it is quick in freeing this memory again. For example, I expect that every other OpenStreetMap editor out there would, after it downloaded the area you want to edit, keep this downloaded map data in memory. StreetComplete does not do that. After downloading and persisting it to the database, the memory is freed again - only for the short period of analyzing the data for quests it is kept in memory, then it is freed. There is no way around that. So, during the download is the point where the app uses the most memory. If it crashes because of an out of memory exception, then likely there.
But as said, there is nothing really I can do about that.

IF you have an Android development environment set up and would like to investigate if there are really no memory leaks (but I am quite sure of that!), feel free to do so. The Android Studio IDE does have the capability to profile and monitor the current memory for the debugged app.

**Comment by westnordost** [comment]
There are also not really in-memory caches for data persisted to the database, so there is nothing really that could be freed when the Android system calls `onLowMemory` on the activity/application.

**Comment by deevroman** [comment]
I decided to reinstall the app. And now it freezes already on the Welcome screen. Also now the system itself offered to send a report, which I did.

**Comment by Helium314** [comment]
> Ah, I see. I tried download that area, it worked without a problem. In fact, the whole download took less than one second on my device, so it can't actually be that much data. The amount of data downloaded varies **a lot** depending on the area.

Auto-download likely fetches a larger area than manual download.

@deevroman are you on WiFI or mobile data? On mobile data, auto-download radius is smaller and maybe then there is no crash.
I also had crashes due to memory usage recently, but turned out that was because my phone had `dalvik.vm.heapgrowthlimit` set to 96 MB, meaning if SC required more than 96 MB it would be killed. Changing to 192 fixed the problem.

**Comment by deevroman** [comment]
Changing `dalvik.vm.heapgrowthlimit=192m` helped!
> [Edit: ok, freezing at welcome... so it's maybe not always OOM?]
After scrolling through the starting messages, there was already a part of the quests on the map. It seems that SC is already on the start screen trying to load them.

**Comment by westnordost** [comment]
Yes,  but only of it has location permission. Which it has on Android 5.1 because there are no runtime permissions yet

**Comment by westnordost** [comment]
How food you send the crash report? By email?

**Comment by deevroman** [comment]
As I understand it, crash reports that the system offers to send are sent through the Play Market. More precisely, now the system says that the application is frozen, not stopped
