### ISSUE TITLE
Require highway=crossing for crossing quests?

### ISSUE THREAD

**Issue by matkoniecz** [streetcomplete/StreetComplete#3664]
https://www.openstreetmap.org/node/9408546335/history

crossing= traffic_signals
highway=traffic_signals

There is also a highway=crossing node next to it

I am not convinced that it is a good tagging and have not yet checked its popularity but maybe do not ask crossing quests if crossing is not actually tagged?

(I will resurvey situation after return from family trip, it may be limited to part of Barcelona or tagging considered as invalid)

**Comment by westnordost** [comment]
This particular situation is clearly a tagging mistake as far as I know. If the crossing is mapped in enough detail that the place where pedestrians cross the road is tagged on a separate node, then adding `crossing=traffic_signals` on the traffic signals node would be wrong.

`crossing=traffic_signals` is used on 7% of all `highway=traffic_signals`. So, it looks to be accepted in low LOD mapping.

https://taginfo.openstreetmap.org/tags/highway=traffic_signals#combinations

In any case, before you request as a ticket here in the issue tracker to remove support for that, you should do some research on that. This ticket is not actionable because it does not contain the necessary research.

**Comment by westnordost** [comment]
If you plan to check if a feature should be added/removed from StreetComplete, then better put this in your todo list than in the public issue tracker.

**Comment by matkoniecz** [comment]
> This particular situation is clearly a tagging mistake as far as I know. If the crossing is mapped in enough detail that the place where pedestrians cross the road is tagged on a separate node, then adding crossing=traffic_signals on the traffic signals node would be wrong.

I agree. I opened https://www.openstreetmap.org/note/3023628 


> then better put this in your todo list than in the public issue tracker.

Yes, sorry.

> it looks to be accepted in low LOD mapping

What you mean by "low LOD mapping"?

> crossing=traffic_signals is used on 7% of all highway=traffic_signals

So maybe requiring `highway=crossing` would be sadly a good/necessary idea?

Or is it about cases where `highway=traffic_signals` is used instead of `highway=crossing` (is it even correct?)

**Comment by westnordost** [comment]
Low level of detail mapping. Lowest possible detail would be a `highway=traffic_signals` node on the intersection of two roads. Next higher level of detail would be traffic signals at their actual locations, implicitly including the pedestrian crossings (if any). Next higher level of detail would be the "proper" way to have 4 traffic signal nodes and 4 `highway=crossing` nodes at their respective actual locations.
