### ISSUE TITLE
MIUI force dark mode issues

### ISSUE THREAD

**Issue by 32Vache** [streetcomplete/StreetComplete#3677]
On the profile menu, tab 'Resolved quests', certain quests' bubbles are rendering incorrectly with MIUI force dark mode enabled :
![Screenshot_2022-01-25-17-25-20-486_de.westnordost.streetcomplete.jpg](https://user-images.githubusercontent.com/42336759/151018231-dec161ca-7f1a-47af-87bf-815ac8b40fad.jpg)
See here some quests have thier white rendered in black and some colors lightened. Turning off force dark mode in MIUI settings fixes it :
![Screenshot_2022-01-25-17-28-58-870_de.westnordost.streetcomplete.jpg](https://user-images.githubusercontent.com/42336759/151018426-f1c87ba3-36d9-4df4-9593-4359c10bdefe.jpg)

I believe this can be fixed with `android:forceDarkAllowed=false` in the layout xml.

**How to Reproduce**
Turn on force dark mode in MIUI settings on a device running MIUI. This may also happen on other non-MIUI devices that have a force dark mode option.

**Versions affected**
Android SDK >= 29

**Comment by westnordost** [comment]
This app has a dark mode, you can just use that instead of a hack made available by MIUI. If the MIUI hack does not work, it is not really the issue of this app.

To cite the documenation,
> Apps must opt-in to Force Dark by setting android:forceDarkAllowed="true" in the activity's theme
https://developer.android.com/guide/topics/ui/look-and-feel/darktheme

MIUI does not adhere to this. See also the rest of the paragraph in the linked documentation. Force dark should not be applied to views that inherit from `Theme.Material` or `DayNight`. StreetComplete theme inherits from these, i.e. already supports dark mode. There is no reason to use this force dark mode.

I consider this a bug in MIUI.
