### ISSUE TITLE
Bike parking capacity with odd number

### ISSUE THREAD

**Issue by boothym** [streetcomplete/StreetComplete#3679]
When editing or using OSM, I've noticed that sometimes users have tagged bike parking stands as each having capacity=1, rather the normal 2. StreetComplete also mentions this when solving the quest.

Therefore, I think it would be a good idea if StreetComplete could ask users to check the capacity of bike parking where capacity is an odd number. This could possibly be limited to objects which also have bicycle_parking=stands tagged on them.

**Comment by HolgerJeromin** [comment]
What would be the osm tag when the odd number is correct?
See quest requirement:

> Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)

**Comment by boothym** [comment]
I think it would be similar to resurveying of bike parking capacity quest, where I was recently asked to check a capacity that was added 4 years ago.

If there is not a check_date:capacity then any odd capacity numbers should be asked to be surveyed immediately (or at least much sooner than other normal).

**Comment by AlertSubject** [comment]
If the capacity is re-checked every 4 years, isn't it easier to just wait until the capacity will be checked in the future?
Seems like less work than implementing a new quest

Especially since bike parking capacity isn't the most important tag (unless I'm missing something)

Might be easier to just wait it out?

**Comment by boothym** [comment]
Not really. 🤔  You could be out at two nearby bike parking locations, one with capacity=5 (when it should be 10) and one without a capacity tagged. StreetComplete would only ask you about the latter when it should also ask about the former as well.

Basically: **odd number + no check date should be treated as if it has no capacity tagged.**

**Comment by matkoniecz** [comment]
Capacity can be actually odd.

**Comment by FloEdelmann** [comment]
It could be a warning dialog that pops up when tapping the OK button (like in the fire hydrant diameter quest or the maxspeed quest):

> **Are you sure?**
> Note that most normal stands can be used from both sides to park each one bike.
> [I will check] [Yes, I am sure]

That wouldn't even require new strings to be translated.

**Comment by westnordost** [comment]
Hm well, exactly that text you see already prominently in the quest form. For wall_loops and certain (novel) stands, it can actually be odd.

**Comment by boothym** [comment]
@matkoniecz Yes, I am well aware that capacity can be odd, thanks.

Any odd capacities which have check_date:capacity will have been added by a StreetComplete user, who we can assume has already seen the warning. That's why I have said it should only ask about those **without** a check date.

Like this example with capacity=1: https://www.openstreetmap.org/node/1179585913 it has check_date:capacity=2021-08-30 so wouldn't be asked about for a while.

But if it didn't have a check date, then StreetComplete should ask me in the same quest as if it had no capacity tagged.

**Comment by Helium314** [comment]
This means that if there is no capacity, or the capacity is changed, StreetComplete will ask twice: once for filling or changing the value, and then once more for the immediately following resurvey.

> For wall_loops and certain (novel) stands, it can actually be odd.

For normal stands the capacity can be odd as well, e.g. if one side is very close to a wall.

**Comment by boothym** [comment]
@Helium314 sorry, I don't follow - can you explain why it would ask twice?

**Comment by Helium314** [comment]
StreetComplete adds a check date only on resurvey if nothing changed. Otherwise no check date is set, see #1998, #2636 and probably other issues for why.

So if you have a bicycle parking without capacity tagged, and you enter 1, then the capacity is added but no check date. If capacity=1 triggers a resurvey, you will have the resurvey immediately. And since StreetComplete is supposed to set a check date only if necessary, I doubt that always setting a check date when entering (odd) capacity would be acceptable.

**Comment by boothym** [comment]
Hmm, I see, thanks.

Perhaps the check for odd capacity could be delayed so that it only checks objects last edited a few months ago or something?

Or in this situation adding a check date could be acceptable, especially if there was an additional prompt for capacity=odd so you can be more certain the capacity is correct?

**Comment by westnordost** [comment]
Technically this (your first suggestion) would be possible, with some effort. But I don't see the issue really. As I wrote, the quest already notes that one stand usually means capacity=2 and the capacity is re-checked every few years anyway.

**Comment by boothym** [comment]
You don't see the issue of a StreetComplete user who is out surveying being asked to input capacity at one location, but not being asked to check a nearby location where capacity=odd? 

I would've thought the entire point of the bike parking capacity quest is to fill that tag with accurate numbers. Where capacity=odd has been tagged it's very likely that real capacity is double that amount.

And yes I know the quest already mentions one stand is capacity=2, but there's also existing data which is likely to have been added by a non-StreetComplete user.

**Comment by matkoniecz** [comment]
I add odd values relatively often, with a correct tagging. Neither of proposed solutions would work well with them.

**Comment by mnalis** [comment]
I agree with @matkoniecz here, I (unfortunately) too often see badly placed bicycle stands, such that one end is too near the wall to be usable, e.g.:

![small_20210720_133647](https://user-images.githubusercontent.com/156656/152419297-03abf504-88bf-44c8-b087-7b9bde4e33af.jpg)

And this is in front of  (bicycle-related) sports store which should know better. (Still, considering they only had wheelbenders before I pleaded with them to put stands, I find it huge improvement, so I'm grateful for that.)

IOW, let's try trusting the OSM data. If someone put odd number of parking sports for bicycles, we might as well assume they know what they were doing.

Sure, it is possible it is wrong, and if so, it will come resurvey time when it can be corrected. Because, if our initial assumption is that someone might have entered wrong data, where does it end? Will we immediately ask for all roads where there is odd number of lanes entered, because the even-numbered lanes are much more common? Should we ask again for all `smoothness < good` or `lit=no` on all city streets, as there is much more of those, a someone _might_ have entered wrong value?

Relatedly, we have (IMHO) much bigger issue with possibly wrong count of bicycle parking spaces: https://github.com/streetcomplete/StreetComplete/discussions/3704 (i.e. this issue could only err with factor of 2, and the other one easily can err with factor of 30)

**Comment by BalooUriza** [comment]
On Thu, Feb 3, 2022 at 2:16 PM Matija Nalis ***@***.***>
wrote:

> I agree with @matkoniecz <https://github.com/matkoniecz> here, I
> (unfortunately) too often see badly placed bicycle stands, such that one
> end is too near the wall to be usable, e.g.:
>
> [image: small_20210720_133647]
> <https://user-images.githubusercontent.com/156656/152419297-03abf504-88bf-44c8-b087-7b9bde4e33af.jpg>
>
> And this is in front of (bicycle-related) sports store which should know
> better. (Still, considering they only had wheelbenders before I pleaded
> with them to put stands, I find it huge improvement, so I'm grateful for
> that.)
>

There's also some practical applications to this where it might make sense
to put the bike stands against a wall.

[image: image.png]

According to Quiktrip, these stands are intentionally placed where they are
to deter blind people from walking into the sign.  I'm not wholly sure I
buy that explanation, but assuming they can back up the claim there's a
strong case for odd-numbered spaces on stands being a recurring thing.
Especially since there's locations in Kansas where they put traffic
armadillos in the same spot the stands appear in that photo, and pull the
stands outward in a similar, slightly wider pattern where bicycle parking
minimums are a thing.  I got this explaination for the discrepancy when I
asked QT "What's with the weirdly difficult bicycle parking?" since the
sign immediately above is a bonk hazard.  Yeah, it's a gas station but
given the shop is clearly designed to be the main event at any of their
locations with the gas effectively existing only to lure motorists in, I
still felt the need to ask.

That said, I'd call this "capacity 2" but as an edge case, since I'm parked
too far forward to allow the other stand to be of much use, and that's
already pretty far backward for what is intuitive with stands.
