### ISSUE TITLE
Confusing duplicate "gate" answer in "How does this road cross the barrier here?" quest

### ISSUE THREAD

**Issue by mnalis** [streetcomplete/StreetComplete#3717]
**How to Reproduce**

- find the "How does this road cross the barrier here?" quest
- notice there are duplicate "gate" answers with different pictures

![small_Screenshot_2022-02-03-04-15-18-878_de westnordost streetcomplete](https://user-images.githubusercontent.com/156656/152445351-c08782a0-65fd-4a96-9e32-6069198cacbb.png)

I'm not sure if that is the error like in https://github.com/streetcomplete/StreetComplete/issues/2303, or is it perhaps intentional. If intentional, it is confusing (at least to me - I've went to answer and undo to check if it is tagged the same, and it is).

**Versions affected**
SC v40.0-beta1, Android 10

**Comment by westnordost** [comment]
It is intentional, it both tags as `barrier=gate`. Not sure why, I guess to cover both big gates (for cars?) and small gates for hikers. @matkoniecz ?

**Comment by matkoniecz** [comment]
It is intentional - one is tiny gate for pedestrian, one is large gate for cars. As people without OSM experience would be unlikely to tag pedestrian gates as vehicle gate (or vehicle gates as pedestrian gate).

The same name is also intentional to hint that there is no actual difference between them.

I tried fitting both on one combined image but it was not legible.

I considered having longer label with explanation but had no idea about anything clear.

-----------

I am not entirely happy about the solution, but I had no better idea.

I even thought about tagging `maxwidth=small` or something similar for small ones but AFAIK there is no accepted standard for that.

**Comment by westnordost** [comment]
I see

**Comment by 10992-osm** [comment]
For context on the decision, I remembered it was related to the stile request, so I've found the following in #3188:

- https://github.com/streetcomplete/StreetComplete/issues/3188#issuecomment-940367666, where @matkoniecz asked if I would look for the gate photo as the existing wasn't suitable for stile replacement quests
- https://github.com/streetcomplete/StreetComplete/issues/3188#issuecomment-941559934, where I posted what I'd found.

**Comment by arrival-spring** [comment]
Related, but maybe should be a new issue:

Most recent/personally popular answers are sorted to the top, but when you answer with wide gate the pedestrian gate is sorted to the top, and the wide gate doesn't seem to change position. It doesn't really matter, but is a bit confusing and is inconsistent.

**Comment by smichel17** [comment]
A new issue would be good
-- 
To respect your time, I try to write short, functional emails.

**Comment by westnordost** [comment]
Most likely a wnf though

**Comment by arrival-spring** [comment]
Are the two items not distinguishable because they reference the same barrier type item?

**Comment by westnordost** [comment]
yes

**Comment by mnalis** [comment]
there has been more (independently reported) discussion on confusion caused by this in https://github.com/streetcomplete/StreetComplete/discussions/3729

**Comment by matkoniecz** [comment]
This for was changed to show only larger gate with description "Gate, any size"
