### ISSUE TITLE
Undo changes after a way was split

### ISSUE THREAD

**Issue by kmpoppe** [streetcomplete/StreetComplete#3765]
**How to Reproduce**
1. Given is a way with the quests AddSidewalk and AddRoadSurface applying to it, AddSidewalk is ordered to be answered before AddRoadSurface in the user settings.
2. Answer the AddSidewalk quest.
3. For AddRoadSurface split the way once somewhere along the way.
4. Undo the AddSidewalk answer.

**Result**
One of the splits (presumably the one that will retain the original changeset history?) returns to asking for AddSidewalk, the other split  remains asking for AddRoadSurface and will only show AddSidewalk after AddRoadSurface was answered. This is only rectified after explicitly searching for new quests (or existing and restarting the app).

**Expected Result**
As the Undo function remove the information about AddSidewalk from both splits (which is expected behaviour!) I would expect both splits to follow the quest order.

**Possible solution**
Resurvey changes for any split way when an answer on that way was undo'd.

**Versions affected**
39.1

**Comment by smichel17** [comment]
@kmpoppe For readability, I would suggest splitting the first step into two:

1. Find a way with the quests AddSidewalk and AddRoadSurface applying to it.
2. Make sure AddSidewalk is ordered to be answered before AddRoadSurface in the user settings.

**Comment by smichel17** [comment]
I agree this should be considered a bug; from the user's perspective, it is clearly the wrong behavior. However, I am pretty sure it will be **hard/impossible to fix**.

- "Splitting a way" is implemented as shortening the existing way on one side, and then creating a new way on the other side. The shortened segment retains the history of the original way, but the new segment looks in the OSM database like a totally new way. Doing it differently (so that both halves would remain associated) would require a major change in OpenStreetMap.

- StreetComplete is implemented assuming that each quest applies only to a single element (related: https://github.com/streetcomplete/StreetComplete/issues/3749#issuecomment-1036541910). So, when the way is split, the AddSidewalk history entry continues pointing at the shortened segment; it knows nothing about the new segment, so it is not able to revert the change for that segment. Doing it differently would require a major change in StreetComplete.

All that said, @westnordost I do wonder if this situation is similar to when we switch to local processing of OSM data instead of overpass queries to find quests— lots of work, but enables a fundamental improvement in what features are possible.

I added a section to https://github.com/streetcomplete/StreetComplete/discussions/2789#discussioncomment-1058716 to keep track of issues that are blocked by this. Maybe eventually it gets long enough that you can apply for another grant to do this work.

If someone wants to trawl through old issues, I'm pretty sure you can find more issues blocked on this feature to add to the lis

**Comment by westnordost** [comment]
Sorry, @smichel17 , I know you are trying to be helpful, but your assumptions are not correct.

**Comment by westnordost** [comment]
@kmpoppe With auto-sync on or off?

**Comment by westnordost** [comment]
So I think with auto-sync on, you'll find exactly this situation like described. Setting the sidewalk and splitting the way has been uploaded already. Undoing the setting of the sidewalk will only undo the setting of the sidewalk on the way it was originally answered for (before it was shortened). And this can not be changed or fixed. The whole "splitting of a way" thing and complexity of it (and "undo" for that matter) is working around the fact that the OSM API doesn't even have a concept of splitting a way nor a concept of undoing a change. So for the OSM API, that other way segment is a new element and there is no connection to the other previously longer way segment at all.

For auto-sync off, it will theoretically do exactly what you would like it to, which is why the sidewalk quest comes back after you undid the quest and hit the download button again. I.e., the sidewalk answer has been undone for both road sections. The reason why you don't see the quest again until downloading again is because the `MapDataWithEditsSource` (which holds the modified map data) thinks that only elements referred to by the edit(s) being undone could have changed and thus the `OsmQuestController` (which re-creates the quests) is notified only of the change of the original way segment.

Hence, when undoing a single edit, making `MapDataWithEditsSource` notify `OsmQuestController` of _**all**_ elements that will be added/updated/deleted by any of the edits not uploaded yet will very likely solve this problem:

```diff
--- MapDataWithEditsSource.kt
+++ MapDataWithEditsSource.kt
@@ -145,20 +145,17 @@
             val mapData = MutableMapDataWithGeometry()
-            val elementsToDelete: MutableList<ElementKey>
             synchronized(this) {
+                /* Local changes need to be rebuilt on every deletion of an edit because that edit
+                *  may have been pulled out from the middle of the edit queue. But the edits must
+                *  be applied in order. So, we just re-apply all the changes from the edits. */
                 rebuildLocalChanges()
-
-                elementsToDelete = edits.flatMap { elementEditsController.getIdProvider(it.id).getAll() }.toMutableList()
-
-                for (edit in edits) {
-                    val element = get(edit.elementType, edit.elementId)
-                    if (element != null) {
-                        mapData.put(element, getGeometry(edit.elementType, edit.elementId))
-                    } else {
-                        // element that got edited by the deleted edit not found? Hmm, okay then (not sure if this can happen at all)
-                        elementsToDelete.add(ElementKey(edit.elementType, edit.elementId))
-                    }
+                /* When local changes have been rebuilt, we call onUpdated for **all** elements
+                   that have been modified instead of just the elements that had been touched by
+                   the deleted edits because edits can affect multiple elements.
+                   E.g. set sidewalk on way, then split the way in another quest -> sidewalk has now
+                   effectively been set on two elements now.  */
+                for (element in updatedElements.values) {
+                    mapData.put(element, getGeometry(element.type, element.id))
                 }
             }
-
-            callOnUpdated(updated = mapData, deleted = elementsToDelete)
+            callOnUpdated(updated = mapData, deleted = deletedElements)
         }

```

This is the sledgehammer approach. Because this means that every time you undo an edit, quests need to be regenerated for _**all**_ elements that have been edited by any of your edits. Especially if you have hundreds of unsynced edits, this will lead to performance issues.

I decided to will-not-fix this issue because:
- the issue remains for users that immediately upload changes to the OSM database and is not really fixable there
- I assess the current behavior to be less of a nuisance than the performance issues that would ensure for the proposed solution. Plus, the behavior now resembles more closely what you can expect with auto-sync on.
