### ISSUE TITLE
Quest for ATM names does not take non-bank operated ATMs into account

### ISSUE THREAD

**Issue by Hidooo** [streetcomplete/StreetComplete#3772]
**Use case**
The ATM quest is currently phrased "What’s the name of the bank for this ATM?" in English. I looked up the ATM in front of me and found out that it is in fact operated by a private security company, with no connection to any bank (_Kontanten_, about 450 ATMs in Sweden). Unsure about what to answer I left a note instead, and from what I gathered from the wiki, added the company as operator. Not sure if this is correct, however, or if there is another tag that could be used. For the record, most ATMs in Sweden are operated by Bankomat, a company jointly owned by _all_
banks, so the current phrasing wouldn't be correct there either. 

**Proposed Solution**
Change question to "What's the name of this ATM?" or similar.

**Comment by matkoniecz** [comment]
The problem is that ATMs do not really have names either.

The hope was that Bankomat/Euronet is approximately a bank, and would be treated this way by mappers.

**Comment by Hidooo** [comment]
Ah, just tried it and it does indeed work as you describe. I didn't even input anything in the textfield to get the auto-suggestion to come up. 

But I still think that asking what bank an ATM is for is misleading, as [this comment](https://github.com/streetcomplete/StreetComplete/issues/203#issuecomment-301271045) also states. The Wiki refers to "Name of bank or organisation operating the cash machine." for the operator tag, and this would be more fitting. 

"What's the bank or organisation/company behind this ATM" or something like that. 

Is there any way to see if users are able to answer a quest consistently, or can you search for notes containing "_Unable to answer x_"? Because if I'm the only one stumped by this quest, it is a non issue, but otherwise I think it should be changed. :)

**Comment by Hidooo** [comment]
Thanks! Alright, seems to be only me and another user in Vienna. Closing this then.

**Comment by Riksu9000** [comment]
In Finland the most common ATM is Otto, which is not operated by a bank. Apparently the operator should be Loomis Automatia Oy according to https://otto.fi/en/, but I haven't seen the operator marked in photos of Otto machines https://fi.wikipedia.org/wiki/Ottopiste. These machines have names, and there are a few types, Otto, TalletusOtto, OttoPlus and ValuuttaOtto. It would be incorrect to say TalletusOtto is an operator instead of a name.

It would be nice if there was an option to answer "This ATM is not operated by a bank", then give some hints about how the operator doesn't always have to be a bank, but also give an option to enter a name instead.

**Comment by matkoniecz** [comment]
See also #3782 - "ask about charging station brand, not about charging station operator"

I think the same applies to ATMs but sadly (mis)using operator is quite deeply rooted :(
