### ISSUE TITLE
"What street does ... belong to?" quest "Tap road on map" is unreliable

### ISSUE THREAD

**Issue by adrianclay** [streetcomplete/StreetComplete#3797]
"What street does ... belong to?" quest does not always recognise when I tap on a road.  I've not been able to understand under what circumstances the tap is recognised.

**How to Reproduce**
1. Open a "What street does ... belong to?" quest
1. Attempt to tap a road.  You may get lucky on the first tap, but I've found several taps are required before the name is recognised.

<details>
<summary>Screen recording</summary>

Notice there are 3 taps in total, 2 failed taps, 1 final successful tap

![What street does belong to](https://user-images.githubusercontent.com/976274/155192893-3b394e87-4d6e-4b42-93f6-bf28d9bd134e.gif)

</details>

**Versions affected**
I've tested versions 40.1 and 40.2 on a physical device.
4cf48d2b0058d750494b01cafb70b2e8c6b80883 on an emulated device (screen recording above).

I don't recall this issue happening when using 40.0, however I couldn't confirm this.

**Comment by riQQ** [comment]
Rotated GIF for easier viewing:
![rotated GIF showing bug](https://user-images.githubusercontent.com/3404787/155212984-65312427-1dad-4043-a5ae-f5bb91827ed7.gif)

**Comment by mnalis** [comment]
I can confirm it happened several times in last few days to me too - I didn't yet report it because I was running my own [modified fork of v40.1](https://github.com/mnalis/StreetComplete/actions/runs/1870355694) and it happens only sometimes, so I wasn't yet able to reproduce it in upstream vanilla version. It didn't happen to me in 39.0 and before.

**Comment by smichel17** [comment]
FYI, if you enable developer settings in your phone, there is a setting to show touches, which makes it more obvious what is happening in a screen recording like this.

**Comment by westnordost** [comment]
Ah... this is because querying by bbox on the map (which the tap does) now works the same way as querying from OSM API. So, if the tap is not close to a node of the way, it won't return anything... :-|

**Comment by joe27g** [comment]
It's unfortunate that further mitigation of this issue isn't planned. I've encountered this dozens of times and it can be very frustrating. The usability of the app is significantly lower in areas with long, straight roads (where mappers usually don't add unnecessary nodes), especially in dense residential areas where you have to zoom in really far to see all quests. The more you have to zoom in, the worse the problem is, because for each quest, you have to go through a process:

- Tap on the street quest icon
- Zoom out
- Scroll near the end of the road (if necessary)
- Tap on the street and complete the quest
- Scroll back to your position (if necessary)
- Zoom in until all the quests are visible again

Going through a multi-step process instead of 3 taps makes it significantly slower to survey affected areas.

If I had the knowledge to do so, I would attempt to find a fix myself, but since I don't, I hope somebody else understands why this is an issue and can attempt a more effective fix.

**Comment by westnordost** [comment]
I know. This is somewhat of a technical limitation though, i.e. would take an disproportionate amount of effort to "completely" fix.

**Comment by mnalis** [comment]
> Ah... this is because querying by bbox on the map (which the tap does) now works the same way as querying from OSM API. So, if the tap is not close to a node of the way, it won't return anything... :-|

I wonder would adding option to _"select road name from a list"_ (in _addition_ to current _"click on the road on the map"_) work to help the usability here, i.e. as suggested in https://github.com/streetcomplete/StreetComplete/issues/5582#issuecomment-2062626663 ?

**Comment by westnordost** [comment]
No, because that would have the same limitation. Only ways that have a node within the bounding box around the housenumber would be available for selection in that list.

**Comment by joe27g** [comment]
Would it be feasible to calculate two bounding boxes for this type of quest, with the new one being a very large radius i.e. 250m, and only use the larger one for a dropdown list? As long as this wouldn't cause performance issues, it seems like it could be a fairly easy fix. Of course, I'm not sure how much work this would actually be since I haven't reviewed much of the code, but just putting the idea out there.

**Comment by westnordost** [comment]
The larger the radius, the slower. Also, what is shown in dropdown suggestions is done the same way as for the picking from the map.

**Comment by joe27g** [comment]
I suppose that makes sense. Thanks for explaining the rationale regarding this issue!

By the way, I feel like I should clarify that I don't think this really affects the usability of the app overall. Though I've encountered it quite a few times, it was only in a handful of areas with specific conditions. Not every edge case is worth fixing; just wanted to check if this one might be.

Appreciate all the work you've done to make this app awesome! 👍
