### ISSUE TITLE
[v41.0-beta1] Add "repeat answer" functionality to measurement quests

### ISSUE THREAD

**Issue by wielandb** [streetcomplete/StreetComplete#3809]
**Use case**
I noticed that when the road is split for some reason but does not change it's width, it is laborious to measure it multiple times.
One could look into the undo-feature what they just entered (because, in contrast to other quests you dont enter the numbers yourself and are less likely to remember what you entered last time) and enter it again, but I think the cognitive load could be reduced by implementing it in UI.

**Proposed Solution**
A little box with the last answer could be added like in AddBuildingLevels or the Street-related quests that when tapped fills the mask with the previous answer.

**Comment by westnordost** [comment]
I don't think this would be good. Mostly because it is unrealistic to assume that the human eye can distinguish whether the road really stayed the same width to a precision of ~10cm. If it is the same (straight) street, it might be, but then just having a short look into the undo history should not be much of a hassle if one forgot what he answered.

Other minor reasons are:
- another button adds more clutter to the UI
- in other measurement related quests, there is also no button (e.g. max height), even though the max height sign is often the same for parking entrances

**Comment by timothywashere** [comment]
It is a bit odd. Some areas you have to measure the road 20 times because of many splits for reasons unrelated to the width of the road. Then you have a 1km road and you only measure it once.

But I do love the measurement tool. Seems to be working well.
