### ISSUE TITLE
highway=footway : give option for AR measurement

### ISSUE THREAD

**Issue by JLZIMMERMANN** [streetcomplete/StreetComplete#3825]
Since StreetComplete v41 we are able to measure the road using AR.

It would be usefull for disabled people using wheelchair to use OpenStreetMap for routing thanks to good datas. For this purpose, we need the width of sidewalks. The option of measurement in AR would be welcome the same way.

**Comment by arrival-spring** [comment]
n.b. comment in https://github.com/streetcomplete/StreetComplete/pull/3735#pullrequestreview-891355704

> Let's add this quest but let's not add any further detailing quests for street-sides for now.

**Comment by andrewharvey** [comment]
I'm not sure I understand the reasoning for not asking on `highway=footway`. This is useful to know for accessibility, people with wheelchairs, prams.

We should also ask for shared cycle/foot paths, particularly when `segregated=no` where the wider the path generally the faster and less blockages the cyclist will face.

The logic at https://github.com/streetcomplete/StreetComplete/pull/3709/files#diff-59dd56c83671be36b258fa47770c2ec40a06b6de655ba7642b2ad1a1ce33ebdeR16-R32 seems to exclude `highway=cycleway/footway/path + foot=designated + bicycle=designated + segregated=no`.

**Comment by arrival-spring** [comment]
I think I interpreted the question as being about sidewalks mapped as part of the road, looking back, that wasn't explicit.

So yes, the width of paths mapped as their own ways could be useful information

**Comment by mnalis** [comment]
Yes, it would be nice if issues closed as `wontfix` would have a short comment by person closing it why they closed it; otherwise it might be unclear (or even based on mistake) like it seems here?

**Comment by matkoniecz** [comment]
In this case explanation is in comment preceding my closure. See https://github.com/streetcomplete/StreetComplete/issues/3825#issuecomment-1057464299

**Comment by mnalis** [comment]
@matkoniecz but that comment seems to be based on misunderstanding that this issue was about tagging extra-detail (e.g. `sidewalk:left:width=*` tags) on `highway=residential|primary|etc` (which was deemed as not wanted in that linked PR), and **not** about tagging `width=*` on separate `highway=footway` which this issue is about instead.

So, I also think this issue should be reopened (with subject changed to say `highway=footway` instead of `sidewalk` to eliminate confusion between different English dialects vs. OSM tagging). Do you agree?

**Comment by westnordost** [comment]
SCEE has this.

For StreetComplete, I am really don't think this is a good idea, for a couple reasons:

In cities, there are double as many sidewalks as there are roads (left + right side). For quests that spawn that much, there should be a good effort to value ratio and they should not be spammy. Measuring with AR is effortful and/or spammy

Sidewalk widths can vary in width a lot, e.g. when they snake around obstacles or even when the abutting buildings/properties do not align (one is further back than the other, some buildings may have protruding parts). If one wanted to be precise here, that's really going to be a pain in the ass.

Then, for many situations, it is not clear if something should still be counted as part of the sidewalk or not. E.g. bicycle parkings, bollards, patches of greenery or even just planters placed on the sidewalk. What about outdoor seating located on the sidewalk? Oftentimes it is not clear whether that area is otherwise private property or officially still considered part of the sidewalk. Oh, and don't let me get started about parking lay-bys that "cut" into the sidewalk - split the sidewalk at the length of the parking so that it is broader at curb extensions and in-between the lay-bys? Uff!

No, this has really far too much potential in getting lost in that. This is not for StreetComplete.

**Comment by JLZIMMERMANN** [comment]
There are 2 kinds of widths the widest one and the thinest. Such information is usefull for wheelchair user.
