### ISSUE TITLE
entrances : type of door

### ISSUE THREAD

**Issue by JLZIMMERMANN** [streetcomplete/StreetComplete#3826]
If we wish to help people using wheelchair, we need more informations about the type of **entrances**.
A good way is proposed with Mapcomplete [here](https://mapcomplete.osm.be/entrances.html?z=20&lat=44.13514&lon=4.810439&language=en#node/2999423032).
![image](https://user-images.githubusercontent.com/4929752/156445556-e4b84f92-f8eb-42a4-8ac2-9a7e82933eda.png)

A good starting point is to display the pictures like the one that are in [this page](https://wiki.openstreetmap.org/wiki/Key:door).
![image](https://user-images.githubusercontent.com/4929752/156445948-ce6e78ad-f452-4beb-856d-1425b62ab082.png)

**Comment by arrival-spring** [comment]
It's helpful for others if you use the new quest template when suggesting a quest idea.

What elements should this be asked for? How would you suggest filtering out private/residential doors?

**Comment by westnordost** [comment]
When the door is closed, you can often not tell apart certain doors from one another, so it is often not well answerable.

Also, it would be asked on every single house entrance, apartment staircase entrance etc. That's a little bit too much while the value of such information is very low because all those entrances are private, belonging to a house. 

For the POIs for which this information may actually be useful - shop POIs - have no `entrance=yes` and thus it would not even be asked for them.

Finally, I very much doubt the usefulness to record this information at all even in the use case of wheelchair users because there are other factors that make a door usable by wheelchair users such as steps in front of the door or the width of the door. Whether or not a shop or not in total is wheelchair accessible or not is already asked by the app, there is no need to dive deep down into such tags.

So, overall, this should not become a quest.
