### ISSUE TITLE
profiles : create a button in the main screen

### ISSUE THREAD

**Issue by JLZIMMERMANN** [streetcomplete/StreetComplete#3827]
There are too many quest, and this is great ;-)
It would be good to **bundle logical quests** : nature, road, shop, disabilities...

Each type of logical type of quest would be gathered on a profile. **A specific button** would be displayed on the main screen.
![1646254144075b](https://user-images.githubusercontent.com/4929752/156449675-5ec03298-2559-458d-b13c-79b0bd3c872e.jpg)
![1646254144082](https://user-images.githubusercontent.com/4929752/156449701-c18e2a32-c8e2-4f56-8225-c19f1100f3b0.jpg)

**Comment by mnalis** [comment]
related: https://github.com/streetcomplete/StreetComplete/discussions/3209

**Comment by mnalis** [comment]
And I absolutely agree that `preset quick-change` would be very useful, and has already be mentioned several times in various tickets. Currently one needs to click 9 times to switch preset, which is too cubersome https://github.com/streetcomplete/StreetComplete/issues/3034#issuecomment-879995215

**Comment by riQQ** [comment]
Only show it if there are 2 or more profiles defined to don't clutter the screen for users that don't use profiles.

**Comment by westnordost** [comment]
There will not be such a button on the main screen. Creating quest presets is already possible, as you show with the screenshot yourself. A faster switch between presets is not planned because it is not meant to be something you switch back and forth all the time. The presets are meant to be used  for each use case, e.g. "you are on a bus", "you  are casually taking a walk", "it is night time" or "you want to map everything" etc. So, if it takes a few seconds to switch the presets, that's fine in these cases. You don't get on and off of buses every few minutes.

You use the presets differently, to group quests by interest. Not sure why you would want to do that. To be able to dedicate one mapping trip to just mapping accessibility stuff? Another mapping trip to just mapping bicycle infrastructure?
Then, you also do not need to quickly switch between the presets because one mapping trip will surely take more than a few minutes.

**Comment by mnalis** [comment]
@JLZIMMERMANN If you really want such quick-preset-switch button though, you may wish to try fork at https://github.com/Helium314/StreetComplete, which has it implemented on the main screen.
