### ISSUE TITLE
OpenStreetMap multi accounts

### ISSUE THREAD

**Issue by JLZIMMERMANN** [streetcomplete/StreetComplete#3828]
Streetcomplete is connected with OSM account.
I use several accounts everydays. It would be good to be able to switch from one account to the other.

The same as using any webapp, a simple displaying of differents accounts would allow to change the username.

**Comment by matkoniecz** [comment]
Why it would be needed/useful?

Why not map in SC with one account?

(asking as person with several accounts that still has no need for changing which one is used for SC)

**Comment by matkoniecz** [comment]
Closing, can be reopened if something used by many people would appear (but I am dubious: multiaccounts are rare and implementing this would take a lot of effort)

**Comment by oliver** [comment]
For the record: I use multiple OSM accounts, for different areas (one for "near my home", one for "near workplace", one for "near my relative's place", and so on). This is for privacy reasons, because I don't want to publish on OSM where I work or where my relatives live.

For vacations I create separate accounts as well, but that's not really a problem because I then use the same account the entire time. But a multi-account feature would make it much easier to do SC quests e.g. on my way to work, because I could quickly switch to the correct account.

**Comment by mnalis** [comment]
Few workarounds / solutions for the issue: 

- most Androids offer a multiple-user setup, which allows for multiple versions of app with different data/settings for each user. (`Settings` / `Users`)
- some Android vendors offer options for multiple app settings even for the same user (e.g. "Second space", "App Twin", "PrivateSpace",...)
- it is possible to install separate forks of SC with different ids. I usually have at least 3 different versions of the SC (upstream, [my own](https://github.com/mnalis/StreetComplete/) devel fork, [SCEE](https://github.com/Helium314/SCEE)) - each with its own separate settings.

**Comment by flo-schn** [comment]
I use multi accounts for different areas. home, work and travel. to be less easily identified online. thus an implementation would greatly be appreciated!

**Comment by HolgerJeromin** [comment]
@flo-schn 
Wild idea:
You could use StreetComplete, a StreetComplete debug build and SCEE for three instances.
