### ISSUE TITLE
cycleway width does not resolve, icon stays

### ISSUE THREAD

**Issue by call-me-matt** [streetcomplete/StreetComplete#3843]
When adding a width to this cycleway, the task does not dissappear:
https://www.openstreetmap.org/way/181766506

Note the history or try it out on your own.

**How to Reproduce**

Seems to happen only for this cycleway, could not determine why.

**Versions affected**

41.0

**Comment by matkoniecz** [comment]
Thanks for a report! You found a serious bug!

-------------------------------

Looking at https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/width/AddCyclewayWidth.kt - `width` is being added but `cycleway:width` is checked in the filter

https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/width/AddCyclewayWidth.kt#L48 mismatches filter

I think that `applyAnswerTo` should rather check `segregated` yes/no instead

**Comment by westnordost** [comment]
>I think that applyAnswerTo should rather check segregated yes/no instead

Hm no, it shouldn't because in this case, adding `cycleway:width` would not be correct.

In fact, that `segregated=yes` is tagged at all on that cycleway is (kind of) wrong. `segregated=yes` is used if there is a footway+cycleway mapped as one way but the two are actually segregated from one another. 

But in the example linked, the cycleway is mapped separately from the footway, not as one way. So, `segregated=yes` is superfluous and/or wrong.
