### ISSUE TITLE
Add 'metal_grid' as surface option

### ISSUE THREAD

**Issue by legofahrrad** [streetcomplete/StreetComplete#3848]
**Use case**
Many steps have metal grids as surface. It would be very helpful to tag those steps correctly, leaving a note would be unnecessary then.
Also, many users choose 'metal' which is not really correct.
Example: https://www.openstreetmap.org/way/1033611793

**Proposed Solution**
Add a new option to the surface quests. → Maybe only for paths / steps? I have never seen a road with metal grid surface.

See also https://wiki.openstreetmap.org/wiki/Key:surface
https://taginfo.openstreetmap.org/tags/surface=metal_grid (1400 uses only but I think it's worth it)

**Comment by demsjf8** [comment]
There's also benches that have a metal grid surface/are made of metal grid, rather than solid metal. Obviously besides benches really made of solid metal/having a closed metal surface.

**Comment by Helium314** [comment]
> Also, many users choose 'metal' which is not really correct.

A metal grid is definitely metal, or is it not?
Similar to concrete lanes being concrete: you can be more specific, but the generic material isn't wrong.

**Comment by legofahrrad** [comment]
> A metal grid is definitely metal, or is it not?

Yeah, sure it is. But being more specific is definitely better, isn't it?

Something like this:
![metal](https://upload.wikimedia.org/wikipedia/commons/3/3c/Metal_steel_surface.jpg)
is something different than this:
![metal grid](https://upload.wikimedia.org/wikipedia/commons/1/1c/Press_grating.jpg)
(Images from Wikimedia Commons: https://commons.wikimedia.org/wiki/File:Metal_steel_surface.jpg and https://commons.wikimedia.org/wiki/File:Press_grating.jpg)

I'm not an Android developer but I think it's not complicated to add one answer option to a quest…
Maybe somebody shares my idea and is able to implement this :)

**Comment by Helium314** [comment]
> Yeah, sure it is. But being more specific is definitely better, isn't it?

I don't disagree here, I only disagree with your statement that metal for a metal grid is not correct.

Adding the answer would indeed be very simple, but I guess it will not be added for the same reason as rubber was not added, which has similar usage (#1859).

**Comment by westnordost** [comment]
I think 1400 usages worldwide is not a lot. Also, unlike equally rare values such as woodchips, they don't occur all over the place in one place. E.g. you can have a public garden with woodchip surface all around, but you can usually not have that with metal grid surfaces because those are usually found on bridges or as footpaths over swampy areas in a (public) park.
So, a note will suffice if one really wants to be very precise.

(By the way, I have seen some of those "metal grids" that were actually made of some kind of composite fibre. So, `metal_grid` as a tag value may actually not be the best choice, as whether they are metal or not is not that important for their functionality but the fact that it is a grating is)

**Comment by andrewharvey** [comment]
> (By the way, I have seen some of those "metal grids" that were actually made of some kind of composite fibre. So, metal_grid as a tag value may actually not be the best choice, as whether they are metal or not is not that important for their functionality but the fact that it is a grating is)

https://wiki.openstreetmap.org/wiki/Talk:Key:surface#fibre-reinforced_polymer_composite_grate_surfaces
