### ISSUE TITLE
Enable avocado for Cyprus

### ISSUE THREAD

**Issue by Oi-sin** [streetcomplete/StreetComplete#3851]
**Use case**
The quest for setting the type of fruit for an orchard does not offer avocados and mandarins. 

**Proposed Solution**
Add choices for avocados and mandarins: 
trees=avocado_trees and
trees=mandarin_trees

**Comment by matkoniecz** [comment]
` trees=mandarin_trees` has 48 uses worldwide https://taginfo.openstreetmap.org/tags/trees=mandarin_trees

`trees=avocado_trees` has 1664 uses worldwide https://taginfo.openstreetmap.org/tags/trees=avocado_trees

For now, just leave notes with photos. If that turns out to be really popular it may make sense to add such options.

But note that

- there was significant research to capture really popular crops
- adding entries adds significant work for translators (2 new entries multiplied by language count)
- this quest is very rarely solved

**Comment by Oi-sin** [comment]
Thanks for the very fast feedback.  
I just looked into the code and at least the option for avocados seems to be present already. In orchardProduces.yml there is a list of fruit types per country. Thus this could be easily activated. 
The source of this feature requests are orchards in Cyprus.

**Comment by matkoniecz** [comment]
@rugk Is it possible to activate avocado for Cyprus in way that will be not lost on the regeneration of this metadata?

https://github.com/streetcomplete/StreetComplete/blob/1c5b7b4b964680646d8fd5483cd598a4a17415ac/res/country_metadata/orchardProduces.yml

Is https://github.com/rugk/crops-parser supporting such manual overrides?

**Comment by rugk** [comment]
Hmm, first of all about the actual request: ~~[The quest](https://wiki.openstreetmap.org/wiki/StreetComplete/Quests#orchard_produce) tags `[produce](https://wiki.openstreetmap.org/wiki/Key:produce)`, _not_ `trees`…~~ aaah now I get, that is just the source for that tag okay.

> Is https://github.com/rugk/crops-parser supporting such manual overrides?

No., not really (you can redefine and map the source data) using [the crops <-> OSM-key mapping](https://github.com/rugk/crops-parser/blob/master/osmcrops.csv) or of course fake the source data to include stuff… :upside_down_face: 

For the manual additions I also needed to redo them for the last update: https://github.com/streetcomplete/StreetComplete/pull/3763
That said, that data is really not regenerated that often (Or does not need to, actually), so one could do that manually every few years.

Or one just has to implement it adds – should not be _too_ hard – if that is the way to go, I'd say one should open an issue in the repo there.

---

So okay, this is the current entry:

https://github.com/streetcomplete/StreetComplete/blob/1c5b7b4b964680646d8fd5483cd598a4a17415ac/res/country_metadata/orchardProduces.yml#L47

Note that this is generated based on official data from FAO, who gets their data from the country statistics offices if possible, so only when the country cannot provide any good data this can be inaccurate.

## Looking into the source data

So I looked into the source data for Cyprus:
[tonnes_harvested_2019+2020_cyprus.csv](https://github.com/streetcomplete/StreetComplete/files/8200958/tonnes_harvested_2019%2B2020_cyprus.csv)
[tonnes_harvested_2019+2020_cyprus.ods](https://github.com/streetcomplete/StreetComplete/files/8200959/tonnes_harvested_2019%2B2020_cyprus.ods)

And all data is official data, except for "Beer of barley" (the other one produced 0 tonnes so we can ignore it…).

Edit: oh gosh I looked at the tonnes (we actually use "area" for SC) and I sorted by item code instead of volume ("value") actually, I should go to sleep… :astonished: 

Here is the same data per area:
[area_harvested_2019+2020_cyprus.ods](https://github.com/streetcomplete/StreetComplete/files/8201054/area_harvested_2019%2B2020_cyprus.ods)
[area_harvested_2019+2020_cyprus.csv](https://github.com/streetcomplete/StreetComplete/files/8201055/area_harvested_2019%2B2020_cyprus.csv)


### Avocados

(this used tones instead of area, but should still be somewhat correct)

So first important thing I noticed is that `Avocados` are in there and should appear in the end result actually:
![grafik](https://user-images.githubusercontent.com/11966684/157120426-ce059c22-e79c-4389-8f4f-6f7b903ca2dc.png)

Their usage even increased in 2020, so maybe there is a bug in the script here?
The mapping [if you search in the Crops "DB" for "Avocado"](https://github.com/rugk/crops-parser/blob/master/osmcrops.csv) seems to be correct though.
So I have no idea what went wrong here.

#### Avocados produced in area

![grafik](https://user-images.githubusercontent.com/11966684/157122007-15e925d0-e2b7-4149-990e-e54207e9e708.png)

they are in here too, no idea what happens here…

(They just did not increase, so they produced more on the same land in 2020…)

And it can be seen however, that's not really a lot 100ha in a whole country… nevertheless, it should of course be included.

### Mandarins

As for mandarines they are unfortunately only provided as aggregated data in `Tangerines, mandarins, clementines, satsumas`.
If we wanted to include this, we should obviously do so for _all_ countries.

However, the question would be what images and what . Can "normal" people differentiate these fruits? Is there even a separate OSM tagging? (Or should there be?) Or is such a "common group" tagging even allowed here – if even the FAO does not do? (Or should ne you differentiate between these)

I guess to discuss that, I would suggest to open a new issue at https://github.com/rugk/crops-parser/issues specifically for mandarins.

obviously in there in the "area harvest" data too (BTW quite a lot > 100 ha):
![grafik](https://user-images.githubusercontent.com/11966684/157122288-84f5095b-27dc-4858-b55a-4fc35f7e3f87.png)

**Comment by rugk** [comment]
Ah btw, the avocado appears in the dataset generated with tonnes, actually BTW – that is _even more_ strange:
https://github.com/rugk/crops-parser/blob/4294f0721842665b6dc0a6aee9482438a10f253a/result/OsmOnly/mostTonnesHarvest_2019%2B2020.yml#L47

**Comment by rugk** [comment]
Ahhh I now the likely cause for the avocado issue.- My data generation [as per it's Readme](https://github.com/rugk/crops-parser#what-does-it) does this:
> It extracts all crops for each country and transforms the first fifteen crops listet into the YAML format.

So it is limited to 15 entries!

In the resulting data for area/CY, I count 16 entries already (uff off-by-one errors are the worst, did not found an xkcd meme hehe), likely avocado is following right after…

Though oh [no, this country has 19 entries](https://github.com/streetcomplete/StreetComplete/blob/1c5b7b4b964680646d8fd5483cd598a4a17415ac/res/country_metadata/orchardProduces.yml#L44) whaaat… maybe the doc is outdated here I have no idea (and also could not find an issue right now)…

**Comment by westnordost** [comment]
okay, @rugk, the solution would be to not limit the entries to any number because the data is not only used to sort the answer options (like for the religion quest or the sports quest) but those options that are not in the list are **not available for selection**.

The reason for that was that e.g. tropical fruits like bananas are not cultivated **at all** in e.g. Sweden, so they should not be shown at all. but any fruit that is in some extent cultivated should be selectable.

**Comment by rugk** [comment]
yeah I know that, but apparently that also is not done currently… this needs more investigation, certainly.

**Comment by Oi-sin** [comment]
Hello guys! Thanks for the extended research. I am really sorry for causing sleepless nights with such a simple(?) request. 

For those few avocados I could do with writing notes. This works fine. If this issue does not have any implications in countries with a larger area of missing crop types, I would accept the current state :-).

As for the mandarins it will be too difficult for a non botanical or agricultural person to distinguish the types. Reading through https://wiki.openstreetmap.org/wiki/Key:trees and the discussion page there it seems to be a bottomless pit one should not enter.

**Comment by rugk** [comment]
> bottomless pit one should not enter

Well… we are already in there… :upside_down_face: (But I also could not find a specific discussion about mandarins but yeah, I guess we have all decided it's not really a good idea to provide an easy image-mapping feature for that – you'*d need a [field guide](https://en.wikipedia.org/wiki/Field_guide) for that – or some of these cool (AI powered?) apps that can detect that by itself, though that likely won't improve data quality and you may often not get close enough to take a proper photo… :upside_down_face: )

Anyway, I'll tackle the found issues…

**Comment by FloEdelmann** [comment]
I've manually edited [orchardProduces.yml](https://github.com/streetcomplete/StreetComplete/blob/master/res/country_metadata/orchardProduces.yml) now in https://github.com/streetcomplete/StreetComplete/commit/d84a077db8129c0db8a2c5cf449111fb2783ecf7, since @rugk already created upstream issues in https://github.com/rugk/crops-parser:

* https://github.com/rugk/crops-parser/issues/61
* https://github.com/rugk/crops-parser/issues/62
