### ISSUE TITLE
Streets in AddStreetParking are stretched

### ISSUE THREAD

**Issue by arrival-spring** [streetcomplete/StreetComplete#3854]
Testing the AddStreetParking quest and I guess the options shouldn't look like this:
![street_parking](https://user-images.githubusercontent.com/77166354/157119342-a7f548bd-bf2f-4534-a520-0a7e71d1eaed.png)

My screen is 720x1520

I guess it's something around here:

https://github.com/streetcomplete/StreetComplete/blob/0d342e80966bfb9c3a1093a117170bd7e6af2e6a/app/src/main/java/de/westnordost/streetcomplete/quests/street_parking/StreetParkingDrawable.kt#L62-L68

Or is it that the images for the streets are not square, but ratio 2:1 and are then being stretched to square?

**Comment by westnordost** [comment]
Uh, what's going on... I tested that before and it worked just right.

The error you see is that the bacground image (the street) should not be stretched but cropped.

**Comment by westnordost** [comment]
I cannot reproduce this (Android 12, Samsung s10e), so it seems to be that the behavior of the canvas is different for different Android versions or devices. Since you can reproduce this and you already identified the place in the code where this happens, maybe you could test what would fix this issue for you?
