### ISSUE TITLE
Don't show smoking quest without outdoor seating in some countries

### ISSUE THREAD

**Issue by Helium314** [streetcomplete/StreetComplete#3856]
In many countries smoking is forbidden inside restaurants/pubs/..., so asking in those countries is pointless if there is no outdoor seating, as the answer will always be no.
Well, except if the 'outside' answer means "you can just leave the pub and smoke on the street"... but the street does not belong to the pub, so smoking on the street shouldn't be tagged on the pub (not sure if this is the current interpretation by the smoking quest, because `outside` answer is still shown if `outside_seating=no`). 

The quest could even depend on answering the new seating quest first, i.e. require both `indoor_seating` and `outdoor_seating` (or `leisure=outdoor_seating` of course). So first the user answers the seating quest, and the smoking quest is only shown if there is outdoor seating (again: in countries with indoor smoking ban).

**Comment by matkoniecz** [comment]
In which countries this quest will be asked (after enabling it) and should not be asked? Can you give some examples?

**Comment by Helium314** [comment]
> In which countries this quest will be asked (after enabling it) and should not be asked? Can you give some examples?

Currently the quest will be asked in all countries, and I don't know any countries where it should be completely disabled.
But e.g. in Ireland smoking is not allowed in restaurants, so if a restaurant in Ireland has no outdoor seating, I would expect that smoking is not allowed, and there is no need to explicitly tag it.

**Comment by Helium314** [comment]
Some quick and very incomplete check of the [Wikipedia list](https://en.wikipedia.org/wiki/List_of_smoking_bans):
No indoor smoking in Austria, Czech Republic, France, Hungary, Netherlands (also Greece, but not enforced).
In Sweden smoking isn't even allowed in outdoor seating areas.

**Comment by andrewharvey** [comment]
I think most Australian states have or soon will ban smoking in outdoor dining areas, so no point asking it at all. New Zealand is really leading the way by phasing in a blanket ban on all smoking.

**Comment by westnordost** [comment]
I was under the impression that this has already been discussed in the #539 ticket and the outcome was (that it's complicated and) the quest should (for that reason) be disabled by default? Same as e.g. Kosher quest which also doesn't make sense in some territories.

**Comment by mnalis** [comment]
@Helium314 the `smoking quest` should already be taking into consideration if new `seating quest` is solved (i.e. if both `outdoor_seating=*` and `indoor_seating=*` are set) and tuning its answer lists depending on that - see https://github.com/streetcomplete/StreetComplete/blob/master/app%2Fsrc%2Fmain%2Fjava%2Fde%2Fwestnordost%2Fstreetcomplete%2Fquests%2Fsmoking%2FSmokingAllowedAnswerForm.kt#L15-L21

As for the customizing quest per-country, I had considered it but find it way too complex and unfeasible for number of reasons, and resorted to **_disabled by default_** (i.e. depending on user to make a decision what is useful in their country) as **_only viable option_**.

<details>

Just to get general idea of problems involved:

- there are several customizations which could be done:
   - in what countries is quest shown at all (e.g. if smoking is forbidden country-wide, quest should be disabled)
   - element selection might vary by country (e.g. in come countries it is allowed in cafes, but not in restaurants)
   - allowed answers might differ by country (e.g. as you note in some countries smoking is always forbidden inside)
- also, there is much more complexity about making decision what to show and where:
   - wikipedia list is complex if you look into it in more detail. It is far cry from simple table `smoking allowed = inside/outside/never/everywhere` - even parsing it is correctly requires reading of linked documents (in different languages) to get even approximate picture
   - regulation is not actually per-country, but quite often per-(sub)region (which SC I don't think supports?)
   - list of exceptions is huge (e.g. smoking might be forbidden in any enclosed spaces, except restaurants - but not in all restaurants but only if they fulfill some criteria etc.)
   - the situation on the ground does not always follow regulations (esp. during transition periods),
   - much of the above is not documented on wikipedia (or similar globally available resource), AFAICT
</details>

So it is my opinion that trying to country-tune smoking quest would be bad idea, because:
- it would require huge amount of work (really, if one would like to dedicate good part of their life to sorting that question out and keeping it up-to-date, I'd recommend making a world-wide huge boolean table on wikipedia that summarizes all current regulations first, so others could benefit too)
- even if someone were to do all that work, the result would quite likely often be wrong (and thus probably do more damage than good).

**Comment by Helium314** [comment]
> @Helium314 the `smoking quest` should already be taking into consideration if new `seating quest` is solved (i.e. if both `outdoor_seating=*` and `indoor_seating=*` are set) and tuning its answer lists depending on that - see https://github.com/streetcomplete/StreetComplete/blob/master/app%2Fsrc%2Fmain%2Fjava%2Fde%2Fwestnordost%2Fstreetcomplete%2Fquests%2Fsmoking%2FSmokingAllowedAnswerForm.kt#L15-L21

Then showing the `outside` answer if there is no outdoor seating is intentional? Why?

> So it is my opinion that trying to country-tune smoking quest would be bad idea, because:

My opinion is that in Sweden and New Zealand the quest does not fulfill the "[users] shouldn't be asked to complete data that does not require a survey" guideline at all, same goes for "no spam".

What I specifically asked for is for countries with _no exceptions_ on indoor smoking ban, and here my point is that asking for places with `outdoor_seating=no` in those countries is similarly spammy, plus does not require a survey. (Perceived spam is why I opened this issue)

> * it would require huge amount of work (really, if one would like to dedicate good part of their life to sorting that question out and keeping it up-to-date, I'd recommend making a world-wide huge boolean table on wikipedia that summarizes all current regulations first, so others could benefit too)

Please note that I'm not asking for what you imply I'm asking for (put entire world legislation or wikipedia list into this quest), but only the simple parts (no indoor smoking without exceptions) or the very simple parts (no smoking indoor and outdoor). This is why I did not include countries like Italy or Germany.
Lists where to not ask will get outdated, but the list will likely not get shorter. And such a list is rather simple to change.

**Comment by mnalis** [comment]
> Then showing the `outside` answer if there is no outdoor seating is intentional? Why?

Ah, I get it now, thanks! :heart: There indeed could be situations where `outdoor_seating` has value, but `indoor_seating` does not. (SC `seating quest` would never do that, but some other editor might have). I'll look into it tommorow when my head is clearer. [Historically](https://github.com/streetcomplete/StreetComplete/pull/3784#discussion_r815457909)  that variable was `isAlwaysOutdoorOnly` and did something slightly different, so that history instead of intention is likely the reason for how it works.

> What I specifically asked for is for countries with no exceptions on indoor smoking ban, and here my point is that asking for places with outdoor_seating=no in those countries is similarly spammy, plus does not require a survey. (Perceived spam is why I opened this issue)

And that is **_exactly_** why the quest is **disabled by default**, is it not? Or am I misunderstanding? I'd completely agree with your reasoning if the quest was _enabled by default_. But what you seem to propose is to make quest "**more disabled than just disabled**", and I do not see in what situation would that help? What would be the use case? Malicious user which  intentionally goes to settings, enables the quest, ignores the warning and confirms they want to do it, and then starts to solve the quest they know is useless in their situation? :confused: 

In my opinion just disabling the quest by default (and leaving it to user to enable it if they want to after reading the warning) is enough (like it is enough for above-mentioned `Kosher` quest). Additionally insisting on not allowing user to enable the quest even when they think they know better, would only show distrust in user (_who is likely more knowledgeable about their country than us or Wikipedia is_), while potentially introducing errors at the same time. 

> My opinion is that in Sweden and New Zealand the quest does not fulfill the "[users] shouldn't be asked to complete data that does not require a survey" guideline at all, same goes for "no spam".

Speaking of potential errors, in what regard do you think Sweden should be disabled from solving this quest? From my reading of https://en.wikipedia.org/wiki/List_of_smoking_bans#Sweden it seems to me that smoking is sometimes allowed inside, and also sometimes allowed outside. Do you read that differently?

**Comment by Helium314** [comment]
> And that is **_exactly_** why the quest is **disabled by default**, is it not? Or am I misunderstanding? I'd completely agree with your reasoning if the quest was _enabled by default_. But what you seem to propose is to make quest "**more disabled than just disabled**", and I do not see in what situation would that help? What would be the use case? Malicious user which intentionally goes to settings, enables the quest, ignores the warning and confirms they want to do it, and then starts to solve the quest they know is useless in their situation? confused

My idea is to simply not show the quest in situations where it is most likely useless.
This is similar to not showing the sidewalk quest for unlit non-urban roads. Some of these roads may have a sidewalk, but it's not asked because by far most don't.
Or like not showing the roof shape quest for 0 or no roof levels in some countries where roofs are usually flat. Even someone who read the disabled message might not want to spam flat roof shape everywhere.

> In my opinion just **disabling the quest by default** (and leaving it to user to enable it if they want to after reading the warning) **is enough** (like it is enough for above-mentioned `Kosher` quest). Additionally insisting on not allowing user to enable the quest even when they think they know better, would only show distrust in user (_who is likely more knowledgeable about their country than us or Wikipedia are_), while potentially introducing errors at the same time.

Personally I find the smoking quest useful, but answering for lots of places where the `no` could be inferred from seating tags (if they exist) makes me want to disable it (or change it in my fork, then at least I am happy).
What I would like to have is NOT to forbid users from enabling the quest (well, except in New Zealand maybe), but rather to have a more elaborate element selection, like it exists for many other quests.

> > My opinion is that in Sweden and New Zealand the quest does not fulfill the "[users] shouldn't be asked to complete data that does not require a survey" guideline at all, same goes for "no spam".
> 
> Speaking of potential errors, why exactly do you think users should be **forbidden** to enable this quest in Sweden? From my reading of https://en.wikipedia.org/wiki/List_of_smoking_bans#Sweden it seems to me that smoking is sometimes allowed inside, and also sometimes allowed outside. Do you read that differently?

Well, this is a good reason not to blindly look at specific parts of Wikipedia like did. I had combined "Smoking has been banned in all bars and restaurants since May 2005" from the smoking in Sweden article with "Starting from 1 July 2019, smoking outdoors will be prohibited for restaurants with outdoor seating" form the general smoking ban list, while apparently ignoring "Smoking rooms are, however, allowed in these institutions" (for the 2005 ban).
Though the weird contrast between prohibiting smoking outside while allowing in special rooms inside might have contributed to this.

**Comment by mnalis** [comment]
> Personally I find the smoking quest useful, but answering for lots of places where the no could be inferred from seating tags (if they exist) makes me want to disable it

Oh, I absolutely agree with you that we should disable some answers if **_tags_** on the object indicate some choice is unavailable (like offering `OUTDOOR` answer even when it is explicitly tagged `outdoor_seating=no` which you noted :heart: ). Sorry if that part of my answer wasn't clear; it was just an omission (on my part), that PR https://github.com/streetcomplete/StreetComplete/pull/3865 now attempts to fix -- feel free to comment / suggest changes there if you think something else should be checked too depending on the mapped **_tags_**.

What I am uncomfortable with, is disabling/modifying quest **on per-country** basis. It seems to me (while I did put some work into trying to make sense of it, it's still just _my_ opinion) that it requires **too much research and is too error prone for too little benefit**. 

As another example, reading up on New Zealand (where it was also proposed to permanently disable the smoking quest), from my reading of that [wikipedia page](https://en.wikipedia.org/wiki/List_of_smoking_bans#New_Zealand) it seems that some bars/cafes/etc. allow smoking outside, but some do not. So I personally would still **_allow_** Newzealanders **_who explicitly want to enable it_** to  solve that quest (for everybody else, it is disabled by default, so I foresee no problems for them).

To be clear, that is just my personal preference, and the amount of work I'd myself want to put into it. If someone else wants to do PR that further tunes smoking (or any other) quest according to reliable sources of information, more power to them. I just wouldn't want to permanently disable the quest for users who see the value in solving it in their country _much better_ then us outsiders.

**Comment by westnordost** [comment]
That's fine, thank you @mnalis!

It is possible in the future to disable the quest completely for certain countries where we know 100% that smoking is not allowed anywhere in public places. But this is certainly not a requirement and should be done in a PR by anyone who wants to do the necessary research. I'll look at #3865 later.
