### ISSUE TITLE
Don't ask for road width on roundabouts

### ISSUE THREAD

**Issue by dbdean** [streetcomplete/StreetComplete#3877]
**Use case**

Generally, pedestrians should not be crossing the road to the centre of a roundabout. So measuring the width of the roundabouts road can be difficult to do safely and/or legally.

**Proposed Solution**

Don't ask for road width on ways tagged with `junction`=`roundabout`

**Comment by kmpoppe** [comment]
Would it be worth making that an AR-only quest?

**Comment by dbdean** [comment]
My point is that it isn't generally safe or legal to answer this quest using AR.

**Comment by westnordost** [comment]
Why would crossing into the center of a roundabout be less safe than crossing any other road? I mean, any other road can be very busy and not have any pedestrian crossing - that alone should not be a reason to not even ask.

**Comment by mnalis** [comment]
Maybe because there is a **high chance** that crossing the road is allowed _somewhere along its length_ (there are usually pedestrian crossings _somewhere_ on there road. Also for example in Croatia, you can legally cross any street except `motorway` if there is no pedestrian crossings within `50m` of you - after you verify it is safe to do so; I'd guess other countries might have similar provisions).

On the other hand, roundabouts (in my experience) have **low chance** of having pedestrian crossings leading to the center of them, and their radius is often less than 50m. In addition, they usually have several ways for vehicle ingress/egress making them **less safe** to cross while looking at your phone (or carrying a meter in your hands), even if crossing them were to be legal in some cases. 

Also the use case of having width of roundabout mapped is likely lower (you might want to know width for each of the roads going in and out of roundabout to know if your wide vehicle can go there, but it is somewhat unlikely that you would be able to enter the roundabout with your wide vehicle, and able to exit the roundabout with your wide vehicle, but not being able to use that roundabout -- and even if that would be the case, you'd have to take the account the curvature of the roundabout and not only it's width etc.)

**Comment by mcliquid** [comment]
Shouldn't it remain a personal decision what possible dangers I expose myself to for a quest?
If I have a laser meter with me, I don't have to cross the road of the roundabout. Or there is absolutely not a single car far and wide, then I can walk merrily across the roundabout.
And if it is too dangerous, an individual should consider not answering the quest at this point at all.

**Comment by mnalis** [comment]
@mcliquid yes, probably so. But then again, one can also safely answer many quests on `access=private` which **do** get hidden currently, for example. It is a matter of striking a balance, I guess. As reasons for why it should remain have already been shared, I'd though to provide the view from other side too.

I personally would prefer a boolean flag in preferences where users could choose how much they want to be spammed with (i.e. should every quest in SC be more or less filtered; and I have a [list of great candidates](https://github.com/streetcomplete/StreetComplete/discussions/3626#discussioncomment-1956514), but that is another story), but adding such preferences is frowned upon here (and probably for good reasons :smiley:).

**Comment by westnordost** [comment]
With `access=private` though, it is really a matter of the guideline point "🤔 No unanswerable quests". If a private driveway is behind a gate, it is simply not answerable. This is different from this matter.

**Comment by MaestroGlanz** [comment]
I disagree. It's a difference, if you measure it on a Sunday afternoon or Monday 8 am. It's also a difference between Munich center and the bushlands of Australia. The app can not regard all possible dangers and issues. At least, it's not effective. 

In general every user is a grown-up and self-responsible. It is not the programmers task to protect them. Trying to do so would be encroaching. Totally unacceptable. There might be minors among the users, but we can not make a tool child safe like we can not make an electric drill child safe.

**Comment by westnordost** [comment]
You disagree with what?

**Comment by MaestroGlanz** [comment]
With the very original statement from the report, the headline.

I think roundabouts shouldn't be excluded.

**Comment by mnalis** [comment]
Since few people has expressed their feeling that it is useful to them to map those, I'll support them. :+1: 

Even for people who don't see the use, it is better to have them see a little more quest spam, than for other users to not be able to answer some quest where they do see the value.
