### ISSUE TITLE
Rename quest_busStop to more neutral ones? Or have separate texts for various kinds of stops?

### ISSUE THREAD

**Issue by matkoniecz** [streetcomplete/StreetComplete#3891]
Current string names

```
quest_busStopBench_title2
quest_busStopBin_title2
quest_busStopLit_title2
quest_busStopRef_title2
quest_busStopShelter_title2
quest_busStopTactilePaving_title
```

are quite confusing and likely to mislead translators.

**Comment by westnordost** [comment]
The translators translate the english text, not the id

**Comment by matkoniecz** [comment]
Yes, but iD is shown and provides valuable info/context.

Which in this case is misleading.

**Comment by westnordost** [comment]
It's not that misleading. The English phrasing just mentions "stop" and when looking at the id, it can actually help to clear up what kind of stop. I.e. not a stop sign or whatever, but a (bus) stop.

Besides, it is always somewhat of a hassle to **rename** ids because one cannot rename ids in POEditor. So one would have to manually copy over each translation to the new key (or let translators re-translate it).
