### ISSUE TITLE
Allow forced resurvey quest on long press

### ISSUE THREAD

**Issue by andrewharvey** [streetcomplete/StreetComplete#3918]
**Use case**
While surveying if you notice some recent changes or construction and would like to update that, normally most quests give options like "no longer there" for shops, or demolished for buildings, however that relies on there being an unsolved quest.

**Proposed Solution**
Long pressing on some feature should present in a list features near your press, which you can select. Then you can select all available quests for that feature even if they would normally already be solved or within the resurvey interval and ask to re-do the quest/mark as no longer there etc.

This makes it more accurate sometimes and more efficient than just leaving a note.

Apologies if this was asked before, I couldn't find it.

**Comment by westnordost** [comment]
1. How would you know that a particular feature exists at that place in the first place? StreetComplete does not show you shops etc.
2. creating quests for elements "for which the quest has already been solved", i.e. the tag the quest is about is already tagged, is not possible. Technically, only maybe those with old data.

Generally, I would say this is a will-not-fix (additionally) because it is quite out of scope. What you want (to use) is a general purpose editor and you just suggest here to do it via quests because this is how things are done with STreetComplete, not because it would make sense.

**Comment by andrewharvey** [comment]
> How would you know that a particular feature exists at that place in the first place? StreetComplete does not show you shops etc.

Some features are shown on the map like buildings, others like shops you wouldn't know, you'd long press and see if it's there or not. Or someone is already using other OSM maps.

> creating quests for elements "for which the quest has already been solved", i.e. the tag the quest is about is already tagged, is not possible. Technically, only maybe those with old data.

Sounds like it would be a bit of effort to build and maintain.

> Generally, I would say this is a will-not-fix (additionally) because it is quite out of scope. What you want (to use) is a general purpose editor and you just suggest here to do it via quests because this is how things are done with STreetComplete, not because it would make sense.

Fair enough, and yes I would normally just use another editor but StreetComplete quests make it dead easy to map, other editors I might need to search the OSM wiki to find the right tag and that's just too much effort on mobile.
