### ISSUE TITLE
Seasonal benches

### ISSUE THREAD

**Issue by hungerburg** [streetcomplete/StreetComplete#3943]
An SC user deleted several benches, likely after failing the backrest quest, here a picture of theirs, https://westnordost.de/p/83889.jpg (This one is still in the data, but others close by, just the same, got deleted.) Here one that got deleted https://westnordost.de/p/83886.jpg You have to look more closely.

Maybe the bench quest should specify "seasonal" as a way out? (At the start of winter, the local gardening department dismounts all the wooden parts, leaving only the concrete parts. In spring, they are then readded.)

PS: This is nice, to be able to find pictures by changing the number in the resource location.

**Comment by westnordost** [comment]
Do you have a link to the changeset?

**Comment by hungerburg** [comment]
No, I don't. In this note, the user claimed to have removed several benches https://www.openstreetmap.org/note/3089117

**Comment by westnordost** [comment]
Yes, I also found it right now through osmcha

https://osmcha.org/changesets/118508989?filters=%7B%22users%22%3A%5B%7B%22label%22%3A%22YieldMapper%22%2C%22value%22%3A%22YieldMapper%22%7D%5D%2C%22comment%22%3A%5B%7B%22label%22%3A%22exists%22%2C%22value%22%3A%22exists%22%7D%5D%2C%22date__gte%22%3A%5B%7B%22label%22%3A%22%22%2C%22value%22%3A%22%22%7D%5D%7D

**Comment by hungerburg** [comment]
Maybe they are not familiar with the practice of the local department, Seasonal should be an option in this quest. Hard to tell for someone non-local, true.

**Comment by westnordost** [comment]
So, one solution I see is to generally not ask StreetComplete users if a thing still exists that has `seasonal = yes` tagged. The obvious downside is that those objects will never be verified again if they exist, but an accidental deletion is avoided. To be consistent, probably any other question should also not be asked for `seasonal = yes` map features. Might be a lot, seasonal bicycle pumps, garbage bins, ... barriers? toilets? playgrounds? ...hmm.

But anyway, that could be done.

**Comment by westnordost** [comment]
However, this doesn't help in this situations similar to this specific example because the benches haven't been tagged with `seasonal = yes`. And as far as I can imagine, I don't see a solution for this, because it is (also) not really an issue of the app:

If a surveyor finds some dismantled benches were benches used to be, that's what he sees. He has no way to ascertain whether the dismantlement is just seasonal. As you wrote yourself in the post above. So, even if there was an option beside the yes/no named "temporarily removed / seasonal", he cannot answer this. And if he could, i.e. knew that it was seasonal, that person would likely either answer "yes, still there" or leave a note about it being seasonal rather than deleting it.

I guess knowing whether something is `seasonal = yes` or not depends on the mapper's familarity with the local department's practices. You have that knowledge, so my specific suggestion to you is to mass-tag all the benches with `seasonal = yes` you know are seasonal.

**Comment by mnalis** [comment]
I would prefer option "B" - show warning to user if they try to delete object marked with `seasonal=yes`. Actually, I feel even that is too mild; what I'd **actually** prefer is that the option _"It does not exist"_ is **_completely disabled_** on objects marked with `seasonal=yes`.

Because, in my experience, users are often too trigger happy with automatically confirming warning popups :cry:  and there is a _very high probability_ that removing seasonal object is a mistake. Having users leave a note instead is much better choice in that specific case, IMHO.

Perhaps that can be done automatically on global SC level (instead of per-quest level) - i.e. if a feature has `seasonal=yes` tag, do not allow removing the object (instead a popup might instruct to user to leave a note if/when they try to remove seasonal object).

Of course, as noticed it wouldn't have helped in this particular case, but it would allow other users to protect such areas from accidental removals due to seasonality.

**Comment by matkoniecz** [comment]
I would disable quests for things marked with `seasonal=yes/...` and `street_vendor=yes` for shops, like https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/existence/CheckExistence.kt#L66

> However, this doesn't help in this situations similar to this specific example because the benches haven't been tagged with seasonal = yes. And as far as I can imagine, I don't see a solution for this, because it is (also) not really an issue of the app:

In this case existing data was simply wrong. Mapping seasonal object without marking it as seasonal is not correct and noone should be surprised if that object would be deleted on someone encountering it and failing to locate it.

**Comment by kmpoppe** [comment]
> I would disable quests for things marked with `seasonal=yes/...` (and `street_vendor=yes` for shops once it gets more popular), like https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/existence/CheckExistence.kt#L66

Agreed.

> In this case existing data was simply wrong. Mapping seasonal object without marking it as seasonal is not correct and noone should be surprised if that object would be deleted on someone encountering it and failing to locate it.

I agree that StreetComplete is no Crystal Ball that's able to guess whether an amenity might be seasonal if the tag is missing. But, tbe, the data was not wrong as per on-the-ground-rule when someone entered a bench that they physically witnessed. That it's placement is seasonal is something _most likely_ not known to the general public.

Is that a kerfuffle for SC? Yes. Is it something somebody _must_ be blamed for? IMHO, I don't think so.

**Comment by cyclingcat** [comment]
> In this case existing data was simply wrong. Mapping seasonal object without marking it as seasonal is not correct and noone should be surprised if that object would be deleted on someone encountering it and failing to locate it.

But how should poor mapper determine if a bench (or other object) is seasonal if he detects one in the wild and wants to add it to the map (with JOSM, OsmAnd or Vespucci)?

However, this is a more general issue. I regularly encounter this situation with bollards on foot-/cycleways: A bollard type quest pops up, but there is no bollard, just a square hole on the path which looks like there once was a bollard. But what's the current situation here? Was it removed just temporarily for some reason and will come back soon (tomorrow? Next week? Next winter?) or was it removed permanently without filling up the hole with concrete?

There is already an "Are you sure that it does not exist" warning message when any (?) object is about to be deleted. Maybe we need a list of object types where the user gets an additional warning in red letters "Beware: The removement could be just temporary/seasonal/whatever!" if he wants to answer "Does not exist" (objects like hydrants are very unlikely to get removed temporarily)? I'm pretty sure many SC users as well as other mappers aren't aware of the fact that some kinds of objects could be seasonal and there is a tag for it - `seasonal=yes` isn't even mentioned on the [OSM wiki page for benches](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dbench).

The cycling cat

**Comment by matkoniecz** [comment]
> But how should poor mapper determine if a bench (or other object) is seasonal if he detects one in the wild and wants to add it to the map (with JOSM, OsmAnd or Vespucci)?

Preferably by repeated surveys. I did it with some objects. Yes, it requires repeated surveys across multiple months (1) to notice it existing (2) to notice it gone (3) to notice it reappearing.

Sometimes you have an official info from entity managing object that this are seasonal toilets/benches/whatever.

**Comment by westnordost** [comment]
So we have the following suggestions on the table for objects that are seasonal:

1. don't ask to check existence (and anything else)
2. display (another) warning message that informs about its status as seasonal before deletion
3. Let the "doesn't exist" answer lead to the creation of a note 

Orthogonal of that, there is the suggestion to append the text in the warning that is shown anyway always with a mention of that the object may have been removed temporarily.

It looks like most think option 1 is the best,  however what about option 3 brought up by mnalis?

**Comment by matkoniecz** [comment]
One more: for which objects we should consider `seasonal` as invalid?

For example: should we skip surface, lane, speed limit and other quests on `highway=residential` `seasonal=yes`? ( https://www.openstreetmap.org/way/872059877 or  - see https://overpass-turbo.eu/s/1hnDhttps://www.openstreetmap.org/way/878423039 https://www.openstreetmap.org/way/726129594 https://www.openstreetmap.org/way/963329075  https://overpass-turbo.eu/s/1hnF )

Should we skip building type quest on `building=yes` `seasonal=yes`?

**Comment by mnalis** [comment]
> > But how should poor mapper determine if a bench (or other object) is seasonal if he detects one in the wild and wants to add it to the map (with JOSM, OsmAnd or Vespucci)?
> 
> Preferably by repeated surveys. I did it with some objects. Yes, it requires repeated surveys across multiple months (1) to notice it existing (2) to notice it gone (3) to notice it reappearing.

That is pretty hard to do for more than just a few places by one mapper, though (i.e. if you map anything more then your own neighbourhood). 

<details>

At least I certainly do not have mental capacity to remember history of hundreds to thousands of benches even in my home city, much less all locations I keep visiting. (If I was capable of that I wouldn't need OSM at all but would simply keep whole maps in my head :smile:).

And cooperation with other mappers is mostly impossible in such use case (e.g. one mapper notices and maps benches, another one deletes them, and third one adds them again - it would just go in infinite circle).
</details>

That's one of the reasons why I (as noted [before](https://github.com/streetcomplete/StreetComplete/issues/2074#issuecomment-716207661)) prefer using [Lifecycle prefix](https://wiki.openstreetmap.org/wiki/Lifecycle_prefix) instead of **deleting** nodes / ways in _such cases_ - as it makes it trivial (and automatable) to detect such seasonal changes and then mark them properly (as you see in the history of the node its changes)

> If someone maps seasonal objects that is on them to mark them as seasonal.

But how would one **know** they are seasonal (in order to mark them as such)? Is there some special marking visible on them? 

<details>
Because if the only real way to know is for single person to check in several different seasons (and keeping notes elsewhere about whether they appear/reappear), that sounds sub-ideal (it would also imply that one should only map such changing objects in areas where they are regular, and avoid contributing it in areas they're just visiting / passing through, and thus unlikely to regularly visit in different seasons). 

</details>

> In my opinion removing seasonal objects not marked as seasonal is much lesser damage than keeping nonexisting ones.

If you have huge number of mappers so it is likely that deleted objects would reappear in days after they reappear, I'd agree. 
<details>
<summary>but not otherwise...</summary>

If it would take them several months to notice and update the map, it would be useless, as the information would obsolete practically as soon as it was entered (mapping summer pavillion benches in fall is not very useful, especially when other user would delete them in late spring).
</details>

**Comment by mnalis** [comment]
> Let the "doesn't exist" answer lead to the creation of a note
> It looks like most think option 1 is the best, however what about option 3 brought up by mnalis?

Just to clarify that I would prefer that because:
- it **avoids a problem** of **_not_** asking for any details of `seasonal=yes` objects  (e.g. https://github.com/streetcomplete/StreetComplete/issues/3943#issuecomment-1087348670)
- while at the same time it **does not seem to introduce new problems** (that I can see - comments are welcome), as it would only be invoked when user actually wanted to remove the object (which we did for years by leaving a note with context, which in my experience often helped more than just removing the object - which is currently done).

**Comment by timothywashere** [comment]
Sorry for being offtopic, but _why_ do they remove benches in the winter?

**Comment by westnordost** [comment]
Okay, I'll use the solution 1 from https://github.com/streetcomplete/StreetComplete/issues/3943#issuecomment-1087331030 

Turns out this is the case already for the CheckExistence quest. But I added it for other quests that ask for properties of public park "furniture" too.

**Comment by hungerburg** [comment]
Well, I started an avalanche. Long story short: The person mapping the benches first is not to fault to not have marked them seasonal. You cannot expect a tourist to be as knowledgeable as a local, even though both contribute "local knowledge". The other person, also a tourist, that did remove some of the benches and later stopped doing that, because they got doubts about the correctness of their observations, is not to fault either.

The "existence" quest should have a means to mark object "seasonal", so the local SC users can protect them from the tourists and do not have to resort to JOSM or iD for this purpose ;)

**Comment by hungerburg** [comment]
> Sorry for being offtopic, but _why_ do they remove benches in the winter?

Not the whole of the bench is removed, just the wooden parts are taken care of in the workshop. This is, because winter time is strenuous to wood, much more than to concrete.

**Comment by Cj-Malone** [comment]
Now that SC is using `seasonal` a lot more can we get `amenity=grit_bin` in the CheckExistence? It was removed due to seasonal grit bins being removed. #2726

**Comment by matkoniecz** [comment]
For now I made https://wiki.openstreetmap.org/w/index.php?title=Tag:amenity%3Dgrit_bin&diff=2307500&oldid=2202701 edit (was discussed previously at https://wiki.openstreetmap.org/wiki/Talk:Tag:amenity%3Dgrit_bin )

**Comment by Cj-Malone** [comment]
Hmm, I can see "Other Answer" -> "Seasonal" also causing issues too. Maybe SC could be super picky for now and only check ones with `seasonal=no`, it'll probably be a small amount right now, but will get [2 thousand more soon](https://wiki.openstreetmap.org/wiki/Sheffield_Grit_Bins).
