### ISSUE TITLE
New quest: Add footway width

### ISSUE THREAD

**Issue by legofahrrad** [streetcomplete/StreetComplete#3945]
### General
Affected tag(s) to be modified/added: [`width`](https://wiki.openstreetmap.org/wiki/Key:width) / [`footway:width`](https://wiki.openstreetmap.org/wiki/Key:footway:width)
Question asked: **What’s the width of this footway here?**

It would be consistent asking for the footway's width, when asking for the cycleway's as well. Additionally, the surface quest has also this divison for footway / cycleway when segregated.

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/blob/master/QUEST_GUIDELINES.md)):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary *(→ use AR measurement feature)*
- [x] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of map data (Worth the effort)

### Ideas for implementation

**Element selection:** 
Same way as cycleway width quest, just replace 'cycleway' by 'footway' (See #698)

Show quest for paved…
- …footways without `width=*`
- …segregated paths without `footway:width=*`

**Metadata needed:** 
Same as at cycleway width quest

**Proposed UI:**
Same as at cycleway width quest
I created a quest icon, just by combining the "bicyleway_width.svg" and "footway_surface.svg" graphics:
![footway_width](https://user-images.githubusercontent.com/92865620/161800987-95ce1bd6-7ae2-4597-bd25-5d403d81bd12.svg)

I'm sorry if this is a duplicate but I didn't found something about footway widths here under Issues :)
I would be happy about feedback / more ideas for this quest.

**Comment by westnordost** [comment]
Could you explain about the useful purpose of widths on paths? What to do with trails (Trampelpfad) that have no clear boundary and/or vary in width every meter?

**Comment by andrewharvey** [comment]
> Could you explain about the useful purpose of widths on paths?

Is this single file or can you walk side by side.
Can my pram/wheelchair fit, can two fit side by side.

> What to do with trails (Trampelpfad) that have no clear boundary and/or vary in width every meter?

If the trail varies a lot the user can say it differs along the way, otherwise usually a measurement of a representative sample is good enough. Usually you can tell a rough width even for these unpaved trails based on it being more worn then the surrounding land.

**Comment by HolgerJeromin** [comment]
We could limit this to some surfaces (all paved and perhaps compacted as this was build up on purpose with a defined width).

But I am unsure if this tag has a useful purpose. 
I doubt that routers use that data or if there is some products is using that data (excluding raw tag view)

**Comment by westnordost** [comment]
@andrewharvey how many footways are not wide enough for a pram? I'd say if there are any that are not wide enough, they eventually turn into something that is wide enough simply because there will be some compacted ground around the (maybe paved) part simply by so many people walking on it.

(It looks like the handy word "Trampelpfad" does not exist in English - lit. "tramp path")

**Comment by mnalis** [comment]
I _sometimes_ find `width` of `paths`/`footways` important, although the problem is as noted that no data consumer takes this tag  into consideration. But I basically only use it to mark some to be of borderline (or no) usability for **all** pedestrians / cyclists. I usually do that by leaving SC picture notes and editing afterwards (or via Vespucci if I have a lots of battery and time to kill).

- if `highway=footway` + `footway=sidewalk` near a street is _very narrow_ (about 0.5m or less, depending on other obstacles like lightning poles sharing that space) then I usually do not map it all (or map it as `sidewalk:left=no`), unless the street is very busy and there is no alternative for non-motorized traffic nearby, in which case I do map it with `width=*` and as `highway=path` instead (as that gets rendered somewhat differently in some data consumers like OsmAnd) + `foot=yes` + `bicycle=no` + `wheelchair=no` for example.

- if that is `highway=path` (+ usually `surface=ground,dirt,grass...`) as some very narrow unpaved trail through the forest, I also add `width=*` and a slew of other tags (`informal=yes`, `wheelchair=no`, but also depending on situation `smoothness=bad` , `trail_visibility=intermediate`, `sac_scale=mountain_hiking`, ...)

But once the footway/path is wide enough that a wheelchair user can use it comfortably, I do not care about `width=*` of it.

**Comment by westnordost** [comment]
Maybe one case where it would make sense is non-segregated foot- and cycleways where bicyclists are **required** to use that footway and **may not** use the road instead:

[`highway=cycleway/footway/path + bicycle=designated + foot=designated + segregated=no`](https://wiki.openstreetmap.org/wiki/Key:segregated#Tagging)

![Zeichen 240](https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/Zeichen_240_-_Gemeinsamer_Fu%C3%9F-_und_Radweg%2C_StVO_1992.svg/240px-Zeichen_240_-_Gemeinsamer_Fu%C3%9F-_und_Radweg%2C_StVO_1992.svg.png)

But this is a German thing as far as I know: Cyclists are not required to use cycle tracks as long as there is not a blue sign with a white bicycle on it. The reason as far as I know for this set or rules are that cycle tracks are regularly in such a bad condition that it wouldn't be legal to force bicyclists to use these. Cycle tracks that are in proper shape usually always have such blue signs.

The blue sign above is similar only that it indicates that there is not really a dedicated cycle track, instead, cyclists must use the space assigned for pedestrians too. Oftentimes, the reason for that is that there is not enough space to accomodate both a cycle track and a sidewalk. But not always, sometimes a non-segregated foot- and cycleway is not problem at all. Sometimes it is. So, measuring the width of such ways may be worth it. But maybe only for Germany, or only if it is explicitly set that there is this sign present.

**Comment by westnordost** [comment]
So, the voiced concern about...
> 🤔 No unanswerable quests 
> 🐿️ Easy answer
might be partly solved by simply not asking for ways that are not paved.

However, looking at
> 🤷 Useful purpose
> 💤 No spam
> 💵 Valuable Surveyors
it is clear that this suggestion does not suffice the quest guidelines because
- 🤷 the use case mentioned is theoretical and despite that, really really rare because a negligible number of footways is narrower than 1m
- 💤 the vast majority of sidewalks in an area will have the same or a very similar width
- 💵 this does not warrant sending all the StreetComplete users on a quest to map out every width of every footway.

I.e. the volume of quests (=work) created is completely disproportionate to the imagined gain.

---

As mentioned, maybe https://github.com/streetcomplete/StreetComplete/issues/3945#issuecomment-1090367765 would make sense. But this needs to be an own ticket and need to be detailed more. It may also not be an own quest but rather an extension of the existing quest.

**Comment by mnalis** [comment]
For those interested, this functionality was [implemented](https://github.com/Helium314/SCEE/pull/462) in [SCEE](https://wiki.openstreetmap.org/wiki/SCEE) fork of StreetComplete.
