### ISSUE TITLE
Snooze quests

### ISSUE THREAD

**Issue by ahstro** [streetcomplete/StreetComplete#3952]
**Use case**

When unable to solve a quest, the only option to see another one for the current node is to hide the quest completely or leave a note.

**Proposed Solution**

It would be nice to be able to snooze quests, so that they are not permanently hidden, but doesn't hinder one from resolving other quests for the same node.

**Comment by matkoniecz** [comment]
note that you can restore quests in settings and reorder quests if you prefer different order

(it fulfills some reasons for snoozing quests, but not all - is it enough for you use case? If not, what exactly you wanted to achieve?)

**Comment by riQQ** [comment]
See also #3023 and #124

**Comment by mnalis** [comment]
Another workaround that I sometimes employ is:
- hide the problematic quest
- solve other quests there (that were shadowed by now-hidden quest)
- press undo button (in lower left corner) and undo **_only_** that `hide` command from 1st step (it's easy to locate in undo list, due to it having `eye` icon)

that preserves status of all other hidden quests.

**Comment by westnordost** [comment]
What quest would you want to snooze, and why?

**Comment by mnalis** [comment]
For example building quests. I (as well as SC default, as it should be) prioritize important information like `housenumber / addresses`, but often houses are between two streets, and only on one street is entrance with visible `housenumber / address`. But I can still _**solve all other**_ building-related quest while being on _"wrong"_ street, so I _temporarily_ skip `housenumber / address` quest (but I still very much want to solve that quest later, maybe even that same day on return part of the trip if passing there)

Another time it might be the the road attributes of **_longer stretch of the road_** - I can see (for example) it is `lit=yes` and `surface=asphalt` and `smoothness=excellent` all the way, but `sidewalk` situation on it changes more often. While I generally find `sidewalk` more important (which is also SC default, as it should be), it pays to solve all the other quests (which don't change) **before splitting** the road in several smaller pieces (because if I do it other way around by first splitting in `sidewalk` quest, I need to solve much more quests for same result)

Or crossing quests (e.g. depending on time of the day/night and surrounding noise I might skip `tactile paving` to get to `beeping` quest, or vice versa, when the other is hard to tell). Same with `tactile paving` vs `lit` on bus stops. 

---
(Those are the few examples of different situations that come to mind; there are likely more but I'd have to pay attention and write them down)

Note that it happens often enough to me that I've also developed quite a fondness of @Helium314 [fork](https://github.com/Helium314/StreetComplete/) feature for `one-click-hide-button` (instead of default 3-click `Other answers` / `Can't say` / `No, just hide`) which I include in my own fork too (although I'm currently currently still reintegrating some patches that broke along the way). His fork also include quick button for `reverse quest order` which is hacky way to _quickly workaround_ this issue (because it makes such "blocking" quest last in line of quests, instead of first - but obviously work only if there is only one blocker quest, but that is the case in vast majority of the cases anyway)

**Comment by dbdean** [comment]
This would be useful, but a good solution to https://github.com/streetcomplete/StreetComplete/issues/124 would be more useful for me.

**Comment by westnordost** [comment]
Hm well, I will not implement this the way it was suggested. That functionality would just open another bag of things that don't quite work for that use case: For example - how long will the quest be snoozed? Is it really possible to find any predefined time that would not feel unwanted in every case? I don't think so. #124 describes the root problem and that is that quests occlude one another, so that ticket is a better description would should be improved (if it was possible technically).

**Comment by FloEdelmann** [comment]
For reference: Another idea from #4324: temporarily move one quest type to the end of the quest order. But it has the same problems as the ideas suggested in this issue.

**Comment by OpenGreenStreet** [comment]
@FloEdelmann Thanks for your effort

**Comment by OpenGreenStreet** [comment]
By the way: for me personally it would be enough if fading out of the task would be done for about 5 minutes
