### ISSUE TITLE
Cannot add photo to note

### ISSUE THREAD

**Issue by MikaelBe** [streetcomplete/StreetComplete#3967]
**How to Reproduce**

Create new note at my present location.
Click "add photo to the note".
Take photo.
Accept the photo (check mark).
Click OK to save the note.
Result: note gets saved, but:
* No photo is attached.
* I cannot see the resulting note in my streetcomplete app. 

To be clear:
* I can see my notes in the iD editor - but without images.
* I can see other people's notes - with links to their images - in the streetcomplete app.
* Neither I nor my wife can see my (open) notes in the app.

**Versions affected**

Streetcomplete v. 42.0
Android v11, Moto One Hyper, model nr XT2027-1
Username: \Mike
And that's 5 characters, yes, there's a backslash in my username/display name. Could this mess something up? I tried to change my display name on openstreetmap.org to something without that special character, but can still not see my own notes. Haven't tried adding a photo since the display name change.

**Comment by MikaelBe** [comment]
Typo.

**Comment by peternewman** [comment]
Well you've obviously gone:
https://www.openstreetmap.org/user/%5CMike/notes

Is this now you?
https://www.openstreetmap.org/user/Mike/notes

I'd start by trying to add a new note now you've changed your name?

When you say without images, do you mean they have the link but it points to a 404?

This sounds like potentially two bugs, firstly you can't see notes with your edge case username in SC (is this all, or image only ones)? Secondly your edge case username doesn't correctly attach images to notes.

Does this also happen if you comment on someone else's note with an image?

**Comment by matkoniecz** [comment]
Can you link one of affected notes?

**Comment by MikaelBe** [comment]
I changed my user name to Mike_Be.

One of the notes from yesterday that I apparently haven't closed yet is this: https://www.openstreetmap.org/note/3136708 (old user name; I tried to take a photo when I created this note)

No, there were no links whatsoever.


**However**: on today's walks, the photo in note *did* work: see https://www.openstreetmap.org/note/313826


If I make a note in SC it never shows up there, and if I comment on another user's note, it disappears from SC for me.
https://www.openstreetmap.org/note/3130098 (was visible in SC until I added the comment, now it's gone from SC for me).
Am I supposed to be able to do see my notes? When reading these discussions here today, I saw someone mentioning in passing something about "since I can't see my own notes in SC, I have to...". I'm not sure if I'll be able to find that comment again, but that made me think that this was a design decision?



So I guess at least one part of the bug could be closed as there's a workaround: don't use  the \ character in the user name, at least not as the first character. 
That fixed the photo-in-note issue, but there might still be a "can't see own notes" issue where I'm not sure about intended behavior.

**Comment by MikaelBe** [comment]
I asked another user if they can see my unresolved notes in the SC app. They can not.

They couldn't either see the note where I had commented on their existing note (3138263). Not clear if they would have been able to see their own notes before I commented, of if my comment was what hid it.

**Comment by peternewman** [comment]
See Settings>Show all notes, for some background see #2692 and #3002. Checking on OSM proper is a better test.

The photo stuff is probably still independent.

**Comment by matkoniecz** [comment]
> One of the notes from yesterday that I apparently haven't closed yet is this: https://www.openstreetmap.org/note/3136708 (old user name; I tried to take a photo when I created this note)

What you mean by "tried to take photo"? Have you managed to see photo attached in SC?

I suspect that things are going wromg with your photo app or with handover of photo to SC.

**Comment by westnordost** [comment]
The OSM username is not used in any part of the taking-a-photo process. So when you rename yourself to \Mike, can you still reproduce this?

Generally, if there is an error while taking the photo (cannot write to disk etc.), there should be a toast that shows an error message. An error message is only not shown if either
- the app does not have the camera permission and the user declined to grant it
- the photo app reported back that no picture was taken

**Comment by MikaelBe** [comment]
I can't comment on what the camera app does or does not do. All I can report is what effects I see, and that was that I tried perhaps a dozen times to add a photo to a note when I used the user name "\Mike" and zero of them got saved; then I changed user name and succeeded in perhaps 6 out of 6 attempts, so I did indeed draw a, perhaps premature, connection between that user name and the behavior of the app. 

I have now changed my user name back, and have managed to get the app to attach photos to notes in 3 out of 3 attempts. 
No, I don't know how to explain that.

Time to close the bug as unreproducible?

**Comment by westnordost** [comment]
Yeah, I guess. My bet is on the camera app, but 🤷

**Comment by gojhub** [comment]
I have the same problem with v42.0 (f-droid) on a Sony Xperia XA2.

I recently noticed that attaching photos to notes doesn't work anymore, but the behavior is a little bit other than the on described by MikaelBe:
1. I press the camera button in the note editor, 
2. the default photo app opens, 
3. I take the photo, 
4. the photo app closes, but _no_ confirmation, _no_ preview viewer
5. and the photo is not attached.

> Generally, if there is an error while taking the photo (cannot write to disk etc.), there should be a toast that shows an error message. An error message is only not shown if either
> 
> * the app does not have the camera permission and the user declined to grant it
> * the photo app reported back that no picture was taken

I didn't get a error toast, and the app has the camera permission (checked it), so your explanation seems that the photo app reported that no photo was taken...

But it worked in the past and afaik I had not changed anything since then.
* The last note with photo in my history was taken with StreetComplete v40.2.
* The first note which should have a photo but it wasn't attached was taken with StreetComplete v41.2.

**Comment by Cj-Malone** [comment]
Did anyones version of Android change?

Just checked on v42.0 from FDroid. Mi A1, Lineage OS 18.1/Android 11.

It worked like usual. Launched the normal camera activity, confirmed it and the thumbnail was at the bottom as expected.

**Comment by gojhub** [comment]
Not mine, it is still an Android 9...

**Comment by Cj-Malone** [comment]
> But it worked in the past and afaik I had not changed anything since then.
> 
>     * The last note with photo in my history was taken with StreetComplete v40.2.
> 
>     * The first note which should have a photo but it wasn't attached was taken with StreetComplete v41.2.

https://github.com/streetcomplete/StreetComplete/commit/103b662481fca5e528a78d6e17aa6848c6237b9d

**Comment by westnordost** [comment]
@gojhub try downgrading to v40.2, can you attach a photo? Then upgrade to v41.2. Can you attach a photo?

**Comment by gojhub** [comment]
@westnordost I tried to downgrade, but the installer told me it can't do it for an unknown reason...

So I decided to do a reboot and before trying again to downgrade, I tested it again with v42...
I think you can guess it, now it works... The photo app closes and below the input box finally the icon with the photo preview appeared as before.

But: As my mobile nags me after 28 days that I really should do a reboot and I obey my mobile ;-), I had done a reboot not so long ago (maybe two weeks ago). Don't know why this reboot now solves the problem.

So, sorry for the noise, can't confirm @MikaelBe problem anymore.
@MikaelBe: Had you tried to reboot your device? Maybe it works for you too?

**Comment by westnordost** [comment]
Hm. Another theory:

The app asks for the camera permission before taking a photo. If the user denies it, a rationale is displayed and after acknowledgement by the user, asks again. If the user then denies this again, the app will not ask for permission at all anymore. 

(This is enforced by the Android system, to the app it just looks as if the user has denied the permission.)

Now, for v41, the camera permission was added. Maybe for some Android versions, an upgrade to v41 led to a state where the camera permission was not granted **and** it was set as "do not ask again".

**Comment by westnordost** [comment]
Oh nevermind, a message is shown to the user in that case "no camera permission". 

Actually, in case a photo is not attached, the only code path where no (error) message is displayed is when the photo app simply does not return a photo.

**Comment by gojhub** [comment]
Interesting, now after three days I couldn't take photos again.
It's the same as described above, no error message, but also no photo for the note.

And now I'm really sure, that no update of Android or the photo app happens.



-------- Ursprüngliche Nachricht --------
Von: gojhub ***@***.***>
Gesendet: 20. April 2022 22:34:36 UTC
An: streetcomplete/StreetComplete ***@***.***>
CC: gojhub ***@***.***>, Your activity ***@***.***>
Betreff: Re: [streetcomplete/StreetComplete] Cannot add photo to note (Issue #3967)

@westnordost I tried to downgrade, but the installer told me it can't do it for an unknown reason...

So I decided to do a reboot and before trying again to downgrade, I tested it again with v42...
I think you can guess it, now it works... The photo app closes and below the input box finally the icon with the photo preview appeared as before.

But: As my mobile nags me after 28 days that I really should do a reboot and I obey my mobile ;-), I had done a reboot not so long ago (maybe two weeks ago). Don't know why this reboot now solves the problem.

So, sorry for the noise, can't confirm @MikaelBe problem anymore.
@MikaelBe: Had you tried to reboot your device? Maybe it works for you too?

**Comment by westnordost** [comment]
When it does not work - does it fix it if you remove StreetComplete from recents (i.e. cold re-start) the app? Or the other way round: If you remove the camera app from recents?

**Comment by gojhub** [comment]
I did some testing, for which I removed all apps from recents.
In this series I started StreetComplete, did a long click near my location for taking a note, clicked directly on the photo icon, made a photo and checked if it would be attached to the note. Neither if it does or not I canceled the note taking with the back button, hit the square for the recents, swiped StreetComplete away and started over.

In the afternoon I had a long series of around 25 continuous attempts for which no photo was attached.
A few moments ago I had a series of 8 continuous attempts for which a photo had been attached to the note editor, then the ninth try resulted in no photo...
Currently I see no reliable way to provoke either case.

In the meanwhile I got the notification about running out of space on my internal space, so I had a look at `/storage/emulated/0/Android/data/de.westnordost.streetcomplete/files/Pictures` and found all the pictures of my failed attempts. All with a filename like `photo_<13digit code>.jpg`, where the digit code seems to be the unix timestamp.
Could it be that the photo app saves the picture but tells StreetComplete that no photo was taken?

**Comment by westnordost** [comment]
Interesting... does the photo file contain the photo at all, or is it empty?

**Comment by peternewman** [comment]
> In the meanwhile I got the notification about running out of space on my internal space, so I had a look at `/storage/emulated/0/Android/data/de.westnordost.streetcomplete/files/Pictures` and found all the pictures of my failed attempts. All with a filename like `photo_<13digit code>.jpg`, where the digit code seems to be the unix timestamp. Could it be that the photo app saves the picture but tells StreetComplete that no photo was taken?

FWIW I looked at the same place out of curiosity and I had three files in mine, two test ones showing bits of my sofa, and a postbox from in the real world.

Mine were all from a long time ago, but shouldn't these failed photos be cleaned up at some point at least?

**Comment by gojhub** [comment]
> Interesting... does the photo file contain the photo at all, or is it empty?

All files contains the photo, e.g. yesterday a lot of photos of my feet on the terrace. But also the photos of the situation which reminds me to report a issue about it.

**Comment by westnordost** [comment]
Thank you for this clue. I think I now know what is happening:

The process of taking a photo is interrupted if the `AttachPhotoFragment` (the view that lets you add, delete, ... photos) is destroyed. Android destroys views at its own leasure (and recreates them when necessary), usually due to memory restrictions. This also explains why it is reproducible only sometimes.
In detail, the process of taking a photo is within a suspending coroutine which is being cancelled when the fragment's view is being destroyed.

Right now I can't think of a good solution for this, will think about this some more.

**Comment by westnordost** [comment]
This can be reproduced reliably when enabling "Don't keep activities" in the developer options.

The issue is that the asynchronous "start another activity and return its result" in StreetComplete has been (recently) refactored to work with coroutines so that it can be written like synchronous code. E.g. something like
```kotlin
if (!hasCameraPermission && !requestCameraPermission()) return
val photo = takePhoto()
resizePhoto(photo)
// etc...
```
...instead of the above code scattered all over the place in a state machine because activities are (potentially) volatile. It is too bad that I didn't think of this case before.

This method is not only done for taking a photo, but also for measuring a width/height, for requesting location to be enabled and for requesting camera permission (for AR). This refactor made the code and logic much easier to read and much shorter, so I am kind of reluctant to revert this (if I even cleanly put that refactor into one commit).

I am considering (finally) using [ViewModels](https://developer.android.com/topic/libraries/architecture/viewmodel) (and thus `viewModelScope` for coroutines) in StreetComplete to circumvent this, if only (at the start) for those places where other activities are started for a result. Using ViewModels would make sense anyway, but the app was created before that library existed and to really consistently use ViewModels everywhere is a huge refactoring undertaking.

So, I don't know, other ideas or volunteers who'd like to try out initial ViewModel support are welcome.

**Comment by westnordost** [comment]
I noticed that the ViewModels wouldn't solve this at all, because ViewModels have of course no access to the view. But starting an activity for result is done from fragments / activities, which are part of the view.

**Comment by Helium314** [comment]
Since the photos exist, SC could just look whether there are some new ones.
Example how this could be done: https://github.com/Helium314/StreetComplete/commit/a9c1b316c23fb4ffb186a49f3d0244daedb55418 (rough solution, working only for the first note).
Then the new photo(s) would be processed normally, i.e. resize and create the mini-preview.
