### ISSUE TITLE
`barrier`=`kerb` should be removed instead of adding `kerb`=`no`

### ISSUE THREAD

**Issue by dbdean** [streetcomplete/StreetComplete#3983]
**Use case**
When there is a `barrier`=`kerb` and the barrier-height SC quests gets answered that there is no kerb, then the `barrier`=`kerb` tagging should just be removed, rather than adding `kerb`=`no`.

An example would be this changeset, where another mapper has commented that this is not really correct tagging: https://www.openstreetmap.org/changeset/110599035#map=19/-30.49917/151.63539&layers=N.

**Proposed Solution**

Just remove the `barrier`=`kerb` tagging.

**Comment by HolgerJeromin** [comment]
Some routers are probably ignoring barrier=kerb with some routing presets without looking at kerb=no.

**Comment by cyrossignol** [comment]
SC 43.0 appears to add back the `barrier=kerb` tag when answering whether a node tagged with `kerb=no` has tactile paving:

```diff
 kerb=no
+barrier=kerb
+tactile_paving=no
```

Is that intended behavior? Or is this a separate issue? I'd imagine that the tactile paving quest should ignore crossing ways tagged with `kerb=no`.

**Comment by matkoniecz** [comment]
Can you link specific object or edit? I expect that it is again this specific bug in one of changeset analysis tools.

**Comment by cyrossignol** [comment]
I rebuilt with a minor change to [KerbUtil.kt](https://github.com/streetcomplete/StreetComplete/blob/558ae6bd529be11372c75895e8117e252e731178/app/src/main/java/de/westnordost/streetcomplete/osm/kerb/KerbUtil.kt#L63) to just hide the noise:

```diff
--- a/app/src/main/java/de/westnordost/streetcomplete/osm/kerb/KerbUtil.kt
+++ b/app/src/main/java/de/westnordost/streetcomplete/osm/kerb/KerbUtil.kt
@@ -56,16 +56,18 @@ private val allowedKeysOnKerbNodeRegexes = getLastCheckDateKeys(".*").map { it.t
 /** Most nodes **could** be a kerb, depending on their location within a way. However, nodes that
  *  are already something else, e.g. shop=hairdresser are definitely NOT a kerb.
  *
  *  If any node **could** be a kerb, this would lead to an unacceptable performance hit when any
  *  node is updated due to an answered quest. See
  *  https://github.com/streetcomplete/StreetComplete/pull/3104#issuecomment-889833381 for more
  *  details on why this function exists */
-fun Node.couldBeAKerb(): Boolean = tags.keys.all { key ->
-    key in allowedKeysOnKerbNode || allowedKeysOnKerbNodeRegexes.any { regex -> regex.matches(key) }
+fun Node.couldBeAKerb(): Boolean = tags.entries.all { (key, value) ->
+    // Ignore nodes explicitly tagged as not-a-kerb:
+    (key != "kerb" || value != "no")
+    && (key in allowedKeysOnKerbNode || allowedKeysOnKerbNodeRegexes.any { regex -> regex.matches(key) })
 }

 /** Find all nodes that are (very likely) kerbs in this map data:
  *  1. nodes tagged with barrier=kerb
  *  2. the shared nodes at intersections of barrier=kerb ways with footways
  *  3. certain shared nodes between a footway=sidewalk and a footway=crossing */
 fun MapData.findAllKerbNodes(): Iterable<Node> {
```

As a potential benefit, it seems to filter `kerb=no` nodes out from any kerb-related quests. However, this approach prevents any resurveying that we may want to do in the future for `kerb=no`.

**Comment by matkoniecz** [comment]
Hmm, I added https://github.com/streetcomplete/StreetComplete/commit/ad7b312628d402761fd2b55f1fb844784f0a2e05 - but maybe stopping asking curb question in places without curb would be even better

On the other hand on such curbless transitions info about tactile paving is the most valuable...

**Comment by cyrossignol** [comment]
That's a good point. I've never seen any curbless paving with tactile bumps before, but maybe these exist in other places.

If the `AddTactilePavingKerb` quest shows up for nodes with `kerb=no`, though, the wording of the prompt may need to change based on the value of the `kerb` tag. It seems confusing to ask whether a curb has tactile paving immediately after someone already answered that no curb exists for the `AddKerbHeight` quest, especially since the answer is probably "no" again.

**Comment by matkoniecz** [comment]
> I've never seen any curbless pavement with tactile bumps before

I have seen some. And some without. And encountered complaints from organization of blind people how this kind of thing is extremely dangerous and confusing for blind people, as makes extremely hard to judge where sidewalk/carriageway border is.

**Comment by cyrossignol** [comment]
I agree&mdash;the presence of tactile paving seems like a very important detail. I thought about it some more, though, and I'm not sure whether this is information that StreetComplete collects effectively for `kerb=no` nodes.

I'll refer to this map of a foot path crossing a road:

```
        │ │
───K╌╌╌╌┼C┼╌╌╌╌K───
        │ │

───   highway=footway
╌╌╌   highway=footway + footway=crossing
│ │   highway=* (motor_vehicle=yes)
```

If a separately-mapped walkway intersects a major road, I think that we'd almost always tag the `K` nodes with `barrier=kerb` + `kerb=*` in countries where tactile paving is common, so it makes sense to ask about tactile paving for these cases.

My concern is for crossings through minor roads like driveways, service roads, etc. At many of these, a paved sidewalk continues across the road with no real-world delineation for the crossing. I think it makes sense to tag the `K` nodes with `kerb=no` like we do now.

However, I'm skeptical about the usefulness of tagging `tactile_paving=*` on the `K` nodes at `kerb=no` crossings. Assistive technology could potentially use the information to communicate whether tactile paving exists when entering and exiting a separately-mapped crossing, but SC also collects this information for the crossing's `C` node, and it is simple enough for software to offer the tactile paving information from the `C` node for the crossing's `K` nodes.

Besides that, I can't think of another way for a map with `kerb=no` + `tactile_paving=*` nodes to help visually-impaired users. For StreetComplete mappers, these separate crossings already manifest as some of the most complex areas to edit due to the high number of small, dense features with several associated quests. Skipping the `AddTactilePavingKerb` quest for `kerb=no` nodes avoids the burden of answering a confusing prompt for a tag that seems hard to take advantage of in the real world.
