### ISSUE TITLE
[Feature request]: More intuitive one-way-question.

### ISSUE THREAD

**Issue by AndreasHoffmann2** [streetcomplete/StreetComplete#3984]
**Use case**
I was using SC in Amsterdam and was asked for the cycle-infrastructure in one street. Like a gazillion times before, I selected "none/none", since there was no infrastructure for cyclists.
Out of nowhere, I was then asked if I am sure that cyclists can only use this one-way-road in one direction.
I did not understand it at all. I did not intend that change. And in all the other cases where I selected "none/none", this did just mean that cyclists need to use the road just like cards. It did not change whether cyclists are allowed to use the street at all.

And since cyclists were actually allowed in both directions in this street, I wanted to fix that. But since I did not know where I selected "one-way-use-only", I did not know how to do that.

The app should be more clear here.

**Proposed Solution**
Solution 1:
Split this into two questions:
1.) Ask for the infrastructure.
2.) Ask whether cyclists are allowed to use the street in the opposite direction (if the question is still necessary then).

If this is not possible with the tagging in OSM, I propose
Solution 2:
Change the dialog to:
"Are cyclists allowed to drive in the opposite direction in this one-way-road? In doubt, check if there is a sign at the end of the street." Yes/No/Abort

When selecting "yes" SC would silently fix the user-input before upload.

With this message, there are clear instructions for the user, what he needs to do.

It is still not transparent, **why** this does pop up. But at least, the user can answer it and move on.

There is already some discussion about this: https://github.com/streetcomplete/StreetComplete/discussions/3966

Screenshot of the dialog:
![image](https://user-images.githubusercontent.com/8135241/164518581-a03d3999-c462-40cd-a4a0-377067578b68.png)

**Comment by matkoniecz** [comment]
I am working on related feature which, I think, solves this issue.

Would it be more clear to have following options for side which goes in opposite direction of general traffic

![screen](https://user-images.githubusercontent.com/899988/164526377-68356fcc-8908-4cd2-8d35-5b8b9bd91077.png)

and this for direction with regular traffic

![screen01](https://user-images.githubusercontent.com/899988/164526656-fa24a4a1-c57c-4cb8-9668-7b4e8db8e522.png)

? (icon is a placeholder)

**Comment by westnordost** [comment]
Interesting idea. I've thought some time about this today and yesterday and I think the following solutions would be best:

1. In case of oneway roads, for the contraflow side, display a floating ⛔ icon on top of the side in the _street side select illustration_ (not in the select dialog)
2. if the sign ⛔ differs substantially for certain countries, localized versions of that icon should be created the same way as for the living street icon
3. In case of oneway roads, for the contraflow side, change the wording to "none and no cycling into this direction (oneway street)" or similar
4. **optionally**: change the icon in the select dialog to also include the ⛔ icon (e.g. instead of the ❌). If the ⛔ icon needs localized versions per countries, it may be worth it to generate that icon programmatically, see `WithFootnoteDrawable.kt` for how to do that

The text in the dialog can then stay as is. I can see the sense in the proposed re-wording, but I find it inconsistent as it de-facto changes the user-selection without the user being able to review it. The solution written above tries to solve the issue more at its root.

@matkoniecz Will you implement this?

Regarding the draft implementation for #3544, I answered in that ticket.

**Comment by AndreasHoffmann2** [comment]
Please keep the option to select the last choice in mind (before alle the options are shown). If the choice "none" is renamed to "none and no cycling in this direction" in one-way-roads, the red cross in the preview should definitely be replaced by the "do-not-enter" - sign.

**Comment by matkoniecz** [comment]
> street side select illustration

You mean display on the road diagram, right?

> @matkoniecz Will you implement this?

I can do this, though for now I prefer my solution with separate "no" value.

**Comment by matkoniecz** [comment]
> "none and no cycling into this direction (oneway street)" or similar

what about
"none, no cycling allowed on this side"
?

"into this direction" would be confusing with dual-direction lane/track on the other side

**Comment by westnordost** [comment]
> You mean display on the road diagram, right?

Yes

> what about
> "none, no cycling allowed on this side"
> ?

🤷 fine too

**Comment by westnordost** [comment]
@matkoniecz I researched all the different sign styles over the world and added graphics for it.

**Comment by matkoniecz** [comment]
@westnordost Do you remember which is present where? Or at least which countries are special?

( https://github.com/streetcomplete/StreetComplete/commit/c4ccbdf2b613b5ff778978fdf4255e53a062cb92 )

**Comment by westnordost** [comment]
https://github.com/streetcomplete/countrymetadata/blob/master/data/noEntrySignStyle.yml

**Comment by westnordost** [comment]
> >  @matkoniecz Will you implement this?

> I can do this, though for now I prefer my solution with separate "no" value as it seems more clear to me

I'll do this now.

**Comment by westnordost** [comment]
https://user-images.githubusercontent.com/4661658/168190270-9555d03e-1095-4299-aced-26a4caf07ef4.mp4
