### ISSUE TITLE
Switch to swipe-friendly UI for building storey quest

### ISSUE THREAD

**Issue by mlell** [streetcomplete/StreetComplete#3999]
**Use case**
The building storey quest is something that is filled out very repetitively in some areas (e.g. residential areas that consist only of auto-generated data from satellite imagery. Therefore small improvements here can have a large effect on how tedious filling in those quests is. 

The  current quest UI uses two text fields. This makes things slow and tedious in the long run, as tapping on the text fields opens a keyboard (with a minor delay), you type in the number, you close the keyboard, tap on the other text field, and so on. Displaying and removing the keyboard shifts the positions of the UI elements, so one has to reorient. Not a big deal when filling out one or two quests, but for a whole street this is annoying in my feeling, so that I disabled this quest. 

<img src="https://user-images.githubusercontent.com/16210594/166137258-1cc2e177-d9ed-4052-a11c-d3d7b2640028.png" width = "200" alt = "Screenshot of StreetComplete UI of building storey quest with text fields" />

**Proposed Solution**

Use spinners, which can be moved via swiping, to set the number of storeys. One element of the spinner can be a "-", which is the default setting and the "OK" button appears only if we have not moved away from that value, as the equivalent of the empty text field in the old UI.  

<img src="https://user-images.githubusercontent.com/16210594/166137632-e56131c1-071d-4374-8a80-21a36b1656c8.png" width = "200" alt = "Mock UI with spinners instead of text fields"> />

**Comment by mnalis** [comment]
After using it for a while, I've personally found out that I **_very rarely_** use those numeric fields when solving this quest. Instead, in vast majority of cases (after I mapped first few) I almost always click on one of **_recent answers_** presented below instead, as even just 2-3 of those cover >95% of the cases for me.
 
Have you @mlell perhaps tried those and seen how well they work for you?

Using spinner might indeed be easier for that few remaining percent, but would also use more screen estate, requiring smaller items, and thus making the quest problematic to use in colder weather with gloves (or at all, for those of us with fatter fingers) - especially as some translations are even longer than German ones, using even more screen estate.

**Comment by eginhard** [comment]
Also, if you tap the "Enter" key on the keyboard, it will advance to the second field. You don't need to close the keyboard in between or manually select the other field.

**Comment by westnordost** [comment]
I tried it out right now with an Android `NumberPicker`, however my impression was that it doesn't work as well. Some may be limitations of the `NumberPicker` class with may be mitigated by coding an own number picker, but that's more effort. Impressions:
- number picker loops around at min/max, e.g. if 0 is displayed, the "number" above is e.g. 100 or whatever one set as max levels
- number picker's height is too big, there is no space left for the description
- on the other hand, the size of the number displayed is pretty small. Not sure if it can be customized
- it looks like the Android number picker does not have a value for "not set"
- **generally**: when using the app with just the right hand, the left number picker is difficult to reach with the right thumb because it is on the other side of the screen

So, I don't think it is worth it. However, you or anyone else interested may experiment with this, maybe you find a solution that actually improves usability there. Maybe a different but still worth to try out feature would be to allow swiping on the building illustration. Swiping Up/Right on the levels-part increases the levels, swiping down/left on the levels-part decreases the levels. The same for the roof levels.

**Comment by westnordost** [comment]
So anyway, I will close this as will not fix, you may reopen and/or create a PR if you find a solution that improves usability.
