### ISSUE TITLE
Wording improvements

### ISSUE THREAD

**Issue by 10992-osm** [streetcomplete/StreetComplete#4044]
I'm leaving things relating to `en-GB` specifically in POEditor comments.

More generally:
- `map_btn_stop_track` "Stop Recording Track" → "Stop recording track"
- `quest_bicycle_rental_type_human` "Human-operated" sounds a bit odd, I've tentatively proposed "staffed" for `en-GB`, but that might not be appropriate for `en`.
- `quest_building_entrance_staircase` "of apartment building" → "for"?
- Generally, "bicycle" or "bike"?

**Comment by mnalis** [comment]
- Generally, I'm more comfortable with "bicycle". Even if slightly longer, it is clear and precise. 
On the other hand, "bike" is often used to mean "motorbike" as well as "bicycle", so there is ambiguity there.
- I also slightly prefer "staffed" instead of "human-operated" (but both have clear meaning to me)

Note: if POEditor comments do not cut it, discussions like this should be under GitHub "Discussion", not "Issue". 
Issues are reserved for clearly defined and **actionable** items.

**Comment by matkoniecz** [comment]
> I'm leaving things relating to en-GB specifically in POEditor comments.

Which of them are about root (USA) language version?

**Comment by FloEdelmann** [comment]
> `quest_building_entrance_staircase` "of apartment building" → "for"?

I think it's an entrance *to* a staircase *of* an apartment building. So isn't it a staircase entrance *of* an apartment building?

**Comment by 10992-osm** [comment]
> > `quest_building_entrance_staircase` "of apartment building" → "for"?
> 
> I think it's an entrance _to_ a staircase _of_ an apartment building. So isn't it a staircase entrance _of_ an apartment building?

I'd forgotten what the whole string was, and I perhaps should have put it in there originally, rather than abbreviating it.  It is currently:

"Staircase entrance (e.g. of apartment building)"

On reflection, I no longer think "for" is the right word, but I'm not sure "of" is either.  The *of* here is modifying entrance.  You can say "entrance of", but I wouldn't in this circumstance.  I'd probably use "in an" or "to an", and I might be inclined to replace *staircase* with *stairwell*, though that might just be `en-GB`.

Alternatively, you could put "Entrance to a staircase (e.g. of an apartment building)".

**Comment by FloEdelmann** [comment]
> replace _staircase_ with _stairwell_, though that might just be `en-GB`

It doesn't seem like it's a regional difference; maybe in US English, the terms can be used more interchangeably:

* https://ell.stackexchange.com/questions/78806/stairwell-or-staircase
* https://dict.leo.org/forum/viewGeneraldiscussion.php?idThread=1071641&idForum=4&lang=de&lp=ende
* https://hinative.com/en-US/questions/13033692

> I'd probably use "in an" or "to an"

Ok, let's go with "to an" then, since the entrance is technically not in the building, but exactly between inside and outside.

**Comment by ZeLonewolf** [comment]
Stairs, steps, stairwell, staircase are somewhat interchangeable.  To me (and this might be regional within the US), stairwell and staircase sound like they're inside a house, and stairwell specifically sounds like they're stairs to a lower level (i.e. stairs within a well).  But all 4 words would be 100% understood in en_US.
