### ISSUE TITLE
StreetComplete 43 and 44 does big changesets which are not liked by community

### ISSUE THREAD

**Issue by agent-redd** [streetcomplete/StreetComplete#4081]
The OpenStreetMap community does not like big changesets, which span over several hundred kilometers. The general recommondation is: "Changesets should be local" (see https://wiki.openstreetmap.org/wiki/Changeset#Geographical_size_of_changesets).
These changesets often get comments to be asked for smaller ones in the future. 

I checked the FAQs and it does not adress this behaviour yet. Therefore I consider this behaviour as unknown and not intented to the users of StreetComplete.

**How to Reproduce**
Reproduced in the past. See Changesets examples:
* https://www.openstreetmap.org/changeset/121963131
* https://www.openstreetmap.org/changeset/121930378 (commented)
* https://www.openstreetmap.org/changeset/121839578
* https://www.openstreetmap.org/changeset/121839564
* https://www.openstreetmap.org/changeset/121837494
* https://www.openstreetmap.org/changeset/121568962 (commented)

**Versions affected**
at least:
* v43
* v44

Edit: add more changesets and wether they are commented by community. Also added wiki link

**Comment by 10992-osm** [comment]
I think this has already been discussed and rejected.  I'll try to find some links, and edit this comment to add them…

**Comment by 10992-osm** [comment]
I think the bottom line is that it has occurred in the past due to bugs when uploading, but I believe these have been fixed.  If they haven't, then we need to identify what is going wrong now.

The other situation where it can occur is where a user makes changes that are not automatically uploaded, due to the user's settings.  This can be either because the user has said that they only want quests to be uploaded on Wi-Fi, and they haven't connected to it, or they have said that they want to manually select when to upload, and have done this after making geographically disparate changes.  This is ± intended behaviour, though the last one is unfortunate user behaviour.

**Comment by agent-redd** [comment]
thanks for the hint for Upload only on Wi-Fi. Why should somebody want this? Isn"t downloading the map data much more data then the small changeset?

**Comment by matkoniecz** [comment]
> thanks for the hint for Upload only on Wi-Fi. Why should somebody want this?

privacy reasons

With uploading on go you give live and accurate real-life location, for example https://www.openstreetmap.org/changeset/121899306 reveals where I was on 14:38 two days ago. Bundling edits reduces accuracy.

**Comment by matkoniecz** [comment]
In general, is there a case where:

- user was editing what they surveyed (no remote edits)
- user has not caused large bbox via deliberated delay

?

**Comment by matkoniecz** [comment]
> I checked the FAQs and it does not adress this behaviour yet. 

https://wiki.openstreetmap.org/wiki/StreetComplete/FAQ#Changeset_made_with_StreetComplete_covers_massive_area

**Comment by BalooUriza** [comment]
At least on my phone (a Pixel 3XL) the performance and stability
improvement from not automatically uploading in real time is substantial,
especially in parts of America with bad data throughput.  The other
possible solution to this would be to allow user selectability to download
all quests within a bounding box as a batch, so that the internet
connection has some hope of keeping the upload queue clear (though that
would be nice to have anyway for planned trips given the low reliability of
mobile internet in general, and in the southern midwest specifically).

**Comment by mnalis** [comment]
Related discussion (about detecting if user was really there on the ground according to GPS): https://github.com/streetcomplete/StreetComplete/discussions/4017
