### ISSUE TITLE
Low location accuracy and infrequent updates on Fairphone

### ISSUE THREAD

**Issue by nicorikken** [streetcomplete/StreetComplete#4104]
Using Streetcomplete in my new Fairphone 4 in the car in Austria I notice a downgraded experience which makes it hard to use Streetcomplete. I'm still trying to pinpoint the issue compared to my experiences on my previous Nokia 8.1 and usage in the Netherlands. This is what I've concluded so far:

Location seems to be just based in GPS. Other apps that use the location services (by Google?) get an instant location fix that is accurate to about 10m and updates frequently.
Streetcomplete takes a while to get a fix, is moderately accurate and only updates about every 30 seconds. If other apps have established a GPS fix Streetcomplete seems to use it and also fix instantly.

The accuracy of Streetcomplete seems to match the accuracy from the GPS apps GPS Cockpit and GPSLogger. As comparison on what I expect I tested OSAnd and Tower Locator which update more frequent and show greater accuracy. All apps tested in the Fairphone 4 running alongside Streetcomplete to ensure equal conditions.

Besides the update frequency and accuracy, Streetcomplete doesn't follow the location: there is no blue line of the travel history nor an automatic map orientation based on the travel direction. But I assume this is an effect of the underlying issue about location accuracy.

I don't recall having this experience using the Fairphone in the Netherlands but I'm not entirely sure about the details of that experience. I can verify once I'm back to run the same tests in that environment.

I'd happily do some further analysis if there are some pointers how to.

I do understand mapping during car travel is not the most obvious use case and the 30s update frequency can be adequate for most users.

**How to Reproduce**

Run Streetcomplete on Fairphone 4 and experience the reduced location experience.

**Versions affected**

- Streetcomplete v43.2 via F-Droid
- Fairphone 4
- Android 11
- Google Play services update 1st of April 2022

**Comment by matkoniecz** [comment]
StreetComplete does not use the Google Location Services, so it is dependent on whatever the GPS sensor reports back to the app via the Android API for that.

https://github.com/streetcomplete/StreetComplete/issues/2664#issuecomment-800529502

**Comment by Helium314** [comment]
Some possible reason for the difference between StreetComplete and OsmAnd: StreetComplete requests location update interval of 2 seconds, while OsmAnd uses 0.
On my phone this has a considerable effect on accuracy if GPS signal is bad, so much that I use update interval 0 in my personal version of SC.

**Comment by nicorikken** [comment]
I had a GPS accuracy of 4m with GPS Cockpit and still Streetcomplete was only updating every 30s

**Comment by westnordost** [comment]
If the increased interval does not have a bad influence on battery life, I would accept a PR to change this interval to 0 (trusting your statement that it somewhat increases accuracy on some devices at least).

Otherwise, there is nothing we can do. The app does not use the Google Location Services but tries to select the best position from GPS, cell towers and wifis. Code is here: https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/util/location/FineLocationManager.kt

I am not sure how the thing with the wifis (can) work, I thought this particular feature ([WPS](https://en.wikipedia.org/wiki/Wi-Fi_positioning_system)) was exclusive to the Google Location Services, but [documentation claims otherwise](https://developer.android.com/reference/android/location/LocationManager#NETWORK_PROVIDER).
So, theoretically, the location should be as precise as with the Google Location Services.

What may be happening with the FairPhone is that this particular feature has been removed from their distribution because obviously the whole WPS stuff is Google proprietary.

**Comment by Helium314** [comment]
Some battery usage test with various GPS settings, ~2 hours each
* GPS off (only network location with interval 2 s): 11.5%/h
* GPS and network interval 2 s: 12.7%/h
* GPS interval 0 s, network interval 2 s: 12.6%/h
* GPS interval 0 s, network interval 15 s: 10.8%/h

So reducing the GPS interval to 0 appears to not have any impact on battery usage.
Interstingly, network location appears to have greater influence than GPS. Either it's the wifi / mobile tower scans, or the DejaVu backend I use does a lot of processing.

**Comment by Helium314** [comment]
Would it be ok to also reduce the network location interval? Or at least not setting it to 0 together with GPS?
Wifi scans needed for precise location take a ~3 seconds anyway, and for mobile tower scans high frequency isn't useful anyway due to the low precision.

**Comment by westnordost** [comment]
Sounds reasonable
