### ISSUE TITLE
Provide some explanation in overlay menu

### ISSUE THREAD

**Issue by matkoniecz** [streetcomplete/StreetComplete#4129]
Primary, not obvious function is that you can click on any object where this quest applies and it will raise a quest menu.

I that it is not obvious and there is space for that in overlay selection menu. Even if overlay count would grow it can be scrollable with one layer less displayed immediately.

Maybe

> It will show OpenStreetMap data and allow to edit all relevant objects, not limited to generated quests

?

![screen02](https://user-images.githubusercontent.com/899988/174298816-ebde8b3b-ca0b-4ec1-a825-970373ca0053.png)

**Comment by westnordost** [comment]
Well, it's for advanced users. If anything should be done in that regard, the first time selecting an overlay should trigger a short tutorial just like the first-startup tutorial that explains overlays. Such a tutorial would probably only make sense if there is some more information that could be conveyed. E.g. if there was a setting which lets you select how old an element needs to be that it is marked in the same color as if it hasn't been specified at all.

**Comment by westnordost** [comment]
Anyway, this ticket specifically I will close, because that dialog does simply not have enough space for a meaningful explanation. I.e. that selection dialog/screen would need to become full screen / be redesigned anyway.

**Comment by matkoniecz** [comment]
@westnordost Is user supposed to guess on its own how overlays work? Or find and read documentation?

Or is there plan to provide such info somewhere else?

**Comment by georg-d** [comment]
+1 for a short explanation _within_ overlay selection, e.g. in form of a question mark icon right of "overlay auswählen", clicking the icon opens explanation which could be just a few sentences. Like that, help is not consuming space for overlay list (hopefully satisfying westnordost) but is still always available in the very place you interact with when activating overlays. That is IMHO clearly superior to "appearance on first usage" e.g. if you did not memorize some detail, did not use the feature for a while, use a shared device,...

Why do I consider a help required? I was running into the issue #4162 in the sense I saw a pink street and knew that pink means "info is missing", I wanted to add lit information – but was unable to do so because I did not find a lit quest pin but only pins for smoothness etc. and even answering them did not bring up the lit quest. When I now looked at the github issues, I learned I need to click _the street_ instead _a pin._ So the app is IMHO not self-explaining enough for a user like me with 10k solved quests – maybe not an advanced user, but also no novice 😉
