### ISSUE TITLE
Same value of cycleway:left and cycleway:right

### ISSUE THREAD

**Issue by goneo62** [streetcomplete/StreetComplete#4133]
When answering the quest about cycle lanes, StreetComplete adds a distinct value for each side of the road. If the values are the same like in `cycleway:left=no cycleway:right=no`, it would be better to add `cycleway:both=no`. It is more concise, more readable, and it would not trigger an Osmose issue level 3 like [this one](https://osmose.openstreetmap.fr/en/issue/260c5d16-771c-864b-7032-6bbd9660d9e4). 

I think this issue is not only for cycle lanes but also for all elements with left and right values.

_In the Osmose summary for my account I have so many such warnings that I cannot find the other ones._

**Comment by matkoniecz** [comment]
https://www.openstreetmap.org/way/5881878/history

it may be related to presence of contraflow without dedicated lane, in general SC is trying to avoid this

**Comment by westnordost** [comment]
StreetComplete tags `cycleway:both=*` if the user selected the same answer in the UI for each side. E.g. if the user answers

left: cycle lane
right: cycle lane (dashed markings)

... then the selected answer in the UI is a different one for each side and thus it will also not tag `cycleway:both=lane` but each side separately.

This is not a bug, it's more of a missing optimization (of using as few tags as possible). Doing this optimization is not trivial, that's why I did not do it. A PR is welcome as long as it doesn't significantly make the code more complicated. The code is in `AddCycleway.kt`

**Comment by westnordost** [comment]
See also #3703 for a related discussion

**Comment by BalooUriza** [comment]
On Sat, Jun 18, 2022 at 10:35 AM goneo62 ***@***.***> wrote:

> When answering the quest about cycle lanes, StreetComplete adds a distinct
> value for each side of the road. If the values are the same like in cycleway:left=no
> cycleway:right=no, it would be better to add cycleway:both=no. It is more
> concise, more readable, and it would not trigger an Osmose issue level 3
> like this one
> <https://osmose.openstreetmap.fr/en/issue/260c5d16-771c-864b-7032-6bbd9660d9e4>
> .
>
I wouldn't sweat the L3 stuff too much.  It's always a good idea to map the
lanes for per-lane detail to clarify where exactly the restricted lane is.
