### ISSUE TITLE
Layers - separate colour scale for night mode?

### ISSUE THREAD

**Issue by matkoniecz** [streetcomplete/StreetComplete#4136]
I am not using night mode in general, but it seems to be not matching what is expected from night mode, right?
![screen03](https://user-images.githubusercontent.com/899988/174457037-0e4d0df6-ee4f-4be2-9077-9dec5cc821ac.png)

**Comment by westnordost** [comment]
Too much work for overlay creators.

Overall, overlays use the most flashy colors available. Both the light and dark mode maps should use colors with less saturation because they are supposed to be in the background. If colors of the background map conflict with overlay colors (and the overlay indeed uses flashy colors), then it is an issue of the background map style.
