### ISSUE TITLE
Mapping party competition mode

### ISSUE THREAD

**Issue by Asteliks** [streetcomplete/StreetComplete#4150]
**Use case**
Imagine you want to organize a mapping party. In it you want x teams of y people to go out and get as many StreetComplete stars as possible. Currently you would need to have everyone show you their phone and write down their current star count. Next you need to make sure everyone starts mapping at a certain time. Start the competition, let everyone map for a cretin amount of time. Finish the competition, count the stars while making sure no one is cheating.

**Proposed Solution**
There are probably several ways to add this feature but the way I see it is extending the current cooperation mode to take care of not only different teams but also score keeping among them.

I’m sure that this mode would bring much joy to several mapping parties!

**Comment by mnalis** [comment]
> Currently you would need to have everyone show you their phone and write down their current star count.

Not really. If you know their usernames, you can see in their changesets how many things they solved with StreetComplete in that time frame while mapping party was active, like http://hdyc.neis-one.org does for example. Such counting could be automated with a script.

However your next point:

> [...] while making sure no one is cheating.

... worries me **much more**. Gamification is all nice and fun and may promote honest mapping, but if it gets taken to far and leads to possibility of cheating, it is IMHO horrible idea and should be abandoned.

The miscounted stars are almost irrelevant there (cheating that is easy: "bad players" could just exit team mode and thus have more quests to solve than honest mappers, thus possibility for higher score), but if some of them are willing to cheat, there is much worse possibility that they might just answer invalid data to the quests in order to be faster and thus solve more quests. (hey, it's much faster to simply click any quest on the map and select the random answer, then to actually go there and verify it and find and enter correct answer).

So, even ignoring all the technical difficulties to properly define (much less implement) such gaming framework, I think there is a limit how far a gamification should be taken, and making it active competition against other "players" sounds to me like it crosses that limit.  

(see links in related https://github.com/streetcomplete/StreetComplete/issues/3706 for more information on problems with adding even more gamification)

**Comment by westnordost** [comment]
So, I'll close this.

However, there is a feature planned that could help for friendly competitions amongst friends: Also display the contributions made in the last week / last month. This way, oldbies introducing their friends to StreetComplete do also have a measure that doesn't massively put them in front of their buddies - i.e. they can compare how much they contributed the last week and what their rank there is.
