### ISSUE TITLE
Hidden quests are shown on the first download

### ISSUE THREAD

**Issue by deevroman** [streetcomplete/StreetComplete#4159]
**How to Reproduce**

1. Download quests in a new area
2. You can see the quests that are hidden.
3. Zoom in/out.
4. Hidden quests will disappear.

https://user-images.githubusercontent.com/25708359/175821519-3bc65519-20c5-4879-9be4-a074f9a46a3e.mp4

**Versions affected**
StreetComplete 45.0 beta1
Samsumg Galaxy A52. Android 12 OneUI 4.1

**Comment by westnordost** [comment]
Can you clarify, which quests are hidden and in what way? Did you hide the quest type? Which quest type did you hide?

**Comment by deevroman** [comment]
<img width="177" alt="Снимок экрана 2022-06-26 в 21 29 18" src="https://user-images.githubusercontent.com/25708359/175828889-dbdd8630-ce11-4dfc-b4ff-94e3c1a76e54.png">

For example, quests about the quality of the road surface and the sale of halal products. These quests are generally disabled by default. (using the default preset)

I can show it and reproduce it in a different way.
1. Create a preset from one quest.
2. Upload a new area.

https://user-images.githubusercontent.com/25708359/175829529-f24b19ea-1a0a-4dec-a285-b55c94ea4100.mp4

p.s. There really is no entrance in the new zone -- an industrial zone

**Comment by westnordost** [comment]
Okay, will look into it

**Comment by mnalis** [comment]
I can confirm that in `v45.0-beta1`

- I have a preset active with only one regular quest enabled (`memorial`; plus of course `notes` which one can't disable)
- initially on app opening only that `memorial` quest is shown
- I manually click on `Scan for quests here` button
- suddenly, tons of unselected quests are shown (bicycle parking, house type, smoothness...)

**Comment by RubenKelevra** [comment]
I can confirm this bug with the current beta 1:

https://photos.app.goo.gl/UnsTtD3cxMrpCQy38

**Comment by RubenKelevra** [comment]
Additional observation:

If there's an element which has more than one quest, like a bus stop, but only one is visible, like in my case a "lights at the bus stop" quest:

If the enabled quest is competed, the next quest will be shown, despite it beeing disabled.

Zooming does *not* hide it again, instead you need to go to the quest filter setting and do a enable/disable change like showed before to hide it again.

**Comment by Helium314** [comment]
I think the problem is located here: https://github.com/streetcomplete/StreetComplete/commit/e1790df970696e9cb3390743fc3db75d42b95b78

In this commit, quests provided by `osmQuestSource.getAllVisibleInBBox` are not checked for visibility, except for team mode filter, as (hence the name) they should only be visible.
But also in this commit also updated quests (when new quests were created, on solving quests or on download) are only checked using team mode filter, and not filtered whether the quest types are actually visible.
(Sorry, that change was done on my suggestion, though I meant to have it only in `getAllVisible`)

**Comment by westnordost** [comment]
yeah
