### ISSUE TITLE
parking:orientation on separately mapped areas

### ISSUE THREAD

**Issue by joshinils** [streetcomplete/StreetComplete#4163]
### General
Affected tag(s) to be modified/added: [parking:orientation](https://wiki.openstreetmap.org/wiki/Key:parking:orientation)
In which orientation may cars park here?

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/blob/master/QUEST_GUIDELINES.md)):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary
- [x] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of map data (Worth the effort)

### Ideas for implementation

**Element selection:** 
any area with amenity=parking and parking=street_side

**Comment by kmpoppe** [comment]
I'd be in favour of such a quest, yet the element selection should (at least for my understading) include such ways that have `parking=lane` or `parking:lane:*=*` so that areas where parking is not explictly tagged with it's own amenity get an orientation as well - this could then make it neccessary to have an UI like cycleways or footways where the left and right of the direction of travel of said way may have different values.

**Comment by joshinils** [comment]
> I'd be in favour of such a quest, yet the element selection should (at least for my understading) include such ways that have `parking=lane` or `parking:lane:*=*` so that areas where parking is not explictly tagged with it's own amenity get an orientation as well - this could then make it neccessary to have an UI like cycleways or footways where the left and right of the direction of travel of said way may have different values.

maybe, but over the span of a whole street this can change, and then the road needs to be split. 
while answering such a quest one may not be able to see the whole length of street it applies to and answer in error.

also, to be complete for this tagging on streets, there should be quests for:
* parking:lane:<side> = <type>
* parking:lane:<side>:<type> = <parking position>
* parking:condition 
  * disc
  * maxstay
  * fee
  * splitting way many times if it changes
* separately mapped already 
* taxi rank tagging, which I do not know of if it exists

for those reasons i excluded roads.
I think it be better those be represented in other quests, if possible.

the zlant parking lane editor (or a fork of it) is better suited than streetcomplete I think, since the tagging can be too complicated, and takes too much effort for a "simple" quest I think.

**Comment by kmpoppe** [comment]
I removed my commet because I didn't even gather that you wrote "seperately mapped"... I'll take a look at zlant, maybe the amount of different things you could tag along a road might really be unsuitable for SC.

**Comment by westnordost** [comment]
There is a quest already for `parking:lane=*` but it is not yet enabled. It will be enabled (or converted into an overlay probably) once @matkoniecz finished the `parking:condition` quest because it makes more sense if both go live at the same time. See https://github.com/streetcomplete/StreetComplete/issues/771#issuecomment-991773832

As this request is about tagging `parking:orientation` on areas with amenity=parking and parking=street_side:
1. This would be difficult to represent in the UI because an area doesn't have an orientation per se. It is not unlikely that users of this app would then actually answer this wrongly
2. How the cars park can usually be inferred from the "thickness" of the area. Also, if it is already mapped as an area, it is likely that the aerial imagery in that region is good enough that this information can be taken from aerial imagery.

**Comment by westnordost** [comment]
While a good image, such as the one created by Wieland in https://github.com/Helium314/SCEE/pull/497 solves my first concern and my claim that data consumers should easily be able to infer this is somewhat debatable, my concerns regarding

- usefulness of this data (i.e. for what purpose would this data be used?)
- and that it would be more efficient to ascertain the data from aerial imagery

still stand.
