### ISSUE TITLE
Bench quests should allow retagging as lounger

### ISSUE THREAD

**Issue by HolgerJeromin** [streetcomplete/StreetComplete#4167]
https://www.openstreetmap.org/note/3242327

https://wiki.openstreetmap.org/wiki/DE:Tag:amenity=lounger

**Comment by matkoniecz** [comment]
Loungers are rare enough that notes are likely fine here.

**Comment by cyclingcat** [comment]
At least for Germany this isn't valid - loungers are getting more and more popular here. Taginfo is of little use in this case as many of them are currently tagged simply as benches.

They sometimes stand in groups with ordinary benches (e.g. 3 benches, 1 lounger), so it would be helpful if
both bench and lounger nodes nearby were shown on the map in order to identify the objects correctly.

Maybe an additional option "This is a lounger" (similar to "picnic table") would be an idea for the backrest quest? And use the existence quest for benches to help refine the tagging if the object is in fact a lounger? 
 
The cycling cat

**Comment by matkoniecz** [comment]
Maybe I will look through opened notes. Which German names are used for loungers? [Sonnenliege and Liegestuhl](https://en.wikipedia.org/wiki/de:Sonnenliege)? Something else?

**Comment by cyclingcat** [comment]
"Liegebank"?

The cycling cat

**Comment by matkoniecz** [comment]
appears to be a rare case:

https://ent8r.github.io/NotesReview/?view=list&query=lounger&status=all
https://ent8r.github.io/NotesReview/?view=list&query=Liegebank&limit=100&status=all
https://ent8r.github.io/NotesReview/?view=list&query=Sonnenliege&status=all
https://ent8r.github.io/NotesReview/?view=list&query=Liegestuhl&status=all

effort to translate this text would be greater than to open notes with photos and process them

also, increased complexity and mistake rate would be not worth it
