### ISSUE TITLE
overlay : add parking_lane editing

### ISSUE THREAD

**Issue by JLZIMMERMANN** [streetcomplete/StreetComplete#4177]
**Use case**
There is a great editor for parking_lane tag [here](https://zlant.github.io/parking-lanes/#18/44.13594/4.80888).
![image](https://user-images.githubusercontent.com/4929752/176750285-ff1a7166-bd01-48f1-8da4-4fb98c2620bc.png)

**Proposed Solution**
The same as the overlay sidewalk for pedestrians an overlay would enhance a specific editing for cars.

**Comment by kmpoppe** [comment]
Related #4163

**Comment by tordans** [comment]
Just wanted to open the same ticket :-).

We are working on collecting parking data for all of Berlin with a local community. And we are working on processing the OSM data to generate good parking data based on it as well. All this is WIP and documented at https://parkraum.osm-verkehrswende.org/. We use a modified version of the Zlant parking editor for this (Links below).

Based on this project, I have some input for the quest / overlay:

- It need to **show separately mapped parking areas** of type lane and street_side (and possibly surface for those cases that are miss-tagged). Otherwise we will generate bad data by mapping the parking data twice. The zlant-Editor does that by showing the separately mapped areas on the map.
  - Examples: https://tordans.github.io/parking-lanes/#20/52.47398/13.44293, https://tordans.github.io/parking-lanes/#20/52.47438/13.44614, https://tordans.github.io/parking-lanes/#19/52.47696/13.44571
- Right now, our project is focussed on just collecting "if and in which direction can be parked", eg `parking:lane:left=parallel`. To keep it simple, I suggest to focus on this, so the **colors of the overlay could visualize "no `parking:lane:<side>` data" vs. "data present".**
  - Side note: In the future, it would be gerat to be able to run the same quest for other sub-data like the parking-position (eg `on_street`), a simple condition check and mappging the surface below the cars (Topic of "Entsiegelung" (unsealing?))
