### ISSUE TITLE
de.westnordost.streetcomplete.data.quest.VisibleQuestsSourceTest tests are failing

### ISSUE THREAD

**Issue by matkoniecz** [streetcomplete/StreetComplete#4182]
getAllVisible does not return those that are invisible in team mode
getAllVisible returns only quests of types that are visible

https://gist.github.com/matkoniecz/e26c29fad1d7ecca8b2109f5bdf8927a

spotted when investigating something unrelated

**Comment by Helium314** [comment]
`getAllVisible returns only quests of types that are visible` assumes `osmQuestSource.getAllVisibleInBBox` may return quests that are not visible. If this is the case, `getAllVisibleInBBox` would be _really_ bad name.
Anyway, it fails because the check whether a quest type returned by `osmQuestSource.getAllVisibleInBBox` is really visible was removed recently.

`getAllVisible does not return those that are invisible in team mode` fails because team mode filter is now only checked if team mode is actually enabled.

**Comment by westnordost** [comment]
I see you commented right when I wanted to investigate. Would you like to adapt the test?

**Comment by Helium314** [comment]
Fix for `getAllVisible does not return those that are invisible in team mode` is simple.

Not sure about `getAllVisible returns only quests of types that are visible`. If we trust `osmQuestSource.getAllVisibleInBBox` then the test doesn't really make sense...

**Comment by westnordost** [comment]
> Not sure about getAllVisible returns only quests of types that are visible. If we trust osmQuestSource.getAllVisibleInBBox then the test doesn't really make sense...

ok
