### ISSUE TITLE
Roof shape quest is not showing object type (building classification, address if available)

### ISSUE THREAD

**Issue by matkoniecz** [streetcomplete/StreetComplete#4194]
Building levels quest is showing this.

It would be useful for identifying buildings and detecting tagging mistakes

Reproduced with not modified v45

**Comment by legofahrrad** [comment]
![Screenshot_20220709-193604](https://user-images.githubusercontent.com/92865620/178117027-c0ab772e-8878-4742-a783-08cacc50e558.jpg)

I don't quite understand what you mean? The "house number 15: House"? It is shown below the title...

**Comment by matkoniecz** [comment]
At least for some it is not shown, say https://www.openstreetmap.org/way/291613117/history

Maybe it has weird building type not found in iD presets?

**Comment by mnalis** [comment]
I can confirm that on [that building](https://www.openstreetmap.org/way/291613117/history) it does show building details (in pristine upstream `45.0`):
![small_Screenshot_20220710_112219_de westnordost streetcomplete](https://user-images.githubusercontent.com/156656/178139200-bb640806-9f65-4cbb-826d-9f38731e9937.jpg)

That might indeed that be due to unrecognized [building=manufacture](https://wiki.openstreetmap.org/wiki/Tag:building=manufacture), as **iD** also does not seem to recognize that type (i.e. **iD** shows it as generic `key=value`, and not as translated building name, like in other cases):
![s_Screenshot 2022-07-10 at 11-26-51 OpenStreetMap](https://user-images.githubusercontent.com/156656/178139274-42edf3a2-d6ab-4e30-8590-f77d31ea16cd.png) ![s_Screenshot 2022-07-10 at 11-26-27 OpenStreetMap](https://user-images.githubusercontent.com/156656/178139273-8305ac5c-6419-4ede-afa6-2f06a3be5a41.png)

**Comment by matkoniecz** [comment]
Should SC show "Building" in such case? Probably no...

If anything - that seems omission in iD presets at most.

**Comment by matkoniecz** [comment]
I fixed it with https://github.com/openstreetmap/id-tagging-schema/pull/524 (new release of iD presets and updating presets in SC is needed before fix is deployed)
