### ISSUE TITLE
Allow setting default visibility for uploaded traces

### ISSUE THREAD

**Issue by Ajedi32** [streetcomplete/StreetComplete#4209]
Currently, all traces are uploaded as "Identifiable (shown in trace list as identifiable, ordered points with timestamps)". For privacy reasons I'd like to be able to set this to something a less specific.

Would also be nice to have an option to upload a trace without leaving a note, as having the points be anonymous doesn't help much if there's a public note associating you with the trace.

**Comment by mnalis** [comment]
Related:

- issue about private/local (i.e. not to be uploaded) notes: https://github.com/streetcomplete/StreetComplete/issues/1992
- See also `About` / `Privacy statement` in the app. Due to the nature of the surveying app like StreetComplete (and OpenStreetMap account itself) it will reveal where you (well, where _your account_) have been anyway. (while one may try to go to elaborate lengths to try to reduce that privacy information leak, it is **unavoidable**: see https://github.com/streetcomplete/StreetComplete/issues/3507#issuecomment-974546715 and related discussion)

**Comment by Ajedi32** [comment]
Good info, thanks.

Thankfully, OpenStreetMap already lets you contribute with nothing but an email address (which isn't even publicly visible) so it's already pretty easy to reduce the amount of information available to something like "an OSM contributor lives in this area" (though obtaining a truly anonymous email address is actually pretty hard these days, given the hoops mainstream services like Gmail and Outlook make you jump through to create an account).

My intention with this feature would be to push things a bit further, making it harder to reliably determine the exact house or even the exact block the contributor lives on, even if it might still be possible to guess the general area. #3507 would also be great for that, in my opinion.

**Comment by 10992-osm** [comment]
I obviously can't speak for how you or anyone else uses StreetComplete, but I think it unlikely that I'd ever make GPS tracks with StreetComplete near where I live, since local knowledge avoids the need, and I'm more able to go out and consciously do a survey with another GPS tool, rather than using SC because it's easily available.

[All of my traces](https://www.openstreetmap.org/user/10992/traces) are from SC, and none are near where I live.

However, I would say that it is generally good to offer more options.  I think the tracks should always be linked to notes from SC, and there is hence no point in making them anonymous.  I've not looked into the other privacy options, and whether they can help without disassociating a trace from a user.

As an aside, I do not (and before someone complains, will not start to) upload GPS traces I make near home, I load them into JOSM, add the track, and upload the changes, keeping the GPS trace for my own reference.

**Comment by westnordost** [comment]
See @mnalis and @10992-osm :  The traces for that particular feature (attach trace to note), the trace **must** be identifiable, because non-identifable traces are not linkable.
