### ISSUE TITLE
What type of fitness station is this?

### ISSUE THREAD

**Issue by arrival-spring** [streetcomplete/StreetComplete#4230]
### General
Affected tag(s) to be modified/added: [fitness_station](https://wiki.openstreetmap.org/wiki/Key:fitness_station)
Question asked: **What type of fitness station is this?**

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/blob/master/QUEST_GUIDELINES.md)):
- [x] 🚧 To be added tag is established and has a useful purpose
Wiki says that multiple types are allowed but this is barely used (at all), so that aspect may not count as established
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
In case of multiple different real world objects being mapped as a single OSM element then we would need to allow to select multiple options
- [x] 🐿️ Easily answerable by any pedestrian from the outside but a survey is necessary
Would need good pictures
- [x] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
- [ ] 🕓 Applies to a reasonable number of map data (Worth the effort)
Only around 37000 elements (nodes with `leisure=fitness_station` without `fitness_station=*`)

### Ideas for implementation

**Element selection:** 
`nodes with leisure=fitness_station and (fitness_station!=* or fitness_station=yes)`

Nodes only as areas are more likely to contain multiple objects

**Metadata needed:** 
Decide which types of fitness station are most common/worth including, the wiki lists quite a lot but maybe only pick the top 10 or so on taginfo?

**Proposed UI:**
Standard image selection, with multi-select enabled.

**Comment by peternewman** [comment]
I'm curious how you differentiate fitness pole and climbing pole, and also slightly concerned given they'd have very different physical loading and hence structural requirements!

> **Metadata needed:** Decide which types of fitness station are most common/worth including, the wiki lists quite a lot but maybe only pick the top 10 or so on taginfo?

Given you're tagging multi-select, and using the presence of !yes to imply it's been mapped, it will need to be made clear to leave a note if one of the present items isn't in our subset list, so it's not assumed to be missing.

Are you proposing to tag no for the ones which have been checked to not exist if more than one is selected?

Your proposed filter:

> nodes with leisure=fitness_station and (fitness_station!=* or fitness_station=yes)

Won't be sufficient to handle:

> Alternatively, if a fitness station has more than one type of equipment, some mappers add tags in the format fitness_station:<equipment_type>=yes to the [leisure](https://wiki.openstreetmap.org/wiki/Key:leisure)=[fitness_station](https://wiki.openstreetmap.org/wiki/Tag:leisure%3Dfitness_station) feature.

Only:

> Rarely a semi-colon value separator is used when there is more than one kind of equipment at the fitness station, with fitness_station=<equipment1>;<equipment2>;etc.

Although taginfo suggests the complete opposite...

**Comment by arrival-spring** [comment]
> Given you're tagging multi-select, and using the presence of !yes to imply it's been mapped, it will need to be made clear to leave a note if one of the present items isn't in our subset list, so it's not assumed to be missing.

Good point, yes. Although I'm not totally sold on whether multi-select is appropriate.

> Are you proposing to tag no for the ones which have been checked to not exist if more than one is selected?

I'm not sure I follow what you mean by that.

> Your proposed filter:
> 
> > nodes with leisure=fitness_station and (fitness_station!=* or fitness_station=yes)
> 
> Won't be sufficient to handle:
> 
> > Alternatively, if a fitness station has more than one type of equipment, some mappers add tags in the format fitness_station:<equipment_type>=yes to the [leisure](https://wiki.openstreetmap.org/wiki/Key:leisure)=[fitness_station](https://wiki.openstreetmap.org/wiki/Tag:leisure%3Dfitness_station) feature.
> 
> Only:
> 
> > Rarely a semi-colon value separator is used when there is more than one kind of equipment at the fitness station, with fitness_station=;;etc.
> 
> Although taginfo suggests the complete opposite...

Ah yes, would also need to exclude `fitness_station:*`

**Comment by peternewman** [comment]
> Good point, yes. Although I'm not totally sold on whether multi-select is appropriate.

Well I've personally mapped at least one node that's the whole fitness station with multiple bits of equipment, rather than doing an area. If multi-select wasn't going to be done (it already is for recycling for example), perhaps some rather vague filter where the quest only shows if there's another node within 50m or whatever (but might not be great for circuit training woodland path ones).

> > Are you proposing to tag no for the ones which have been checked to not exist if more than one is selected?
> 
> I'm not sure I follow what you mean by that.

If you were tagging with the single style, and I guess if someone selected more than one, implying it's not a station but a group of them, would you tag say as follows, given you know they don't exist:
```
fitness_station:ab_twist=yes
fitness_station:air_walker=no
fitness_station:back_massager=yes
```

I guess it's a bit irrelevant if semi-colon style is done, although personally I'm not really a fan of that style generally, partly as it breaks things like taginfo so spectacularly. We should also make sure we at least order them alphabetically or do something consistent if we're doing it that way.

**Comment by arrival-spring** [comment]
> If you were tagging with the single style, and I guess if someone selected more than one, implying it's not a station but a group of them, would you tag say as follows, given you know they don't exist:
> 
> ```
> fitness_station:ab_twist=yes
> fitness_station:air_walker=no
> fitness_station:back_massager=yes
> ```

I see what you mean now. It seems that no values are not used, so I wouldn't suggest to use that, as this clearly seems to be an exclusive tag, where any values with yes implies no to everything else.

Also, fitness_station:* seems much more used than semicolon as you say, so with multiselect I would go for that I think.

**Comment by peternewman** [comment]
> I see what you mean now. It seems that no values are not used, so I wouldn't suggest to use that, as this clearly seems to be an exclusive tag, where any values with yes implies no to everything else.

Fair enough.

> Also, fitness_station:* seems much more used than semicolon as you say, so with multiselect I would go for that I think.

It seems the opposite to me:
https://taginfo.openstreetmap.org.uk/tags/fitness_station=parallel_bars
versus:
https://taginfo.openstreetmap.org.uk/keys/fitness_station%3Aparallel_bars

Unless I'm missing something...?

**Comment by arrival-spring** [comment]
I meant in terms of when there are multiple pieces of apparatus in one `leisure=fitness_station`

Very few times has a semicolon been used, but I should think that most times the colon form is used it is because there are multiple objects present, e.g. https://taginfo.openstreetmap.org/keys/fitness_station%3Ahorizontal_bar#combinations

**Comment by mnalis** [comment]
> Well I've personally mapped at least one node that's the whole fitness station with multiple bits of equipment, rather than doing an area

When on the ground, **_I_** practically **_always_** just map whole group as a node (usually from OsmAnd or EveryDoor) - same as if I add a shop/cafe/amenity etc; I rarely if ever bother with areas. The reasoning being that the use of the map to me is primarily to _**find things**_ - everything else is mostly just visual fluff.

**Comment by westnordost** [comment]
Hm, after reading through this ticket and the wiki, I do not think this is eligible as a quest:

> 🚧 Established tags only + 🕓 Effort vs impact

The key is established alright, but the value is quite free-form, as there are many different kinds of fitness equipment around, even to the point where it gets hard to decide if a particular equipment is still a variation of type A or maybe an entirely different type. This makes it very hard to properly cover all the (popular) equipment. Just by remembering how a fitness station close to my place looks like, I can tell that many values are missing.
It may be less of a Sisyphus task to instead map which muscles are trained by the equipment because at least those are enumerable.

> **👨‍💻 Users are no experts**  + 🐿️ Easy answer

More importantly, due to the above, there'd be lots of answer options. But there is only a (tiny) picture to display how the fitness equipment looks like. And style varies a lot. Maybe with a different layout (like the building types), there is room for a short description. Still, it will be very hard or possibly impossible to make it so that the average user will know what to select with certainty - from a huge list of pictures of equipment that all look similar, to beat.

I think the more efficient way to map fitness stations is (by those who are interested in it) to make photos of the place, then look through the wiki at home to select the fitting stations and/or discuss how (showing the photo) a particular fitness station equipment should be named.
