### ISSUE TITLE
High priority notes

### ISSUE THREAD

**Issue by OpenGreenStreet** [streetcomplete/StreetComplete#4237]
**Use case**
I wish there were high priority notes.

**Proposed Solution**

For example: a road has been closed due to construction. This is important information from my point of view and who should be added to OSM as soon as possible.

PS: In my experience, a note can be processed very quickly but can also remain unprocessed for several months. (Maybe the construction work is already finished then).

https://www.ls.brandenburg.de/ls/de/pressemitteilung/ansicht/~11-07-2022-l-23-sanierung-der-ernst-thaelmann-strassa-in-strausberg-geht-in-die-naechste-runde#

**Comment by matkoniecz** [comment]
>  I wish there were high priority notes.

What you mean by that?

When making notes with SC - always attach photos to make them easier and more likely to remotely process.

You can use https://resultmaps.neis-one.org/osm-notes to review notes in you area (see say https://resultmaps.neis-one.org/osm-notes-country?c=Poland ) to review notes in a given country allowing to process remotely fixable.

You can also edit in place with Vespucci, without making a note.

You can also invite more people in OSM community to use this tools and make them aware, especially OSM note.

**Comment by RubenKelevra** [comment]
Priority of nodes needs upstream support from the OpenStreetMap project. Please let them know that you would like to have this feature - once implemented I'm sure that would be interesting to have integrated into StreetComplete as well.

**Comment by matkoniecz** [comment]
> Please let them know that you would like to have this feature

It does not really make sense to have ability to mark notes as urgent - it is additional complexity without actual benefit

**Comment by westnordost** [comment]
Closing because this is not a streetcomplete specific issue. Also, I do not think such a ticket would be accepted over at [openstreetmap-website](https://github.com/openstreetmap/openstreetmap-website), see @matkoniecz last comment.

**Comment by mnalis** [comment]
> PS: In my experience, a note can be processed very quickly but can also remain unprocessed for several months. (Maybe the construction work is already finished then).

- Perhaps, you should solve your notes as soon as you get back home, instead of leaving them unsolved for several months, expecting someone else to solve them (plug: you can find your own unsolved [notes](https://wiki.openstreetmap.org/wiki/Notes) easily on https://my-notes.osm-hr.org/)

- Additionally, you can start the text of the note with text `URGENT:` - violla, instant high-priority notes. But it is not really a good idea - who would want their notes to never be solved as there is always some more urgent ones?

- best solution @OpenGreenStreet : as noted by others, you can use general purpose [mobile editors](https://wiki.openstreetmap.org/wiki/Editors#Mobile) like [Vespucci](https://wiki.openstreetmap.org/wiki/Vespucci) (it's not _that_ hard to learn its basic features like tag editing!) to **immediately** mark road as [highway=construction](https://wiki.openstreetmap.org/wiki/Tag:highway=construction), preferably with [opening_date](https://wiki.openstreetmap.org/wiki/Key:opening_date) if known, and/or [fixme=*](https://wiki.openstreetmap.org/wiki/Key:fixme) with additional information

**Comment by OpenGreenStreet** [comment]
Thank you very much for the feedback. Sorry about that: my focus is on Wikipedia and I use StreetComplete almost only on the road.

**Comment by OpenGreenStreet** [comment]
see also: https://github.com/openstreetmap/openstreetmap-website/issues/3626#issuecomment-1198188601
