### ISSUE TITLE
Quest suggestion: "Is this location open at public holidays?"

### ISSUE THREAD

**Issue by dreirund** [streetcomplete/StreetComplete#4262]
### General

* Affected tag(s) to be modified/added: [opening_hours](https://wiki.openstreetmap.org/wiki/Key:opening_hours)
* Question asked: **Is this location open at public holidays?**
  - Possible answers:
    + "*No*": If the place is closed on public holidays, even if it would have open if the day would not be a public holiday,
    + "*Unaffected*": If public holiday does not change the opening of a place,
    + "*Especially*": If the place is open whenever there is a public holiday,
    + "*Other answers&hellip;*": Maybe similar as we have for the general Opening hours quest?: "*Differs by type of holiday&hellip;*", "*Open 24/7*", "*No regular opening hours*", "*No opening hours sign*", "*It does not exist&hellip;*", "*Can't say&hellip;*"

#### Rationale:
Many places with opening hours (like shops) miss information how public holidays are handled.

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/blob/master/QUEST_GUIDELINES.md)):
- [x] 🚧 To be added tag is established and has a useful purpose
- [?] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
  + Would add "`PH`"-subtag to "`opening_hours`".
- [x] 🐿️ Easily answerable by any pedestrian from the outside but a survey is necessary
- [?] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
  + The "street surface quality" also appears on almost every road I have in my surroundings, so if that quest is allowed, than this should be, too.
- [x] 🕓 Applies to a reasonable number of map data (Worth the effort)

#### Element selection:

* If [`opening_hours`](https://wiki.openstreetmap.org/wiki/Key:opening_hours) is present but it says nothing about public holidays (`PH` not present therein), the quest is asked.
* **Unclear to me:** Can an explicit `PH` specification be made in `opening hours` that basically says "public holiday does not influence opening hours"? -- since we must set `PH` to indicate that public holidays have taken into account.

**Comment by cyclingcat** [comment]
> *  Easily answerable by any pedestrian from the outside but a survey is necessary

Is this requirement for a new quest really fulfilled? I have solved many 100 opening hours quests so far (and tagged many opening hours via JOSM and OsmAnd), mostly in Germany, and have noticed that at least in my country the information if the values for "Sunday" includes "public holidays" or not is indicated very rarely. As useful as this information would be for data consumers, I fear that this quest wouldn't be answerable reliably without a lot of additional research (including asking the shop/restaurant operator or even checking on-site on public holidays).

The cycling cat

**Comment by Helium314** [comment]
It's not clear to me why this should be a separate quest.
Opening hours on public holidays can be added as part of the normal opening hours quest, and I would assume users are aready adding this information (if it is signed).

**Comment by matkoniecz** [comment]
Strictly speaking in OH quest you cannot answer that something is closed on public holidays.

**Comment by Helium314** [comment]
After adding at least some opening hours, you can add off days, and as part of this you can select public holidays... or do you mean something else?

**Comment by dreirund** [comment]
> It's not clear to me why this should be a separate quest.
> Opening hours on public holidays can be added as part of the normal
> opening hours quest, and I would assume users are aready adding this
> information (if it is signed).

Many supermarkets have only opening hours like Monday to Friday,
Saturday" added. Supermarkets and almost all other shops in Germany are
closed on public holidays (most of them by law). But that information is
mostly not added.

That was the use case for the quest, to add that mostly overseen bit of
information.

Since in the mind of people, it is clear that they are closed on public
holidays, even if it is a Wednesday where it normally has open.

No general shop in Germany writes on it's sign that it has closed on
public holidays, although it has.

**Comment by mnalis** [comment]
IMO assumptions heavily varies by country / region. In Croatia, that  assumption varies / depends a lot.

- sometimes, the shop will spell explicitly working hours for Sunday, and (separately or combined) for Public Holidays (yay!)
- sometimes, the shop will spell explicitly working hours only for Sunday, and you do not know situation about PH (It might be same as Sunday, or it might be off -- usually it will be off if amenity has same other off-day, like Mo or Tu, but that is pure guess so can't be entered without checking with owner, which I venture into only on few strategic rural places where there is no alternative for many miles around)
- regardless of the above, often shop here will work on most public holidays (sometimes having it signed, sometimes not - see above), but **not** on religious holidays which are also PH (e.g. they might work on Labour day, but not work on Christmas and Easter). And they might have shorter working hours a day before such religious holidays. What is worse, it might not be signed at all, or (usually) only signed a few days before such a day so it is mostly hopeless to add it in `opening_hours=*` (esp. as format does not allow for distinction RH/PH, and dates are not fixed but changed every year. [opening_hours:url](https://wiki.openstreetmap.org/wiki/Key:opening_hours:url)  is best hope there, provided shop has online presence, which most small ones do not)
- I especially hate it when they say "every day 11:00-22:00" (or just 11:00-22:00) as that "every day" might mean _**any**_ of "Mo-Fr", "Mo-Sa", "Mo-Su", "Mo-Su,PH"

`</rant>`

---

But I also think this quest is not needed, because:

- `opening hours` quest **_already allows_** specifying Public Holidays both as working (with separate or shared opening hours) or as a off-day, and `opening hours` quest gets resurvey intervals anyway.
- it fails _"🤔 Any answer the user can give must have an equivalent tagging"_ (e.g. `"Unaffected": If public holiday does not change the opening of a place` cannot be expressed in [opening_hours=*](https://wiki.openstreetmap.org/wiki/Key:opening_hours) syntax, only in rarely used freeform [opening_hours:description=*](https://wiki.openstreetmap.org/wiki/Key:opening_hours:description)  or [opening_hours:note=*](https://wiki.openstreetmap.org/wiki/Key:opening_hours:note))
- it also fails _"🐿️ Easily answerable by any pedestrian from the outside but a survey is necessary"_ (See rant above)

**Comment by matkoniecz** [comment]
> opening hours quest already allows specifying Public Holidays both as working (with separate or shared opening hours) or as a off-day

Can you specify PHs as an off day?

But otherwise I sadly agree :(

I would really like more quests, but like most of my own ideas: it is not viable :(

**Comment by mnalis** [comment]
> Can you specify PHs as an off day? I think that you cannot do this in SC.

Yes you can (Both for off days, and as a working day, you can select Mo-Su **and** PH in StreetComplete)

**Comment by BalooUriza** [comment]
Would be interesting if this could appear only near public holidays when
this is likely to be signed.
