### ISSUE TITLE
Add "chipseal" as road surface type

### ISSUE THREAD

**Issue by MrConorAE** [streetcomplete/StreetComplete#4265]
**Use case**

Chipseal is a common and inexpensive road seal, used heavily in Oceania. It's currently not an option in StreetComplete, which is leading to some confusion, including causing amateurs (like me!) to incorrectly mark it as "asphalt" when it technically isn't.

**Proposed Solution**

Add "chipseal" as an option for road surface, alongside asphalt, concrete, etc.

The OSM key/value for this is `surface=chipseal`.

**Comment by matkoniecz** [comment]
I documented it some time ago at https://wiki.openstreetmap.org/wiki/Tag:surface%3Dchipseal and discussed at https://lists.openstreetmap.org/pipermail/talk-us/2021-January/020826.html

Reaction was quite mixed on whether it is a distinct value that should be tagged separately from `surface=asphalt` - so I have not pursued it further.

It is used really rarely compared to other values.

Not sure what should be done here and how. Propose that you start a new thread at [tagging mailing list](https://lists.openstreetmap.org/listinfo/tagging) and ask people for opinions? Do something else?

Main questions are

- should it be considered as distinct from `surface=asphalt`?
- should it be encouraged to be used?
- would it be preferable to use some other tagging? Maybe `surface=asphalt` `asphalt=chipseal`?
- is OSM community tagging opinion supporting use of this tag?
- is it popular enough to be worth supporting (probably yes?)
- do we have a photo making distinction from both asphalt and fine gravel quite clear?

**Comment by matkoniecz** [comment]
I forgot about the most obvious way to promote this tag: just use it in your mapping. You can switch to Vespucci and surface there if you encounter it.

This tag is so rare that single mapper can add 10%-20% more objects. Right now even `surface=cement` (mistagging of `surface=concrete` is used more often), and its usage as part of all surface values is dropping.

You can also try to track down who was retagging `surface=chipseal` - see https://taginfo.openstreetmap.org/tags/surface%3Dchipseal#chronology (38% was retagged so one may look at 2020 data and look through history of objects - but maybe this edits were reverted and that is why there is so huge jump)

https://wiki.openstreetmap.org/wiki/Proposal_process is another option, but people may vote against.

Overall, I think that given lack of consensus to support it, decreasing and tiny usage, treating it as `surface=asphalt` not being obviously wrong  - I would not add it. But if any of that changes...

**Comment by matkoniecz** [comment]
Looking at https://taginfo.openstreetmap.org/keys/surface#chronology https://taginfo.openstreetmap.org/tags/surface%3Dchipseal#chronology again - this would require some clear support from community, like `surface=unhewn_cobblestone` (new previously unused surface tag value promoted by StreetComplete had)

![screen21](https://user-images.githubusercontent.com/899988/182677459-834e87d4-6dd6-42f6-b14e-75fbfd094471.png)
![screen20](https://user-images.githubusercontent.com/899988/182677468-1e26a273-fb57-4ab4-a5f8-6e9216893d49.png)

**Comment by ravenfeld** [comment]
Maybe we should reopen the subject? 
it's being used more and more by too few people in my opinion, but it's a great help to cycle routers, especially for those who only want to ride road bikes on roads with good performance. It doesn't change the use of smoothness in any way

**Comment by ravenfeld** [comment]
In France, I was told that if it's in the wiki, use it ;) That the lack of use is more to do with ignorance. But maybe it's because we know the difference between asphalt and chipseal. At the moment, for reasons of cost, local authorities often do this.

**Comment by mnalis** [comment]
It does seem that `surface=chipseal` had a constant and sharp uptake in those 2 years (since 2022): https://taginfo.openstreetmap.org/tags/surface=chipseal#chronology

**Comment by mnalis** [comment]
That being said, its [3737 uses worldwide](https://taginfo.openstreetmap.org/keys/surface#values)  are still only about 0.006% of surface values, and SC does not offer to tag directly even more popular values which get similar or worse treatment (like `stone` at 11845 uses, `soil`, `brick`, `acrylic`, etc.)

But more than that, given that the StreetComplete does in fact [specifically detect existing](https://github.com/streetcomplete/StreetComplete/blob/05ef7ce4564e8eba42220ae02e38f87f0e7b6aa5/app/src/main/java/de/westnordost/streetcomplete/osm/surface/Surface.kt#L39) `chipseal` surfaces, I would guess the main issue might be failing those [Quest Guidelines](https://github.com/streetcomplete/StreetComplete/blob/master/QUEST_GUIDELINES.md): 

- 👨‍💻 Users are no experts: No knowledge about OpenStreetMap or any other background knowledge must be necessary
- 🐿️ Easy answer: Users are out and about and impatient. A quick, straightforward and clear answer must be possible

As mentioned in those tagging discussions, it's hard  to say if something is old asphalt surface, or old chipseal surface as they (supposedly) both might look and feel (e.g. when driving the bicycle over them) the same (as opposed when they are both new when they differ significantly more). 
Also, in countries which lack those and people are unfamiliar with the term, it would bring much more confusion than the issues it would solve. Not to mention translation issues - how to translate something that doesn't even have a name in your language?

Possible workarounds might be:
- if you care about that specific tag a lot, leave  a note instead of answering directly (might not work well if your country has huge number of those, as it will produce extra work)
- if you are not married to that specific `chipseal` value, marking it as `surface=asphalt` and then giving lower `smoothness=*` (in [Surface quality](https://wiki.openstreetmap.org/wiki/StreetComplete/Quests#smoothness) quest) might be good enough approximation (and also much more likely to be actually supported by other data consumers)
- I see you've already found third possible alternative (suggesting to https://github.com/Helium314/SCEE/issues/561)
- maybe the maintainer will change his mind as the key gets more uses :man_shrugging:

**Comment by mnalis** [comment]
> It also seems that ratio of surface=chipseal to surface=asphalt is growing.

That seems to be correct; some data:

- in July 2022, ratio of chipseal/asphalt was about 1600/20000000 = .00008
- in July 2024 it's 3737/27859641 = .000134

**Comment by ravenfeld** [comment]
> > It also seems that ratio of surface=chipseal to surface=asphalt is growing.
> 
> That seems to be correct; some data:
> 
> * in July 2022, ratio of chipseal/asphalt was about 1600/20000000 = .00008
> * in July 2024 it's 3737/27859641 = .000134

The ratio would have to be 0, which would mean that local authorities would invest money in better roads ;)

**Comment by mnalis** [comment]
> The ratio would have to be 0, which would mean that local authorities would invest money in better roads ;)

Be careful what you wish for, though. There is even cheaper "solution" for municipality to handle asphalt roads which have fallen into disrepair - just completely ignore the problem :open_mouth:. 

But let's try to keep the topic of this **StreetComplete GitHub issue** to what can be done specifically ***in StreetComplete*** about the issue, and provide data which might be useful to making a decision for SC. For more general issues still related to OSM, there is https://community.openstreetmap.org/, and for even more down-to-the-core-issue, help organizing letter writing to your municipality, or organizing legal protests or something. Feel free to link to relevant discussion elsewhere if you find/start them.

**Comment by matkoniecz** [comment]
I put "blocked" as I am not huge fan of establishing new `surface` values through any editor, including StreetComplete, without clear support from community. This can be confirmed by discussion at official forums where people agree that this value should be treated like regular `surface` value and promoted/supported. Or at least they do not protest.

And wiki page is hardly independent confirmation as I am one who documented this tag as valid value, see https://wiki.openstreetmap.org/w/index.php?title=Tag:surface%3Dchipseal&diff=2097594&oldid=1388275

(for `soil` - AFAIK it is supported as `dirt` duplicate)
