### ISSUE TITLE
Streetlight and bike lane quest selection error 

### ISSUE THREAD

**Issue by zyphlar** [streetcomplete/StreetComplete#4279]
When trying to complete quests lately, I'll see a street light quest ("is this way lit here?") and press it, but instead a quest asking about the lanes or curbs or bike lanes pops up instead.

**How to Reproduce**

- Run v45.2
- Complete quests in an area with unknown street lamp quality
- Press on a street lamp icon
- Notice that sometimes, especially if you're in motion, another quest appears instead
- Oddly, no additional quest appears after finally re-pressing the lamp quest.
- If you have trouble reproducing, try working on the West coast of the USA with the sidewalk overlay active.

**Expected Behavior**
- Pressing a quest marker always opens the quest associated with that marker

**Versions affected**
45.2

**Comment by zyphlar** [comment]
Correction it appears that the behavior of sidewalk overlays is that pressing any road will allow you to edit that road's sidewalk details. However when moving it's easy to mis-press or have the press registered as on the road when it was in fact on a quest marker. That seems to be the problem.

**Comment by westnordost** [comment]
Understandable. Mis-tapping happens when buttons are too close to each other (or too small individually). However, I don't really see how this can be solved. If this happens frequently enough for you that it is really disruptive, you should either turn off the overlay or disable the other quests (like "is this way lit here?")
