### ISSUE TITLE
Add "is there a building?" quest based on RapiD

### ISSUE THREAD

**Issue by kristbaum** [streetcomplete/StreetComplete#4290]
Would it be possible to add a "is there a building?" quest, using the suggestions created by [RapiD](https://github.com/facebookincubator/RapiD)? 
It would be a simple yes/no quest, and would allow to map in areas with a lot of missing buildings, without compromising on comfort, and without adding a full vector editor system.
I'm not sure how to get the generated suggestions from RapiD, but I could look into it further if there is any interest.

**Comment by westnordost** [comment]
I'd say no, because:

> 💵 Valuable Surveyors: Surveyor time is valuable, they shouldn't be asked to complete data that does not require a survey and can more efficiently be done remotely.

The building outline is generated automatically from aerial imagery. It is quite impossible to confirm even the rough outline of a building without also looking at it from an aerial perspective. Also, it is more effective and efficient anyway to add buildings from the desktop editor. Often enough, there may be a building, but the outline would need to be adjusted (slightly), merged to the neighboring building, aligned with the road, actual building and garage/shed separated etc, this is all awkward on the phone and anyway not possible with StreetComplete.

**Comment by kristbaum** [comment]
That's a valid point, thanks for considering it anyway!
And thanks for a great and valuable project!
