### ISSUE TITLE
Broken link in created note (internal ID?)

### ISSUE THREAD

**Issue by Discostu36** [streetcomplete/StreetComplete#4309]
StreetComplete created a broken link in a [note](https://www.openstreetmap.org/note/3328360):

 > Unable to answer "What surface does this piece of road have?" for https://osm.org/way/-27 via StreetComplete 45.2:

I guess that the road has been split in the app, but not uploaded yet, so an internal ID has been added to the link.

**How to Reproduce**
I'm not sure. 

**Expected Behavior**
The app should only add working links with online IDs to notes.

**Versions affected**
StreetComplete 45.2 (according to note)

**Comment by westnordost** [comment]
Oh, haha, okay. Yeah, that's a bug.

**Comment by Discostu36** [comment]
The user who created the note tells me he had auto upload off, but I don't know if this is part of the problem.

**Comment by westnordost** [comment]
The problem is that the element ID is written into the note text at note creation. When the `ElementEditsUploader` uploads an edit (e.g. splitting of a way), any ID updates returned by the OSM API are only communicated to the `ElementEditsController` and the `MapDataController` but not the `NoteEditsController`. So, a solution would need to 
1. either edit the database schema to defer constructing the note text until just before upload(?) and safe the element id it referred to in a separate column OR on every element id update, regex search through the text of every note edit and replace the id if found. The latter solution may sound dirty, but may actually be the more straightforward solution - after all, there are not thousands of note edits in the local db (and even that would not take long to regex-search through)
2. pass the ID updates after upload to the `NoteEditsController`
