### ISSUE TITLE
Street overlay houses in sidewalk overlay

### ISSUE THREAD

**Issue by tiptoptom** [streetcomplete/StreetComplete#4310]
I hope I am in the right place with this. This happens in the 45.2 version.
![grafik](https://user-images.githubusercontent.com/73886169/186524327-c36bf14a-9483-40e2-894a-5e2da0a88ace.png)

**Comment by westnordost** [comment]
This is actually kind of deliberate. After all, they are called overlays. While it may look weird sometimes, I think the alternative, that the highlighted data is not visible due to the buildings, is less desirable.#

However, it is inconsistent that the left/right strokes (the pink one in your screenshot) are behind buildings, but the other lines are in front.

**Comment by tiptoptom** [comment]
Yes, obviously the overlay is at the bottom and the roads overlay everything. But I would find the nicest solution if the overlays for lighting and sidewalks, which both relate to the road, were also on one level with the road.

**Comment by tiptoptom** [comment]
Maybe, the houses could be transparent, when the overlay is active?

**Comment by westnordost** [comment]
I wasn't able to have the overlay stuff appear behind buildings as that would cause other render artifact we do not want to have (not sure if trangram bug or intended render behavior). But in any case, what I did was to at least make it consistent: Both the left/right line (for sidewalk) and separate lines are all rendered above buildings now.
