### ISSUE TITLE
add shoulder overlay

### ISSUE THREAD

**Issue by legofahrrad** [streetcomplete/StreetComplete#4340]
**Use case**
Shoulder overlay should be easy to create, it can use the same design as the sidewalk overlay with the same colours
* green = shoulder
* grey = no shoulder
* red = information missing

**Proposed Solution**
same as for the sidewalk overlay with the colours on the left/right side of the road

I guess it would be useful to allow tagging of motorways and motorway links.

**Comment by westnordost** [comment]
Hmm, shoulders and parking lanes are usually mutually exclusive, so maybe I could put this also in the parking overlay. (Sometimes it is also very difficult to say if something is supposed to be a shoulder or a parking lane.)

On the other hand, a `shoulder=yes` in OSM can also denote a soft shoulder, i.e. just a white line, some centimeters of pavement behind that and then just some compacted surface. So maybe this is orthogonal to whether there are parking lanes or not since the presence of a shoulder may mean that cars park on the paved area but also may mean that they park half off the roadway.

**Comment by westnordost** [comment]
So anyway, a shoulder overlay is not planned, mostly because
- mostly irrelevant within a town and usually mutually exclusive to parking lanes / cycle lanes
- the shoulder tag's definition is relatively poor because it is interpreted too widely. Tagging `shoulder` alone is not too useful but at the same time, no proper tagging scheme exists that would cover the important aspects (whether it is a hard shoulder or not, if not, width of the paved part of the shoulder; width of the unpaved part of the shoulder, etc.)

**Comment by matkoniecz** [comment]
@westnordost Maybe there could be a list made somewhere (in discussion? in file in repo?) listing OSM tagging schemes which were discovered to be tragically flawed?

**Comment by mnalis** [comment]
Perhaps _tragically flawed_ OSM tagging schemes might be mentioned on the OSM wiki pages for that tag, as that is useful information outside of SC. Depending of **how much** tragically flawed they are, OSM wiki for such tags might perhaps even be marked with `{{Ambox|type=caution}}, or just mentioning usability issues at their `Talk:` pages.

**Comment by matkoniecz** [comment]
I added note to https://wiki.openstreetmap.org/wiki/Key:shoulder#History and posted https://community.openstreetmap.org/t/shoulder-tag-is-confusing/5185
