### ISSUE TITLE
Add overlay to add fire hydrants

### ISSUE THREAD

**Issue by riQQ** [streetcomplete/StreetComplete#4343]
### General
Affected tag(s) to be modified/added: [`emergency=fire_hydrant`](https://wiki.openstreetmap.org/wiki/Tag:emergency%3Dfire_hydrant)
Add fire hydrant and show existing fire hydrants in overlay to avoid duplication.

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/blob/master/QUEST_GUIDELINES.md)):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] ~~🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)~~
  -> doesn't apply to this kind of overlay
- [x] 🐿️ Easily answerable by any pedestrian from the outside but a survey is necessary
  -> aerial imagery is too bad in most cases and in some countries, e.g. Germany, there are signs that hint at the position of underground fire hydrants
- [x] ~~💤 Not an overwhelming percentage of quests have the same answer (No spam)~~
  -> doesn't apply to this kind of overlay
- [x] 🕓 Applies to a reasonable number of map data (Worth the effort)

### Overlay guidelines
- [ ] 🕸️ **Contextual only**: Overlays should only be used to display data that only makes sense in relation to neighbouring data, e.g. data in a network (such as cycleways, speed limits, ...) or data that depends (to a degree) how surrounding data is tagged (such as road smoothness, lit status, ...).
-> not exactly sure if this criterion is fulfilled. At least adding new fire hydrants requires the context of showing already existing fire hydrants in order to not duplicate data.
- [x] 🔎 **One aspect**: Similar to the atomic quests guideline, only one aspect should be displayed and be editable to the user.
- [x] ⭐ **Not a quest**: Usually eligible data should *either* be recorded and displayed in an overlay *or* as a quest.

### Ideas for implementation

**Element selection:** 
Existing hydrants: nodes with `emergency=fire_hydrant`

**Metadata needed:** 
Same as for quests about hydrants?

**Proposed UI:**
Show existing hydrants as overlay icons.
Bonus: different icons for different types of hydrants.

**Comment by westnordost** [comment]
> not exactly sure if this criterion is fulfilled. At least adding new fire hydrants requires the context of showing already existing fire hydrants in order to not duplicate data.

Not sure man. You could basically say this for every kind of POI. Is it not possible to add this data with every door?

**Comment by riQQ** [comment]
Sure, other editors can be used for this. Every Door is missing a focused mode as of now (Zverik/every_door#406) but it looks like it's planned to be added in the future.
MapComplete would also be an option, although it's a web app and not a native app. 

So I guess this is a matter of how you want to scope the overlay feature. I can totally understand if this is deemed to be out of scope for StreetComplete.

**Comment by westnordost** [comment]
Every door is a native app.

**Comment by riQQ** [comment]
I never said that it wasn't. I only said that **MapComplete** is not a native app.

**Comment by westnordost** [comment]
Oh, ok

**Comment by westnordost** [comment]
Anyway, I think I'll reject that for now. Overlays should really serve one really narrow purpose and I am not sure whether StreetComplete's overlays should be broadened to serve such thematic editing (fire hydrants, trees, bicycle parkings, ....) too. This is a use case that Every Door may be ideal to fill later on.

**Comment by peternewman** [comment]
> Not sure man. You could basically say this for every kind of POI.

I was going to suggest something similar but a bit broader, probably called street furniture or similar, including things like postboxes, benches, fire hydrants, defibrilators etc. Basically the shop overlay, but you pick an item of street furniture instead of a shop type (so where the presets have it, you could even pick a BT phone box for example). Like shops, suitable icons will already exist.

> Anyway, I think I'll reject that for now. Overlays should really serve one really narrow purpose and I am not sure whether StreetComplete's overlays should be broadened to serve such thematic editing (fire hydrants, trees, bicycle parkings, ....) too.

Do you feel something a bit broader like street furniture is still unsuitable @westnordost ?

> This is a use case that Every Door may be ideal to fill later on.

Having had a bit of a quick look at the screenshots, that app seems to often fall back as many other editors do to giving you lots of flexibility but expecting you to know the tagging to some extent.

My thinking was that the shop overlay is very user-friendly point and shoot style, and enables a load of future new quests which are by design also user-friendly and simple (e.g. seating, opening hours, card, diet etc). This seems to have lots of parallels to adding a post box based on it's location and then getting a load of quick and easy questions about it's collection times and ref etc. It also avoids overwhelming people by making them feel they need to add 20 bits of data rather than just get the object on the map and they or someone else can fill in the finer details.

To avoid making it too broad I'd suggest it only let you add nodes of things where SC asks a quest about the node.

I also possibly somewhat naively assumed that adding such an overlay would mostly just be a case of coming up with the filter now the shop code exists, so it's also a strong benefit for minimal effort.

**Comment by mnalis** [comment]
> I was going to suggest something similar but a bit broader, probably called street furniture or similar, including things like postboxes, benches, fire hydrants, defibrilators

Yeah, if such overlay were to be implemented, I'd also like for it to be generic (so one can add/modify all those features) instead of being specific to one little feature (like fire hydrants only)... But (surprisingly for me) I'm not set on StreetComplete re-implementing every bit of EveryDoor. Especially for such micromapping tasks, I think EveryDoor is actually the better choice.

I do think SC overlays **for nodes** are inferior to EveryDoor approach (see below for details)

>>    This is a use case that Every Door may be ideal to fill later on.

> Having had a bit of a quick look at the screenshots, that app seems to often fall back as many other editors do to giving you lots of flexibility but expecting you to know the tagging to some extent.

Um, not really. It does not expect that you know the tagging. EveryDoor has `amenities mode` which works akin to StreetComplete `Shops overlay`, and it has `POI mode` (which would be akin  to this proposed `Street furniture overlay`). But it works similarly to SC, by using `iD presets` to show the **_newbie-friendly human-readable iD name of the feature_** to user.
