### ISSUE TITLE
Remove `concrete:plates`

### ISSUE THREAD

**Issue by EvanCarroll** [streetcomplete/StreetComplete#4344]
It just occurred to me that I've been using this wrong the whole time, and the the picture was guiding me the wrong direction. I think it's better to remove this. It can be very hard to tell for people who haven't researched this whether or not a concrete "plate" was fabricated off site, or was poured on site as a panel (and is thus just `concrete`). It's also impossible to know whether or not they're held together by chains on the underside, or rebar in the pour.

It's not enough to assume that "regular gaps in between" make `concrete`, `concrete:plates` and even very experienced users are getting this wrong.

See this for more information

https://help.openstreetmap.org/questions/85524/concrete-vs-concrete-plates

The fact that this kind of question exists tells me the difference is probably not worth having in SC.

**Comment by TS-R** [comment]
I think simply removing concrete:plates will also result in wrong tagging. Removing concrete:plates will lead tagging those ways as concrete.
Maybe the tagging could be validated with smoothness tagging, similar to the track grade.

**Comment by matkoniecz** [comment]
I am not convinced that

> concrete poured on site with "regular gaps in between" as concrete:plates is wrong

But overall tag documentation on wiki would benefit from significant improvements

**Comment by mnalis** [comment]
> held together by chains on the underside, or [...]

I think you misunderstood that English idiom _"chained together"_ from wiki _"Heavy-duty plates **chained closely together**, might have tar or sand in between the connections."_

What is meant is  e.g. [definition 2 from merriam webster](https://www.merriam-webster.com/thesaurus/chained): ":

> to put or bring together so as to form a new and longer whole
>  "the prosecutor meticulously and brilliantly chained all the evidence together in his closing argument"

So, it is **not** important where the blocks themselves were produced, or using which method, or what are their foundations (as those would indeed be impossible to anyone who is not an engineer involved in that road project to even guess at!). 

What is important is:

- is it **one monolithic piece** of concrete **_without_** interruptions/breaks (resulting in smooth driving over it) which is what [this picture](https://wiki.openstreetmap.org/wiki/File:Concrete_sidewalk_construction.jpg) would result in when dried - in which case it is [surface=concrete](https://wiki.openstreetmap.org/wiki/Tag:surface%3Dconcrete), or
- is it **many separate slabs** of concrete with interruptions, so when you drive over it you make "thump - thump - thump" sounds each time you encounter the break between the slabs - in which case it is [surface=concrete:plates](https://wiki.openstreetmap.org/wiki/Tag:surface%3Dconcrete:plates)

But as you note @EvanCarroll, wiki could certainly use an improvement there. Please, feel free to do so! (as it confused you, you are the best suited person to explain it in a better and more understandable way! Your help would be much appreciated!)

**Comment by EvanCarroll** [comment]
@matkoniecz then the wiki needs to be updated because the link from concrete to `conrete:plates` specifically calls for "pre-fabricated".

@TS-R that would **NOT** make it incorrect, because there seems to nothing about `concrete` that would _exclude_ `concrete:plates`. As documented `concrete:plates` are merely a subset that places additional constraints on the method of construction (pre-fabricated plates linked together).

If you had though and you didn't know if it was poured on a site or not, and you didn't know if the plates were chained together or unlinked you'd tag `concrete`.

**Comment by EvanCarroll** [comment]
> But as you note @EvanCarroll, wiki could certainly use an improvement there. Please, feel free to do so! (as it confused you, you are the best suited person to explain it in a better and more understandable way! Your help would be much appreciated!)

I'm still not the person to do so even with your explanation that "chained together" can be metaphorical because "concrete:plates" are documented as pre-fabricated, so I'm still unconvinced "thump thump" when you're driving is sufficient to tag something as a `concrete:plate`.

**Comment by TS-R** [comment]
I think using concrete instead of concrete plates is wrong IMHO as it suggests in general a smooth surface without gaps where concrete:plates let the data consumer (router) expect an unsmoother surface which could be optimized by an alternate route.

@EvanCarroll You quote was not complete. The complete text from wiki: `For pre-fabricated plates, please use concrete:plates or concrete:lanes if you know how the concrete is laid out and one of these tags fits.`

I think the example pictures in wiki are also clear.

**Comment by mnalis** [comment]
> so I'm still unconvinced "thump thump" when you're driving is sufficient

Well, that's how **_I've_** been tagging it all along. And I'm certain I'm not the only one (see the other answers on your linked https://help.openstreetmap.org/questions/85524/concrete-vs-concrete-plates). So, one would just have to accept when they see `surface=concrete:plate` that this is _**one**_ of the possible meanings of that tag.

If you **generally feel** that the tag is poorly defined and/or **should not be used** (which seems to be the case), StreetComplete issue tracker is **not** a place to do it. Preferred way is to discuss it at [Tagging mailing list](https://wiki.openstreetmap.org/wiki/Tagging_mailing_list), and also mentioning that you initiated discussion there on `Discussion` page of that specific tag wiki (to invite people following that tag to the discussion). After the consensus has been reached on Tagging mailing list, by all means come back here and mention it to us, so we can take appropriate steps if needed.
Also note that in OSM, once a initially poorly defined tag is used out in the wild, there is no way to put that cat back in the bag. Best one could hope for is to discuss (at length!) and then [propose](https://wiki.openstreetmap.org/wiki/Proposal_process) new&better defined tag, and hope people will start using that instead of the old tag (which would remain unclear/ambiguous forever after). 



However, if you had some claim that having both `concrete:plate` and `concrete` is **great idea elsewhere**, but it is some specific part of **SC implementation** that makes it problematic (e.g. bad pictures, unclear translation, etc) that might indeed be useful in [SC issue tracker](https://github.com/streetcomplete/StreetComplete/issues).

Regarding SC itself, there are reasons why `concrete:plate` was added to StreetComplete after it had just `concrete` for some time (see https://github.com/streetcomplete/StreetComplete/issues/2437, https://github.com/streetcomplete/StreetComplete/issues/3468 and  https://github.com/streetcomplete/StreetComplete/pull/3354 for details).

**Comment by EvanCarroll** [comment]
How does the full quote change anything?

> For pre-fabricated plates, please use concrete:plates or concrete:lanes if you know how the concrete is laid out and one of these tags fits.

IE., If they're not pre-fabricated and if you do not know how the concrete is laid out you should not use use `concrete:plates`?

But yes, I should post to the tagging list. I'll get that done for now.

**Comment by mnalis** [comment]
> But yes, I should post to the tagging list. I'll get that done for now.

Thanks, please link the discussion here (and the wiki discussion pages) when you do, so interested parties can followup!

**Comment by TS-R** [comment]
I understand your concerns. I think if they are not pre-fabricated then in almost every case concrete:plates is not correct. I think even all non pre-fabricated concrete surfaces in good condition will have no recognisable gaps while driving over it and are like an even surface. And in this case there also will be no gras, sand or something between the segments.

And correct. I anybody is unsure what the correct tagging is it's best practice to skip this quest so it could be done by any one else or discuss this issue. So thank you for bringing this up to the mailinglist. I hope this helps to make this issue more clear for the future and for any possibly necessary changes in editors.

**Comment by RubenKelevra** [comment]
I don't think we can observe on site if concrete plates are prefabricated or cast on site.

But you can observe if its one continous surface with just small indentations, to let the surface crack there. Or if there are actual gaps in between the plates and they are just placed together. 

If unsure I use concrete, as concrete:plates is a "subcategory". 

Not sure however if that distinction is actually **that** important.

Maybe we could use just "concrete" in the list. If the user sends it, we could have a popup with both options with detailed pictures of the transitions with the notice 'if unsure use concrete'. 

---

Just to add my point of view on what I would tag:

![Foto02-B250.jpg](https://user-images.githubusercontent.com/614929/200263575-789e4c2c-9b14-4171-af3e-30d36bff967b.jpg)
**paving stones**


![raiba01.jpg](https://user-images.githubusercontent.com/614929/200263613-72b40fd2-b655-42ab-9592-d438575cd349.jpg)
**concrete plates**


![leobersdf01.jpg](https://user-images.githubusercontent.com/614929/200263720-de82376c-7c6a-4071-9dfb-d11dc728bac3.jpg)
Unsure, would use **concrete**


![image%3A1000008578_eightbit.png](https://user-images.githubusercontent.com/614929/200263790-8381da9f-55ab-44ca-bb54-dd67df8281b3.png)
**concrete plates**


![iStock_000003502738XSmall.jpg](https://user-images.githubusercontent.com/614929/200263837-553458fc-d7cb-4aa1-9604-5b41e014ec90.jpg)
**concrete**


![Ehemalige-Reichsautobahn.jpg](https://user-images.githubusercontent.com/614929/200263887-98326e2a-1511-4e1e-8b94-2a8e61513d70.jpg)
**concrete plates**

**Comment by mnalis** [comment]
For interested parties, see also:

- Discussion at tagging mailing list: https://lists.openstreetmap.org/pipermail/tagging/2022-September/065413.html
- Help site https://help.openstreetmap.org/questions/85524/concrete-vs-concreteplates
- Wiki Talk https://wiki.openstreetmap.org/wiki/Talk:Tag:surface=concrete:plates

- and https://github.com/streetcomplete/StreetComplete/issues/2437 for reasons why `concrete:plates` was added in the first place
