### ISSUE TITLE
Motorway on Bridge renderd beneath road underneath in Footpath Overlay

### ISSUE THREAD

**Issue by GlOwl** [streetcomplete/StreetComplete#4347]
Have seen it a few times now that a motorway tagged as "on a bridge" is rendered beneath a road that is crossing underneath. It only switches that way when The Footpath Overlay (Bürgersteig in German) is enabled.

Is this on purpose? because it quite confused me, as i can not remember being shown a warning that this happens. even though i would kind of get why it was chosen this way, because motorways have no footpaths and so are not as important in this view.

Using
StreetComplete v45.2

Screenshots:
No Overlay:
![62fa1b26a09ec7640395833cab80458827ad7b4463c378b89a2f3e4397cce5df](https://user-images.githubusercontent.com/25726955/188271162-eafbe0ac-e144-472f-9390-b539ff835f38.jpg)

Pathway Overlay:
![524356affed2907c61cba997e231ccfd244dc44befbd1a6887ec11de14911601](https://user-images.githubusercontent.com/25726955/188271165-1b903142-be2e-4c9c-a7d7-bf6080592863.jpg)

Lantern Overlay:
![6e5e1872e76a45552d16099b51e4c8d21c01a0cd75b4232b67f71fc07875404d](https://user-images.githubusercontent.com/25726955/188271157-52bff196-d5d6-42a7-a9d9-54c6c87ae52a.jpg)

Same Coordinates on the OSM website with my confused osm issue:
https://www.openstreetmap.org/note/3333963#map=19/49.93292/7.89535

**Comment by GlOwl** [comment]
But it might be an issue with the map style? I am not quite sure.

**Comment by mnalis** [comment]
I think it is intentional that overlay is shown at the top. See https://github.com/streetcomplete/StreetComplete/issues/4310#issuecomment-1226413517

**Comment by westnordost** [comment]
It is deliberate that anything part of the overlay is always shown on top of anything that is not in the overlay. Motorways are the only road type that are not shown (and are not editable) in the sidewalk overlay, hence they are shown behind any other road.
Motorways are shown in the lit overlay though and are editable, so they are also shown on top of everything else just like all the other roads. Hence, in this overlay, you see the motorway on top of the other road again (because it has a higher `layer` property)
