### ISSUE TITLE
Mehr Symbole bei Wegen und Straßen

### ISSUE THREAD

**Issue by OpenGreenStreet** [streetcomplete/StreetComplete#4348]
Für Wegen und Straßen würde ich mir in StreetComplete Symbole zur Abfrage der Oberfläche ca. aller 100m wünschen. Oft gibt es für lange Wegabschnitte nur ein einziges Abfragesymbol, so dass man viel scrollen/witschen muss, um am Ende des Weges das Abfragesymbol wieder zu finden.

**Comment by mnalis** [comment]
Can you post a screenshot of what you mean exactly? I think that on long ways SC does indeed show additional multiple quests icons on the way, and not just at the way start and end?

**Comment by legofahrrad** [comment]
![grafik](https://user-images.githubusercontent.com/92865620/188285614-bcdae68c-94ab-40ad-b466-1b93f575fbaf.png)
This is a 600 m long street – the markers are at both ends plus one in the middle.
The idea is to place more quest markers in higher density.

**Comment by mnalis** [comment]
>  The idea is to place more quest markers in higher density.

OK, but **_why_**? Can you not click on existing icon(s)? Or do you not see the highlighted road? Or what is the usability problem _exactly_?

BTW I guess number of icons depends on the zoom and not meters; e.g. in your picture you _might_ be able to squeeze `2` more icons (or maybe not - they may then hide existing ones if they overlap). But if you could, how exactly would that help usability in this situation if there were for example `5` icons on the screen (instead of just `3` as currently shown)?

Perhaps DeepL has not translated that very good, but translation seems to say that this is a problem because :
> so you have to scroll/swipe a lot to find the query icon again at the end of the path.

I do not see in your picture **_why_** would you need to _"scroll/swipe (pan?) a lot to find the icon"_ ? I can see 3 icons just fine in that screenshot.

**Comment by OpenGreenStreet** [comment]
Ich habe noch einmal darüber nachgedacht und vermute auch, dass das Zoomen das eigentliche Problem ist: ich arbeite mit StreetComplete meist mit einem sehr starken Zoom und sehe dann bei langen Wegen „kein“ Symbol mehr.

Wäre es nicht möglich, egal wie stark der Zoom-Faktor ist, immer ein Symbol für die gefragte Oberfläche des Weges einzublenden?

(Das wäre für mich wichtig, da sich oft die Oberfläche sowohl von der grundsätzlichen Struktur als auch von der Qualität ändert.)

**Comment by westnordost** [comment]
Nein, nach Zoom kann man da nichts machen. Aber ich habe mal die Mindestentfernung die zwischen den Pins liegen muss um 20% gekürzt.

**Comment by OpenGreenStreet** [comment]
@westnordost : prima, vielen Dank
