### ISSUE TITLE
Skip address quests for Norway

### ISSUE THREAD

**Issue by NKAmapper** [streetcomplete/StreetComplete#4360]
Please skip Norway for any quests related to addresses. We already have 100% coverage with automated updates.

I believe this is also the case in Denmark.

**Comment by matkoniecz** [comment]
Which address quests are are enabled in Norway and should not be?

**Comment by NKAmapper** [comment]
The one I have seen in changesets is AddAddressStreet.

**Comment by matkoniecz** [comment]
Can you link unwanted edits?

Given

> We already have 100% coverage with automated updates.

how it could be causing problems? It is only triggered for incomplete data.

**Comment by NKAmapper** [comment]
https://www.openstreetmap.org/changeset/125617363

**Comment by matkoniecz** [comment]
And why it is wrong? Is this address not including street as part of the name?

**Comment by NKAmapper** [comment]
My observations:
- There is already another separate node within the building footprint with the full address information (this is how the communities in Norway and Denmark have decided to maintain the addresses).
- The new address information from StreetComplete on the building is incomplete/inferior (it lacks addr:housenumber and addr:city).
- The addition from StreetComplete creates duplicated information of the already existing address node.

I am sure the quest is helpful in other countries which lack addresses in OSM, but not in Norway (and Denmark).

**Comment by Helium314** [comment]
Why this address was seen as incomplete and thus asked: The building has `addr:housename` without `addr:streetname`
So actually the address information on the building was arguable less complete before adding the street name...

If the name is indeed part of the address it should be moved to the address node to have complete data, and if it's not part of the address it should better be in a normal `name` tag.

**Comment by mnalis** [comment]
I agree that if an object has `addr:housename` but not `addr:street`, it should be added according to  [Key:addr:*](https://wiki.openstreetmap.org/wiki/Key:addr:*) wiki (although wiki says it alternatively can be represented by relation - which I don't think SC checks for, but is not an issue in this example).

Though I was wondering, wasn't SC generally supposed to skip the `house number/name/street` quests if there is already address node with such information `"(addr:housenumber OR addr:housename) AND addr:street`" inside `building=*` polygon ?

As for this specific request, seeing that we **_already skip_** `NO`/`DK` for [AddHousenumber.kt quest](https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/address/AddHousenumber.kt#L29), I guess it makes sense to also skip `NO`/`DK` in [AddAddressStreet.kt](https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/address/AddAddressStreet.kt#L32) too.

**Comment by westnordost** [comment]
The `AddHousenumber` quest is already skipped for Norway.

The `AddAddressStreet` quests merely checks for **incomplete** address information (`addr:housename` or `addr:housenumber` without `addr:street` or at least `addr:place`). It does not introduce any duplicate information, it only compliments incomplete data. See https://github.com/streetcomplete/StreetComplete/issues/4360#issuecomment-1239033183

So, it does not make sense to skip `AddAddressStreet` for regions in which `AddHousenumber` is disabled. If the imports are complete, the quest would never be asked.

**Comment by NKAmapper** [comment]
House names are not part of any public addresses in Norway, as defined by the national cadastre registry. So any address built on addr:housename would be incorrect.

**Comment by Helium314** [comment]
If it's not part of the address, isn't `addr:housename` invalid?

**Comment by NKAmapper** [comment]
Correct, but random users may not know that.

**Comment by mnalis** [comment]
@NKAmapper So, it I'm reading this correctly, you're saying that in that specific example (https://www.openstreetmap.org/way/97419687) `addr:housename=Trondhjems Stempelfabrik` is incorrect, and **instead** of **_adding_**  `addr:street=Fjordgata` (which was done by SC user), `addr:housename` should have been **_removed_** (as it is invalid)?

**Comment by NKAmapper** [comment]
Adding addr:street was wrong, and the name could be assigned to name=* or old_name=*. This issue is about the general case though.

**Comment by mnalis** [comment]
@NKAmapper Well, in general case, as explained above by westnordost, the quest would **never** pop up in `NO`/`DK` as they (as you say) have **all addresses** mapped with both  `addr:street` **and**  `addr:housenumber`, and this quest pops up **only** when `addr:street` is missing (**and** one of `addr:housenumber` / `addr:housename` is present). 

So, **_the quest would only pop up when the underlying data is already incorrect_** (as in this case) and **never** when the data is correctly mapped. And when it does pop up, it would give the more experienced mapper the option to leave a note (with a picture perhaps) to explain what exactly is incorrect (and nonexperienced would map extra information like this, which again would help experienced `NO`/`DK` mapper to look at changesets and clean up _pre-existing_ invalid data - like invalid `addr:housename=Trondhjems Stempelfabrik` in this case).

If one prefers to be proactive rather then reactive, one can use [this overpass query](http://overpass-turbo.eu/?Q=%5Bout%3Ajson%5D%5Btimeout%3A25%5D%3B%0A%2F%2F%20gather%20results%0A(%0A%20%20nw%5B%22addr%3Ahousenumber%22%5D%5B%22addr%3Astreet%22!~%22.*%22%5D(%7B%7Bbbox%7D%7D)%3B%0A%20%20nw%5B%22addr%3Ahousename%22%5D%5B%22addr%3Astreet%22!~%22.*%22%5D(%7B%7Bbbox%7D%7D)%3B%0A)%3B%0A%2F%2F%20print%20results%0Aout%20body%3B%0A%3E%3B%0Aout%20skel%20qt%3B&C=59.7397;10.19941;15) to detect such invalid tag combinations in `NO`/`DK` in order to correct them. When they are corrected, this SC quest would never pop.
