### ISSUE TITLE
new building type: security checkpoint 

### ISSUE THREAD

**Issue by Identitaet** [streetcomplete/StreetComplete#4374]
**Use case**

Often next to barriers there are little buildings where a security guard sits and does security stuff 
**Proposed Solution**

I'm a bit unsure how one would tag.

But the solution is to add it

**Comment by wielandb** [comment]
There is [building=guard_post](https://wiki.openstreetmap.org/wiki/Tag:building%3Dguard_post), but it only has 24 uses :(

**Comment by westnordost** [comment]
True about the low usage. People have been struggling to find a proper tag for that. There is `building=gatehouse` (German translation: Pförtnerhäuschen), however the wiki defines this as a building that spans over a road. 

@SK53 added to the wiki in November 2021 that this tag (should) also describe it as 

> small modern buildings at the entrances to large commercial, industrial, military or academic (university) sites) housing security personnel who control access to the site

but @matkoniecz removed this again in June 2022, pointing instead to the tag mentioned, `building=guard_post`. Given that the tag hasn't been documented very long, I think `building=guard_post` is fine, the low usage is not an issue because there is not any more popular tag to describe the thing.

I am worried though about that the usage number of `building=gatehouse` went up rapidly only after @SK53 added the cited paragraph to the wiki. So maybe the de-facto meaning of `building=gatehouse` has already become what he described it as?

**Comment by westnordost** [comment]
By the way, so far I have usually tagged such guard posts as simply "commercial", i.e. a nondescript/multipurpose building on a commercial or industrial compound. IMO that's also fine. There are uncountable special purpose buildings around, we cannot accomodate all anyway.

**Comment by matkoniecz** [comment]
>  I have usually tagged such guard posts as simply "commercial", i.e. a nondescript/multipurpose building on a commercial or industrial compound

I prefer to tag them specially as they are (at least to me) quite distinct and not really commercial. Especially ones on military bases.

Ones in gated residential areas and in industrial sites can sort of fir commercial label, but...

**Comment by matkoniecz** [comment]
There is also https://en.wikipedia.org/wiki/Guardhouse https://taginfo.openstreetmap.org/tags/building=guardhouse#overview that seems to apply both to tiny booths and large buildings. Somehow I ignored/missed it while making writeup last time?

Would it cover https://commons.wikimedia.org/wiki/Category:Crossing_keeper_cabins ? Note say https://www.openstreetmap.org/way/589832071

**Comment by SK53** [comment]
SK53 here. 

I documented actual usage of the tag, not what I believed was correct. The change would have been based on UK usage I expect. My problem is that the historic gatehouse at the bottom of the road was mapped as a castle, but when I came to examine tag usage most examples of gatehouse were actually the simple security cabin type.

If usage increased it was just because lots of people had the same dilemma and had no idea how to tag things.

IMO: gatehouse should be reserved for elaborate structures with a gate/gates in them, often of historical interest
guardhouse should be used for all other things, typically small buildings or even cabins housing security personnel at entrances to campuses, industrial sites, etc.

**Comment by michaelblyons** [comment]
> If usage increased it was just because lots of people had the same dilemma and had no idea how to tag things.

I am one of those people. I've (mis?)tagged a number of these over time. Whatever gets decided, I'll try to update my history to match.

**Comment by Identitaet** [comment]
To be honest I hoped I was just missing some random English translation for this but since it seems to be completely unclear I guess we could just close it for now

**Comment by westnordost** [comment]
> There is also https://en.wikipedia.org/wiki/Guardhouse https://taginfo.openstreetmap.org/tags/building=guardhouse#overview that seems to apply both to tiny booths and large buildings. Somehow I ignored/missed it while making writeup last time?

Looks like it. It has more usage than `guard_post` even though it is not documented. I looked at some buildings tagged like that randomly and this sounds about right. All I've found were some kind of guard post/guardhouse buildings at the entrance of industrial or military or aeroway estates ("Pförtnerhäuschen").

So we can use that. I made an icon:

![guardhouse](https://user-images.githubusercontent.com/4661658/193351875-a4abe62f-6adc-4b72-bf11-1430f09937e6.png)

**Comment by rhhsm** [comment]
I've been looking for such a building for some time, and recently found it by accident under the "For cars" category. Since it is used at many more sites than only car parks, could it be moved under the "Others" building types?

**Comment by westnordost** [comment]
It's also in "commercial" category. After all, those things are found primarily at the entrances of large industrial or commercial properties.

**Comment by rhhsm** [comment]
They are also found at entrances to gated residential communities and to public buildings (ministries, embassies, etc.), so it should then be in the "residential" and "public" categories as well ;)

**Comment by westnordost** [comment]
Well, then I move it to "other"

**Comment by mpawelski** [comment]
I just learned about this `building=guardhouse` because my old [note](https://www.openstreetmap.org/note/3027301) was resolved and I wanted to suggest adding this type to StreetComplete. Nice that this was added!

But I would suggest adding some small text description to it, because IMO just a "Guardhouse" ("Wartownia" in polish) doesn't explain that well what is it. Something like the the description in [wiki](https://wiki.openstreetmap.org/wiki/Tag:building%3Dguardhouse) would be great. Maybe just shorter, like for example:

"small building with guards inside, common at supervised parking lots and other areas that are surveilled by guards"

**Comment by mnalis** [comment]
Good idea @mpawelski , although even that shortened description seems to me longer than currently existing ones for other building types.

**Comment by matkoniecz** [comment]
"building constructed to house guards, common at entrances to guarded areas such as parking lots" ?

**Comment by matkoniecz** [comment]
Though in general opening new issues is better than commenting in old ones - comments in old ones may be easily missed while new open issue is more visible.

**Comment by SK53** [comment]
Suggest s/guards/security staff/, s/guarded/controlled/, s/parking lots/industrial areas/.

The common uses for me are: industrial areas, particularly factory sites, commercial areas including one or more warehouses, data centres, universities, military sites. First two are as much about controlling staff **leaving** the site (theft) as entering, miltary/data centres are about authorised access, universities are probably mainly about parking. The normal one I see at car parks is a parking attendant, rather than a security guard, whose role is to take parking fees (and enforce overstay penalties).

**Comment by matkoniecz** [comment]
yes, security staff is especially good one as it demilitarises it a bit

I will likely just drop "such as" part
