### ISSUE TITLE
overlays for surface

### ISSUE THREAD

**Issue by matkoniecz** [streetcomplete/StreetComplete#4378]
For now issue only as code is not worth reviewing for now.

Issue is created to reduce risk that someone else will work on it (and it is quite amazingly elaborate to deal with various surfaces)

**Comment by westnordost** [comment]
And smoothness?

**Comment by mnalis** [comment]
> And smoothness? (If there is an overlay for smoothness, I would actually remove the quest for it then because without seeing how the surrounding data is tagged, it is really head to answer sometimes)

While `smoothness` overlay might be nice _addition_, if adding `overlay` would mean a demise of the `quest`, I'd actually **_prefer quest form_** only. 

At least over here, it _**quite often**_ happens that surface quality degrades on _segments_ of the road only (and very often, the OSM road is split into segments **_only_** because the parts differ in `smoothness` - e.g. `smoothness=good` becomes `intermediate` and even `bad` on parts; or alternatively they patch up or resurface only worst few hundred meters of road when quality of those drops to mostly unusable levels). 
Using Overlay people would (/might) mistakenly assume (without actually physically traveling all segments of the road) that because there is `bad` patch of the road sandwiched between two `intermediate` parts, that it should be "fixed" to `intermediate` too. (yeah, I know, everybody _should_ physically visit, but...)


While it  also might sometimes happen with `surface` (e.g. `compacted` part of the road in between two `asphalt` parts, for example in preparations of resurfacing bad segment with asphalt), it is **much more rare**  (and much more temporary) condition, and thus probably not problematic for overlay.

**Comment by NotSoImportant** [comment]
As a reference you can check OsmAnd. 

Surface:
![Screenshot_20221031-151125](https://user-images.githubusercontent.com/35758921/199028911-dbcc9901-1189-4b9c-bac8-c06da6e2035e.png)

Smoothness:
![Screenshot_20221031-151103](https://user-images.githubusercontent.com/35758921/199029057-a724f002-66e1-4f75-bf44-2c39d25675d7.png)

Legend:
![Screenshot_20221031-151320](https://user-images.githubusercontent.com/35758921/199029105-b8227a2b-a72c-4e36-b28d-01171a75b9bc.png)

In addition: track type:
![Screenshot_20221031-151655](https://user-images.githubusercontent.com/35758921/199029503-48d132a3-386b-462c-afab-eec1ad19d26b.png)

**Comment by westnordost** [comment]
four different shades of brown...

**Comment by NotSoImportant** [comment]
> four different shades of brown...

While it might not be perfect, it is an existing solution to visually compare surface, smoothness and track grade. Just wanted to share this to make you aware. I am sometimes using it in parallel while solving those kind of quests. Take what is good and change what isn't :-) 

> but I was more like: `wait, what, OsmAnd actually has a legend for all those?! Where???`

Yes, it is well hidden in the help dialog. 
![IMG_20221031_204101](https://user-images.githubusercontent.com/35758921/199096667-09bfcb54-cfad-4bae-a843-cfda5559c667.jpg)

**Comment by matkoniecz** [comment]
StreetComplete now detects string conflicts between surface. And tracktype values are not intuitive, highly abstract and hard to judge in my experience.

I used surface overlay in forest and it was useful (even if not as useful as I expected) but I never used or had need for tracktype overlay.

I will disable tracktype overlay in my implementation, revert tracktype changes (get rid of `app/src/main/java/de/westnordost/streetcomplete/osm/Tracktype.kt` in https://github.com/streetcomplete/StreetComplete/compare/master...matkoniecz:overlays?expand=1 ) and drop this plan.

**Comment by matkoniecz** [comment]
I am getting to the end! 

open questions that are not code-specific:
Maybe do not show service=driveway without surface as missing data. While still allowing to set it. The same may apply to lit overlay.

How surface=mud and surface=metal_grid should be supported?
Added to regular surface answers?
Shown as values but unselectable as answer?
Not supported at all, ways with this surface values are not editable? (current state)
See also https://github.com/streetcomplete/StreetComplete/discussions/4300

What about brick, bricks, paving_stones:30, cobblestone:flattened ? These are for now not supported at all and I plan to leave them this way as dubious values.
Though maybe brick/bricks should be shown as alias of paving_stones like earth is shown as alias of dirt?

**Comment by westnordost** [comment]
You mean independent of it being set as private? Rather not. 

Regarding mud etc... how open ended are the sirface tags really? Probably certain values should be **shown as** syonymous to values Wer support but should not be changed of the user "okay"s the displayed selection. Pretty much what the lit overlay does with certain values IIRC.

**Comment by matkoniecz** [comment]
> You mean independent of it being set as private? Rather not.

OK

> Probably certain values should be shown as syonymous to values we support but should not be changed if the user "okay"s the displayed selection.

Done with `surface=dirt/earth/soil`

> how open ended are the sirface tags really?

I would say that `surface` is not freeform field - and in this it is closer to `highway` road values than to `building` endless value ocean. Though some may be missing and new values may appear, like `highway=busway` appeared recently.

**Comment by matkoniecz** [comment]
> because we do not want a situation where StreetComplete shows such rare but OK tags as "missing" and destroys data by letting the user re-tag it with a value that is perceived as less detailed.

Current handling of unrecognised tags is to disallow editing (you cannot tap on such objects in overlay)
