### ISSUE TITLE
Add monorail bridges to maxheight quest

### ISSUE THREAD

**Issue by Squamoto** [streetcomplete/StreetComplete#4387]
**Use case**
Currently the maxheight quest only checks for crossing railway bridges with these attributes:
`rail|light_rail|subway|narrow_gauge|tram|disused|preserved|funicular`

Monorail bridges should be included too. Real life use case:

https://www.openstreetmap.org/note/3360680

**Proposed Solution**
Add monorail in [AddMaxHeight.kt#L47](https://github.com/streetcomplete/StreetComplete/blob/7c97885cb6c24f9f7defed22e4497a495ab7e4ab/app/src/main/java/de/westnordost/streetcomplete/quests/max_height/AddMaxHeight.kt#L47)

**Comment by westnordost** [comment]
Sure, will you create a PR?

**Comment by adbok001** [comment]
Easier if you just add it yourself I guess

**Comment by westnordost** [comment]
The reason why I encourage users to make simple changes deemed useful themselves is because my own time is limited and there are certain things in this project only I or very few other experienced contributors can do which is why I try to focus on these.
Furthermore, by changing it oneself, new contributors may become slowly more familiar with the code and be able to do more complex things later on, making the number of people that maintain this project larger, ensuring the future of this project.

One reason why I started this project at all was because I eventually realized that most OSM enthusiasts are not software developers and while I could just merrily map on, I'd have a greater impact if I created software that made it more easy for others to contribute - because fewer are able to do that as they are not software developers.
Everyone can help according to his/her own ability. I believe adding monorail to that quest filter is well within your ability to contribute.
