### ISSUE TITLE
Add parking=street_side and parking=lane areas to access and fee quests

### ISSUE THREAD

**Issue by Discostu36** [streetcomplete/StreetComplete#4392]
**Use case**
If I see correctly, the quests that ask for `access` and `fee` for `amenity=parking` are not asked for `parking=street_side` and `parking=lane` areas. They should because they often have fees and/or access restrictions, especially in cities.

**Proposed Solution**
Add these types of parking to both quests.

**Comment by matkoniecz** [comment]
See  #2408 and ```
    // Exclude parking=street_side lacking any access tags, because most of
    // these are found alongside public access roads, and likely will be
    // access=yes by default. Leaving these in makes this quest repetitive and
    // leads to users adding lots of redundant access=yes tags to satisfy the
    // quest. parking=street_side with access=unknown seems like a valid target
    // though.
    //
    // Cf. #2408: Parking access might omit parking=street_side
```

in https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/parking_access/AddParkingAccess.kt for why it is done this way now.

Not really sure.

**Comment by Discostu36** [comment]
At least in larger German cities, many parking spaces next to the road might be reserved to residents. But one thing that I didn't consider is that there does not seem to be a documented consensus about how these should be tagged. Looking at the `parking:lane` scheme, `access=residents` is the most logical choice, but this is not documented yet. So maybe it's not the right time yet to implement this into SC.

Fee, on the other hand, is a more clear case in my opinion.

**Comment by matkoniecz** [comment]
> Fee, on the other hand, is a more clear case in my opinion.

https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/parking_fee/AddParkingFee.kt#L11

no exclusion (can be found with https://wiki.openstreetmap.org/wiki/StreetComplete/Quests )

**Comment by Discostu36** [comment]
I see, so those are kind of dependant on each other. I understand that SC doesn't want to ask about fees on parking lots that might be private. So no there is no real good solution for this at the moment I guess 😕

**Comment by westnordost** [comment]
Like @matkoniecz said, also the whole access + fee thing on parking areas (vs street-parking) is not really well thought out yet tagging-wise. This needs some proper proposal to capture all the thins that may apply (resident parking, resident parking + fee, disc parking etc etc) and hopefully aligning the tagging schemese of street-parking and parking areas. @SupaplexOSM might be working on that. At least he would be interested in contributing to it should a to-be-discussed proposal arise.

**Comment by SupaplexOSM** [comment]
I actually plan to document access and fee tagging with examples from [this overview page](https://wiki.openstreetmap.org/wiki/Proposed_features/parking_conditions_on_separately_mapped_parking_areas) for street-side/lane parking areas in the wiki soon - either directly on the [street-side wiki page](https://wiki.openstreetmap.org/wiki/Tag:parking%3Dstreet_side) or as a separate proposal. (But since this is about applying an already established tagging in a special case, a proposal is not really necessary). In preparation for this, I recently [asked for feedback on the tagging mailing list](https://lists.openstreetmap.org/pipermail/tagging/2022-September/065331.html).

In principle, I would support a "synchronisation" of the two schemes (parking:condition and access/fee variant), but I myself will not continue to push this, as imho this would require a complete reworking of the parking:lane/condition scheme (see column ["_using access/fee/maxstay_" on "_Linear Features_"](https://wiki.openstreetmap.org/wiki/Proposed_features/parking_conditions_on_separately_mapped_parking_areas#Examples)) and thus also of all applications that are already based on this scheme (not least the new StreetComplete overlay or my own [parking lane analysis method](https://parkraum.osm-verkehrswende.org/project-vector-tiles/#16/52.47928/13.4381)).
