### ISSUE TITLE
Opposite road mark rotation in quest "What's the surface of the sidewalk here?"

### ISSUE THREAD

**Issue by massimostanzione** [streetcomplete/StreetComplete#4402]
While solving the _"What's the surface of the sidewalk here?"_ quest, the road represented into the image in the bottom of the screen, to which the quest is related, is shown with the "?" mark rotated in the opposite direction.

For example, a straight road with two nodes, of which the initial one to the south, the final one to the north (therefore "pointing" to the north, and which should be represented with the mark "?" as it is read) is represented with the mark upside down (¿), pointing to the opposite direction.

In the image in the bottom, however, updated sides of the road are compliant to the mark: left (right) sidewalk is placed coherently on the left (right) of the mark as you would read it upside down, and the tags `sidewalk:left=*` are preserved and correctly loaded. The problem is only related to the orientation of the mark.

**How to Reproduce**
Try to load the quest, for example, for [way 174636377](https://www.openstreetmap.org/way/174636377), purposely left not solved.

**Versions affected**
v46.1

**Comment by westnordost** [comment]
Better if you made a screenshot for illustration purposes

**Comment by massimostanzione** [comment]
... well, fair enough :)
Take, for example, the way mentioned above: the sidewalk is only on the **left** side.

This is the way mentioned above as it appears in JOSM, you can check the orientation:
![immagine](https://user-images.githubusercontent.com/58670599/191615285-e486034d-8060-4d30-93f2-c4b01a4a87bd.png)

this is what is shown in SC, where the "?" mark seems to be upside down from what it should be:
![immagine](https://user-images.githubusercontent.com/58670599/191617055-2c007aef-54fc-4337-b9b9-6fc1faa77567.png)

and this is what is shown when the answer to the quest is selected:
![immagine](https://user-images.githubusercontent.com/58670599/191617362-7f477236-ee16-4447-976f-fb42898c000d.png)

**Comment by massimostanzione** [comment]
@mcliquid Thank you for your answer, it was not really easy to make the question clear. The main concept is that the _The road in the illustration is rotated the same as its center on the map_ note, shown above the illustration, is not valid anymore in this case.

**Comment by westnordost** [comment]
@arrival-spring are you interested in looking into implementing this suggestion? It sounds like it would make sense: 

> Idea for better implementation:
> Both sides are shown after all, but in this case the right side is already marked with "Has no sidewalk". So it would be immediately obvious how the tagging looks here.

**Comment by arrival-spring** [comment]
That's how I had it originally, see #3735, in particular:
<img src="https://user-images.githubusercontent.com/77166354/152869857-ec54a340-d74c-4141-9312-2f46cfa86951.png" width="250">

You then changed it to how it currently is when you refactored, I think in #3873, and I assumed there was a reason for that. I wonder if it was to simplify code in terms of not having options to have only one side selectable?

**Comment by westnordost** [comment]
I can look into that though, if you are busy or don't want to implement it again after I seem to have removed it in the refactor

**Comment by arrival-spring** [comment]
I am a bit busy, so am unlikely to get a chance to look at this any time soon

**Comment by peternewman** [comment]
Looking forward to getting this back, I'd meant to flag up the regression, it would certainly get complicated without it when you're abroad and dealing with people driving on the other side of the road.

**Comment by westnordost** [comment]
Sorry to disappoint, but I decided to not do this after all. Turns out, there was a reason why I removed it.
 
<details>
</summary>
I tried to do this, two times, each from different angles, but came to the conclusion that this slight improvement is not worth the additional code.</summary>

The current generalization of the code does not allow for one side of the street-side-select-puzzle to have a representation that does not represent a selectable value + does not count towards not being set + is not clickable. The meaning, i.e. what it should do, is very similar to not showing that side at all, which is why I opted to use that mechanism for sidewalk surfaces too. Maybe how it used to be is a little clearer, but confusion can arise just as well with that approach when the user finds out that the side is not clickable. Or, when the user notices that it is actually not "no pavement" but it is mapped separately - remembering from the sidewalk quest that this should be tagged differently, not knowing that @arrival-spring 's original implementation did not differentiate there. (So to solve this, the text would have to be different depending on that, but this again introduces more sonderlocken)
Doing it the other way round, i.e. always showing both sides but showing the "disabled" side as just a street without anything else on the other hand would not work for cycleways because there is this other answer option to also define the other side (for oneway roads). If that other side would already be shown, there'll be confusion why it is not clickable.

Anyway, that's the price one pays for generalization of UI, the UI becomes less customizable. But #4402 is a very small price to pay, IMO.
</details>

But what I will do, is to reduce the size of the street side select puzzle a bit when only one side is shown. Part of the confusion of the OP is certainly because the round "paving stones" icon obscures pretty much all of the sidewalk graphic shown below.
