### ISSUE TITLE
Groups for "Multiplayer"

### ISSUE THREAD

**Issue by PPPBerlin** [streetcomplete/StreetComplete#4403]
Hi,
 a workmate showed me this application yesterday and I'am very happy with it. We spread it to much more mates and now it would be nice to kid of challenge each other for example in a group.

Many thanks for the gamification to keep OSM updated! :)

**Comment by HolgerJeromin** [comment]
ref #4150

**Comment by PPPBerlin** [comment]
I had already considered mentioning this point. I am not concerned with the temporary function, which works well. I am concerned with a longer-term function.

**Comment by mnalis** [comment]
Well, you can check the number of stars under `My Profile` and compare it with your mates.

Note that while friendly competition might often be nice way to increase contributions, it might also lead to data corruption and other issues "in order to win". For examples, see issues linked at https://github.com/streetcomplete/StreetComplete/issues/3706 
So making a direct competition is in many cases not a great idea, unless you are absolutely sure all your companions are already hardcore OSM editors and thus very likely to value OSM correctness way more than winning in any competition.

I've now added an FAQ entry for it. https://wiki.openstreetmap.org/wiki/StreetComplete/FAQ#I_like_gamification_factor_of_StreetComplete,_and_have_an_idea_how_to_increase_it_even_more

**Comment by westnordost** [comment]
"may lead to data corruption" sounds cryptic in your comment and in the wiki.

What is meant:

Statistically speaking, the more competitiveness there is, the higher the possibility that people will get sloppy with actually verifying the information recorded on-site because they want to solve more quests in less time, which inevitably leads to incorrect data.
For example, _"Oh, this very long street has a sidewalk here, it will surely also have a sidewalk at the other end, I can't be bothered to go down there now"_ or worse, for example answering for all buildings in a suburb that they are detached houses without actually having checked it on-site because one assumes that all buildings there are (but then there are garages, sheds, semi-detached houses, some apartment buildings, houses that have been demolished etc.)

The more gamification, the more the people this app will attract who also want to "game" it. I.e. actually contributing data to OSM takes a backseat and being on top of the leaderboard and similar is more important. Again, statistically speaking, this decreases the quality of the data collected with StreetComplete.

**Comment by mnalis** [comment]
thanks, I've updated the FAQ with your nicer explanation!
