### ISSUE TITLE
Missing meta data / context in wheelchair quest

### ISSUE THREAD

**Issue by HolgerJeromin** [streetcomplete/StreetComplete#4448]
https://www.openstreetmap.org/node/1423239695

entrance : yes
shop : estate_agent

![rps20221001_181016_971](https://user-images.githubusercontent.com/2410353/193418294-edae4451-9dab-4610-8e6a-ff36df96f104.jpg)

SC  v48.0-alpha1

**Comment by westnordost** [comment]
This is because `shop=estate_agent` is not recognized by the iD presets. The iD presets support the much more widely used `office=estate_agent` instead. 

It is mentioned here, too:
https://github.com/openstreetmap/id-tagging-schema/issues/529

I guess the reason why iD does not propose to "upgrade" `shop=estate_agent` to `office=estate_agent`, i.e. recognize the former as "deprecated" is because that tag is actually not deprecated.
In any case, this is an upstream issue.

**Comment by HolgerJeromin** [comment]
If SC knows nothing we should perhaps present the raw (main) tag so the user get a clue that the quest is not for drachenpoint (in the screenshot).
At least for shop=/office= elements.

**Comment by westnordost** [comment]
No, not making exceptions to not confronting the users with the tags. Drachenpoint is shown as a separate node.

**Comment by HolgerJeromin** [comment]
Skip the quest because how should the user be able to answer the quest?

**Comment by westnordost** [comment]
In #4241 (@Helium314 ) it was changed that this quest is also asked for nameless properties. I guess this was done under the assumption that for every feature asked, a feature name can be found through the id editor presets.

A few quests, like the opening hours quest, explicitly check for whether the object can be named and only show it if that is the case

https://github.com/streetcomplete/StreetComplete/blob/4a8f743ffc55eb23a266a7f0c073f3d76fb270fc/app/src/main/java/de/westnordost/streetcomplete/quests/opening_hours/AddOpeningHours.kt#L176-L182

...but to do that for every (shop-POI) quest would be somewhat expensive to do I think - not to mention the code duplication.

So while the current situation is not favourable (because inconsistent), i.e. some quests are shown even if the feature cannot be referred to by name and some have these checks, the better long term solution is to "simply" improve the id presets to cover more shop types rather than dealing with it in the way as cited above.
Maybe we should (just) return to checking `name or brand or name:signed=no` for all shop-type quests (and trusting that `name:signed=no` is only set if it has a feature name as the `AddPlaceName` quest checks for that?)

@FloEdelmann @matkoniecz

**Comment by matkoniecz** [comment]
> Maybe we should (just) return to checking name or brand or name:signed=no for all shop-type quests (and trusting that name:signed=no is only set if it has a feature name as the AddPlaceName quest checks for that and name:signed=no is usually only set by that quest?)

That makes sense to me.

For nameless objects answering this quest requires identifying specific objects anyway, so it means that user can answer `AddPlaceName`

If user failed to answer `AddPlaceName` and `name or brand or name:signed=no` is missing it means that either happened:

- no supporting iD presets so skipping it is a good idea to prevent problem like here (and per https://github.com/openstreetmap/id-tagging-schema/issues/529 this problem is relatively rare)
- user was unable to answer name quest (so skipping is a good idea)
- user disabled name quest (so not asking complicated questions requiring identifying feature is fine, I guess)

**Comment by FloEdelmann** [comment]
Checking `name or brand or name:signed=no` for all shop-type quests (except `AddPlaceName`, where we check for a iD feature name instead) sounds like a good mitigation to me.
