### ISSUE TITLE
Sidewalk layer should include motorway links

### ISSUE THREAD

**Issue by DerDings** [streetcomplete/StreetComplete#4475]
… to avoid gaps like this:
![Screenshot_20221007-173408_1.png](https://user-images.githubusercontent.com/42044179/194599590-0f1b68a7-db1e-4afc-9346-e89cf1a025c0.png)![Screenshot_20221007-174800_1.png](https://user-images.githubusercontent.com/42044179/194599607-92265992-7ffe-4bea-96c6-97827e9f29c9.png)

Maybe it should not show the „missing sidewalk“ glow, but it should be tappable and if sidewalks/no sidewalks are tagged they should be shown. Just like it's currently done for living streets.

**Comment by davidpnewton** [comment]
If it's a motorway link road then it's under motorway regulations or the local equivalent. That means no pedestrians. If it has a pavement then it's not under motorway regulations and therefore it's not a motorway link and shouldn't be tagged as such.

This comes down to the very bad practice of tagging things automatically from where such roads diverge from junctions. They are motorways between the limits of the motorway signs. Otherwise they should be tagged as link roads at the level of the junction they diverge from or merge with.

**Comment by DerDings** [comment]
> If it's a motorway link road then it's under motorway regulations or the local equivalent. That means no pedestrians. If it has a pavement then it's not under motorway regulations and therefore it's not a motorway link and shouldn't be tagged as such.
> 
> This comes down to the very bad practice of tagging things automatically from where such roads diverge from junctions. They are motorways between the limits of the motorway signs. Otherwise they should be tagged as link roads at the level of the junction they diverge from or merge with.

As far as I know, most motorway junction are tagged as motorway_link from junction to junction. However, things get more and more motorway-like the nearer you get to the motorway.
Tagging the first part of the link other than motorway_link would not be entirely different from current practice.

Anyways, this is a motorway_link tagging issue, not a sidewalk tagging issue. Thus, it doesn't have to be discussed here.
