### ISSUE TITLE
quest order and quest hide (temporally)

### ISSUE THREAD

**Issue by Katzenstreu** [streetcomplete/StreetComplete#4476]
Hi!

It would be great if i could change the order of quests on the same POI. Normally there are a few quests on the same place. Sometimes I want to "hide" or quit some quests because I can't answer them. Normally I want to answer all quests (all quests are chosen / activated).

Additionally sometimes are POI next to each other. So I have to answer a quest which I don't know. I would like to answer the little white pin point without simbol first.

Best regards
Tim

**Comment by mnalis** [comment]
> It would be great if i could change the order of quests on the same POI

You can. Go to `Settings` / `Quest selection and display order` an you can drag&drop quests to different order by dragging from the left part of the quest line (image of many dots) and moving it up or down.

> Sometimes I want to "hide" or quit some quests because I can't answer them

When answering any quest, you can select `Other answers` / `Can't say` and then choose `Hide`. That will hide that quest from you. (you can later restore those hidden quests if you choose so in `Settings` / `Restore hidden quests` to restore all of them, or you can click `Undo` button in lower left of the map and unhide them one by one, as wanted)

> Additionally sometimes are POI next to each other
> I would like to answer the little white pin point without simbol first.

Usually the solution is to zoom in, and more quests will be "expanded" from white dot to full quest. However, if you're already at maximum zoom, you obviously can't do that (and we can't increase max zoom due to https://github.com/streetcomplete/StreetComplete/issues/2878). Sometimes, when at maximum zoom, rotating the map changes which quests is shown, so it might help to show the quest which you want shown. Otherwise, you'd have to hide unwanted quests (see above) - when all surrounding unwanted quests are hidden, your white dot will expand to full quest icon which you can then solve.

**Comment by Katzenstreu** [comment]
Hi! 

> > It would be great if i could change the order of quests on the same POI
> 
> You can. Go to `Settings` / `Quest selection and display order` an you can drag&drop quests to different order by dragging from the left part of the quest line (image of many dots) and moving it up or down. (you can also click on three-vertical-dots icon there and choose `Manage presets` if you would like to have several different orders and choose between them later at will)
> 
I know. too complicated, too slow. This could be easier. 

> > Sometimes I want to "hide" or quit some quests because I can't answer them
> 
> When answering any quest, you can select `Other answers` / `Can't say` and then choose `Hide`. That will hide that quest from you. (you can later restore those hidden quests if you choose so in `Settings` / `Restore hidden quests` to restore all of them, or you can click `Undo` button in lower left of the map and unhide them one by one, as wanted)
> 
This is my "workaround" at the moment. Easier would be "Hide quest for 1 hour". 

> > Additionally sometimes are POI next to each other
> > I would like to answer the little white pin point without simbol first.
> 
> Usually the solution is to zoom in, and more quests will be "expanded" from white dot to full quest. However, if you're already at maximum zoom, you obviously can't do that (and we can't increase max zoom due to https://github.com/streetcomplete/StreetComplete/issues/2878). Sometimes, when at maximum zoom, rotating the map changes which quests is shown, so it might help to show the quest which you want shown. Otherwise, you'd have to hide unwanted quests (see above) - when all surrounding unwanted quests are hidden, your white dot will expand to full quest icon which you can then solve. 
Thanks, next time I'll try to rotate the map.

**Comment by mnalis** [comment]
> I know. too complicated, too slow. This could be easier.

Perhaps. Creating `presets`, while somewhat intensive, is something which only needs to be done once (and never again), so it worked fine for me. Your case might be different, of course; but it is something to try out.

If you however have some ideas how the easier workflow might look up, maybe with a mockups (or detailed explanation), it would be great to [start a discussion](https://github.com/streetcomplete/StreetComplete/discussions) about it, so perhaps something doable might be thought up.

> This is my "workaround" at the moment. Easier would be "Hide quest for 1 hour".

See https://github.com/streetcomplete/StreetComplete/issues/3952 and linked quests for discussion about that idea.

**Comment by OpenGreenStreet** [comment]
I would be delighted if this could be implemented soon.
