### ISSUE TITLE
Conflict between StreetComplete and Osmose?

### ISSUE THREAD

**Issue by Rudloff** [streetcomplete/StreetComplete#4478]
I have seen several back and forth like this: https://www.openstreetmap.org/way/40848257/history
It seems StreetComplete wants to use `cycleway:right=lane` and `cycleway:left=lane` whereas Osmose wants to use `cycleway=lane`.

**How to Reproduce**

Walk to a cycleway fixed by Osmose with `cycleway=lane`.

StreetComplete will add a "is this still the cycleway situation here" quest on the cycleway.
If answered, the generated tag will be considered incorrect by Osmose and probably fixed later by another contributor. Then the quest will appear in StreetComplete again.

**Expected Behavior**

StreetComplete and Osmose should not "fix" each other.

**Versions affected**

v47.0 on Android 11

**Comment by matkoniecz** [comment]
Why Osmose claims that this tagging is incorrect?

**Comment by westnordost** [comment]
Create a bug in osmose then.  An inspection rule that treats `cycleway:both=lane` and similar as an error and suggests to replace it with `cycleway=lane` is extremely opinionated and leads to less explicit and hence worse data.

`cycleway:<side>=lane` is more explicit and should thus be preferred. That having said, StreetComplete actually understands `cycleway=lane` and does not flag it as incorrect if it is tagged that way because both are correct.

**However**, `cycleway=lane` on oneway roads is ambiguous, as is the case for https://www.openstreetmap.org/way/40848257/history, because it is not clear whether with `cycleway=lane` it is meant that only in the flow direction there is a lane or also in contraflow direction, after all there is already `cycleway=opposite_lane` for that purpose. Which makes this osmose rule even worse because it turns explicit data into ambiguous data.

Comment from the code:

> For oneways, the naked "cycleway"-keys should be interpreted differently:
   E.g. a cycleway=lane in a oneway=yes probably means that only in the flow direction, there is a lane. E.g. cycleway=opposite_lane means that there is a lane in opposite traffic flow direction.
   Whether there is anything each in the other direction, is not defined, so we have to treat it that way.
