### ISSUE TITLE
Handle addr:substreet and addr:parentstreet as used in the UK in house street name quest

### ISSUE THREAD

**Issue by peternewman** [streetcomplete/StreetComplete#4483]
As detailed here, the UK now sometimes uses some alternative tags:
https://wiki.openstreetmap.org/wiki/Addresses_in_the_United_Kingdom#addr:substreet,_addr:street_&_addr:parentstreet

I should note I'm just a user here who only happened to notice due to a discrepancy around street names and not being able to select this street ( https://www.openstreetmap.org/way/37107064 ) as the name, which it turns out was because it didn't have a name set and that wasn't asked because it's only a service road.

**How to Reproduce**
Go to https://www.openstreetmap.org/way/230252827
Note how the street name quest is being asked for the building, despite substreet and parentstreet being set.

**Expected Behavior**
Don't ask if either addr:substreet or addr:parentstreet is already set.

**Versions affected**
SC v47.1

**Comment by peternewman** [comment]
The address overlay will need tweaking too...

**Comment by westnordost** [comment]
Uhm, i don't understand these tags

**Comment by westnordost** [comment]
So what to do for the address overlay then?

**Comment by peternewman** [comment]
I'm not sure, partly because I've not seen it yet because the release cadence combined with what feels like a bug in Google Play means its not offering me the higher numbered alpha release to update to.

What does it do about house names (rather than, or as well as numbers), or are they shown on the three dot menu?

I guess for editing existing ones, it should show two street fields if they're set (N.B. iD doesn't either currently), so as not to damage or misrepresent existing data, or it could just show the substreet, and change the label.

For adding new addresses, I guess either solution could work too, either a way to switch on the three dots (like house name hopefully has), or something else. If I'm honest, if I hadn't gone down this particular rabbit hole because the service road didn't have a name set, I wouldn't have known, so I'm not convinced your average punter will necessarily know if it's a sub street/whether you can tell onsite. So adding it as a street and then someone with more knowledge correcting that later doesn't seem terrible to me.

I think the main thing we want to avoid is us ending up with:
```
addr:housenumber: 29
addr:substreet: Acacia Avenue
addr:parentstreet: High Road
```

Becoming
```
addr:housenumber: 29
addr:substreet: Acacia Avenue
addr:street: Acacia Avenue
addr:parentstreet: High Road
```

Because people can't see that a substreet is already set.

To me an entirely missing address being added as:
```
addr:housenumber: 42
addr:street: Acacia Avenue
```

Isn't the worse thing in the world, as that bit needs the onsite survey to find where 42 is, whereas presumably you can correct the other bit using other remote data...?

**Comment by mnalis** [comment]
@peternewman so, did you have in mind simply skipping the `AddAddressStreet.kt` quest if `addr:substreet` or `addr:parentstreet` are present (e.g. like we currenty skip if `addr:block_number` is present), or were you aiming for something more complex?

https://github.com/streetcomplete/StreetComplete/blob/d215e40b2112fd2f803387a63e82f97a3f5a82ca/app/src/main/java/de/westnordost/streetcomplete/quests/address/AddAddressStreet.kt#L16-L20

**Comment by westnordost** [comment]
So I understand that at least in Great Britain, there can be "very local" roads (`addr:substreet`) that branch off from a normal road (`addr:street`) and the name of that very local road is not guaranteed to be unique within a city / postcode area and that is why it is necessary to also tag the parent street?
But then, why does (`addr:parentstreet`) exist? There's already (`addr:street`).

That tagging scheme doesn't make a lot of sense to me. Also, apparently `substreet` does often not describe a street, but a commercial estate? Uhm...

Anyway, I will close this issue for now as "not planned" because
1. it is not documented in `addr:*` wiki page
2. I don't want to support every country community brewing their own soup and coming up with their own tags here - certainly such an address (number X in business park Y) is nothing specific to the UK, so whoever wrote that "Addresses in the United Kingdom" wiki page shouldn't make it look like their situation (in the UK) is so special that they need an own tag which they do not need to put through the usual proposal process or other discussion in the international community
3. it is not interpreted by any software. E.g. Nominatim knows nothing of it. I suggest to create a ticket at Nominatim for this and/or ask the maintainer if there is already a correct way to give an address like "number X in business park Y" and similar

**Comment by peternewman** [comment]
There's a related page here which just talks about street and parentstreet:
https://wiki.openstreetmap.org/wiki/Proposed_features/Proposal_to_Document_the_Key_%22addr:parentstreet%22

I wonder if the logic might have been that because people have misused various combinations of place/street street/parentstreet etc, you need to start from a clean slate and hence new keys.

@sk53 might have some better ideas as this was cited too:
http://sk53-osm.blogspot.com/2020/06/housing-terraces-in-wales-minor.html

I appreciate note wanting to add stuff to the overlay and all the complexity that would involve, but could we at least avoid adding more tags if say substreet AND parentstreet are already set in the quest? So we don't end up with nodes with all three, which seems even more confusing!

I'm assuming the overlay doesn't support addr:block_number or addr:streetnumber either, which appear to be country specific tags (Japan and Czech Republic specifically).

**Comment by westnordost** [comment]
> I'm assuming the overlay doesn't support addr:block_number or addr:streetnumber either, which appear to be country specific tags (Japan and Czech Republic specifically).

You assume wrong

**Comment by mnalis** [comment]
To add some statistics for the rationale: [addr:parentstreet](https://taginfo.openstreetmap.org/keys/addr:parentstreet#overview) + [addr:substreet](https://taginfo.openstreetmap.org/keys/addr:substreet) combined are about `10k` uses.

(Other mentioned exceptions that we do handle are [addr:block_number](https://taginfo.openstreetmap.org/keys/addr:block_number) with about `142k` and [addr:streetnumber](https://wiki.openstreetmap.org/wiki/Key:addr:streetnumber) with almost a million uses. Those are order or two of magnitude more usage).

Still, `10k` uses is not negligible, so I myself wouldn't mind doing and testing a PR that skips the `AddAddressStreet quest` if either  `addr:substreet` or `addr:parentstreet` are already defined, as answering this quest there would likely only lead to more confusing data, instead of actually helping OSM. 

Would such PR be accepted?

**Comment by westnordost** [comment]
Ok, yes

**Comment by peternewman** [comment]
Thanks @mnalis !
