### ISSUE TITLE
Stop asking for wheelchair accessibility of car washes

### ISSUE THREAD

**Issue by lunarna-gh** [streetcomplete/StreetComplete#4491]
Currently if a car wash has a brand or name, StreetComplete asks for wheelchair accessibility. In self-service car washes you don't enter a building, and in automated car washes you usually don't have to exit your car, so at least after specifying the type of car wash, SC shouldn't ask for wheelchair accessibility. ![IMG_20221013_041432.jpg](https://user-images.githubusercontent.com/113068485/195485170-907261be-76ae-4f62-b756-e6c2bbdbfc6e.jpg)

**Comment by westnordost** [comment]
Hmm.... no, I won't change that.

The place where you have it washed may be wheelchair accessible by default, but that doesn't mean automatically that the entire place is wheelchair accessible: You may need to go inside to pay, and that place may then not be wheelchair accessible.

It's the same with fuel stations in general really. Of course the area where you fuel is wheelchair accessible (because it is car-accessible), but it does not automatically mean that the place where you pay is also.

**Comment by lunarna-gh** [comment]
Yeah that makes sense, I think it wouldn't be an issue for self-service car washes though, I don't think there are any that are paid inside buildings, they all have a machine you can insert coins into. I don't really know how to answer the quest for one near me right now, if I marked it as accessible it would be displayed on maps as something that specifically accommodates wheelchair users when it just happens to because it's not a building.

**Comment by lunarna-gh** [comment]
I mean, yes, but the tag assumes there is a way these could be inaccessible, which is why it is added to buildings but not to grass, just like why foot=designated is added to shared cycleways, but not sidewalks. Buildings which are built in a way that allows wheelchair users to comfortably use them are what I meant by accommodating, even if it's not on purpose, because there are many buildings aren't accessible.
I won't continue because I don't want to waste more of your time though, great work on the latest SC releases!<3
