### ISSUE TITLE
Building addresses asked incorrectly when in larger area with address until quest refresh

### ISSUE THREAD

**Issue by dbdean** [streetcomplete/StreetComplete#4493]
**How to Reproduce**
Answer a quest on a building without an address in a larger area with an address.

You will get a quest on the building asking the address of the building. To make it go away, you have to refresh the quests in the area.

Example (located at https://www.openstreetmap.org/#map=18/-30.52103/151.65133):

![image](https://user-images.githubusercontent.com/12725310/195489381-69439277-bb13-44f8-b31e-3b695ec85d4b.png)

**Expected Behavior**
The building address quest won't come up because the larger area already has an address tagged.

**Versions affected**
48.0-alpha (but has been happening for a while) on Android 11.

**Comment by westnordost** [comment]
This cannot be fixed. E.g. the enclosing area could be arbitrarily large, with no nodes within the downloaded bounding box. When an area has no nodes inside the downloaded bounding box, it is not downloaded. This is how the OSM API works. When that area is not present in the downloaded data, it can also of course not be taken into account.

The offline behavior of the app mirrors this behavior of the OSM API. In particular, the housenumber quest will look in a certain radius around the building for such areas. For this case, the radius chosen was not big enough to find the enclosing area (because no nodes of that enclosing area were inside the bbox around that building). But the radius must be fixed at **some** level, so no matter how big the radius, there will always be cases where this produces false-positives (cause those enclosing areas could be arbitrarily large). Obviously, choosing a bigger radius has performance implications. The current radius is just fine for most situations.

**Comment by dbdean** [comment]
If the offline behavior is the same as using the offline API, why does it go away when I rescan for quests?

**Comment by westnordost** [comment]
The bounding boxes are different.

The behavior regarding "if no node of a way is in the bounding box, the way will not be included" is the same.

The download may happen across a very large area, spanning several city blocks. When editing an element (offline), to check if any new quests have been unlocked, it only fetches the a bounding box of the immediate vicinity from the local database.

**Comment by riQQ** [comment]
Is the following issue caused by the same circumstances?
I solve an exit quest with any answer, undo this answer and the quest doesn't show up again. Only via 'Scan here's am I able to get the quest to appear again.

**Comment by westnordost** [comment]
What exit quest?

**Comment by riQQ** [comment]
Entrance / exit quest.

**Comment by westnordost** [comment]
The "What kind of building entrance is this?" from @matkoniecz ?

Actually, no, I don't think this should happen with that quest because it does not do any point in polygon checks. It only checks for which nodes belong to which ways and as any way that has at least one node in the bounding box is included, this should be fine.

**Comment by westnordost** [comment]
It should only be possible to happen for
- housenumber
- level of shop in mall etc.
- summit cross
- summit register
- sidewalk
- cycleway
