### ISSUE TITLE
Enable "Does this place take cash?" quest in the UK (GB)

### ISSUE THREAD

**Issue by TurnrDev** [streetcomplete/StreetComplete#4517]
Since COVID-19, it's not uncommon for places in the UK to only take card. I'd like to propose enabling this quest in the UK.

**Comment by TurnrDev** [comment]
I'm happy to make this change, but would this be accepted?

**Comment by mnalis** [comment]
Was there some discussion on OSM UK communication channels showing that it is somewhat widespread case (e.g. not just a few random shops in your neighborhood), or link to some news stories? 
I.e. something other than [anecdotal evidence](https://en.wikipedia.org/wiki/Anecdotal_evidence)?

Also, in your own experience, what is your guess of percentage of the shops in your town that no longer accept cash?
(e.g. `30%`? `10%`? `1%`? )

**Comment by matkoniecz** [comment]
Or maybe is there a growing count of shops mapped as not accepting cash in UK?

**Comment by matkoniecz** [comment]
> Or maybe there is some other tool that could be used to find out such trends?

Overpass api with queries limited to UK and with attic data (old osm data) being checked.

**Comment by TurnrDev** [comment]
I'll find out and come back here when I know

**Comment by matkoniecz** [comment]
@TurnrDev Let me know which tags should be checked if you get stuck, I have somewhere code for getting such statistics.

**Comment by TurnrDev** [comment]
> @TurnrDev Let me know which tags should be checked if you get stuck, I have somewhere code for getting such statistics.

Not got round to it yet but I assume it'll be `shop=*` & `cash=no` - I know places that are card only but haven't updated maps yet as I'm usually out and forget by the time I get home. I'll try update when I can

**Comment by mnalis** [comment]
(You probably mean `payment:cash=no` instead of `cash=no`?)

**Comment by TurnrDev** [comment]
Probably, yeah

**Comment by mnalis** [comment]
@matkoniecz perhaps look at:
-  P16 = `count("shop="+"payment:cash=no") / count("shop=*") * 100` in **2016/01** (i.e. percentage of "no cash"  in 2016)
-  P18 = `count("shop="+"payment:cash=no") / count("shop=*") * 100` in **2018/01** (i.e. percentage of "no cash"  in 2018)
-  P20 = `count("shop="+"payment:cash=no") / count("shop=*") * 100` in **2020/01** (i.e. percentage of "no cash"  in 2020)
-  P22 = `count("shop="+"payment:cash=no") / count("shop=*") * 100` in **2022/01** (i.e. percentage of "no cash"  in 2022)

and then compare `P18-P16` (2-year non-covid19 no-cash growth) with `P22-P20` (2-year covid19 no-cash growth)?

**Comment by mnalis** [comment]
I've also asked at [talk-gb](https://lists.openstreetmap.org/pipermail/talk-gb/2022-October/029523.html) for experiences, which might provide additional insight in addition to tag statistics.

**Comment by mnalis** [comment]
- related: https://github.com/streetcomplete/StreetComplete/issues/2647

**Comment by mnalis** [comment]
`talk-gb` **update**: 7 people responded in 8 comments on [talk-gb](https://lists.openstreetmap.org/pipermail/talk-gb/2022-October/029523.html) mailing list: general opinion seems to be that there are now indeed noticeably more stores (and even chains) that refuse cash, and while they are still a small minority, there were no objections to enable `cash quest` in `GB`. 

(There were some concern raised that one might have to enter the store to know the answer as it might not always be signed outside but only at the counter; but since we also additionally warn about that with `default_disabled_msg_go_inside` I do not think that would be a problem).

So my opinion would be that it is reasonable to **enable cash quest** in `GB` too in addition to `SE`, especially as even when geo-unlocked, the quest will be disabled by default anyway (so would not be spammy on unsuspecting users by default). 
(I don't know if @matkoniecz still wants to run the [stats](https://github.com/streetcomplete/StreetComplete/issues/4517#issuecomment-1281469255) [calculations](https://github.com/streetcomplete/StreetComplete/issues/4517#issuecomment-1282220828) or if it is perhaps not even needed...)

**Comment by westnordost** [comment]
Ok, I'll enable it then. Thank you @mnalis
