### ISSUE TITLE
Address mapping in v48.0-beta1

### ISSUE THREAD

**Issue by 501Ghost** [streetcomplete/StreetComplete#4527]
I was looking at https://github.com/streetcomplete/StreetComplete/releases/tag/v48.0-beta1 and I noticed that it said "You can add addresses to buildings". This would not be helpful in the Netherlands because there is an actively maintained address node import in place from government sources (specifically the BAG). I request that users are not asked to add addresses to buildings in NL.

See also https://github.com/Zverik/every_door/issues/325 for the same question I asked at Every Door.

**Comment by westnordost** [comment]
> I request that users are not asked to add addresses to buildings in NL.

They are not asked to add addresses to buildings in NL. Other than quests, overlays do not ask the user anything. They merely provide the ability to add such data.

You can also add addresses to buildings in JOSM in the Netherlands.

**Comment by 501Ghost** [comment]
> Other than quests, overlays do not ask the user anything. They merely provide the ability to add such data.
This is totally redundant and I request that this gets and stays disabled.

> You can also add addresses to buildings in JOSM in the Netherlands.
Yes, and then other mappers like me have to clean up those duplicates. There is no reason to give people new abilities to map addresses on buildings in NL.

**Comment by westnordost** [comment]
It is staying disabled. The quest is disabled in the Netherlands.

So you are cleaning up (duplicate) house numbers created with JOSM and iD etc. in the Netherlands. But why did those people add addresses in the first place when nothing was missing?

**Comment by 501Ghost** [comment]
> It is staying disabled. The quest is disabled in the Netherlands.

Great :)

> why did those people add addresses in the first place when nothing was missing?

To map POIs, which in accordance with Dutch mapping guidelines should (nearly) all be mapped on the address nodes.

**Comment by westnordost** [comment]
Hm, so according to Dutch mapping guidelines, all addresses should be on nodes.

Am I correct to assume that according to these guidelines..:
- that these nodes are free-floating nodes within the building outline
- `entrance=main` etc. does thus NOT get a housenumber because there is already that other imported free-floating address node and that would be duplicate
- POIs such as hairdressers within the same building outline as the imported free-floating address node also do not get a housenumber because they too would be considered duplicate

...and that the latter points require continuous clean up because people are adding housenumbers on POIs (and entrances) because in popular editors, at least iD, there are fields for that so people tend to fill these out?

**Comment by 501Ghost** [comment]
> These nodes are free-floating nodes within the building outline

Yes. Each address has its own node within the building outline. No address ranges, no cases of multiple addresses on single objects, just all separate nodes.

> `entrance=main` etc. does thus NOT get a housenumber because there is already that other imported free-floating address node and that would be duplicate

That is indeed the case. Personally I tend to move the address nodes somewhere close to the building entrances, but that's as far as most Dutch mappers go with this practice. We don't put addresses on entrances.

> POIs such as hairdressers within the same building outline as the imported free-floating address node also do not get a housenumber because they too would be considered duplicate

Ideally they should be mapped on the existing address node, so when you search the address you find the hairdresser and vice versa. 

If multiple POIs are on the same address, it's generally considered good practice to duplicate the address for that reason. See for example these three doctor's offices I've mapped: [10111544467](https://www.openstreetmap.org/node/10111544467) / [10111544466](https://www.openstreetmap.org/node/10111544466) / [3012962502](https://www.openstreetmap.org/node/3012962502)

> The latter points require continuous clean up because people are adding housenumbers on POIs (and entrances) because in popular editors, at least iD, there are fields for that so people tend to fill these out?

Indeed. For example yesterday I was cleaning up some hardware stores that were mapped on the buildings, and I've also done various cleanups where shops were mapped on new nodes and I had to merge them with pre-existing address nodes.

**Comment by westnordost** [comment]
So, the "address on POIs" is not causing continuous clean-up because it is accepted that the address is duplicated on different POIs at the same housenumber? The only issue is that some people add the housenumber to buildings (or areas)?

**Comment by 501Ghost** [comment]
> So, the "address on POIs" is not causing continuous clean-up because it is accepted that the address is duplicated on different POIs at the same housenumber?

Indeed. It's the opposite what causes continuous clean-up: POIs without address tags.
Moreover, when someone maps a new POI node _with_ address tags and leaves the pre-existing address node untouched, the address would be unnecessarily duplicated, so adding POIs to existing nodes is highly preferable.

> What about shops that are areas?

Most or all brick-and-mortar shops are registered at an address. Mapping them as areas is sometimes done (see [Taginfo](https://taginfo.geofabrik.de/europe/netherlands/keys/shop)), but as the statistics show this is not the preferred way.

As I showed in the example with the doctor's offices, the address of a POI is not necessarily unique; sometimes multiple POIs share the same address, usually within the same building.

Another problem arises when someone removes an outdated POI: usually people remove it completely. This also removes the address information. This is an issue because unless the building is taken down along with the POI or the address changes officially, the node with address tags should remain behind when a POI disappears.

**Comment by westnordost** [comment]
Hm, that sounds really complicated and difficult to convey to (new) mappers. Do you really think that maintaining this after the initial import of housenumbers is worth it?

Anyway, I was going to say that I'll look into at least disabling the ability to map housenumbers on buildings from that address overlay because that is not the encouraged mapping practice in Netherlands.
But then again, I turned around and thought that mapping **any** addresses is not the encouraged mapping practice in Netherlands, because they are all imported. So, actually, the address overlay should be disabled altogether. But unlike quests, it is not possible to disable overlays for specific countries.
And I do not think this is a big issue. If all the addresses are already on the map in the Netherlands, noone is going to get the idea to add addresses (because they are already there), hence noone is going to activate that overlay to add addresses. **Except** in cases where an address is actually missing from the import, in which case I'd say adding it is not an error.

In any case, I think the existence of the address overlay is much less of an issue than iD (and other editors?) displaying the address input field on every building (and every POI)

![image](https://user-images.githubusercontent.com/4661658/197009198-09aa8f72-6a20-4e3f-94f2-e0eb73d5595e.png)

which I gather is rather the source of most addresses "incorrectly"/in duplicate added to buildings.
