### ISSUE TITLE
Parking access quest asked for HGV-only parking lots

### ISSUE THREAD

**Issue by tapetis** [streetcomplete/StreetComplete#4538]
In Germany (and probably many other countries) it is possible to specify which vehicles may be parked in a parking lot or on the side of the road. An additional sign (e.g. Zusatzzeichen 1010-51 for HGVs) can be attached to the parking sign (Zeichen 314) for this purpose (see [this](https://www.stvo2go.de/verkehrszeichen-parken-zusatzzeichen/) description in German for more details).

In OSM, many HGV parking spaces are currently tagged as just `amenity=parking` and `hgv=designated`. It can be argued that one should also tag `access=no` or `motor_vehicle=no` to make it clearer that only trucks may park there (see [here](https://wiki.openstreetmap.org/wiki/DE_talk:Tag:amenity%3Dparking#LKW_Parkplatz) and [here](https://forum.openstreetmap.org/viewtopic.php?id=68542)). However, this is often not the case. The same problem exists with bus parking, for example.

When there is no `access` tag, StreetComplete ask the user "Who is allowed to park here?" and in most cases adds the `access=yes` tags to these parking areas. Afterwards, the area has wrong tags and is displayed as if cars are also allowed to park there as specified by the [access hierarchy](https://wiki.openstreetmap.org/wiki/Key:access#Land-based_transportation).

Here are some `amenity=parking` that were previously only tagged as `hgv=designated`, which now also have `access=yes` tagged by StreetComplete:

- https://www.openstreetmap.org/way/353163903/history ([Mapillary](https://www.mapillary.com/app/?pKey=589521965364323)),
- https://www.openstreetmap.org/way/493334668/history ([Mapillary](https://www.mapillary.com/app/?pKey=564130354549717)), and
- ~~https://www.openstreetmap.org/way/294331631/history ([Mapillary](https://www.mapillary.com/app/?pKey=299076235049840))~~.

As can be seen from the Mapillary links, the first two linked parking lots are more or less clearly designated as truck parking. More ways like this can be found easily using [overpass](https://overpass-turbo.eu/s/1mWn).

I think the app should handle these truck parking lots that are tagged only as `hgv=designated` better. A straightforward solution would be to simply not display the `AddParkingAccess` quest for such parking lots. Another solution would be for the quest to allow the user to specify that only certain types of vehicles are allowed to park, rather than only adding the general `access` tag.

**Comment by westnordost** [comment]
Hm, I am not sure if `hgv=designated` should be interpreted as that cars may not park there. Something could very well be designated for HGV but not prohibited for other motor vehicles. A special HGV lane on some highway does not necessarily need to be prohibited for others, just, others may not want to drive there. The same with parkings - I am not sure but are those HGV parkings at rest areas at German motorways even HGV only? Well, if they are, in other countries the legislation might just as well be different.

https://wiki.openstreetmap.org/wiki/Tag%3Aamenity%3Dparking mentions nothing about this. https://wiki.openstreetmap.org/wiki/Key:hgv#Tagging_examples specifically lists `access=no + hgv=designated` for how to tag HGV-only lanes

So, software support for this interpretation of this tag value is likely zero. Hence, I'd argue that not the adding of `access=yes` is adding wrong tags, but already the assumption that from `hgv=designated`, `motor_vehicle=no` is inferred.

**Comment by mnalis** [comment]
I agree that if only access tag is `hgv=designated` that it says **nothing** of access of other vehicles. `access=no` or `motor_vehicle=no` should be added ***in addition*** to `hgv=designated` if one wants to indicate that other non-HGV vehicles are prohibited from using that parking; as wiki states. So that part or the problem is _tagging omission from original mapper_. It is not _wrong_, but it does not say that other vehicles are prohibited (which they may or may not be), which would be very useful information.

However, the StreetComplete quest does seem to _**ask in a way that does not mention different types of vehicles at all**_.
Which could easily lead to mappers giving wrong answers on that quest in vehicle-type-restricted parkings.

Perhaps it would be easiest to have the `AddParkingAccess` quest skip all parkings which already have mapped any of the [more granular access types](https://wiki.openstreetmap.org/wiki/Key:access#Land-based_transportation) like `vehicle`, `caravan`, `hgv`, `coach` etc. (as adding `access=yes` to those would probably only lead to confusion and problems as noted), as that would avoid SC misleading users in cases `hgv=*` and similar are mapped.
I could do PR for that if that whould be an acceptable solution.

Alternatively, we might try to explain it the quest text (and translations), but that would probably get too long.

**Comment by westnordost** [comment]
Hm, all good points and thank you for the links. But I'd also add that if for parkings for which a more granular access tag is already set, the general `access=*` is never tagged which leaves the parking in an incomplete state that will not be interpreted correctly by data consumers.

The ideal solution would be if the UI was designed in a way that users would select to leave a note or similar in such a case. 

The current wording is _"Who is allowed to park here? Parking may be free or paid."_
As far as the question is concerned, it sounds correct already. E.g. the answer could be "only trucks may park here". So maybe the answer options are the problem that cause the misunderstanding, because nothing "by vehicle type" is mentioned. 
Question is, would a fourth answer option named something like "Others (Leave note)" solve this?

In any case, both the situation that there is an incomplete access tagging (e.g. only a positive `hgv=yes` but no negative thing one level up - `access=no` or similar) and the situation that there are seemingly superfluous positive access tagging (`hgv=yes` and `access=yes`) can be found automatically, so solving this could be an Osmosis error/warning or a StreetComplete quest or both.

So I guess, if you find my suggestion to add a fourth answer option not sufficient to solve the misunderstanding, then @mnalis suggestion seems to be the best way to go. Would need to revisit the other parking quests too, maybe some should also not be asked.

**Comment by mnalis** [comment]
I guess the additional answer _might_ perhaps also work, provided:

- it is more descriptive, e.g. `Only some vehicle types (Leave note)`.
  Just `Other (Leave note)` sound much too confusing and not likely to help IMHO.
- it is put at **_first place_** in the list of answers (as otherwise I'm afraid people will click on first answer that matches, which is likely `Any member of the general public`).

But even with that, it might _still_ be confusing, as we would basically _ask about two different things with same answer_ (`what types of vehicles` and `people with what permit`), so multiple answers can be true at the same time (e.g. `Any member of the general public` and `Only some vehicle types` can be true at the same time). 

---

Another possible alternative might be **_additional_** multi-choice parking quest, which would ask specifically about `What vehicle types may park here? (select all that apply)` (done in the manner similar to `recycling quest`) that would tag **both** `access` **and** one or more _more specific access tags_ (like `hgv`, `coach`, ...), and have higher priority than the current `AddParkingAccess` quest.

However that new quest:

- would be too spammy to be asked generally on parkings, so should be asked only on parkings which already have some specific access tag (like `hgv=yes`) but **no** general `access=*`
- might have lot of answers and pictures, so probably only few most popular should be given as answers and have `other (leave note)` for rest of them.

The disadvantage is that it would be more work to implement, and is an _additional_ parking quest, but the advantage is that it would actually help fix incomplete (or incorrect) data in such cases (instead of just ignoring the parking in order to not make situation even worse, as in my [first suggestion](https://github.com/streetcomplete/StreetComplete/issues/4538#issuecomment-1287563923))

**Comment by mnalis** [comment]
Yeah, scratch that idea about separate quest. It would simply replace current failure mode with another one (not just the situation you menition, but also what if some parking space is for example for `coach=yes` but `with permit only`.

**Comment by westnordost** [comment]
So, it sounds like the best solution right now would be to not ask if any access tags are set. You would create a PR for this, @mnalis ?
