### ISSUE TITLE
Defaults: Ask building height/levels and roof type before number

### ISSUE THREAD

**Issue by hamishmb** [streetcomplete/StreetComplete#4558]
**Use case**
I often add data to OSM while travelling as a passenger. For this use case, I can almost never match house number to what I see on the map quickly enough, but I often can do building heights and roof types.

For those on foot, being asked the questions in this order shouldn't make any meaningful difference, I think.

**Proposed Solution**
Ask for the height/levels and roof type first.

**Comment by hamishmb** [comment]
That's exactly what I did - I'm proposing changing the default

**Comment by westnordost** [comment]
Hmm, while building levels and especially roof type may often easily be seen from afar (e.g. in suburbs), in many cases it may actually be very difficult to answer or not answerable at all: For high buildings in a (narrow) street, you can't really see the roof.

So, if these quests are sorted in front of the housenumber, your inability to solve the quest right now (without walking away a good distance so that you can maybe see the roof) blocks your ability to solve the housenumber quest. The housenumber quest, unlike those mentioned above, should always be solvable.

**Comment by hamishmb** [comment]
That's a good point.

Perhaps we could add some default presets instead then?

**Comment by westnordost** [comment]
I fear adding more default presets would be a barrel without bottom. There have been many tickets about this before, without result, because everyone seems to have a different idea what default presets there should be and what should be in it. I'm sorry, I can't find the last ticket about this now, maybe it has been closed.

**Comment by Helium314** [comment]
I think that was the more or less same thing we already had before presets were implemented: what can the user solve (on foot / bicycle / car / train...) vs what does the user want to solve (focus on bicycle / car / accessibility...)

**Comment by mnalis** [comment]
- one of the relatively recent issues was https://github.com/streetcomplete/StreetComplete/issues/3981
- but yeah, there are conflicting wishes. Some people (like me :smiley:) don't really care about _mostly useless_ map information like `roof types` _at all_, but find `address` information **_extremely valuable_**. So **GOOD** default profile in my opinion would be to get rid of roof types by default at all, **_instead_** of making them the priority. Obviously, it is unlikely to reconcile the sides here.
- Luckily, with the inclusion of https://github.com/streetcomplete/StreetComplete/pull/4537 in next major version, **everyone** can publish their own **"best profile"** and lobby people to use that one! (to paraphrase popular [quote](http://www.quotationspage.com/quote/473.html) about standards: _"the best thing about **defaults** is that there are so many of them to choose from!"_)

**Comment by mnalis** [comment]
> I often add data to OSM while travelling as a passenger. For this use case, I can almost never match house number to what I see on the map quickly enough, but I often can do building heights and roof types.

So make a preset for traveling in a car/bus/train which has deselected/deprioritezed quests you're unlikely to be able to solve. I do. It solves exactly that problem. When #4537 goes live, I'll even be able to share it with you :heart: !
 
> For those on foot, being asked the questions in this order shouldn't make any meaningful difference, I think.

But it does, and **hugely**. I prefer to solve quests which contribute _actually useful_ information to the openstreetmap. If _<strike>worthless</strike>less useful_ quest have priority, I **won't have time** (without stopping and wasting time, which I'd absolutely want to avoid) to solve **_important quests_** (as I would have used that precious time on previous non-important quests!) 

Note that it seems that **users on foot** are [first-class citizens in SC](https://github.com/streetcomplete/StreetComplete/pull/4188) and considerations of mappers using all other types of transport come second.

**Comment by hamishmb** [comment]
I think that's all very reasonable. I think #4537 renders this question completely irrelevant. I'll be happy to share my configs once that is in a stable release.
