### ISSUE TITLE
Close overlay form when overlay is deactivated

### ISSUE THREAD

**Issue by Tatfahren** [streetcomplete/StreetComplete#4559]
**How to Reproduce**

Activate housenumber overlay ---> click on a building or   
node ---> click at empty to discard like on other overlays  

or  ---> disable all overlays ---> click on empty

Get out with using another overlay or restart the App.

https://youtube.com/shorts/hhVTqkKWmi0?feature=share

**Expected Behavior**

I think it should close the task, because you can't add a new number without an existing build then or do the normal task's.

**Versions affected**
SC: v48.0 with Google Play
Android: 11 RKQ1 200826.002
(MIUI): 12.5.5.0

I'm sorry for my "bad" English, if you can't understand something I'm happy to help you.

**Comment by Helium314** [comment]
Actually you should have the same issue for the road name quest, is this correct?
I can only recommend to use the back button for closing the form. Tapping the map does not help because from within the form you need to be able to interacti with the map.

Though the form should probably close when opening the menu, or at least when disabling the overlay.

**Comment by Tatfahren** [comment]
Sorry, i forgot to use the back button of my device, because in all the other overlays and quests it work with clicking on an empty part of the map like a meadow or a field. If i double click the back Button the app closes, thats e i still think that it should close if i select none overlay?

**Comment by mnalis** [comment]
I'll reopen this, as disabling the overlay (setting it to `None`) IMHO should really close the forms open by previously active overlay.
