### ISSUE TITLE
Czechia showing up in my overview for no reason

### ISSUE THREAD

**Issue by TFox42** [streetcomplete/StreetComplete#4568]
It shows czechia in my profile, despite me never having edited something in that country, let alone 72 edits.![image](https://user-images.githubusercontent.com/53448898/198851070-965a28d1-3676-4845-bfc5-86d2927ee140.png)

**Comment by legofahrrad** [comment]
What's your OpenStreetMap username?

AFAIK the app counts the edits from one changeset to the country, that is in the center of the changeset's bbox.

**Comment by TFox42** [comment]
EngineerFox
> What's your OpenStreetMap username?
> 
> 
> 
> AFAIK the app counts the edits from one changeset to the country, that is in the center of the changeset's bbox.

**Comment by Helium314** [comment]
> AFAIK the app counts the edits from one changeset to the country, that is in the center of the changeset's bbox.

Yes, that's the reason. See also #2987

**Comment by legofahrrad** [comment]
Okay, but I can't find any changeset where the center is in Czech Republic, only [this](https://www.openstreetmap.org/changeset/128220359) and [this](https://www.openstreetmap.org/changeset/128220108) changeset are older than the issue and overlapping with Czech Republic a bit...

**Comment by westnordost** [comment]
The following changesets have been classified as being in Czech Republic:
128220108
128220359
128233258
128233261
128233679

**Comment by mnalis** [comment]
(likely related to problem with big bbox in changesets, i.e. not uploading before trip to another country? 
E.g. https://github.com/streetcomplete/StreetComplete/issues/3640, FAQ [A changeset made with StreetComplete covers a massive area, why is this? How can it be prevented?](https://wiki.openstreetmap.org/wiki/StreetComplete/FAQ#A_changeset_made_with_StreetComplete_covers_a_massive_area,_why_is_this?_How_can_it_be_prevented?))

**Comment by mnalis** [comment]
While finding Czechia as country of origin is not ideal, one should note that _finding a better center_ of the changeset bbox **_wouldn't really improve situation generally_** (it might in this case as Germany happens to be a center of 5 countries caught in the bbox, and it is one of the countries where edits were made, but it could as easily be totally wrong too.

Since we don't seem to want to split changesets having huge bboxes (see linked issues in previous comment),  what might help is using coordinates of (say) the first modified element in that changeset (instead of some changeset bbox calculations which might be going on - I have no idea of current logic). 

That would at least in majority of the cases make one of the countries that were involved in editing as being counted (instead of some unrelated country that happens to be in the middle). (it still wouldn't be perfect: one might have been at the border and tagged a long road which crosses the countries without being split; but I'd guess that at least would happen much less often than current situation).

On the other hand, I seem to recall some of the argumentation in previous tickets that it is actually **_preferred to confuse the mapper_** who uses such big bboxes, as it very often **indicates user error** (either user not-really-using-sc-on-the-ground as they should, or user not-uploading-data-for-long-time which is also bad practice), and we actually do prefer such users being notified by other mappers (or themselves notifying it) and thus correcting their behaviour.

**Comment by westnordost** [comment]
Okay, I actually found a bug: The "center" position of every changeset was actually wrongly the outer most eastern position.

**Comment by westnordost** [comment]
So what I'll do now is to throw away the whole database and let it be aggregated anew. This will take a while, in which there will be no statistics syncs possible

**Comment by westnordost** [comment]
The re-populating is done bit by bit (a cron job that runs for 5 minutes every hour). Re-populating is about 1% done now, so it looks like the whole thing will take a bit more than a month.

**Comment by matkoniecz** [comment]
I wonder is it likely that it first processed users with large amount of edits so later processing will be faster

**Comment by westnordost** [comment]
No

**Comment by westnordost** [comment]
But opening the app with yourself logged in also triggers a sync for yourself which runs a few seconds but then gives up if it can not teturn an up to date result within a few seconds.
Hence,  active users who use the app often will more quickly get to a state where their stats are up to date again

**Comment by chau-intl** [comment]
I also have Czechia showing up on my profile with 57 edits and I sadly haven't been in the country for more than 10 years. I don't remember when it appeared in my profile, but I guess the rebuild mentioned above didn't fix it for me?

**Comment by mnalis** [comment]
@chau-intl note that rebuild does not fix the core of the issue, i.e. if you have multiple countries in same changeset (see e.g. https://github.com/streetcomplete/StreetComplete/issues/4568#issuecomment-1296164092 and https://github.com/streetcomplete/StreetComplete/issues/2987#issuecomment-865004934).

In other words, it is still expected that if you e.g. mapped in Finland but not uploaded changes, and then traveled to Namibia and mapped there, that your changes would get get attributed to neither Finland nor Namibia, but somewhere around Greece instead. Trying to address that would be too hard / problematic to do (see linked issues for details).


So the rebuild only fixes how the actual center of the changeset is calculated (previously it used eastern side of the changeset, instead of middle point between east and west sides of a changeset bbox).

---

Thus, the only "solution" to not have not-visited-countries wrongly attributed is to make sure your previous changes are uploaded _**before**_ you travel to another country, so no multiple countries ever end up in the same changeset.

**Comment by chau-intl** [comment]
@mnalis, I have looked at my commit history and there is a single commit in Kosovo, which wasn't uploaded before I got back to Denmark, and that puts the center of the BBOX nicely inside the Czech Republic. I guess looking through each commit to determine where each change took place would require too many resources, but it would give the correct result though. I'll try to enjoy my free Czechia badge :)
