### ISSUE TITLE
CheckExistence-Quest: Add highway=speed_camera to quest selection

### ISSUE THREAD

**Issue by mcliquid** [streetcomplete/StreetComplete#4576]
I've noticed some speed cameras in my area that don't even exist in real life (anymore).

Would it be an idea to add speed cameras (`highway=speed_camera`) to the quest? Or would a "doesn't exist" be problematic with the relations that might exist?

**Comment by westnordost** [comment]
Aren't such cameras often camouflaged in a way that they don't look like speed cameras, e.g. some innocent box somewhere that could just as well be a street cabinet?

**Comment by mnalis** [comment]
Not being a car driver, I'm no expert at the subject _at all_ (so I myself wouldn't be able to confirm or not *any* speed camera unless someone tutored me beforehand, _or_ there was always a big sign saying _"this is a speed camera" - which only rarely happens here e.g. when they have special huge display telling you the speed with which you drove there in order to be preventive rather then punitive)...

But I'm told that few years ago in Croatia a big push was realized for new model of speed cameras, which are more stealthy (and with much more features) than previous ones (e.g. https://www.antenazadar.hr/clanak/2019/10/u-hrvatskoj-postavljeno-na-stotine-nadzornih-kamera-nove-generacije-doznajte-njihove-lokacije/).

**Comment by peternewman** [comment]
> Aren't such cameras often camouflaged in a way that they don't look like speed cameras, e.g. some innocent box somewhere that could just as well be a street cabinet?

Not in the UK, bright yellow box and not allowed to be hidden by trees/bushes:
https://www.confused.com/car-insurance/guides/speeding-law-faqs#10

**Comment by matkoniecz** [comment]
At least some `highway=speed_camera` are deliberately hidden

![screen02](https://user-images.githubusercontent.com/899988/199002429-16f55941-8fd4-40b3-9b7a-88540524c6f4.png)

**Comment by westnordost** [comment]
Closing because not easily surveyable by non-experts. I.e. speed cameras may be deleted on the ground that the surveyor simply doesn't find them or doesn't know what to look for.

**Comment by matkoniecz** [comment]
@peternewman OK, maybe that specific case is completely bogus. But there were some well camouflaged permanent ones in Poland (including ones that I have seen myself), later they banned camouflage and now I think it is permitted again.
