### ISSUE TITLE
Plots not appearing in address overlay

### ISSUE THREAD

**Issue by vnmabus** [streetcomplete/StreetComplete#4577]
**How to Reproduce**
Plots don't appear in the address overlay.

**Expected Behavior**
 In some places, for example in some Spanish villages, addresses are assigned to the plot (https://wiki.openstreetmap.org/wiki/Tag:place%3Dplot) and not to the buildings. Thus, it would be useful for plots to be shown in address overlay and to be able to set address information for them.

Related: #3162

**Versions affected**
v48.0

**Comment by rhhsm** [comment]
This is also common in Bulgaria, but plots are not mapped (the wiki is not encouraging this) so I usually attach the same address to all inhabitable buildings on the plot. Isn't that a good work-around?

**Comment by mnalis** [comment]
(I guess the same issue applies to `housenumber quest` too, and not only to `address overlay`?)

However, looking at the [place=plot](https://wiki.openstreetmap.org/wiki/Tag:place=plot) wiki, I do not see [addr:*](https://wiki.openstreetmap.org/wiki/Key:addr:*) tagging mentioned at that wiki at all, only about mapping `name=*`? 
Nor does  [addr:*](https://wiki.openstreetmap.org/wiki/Key:addr:*) wiki seem to mention  [place=plot](https://wiki.openstreetmap.org/wiki/Tag:place=plot). 

Is such behaviour (tagging `addr:housenumber`, `addr:street` etc. on `place=plot`) documented anywhere?

In fact, `place=plot` specifically mentions that `they do not necessarily match cadastral records` (e.g. one `place=plot` may span several addresses, or several `place=plot` may have same address if I understand it correctly)

**Comment by westnordost** [comment]
Hmm, only less than 2% of plots have addr:housenumber tagged and the wiki does not mention this. I'd tend to not support this.

Do you have an example of a plot with an address? I'd like to know how e.g. Nominatim handles this. Is this common tagging practice anywhere?

**Comment by westnordost** [comment]
For now, I decided to not include this. Reasons:
1. only less than 2% of plots have addr:housenumber tagged and the wiki does not mention this
2. Plots and any other area-features (like schools, hospitals, industrial grounds, ....) that **could** have housenumbers are also not shown and editable in the address overlay. They are not editable because they are not shown: You wouldn't tentatively tap on same invisible area just to probe if there is some area where the housenumber could be added to. And areas that **could** have housenumbers tagged are not shown because the number of areas that could have housenumbers are countless, one would probably end up with a really long and ever-growing list of areas to show, making it an absolute mess to display
3. Also, housenumbers, as surveyed on the ground, are always at some specific location. You'll never see a housenumber with the disclaimer "actually the whole fenced area here is housenumber 123" but just the housenumber, sticking to a gate, postbox or entrance. So when on a survey, it is much better and more precise to map the housenumber at its actual location, not on the area. It is also fine to stick the housenumber to the building, but only because for most buildings, it is true that they have exactly one housenumber (and one entrance).

**Comment by vnmabus** [comment]
Well, in the particular village I was mapping every plot is walled (so you can check the bounds without using the cadastre) and has its own address (even if it has no building yet). Inside the plot could be 0, 1 or even more buildings (e.g. the house and a garage or a barbecue), all corresponding to the same address. Each plot can have more than one entrance (typically one for cars and other for humans, but sometimes also one in the back), all with the same address. I would rather not map the individual entrances, at least at first.

Given these constraints, for me adding the address to the plot was the natural thing to do. I would like to have support for it in OSM, but I understand that maybe it is not common enough yet for that.

Maybe a possible solution in the future would be the possibility to personalize the list of objects shown in the address overlay to cater for the particular  needs of everyone.
