### ISSUE TITLE
Confusing highlighting on some selected tasks

### ISSUE THREAD

**Issue by sw-fox** [streetcomplete/StreetComplete#4578]
When one selects some task the highlighting seems sometimes to be wrong. 
For example, if I select a Task for opening hours, some buildings beside the shop are also highlighted. Same for some house number. The other selected houses have already a number.
(Please see atached screenshots)

**How to Reproduce**
I don't know when this happens. I just observed this behaviour yesterday three to four times when I tried the new update v48.0.

**Expected Behavior**
My expectation is that only the affected building is highlighted.

**Versions affected**
It seems to be a new bug in v48.0

![IMG_20221031_105727_145](https://user-images.githubusercontent.com/56607198/198981779-8d4926f8-fc07-48a4-8d31-21360f317cdf.jpg)
![IMG_20221031_105723_716](https://user-images.githubusercontent.com/56607198/198981785-40ddb219-9d83-4970-bcff-73d02bcad31f.jpg)

**Comment by FloEdelmann** [comment]
See https://wiki.openstreetmap.org/wiki/StreetComplete/FAQ#When_I_click_on_quest,_several_similar_icons_pop_up,_why?

**Comment by sw-fox** [comment]
If I understand your link and the feature #3480 correct, only tasks of the same type shound be highlighted? On the second screenshot you can see that the other buildings have already a house number. I also checked the other task and there is no similar task for opening hours on the other buildings.

**Comment by mnalis** [comment]
> only tasks of the same type should be highlighted

Well... mostly yes. It is up for the quest itself to define it, and some quests stray a little from that rule in order to be more helpful (e.g.  quest for compressed air will also show nearby fuel stations, or somewhat similar types like shops+cafes+restaurants+offices might be bundled in the same category which gets used for all of them)

> On the second screenshot you can see that the other buildings have already a house number

Yes. So the intention is that you can **_more easily identify/position the current quest_** (small building marked in **orange** color), as the small building between _"helper"_ buildings `24` and `28` (marked in **pink** color).
In your specific screenshot there is only that one small building, so you probably don't need help for locating it, but in other cases there can be for example several small buildings, between different but similarly-looking bigger buildings, and your GPS precision in the city can easily be off by 10 meters or so, so without checking that one is answering for correct building, one might likely be giving wrong answers unknowingly! 

So, those "helper" buildings/amenities are shown so you can doublecheck you're giving answer for _**correct**_ building/amenity (and not nearby similar-looking one).
 
> I also checked the other task and there is no similar task for opening hours on the other buildings

See above - it is likely in the same category with others. So, they might already have `opening_hours` mapped (so the quest wouldn't be shown to you), or they might be of the type that SC won't ask for `opening_hours`. Still, they are useful for positioning and making sure you are answering quest for right amenity (e.g. exactly one to the right of `Jagdschule Apt` if you're standing on `Friedrich-List-Straße`)

---

While the confusion is still fresh in your mind @sw-fox, could you help us by giving us your suggestion how to improve the wording at [in that FAQ question](https://wiki.openstreetmap.org/wiki/StreetComplete/FAQ#When_I_click_on_quest,_several_similar_icons_pop_up,_why?) so it would more clear? It would be much appreciated!

(BTW @FloEdelmann , _GitHub often breaks the pasted URLs_ if they contain any characters but alphanumerics, so one has to use "chain link" icon to paste them correctly, like I did above)

**Comment by sw-fox** [comment]
If this is an intended behaviour this bug can be closed, but I find it very counterintuitive that when I select the opening hour question the buildings next door are marked. I can understand if this happens with stores in the same building, but I personally check the stores name in the question against the name on the door. But if another building is marked I got a little confused.

**Comment by matkoniecz** [comment]
> If this is an intended behaviour this bug can be closed

Sorry that it is confusing in this case :(

> But if another building is marked I got a little confused.

That is one more bad consequence of merging shop and building into one object, rather than marking this two elements as two separate OSM elements
