### ISSUE TITLE
Address overlay: Buildings without addresses

### ISSUE THREAD

**Issue by westnordost** [streetcomplete/StreetComplete#4583]
> When selecting a building without an address in the overlay, and then tapping "no address here" in the three-dots-menu, SC does nothing (because there is no address to remove) but shows one edit to upload (auto-upload off).
> 
> Should I open a new issue for that?

_Originally posted by @legofahrrad in https://github.com/streetcomplete/StreetComplete/issues/4446#issuecomment-1279901769_

**Comment by westnordost** [comment]
> **My suggestion:** When selecting a building without an address in the overlay, and then tapping "no address here" in the three-dots-menu, SC should add `noaddress=yes` or `nohousenumber=yes`. For those buildings without an address, SC should give a hint that somebody tagged the building as having no address and thus not show any fields for street or housenumber.
>
> When users try to add `noaddress=yes` to any building types such as garages or sheds which are likely to have no address at all, there should come a warning, that `noaddress=yes` is intended for those buildings that are likely to have an address but actually don't have one.
>
> ---
>
> In the current version, `nohousenumber=yes` gets just ignored, so if somebody tagged `nohousenumber=yes` (by mistake) on a building and then somebody else using SC address overlay adds the real housenumber, `nohousenumber=yes` stays, which should actually be removed when adding the housenumber.

**Comment by westnordost** [comment]
So that nothing happens when selecting "no address here" is definitely a bug.

Regarding the suggestion, not sure. What is the use case for that? I.e. why would a user that is contributing addresses this way explicitly state that some building does not have an address? The `nohousenumber` stuff is mostly only useful for the housenumber quest, not so much the overlay. Also, regarding your proposed solution, this kind of breaks with `building=yes` because that could either be a garage or a house.

**Comment by matkoniecz** [comment]
Maybe in overlay mode just do not show this option? (if that is reasonably achievable)

**Comment by westnordost** [comment]
@legofahrrad ping

**Comment by legofahrrad** [comment]
It would be useful to have the ability to tag a building which is likely to have an address (house, apartment building, office building etc.) as `noaddress=yes` if it has no address. Otherwise after adding housenumbers with the overlay the housenumber quests will only remain on the buildings that don‘t have a housenumber. The answer for these will be spammy then, as it is always “has no housenumber“.
Additionally, if `noaddress=yes` is not tagged, somebody could think data is missing.
The option to tag `noaddress=yes` should be only available for buildings that are likely to have an address, as already stated above. For other building types don’t show the option.

---

(I’m not sure whether `noaddress` or `nohousenumber` should be used)

**Comment by westnordost** [comment]
So, I implemented that `noaddress=yes` is added when the user answers "no address here", but only on areas (=buildings, plots etc.), i.e. not on nodes. For nodes, if it is an address node, it is anyway deleted in that case and if it is a node that contains more information (e.g. is an entrance, is a shop), adding `noaddress=yes` does not make so much sense as that tag is explicitly documented to apply to buildings (only).
Tagging a building with an address then also removes `noaddress=yes` and `nohousenumber=yes` in case it is missing.

**Comment by mnalis** [comment]
- (related: https://github.com/streetcomplete/StreetComplete/issues/2464)
