### ISSUE TITLE
trunks shouldn't be spammed with `sidewalk=no`

### ISSUE THREAD

**Issue by legofahrrad** [streetcomplete/StreetComplete#4606]
**Use case**
At the moment, all `highway=trunk`s without sidewalk info are marked red in Sidewalk Overlay. `highway=trunk` + `motorroad=yes` are (at least in Germany) forbidden for pedestrians. Thus they never have sidewalks.
I recommend not to "ask" for sidewalk info if `motorroad=yes` is tagged. (Of course SC doesn't ask in the overlay mode but many users want to get rid of any red highlighting and spam sidewalk=no to trunks.)
So the red highlighting should not be shown, but editing should be allowed (just as it is for living streets etc.).

**Comment by legofahrrad** [comment]
Also if it is [`motorroad=yes`](https://wiki.openstreetmap.org/wiki/Key:motorroad)?

**Comment by Helium314** [comment]
see #2953, which is kind of the opposite

**Comment by mnalis** [comment]
> I recommend not to "ask" for sidewalk info if motorroad=yes is tagged

And **_are_** they being asked currently? Can you give example @legofahrrad ? 
Because cursory look at the code seems to suggest that `motorroad=yes` highways should be excluded already, unless I'm misinterpreting it:

https://github.com/streetcomplete/StreetComplete/blob/cf7e3c87dca432aa85472fbbfded09b172773e79/app/src/main/java/de/westnordost/streetcomplete/quests/sidewalk/AddSidewalk.kt#L110-L124

**Comment by legofahrrad** [comment]
I'm talking about the overlay and the red highlighting there
