### ISSUE TITLE
Shoulder quest only on motorway and trunk in the Netherlands

### ISSUE THREAD

**Issue by A67-A67** [streetcomplete/StreetComplete#4617]
In the Netherlands only motorways and some trunk roads have shoulders, in Dutch: vluchtstrook (fleeing/emergency lane). On primary, secondary and tertiary they are extremely rare. Hence the quest "Add whether there are shoulders" would lead to adding shoulder=no on 99,9% of these roads, which is undesirable. [An inquiry with the Dutch community](https://community.openstreetmap.org/t/streetcomplete-voegt-shoulder-no-geen-vluchtstrook-toe-aan-allerlei-wegen/4889) made clear a lot of people agree that this is undesirable.

I'd like to propose enabling this quest only on highway=motorway and highway=trunk in the Netherlands. If this isn't possible, I think it'd be better to disable this quest entirely in the Netherlands.

**Comment by westnordost** [comment]
Are you aware of that also soft shoulders and not only hard shoulders are tagged with `shoulder=*` in OSM?

I.e. any area next to the roadway that was made with enabling emergency stopping in mind.

In German, those would be called "Bankett" (maybe similar in Dutch).

**Comment by westnordost** [comment]
E.g.
<img src="https://www.securatek.de/media/image/02/32/81/bodengitter-bg50-bankett-befestigung-008.jpg">

**Comment by Geim66** [comment]
A shoulder in the Netherlands is a "Vluchtstrook" always a hard shoulder (we know, we invented them: https://nl.wikipedia.org/wiki/Vluchtstrook ). No soft shoulders. Only road, shoulder and verge
Like in this picture 
![image](https://user-images.githubusercontent.com/112258895/200288486-6d3b1d2a-8f92-44c2-81cf-efc3996e2b64.png)

**Comment by westnordost** [comment]
You mean
1. there are never any soft shoulders as depicted in NL, or
2. 2. if there are any soft shoulders,  they are not tagged with `shoulder=*` in NL?

**Comment by Geim66** [comment]
Let's say it like this. This road has no shoulder.

![image](https://user-images.githubusercontent.com/112258895/200319800-83e84ef4-625a-42f5-bbba-d1c3f3cb7136.png)

**Comment by Helium314** [comment]
> E.g. ![](https://camo.githubusercontent.com/12122c00bd5bc3df4b8a481ed0e864449c43a0dfb422c3188b8d200f2a6b4da3/68747470733a2f2f7777772e73656375726174656b2e64652f6d656469612f696d6167652f30322f33322f38312f626f64656e6769747465722d626735302d62616e6b6574742d6265666573746967756e672d3030382e6a7067)

If this really counts as shoulder, shouldn't this count too?
(

![s](https://user-images.githubusercontent.com/43007630/200639465-19c0ca89-64b9-4965-96d3-dbaa93ab0bed.jpg)

@Geim66 one road without a shoulder doesn't mean no road has a shoulder. Could you please explain what you are trying to tell with your comment?

**Comment by rhhsm** [comment]
The matter seems to be what a "shoulder" is. The wiki states that it is a "lane" that is _wide enough to be used as an emergency refuge for cars_  The photos posted by westnordost and Helium314 show what looks more like a reinforced verge; I think they are not wide enough to be used as an emergency lane so I wouldn't tag them as a shoulder.
Back to the original question, I agree that shoulders are very rare on roads other than trunk and motorway. Maybe that's because I'm also Dutch, but I'm using SC mostly in Bulgaria and Turkey. In Bulgaria (and probably in many other countries) a paved shoulder is a requirement for a road to have motorway status, so asking for it on motorways would result in close to 100% shoulder=yes in those countries.

**Comment by westnordost** [comment]
@Helium314 according to the current wiki wording, your example would not have a `shoulder=yes` because a car could not completely stop beside the traffic lanes. For my example on the other hand, it could, at least at the area close to the camera - not sure about at where the trees start. Geim66's example looks like it would also fall under the wiki definition of a (soft) shoulder  because a vehicle can stop completely beside the traffic lane and on first glance, it seems to be maintained as an emergency stopping lane (plane solid surface of short cut grass without any shrubbery or ditches; clearly demarcated shoulder line some distance from the actual edge of the paved surface).

I recognize that the current wiki definition of `shoulder` is quite wishy-washy and leaves a lot of room for interpretation. Is something just a well maintained and broad `verge`? Or a soft `shoulder`? How to tag (soft) shoulders that are not full-width, like in your example? How to tag shoulders where one part is paved and the rest is just gravel or grass?

It would be a lot easier and clearer, if something would only be tagged as `shoulder=yes` when there is a full-width hard shoulder, or something. But alas, that's not how the tag is seen to be used in the wild and this is also not the wiki definition. (If I remember correctly, the initial implementation of this quest in StreetComplete did define it like that in the explanatory text, but it was challenged that this would not coincide with the wiki definition.)

In any case, StreetComplete issue tracker is not the right place to propose to change the definition or invent new tagging keys.

**Comment by matkoniecz** [comment]
On topic of shoulder tag being confusing: I added note to https://wiki.openstreetmap.org/wiki/Key:shoulder#History and posted https://community.openstreetmap.org/t/shoulder-tag-is-confusing/5185 - and disabled this quest for myself.

**Comment by westnordost** [comment]
I am contemplating removing this quest until such time as shoulders can be tagged with more precision. What do you think?

**Comment by matkoniecz** [comment]
Well, I removed it for myself, as I was unable to confidently answer it.

I think that it sadly is necessary as definition/data is a flaming trash heap and there is risk that StreetComplete can make it worse or get blamed for it. At least data/definition problem was discovered.

Note that outright removal of quest (not just disabling it) requires extra support as otherwise SC will crash at startup.

**Comment by westnordost** [comment]
>Note that outright removal of quest (not just disabling it) requires extra support as otherwise SC will crash at startup.

Why would it crash at startup?

**Comment by westnordost** [comment]
Thanks @Helium314. I now disabled the shoulder quest completely. Rather than changing `ElementEditsDao`, I'll just remove all non-uploaded `AddShoulder` on update.
