### ISSUE TITLE
Enhance user friendliness of the Lit quest

### ISSUE THREAD

**Issue by rhhsm** [streetcomplete/StreetComplete#4622]
I noticed in the Lit overlay, the question is asked using 2 dialogues, shown in these screenshots.
![image](https://user-images.githubusercontent.com/69100427/200651193-7083a5c8-ceb0-45f7-b210-54f098052a70.png)

![image](https://user-images.githubusercontent.com/69100427/200651050-37334abc-8343-4022-84c4-a52a149504d8.png)

I think that if the icons in the second image are made a little bit smaller, they can be fitted next to each other on one row, which would make the "select" screen unnecessary and reduce the number of taps to answer it by half. This could then also be used for the normal Lit quest (without overlay).

**Comment by westnordost** [comment]
This is the default interface for overlays and I want to keep it that way for consistency.

**Comment by mnalis** [comment]
- (duplicate https://github.com/streetcomplete/StreetComplete/discussions/4640; as github does not link discussions and issues automatically)

**Comment by mnalis** [comment]
Clarification: when you click on way that is already mapped, it looks like this instead:
![small_Screenshot_20221120_192326_de westnordost streetcomplete](https://user-images.githubusercontent.com/156656/202919215-49ae6098-325b-4eca-8388-a8734ac584fa.jpg)

Maybe it would be clearer if we show a picture of big question mark (`?`) when `lit` status in **_unknown_** (instead of omitting picture and replacing it with text `SELECT:`). That way it would be visually more similar to other overlays (and less confusing "why one has to click twice"). 

Dropdown triangle should be equally good indication that one has to click there to change value (as it does in case when some `lit` status is already mapped).
