### ISSUE TITLE
Feature request: Manual trigger for AR Measure?

### ISSUE THREAD

**Issue by contactobscurantist** [streetcomplete/StreetComplete#4636]
**Use case**
Entering quest data for which AR Measure could be of use, but is not activated as a source.
Think tonnel or building passage Max Height quests, wall/fence height, leaving notes for new objects or details, etc.

**Proposed Solution**
Maybe a button for accessing AR measurements can be added inside one of the menus?
For example: `Add Note` -> `AR Toolkit` -> What would you like to measure? `Distance`|`Height`
Basic mockup included.
![newnote-armeasure](https://user-images.githubusercontent.com/52663997/202261715-db4101bb-063b-4969-8be2-826e80443525.png)

If this feature is considered out-of-scope for StreetComplete, I think AR Measure part can be useful to many as a stand-alone app.

**Comment by westnordost** [comment]
Hm well, it looks like the AR measure needs to be outsourced from StreetComplete (i.e. made into a separate non-GPL-licensed app) anyway as it turned out that Google's ARCore library is not actually licensed under the Apache license 2.0 but is proprietary. Hence, the ARCore library cannot be part of GPL-licensed software like StreetComplete. The Google team that maintains ARCore seems uninterested in straightening out the issue (i.e. either documenting that it is not open source or actually following the license they declared for the product). Google is a big company and all and thus decisions make take a while but after 3 months, I don't have my hopes up that they intend to change anything in that regard. I.e. measuring stuff could remain in the app if they made it open source.

So anyway, long story short, I will soon be forced to remove AR measuring from the app and (maybe) reenable it by creating a separate (e.g. apache licensed) measuring app with which StreetComplete then communicates instead of doing the measuring itself. On the upside, this would enable other apps such as Vespucci, EveryDoor etc. to profit from this, plus, you could just do a measure independent of the app.

See https://github.com/google-ar/arcore-android-sdk/issues/1538 (and #4289)
