### ISSUE TITLE
Falsche Gebäudeart korrigieren

### ISSUE THREAD

**Issue by biketeur** [streetcomplete/StreetComplete#4641]
Ich war vor kurzem in einer Kleinstadt und stellte dort fest, dass die meisten Gebäude mit "house" getaggt waren, obwohl sie richtigerweise als Mehrfamilienhaus, Doppelhaushälfte, freistehendes Einfamilienhaus, ... hätten getaggt sein müssen. Anzahl Stockwerke und Dachform waren noch offen und wurden von streetcomplete erfragt.
Ich würde nun gerne die richtige Gebäudeform mit sc erfassen/korrigieren und schlage folgende Lösung vor:
Wenn sc nach der Anzahl Stockwerke fragt, klickt man "weitere Antworten" an und dort gibt es einen weiteren Punkt "Gebäudeart korrigieren". Wenn man diese Erweiterung so handhabt, als stünde dort building:yes statt building:house, so ließe sich diese Erweiterung leicht umsetzen.
Ich würde mich freuen, wenn diese Erweiterung in sc einfließen könnte, denn der Umweg über Vespucci ist sehr aufwendig.

**Comment by rhhsm** [comment]
Related #2016 "house", like "residential", is often used for any residential building while usually a more specific tag can be given.

**Comment by westnordost** [comment]
`house` is not incorrect, just less precise. Being able to correct/change properties of an object not related to the question asked in the quest is out of scope of this app, i.e. does not fit into the UX concept of StreetComplete.

**Comment by matkoniecz** [comment]
Yes, but that would be out of scope. There is possibility to implement infinite amount of "can't say" not really related to the quest

It seems to fail https://github.com/streetcomplete/StreetComplete/blob/master/OVERLAY_GUIDELINES.md requirement, though one may make a fork of SC and include it there.

**Comment by mnalis** [comment]
>  Ich würde mich freuen, wenn diese Erweiterung in sc einfließen könnte, denn der Umweg über Vespucci ist sehr aufwendig.

As a workaround, for changing house types, I'd recommend [EveryDoor](https://wiki.openstreetmap.org/wiki/Every_Door) over Vespucci, for quicker and easier editing. 

Or, you can choose `Leave a note` if it happens rare enough, but I personally wouldn't do that for such (IMHO) unimportant difference (because _someone_ has to invest effort to fix those notes later - but if **you** commit to solving all such notes, than it might be acceptable)

**Comment by rhhsm** [comment]
> `house` is not incorrect, just less precise. Being able to correct/change properties of an object not related to the question asked in the quest is out of scope of this app, i.e. does not fit into the UX concept of StreetComplete.

We can already correct a surface of a way (when asking for its smoothness), change a path to steps, edit the tag of a shop to another one or to "disused", etc. I think these are great improvements of the app, and I use them regularly to correct mistakes. Introducing the possibility to change the tag of a building is not that different, and would be a welcome improvement too.

**Comment by matkoniecz** [comment]
> We can already correct a surface of a way (when asking for its smoothness), change a path to steps, edit the tag of a shop to another one or to "disused", etc. I think these are great improvements of the app, and I use them regularly to correct mistakes. Introducing the possibility to change the tag of a building is not that different, and would be a welcome improvement too.

It is kind of question about putting some arbitrary limit. It is necessary to limit complexity because otherwise sooner or later (for example in 10 years after accepting 10 000 other feature requests) we end as "JOSM on phone" and we already have this.

Yes, some of rejections will be irritating/mistaken/not justified but it is necessary if keeping simplicity and relatively low complexity is one of the primary priorities.

(I am not really sure about this one in either direction, but in such case I will default to following what Tobias decided - partly because Tobias losing interest in StreetComplete and spending time on something else is the primary risk for continued flourishing of StreetComplete)

**Comment by westnordost** [comment]
A building type overlay would probably be fine. It would be efficient to (mass) correct building types and also get an overview of what is tagged currently.
