### ISSUE TITLE
New Quest: Does this place have a drive through?

### ISSUE THREAD

**Issue by kaneap** [streetcomplete/StreetComplete#4656]
### General
Affected tag(s) to be modified/added: [drive_through](https://wiki.openstreetmap.org/wiki/Key:drive_through)=*
Question asked: **Does this place have a drive-though?**
This should be asked for places tagged with [amenity](https://wiki.openstreetmap.org/wiki/Key:amenity)=[fast_food](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dfast_food).
Additionally in the US and Canada this should be asked for [amenity](https://wiki.openstreetmap.org/wiki/Key:amenity)=[bank](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dbank), [amenity](https://wiki.openstreetmap.org/wiki/Key:amenity)=[pharmacy](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dpharmacy), [amenity](https://wiki.openstreetmap.org/wiki/Key:amenity)=[atm](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Datm), [amenity](https://wiki.openstreetmap.org/wiki/Key:amenity)=[post_box](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dpost_box), [shop](https://wiki.openstreetmap.org/wiki/Key:shop)=[alcohol](https://wiki.openstreetmap.org/wiki/Tag:shop%3Dalcohol), and [amenity](https://wiki.openstreetmap.org/wiki/Key:amenity)=[cafe](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dcafe) with [cuisine](https://wiki.openstreetmap.org/wiki/Key:cuisine)=[coffee_shop](https://wiki.openstreetmap.org/wiki/Tag:cuisine%3Dcoffee_shop)

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/blob/master/QUEST_GUIDELINES.md)):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by any pedestrian from the outside but a survey is necessary
- [x] 💤 Not an overwhelming percentage of quests have the same answer (No spam) See below
- [x] 🕓 Applies to a reasonable number of map data (Worth the effort)

I have read through #2317 and would like to reference the store locators for [Rite-Aid](https://www.riteaid.com/locations/search.html?q=Philadelphia%2C+Pennsylvania%2C+United+States&services=3982) and [Walgreen's](https://www.walgreens.com/) (search for a city like Los Angeles in the store locator) will show that a large proportion of American Pharmacies will have a drive-through (and this matches my experience as well)

[amenity](https://wiki.openstreetmap.org/wiki/Key:amenity)=[cafe](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dcafe) with [cuisine](https://wiki.openstreetmap.org/wiki/Key:cuisine)=[coffee_shop](https://wiki.openstreetmap.org/wiki/Tag:cuisine%3Dcoffee_shop) is primarily for coffee shops like Starbucks or Dunkin', which usually will include a drive through if they have the room for it (locations downtown won't have it, nor will locations located in shopping malls, but in the suburbs they usually will have it. These coffee chains may be more the exception than the rule, so it may make sense to filter based on the name. (May also apply to Tim Horton's in Canada).

As for other countries, I am not certain how their development patterns have affected the prevalence of drive-throughs, however I would err on the side that it should ask for `amenity=fast_food` in most countries.

### Ideas for implementation

**Element selection:** 
Elements tagged with `amenity=fast_food`, `amenity=bank`, `amenity=pharmacy`, `amenity=atm`, `amentity=post_box`, `shop=alcohol`, or `amenity=cafe` with `cuisine=coffee_shop`, without `drive_through=*`

**Metadata needed:**
Only enabled/disabled on a country-by country basis.

**Proposed UI:**

Q: Does this establishment have a drive-through?
A: Yes, No, Drive Through only (`drive_through=only`)

Here is a mockup of how the icon could look (please note, I am not a graphic designer :))
![drive-thru_mockup](https://user-images.githubusercontent.com/35740782/204317976-9d5ff729-496b-4a92-ac43-10583b0459c9.png)

**Comment by FloEdelmann** [comment]
@westnordost this is not a duplicate

**Comment by westnordost** [comment]
How so?

**Comment by kaneap** [comment]
#1299 specifically addressed restaurants (`amenity=restaurant`) whereas this specifically addresses amenities where the presence of a drive through is probable and helpful to end users.

**Comment by westnordost** [comment]
How probably though? Do you have some numbers?

**Comment by kaneap** [comment]
I found this [study](https://www.qreadvisors.com/wp-content/uploads/2021/04/Tenant-Spotlight-QSR-Drive-Thru-2.pdf) which focuses on the US:
- Drive-thru sales represent 70% of fast food sales
- Roughly 64% of Dunkin’ (coffee shop) locations are equipped with drive-thru facilities
- Starbucks has drive-thrus at roughly 58% of company operated locations.

As for drive-through banks in the US, I found [this](https://believeinbanking.com/2020/07/21/window-of-opportunity-how-to-reshape-the-drive-up-for-the-social-distancing-era/) which states that "as recently as 2016, bank drive-ups were home to an estimated 60-65% of transactions"

I couldn't find any numbers on post boxes, but the drive-though mailbox is one of the standard designs for US mailboxes: 
[USPS mailbox Mapleton, Utah.JPG](https://commons.wikimedia.org/wiki/File:USPS_mailbox_Mapleton,_Utah.JPG)

Outside the US I was at least able to find that McDonald's in Austria has a drive-through (or McDrive as they call it) has a drive through at 134 out of 196 locations: https://www.mcdonalds.at/presse/mcdonalds-oeffnet-fast-alle-mcdrives (McDonalds may be an exception, and I certainly don't think it's a good idea to show this quest for every kebab stand in Germany, for example)

**Comment by rhhsm** [comment]
In order not to be spammy, for Europe this should be restricted to some brands that are known to have drive throughs (McDonalds, Burger King, KFC, ...) and should further be filtered to exclude branches in inner cities, malls, etc. The drive throughs I know all have service roads very close to the building or node, so maybe that could be a filter criterion? If `service=drive-through` is present, that's a sure sign there is a drive through.

**Comment by westnordost** [comment]
Oh sorry, I actually rather meant openstreetmap data. Real data is fine too, but the data you mention here is highly selective and thus does not grant an overall picture unless the quest should only exist for Starbucks and Dunkin in the US.

The reason why I'd tend to reject this quest is that even if drive-through is prevalent in some places in the United States where shopping facilities are spread out sparsely along strip malls in the typical small-town-in-America kind of way

(e.g. as shown here)
https://youtu.be/ORzNZUeUHAM?t=12

you still have, even in the United States, towns that have a "real" center, where pedestrians are the expected customers. Like, probably any part of New York etc.. For these places, it would then be somewhat spammy to ask.

I've never been in the United States, but from what I know, maybe at best only in the American Midwest there are **only** towns without a real (pedestrian designated) center where drive-through is a reasonable thing to ask? In general, my gut feeling is that it is not possible to narrow it down geographically and by kind of shop to reach an acceptable ratio of "yes" and "no" answers that is not spammy or where the question somewhat sounds out of line in the first place.

**Comment by matkoniecz** [comment]
I have some doubts about this tag in general - is it maybe easily detectable from street layout and `service` tags?

**Comment by matkoniecz** [comment]
Also, is this tag in actual use? (tag is established and has a useful purpose)

**Comment by westnordost** [comment]
Yes, it is in use. However, does it have a useful purpose? Well, it is the difference between parking and getting out of your car to walk a few meters to the shop entrance and staying in your car.  This may be relevant for the (severely) handicapped for whom walking is connected with much pain. So, I think this question can be answered with a "yes", even though it is much less important than `wheelchair` which is about whether you can access a shop **at all** on wheels, rather than being mostly about convenience.

**Comment by kaneap** [comment]
There are even a few drive_though=yes in downtown Chicago (https://overpass-turbo.eu/s/1olZ). Examples like Manhattan are definitely more the exception than the rule. (Perhaps @1ec5 may want to share his perspective as well) 

In terms of actual use, I'm not to familiar with all the implementations using OSM data, but it definitely has a use-case (Google maps allows you to filter for them by adding "drive-thru" after your search query). I definitely agree that this quest should be lower on the hierarchy than wheelchair by default.

**Comment by 1ec5** [comment]
> you still have, even in the United States, towns that have a "real" center, where pedestrians are the expected customers. Like, probably any part of New York etc.. For these places, it would then be somewhat spammy to ask.

Manhattan is exceptional in many ways, so I wouldn’t generalize the situation there to the rest of New York City, let alone the country. New York City is the only one out of the five largest cities in the U.S. where one could reasonably assume that a downtown bank or pharmacy lacks a drive-through, let alone one located outside of the downtown core.

That said, does it make sense to focus StreetComplete users’ attention on something that an armchair mapper can infer based on aerial imagery in most cases? In the U.S., drive-throughs are especially apparent beside standalone fast food restaurants, banks, and pharmacies. The national restaurant chains standardize on features like a canopy at the drive-through window, a height restrictor near where you place an order, and a specific shape for the drive-through. Bank drive-throughs tend to be very wide with multiple lanes, though there are also standalone ATMs with their own drive-throughs.

A typical U.S. Post Office drive-through goes from the main street back to the main street, never connecting to the parking lot, let alone the building. This makes it pretty easy to map from aerial imagery too. However, many post offices have drive-through collection boxes that stand beside the road or at the edge of a parking lot, without a dedicated drive-through anywhere on the premises. There are also drive-through collection boxes nowhere near a post office. There’s no real distinction between rural, suburban, and urban areas in terms of car-accessible collection boxes.

Postal collection boxes would be an interesting feature to include in this quest, because the boxes themselves are difficult to discern in aerial imagery – you can almost never tell if the box is facing the street or facing the sidewalk, even with very high-resolution aerial imagery. In an area where it’s hard to find street parking or where winter weather is brutal, you might really want to know whether you can drop off the mail without getting out of the car.

> Well, it is the difference between parking and getting out of your car to walk a few meters to the shop entrance and staying in your car. This may be relevant for the (severely) handicapped for whom walking is connected with much pain.

Yes, accessibility is one justification for tagging this information, not only for wheelchair users but also for expectant mothers and elderly people. Additionally, in some regions, drive-throughs matter to the general population for more than saving a few steps. In the Midwest, there’s a whole industry of drive-through-only convenience stores (historically liquor stores) that thrives during cold weather. At restaurants and banks, drive-throughs often operate earlier in the morning and later at night than indoor service. Some banks let non-customers use the ATM at the drive-through but refuse service indoors.
