### ISSUE TITLE
Enable manual stop of automatic download of quests

### ISSUE THREAD

**Issue by rhhsm** [streetcomplete/StreetComplete#4662]
**Use case**
1. I am normally offline while surveying. When I happen to be in range of a wifi that my phone knows and automatically connects with, the app automatically starts to download and update quests, which often leads to the app being blocked for edits for an annoyingly long time.
2. When surveying from a moving public transport vehicle with slow wifi connection, the app is often busy downloading quests from an area that I passed some time ago, so that I can't download the quests in an area that I know I'm heading to.

**Proposed Solution**
Enable to manually stop automatic download of quests. Maybe this could be activated by long-pressing the star in the upper left corner of the screen (a short tap there now toggles between total and last week's number of stars). Automatic updating of quests is a very good thing in most cases, so it should be the default and the manual stop could be time-limited (automatically go back to automatic updating after say 5 minutes) or with annoying reminders every 5 min asking to switch back to automatic.

**Comment by westnordost** [comment]
> the app is often busy downloading quests from an area that I passed some time ago, so that I can't download the quests in an area that I know I'm heading to.

But you can. A manually started download cancels any download that was started before. If you do this, it will even be mentioned in the dialog that pops up in that case.

**Comment by rhhsm** [comment]
> > the app is often busy downloading quests from an area that I passed some time ago, so that I can't download the quests in an area that I know I'm heading to.
> 
> But you can. A manually started download cancels any download that was started before. If you do this, it will even be mentioned in the dialog that pops up in that case.

Often I can't start a manual download, because of "the app being blocked for edits for an annoyingly long time"

**Comment by westnordost** [comment]
What?

**Comment by rhhsm** [comment]
Maybe the real problem is that while the app is automatically downloading and updating quests through a slow wifi connection (low signal strength), all kinds of problems occur, such as:

- the screen freezes or goes black, and I cannot do anything but wait unless I manually disable my wifi connection (recovery takes a few seconds after doing that; the app takes a few seconds to find out there's no connection any more, and then returns to normal);
- if it doesn't completely freeze, the app doesn't seem to accept new data, or it does accept them but doesn't tell me. Once, after entering shop opening hours and tapping the tick mark button, it asked for these opening hours again. Another time, I added a new shop in the shop overlay, but it did not show up so I added it again (twice). Then it showed up, asking for opening hours, so I entered them, but it asked again so I entered them again. When I came home and manually uploaded the quest answers, I noticed that the new shop was added to the map 4 times (4 new nodes), 2 of them with opening hours...

It's hard to write a specific bug report on this because it's not very reproducible... I'm using an LG Q60, Android 10 and SC 49.2

**Comment by riQQ** [comment]
Seems to be related to #4258.

**Comment by westnordost** [comment]
Okay, this is all rather off topic to the original request to have a "cancel" button.

Since the OP knew about the functionality that manually triggering the download for a given area cancels the old one, and any new functionality that would add a dedicated cancel button would do very much the same, it looks like the requested feature would not solve the OPs use case. Hence, I will close this issue.
The issue at hand could be solved by a number of other things, first and foremost the ability to disable any automatic downloads (without having to turn off location), making the download faster (e.g. by creating quests already while persisting the downloaded OSM data, @Helium314 once tried that) or changing the logic by which the app decides how big of an area it shall download to e.g. a time-based approach (if downloading the smallest possible bbox took longer than 5 seconds, don't download anything more for example).

**Comment by Helium314** [comment]
Some notes here:
* Creating quests already while persisting the downloaded OSM data turned out to be at best only slightly faster than than current way of persisting and then creating quests. I did some tests and it looks like the slow part in creating quests is actually the database operations (reading old quests, writing new ones). So actually I suspect having two separate databases (one for OSM data, one for quests / other stuff) could help a lot as the persisting OSM data then shouldn't block quest persisting any more.
* I added the option to disable auto-download in my fork for reasons similar to what @rhhsm describes. While a download is happening, the app is _much_ slower, and often is effectively blocked for quite a while. My guess is that persisting OSM data blocks writing edits, in addition to the obvious CPU load.
But also when a download is simply not finishing due to bad connection It feels slower, though I don't know what might actually cause this (unfinished download does not cause DB operations). Though I can't remember any complete freeze / going black here...

**Comment by westnordost** [comment]
> Creating quests already while persisting the downloaded OSM data turned out to be at best only slightly faster than than current way of persisting and then creating quests.

Hmm right, it looks like starting the app in debug distorts the actual time it takes to create quests. In debug mode, creating quests took about as long as persisting, but when not in debug, for the area around where I live it looks like this:

![bitmap](https://user-images.githubusercontent.com/4661658/205643984-120ee9ab-82c2-40b8-af77-cd6afd6c84d5.png)

One aspect not measured by this how long the map update takes after update of the data.
