### ISSUE TITLE
Support new street parking tagging scheme

### ISSUE THREAD

**Issue by westnordost** [streetcomplete/StreetComplete#4664]
The proposal for a [new street parking schema](https://wiki.openstreetmap.org/wiki/Proposed_features/street_parking_revision) will very likely be approved.

Part of the proposal is to deprecate the old schema. Hence, in order to not use deprecated tags, the app must use the new schema too.

**Affected files**
- [StreetParkingParser.kt](https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/osm/street_parking/StreetParkingParser.kt) + [tests](https://github.com/streetcomplete/StreetComplete/blob/master/app/src/test/java/de/westnordost/streetcomplete/osm/street_parking/StreetParkingParserKtTest.kt)
- [StreetParkingCreator.kt](https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/osm/street_parking/StreetParkingCreator.kt) + [tests](https://github.com/streetcomplete/StreetComplete/blob/master/app/src/test/java/de/westnordost/streetcomplete/osm/street_parking/StreetParkingCreatorKtTest.kt)
- maybe [StreetParking.kt](https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/osm/street_parking/StreetParking.kt) + [StreetParkingItem.kt](https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/osm/street_parking/StreetParkingItem.kt) + [tests](https://github.com/streetcomplete/StreetComplete/blob/master/app/src/test/java/de/westnordost/streetcomplete/osm/street_parking/StreetParkingKtTest.kt) and [StreetParkingOverlay.kt](https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/overlays/street_parking/StreetParkingOverlay.kt) + [StreetParkingOverlayForm.kt](https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/overlays/street_parking/StreetParkingOverlayForm.kt) in case new selections should be added or changed

**Implementation**
The parser that parses the old scheme should first be renamed to `OldStreetParkingParser` and be used as a fallback for a while as long as roads that are tagged with the old schema are still around.

<strike>
<b>Coordination required</b>

In the proposal, there was a mention about that a mechanical edit could be done in order to replace the old tags in one go so that data consumers (such as StreetComplete, too) do not need to be able to parse both the new and old schema.

If this is done, implementation & release of a StreetComplete version with parsing for and tagging the old schema replaced must be done in concert with those that do organize the mechanical edit (ping @SupaplexOSM). The mechanical edit should be only done after most users of StreetComplete updated to the new version that tags with the new schema.

If in the end **no** mechanical edit is done, it means that </strike> [ see [comment by @SupaplexOSM](https://github.com/streetcomplete/StreetComplete/issues/4664#issuecomment-1336277631) ] the `OldStreetParkingParser` must stick around probably indefinitely. StreetComplete would then only re-tag to the new tags if the user touches, that is, _changes_ the parking situation on the street. So as long as the parking situation does not change, those streets will not be re-tagged with the new schema.

Whether or not and when a mechanical edit will be done does not block the implementation of this ticket though.

**Comment by SupaplexOSM** [comment]
I just posted the main reasons in #4562 that prevent a / prevents us from a mechanical edit. However, if someone feels challenged to support us in this, we would of course be very happy.

Hopefully, the numbers of the old tagging decrease significantly in near future and may be erased completely after some time (but years, I think) - we are trying to support this development with some [tools](https://wiki.openstreetmap.org/wiki/Proposed_features/street_parking_revision#Call_for_participation:_Updating_parking_lane_data) ([Tag Translator](https://osmberlin.github.io/osm-tag-updater/), [JOSM stylesheet](https://josm.openstreetmap.de/wiki/Styles/ParkingLanes), probably MapRoulette Challenge...).

So reading old and writing new schema seems to be necessary.

**Comment by tordans** [comment]
I looked at the code recently with @SupaplexOSM and tried to add notes on what / how to update the parking overlay.

We hope that this will help someone who knows more about the code to going on this faster.

## Draft PR with notes in the code

https://github.com/streetcomplete/StreetComplete/pull/4717

## What needs to happen to support the old tagging (interpret and show it, but not write it)

The goal is

- SC interprets the old tags
- SC displays old/new the same (other tools/processes are used to update old to new like MapRoulette)
- SC only writes new tags

### `String.toParkingPosition()`

```kotlin
private fun String.toParkingPosition() = when (this) {
    "lane", "on_street", "on-street" -> LANE // add 'lane'
    "half_on_kerb" -> HALF_ON_KERB
    "on_kerb" -> ON_KERB
    // "painted_area_only", "marked" -> PAINTED_AREA_ONLY // remove
    "lay_by", "street_side", "bays" -> STREET_SIDE
    "shoulder" -> SHOULDER // added
    else -> null
}
```

### Translation table

| old tag                                                      | new tag                                                                                                                                  |
| ------------------------------------------------------------ | ---------------------------------------------------------------------------------------------------------------------------------------- |
| `parking:lane:$side=*`                                       | => `parking:$side:orientation=` (x-transformation)                                                                                       |
| `parking:lane:$side:$orientation=*`                          | => `parking:$side=` (x-transformation)                                                                                                   |
| `parking:condition:$side=no`                                 | => omit (`parking:$side=no` is enough; there is `:restriction` and `parking:$side:reason=narrow/dual_carriadeway/…` to tag more details) |
| `parking:condition:$side=no_stopping/no_standing/no_parking` | => `parking:$side:restriction=no_stopping/no_standing/no_parking`                                                                        |

See below about `painted_area_only` and `marked`.

## What needs to happen to support the new schema

### remove `parking:lane:$side:$orientation=painted_area_only` and `parking:lane:$side=marked`

This is the most complex one since the new schema remove this value and the old schema was kind of broken in this case. We cannot tell which postion a segement tagges `painted_area_only` or `marked` has.

Our recommendation is to not interpret this value at all and mark those segements as "not mapped" in terms of parking. So users need to re-tag them. (The UI could show the tagged orientation based on `parking:lane:$side=parallel|etc`.)

SC should then remove the old tagging.

Luckily this value was not used a lot: 5.665 <details><summary>Detailed numbers…</summary>

* 1779 https://taginfo.openstreetmap.org/tags/parking:lane:right:parallel=painted_area_only#overview
* 1443 https://taginfo.openstreetmap.org/tags/parking:lane:left:parallel=painted_area_only#overview
* 1133 https://taginfo.openstreetmap.org/tags/parking:lane:both:parallel=painted_area_only#overview
* 191 https://taginfo.openstreetmap.org/tags/parking:lane:right:diagonal=painted_area_only#overview
* 228 https://taginfo.openstreetmap.org/tags/parking:lane:left:diagonal=painted_area_only#overview
* 44 https://taginfo.openstreetmap.org/tags/parking:lane:both:diagonal=painted_area_only#overview
* 280 https://taginfo.openstreetmap.org/tags/parking:lane:right:perpendicular=painted_area_only#overview
* 299 https://taginfo.openstreetmap.org/tags/parking:lane:left:perpendicular=painted_area_only#overview
* 268 https://taginfo.openstreetmap.org/tags/parking:lane:both:perpendicular=painted_area_only#overview

</details> 

## rename `ON_STREET` => `LANE`

A simpley 1:1 rename. (No change to `ParkingPosition.estimatedWidthOnRoadFactor` etc. needed)

## consider `shoulder`

This is not a new value `parking:lane:$side:$orientation=shoulder`. There was a reason to omit it in the initial release. And the value is used very sparcely (new schema https://taginfo.openstreetmap.org/keys/parking%3Aright#values 0.44%, old schema https://taginfo.openstreetmap.org/keys/parking%3Alane%3Aright%3Aparallel#values 0.17%). And it is super similar to `on_kerb`, so hard to describe in the answer panel.

We recommend to continue omitting it from the answers. Or at least to add it in an separate update, so this does not get overburdened.

However, it would be good to visually display `shoulder` as valid and tagged segement – the same way as `street_side` (or `ON_KERB`) is displayed.

**Comment by Discostu36** [comment]
Is anyone already working on this? I have to admit that I'm a bit impatient for this, as SC is by far the most convenient editor for street parking editing.

**Comment by westnordost** [comment]
Yes, I will together with @tordans.

**Comment by westnordost** [comment]
The necessary work on it is by the way financed by @gislars who is part of the Berlin OSM community and quite into the Verkehrswende topic.

So much in fact that he is working together with @SupaplexOSM and @tordans to create a map visualizing street parking (in Berlin), see https://parkraum.osm-verkehrswende.org/. I.e. it is the first data consumer to comprehensively visualize parking data, supporting of course the new street parking tagging scheme (it is based on the "Parkraumkarte Neukölln" by @SupaplexOSM ). 

This [osm-parking-processing](https://github.com/osmberlin/osm-parking-processing) project is funded by the Prototypefund, but for the changes to be made on StreetComplete he pays out of his own pocket. :-) Maybe that project can be developed further into showing a global map by people interested in this later when the parking data is more saturated.
