### ISSUE TITLE
Bicycle overlay: bicycle=yes not visible

### ISSUE THREAD

**Issue by SLMapper** [streetcomplete/StreetComplete#4669]
A line with `highway=footway`, `bicycle=yes` (with or without `segregated=no`) is not highlighted in the overlay. 
See https://www.openstreetmap.org/way/22931888

**Expected Behavior**
Should be highlighted in blue

**Versions affected**
v50.0-beta1

**Comment by legofahrrad** [comment]
https://github.com/streetcomplete/StreetComplete/blob/5e0244e6aa4de3da77069af4ffc57a1b17c81e5d/app/src/main/java/de/westnordost/streetcomplete/overlays/cycleway/SeparateCyclewayForm.kt#L33-L55

@matkoniecz You meant this comment, right?

**Comment by matkoniecz** [comment]
yes

**Comment by westnordost** [comment]
> In Germany the difference between those two is that with bicycle=designated (blue sign) you have to use it, whereas with bicycle=yes ("Fahrrad frei") you are allowed to (which otherwise would be prohibited).
> So besides the legal situation in Germany of "must" vs. "can" there is no difference between these two.

The overlay really is just about the physical situation, not about the signage. And this is the reason why `bicycle=no` and `bicycle=yes` are also thrown into one pot, see above cited comment.
Only of interest is whether is a physical cycle track, regardless of whether it is signed to be mandatory ("benutzungspflichtig").
The signage is then a matter out of scope of this overlay that can be recorded separately, as explained in the cited comment - and by the way potentially a humongous amount of work, given the number of different legislation there is in the world and different signage there is in the world (and StreetComplete's aspiration to not confront users with the raw tags but present it with a WYSIWYG kind of UI) .

Maybe iin the future, there could be a quest, limited to Germany (and/or other countries where not all cycle tracks are mandatory/not mandatory) that specifically asks about if there is a blue lollipop for this cycle track.

**Comment by SLMapper** [comment]
Thank you for commenting. I understand the difficulty to apply per country rules that fit well here.
If it will be kept like this I however find the answers unclear and think a change is needed.

As SC is supposed to be a WYSIWYG UI, what should the user select in the situation described by me?
Example picture:
![Footway with "bicycle=yes" sign](https://www.karlsfeld.de/images/2014/Mar/31/l_3103.9c42b47901b8add9d8a4af2684e1c36e.jpg)
- `Not designated for cyclists (regardless of whether cycling is allowed or not)` is wrong, because there **is a sign**, designating it for cyclists (however SC chooses this option when `bicycle=yes` is present)
- `Designated combined foot- and cycleway` is wrong because it would set `bicycle=designated` (but I think most people would choose this)

What speaks against adding another option: `Footway with designated use for cyclists`?
This would resolve the ambiguity.

**Comment by SLMapper** [comment]
Having this new option would imho even make it easier to review any situation where `bicycle=yes` is wrongly added.

**Comment by SLMapper** [comment]
> Any clearer?

I don't think so, unfortunately.

> Didn't you read the cited comment in the code?

Yes, I read it before. My summary: _`bicycle=yes` does not indicate if there is a sign or not. This can depend on the country you are in and other factors._

I am only wondering if there would be **any concrete problem** to handle `bicycle=yes` on `highway=footway` like being in any form explicitly allowed (e.g. by a sign or any other visual clue).
What would e.g. be the issue to show this on "a path in a forest"?
I can rather see the benefit of detecting and correcting any non-optimal tagging there.

Making it a separate option (like suggested) would imho help not mixing it up with any other form of cycleway.

**Comment by westnordost** [comment]
> This is already today not true for bicycle=designated + segregated=no, because there the only indication is the sign and thankfully you are showing it in the overlay 👍

Hm, true.

> I am only wondering if there would be any concrete problem to handle bicycle=yes on highway=footway like being in any form explicitly allowed (e.g. by a sign or any other visual clue).
> What would e.g. be the issue to show this on "a path in a forest"?

            Hence, it is not verifiable well for the on-site surveyor: If there is no sign that 
            specifically allows or forbids cycling on a footway, the user is left with his loose 
            (mis)understanding of the local legislation to decide. After all, bicycle=yes/no 
            is (usually) nothing physical, but merely describes what is legal. It is in that sense 
            then not information surveyable on-the-ground, unless specifically signed. 
            bicycle=yes/no does however not make a statement about from where this info is derived. 
            [...]
            More importantly, at the time of writing, there is no way to tag the information that a 
            bicycle=* access restriction is derived from the presence of a sign. This however is a 
            prerequisite for it being  displayed as a selectable option due to the reasons stated 
            above. 

To elaborate: Whether or not bicycles are allowed by default on a sidewalk and under what conditions (in Germany: always "no" unless otherwise signed.... as far as I know, that is) differs from country to country. In Poland, there is some rule like "if the sidewalk is broader than X meters and also some other criteria is given" it is allowed, otherwise prohibited. We can't expect surveyors to know these rules. But if we showed that information, we'd expect that from him, because otherwise he might re-tag that information incorrectly to "none allowed" (or "yes, allowed") because there is no sign and he just assumes that bicycles will be not allowed / be allowed there.

**Comment by matkoniecz** [comment]
> In Poland, there is some rule like "if the sidewalk is broader than X meters and also some other criteria is given" it is allowed, otherwise prohibited. 

It is more complex!

It can be under default rules:

- legal when sidewalk is wider than 2m and carriageway allows more than 50 km/h
- during dangerously bad weather
- when accompanying child that is cycling but legally considered as pedestrian (younger than 11 years old if I remember right)
- otherwise not allowed

Cycling can be also banned, in such case neither of this applies. But young children can still cycle as they are legally considered as pedestrians (not sure about people accompanying them...)

**Comment by westnordost** [comment]
Well okay, but most of this is not relevant for tagging in OSM

**Comment by matkoniecz** [comment]
> Well okay, but most of this is not relevant for tagging in OSM

I just wanted to give that as example of why

> We can't expect surveyors to know these rules. But if we showed that information, we'd expect that from him, because otherwise he might re-tag that information incorrectly to "none allowed" (or "yes, allowed") because there is no sign and he just assumes that bicycles will be not allowed / be allowed there.

**Comment by westnordost** [comment]
> displaying bicycle=yes as Footway with designated use for cyclists (signed or legally)

Translation issue? How is a footway on which bicycles are allowed "designated use" for cyclists?

**Comment by SLMapper** [comment]
Maybe. My understanding of "designated" (German: "ausgewiesen", "bezeichnet") is that there is a sign. However translations "ernannt" and "vorgesehen" could mean any (non exclusive) dedication without a visible sign.

Anyhow: What do you think about the suggestion using `Footway with allowed use for cyclists (signed or legally)`

**Comment by westnordost** [comment]
Well, as said, that shifts the responsibility to decide whether something is "legally" allowed or not onto the individual mapper. We do not do that in StreetComplete. For good reason. A little warning dialog will not better that situation.

It is not only a matter of UI / design principle in StreetComplete to be easy for the average joe but also a question of data quality. If it is up to each individual mapper to decide if something is "legally" allowed or not, it will result in a hodgepodge of wrong and correct values, depending each on how much in detail the individual user is informed about the legal situation. 

(For example, are you actually sure that German law does not have similar rules and exceptions as the Polish law? There must be something in the law that in general allows bicycle traffic on just some path without any sign, but on the other hand forbids bicycle traffic on "straßenbegleitende" ways unless it is signed. Such details are important when one wants to tag `bicycle=yes/no` explicitly according to the current regulations).

Not to mention what happens if the legislation changes.

The only way to escape this situation is to have a tag to denote whether the individual bicycle access restriction is derived from an actual sign or not, like `access:bicycle:signed=yes` or something(?). As far as I know, that tag does not exist (yet), so any further discussion about whether recording this kind of information could maybe be integrated into the overlay is blocked until such time.

**Comment by SLMapper** [comment]
Ok I see my proposal seems not suitable. 

I however still see a problem with the existing situation. 

Ethymological the word "designated" is related to "sign", same as in German "beschildert" is related to "Schild". 

Therefore "not designated for cyclists..." is wrong to me in case there is a sign. 

If "bicycle=yes" **can** mean there is a sign, this wording is incorrect for the cases where a sign is really present. 

I doubt however the usage of something like `access:bicycle:signed=yes` would expand fast even if accepted by the community. 

So what other solution can you think of? 
- Is there maybe a better wording to distinguish between 
  - allowed bicycle access (maybe by sign) 
  - explicit cycleway (blue sign) 
- or is there a better additional option to reflect allowed bicycle access (maybe signed) - from your answer it seems not possible

**Comment by SLMapper** [comment]
Thank you for asking in the osm community. Currently I dont have time to check this, but will do so some days later.
If anybody else can see if it will help to distinguish the mentioned scenarios that is appreciated.

**Comment by westnordost** [comment]
I also asked in slack-us regarding "designated" and "dedicated" and will update the wording accordingly.

**Comment by joshinils** [comment]
> ![Footway with "bicycle=yes" sign](https://camo.githubusercontent.com/75a4a0eb75b2189484431cee92afe02255306a9572894034efe1e20e1cc4b0c3/68747470733a2f2f7777772e6b61726c7366656c642e64652f696d616765732f323031342f4d61722f33312f6c5f333130332e39633432623437393031623861646439643861346166323638346531633336652e6a7067)

That combination of DE:239 + DE:1022-10 implies a `maxspeed:bicylce=walk`! though no one actually tags it as such and even less people actually go that slow.

**Comment by joshinils** [comment]
> Maybe there is a solution that would add another selectable option to distinguish at least between:
> 
>     * `foot=designated + bicycle=no/yes/unset` -> "Footway (regardless of whether cycling is allowed or not)"
> 
>     * `foot=yes + bicycle=yes` (e.g. `highway=path` with no extra tags) -> "A path without any designation"
> 
> 
> Whether this solves the angle you criticized I don't know, but at least paths in the forest etc. wouldn't be displayed in black (but probably similar to `shared foot- and cycleway`)
> 
> https://community.openstreetmap.org/t/fahrradfahrer-frei-von-situationen-unterscheiden-in-denen-radfahrer-implizit-erlaubt-sind/6478/6?u=westnordost

The German forest law specifically allows cycling on all visible paths in any forest, so any path in any forest (private or not) is automatically a shared foot and cycleway.

> BWaldG § 14 Betreten des Waldes
>
> (1) Das Betreten des Waldes zum Zwecke der Erholung ist gestattet. Das **Radfahren**, das Fahren mit
Krankenfahrstühlen und das Reiten im Walde ist **nur auf Straßen und Wegen gestattet**. Die Benutzung geschieht
auf eigene Gefahr. Dies gilt insbesondere für waldtypische Gefahren.

In any case, legalities per country should not concern SC. Only if the tagging is as such, with the per country default values for an otherwise untagged path.

**Comment by joshinils** [comment]
> Yeah, so you choose the option "not designated for cyclists". Anyway, that example above... maybe in paper you may go only walk speed, but i bet even the people who put this sign weren't aware of that shrug

yeh :roll_eyes: :shrug: 

> > The German forest law specifically allows cycling on all visible paths in any forest, so any path in any forest (private or not) is automatically a shared foot and cycleway.
> 
> No, it's a "path". Everything is allowed unless forbidden.

Yes, but I wanted to give an example on where cycling access-tagging can be a result of a law many people do not know about.
Even a sign disallowing cycling in a forest is legally void, and thus the value in OSM (in my opinion) should probably follow the legal value over a sign on-the-ground. Reason being that it is most probably only temporary because of tree work and closed to everyone during and open after.

**Comment by SLMapper** [comment]
I like the improved situation in v 50.0:
- wording is more clear now - at least in German: `Nicht ausgewiesen als Radweg (Radfahren kann trotzdem erlaubt sein)`. This imho resolves the previous ambiguity.
  - most likely English should be adapted accordingly from current `Not designated for cyclists (cycling may still be allowed)` to `Not designated as cycleway (...)`
- paths are now also highlighted. This could be helpful, but on the other hand leads to inconsistency. See below.

### Current situation
Highlighted (shown as `Path or trail`):
- `highway=path` [example](https://www.openstreetmap.org/way/1065342917)
- `highway=path` (`surface=grass`, `mtb:scale=4`) [example](https://www.openstreetmap.org/way/218663808) - _yes surface or mtb scale are not evaluated, but this reveals that highlighting path like a "cycleway" might not be ideal_ 
- `highway=footway`, `bicycle=yes`, `foot=yes` [example](https://www.openstreetmap.org/way/22931947)

Not highlighted (shown as `Not designated for cyclists (...)`):
- `highway=footway` [example](https://www.openstreetmap.org/way/1052848950)
- `highway=footway`, `bicycle=yes` [example](https://www.openstreetmap.org/way/22931537)
- `highway=footway`, `foot=designated`, `bicycle=yes` [example](https://www.openstreetmap.org/way/16604291)
- `highway=footway`, `footway=sidewalk`, `foot=designated`, `bicycle=yes` [example](https://www.openstreetmap.org/way/22931888)

### Suggestion
- do not highlight `highway=path` or `highway=footway` in general. Instead only highlight them whenever there is a `bicycle=yes` on it. Because it means, allowed bicycle usage is explicity tagged, compared to any path where it is implicity allowed anyhow.
- (maybe) add another option when `bicycle=yes` is set on such ways

**Comment by westnordost** [comment]
Hw=path is highlighted mainly because "some path" in the forest shouldn't look like you can't cycle there. Hw=path implies yes for both foot and bicycle. It is treated as such in the parser for the data (hence, no difference can be made between hw=path and hw=path+bicycle=yes).

**Comment by SLMapper** [comment]
So for paths no difference between explizit and implicit `bicycle=yes`, ok.

Though you are highlighting them because cycle access is allowed there, while refraining from highlighting `bicycle=yes` on footways for the same reason, right?

Current situation is inconsistant, as e.g.
- some paths/footways are highlighted, some not (_leads to not understanding why some are highlighted and some not - thereby effectively reducing the meaningfullness of the highlighting_) 
- in the forest/field paths are highlighted, but tracks are not (_leads to highlights appearing in the out of nowhere_) 

I can attach examples if wanted.

**Comment by westnordost** [comment]
So, should maybe paths be highlighted in black, too?

**Comment by SLMapper** [comment]
If you prefer to keep `highway=footway, bicycle=yes` in black, then yes, paths should be black as well.

**Comment by SLMapper** [comment]
We could think it the other way round, adding another highlight color for disallowed bicycle access (`footway=yes` without `bicycle=yes` and any way with `bicycle=no`)

**Comment by SLMapper** [comment]
Thanks, it's consistant now.

I am thinking about opening a new issue to give all `bicycle=yes` or `path` a different color to make this overlay more effective / show the complete picture.
However that's for the future.

Now it is mostly clear and understandable and I like this.
