### ISSUE TITLE
Changing cycleway tags should remove any cycleway-related tags

### ISSUE THREAD

**Issue by legofahrrad** [streetcomplete/StreetComplete#4675]
**How to Reproduce**
- use the cycleway overlay
- choose any way that has any cycleway information and additional information about that cycleway (e. g. https://www.openstreetmap.org/way/4855231 which has for example `cycleway:right:smoothness`)
- change the "track" to "none"
- open the undo menu
- tap on the last change and see that the `cycleway:right` and `cycleway:right:oneway` was changed but no other information
- thus, the not (anymore) existing cyclway has still tagged surface, smoothness, ... infos

**Expected Behavior**
Similar to #4123 SC should remove these information as the cycleway was changed

**Versions affected**
v50.0-beta1

**Comment by westnordost** [comment]
This one is problematic to implement because it is somewhat unclear what information depends on the cycleway and which does not and depends on the situation. 

Access restrictions, width, surface and smoothness are candidates, but the list may be longer. 

After all, you certainly wouldn't want the `smoothness` to be deleted  if you changed a cycleway from "unspecified lane" (or exclusive cycle lane) to advisory cycle lane. Also, even for cycle tracks, it is possible that the surface did not actually change when changing from "explicitly on sidewalk" to "cycle track". After all, it could be that just a line was drawn on the sidewalk.
Also, the app does not know whether the cycleway was "really" changed, or if the previous information was just corrected.

Dealing with this (e.g. only delete if it was changed from/to cycle track??) would get messy really fast and there will be always cases where it is deleted when it shouldn't be and the other way round.
Furthermore, what about if a property is defined for `:both=X` but only one side is changed? Then, StreetComplete would need to set e.g. `:left=X` without the user actually having checked that value.

**Comment by legofahrrad** [comment]
I see – yes, in some cases when changing _"exclusive lane"_ to _"exclusive lane, both directions"_ for example the information should not be removed. But when changing _"track"_ to _"none"_ it is quite a bug that the surface, smoothness etc. stays.
So will you close it as a `wontfix`?

**Comment by westnordost** [comment]
Not sure, I first wanted to state the possible complications with that.

**Comment by westnordost** [comment]
Hm yeah, I figure that I won't implement this as I fear this ranges quite into the kind of "smart" behavior that may as well overreach and do unexpected things in edge cases. Also, the complexity with dealing with (subtags of) this left-right-both tagging for sidewalks, cycleways and street parkings on the roadway makes me want to recommend mapping these things separately if one really wants to go into detail here. This makes it somewhat easier to to parse, update and maintain (for mappers), who also do not need to deal with roads cut into thousand little pieces.

When tagging sidewalks, by the way, any properties of sidewalks that one may count as a subtag of that (e.g. sidewalk:*:surface, smoothness, width is also not updated).

So.... I am not sure if I should recommend that someone interested in this could create a PR, after all, I arrived at this conclusion knowing the code and imagining how a PR+tests for this would look like. But at least, if there was a PR, it would open the discussion again if this should really not be included (given someone already created it and wrote all the tests etc).
