### ISSUE TITLE
Don't mark contraflow sides of dual carriageways as missing cycleway information if `cycleway:right` is set

### ISSUE THREAD

**Issue by legofahrrad** [streetcomplete/StreetComplete#4676]
With the Cycleway Overlay, left sides of one-way roads are marked red if the cycleway info is missing.
If this is a `dual_carriageway=yes`, it doesn't make sense to tag `cycleway:left`, as the info is tagged on the opposite side of the dual carriageway. (For countries with left-hand traffic the other way around.)

![grafik](https://user-images.githubusercontent.com/92865620/206849511-fa998616-ec07-4876-944d-7e3d6b201808.png)

This issue was mentioned once before here: https://github.com/streetcomplete/StreetComplete/discussions/4670#discussioncomment-4325126

**Comment by westnordost** [comment]
@joshinils wrote:
> the only way around this i see is to use the tag [dual_carriageway=yes](https://wiki.openstreetmap.org/wiki/Tag:dual_carriageway%3Dyes) if it exists. but it probably is best to explicitly tag all those as not having a cycleway on the left hand side. same situation with the parking overlay.

If I understand correctly, he wrote that it is best to just explicitly tag all those?

After all, `dual_carriageway` is quite the rare tag anyway.

**Comment by westnordost** [comment]
Hm, this could just as well be said for `sidewalk`s. 

I actually half-implemented it, but looking at the code produced, I do not think it is worth the added complexity. The logic is somewhat complicated with that, as the cycleway would only not be expected on **one** side, but on the other. And on which side that is is dependent on
- country (left hand traffic or not) - i.e. for each individual road piece it has to be checked in which country it is
- whether it is a `oneway=yes` or a `oneway=-1`

Which means, that any other data consumer would face the same problem to ascertain if it is missing or not, so I actually think it is better to tag it explicitly.

Also, as I wrote, `dual_carriageway=yes` is only set on a tiny percentage of actual dual carriageway roads. This means, that on most dual carriageway roads, StreetComplete will still show the sidewalks and cycleways missing on the "inner" side and consequently, people will tag the inner side, too. When later `dual_carriageway=yes` is added, these have already been set. Might as well completely ignore that tag then and show this data as missing (because it technically is) rather than jumping through hoops to come to the conclusion that the non-existance of cycleways and sidewalks on that particular side is indeed implied to not be missing.

The greater "problem" in this regard is any more complicated intersection, which in reality is just a big asphalted area with appropriate markings but in OSM is a network of many small road segments that connect to each other. Data consumers (such as STreetComplete) also do not know that these are not proper roads and thus mark sidewalk information (etc) as missing if it is not set. And here, there is not even an established tag for that (yet) to denote that a road is not a "real" road.

<details>
<summary>Here is the diff for the cycleway overlay, in case I change my opinion later. The same would need to be done for the sidewalk overlay:</summary>

```diff
+diff --git a/app/src/main/java/de/westnordost/streetcomplete/overlays/cycleway/CyclewayOverlay.kt b/app/src/main/java/de/westnordost/streetcomplete/overlays/cycleway/CyclewayOverlay.kt
index 6d7e9bfda..81cc566a6 100644
--- a/app/src/main/java/de/westnordost/streetcomplete/overlays/cycleway/CyclewayOverlay.kt
+++ b/app/src/main/java/de/westnordost/streetcomplete/overlays/cycleway/CyclewayOverlay.kt
@@ -21,6 +21,7 @@ import de.westnordost.streetcomplete.osm.cycleway.createCyclewaySides
 import de.westnordost.streetcomplete.osm.cycleway.isAmbiguous
 import de.westnordost.streetcomplete.osm.cycleway_separate.SeparateCycleway
 import de.westnordost.streetcomplete.osm.cycleway_separate.createSeparateCycleway
+import de.westnordost.streetcomplete.osm.isInContraflowOfOneway
 import de.westnordost.streetcomplete.osm.isPrivateOnFoot
 import de.westnordost.streetcomplete.overlays.Color
 import de.westnordost.streetcomplete.overlays.Overlay
@@ -92,24 +93,39 @@ private fun SeparateCycleway?.getColor() = when (this) {
 }
 
 private fun getStreetCyclewayStyle(element: Element, countryInfo: CountryInfo): PolylineStyle {
-    val cycleways = createCyclewaySides(element.tags, countryInfo.isLeftHandTraffic)
-    val isBicycleBoulevard = createBicycleBoulevard(element.tags) == BicycleBoulevard.YES
+    val tags = element.tags
+    val isLeftHandTraffic = countryInfo.isLeftHandTraffic
+    val cycleways = createCyclewaySides(tags, isLeftHandTraffic)
+    val isBicycleBoulevard = createBicycleBoulevard(tags) == BicycleBoulevard.YES
 
     // not set but on road that usually has no cycleway or it is private -> do not highlight as missing
     val isNoCyclewayExpected =
         cycleways == null && (cyclewayTaggingNotExpected(element) || isPrivateOnFoot(element))
+    val isNoCyclewayExpectedLeft =
+        isNoCyclewayExpected || cycleways?.left == null && cyclewayTaggingNotExpectedForSide(false, tags, isLeftHandTraffic)
+    val isNoCyclewayExpectedRight =
+        isNoCyclewayExpected || cycleways?.right == null && cyclewayTaggingNotExpectedForSide(true, tags, isLeftHandTraffic)
 
     return PolylineStyle(
         stroke = when {
-            isBicycleBoulevard ->   StrokeStyle(Color.GOLD, dashed = true)
-            isNoCyclewayExpected -> StrokeStyle(Color.INVISIBLE)
-            else ->                 null
+            isBicycleBoulevard -> StrokeStyle(Color.GOLD, dashed = true)
+            isNoCyclewayExpectedLeft && isNoCyclewayExpectedRight -> StrokeStyle(Color.INVISIBLE)
+            else -> null
         },
-        strokeLeft = if (isNoCyclewayExpected) null else cycleways?.left?.cycleway.getStyle(countryInfo),
-        strokeRight = if (isNoCyclewayExpected) null else cycleways?.right?.cycleway.getStyle(countryInfo)
+        strokeLeft = if (isNoCyclewayExpectedLeft) null else cycleways?.left?.cycleway.getStyle(countryInfo),
+        strokeRight = if (isNoCyclewayExpectedRight) null else cycleways?.right?.cycleway.getStyle(countryInfo)
     )
 }
 
+private fun cyclewayTaggingNotExpectedForSide(
+    isRightSide: Boolean,
+    tags: Map<String, String>,
+    isLeftHandTraffic: Boolean
+) = tags["dual_carriageway"] == "yes" && isInContraflowOfOneway(isRightSide, tags, isLeftHandTraffic)
+
+private fun cyclewayTaggingNotExpected(element: Element) =
+    cyclewayTaggingNotExpectedFilter.matches(element)
+
 private val cyclewayTaggingNotExpectedFilter by lazy { """
     ways with
       highway ~ track|living_street|pedestrian|service|motorway_link|motorway
@@ -122,9 +138,6 @@ private val cyclewayTaggingNotExpectedFilter by lazy { """
       or ~${(MAXSPEED_TYPE_KEYS + "maxspeed").joinToString("|")} ~ ".*zone:?([1-9]|[1-2][0-9]|30)"
 """.toElementFilterExpression() }
 
-private fun cyclewayTaggingNotExpected(element: Element) =
-    cyclewayTaggingNotExpectedFilter.matches(element)
-
 private fun Cycleway?.getStyle(countryInfo: CountryInfo) = when (this) {
     TRACK ->
         StrokeStyle(Color.BLUE)
```
</details>

**Comment by joshinils** [comment]
> @joshinils wrote:
> 
> > the only way around this i see is to use the tag [dual_carriageway=yes](https://wiki.openstreetmap.org/wiki/Tag:dual_carriageway%3Dyes) if it exists. but it probably is best to explicitly tag all those as not having a cycleway on the left hand side. same situation with the parking overlay.
> 
> If I understand correctly, he wrote that it is best to just explicitly tag all those?
> 
> After all, `dual_carriageway` is quite the rare tag anyway.

Somewhat, I would rather a router or other software explicitly parses a cycleway:left=no rather than relying on it knowing how to handle `dual_carriageway=yes` and what it means in a specific country.

**Comment by joshinils** [comment]
> Hm, this could just as well be said for `sidewalk`s.
> 
> I actually half-implemented it, but looking at the code produced, I do not think it is worth the added complexity. The logic is somewhat complicated with that, as the cycleway would only not be expected on **one** side, but on the other. And on which side that is is dependent on
> 
>     * country (left hand traffic or not) - i.e. for each individual road piece it has to be checked in which country it is
> 
>     * whether it is a `oneway=yes` or a `oneway=-1`
> 
> 
> Which means, that any other data consumer would face the same problem to ascertain if it is missing or not, so I actually think it is better to tag it explicitly.
> 
> Also, as I wrote, `dual_carriageway=yes` is only set on a tiny percentage of actual dual carriageway roads. This means, that on most dual carriageway roads, StreetComplete will still show the sidewalks and cycleways missing on the "inner" side and consequently, people will tag the inner side, too. When later `dual_carriageway=yes` is added, these have already been set. Might as well completely ignore that tag then and show this data as missing (because it technically is) rather than jumping through hoops to come to the conclusion that the non-existance of cycleways and sidewalks on that particular side is indeed implied to not be missing.
> 
> The greater "problem" in this regard is any more complicated intersection, which in reality is just a big asphalted area with appropriate markings but in OSM is a network of many small road segments that connect to each other. Data consumers (such as STreetComplete) also do not know that these are not proper roads and thus mark sidewalk information (etc) as missing if it is not set. And here, there is not even an established tag for that (yet) to denote that a road is not a "real" road.
> Here is the diff for the cycleway overlay, in case I change my opinion later. The same would need to be done for the sidewalk overlay:

Overall OSM is missing a concept for grouping separately mapped ways, i.e. the centerline (usually car-road) and cycleways, sidewalks, or two pieces of a dual carriageway together logically besides just their position.
Meaning any of the non-car ways do not have a `name` tag etc. where in actuality the whole street including all of them has the name.

This leads to problems with routers for pedestrians or cyclists where they jsut tell you to take the next right hand turn to "unnamed xy" since the separately mapped way does not have the name of the street.
And the recent RFC for [`is_sidepath=yes`](https://wiki.openstreetmap.org/wiki/Proposed_features/Key:is_sidepath) and potential accompanying tags `is_sidepath:of` and `is_sidepath:of:name` were not a favourite of the community as I remember.
Never mind grouping them all in a relation... :roll_eyes:

**Comment by westnordost** [comment]
Routers could use the formulation "take that cycleway along Butterbrotstraße to the left" though even now. It wouldn't even be wrong if that cycleway couldn't be viewed really as part of that road anymore. 

Also,  for sidewalks there is `footway=sidewalk` which somewhat carries similar information as `is_sidepath`

**Comment by joshinils** [comment]
> Routers could use the formulation "take that cycleway along Butterbrotstraße to the left" though even now. It wouldn't even be wrong if that cycleway couldn't be viewed really as part of that road anymore.

_If_ they can connect the sidepath with the centerline. 
Based on hearsay from people using komoot for example that is not the case, they only use the info of the separate cycleway way.

too off-topic for me and too hypothetical
