### ISSUE TITLE
Allow answer "it is under construction"

### ISSUE THREAD

**Issue by matkoniecz** [streetcomplete/StreetComplete#4683]
I relatively often encounter footways/roads that are under construction making answering in SC impossible.

Yes, I can switch to Vespucci or create note and later edit at home but manually switching `highway=footway` to `highway=construction` `construction=footway` is a bit annoying and error prone.

@westnordost what you think about adding such "can't say" option to StreetComplete? (if not, then I will just add it to my private version)

**Comment by westnordost** [comment]
I don't understand; there is a quest for that.

In any case, if you are going to implement it anyway, you could just implement it in your private version and create a PR, so then I also understand what you want to achieve.

**Comment by matkoniecz** [comment]
When there is `highway=steps` and it asks about whether steps have ramp then it would become possible to answer "under construction" and turn it into `highway=construction construction=steps`

**Comment by westnordost** [comment]
Ah, I see. 

I do think it is better to create a note in this case.

Because it is not a construction, but a deconstruction or a reconstruction, since the way is already there in OSM. Which means, after the construction is over, the way may look completely different or be gone (replaced by something else). This is a different case than a way that is being constructed.
