### ISSUE TITLE
Sidewalk quest does not show up

### ISSUE THREAD

**Issue by RubenKelevra** [streetcomplete/StreetComplete#4684]
I removed the sidewalk tag on a street (as it was wrong) and noticed that SC's sidewalk-quest isn't showing up. I waited some days and cleared the cache in SC - but no difference. I have all quests active.

Tags on a segment of the street:

![Screenshot_2022-12-13-23-57-17-199-edit_de blau android](https://user-images.githubusercontent.com/614929/207464391-6d1ae7bb-472e-4b3a-b0c0-936fb2ff6ab2.jpg)

StreetComplete complete showing the area:

![Screenshot_2022-12-13-23-59-56-395-edit_de westnordost streetcomplete](https://user-images.githubusercontent.com/614929/207464452-5e7a5545-89ac-4240-9f85-4bc29d4179db.jpg)

**How to Reproduce**
Unsure

**Expected Behavior**
Show a sidewalk quest.

**Versions affected**
- v49.2
- v50.0

**Comment by westnordost** [comment]
Is the sidewalk quest activated?

**Comment by westnordost** [comment]
Also, why did you remove the sidewalk tag (with Vespucci?) when it was wrong? Couldn't you simply have used the sidewalk overlay?

**Comment by westnordost** [comment]
Ah, I see. 

The problem is that `maxspeed` is not a numerical value. StreetComplete did not expect this. It shows the sidewalk quest only on roads that have `maxspeed > 9`.

This tagging may be considered a mistake beause it is not at all common to put `DE:urban` into `maxspeed` but since in Romania and Russia, tagging `RO:....` on the `maxspeed` key is common, I ought to fix this.
