### ISSUE TITLE
when POI and note have the same positon: Hide notes to make nodes editable

### ISSUE THREAD

**Issue by Strubbl** [streetcomplete/StreetComplete#4687]
I cannot solve notes by editing. In OSM there are a lot of notes which are on the same position as a POI. With StreetComplete it is not possible to edit these POIs in order to fix the note.

**How to Reproduce**
1. Have a note on the exact same position as a POI node
2. answer the note so that it disappears
3. Now i want to edit the POI e.g. with the shop overlay
4. If i select the POI node it opens the note instead

**Expected Behavior**
If i select the POI node it opens the node for editing. 
(Also i cannot disable the notes quest, which might have worked around this issue.)

**Versions affected**
v50

**Comment by Helium314** [comment]
Notes block everything within a (very) short distance.
You need to solve the note some other way first, see e.g. #4680

**Comment by Strubbl** [comment]
I can confirm that experience. 

The referenced issue quotes: "that must be solved first (outside of the app)".
Maybe my issue is a feature request then. I want to solve this first with the help of StreetComplete.

**Comment by westnordost** [comment]
If you are certain that you can solve the note via StreetComplete, you can close the note (and download the area around that note again in SC), editing will be unlocked.

**Comment by Strubbl** [comment]
The steps you are mentioning take too much time (switch app, close note, switch back to SC, download data again) - so much, that i am not going to do this. 
Can i close the note anyhow via StreetComplete? Switching apps on mobile is not that fast, e.g. i only know OsmAnd for closing notes. And OsmAnd is sooo slow on my mobile.

**Comment by westnordost** [comment]
No,  you can't

**Comment by mnalis** [comment]
> And OsmAnd is sooo slow on my mobile

True, OsmAnd is slow on first load (but if you run it in background e.g. for track recording / navigation, switching to is very fast). I usually just doubleclick the square android navigation icon and I'm in OsmAnd in less than a second.

If you prefer other editor that can close notes @Strubbl , [EveryDoor](https://wiki.openstreetmap.org/wiki/Every_Door) and [OSMBugs](https://wiki.openstreetmap.org/wiki/OSMBugs) load much faster when doing cold start in my experience.

**Comment by peternewman** [comment]
> If you are certain that you can solve the note via StreetComplete, you can close the note (and download the area around that note again in SC), editing will be unlocked.

@westnordost is it worth allowing notes to be overridden in a few cases now, particularly with overlays? There are now lots of ways you can fix a lot of reasonably complicated notes, e.g. moving a node a bit, or changing the shop type or making it vacant, the only thing actually stopping you is that SC doesn't let you because the note is present!

**Comment by Strubbl** [comment]
This would help me a lot, e.g. in Munich, where i opened several hundreds of notes for shops, because the shop websites were not available anymore. With notes it is easier to find the needle in the haystack of shops, which might be outdated. And it is a pity, that i cannot fix the issue right in front of the new or vacant shop (except of course via closing the note anyhow complicated with another app).

**Comment by westnordost** [comment]
@peternewman I don't see how this could work. It remains the case that not **all** notes can be solved via StreetComplete, and it will never be the case. So, how should the "in a few cases now" work?

**Comment by mnalis** [comment]
> Or i whish for the notes quests to be able to disable them manually via the quests settings

@Strubbl StreetComplete [Expert Edition fork](https://github.com/Helium314/StreetComplete/) at least has that possibility - to disable notes quest same as any other quest (something I too find very useful, but which was rejected for mainline SC - see https://github.com/streetcomplete/StreetComplete/issues/3532)

> Or a hide/unhide notes functionality via this button

EE fork also has a quick button on main screen to (among other things) switch presets (and since you can disable Notes per-preset, you can more quickly switch notes on/off with it)


>  I don't see how this could work. It remains the case that not all notes can be solved via StreetComplete, and it will never be the case. So, how should the "in a few cases now" work?

I don't know how internal architecture might complicate viability of this, but how I would expect Overlay to work (as they are purportedly intended for little more advanced users) is that Overlays (unlike Quests) **would not be blocked** by existing Note (i.e. if user wants to change something in Overlay, let them, even if some user which left a note via Quest did not). So Overlay would "work in all cases", as "Does a note exist?" check would not be used in Overlay.  
  
Because, just because user was unable to answer a "Quest about X" and left a note (with who-knows-what version of SC), does not mean some other user may not fix (or at least improve) situation there using "Overlay for X" (see https://github.com/streetcomplete/StreetComplete/issues/4529#issuecomment-1283269174)

**Comment by Strubbl** [comment]
> that Overlays (unlike Quests) **would not be blocked** by existing Note

This sounds like a good approach. With overlays i can also fix e.g. existing sidewalk tagging if it is slightly wrong - even when there is no open quest about this anymore due to the existing tagging. Additionally, a note does not block the entire way and thus it can be worked around the note if there would be one.

**Comment by westnordost** [comment]
Are you forgetting that also in overlays you can leave a note instead? If you leave a note in the overlay, you surely want to see the note again when you again tap on the road. Otherwise it will lead to users leaving multiple notes for the same road because they forgot that they already left one or are confused that it doesn't show up

**Comment by Strubbl** [comment]
> Are you forgetting

Yes. Sorry.

**Comment by mnalis** [comment]
> If you leave a note in the overlay, you surely want to see the note again when you again tap on the road

Perhaps the note could be shown when road is tapped, but the user still given the choice if the want to proceed with overlay changes or aborting? (e.g. change Note dialog buttons from single `No` to `No, cancel` and `No, but I want to edit`)
