### ISSUE TITLE
noexit=yes is displayed over road class in object descriptions

### ISSUE THREAD

**Issue by matkoniecz** [streetcomplete/StreetComplete#4695]
See https://www.openstreetmap.org/way/714073113

![screen01](https://user-images.githubusercontent.com/899988/208382361-705caf5e-3b06-40af-8c41-1ad631d756c2.png)

(yes, noexit=yes on way is a bad tagging scheme - but accepted enough to make mass removing it as approach that is not viable)

iD using its presets displays it correctly - see https://www.openstreetmap.org/edit?editor=id&way=714073113#map=19/52.61365/13.43482

![screen02](https://user-images.githubusercontent.com/899988/208382565-93dbbbaf-f00d-4cd8-88b9-33cbdf122bad.png)

This seems distinct from `building=yes` displaying bad labels for multipolygon buildings as `highway=living_street` is defined without catchall.

**Comment by Helium314** [comment]
I suspect the difference comes from SC determining feature by tags only.
iD probably doesn't show _No Exit_ because `noexit=yes` is not valid on a way, but SC doesn't check geometry type, see https://github.com/streetcomplete/StreetComplete/blob/7a976ed3411c537b20d4dc0f76e37da81c8d91cc/app/src/main/java/de/westnordost/streetcomplete/util/NameAndLocationLabel.kt#L75-L76
(now with the cache, such a geometry check might be more feasible)

**Comment by matkoniecz** [comment]
Also, even if points and vertices or way and areas cannot be distinguished we can still distinguish points/vertices from ways/areas.
