### ISSUE TITLE
House numbers in shop overlay

### ISSUE THREAD

**Issue by Dardy87** [streetcomplete/StreetComplete#4702]
I'd like to discuss about shop overlay, many time I mapped some shops and later discovered that its housenumber is already available in osm, so I had to merge node manually in josm after my survey.
In my opinion could be useful if the shop overlay shows also the house numbers, so that if the shop I want to map has already a mapped housenumber the user do not create a duplicate.

**Comment by matkoniecz** [comment]
why you would need or want to merge housenumber and shop nodes?

**Comment by Dardy87** [comment]
It's a very common way to map shops with addresses without inserting 2 nodes. I can see it almost everywhere, not only in Italy. I just did this simple overpass query to verify it.

```
[out:json][timeout:25];
// gather results
(
	nwr["shop"]["addr:housenumber"]({{bbox}});
);
// print results
out body;
>;
out skel qt;
```
It's also allowed in the [shop wiky](https://wiki.openstreetmap.org/wiki/Key:shop).

**Comment by rhhsm** [comment]
It's also useful to show house numbers of buildings in the shop overlay, so the shop node can be added within the correct building area

**Comment by westnordost** [comment]
Housenumbers are not shown because they often overlap with shop names. It has been initially so in testing, but it turned out that then some shops/icons would not show and instead the housenumbers were shown. This specific issue might have been solved in #4522 which means that housenumbers could be switched visible again. I am going to check this in a moment.

---

That you can map shops onto housenumbers (i.e. using the same node) is not planned either and this is actually quite deliberate. Merging shops onto preexisting housenumbers sounds like a somewhat questionable practice to me:

There are several different accepted ways to map housenumbers:
- on the `building=*` outline itself (only if the building only has one housenumber)
- on the actual `entrance=*` vertex of the building at which number is signed (this is the most precise)
- as free-floating node(s) within the `building=*` outline. Often seen where the building entrances are not micro-mapped on buildings which have several housenumbers

So, when you find free-floating nodes with `addr:housenumber` within building outlines and **without** `shop=*` or similar, you can be pretty sure that they refer to an actual signed building entrance, e.g. leading to apartments or offices in the floors above, or it is some service entrance. 
So, unless the particular building is a strip mall and thus only consists of shop entrances, merging the free-floating housenumber node with the shop actually destroys the information that there is a regular entrance to the building there. And if it is a strip mall, then the node with the housenumber should have had a `shop=*` on it already.

It is accepted to also add the address information on shop nodes within buildings. But to differentiate "real" housenumbers from just the address information of shops, many  data consumers do not consider or show the housenumber on shops.

**Comment by westnordost** [comment]
> Housenumbers are not shown because they often overlap with shop names. It has been initially so in testing, but it turned out that then some shops/icons would not show and instead the housenumbers were shown. This specific issue might have been solved in https://github.com/streetcomplete/StreetComplete/issues/4522 which means that housenumbers could be switched visible again. I am going to check this in a moment.

It looks like this is not an issue anymore, so housenumbers can be made visible for the shops overlay.

**Comment by matkoniecz** [comment]
> It's a very common way to map shops with addresses without inserting 2 nodes.

1) adding two nodes is not a problem
2) in many cases (where address matches to building 1:1) you can add house number info on building outline (maybe not in Italy) and give address info by locating shop object within building
3) in cases where address is assigned to entrance merging shop and address is not really correct
4) merging addresses and shops makes deleting defunct shops far more annoying

Yes, this is common but it should not be encouraged and spending extra effort to support it is not a good idea.

**Comment by Dardy87** [comment]
> > It's a very common way to map shops with addresses without inserting 2 nodes.
> 
> 1. adding two nodes is not a problem

Yes, not a problem but in this way routers can't never correlate addresses with shops (imagine for example if you type an address on Google maps, it automatically correlate the shop)

> 2. in many cases (where address matches to building 1:1) you can add house number info on building outline (maybe not in Italy) and give address info by locating shop object within building

It's true but not applicable in Italy as building->address is not a 1:1 relation (very often for a building there are more than 1 housenumber)

> 3. in cases where address is assigned to entrance merging shop and address is not really correct

Why not? the only case I can imagine where this is true is for example a mall, where there are many shops and one building entrance, in all the other cases shop has its own entrance.

> 4. merging addresses and shops makes deleting defunct shops far more annoying

True, but I think that delete defunct is not so common as the substitute and for this StreetComplete work very well, if a shop is different I can select it and change the type, and also if vacant I can't use it.

> Yes, this is common but it should not be encouraged and spending extra effort to support it is not a good idea.

In my opinion StreetComplete should not decide how to map things, for this there is already an active community and clear (not always :P) wiky on what you can do and not.
StreetComplete should "only" speedup the mapping applying standard mapping (so prevent manual errors). Say that should not be encouraged seems to me to negate a standard mapping that is available almost everywere and also documented (not only in Italy).

I know that things to do are many and you are not so many, in any case StreetComplete is a very good app, so thanks to you all!

**Comment by Dardy87** [comment]
> > Housenumbers are not shown because they often overlap with shop names. It has been initially so in testing, but it turned out that then some shops/icons would not show and instead the housenumbers were shown. This specific issue might have been solved in #4522 which means that housenumbers could be switched visible again. I am going to check this in a moment.
> 
> It looks like this is not an issue anymore, so housenumbers can be made visible for the shops overlay.

With the last beta release I can see housenumber, it's a good thing even if the housenumber is not editable.
But I can see that the housenumber overlap with the shop Icon.
In my opinion there are to soultions to this issue:

- do not show the housenumber if it's a shop (it is shown correctly later when I tap on it)
- move the housenumber under the icon


![WhatsApp Image 2022-12-28 at 22 05 10](https://user-images.githubusercontent.com/4279340/209872147-79819fbc-7423-4341-8f2e-60d74178c029.jpeg)

**Comment by westnordost** [comment]
> But I can see that the housenumbers overlap with the shop icon.

Oh. I didn't notice that when I tested the change. Unfortunately, neither of your two suggestions is technically possible. So, maybe remove the housenumbers again? After all, the housenumber is visible when you tap on the shop.

**Comment by matkoniecz** [comment]
> In my opinion StreetComplete should not decide how to map things, for this there is already an active community and clear (not always :P) wiky on what you can do and not.

SC should not push weird new tagging unconsulted with community or mapping known to be unwanted. But big part of SC design is deciding how it should map things as many tagging decisions are made automatically.

**Comment by Dardy87** [comment]
If no solutions are technically possibile we can close this task, I did
this suggestion to make shop layout more complete and versatile (sometimes
it's useful to see where numbers are disposed to place shop more precisely)
but in any case it already speedup work.
Thanks again for your effort.


Il Gio 29 Dic 2022, 02:21 Tobias Zwick ***@***.***> ha
scritto:
