### ISSUE TITLE
Bicycle boulevard shows as missing bike path

### ISSUE THREAD

**Issue by duemoselund** [streetcomplete/StreetComplete#4709]
When activating the Bike Path overlay, streets with the tag Bicycle boulevard is displayed as red i.e. missing bike path information rather than as blue since Bicycle boulevard seems to override Bike Path in StreetComplete. 
![Screenshot_20221230_121616_StreetComplete](https://user-images.githubusercontent.com/11139391/210064780-a997cc2b-fdc1-45af-8351-3c05dbf93035.jpg)

**Comment by matkoniecz** [comment]
Affected way: https://www.openstreetmap.org/way/11831576#map=18/56.14814/10.19994

**Comment by westnordost** [comment]
My guess is that is shows it that way because of `cycleway=shared_lane`. I.e. a cycleway **is** specified, but it is incomplete (does not say what kind of shared lane).

A missing `cycleway=*` on a bicycle boulevard is not shown in red, however, it makes sense to show it in red if it is incomplete or invalid, no?

**Comment by westnordost** [comment]
Well I'll close this then. I think the current behavior is fine. That you cannot edit this situation as long as it is a bicycle boulevard is inconvenient but hopefully it does not appear often.
