### ISSUE TITLE
Use "System Default" theme by default

### ISSUE THREAD

**Issue by xmha97** [streetcomplete/StreetComplete#4710]
Please use the "System Default" theme by default.

![Screenshot_2022-12-30-21-07-20-110_de.westnordost.streetcomplete.jpg](https://user-images.githubusercontent.com/23485114/210098648-fa1f68b4-770d-4c0e-8f3a-a25651cc8de0.jpg)

**Comment by westnordost** [comment]
Actually, I think "Auto" should be removed altogether. Why would you let SC switch between light and dark theme automatically but not the rest of your phone as well? @ENT8R what do you think?

**Comment by ENT8R** [comment]
I think the auto option is still a leftover from the time when a system-wide dark mode was not yet widely supported. Since Android version 10, where a system-wide dark mode was introduced, the percentage of people using this setting should not be too large. However, some users might still use this setting before Android 10, so maybe it is reasonable to keep this option for Android versions before 10 but remove it for more recent versions?
And if you decide not to remove this option, [`MODE_NIGHT_AUTO`](https://developer.android.com/reference/androidx/appcompat/app/AppCompatDelegate#MODE_NIGHT_AUTO()) should probably be replaced with `MODE_NIGHT_AUTO_BATTERY`, since the first one is deprecated.

**Comment by mnalis** [comment]
> Why would you let SC switch between light and dark theme automatically but not the rest of your phone as well?

Because your phone does not have that functionality? Even on phones that have system-wide dark/light mode like my newer EMUI12-based phone (which used to be Android10, but nowdays I can't even tell as they removed that information from `About` screen) might not have system time-based schedule for  turning dark-mode on/off? My older phone I use for SC I don't think even has a concept of Android-level dark/light modes.

So I would definitely **leave `Auto` option in**. I'd also be **_against randomly removing options from preferences_** depending on android version, that is the recipe for user confusion, especially if there is not a technical reason why it _must_ be done (if there was such a technical reason, I'd still prefer the option to be _greyed out_ instead of removed, with extra link appearing leading to explanation why it cannot be selected).  

---

As for making `System Default` the SC default on new installs, I definitely see the reasoning for it, and even somewhat lean towards that idea. ..

However, one should note that doing so **_would likely reduce discoverability_** of different themes (i.e. with `Auto` being the default, the user using the SC in various times of the day will be exposed to different SC themes, so knowing that there are choices, might decide to choose the one they like better. I do know know if Android11 and newer automatically switch system-wide dark/light modes _by default_? Older ones like mine definitely do not have that capability, so users would not be exposed to different themes, so they'd probably not be aware they exist, even if they dislike the currently displayed theme).

**Comment by westnordost** [comment]
Currently, 87% of all StreetComplete users on Google Play use Android 10 and above.

**Comment by xmha97** [comment]
For Android 10 and earlier:
Set "Auto" theme by default.

For Android 10 and later:
Set "System default" theme by default.

(VLC's strategy for choosing a default theme is this)

Note: An option should not be removed, even in Android 10 and later, the Auto option can be useful.

**Comment by mnalis** [comment]
> Currently, 87% of all StreetComplete users on Google Play use Android 10 and above.

And when was feature time-based auto-switching Android light/dark mode implemented? Because I'm not seeing it in my Android 10 (EMUI 12). Maybe that is Android 11 or newer (or is only present in _some_ Android 10 versions?). Sadly I don't have access to anything newer than that Android 10, so can't test. 

>For Android 10 and earlier:  Set "Auto" theme by default.
>For Android 10 and later: Set "System default" theme by default.
> (It's VLC's strategy for choosing the default theme)

@xmha97 That sounds good to me; but do you know what it does if the Android version is **exactly** 10 ?

**Comment by xmha97** [comment]
> Do you know what it does if the Android version is exactly 10 ?

Set the "System default" theme by default on Android 10,

because system-wide dark mode has been introduced on Android 10 (although it was beta in older Android)

https://developer.android.com/about/versions/10/highlights#dark_theme

**Comment by mnalis** [comment]
> https://developer.android.com/about/versions/10/highlights#dark_theme

Does it **change automatically by time of day** in Android 10, though? (Which is what SC "Auto" mode does, and is quite convenient default, especially as SC bright theme is hard on eyes in the evenings, and SC dark theme has problems being usable in the bright daylight - e.g. see discussions in https://github.com/streetcomplete/streetcomplete-mapstyle/pull/141).

**Comment by HolgerJeromin** [comment]
Android 10 does support manual dark mode but not switching to it by time.
(I do switch the mode with the app macrodroid though.)
Android 11 has the timebased dark mode.

**Comment by mnalis** [comment]
>  Android 11 has the timebased dark mode.

Then perhaps Android 11 (and higher) should default to _"System Default"_ SC theme, and previous versions to _"Auto"_ SC theme?
