### ISSUE TITLE
"cycleway:left=separate" should not imply "oneway:bicycle=no"

### ISSUE THREAD

**Issue by slasherfun** [streetcomplete/StreetComplete#4715]
Hi!

**How to Reproduce**
In StreetComplete, with the "cycleways" layer enabled (but maybe also without using the "is there a cycleway" quest?), pick a one-way street, and specify that it has a separately mapped cycleway on its left side.
StreetComplete will add two attributes to two way:
- `cycleway:left=separate`
- `oneway:bicycle=no`
Example: https://www.openstreetmap.org/way/22715945 v34 > v35 (changeset [130663547](https://www.openstreetmap.org/changeset/130663547))

**Expected Behavior**
StreetComplete should not add `oneway:bicycle=no`, as the street selected is still one-way (bicycles *may* run on the opposite direction on the separately mapped path on the left side, but that's not necessarily the case)

**Versions affected**
v50.1

Let me know if you need additional input.

**Comment by westnordost** [comment]
Can you link to a wiki documentation that exclaims this? I see it is possible to argue in both directions here. And while it is not documented in the wiki clearly which method is preferred, we will get somewhat different tagging practices, regardless of which method one app decides to tag.

I have no stake in this, but just to represent the opposing standpoint here:

There is a reason why the `separate` value exists at all. And that reason is to indicate that the given street indeed has a cycleway, but it has been mapped separately. So, data consumers that are interested **in less level of detail** know still the cycleway situation without doing a spatial fuzzy search for nearby `highway=cycleway`. (Otherwise we would just put `cycleway=no`.)
Since the road in question indeed **has** a cycleway in the direction opposite to the oneway flow, it is correct to mark the road as being not a oneway for bicyclists at all. This also enables for example router applications that not specifically look for `highway=cycleway` etc. to still output a correct route for bicyclists.

**Comment by slasherfun** [comment]
I couldn't find a wiki page that mentions this specific case, no.

But I don't agree with the "Since the road in question indeed has a cycleway in the direction opposite to the oneway flow" reasoning: to me, having `cycleway:left=separate` states that there's a separate cycleway on the left side of the current way, but it does *not* mean that you can necessarily run on the opposite direction on this cycleway, even if it's on the left side (exemple: https://goo.gl/maps/uT4xwkKQYGNxrAWw5 for example, although this street has been redesigned since that picture has been taken)

**Comment by westnordost** [comment]
Hmm, so your line of argumentation is that one can not always assume that the direction of the separately mapped cycleway is the one that is expected.

Fair enough, but your example shows a cycle lane. Cycle lanes are always mapped on the road-way itself. StreetComplete even has support for such things now:

https://user-images.githubusercontent.com/4661658/210270205-b7248509-a6c9-42dd-9b3f-6b97486bfdb9.mp4

A cycle track on the left side of a oneway road that goes in flow-direction? I guess it would be theoretically possible too, even if we can't come up with a real life example right now.

But then again, this is similarly supported by StreetComplete: I think your should be able to reverse the direction of the "separate cycleway" too.

**Comment by slasherfun** [comment]
Two lines of argumentation on my side:
- having a separate cycleway with a flow going in the opposite direction doesn't make the main/larger/central/cars way two-ways for bicycles (I get your "big picture" point, I agree that there should be a way to summarise detailed street mapping into a single big way, but I don't think this should be done this way)
- having a separate cycleway on the left side doesn't necessarily mean that you can go in the opposite direction on that cycleway: it's usually the case as it's definitely the best practice, but it's not always the case (my example is actually a cycle track, since there's a (small) physical separation between the main part of the street and the "cycle part", but it's close enough to the main road so that it's been mapped as a `cycleway=track` and not as a separate cycleway)

**Comment by westnordost** [comment]
In this case I propose that you address this in the forum. Whatever consensus comes out of the discussion can then documented and subsequently be implemented in the app.

Basically, it comes down to how `bicycle:oneway` (=~ vehicle access restrictions) should be interpreted (in relation to `cycleway=separate`):
1. Should it always refer to the street as a whole (i.e. including potentially separately mapped cycleway) or
2. Should it refer to the whole street only if the `cycleway` situation is not mapped on a separate way?

Or in other words, should access restrictions refer to always streets as a whole or to individual OSM ways?

When you post it in the forum, would you post the link here so that I can monitor it?

**Comment by slasherfun** [comment]
There you go: https://community.openstreetmap.org/t/when-mapping-a-cycleway-separately-should-the-oneway-attribute-on-the-main-way-reflect-the-global-main-way-cycleway-situation-or-should-it-be-strictly-about-the-main-way-situation-without-regard-to-the-situation-on-the-separate-cycleway/7504

**Comment by westnordost** [comment]
So, I think the topic more or less concluded to the point that _"`cycleway:left=separate` should not imply `oneway:bicycle=no`"_.

The remaining question is, should SC remove a `oneway:bicycle=no` if the "it is mapped separately" option is selected, or (just) never touch that tag? I'd say yes, but in the forum, two cases where it shouldn't be removed were mentioned:

> 1. local laws generally allow cycling against oneways unless explicitly forbidden (unsure if this exists)
> 2. cyclists aren’t required to use the separate cycleway and could also use the main road (explicit or implied bicycle=optional_sidepath)

On one I do not really think that this actually exists. After all, oneways can also be so slim that it would be impossible to go in contra-flow even with a bike. 
Number two may theoretically exist, through negligence or something if the traffic authority forgot to remove that sign when they built a dedicated cycleway? However, my take is, to not remove now wrong information in 99.9% of cases when updating it would be worse than taking into account that such a unicorn case **may** exist. @matkoniecz wrote earlier somewhere that in such weird cases, one can always leave a note and tag the situation outside of StreetComplete.

**Comment by matkoniecz** [comment]
also, I would expect that in case of numer two mapper should select option "can drive on road in opposite direction" or leave note, "has separately mapped cycleway" is not really correct here

**Comment by Woazboat** [comment]
> After all, oneways can also be so slim that it would be impossible to go in contra-flow even with a bike.

Unfortunately that never stopped any traffic planner from trying to route bikes through it. In my local area there's a narrow oneway street that has a contraflow bike lane (signposted, painted and all) where cars more or less need to drive on the bike lane because otherwise they wouldn't fit.

**Comment by westnordost** [comment]
That's an advisory bike lane, right?

**Comment by Woazboat** [comment]
Yes, it's an advisory bike lane. (So this issue wouldn't apply, just mentioned it for illustration purposes)
