### ISSUE TITLE
Cycleway segregation + overlay: New ... option "it's a different type of way"

### ISSUE THREAD

**Issue by SLMapper** [streetcomplete/StreetComplete#4716]
**Use case**
For the Cycleway segregation quest:
When being asked how the cycleway and footway are laid out, there should be an answer to tell that actually this is not a shared cycleway/footway at all.

**Proposed Solution**
There should be a new option under the ... menu: "it's a different type of way".
Answers could be the ones from the bicycle overlay for a separate way.
In addition this list should also include `hw=track` (**also add this option for the bicycle overlay**).

![way selection in bicycle overlay](https://user-images.githubusercontent.com/104768113/210227537-f8b7c251-becb-4399-b3ab-0d1842d718f6.png)

If not done using the bicycle overlay list, at least the following ones should be there:
- it's a path (no sign)
- it's a track (no sign / agricultural only sign)
- it's a cycleway only (signed)
- it's a footway only (signed)

**Comment by westnordost** [comment]
> For way-based questes

Which quests exactly?

**Comment by SLMapper** [comment]
I will check and come back with a list

**Comment by SLMapper** [comment]
Thanks @westnordost I checked and actually I think only the _Cycleway segregation quest_ and _Bicycle overlay_ are applicable here. I have updated the title and description accordingly.

**Comment by westnordost** [comment]
What makes a track a track is somewhat badly defined in OSM. See the very very long and partly emotional discussion in the iD issue tracker about it and then the subsequent Pull Request to add aliases to the name for a "track". Hence, if StreetComplete would enable its users to display + re-tag paths to tracks, it would need to state a clear and short description of it. This is not really possible. So, in cases where a path is displayed in the bicycle overlay as a track or the other way round, it is better to leave a note with a photo or something, in my opinion.

Regarding an other-answer for the cycleway segregation quest "It's not a foot+cycleway...": Fair enough, could be done. However, I don't really see that it is worth implementing. After all, if a path has already been mapped as both `foot=designated` and `bicycle=designated`, I'd expect that this was due to a mistagging or something has been changed to be somewhat rare. And for rare cases, people can leave notes.

**Comment by SLMapper** [comment]
Thanks to explain the reasons to me. I agree that it's probably not worth implementating it and will close the issue now.

Just out of curiosity: which iD issue did you mean? https://github.com/openstreetmap/iD/issues/4092?

**Comment by matkoniecz** [comment]
@SLMapper Probably yes. Note other discussions linked there and https://github.com/openstreetmap/id-tagging-schema/pull/288 and there were also some discussion elsewhere and so on.
