### ISSUE TITLE
Support increments to  house number with letters

### ISSUE THREAD

**Issue by dpriskorn** [streetcomplete/StreetComplete#4724]
**Use case**
as a user I want to add house numbers to a street without a lot of typing 

I went to a street today that had:
7-9 on one house 
11-13 on the next etc

I expect the up arrow to understand this combination and increment wisely. 
One press on 7-9 -> 8-10
One more press 8-10->9-11
And so forth

This is way faster than fiddling with numbers and dashes using the keyboard 

Another case:
3a -> 3b
Another case
3a-d -> 4a-d

This can of course be discussed. Maybe we need more buttons and settings to make it work nice for the user. 

Also see the keypadnumber app which is fantastic and wayyy faster than streetcomplete

**Proposed Solution**

**Comment by westnordost** [comment]
This is not planned. I tried it out in the initial implementation during development, it didn't feel right. Too often the guess would be wrong.

**Comment by westnordost** [comment]
For example it is equally likely or more likely that the next housenumbee after 7-9  is 11.

Same with 3a ( there could be hs 3 and 3a, no 3b). More so,  it is vastly more likely that when there is a 3d, there is no 3e (etc) but the next is a 5. So to be consistent, the app does not enumerate the letters at all instead of cutting it off at a certain letter.
