### ISSUE TITLE
points revert to same value a couple seconds after solving 

### ISSUE THREAD

**Issue by playmobilmeister** [streetcomplete/StreetComplete#4757]
Hello, 

### Problem:

My star / point count has been stuck at 662 for the past week although I am completing quests and will continue to do so nonetheless. 

As soon as I solve a quest I get the points, then a few seconds afterwards the count reverts back to that value (but the change still applies and the quest is not presented anymore)

### What I tried:

- deleting the cache 
- logging out and in again

### Session info:
v50.1
Android 10
Nokia 6.1

### other stuff
Btw, Love this app and using it to map my city for the past 3 weeks or so. What a great idea ! Contributing monthly from now on.

**Comment by westnordost** [comment]
You first get granted the point when solving a quest immediately.

Then, when the answer is uploaded, that point is deducted again only in case the upload failed due to an error during upload - usually a conflict (someone else edited exactly the same thing before you).

I don't think that every single answer you gave run into a conflict, so maybe there is something else wrong.

Can you reproduce this with a specific quest for a specific element? If yes, can you link to the element on osm.org so that we may look at the history of the element?

**Comment by playmobilmeister** [comment]
Just Answered no on whether [ this zebra crossing](https://www.openstreetmap.org/node/5362143336) has an island. points reverted to 662 almost immediately but the change itself registered

**Comment by Helium314** [comment]
You are using [StreetComplete EE](https://github.com/Helium314/StreetComplete), which actually has a message on first start that solving quests will not count towards statistics.
