### ISSUE TITLE
Distinguish between cycling may be permitted and cycling not permitted on paths/footways

### ISSUE THREAD

**Issue by frankie2784** [streetcomplete/StreetComplete#4760]
Can we include a way to tag/see when cycling is explicitly banned on a footway or other off-road path?

For example, I've just tagged this way as bicycle=no, but it still shows on SC as "cycling may still be allowed":

![Screenshot_20230119-083400.png](https://user-images.githubusercontent.com/19356194/213300488-d6f2af59-aa08-44a1-933e-559b93ffa0f4.png)

This tag is particularly useful to assist in trip routing.

In some jurisdictions, such as where I live, cycling is legal on footpaths only for certain users (children and accompanying parents, for example) - so local routing engines need to somehow take this nuance into account. But a way to tag paths where cycling is explicitly not allowed at all would add additional certainty about the status of those paths.

![PXL_20230118_215919899.jpg](https://user-images.githubusercontent.com/19356194/213304846-3e5aa006-1b15-4350-b873-dbc99db230c3.jpg)

**Comment by matkoniecz** [comment]
See #4714 #4669 and likely other

**Comment by frankie2784** [comment]
> See #4714 #4669 and likely other

Thanks @matkoniecz - lots of back and forth in those threads, was there a final conclusion or is it still an open issue?

**Comment by matkoniecz** [comment]
https://github.com/streetcomplete/StreetComplete/blob/5e0244e6aa4de3da77069af4ffc57a1b17c81e5d/app/src/main/java/de/westnordost/streetcomplete/overlays/cycleway/SeparateCyclewayForm.kt#L33-L55 is still applying, though some people (as seen in this issues) tried to convince @westnordost to change that. Not checked whether this issue contains new arguments.

**Comment by frankie2784** [comment]
I'm not entirely persuaded by the line of argumentation in that code comment. This is how I read it:

1. `bicycle=no` should only be considered legitimate if it is explicitly signed, but because there is no way to tell if there is a sign based on the tag `bicycle=no` alone, then SC shouldn't display it.

- Okay, I guess. Although I don't see anywhere on the wiki that states that `bicycle=no` requires signage (https://wiki.openstreetmap.org/wiki/Tag:bicycle%3Dno). In fact, the second example on the page is not explicitly signed, it is a legal example, which appears to be a legitimate use of `bicycle=no`.

2. Because SC requires `bicycle=no` to be explicitly signed, but also deems it too unreasonable to expect users to find signs, it disallows this option altogether.

- Maybe a similar argument to why speed limits are disabled by default? The difference is that if someone wants to tag speed limits, at least they have the option of re-enabling the quest. No such option for `bicycle=no`.

3. Displaying/allowing explicit tagging of `bicycle=no` is not wise because defaults vary between countries and so determining if cycling is allowed, when there is no sign either way, is left up to the user's "loose" interpretation of local laws.

- Okay, but I don't see any fatal problem in this. If a surveyor deems it appropriate to tag a particular feature as being forbidden for cyclists, then surely that's their prerogative to use their judgement. If appropriately displayed on the map, other users can easily change the designation if they feel there's been a misinterpretation on any particular way. This doesn't seem all that dissimilar to other quests/overlays on SC.

--

Is the ultimate concern that OSM will be overrun by errant `bicycle=no` tags if this option is enabled? Has there been feedback that this particular issue is too difficult or confusing for users to make a reasonable judgement call on? Is there perhaps a way to frame the quest to remove some of the ambiguity, such as "cycling explicitly prohibited here"?

**Comment by westnordost** [comment]
No,  you misunderstood. It's very simple. The "no bicycle" and "yes bicycle" options are missing bcause there is no tag that denotes that that particular access restriction has been set because of a sign. 

Longer explanation: It's not about what should be considered legitimate but what can be considered verifiable on the ground. SC only shows as option what is verifiable on the ground. 
Distinction between `bicycle=yes` and `no` is only guaranteed to be verifiable if there is a sign.  But there is no way to tag whether there is a sign or not.

**Comment by westnordost** [comment]
Or even shorter: Show me a way to tag that a `bicycle=no` or `yes` has been set explicitly through a sign and these options will be added.

**Comment by westnordost** [comment]
See also this fruitless discussion where I asked the simple question about whether there is a tag for denoting that there is a sign that immediately went off topic and went nowhere https://community.openstreetmap.org/t/fahrradfahrer-frei-von-situationen-unterscheiden-in-denen-radfahrer-implizit-erlaubt-sind/6478/45

So please forgive me if I sound sore about this topic,  because I am.

**Comment by frankie2784** [comment]
Interestingly, "bike-only path" (i.e. `foot=no`), which is basically the
inverse of `bicycle=no` doesn't seem to have the same requirement for proof
of signage.

**Comment by frankie2784** [comment]
> So please forgive me if I sound sore about this topic,  because I am.

I'll steer clear of fanning the flames.

**Comment by westnordost** [comment]
> Interestingly, "bike-only path" (i.e. `foot=no`), which is basically the inverse of `bicycle=no` doesn't seem to have the same requirement for proof of signage.

Because it is always signed or demarcated in one way or another.  Otherwise it would not be a cyclists-only path (but a path)

**Comment by frankie2784** [comment]
> > Interestingly, "bike-only path" (i.e. `foot=no`), which is basically the inverse of `bicycle=no` doesn't seem to have the same requirement for proof of signage.
> Because it is always signed or demarcated in one way or another.  Otherwise it would not be a cyclists-only path (but a path)

This is true, and makes sense. "Shared-use paths" on the other hand are not always marked. Or at least SC is not specific enough that users are required to check for signs or other markings to distinguish them from a more generic "path" or simply a "footway" that cyclists happen to ride on. In fact, some shared use paths in the outer suburbs of my city are not signed but "known" to be a SUP by locals, and are tagged as such (rightly in my view).

What I'm getting at is that SC doesn't seem to worry about where the information was sourced from when displaying info about existing `bicycle=designated` tags, or how the user decides if a new way is or isn't, for example, a SUP. It couldn't possibly, because tagging conventions don't currently allow for such things, and policing it would be a bit of overkill - instead SC's decision (sensible in my view) is to simply let the user see what's been tagged as what, be as clear as possible about what these tags mean, and give them the option to update it if necessary.

Really, the same approach could be taken for `bicycle=no`. As long as the default remains something like "designated for pedestrians, cycling may still be allowed" alongside options for both "cycling is explicitly designated" and "cycling is explicitly prohibited" - putting the power into users hands seems to me the best approach.

That's my last word on this, as it's obviously a point you're not interested in rehashing. But I suspect you will continue to get requests to reconsider this point, as cycling is important to many people, as is being able to capture this info where it's appropriate.

**Comment by westnordost** [comment]
> "Shared-use paths" on the other hand are not always marked. 

In which case one should select just "path". "shared-use path" means that the path has been explicitly designated as shared-use. Not necessarily signed, could be by markings too, I guess.

> Really, the same general approach to bicycle=designated could be applied to bicycle=no. As long as the default remains something like "not designated for cyclists/designated for pedestrians, cycling may still be allowed" alongside options for both "cycling is explicitly designated" and "cycling is explicitly prohibited" - putting the power into users hands seems to me the best approach.

Oh so you mean...
- `highway=footway` - "designated for pedestrians, cycling may still be allowed"
- `highway=footway + bicycle=no` - "cycling is explicity prohibited"

This doesn't work. Because `bicycle=no` says nothing about that it is explicitly prohibited. It could be implicitly prohibited.

Example:
One mapper added `bicycle=no` to all the sidewalks as per his interpretation of the legislation (e.g. cycling on sidewalks is forbidden).
Then, a StreetComplete mapper visits the place. He sees these footways mapped as "cycling is explicitly prohibited". Since he sees no sign, he corrects it to "designated for pedestrians, cycling may still be allowed", thus removing the `bicycle=no`, i.e. removing correct information. 

So, I'd rather insta-close a few duplicate requests than taking the blame on that StreetComplete users effectively vandalize data (see above).

--- 

I am very interested in this point being rehashed. It's very simple: There needs to be a way accepted by the community to denote an access restriction as sourced by a sign, that's it.

**Comment by frankie2784** [comment]
> Example:
> One mapper added `bicycle=no` to all the sidewalks as per his interpretation of the legislation (e.g. cycling on sidewalks is forbidden).
> Then, a StreetComplete mapper visits the place. He sees these footways mapped as "cycling is explicitly prohibited". Since he sees no sign, he corrects it to "designated for pedestrians, cycling may still be allowed", thus removing the `bicycle=no`, i.e. removing correct information. 

Could just drop the word "explicitly" then?

The awesome utility of SC that I see is in easily viewing and tagging local conditions, wherever that may be. Obviously there's some nuance in this particular case that you're not comfortable with (although I suspect opportunities for users mistagging or disagreeing about how to categorise certain features in SC is not exactly unique to `bicycle=no`).

Maybe one solution is to begin to document, similar to advisory lanes and other country-specific rules, where local laws prohibit cycling on the footpath? That way any time `highway=footway` or `highway=sidewalk` is encountered without a `bicycle` tag in one of those countries, it's assumed that "cycling is prohibited", elsewhere it's "cycling may be allowed", thus avoiding the majority of opportunities for confusion? Dunno, possibly not robust enough given local laws can differ even within countries.

Regardless, somehow I doubt the tag `bicycle:type=sign` will be forthcoming very soon at a global level, as nice as that would be.

**Comment by westnordost** [comment]
> Could just drop the word "explicitly" then?

No,  see the comment in the code. Implicit "yes" or "no" is not information surveyable on the ground. 

Same as for `maxspeed`. If there is no sign,  Streetcomplete also does just tag that there is no sign instead of the Implicit speed limit. 

> Regardless, somehow I doubt the tag bicycle:type=sign will be forthcoming very soon

`bicycle:signed=no` or something with `source:bicycle` sounds more fitting to me. 
But anyway, that's up to you, or anyone else interested in this. It can take as little as asking on the tagging mailinglist or forum what tag would be most fitting to denote whether an access restriction is signed or not.
