### ISSUE TITLE
Add "Disable this quest type" to the "Other answers"

### ISSUE THREAD

**Issue by sabi0** [streetcomplete/StreetComplete#4771]
**Use case**
I am new to StreetComplete. And do not know yet which types of quests I would not want to complete. E.g. I would probably not be measuring widths of roads.
The list of quest types is very long. And going through all of them to decide which I do not want is tiresome. And some of them might not even appear in the places I go to.
Also sometimes I would like to see possible answers to decide if the quest is "for me".

**Proposed Solution**
I would like to suggest therefore to implement a way to disable a particular quest type directly from the map.

Here is how it could work:
- I tap a quest on the map
- if I decide I do not want this quest I press the "Other answers" button
- there is an option "Disable this quest type" in the menu
- once disabled this way all the quests of this type disappear from the map
- and a toast message like this is shown for a few seconds:
> "How wide is the road here?" quest is disabled. Undo
- with the "Undo" being a link upon clicking which the quest type will be re-enabled

**Comment by westnordost** [comment]
IMO such an entry directly in the "other answers" menu would be too prominent. Also, whenever there is just one "other answer" (which is "Can't say..."), no menu is shown at all and "can't say" is shown directly in the button bar.

Maybe what could be done is to show another button next to "Hide" and "Leave note" in the "Leave a note instead?" dialog. Though, this is a little out of context and it would kind of take the space that the #1992 feature would otherwise take up.

**Comment by mnalis** [comment]
This is interesting idea, but as noted would  clutter "Other Answers" (and always avoid the optimization that we directly show `can't answer` if it is the only other answer), which is bad... 

So it would be nicer to trigger it in some other way. 

- Perhaps, if user 3 times in a row selects `no, hide` for same quest type it could be offered to disable that quest permanently (along with instructions where to enable/disable the quests if they later change their mind"? That would require no extra UI and would automagically pop-up when user is probably wanting to avoid that quest altogether, but then is also not so easy to trigger at will for more experienced users. (and it also might have some false positives)

- Or, when users select `can't say` we could offer not only `Hide` and `Leave note`, but also `Disable this quest type permanently` (but in less words of course).

- Or (to attack the problem from the other angle) we could simply make default list of quest smaller (e.g. not including quests that user might find uninteresting like `line width`) and after xxx quests solved suggest to the users to enable other quests if they find them useful (e.g. open the quest selection menu if they answer they are interested in more quests)  

> Also, by the way, this UI element is called a "[snackbar](https://m2.material.io/components/snackbars)" and I generally find it to be really bad design

With this I agree, such auto-disappearing snackbars are bad UI if they provide any useful information at all, and it is especially horrible when they offer the optional action (as `Undo` in example above). 
It is also highly stress-inducing (at least to me): _"You have 3 seconds to read, translate, and understand this message before it self-destructs, then make a decision about it, and coordinate your hand to press at this tiny portion of the screen if you are sure you've made a right choice, or otherwise your once-in-a-lifetime chance to understand what just happened will be gone forever; but no pressure. Ooops, too late!"_ :scream:  

So I'd much prefer _"Are you sure"_ `yes`/`no` dialog for such confirmation instead, which would actually **additionally** be good place to display info **why**/for which groups of people/purposes is this quest **useful**, as it might look useless for the mapper at first), but they might change their opinion if the reason is described.  (providing such information about _"why some quest is actually useful"_ has been proposed few times before, but of course I'm now unable to find those threads)

**Comment by sabi0** [comment]
When I open a quest and discover it's not something I'd want to answer I just got back, not press "Can't say" (that might even be hidden under "Other answers").
And then I remember the quest icon and try to avoid pressing it ever again.
So I would not be able to discover this secret path of "cancel 3 times in a row to get to the disable dialog".

Maybe quests in the settings could have dedicated "Details" pages with the "Enable / Disable" checkbox in the top right corner?
The screen would explain why the quest is useful, mention why it's never offered in the Netherlands, etc.

And the menu shown on a quest icon tap on the map would have a "Details" link leading to that page, where the quest could also be disabled.
No magical "3 cancels in a row" spells, no confirmations. Plain and simple.

**Comment by mnalis** [comment]
> And the menu shown on a quest icon tap on the map would have a "Details" link leading to that page, where the quest could also be disabled.

That might work. So after showing a quest text (e.g. _"Does this bench have a backrest?"_  mini-icon like  &#x2139; or &#x24D8; could be shown, and when clicked it would describe the usefulness of a quest (that would require people writing such an explanation for each quest, of course!) and offer to disable showing this quest in the future.

Would such a workflow be intuitive to you (i.e. if we didn't just talk about it, would you have clicked on that "&#x2139;" and disabled such a quest that you find noninteresting, or not?) 
Or did I misunderstood how you envisioned it?

**Comment by westnordost** [comment]
> that would require people writing such an explanation for each quest, of course!

Yeah, well that is obviously out of question.

**Comment by mnalis** [comment]
> Yeah, well that is obviously out of question.

Well, that might be some work, and outside the specific scope of this particular issue, true.
But it would play quite well with it, I think (as proposed above)

I'm **not proposing writing a full-fledged essay about each**.  For majority of the quests, it might even be auto-generated from achievements that quest accomplishes, and only for some percentage of the quests (especially ones found dubious by the community) it could extended manually (in a matter of optional `override val questReasoning="..."` in that quest) with an extra short sentence like:
- _"Shape of roof helps in nicer-looking 3D models"_ or 
- _"Presence of backrest on a bench is useful for elderly and otherwise impaired persons to get adequate rest"_ or 
- _"number of steps helps routing apps to disadvantage some routes more than others, e.g. when using bicycle routing smaller number of steps is much preferred"_ or
- _"knowing if the way is lit helps in finding better and safer driving routes in the night, avoiding potentially dangerous neighborhoods in the night, etc."_ 

The we would **not** need to write an explanation for every quest manually; e.g. quest with `LIFESAVER` achievement could automatically get `This quests helps emergency services`. 

I do not think initial number of translation strings would be too big (maybe half a dozen quests, plus a dozen achievements). If we later found extra quests which people do not understand a usefulness of, they could be added later.

Would that be more acceptable? Anyway, it was just an idea how to fix this issue it in sensible way (while also adding extra value!), feel free to discard it if you don't like it.

**Comment by sabi0** [comment]
On the second thought it is not completely obvious that disabling a quest can be accessed by clicking the "ℹ".

Maybe the initial version could use a regular checkbox where the "ℹ" would have been?
And tapping it to uncheck would show a simple "Do you really want to disable this quest type?" confirmation.

Later on this dialog could be extended to also include description why the quest is useful, list associated achievements, etc.

**Comment by rhhsm** [comment]
> That might work. So after showing a quest text (e.g. _"Does this bench have a backrest?"_ mini-icon like ℹ or ⓘ could be shown, and when clicked it would describe the usefulness of a quest (that would require people writing such an explanation for each quest, of course!) and offer to disable showing this quest in the future.

It would also be a good place to add a link to the OSM wiki for much more detailed info about the quest

**Comment by arrival-spring** [comment]
How about if a long press on a quest icon brought up the option to hide that quest type? Would that be discoverable enough?

Then wondering about what else would go in that menu, maybe an option to show only this quest?

**Comment by westnordost** [comment]
A long press on the quest type should rather bring up a menu for #124

**Comment by TailyFair** [comment]
I found this after creating [#664](https://github.com/streetcomplete/StreetComplete/issues/6449)

As a new user, I faced a bit of resistance to hide quest types that I don't feel like doing.

**Comment by TheBicPen** [comment]
+1 to being able to hide a quest type more easily. My suggestion is to use the long-press menu for this. Long-pressing on a quest bubble as opposed to a map location with no bubble would add an additional context menu item(s) to hide quests. "Hide this quest" and "Hide quests of this type" seems reasonable to me. This does make the menu larger, but some of the existing menu items could be removed as they pertain to a map location rather than a quest. Namely the "Create track recording" item.
