### ISSUE TITLE
Cycleway resurvey quest applies incorrect tags for one-way streets

### ISSUE THREAD

**Issue by tapetis** [streetcomplete/StreetComplete#4774]
As shown in the video below, the cycleway quest applies incorrect tags when the "Is this still the cycling situation here?" question is asked for one-way streets.

**How to Reproduce**

https://user-images.githubusercontent.com/6892794/215330723-e8d2c598-acc5-46c9-a81d-728a3b6b008d.mp4

The way shown in the video is https://www.openstreetmap.org/way/109539742. This way is tagged with both `cycleway=lane` and `cycleway:right=lane`, which is, of course, suboptimal tagging. However, the bug also appears on the way https://www.openstreetmap.org/way/37873577, which is tagged as just `cycleway=lane`. The error occurs not only when "none" is selected, but also with other options with different obscure results.

Please note, the ways above are only examples and the chosen option does not reflect the real situation on the ground.

**Versions affected**
v50.2

**Comment by westnordost** [comment]
I think what is happening here is that the left and right side are being pre-filled with "ambiguous" (as it could be a cycle lane or an advisory cycle lane) and as "ambiguous" values are generally shown as if they are not set, they are not shown at all. Now, the user sets the right side and only the right side is being re-tagged while the left side remains the same.

So, the actual issue is that both sides of a oneway street should be shown to the user also if the side in opposite flow direction has some invalid or ambiguous value (and not only if it has a known value).
