### ISSUE TITLE
Street names are automatically title-cased in locales where they shouldn't be

### ISSUE THREAD

**Issue by balsoft** [streetcomplete/StreetComplete#4784]
Because of [this line](https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/view/controller/AutoCorrectAbbreviationsViewController.kt#L51), whenever one is typing in a name for a street or a place, it always capitalizes the first letter of each word in the street name. While this is great for many languages where uppercase letters are used at the start of each word in toponyms, this is a problem in other languages where that's not the case. For example, in Georgian language, while capital letters are included in the Unicode standard, they are not used for title casing. This makes it really annoying to input street names, as one has to edit the words afterwards to remove the capitalization.

I'm not sure what the best solution for this would be. Perhaps add a list of "exception" languages which are not to be titlecased, or even a simple toggle to disable the feature.

**How to Reproduce**

Start solving a "Street Name" quest somewhere in Georgia, type in street name in Georgian. The first letters are automatically capitalized, even though they shouldn't be.

Here's what it looks like:

https://user-images.githubusercontent.com/18467667/215851298-f3f8194d-74bb-4378-a82d-e9f1d5544de4.mp4

**Expected Behavior**

No tilte-casing occurs.

**Versions affected**

v50.2 (latest from F-Droid)

**Comment by westnordost** [comment]
So this first needs some research in which languages (or countries?) a title case is not used. Would you care to do this research?

**Comment by westnordost** [comment]
By the way, you can tap on the street it belongs to instead of writing it each time manually.

**Comment by balsoft** [comment]
> By the way, you can tap on the street it belongs to instead of writing it each time manually.

Yep, I'm aware of that; However, this also happens for place names (which are quite common here, in the form of microdistricts, and here I can't use that feature with place names).

**Comment by balsoft** [comment]
> So this first needs some research in which languages (or countries?) a title case is not used. Would you care to do this research?

I think a good first approximation would be to look at endonyms of countries, to see which ones are and aren't using title-casing: https://en.wikipedia.org/wiki/List_of_countries_and_dependencies_and_their_capitals_in_native_languages

**Comment by matkoniecz** [comment]
I found https://bugs.ruby-lang.org/issues/14839 which is quite related

>  MTAVRULI may not be used in the same contexts as Upper Case in other scripts. One very clear case is that MTAVRULI is only used for ALL CAPS. But this is covered by Unicode data, which means that .capitalize will be a no-op. The main area I can see where this can create problems is "Convention over Configuration" situations where all of lowercase, Uppercase, and ALLCAPS are used. If only lowercase and Uppercase are used, Georgian can be treated as an unicameral (only one case) script, similar to e.g. Hiragana. If only lowercase and ALLCAPS are used, then Georgian can be treated as a bicameral (two cases) script.

> The current implementation of String.capitalize is not just a problem in Georgian, but also in other languages like Dutch. Words beginning with „ij“ must be titlecased with a leading „IJ“, e. g. „IJsbeer“ (polar bear). 

hunting down that "Unicode data" part of Unicode may be helpful

**Comment by balsoft** [comment]
Also, this might be related: https://en.wikipedia.org/wiki/Capitalization

**Comment by matkoniecz** [comment]
Given situation with Georgian alphabet this is a bug in `uppercase` function.

Curiously

```
import java.util.Locale

fun main(args: Array<String>) {

    
    val locale = Locale.forLanguageTag("ka")
    val capital = "თირაკლი".substring(0, 1).uppercase(locale)
    println(capital)
    println("თირაკლი აბაშიძის ქუჩა".capitalize())
    println("თირაკლი აბაშიძის ქუჩა".uppercase())
}
```

on [Kotlin playground](https://play.kotlinlang.org/#eyJ2ZXJzaW9uIjoiMS44LjAiLCJwbGF0Zm9ybSI6ImphdmEiLCJhcmdzIjoiIiwibm9uZU1hcmtlcnMiOnRydWUsInRoZW1lIjoiaWRlYSIsImNvZGUiOiJpbXBvcnQgamF2YS51dGlsLkxvY2FsZVxuXG5mdW4gbWFpbihhcmdzOiBBcnJheTxTdHJpbmc+KSB7XG5cbiAgICBcbiAgICB2YWwgbG9jYWxlID0gTG9jYWxlLmZvckxhbmd1YWdlVGFnKFwia2FcIilcbiAgICB2YWwgY2FwaXRhbCA9IFwi4YOX4YOY4YOg4YOQ4YOZ4YOa4YOYXCIuc3Vic3RyaW5nKDAsIDEpLnVwcGVyY2FzZShsb2NhbGUpXG4gICAgcHJpbnRsbihjYXBpdGFsKVxuICAgIHByaW50bG4oXCLhg5fhg5jhg6Dhg5Dhg5nhg5rhg5gg4YOQ4YOR4YOQ4YOo4YOY4YOr4YOY4YOhIOGDpeGDo+GDqeGDkFwiLmNhcGl0YWxpemUoKSlcbiAgICBwcmludGxuKFwi4YOX4YOY4YOg4YOQ4YOZ4YOa4YOYIOGDkOGDkeGDkOGDqOGDmOGDq+GDmOGDoSDhg6Xhg6Phg6nhg5BcIi51cHBlcmNhc2UoKSlcbn0ifQ==) is without triggering this bug.

**Comment by balsoft** [comment]
So, I've found the [titlecase](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.text/titlecase.html) function which seems to do exactly what's needed in our case. #4785 should make use of that function. That said, I have never written Kotlin before, and I couldn't be bothered to build it locally (I'm sorry, I don't have the best PC with me currently).

**Comment by HolgerJeromin** [comment]
@balsoft 
No need to setup build infrastructure:
https://github.com/streetcomplete/StreetComplete/blob/master/CONTRIBUTING_A_NEW_QUEST.md#alternative-to-android-studio

**Comment by matkoniecz** [comment]
https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/screens/user/statistics/CircularFlagView.kt#L154 looks like internal use

But there is also https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/data/meta/Abbreviations.kt#L77 used when abbreviations are expanded, I guess that it also should be fixed (maybe it is not triggered right now if no abbreviations are defined for Georgia)

**Comment by rhhsm** [comment]
It's an issue for Bulgarian too (Стара планина becomes Стара Планина but it shouldn't). My wife, who's fluent in Russian, says it would be wrong in Russian too. So maybe for all languages using Cyrillic script?

**Comment by matkoniecz** [comment]
@rhhsm Can you open a new issue? Here it can be come lost

**Comment by westnordost** [comment]
Uh,  we use title case function now.  If that function returns false results, it is not in our hands to fix it.  The fix for Georgian should have been the fix for any language.

**Comment by mnalis** [comment]
Um, it behaves very strange to me too. Is that [titlecase()](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.text/titlecase.html) supposed to behave differently depending on the language used (because it works the same for me in English and in Croatian)? 

I mean, generally (outside of android), [titlecase](https://en.wikipedia.org/wiki/Title_case) simply means that _"all words are capitalized, except for minor words (typically [articles](https://en.wikipedia.org/wiki/Article_(grammar)), short [prepositions](https://en.wikipedia.org/wiki/Preposition), and some [conjunctions](https://en.wikipedia.org/wiki/Conjunction_(grammar))) that are not the first or last word of the title"_. 

And what android `titlecase()` function seems to provide _simplified_  (see below) version of that wikipedia definition.

There are several issues with such approach:

- instead of using correct wordlists of propositions, conjuctions etc. (which would need per-language databases etc), it seems to assume all words with 3 or less letters are "minor" and all other words should be capitalized (e.g. video `0:42-0:51`)
- it seems to have an annoying bug that it will do capitalization only if word is followed by space (so every last word in a name will not be capitalized even in cases where it should be, at least on my EMUI 12, e.g. video `0:16-0:20`)
- (biggest issue)  **Title case** is generally [mostly used only in English](https://en.wikipedia.org/wiki/Letter_case#Headings_and_publication_titles) (specifically, in Northern American variant of English). In most other languages (at least in Croatian), "title case" is definitely **not a correct way** to capitalize street names (or anything else, for that matter). Specifically in Croatian, proper way of entering street names should be using [Sentence case](https://en.wikipedia.org/wiki/Letter_case#Sentence_case), i.e. _"The first word, [proper nouns](https://en.wikipedia.org/wiki/Proper_noun) and some specified words capitalised"_ (e.g. rest of the video like `0:28-0:38` gets basically everything _wrong_).

So I would suggest using **sentence case** in all countries except USA and maybe a few others (where **title case** might be more proper).

https://user-images.githubusercontent.com/156656/233198104-d233e714-31e0-475f-9fbc-1945dd879d64.mp4

**Comment by westnordost** [comment]
Do you know a source where one can find a list of languages where title case should be used as opposed to sentence case? For street names, place names?

**Comment by mnalis** [comment]
> Do you know a source where one can find a list of languages where title case should be used as opposed to sentence case? For street names, place names?

Uh, unfotunately not, and quick search does not reveal that to me. Wikipedia seems to imply that titlecase it is used [mostly in English speaking countries](https://en.wikipedia.org/wiki/Letter_case#Headings_and_publication_titles):

> Title case is widely used in many English-language publications, especially in the United States. However, its conventions are sometimes not followed strictly – especially in informal writing. 

Quick checking of most common suspects would indicate those do use titlecase:
- USA
- Canada (https://www.openstreetmap.org/relation/2989349#map=17/43.65219/-79.37727)
- UK (e.g. "Trafalgar Square" and abouts https://www.openstreetmap.org/relation/3962877)
- Ireland (https://www.openstreetmap.org/relation/1109531#map=18/53.34879/-6.26314)
- Australia (https://www.openstreetmap.org/relation/5750005#map=17/-33.76677/150.72277)
- New Zealand (https://www.openstreetmap.org/way/44135731#map=16/-42.7412/171.5225)

But of course there are likely more.

**Comment by mnalis** [comment]
Now, if one were feeling adventurous, chatGPT says those countries _might_ be using title case for street or place names:

```
[  "AG",  "AI",  "AU",  "BB",  "BD",  "BE",  "BM",  "BS",  "BZ",  "CA",  "CK",  "CY",  "FJ",  "FK",  "GB",  "GD",  "GG",  "GI",  "GM",  "GY",  "HK",  "IE",  "IM",  "IN",  "JE",  "JM",  "KN",  "KY",  "LC",  "LK",  "MS",  "MT",  "MU",  "MV",  "MW",  "MY",  "NA",  "NF",  "NG",  "NP",  "NR",  "NZ",  "PG",  "PH",  "PK",  "PN",  "SB",  "SC",  "SG",  "SH",  "SL",  "SS",  "SZ",  "TC",  "TO",  "TT",  "TV",  "VC",  "VG",  "VU",  "WS",  "ZA" ]
```

But I wouldn't trust (for anything important) that language model predictor farther than I could throw it :smile:

**Comment by matkoniecz** [comment]
> "title case" is definitely not a correct way to capitalize street names (or anything else, for that matter). Specifically in Croatian, proper way of entering street names should be using [Sentence case](https://en.wikipedia.org/wiki/Letter_case#Sentence_case), i.e. "The first word, [proper nouns](https://en.wikipedia.org/wiki/Proper_noun) and some specified words capitalised"

What about street names named after people?

In Warsaw we have for example street `name=Mordechaja Anielewicza` named after a person (Name Surname form).

**Comment by rhhsm** [comment]
This source http://www.bibnet.be/files/download/525b23b4-d008-433b-bbc2-e24b32872d2b/Regelgeving/vlacc_bronnen/vlacc_bronnenTitelbeschrijven/Hoofdlettergebruik%20per%20taal.html states that compound geographic names (Samengestelde geografische namen) should be capitalised in Dutch, English, Spanish and German, while French is more complicated.
The keyboard app I'm using (Microsoft SwiftKey) does a pretty good job suggesting words with the correct capitalisation. If other keyboard apps do the same, I think we should not use the title case function by default unless we're absolutely sure it is correct for the current input language.

**Comment by balsoft** [comment]
> The SC might as well just make a first letter uppercase (as that sounds pretty common mostly everywhere?)

Well, this issue is specifically about the case where it's not true: in Georgian, upper-case letters are only used for ALL CAPS and not for title-case or sentence-case.

**Comment by westnordost** [comment]
So, I've searched extensively on the OpenSTreetMap. In these countries/languages, street names are (sometimes/often) not title-cased:

<a href="https://ent8r.github.io/blacklistr/?data=SI,HR,HU,SK,CZ,FI,LV,LT,RU,BY,UA,KZ,MN,KG,UZ,TJ,TM,AZ,GE,AM,EE">
<img src="https://user-images.githubusercontent.com/4661658/235802018-a8030458-4b78-47d1-a1d5-59a5a3818028.png">
</a>

(Bulgaria is not amongst them)

**Comment by rhhsm** [comment]
What is the source of info that made you conclude not to include Bulgaria?

**Comment by westnordost** [comment]
I scrolled through the map. E.g. here, ~all road names are title cased: https://www.openstreetmap.org/#map=17/45.66213/25.60465

**Comment by Helium314** [comment]
That's Romania. But still looks similar in actual Bulgaria, e.g. https://www.openstreetmap.org/#map=17/42.12727/24.74976

**Comment by westnordost** [comment]
Whoops, sorry. But I definitely looked in real Bulgaria too yesterday

**Comment by rhhsm** [comment]
Why look on the map when you could have asked me :)

> That's Romania. But still looks similar in actual Bulgaria, e.g. https://www.openstreetmap.org/#map=17/42.12727/24.74976

All streets names in this example are "title case" because they're all named after people (very very common in Bulgaria). The only 2-word name that's an exception is Шар Планина which is wrongly capitalised (it should be Шар планина, `int_name=Shar planina`, just corrected it).

See here https://wiki.openstreetmap.org/wiki/Multilingual_names#Bulgaria for transliteration guidelines for Bulgarian: the examples are copy-pasted from the quoted law.

Maybe the map of the Sofia Metro would be more convincing?
![image](https://user-images.githubusercontent.com/69100427/235978579-07e8d009-389f-459f-9aff-103f8e5529ff.png)

**Comment by westnordost** [comment]
Apart from Bulgaria, are there more countries apart from those I already found where not titlecase should be used? Apparently I did not look closely enough in my swipe.

**Comment by jmontane** [comment]
At Spain, it depends on language used. Note that value of "name" can be in any of the following languages.

- Spanish (es): titlecase, but few words are lowercase (articles and prepositions: el, la, los, las, de, del, de la, de las, de los...)
- Catalan (ca): titlecase, but few words are lowercase (articles and prepositions: el, la, l', els, las, de, del, de la, de les, dels...) + middledot U+00B7 is used as innerword char (titlecase functions sometimes capitalize wrongly letter after middledot) + way type isn't always capitalized (carrer Ample, carrer del Pinter Joan Miró...)
- Occitan (oc): I dont' know. I suspect it follows similar criteria than Spanish
- Galician (gl): I dont' know. I suspect it follows similar criteria than Spanish
- Basque (eu):  I dont' know. I suspect it follows similar criteria than Spanish
- Asturian (ast):  I dont' know. I suspect it follows similar criteria than Spanish

**Comment by westnordost** [comment]
Note that words are currently only automacially titlecased if the word has more than 3 characters. That should take care of all the el, la, las, de, del, van, von, etc...

**Comment by westnordost** [comment]
I started implementing this with a huge list of languages in which no title case should be applied automatically but stopped this after several hours because I realized this automatism is just not worth the extra complexity. After all, it will probably be never 100% correct, there are many languages after all and it was just a small convenience for regions where everything is in title case. The user might as well just press shift then 🤷

**Comment by rhhsm** [comment]
If it's a matter of already having done the basic work but not yet completed the list of languages, then it's worth implementing what has been done so far. Applying title case to languages that shouldn't do that generates wrong data, and that should be prevented as much as possible. If the list of languages that don't apply title case is longer than the one for languages that do, then maybe sentence case should be the default?

**Comment by westnordost** [comment]
No, I am telling you, it is not worth implementing. That's what I wrote in my previous comment. Did you read it? #5105 100% solves this issue by not using titlecase automatically at all. Which is fine, because it is not exactly a major inconvenience for the user to press shift, plus for names ("Avenue Lenin"), the keyboard app usually suggests to titlecase it anyway.

**Comment by rhhsm** [comment]
Sorry for the misunderstanding, I don't even understand what a pull request is :) I agree that leaving the capitalisation to the keyboard app is the best option.

**Comment by westnordost** [comment]
It is a technical term for a suggested change that can be viewed, discussed and commented on on github.
