### ISSUE TITLE
On the carriageway in dedicated spaces does not automatically imply staggered parking

### ISSUE THREAD

**Issue by davidpnewton** [streetcomplete/StreetComplete#4786]
I recently completed a parking quest with the new tagging for way 1137033688 amongst others.

The street has double yellow lines on one side and marked parallel-orientated parking bays within the carriageway on the other. The tagging I would have expected to see for this in the UK would be:

* parking:left=lane
* parking:left:marked=yes
* parking:left:orientation=parallel
* parking:right=no

However in addition to these correct tags parking:left:staggered=yes was also set. Marked parking bays within the carriageway do not automatically imply staggered parking so this tagging is incorrect.

Presumably equivalent tagging is added for right and both depending on exact quest solving sequence.

**How to Reproduce**

Solve the quest as described above.

**Expected Behavior**

Don't set the staggering tag for this quest solving pathway.

Add a further option to explicitly set staggered, dedicated parking bays as there are for on the carriageway without markings and partially on the carriageway without markings. Only show this option when a combination of tags indicates parking is allowed on both sides of the carriageway if possible.

**Versions affected**

51.0 beta 1 and 13.

**Comment by westnordost** [comment]
I presume that you mean "marked parking spaces on the street" with "parking bays within the carriageway".

For reference, this is the road: https://www.google.de/maps/@52.2746449,-1.5334176,3a,75y,67.25h,64.19t/data=!3m6!1e1!3m4!1s4hUA-e8xvpYCQXd087ki_A!2e0!7i16384!8i8192

I don't see any parking markings there. Is this an old photo?

**Comment by davidpnewton** [comment]
"I don't see any parking markings there."

Oh yes you do! You likely just don't realise what UK parking bay markings look like.

The outer edge of the parking bay is marked by the white dashed line almost in the middle of the road. So what I suspect you believe to be a white line in the middle of the road being the dividing line for traffic in different directions in fact denotes the parking bay's extent.

**Comment by arrival-spring** [comment]
This is the offending section:
https://github.com/streetcomplete/StreetComplete/blob/afed9672c20194ccb386a92aabd3f74998a10285/app/src/main/java/de/westnordost/streetcomplete/osm/street_parking/StreetParking.kt#L48-L51

I can't see why `PAINTED_AREA_ONLY` should imply staggered parking

**Comment by arrival-spring** [comment]
This is the offending section:
https://github.com/streetcomplete/StreetComplete/blob/afed9672c20194ccb386a92aabd3f74998a10285/app/src/main/java/de/westnordost/streetcomplete/osm/street_parking/StreetParking.kt#L48-L51

I can't see why `PAINTED_AREA_ONLY` should imply staggered parking

**Comment by westnordost** [comment]
Ah, I see. Well, the selection you are supposed to select here is to ✂️ the road at which the parking starts and ends and select **"on street"** because this option should be selected **regardless** of whether the parking has markings or not.

**"On street only in dedicated spaces"** is meant to be only used for cases where there are just some scattered marked parking spaces along the road. I did hope the illustration would make this clear, but maybe the wording of both these selections could be improved.

StreetComplete generally does not distinguish between parkings with marking and parkings without marking, with the exception you encountered. The reason why this exception exists is to project the situation found in the real world that there is a road and only at some / at a few spaces on the road, there are (single) marked parking spaces but in the rest of the road, it is not allowed to park. You see, that selection exists only to cover that case because I imagine otherwise people would not know what else to select in that case.

Do you think the following would be an improvement?
"On street only in **some** dedicated spaces"

Or do you have another idea how to deal with this?

**Comment by arrival-spring** [comment]
I still don't think that dedicated spaces implies staggered. staggered seems to mean some spaces on each side, so must be used only with `parking:both` not `parking:left` or `parking:right`

I think the distinction between "on street" and "on street only in dedicated spaces" should surely just be the addition of `parking:left:marked=yes` and that matches the descriptions and images.

**Comment by westnordost** [comment]
@arrival-spring 

> I still don't think that dedicated spaces implies staggered. staggered seems to mean some spaces on each side, so must be used only with parking:both not parking:left or parking:right

Yeah, but there is no better tag for that. The `painted_area_only` tag was deleted in the new schema, so I can't just continue to use that tag.

> I think the distinction between "on street" and "on street only in dedicated spaces" should surely just be the addition of parking:left:marked=yes and that matches the descriptions and images.

No, because `parking:left:markings=yes` + `parking:left=lane` just means that the cars park in a marked parking lane on the left. This is very different from a situation where no parking allowed on the whole road except for some marked parking spaces. That's what the "On street only in some dedicated spaces" option is intended for.

While it is possible in the new tagging scheme to specify for any parking whether it has markings or not, this would simply double the amount of selectable options for a kind of information that has borderline no meaningful usecase except for rendering. Hence, StreetComplete neither reads or writes the `markings` information except for this special case.

**Comment by davidpnewton** [comment]
What should be done?

Add an option to put in marked bays all along the length of the road and separate out the staggering option for this just as the staggering option has been separated out for the other tagging scenarios.

**Comment by westnordost** [comment]
Well, I already wrote that it is deliberate that StreetComplete does not differentiate between marked and non-marked. Because, *every* of the selectable options - "on street", "partially on street", "adjacent to street" could be marked or could not be marked. So, differentiating would *at least* add 3 additional options. As I said, this is overkill for a property not really worth distinguishing in the first place.

The option the app wants you to choose in your example (and which is the correct one tagging-wise) is the **"On street"** one.

I suppose the app could be explicit here and add a "(regardless if marked or not)" to the description, but this text would need to be added to **every single selection**. So I wouldn't like that.
Instead, that's why I proposed to make the description of "On street only in dedicated spaces" clearer. Do you have any idea for that? Also,
1. what selection would you have chosen if that option was not available at all?
2. what selection would you choose if that option was not available at all in the case that parking is not allowed except at a few marked spaces alongside the road?

**Comment by westnordost** [comment]
I asked because I am thinking about deleting that option altogether. I would like to have this issue resolved before v51.0 is released

**Comment by arrival-spring** [comment]
I think it would be fine for the option to be removed. Maybe it would lead to more splitting so that people could select "on the road" more precisely, but given the other arguments it is perhaps basically a duplicate option.
