### ISSUE TITLE
Road and path width should not be enabled by default if AR is not available

### ISSUE THREAD

**Issue by matkoniecz** [streetcomplete/StreetComplete#4795]
It seems that they have become enabled by default in latest version as part of migrating away measuring app.

I am on a phone without AR support without measure app installed and Google Play not allowing me to install StreetMeasure.

https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/width/AddRoadWidth.kt#L57

Is proper check for AR support also a part of binary blob that was unfree and therefore migrated away?

On v51.0-beta1 that was not modified, I have reset quests enablement.

<h2 dir="auto">Device info:</h2>

Android build version | V11.0.5.0.QDLMIXM
-- | --
Android release version | 10
Android SDK version | 29
Android build ID | QKQ1.191002.002.V11.0.5.0.QDLMIXM
Device brand | xiaomi
Device manufacturer | Xiaomi
Device name | daisy_sprout
Device model | Mi A2 Lite
Device product name | daisy
Device hardware name | qcom
ABIs | [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit) | [armeabi-v7a, armeabi]
ABIs (64bit) | [arm64-v8a]

**Comment by westnordost** [comment]
> Is proper check for AR support also a part of binary blob that was unfree and therefore migrated away?

Correct. Without that, some checks can be made like for the min Android version, the min supported OpenGL ES version, but whether that **specific device** is supported can only be found through asking that library. There is no public API or downloadable CSV available of the devices that are supported, see https://developers.google.com/ar/devices

What is possible is to download a snapshot of that CSV in the google play console and e.g. bundle that CSV (or in a processed form) into the app. However, the clear disadvantage is that this CSV would need to be updated all the time because new devices are added to the list all the time (because new devices are built all the time). This means, that new devices will not work for that until StreetComplete is updated with the new list. 

IMO this adds too much non-automatable churn to the app maintenance. Otherwise, the best solution would be to create a tiny (PHP based) API (or simple text file) which would just return a list of supported devices, update that regularly and from the app, download that file once or every once in a time. Maybe that downloading of the CSV is automatable the same way getting all the contributors from POEditor is automatable (by scraping the HTML), but this is surely even more effort.

Hence. Maybe theoretically doable in a way that has no caveats, but then too much effort to work on it. Anyone else is free to try this.
