### ISSUE TITLE
Quest suggestion: hairdresser for men/women/all

### ISSUE THREAD

**Issue by FloEdelmann** [streetcomplete/StreetComplete#4833]
### General
Affected tag(s) to be modified/added: [`female=yes`](https://wiki.openstreetmap.org/wiki/Key:female) or [`male=yes`](https://wiki.openstreetmap.org/wiki/Key:male) (for [`shop=hairdresser`](https://wiki.openstreetmap.org/wiki/Tag:shop%3Dhairdresser))
Question asked: **Which customers does this hairdresser serve?**

`male=no` or `female=no` could be tagged together with `female=yes` or `male=yes`, respectively.

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/blob/master/QUEST_GUIDELINES.md)):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by any pedestrian from the outside but a survey is necessary
- [x] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
    → most will probably be `female=yes`+`male=yes`, but the exceptions are not totally rare, see https://overpass-turbo.eu/s/1rx0 and https://taginfo.openstreetmap.org/tags/shop%3Dhairdresser#combinations
- [x] 🕓 Applies to a reasonable number of map data (Worth the effort)
    → see https://overpass-turbo.eu/s/1rwX

### Ideas for implementation

**Element selection:**

```
nodes with
  shop = hairdresser
  and !female and !male and !unisex
```

Or, to cover edge cases like [this one I discovered](https://www.openstreetmap.org/node/4945998997):

```
nodes with
  shop = hairdresser
  and female != yes and male != yes and unisex != yes
```

In this case, should the respective other existing keys should be deleted, in addition to setting `female=yes` / `male=yes`? Or should the unusual `only` value also be considered valid?

**Metadata needed:** None.

**Proposed UI:** Simple text selection: "Women only" / "Men only" / "Both"

---

Note: this is a follow-up suggestion to #4829. The `unisex` tag is considered "burnt" and should not be tagged by StreetComplete. For the quest selection, it can still be considered.

**Comment by Discostu36** [comment]
I find it an important information for non-binary people to know if a hairdresser is gender neutral or if they have to decide to use a door for men or a door for women. In my opinion, a quest without a third option should not be done.

**Comment by mnalis** [comment]
If `unisex` is consider burnt,  we should use this quest to clean it up. I.e. match on

```
nodes with
  shop = hairdresser
  and female != yes and male != yes
```

and then upon answering the quest remove any existing `unisex` tag.

**Comment by Discostu36** [comment]
Please do not remove tags from OSM without an accepted deprecation proposal.

**Comment by matkoniecz** [comment]
> If unisex is consider burnt, we should use this quest to clean it up.

The problem is that it is burnt without a proper replacement existing for some of tasks it was tried to be used.

**Comment by mnalis** [comment]
> I find it an important information for non-binary people to know if a hairdresser is gender neutral or if they have to decide to use a door for men or a door for women. In my opinion, a quest without a third option should not be done.

While I agree that it is important information for non-binary people, there are few issues with that third option, though:

- how is causal mapper to know when non-binary people are welcome? Do hairdressers in your area usually put such notices on the door?
- how would you **actually tag that third option**? Current `male`/`female`/`unisex` is not adequate. To the best of my knowledge, there are no widely accepted unambiguous tags currently existing (there are few ideas: [gender_segregated=*](https://wiki.openstreetmap.org/wiki/Key:gender_segregated) , [enby proposal](https://wiki.openstreetmap.org/wiki/Proposed_features/Add_enby_as_counterpart_to_male_and_female), [Gender proposal](https://wiki.openstreetmap.org/wiki/Proposed_features/Gender), and I think that was at least one other one which I'm missing). Any of them would need to have community acceptance before tagging them in SC, I think.  There is always an option to leave a note, though.


 - see somewhat related discussion in https://github.com/streetcomplete/StreetComplete/issues/2603 
 
> Please do not remove tags from OSM without an accepted deprecation proposal.

Dunno. When I edit manually, I map it clearly (i.e. would replace `unisex` with `male` and `female` on survey). But I understand your concern.

**Comment by mnalis** [comment]
Also, at the quest level, I find those problems:

- There a difference between [sex](https://en.wikipedia.org/wiki/Sex) and [gender](https://en.wikipedia.org/wiki/Gender). Which of them is this quest to be about? Or is it **not** about either of them, but about **haircut style** (e.g. if a male with long hair wants to have to stereotypical female haircut, can they go into _"hair saloon for women"_? What about if they put lipstick on? It seems to me, that there are issues not only at OSM level, but at societal level that are unclear - even on per-country basis, much less something that is accepted worldwide) 

- also,  I do not think [":chipmunk: Easily answerable by any pedestrian from the outside but a survey is necessary" ](https://github.com/streetcomplete/StreetComplete/issues/4829#issuecomment-1436051740) has been addressed satisfactorily?

**Comment by mnalis** [comment]
>>  Please do not remove tags from OSM without an accepted deprecation proposal.
> There are some cases where it is entirely fine without deprecation proposal (though not in this specific case).

Note that [unisex=*](https://wiki.openstreetmap.org/wiki/Key:unisex) wiki **does** however say:

> In case of conflict with other gender-based tags (e.g. [female](https://wiki.openstreetmap.org/wiki/Key:female)=*), resolve in favour of the more specific tag.

Which seems to suggest that mappers should replace `unisex` tag if usage is clear `male`+`female` (or leave note to later add `description=*` or something if the `unisex` meant something different in that specific case).

**Comment by Discostu36** [comment]
> * how is **causal mapper to know when non-binary people are welcome**? Do hairdressers in your area usually put such notices on the door?

On the contrary, if there is no sign about gender on the door, I'd consider it a unisex hairdresser where every person is welcome.

> * how would you **actually tag that third option**? Current `male`/`female`/`unisex` is not adequate. 

In my opinion, it is adequate and the definition is quite clear: Unisex clothing, toilets or hairdressers can be used by anybody, they are gender-neutral. But as can be seen on wiki, there seem to be people with a different opinion on that. 

So from my perspective, there are now these options, as long as there is no clear definition on wiki:
1. Wait for a proposal that solves the conflict with a clear definition of unisex key. Don't do this quest until that is the case.
2. SC chooses the unisex definition that means "all (non-)genders can use it" and creates the quest like proposed in the original issue

Of course, theoretically, there is a third option, but I hope nobody will argue for that:
3. For SC there is only male and female

**Comment by mnalis** [comment]
> On the contrary, if there is no sign about gender on the door, I'd consider it a unisex hairdresser where every person is welcome.

That assumption seem culturally dependent to me (and incorrect in Croatia, see below). 

There are basically 4 categories in Croatia (ignoring for the moment rampant confusion about [sex-vs-gender](https://www.healthline.com/health/sex-vs-gender)) e.g. man-vs-male, and them being called the same at least for the last hundred years, so it is likely they haven't caught up with non-binary distinctions: 

- those which have signed _"za žene i muškarce"_ (literally meaning **_"for woman and man"_**). Most popular category. I'd tag those `male=yes`+`female=yes`. Can do both "za žene" and "za muškarce" (although barber services for males might be missing sometimes).
  <details>
  <summary>pic</summary>

  ![mf1s](https://user-images.githubusercontent.com/156656/220411014-e8857af6-7899-4a9a-8093-a4fb1a6bdfc7.jpg)   ![mf2s](https://user-images.githubusercontent.com/156656/220411023-c6972c97-5ac8-4305-b0c0-a3419f4c34c1.jpg)

  </details>

- those which have signed _"za žene"_ (literally meaning **_"for woman"_**). Implying that  (Croatia being quite conservative in that regard) they specialize in "woman hairstyles" (esp. long hair styles, undulations, highlights, hair inserts, hair washing & conditioning & bleaching & coloring, feminine perfumes, etc. Also sometimes offer makeup services and other stuff (although I'd tag `shop=beauty` instead if it offers more then extra makeup to go with hairstyle). Second most popular, as (see conservative part) women are willing to pay most money for extravagant hairstyles taking long to make. Also, stereotypically, often one of the most popular places to get/spread gossip. I'd tag those `male=no`+`female=yes`.

  <details>

  <summary>pic</summary>

  ![fs](https://user-images.githubusercontent.com/156656/220413601-2112983c-149f-406c-909e-326181b01a0f.jpg)

  </details>

- those which have signed _"za muškarce"_ (literally meaning **_"for man"_**). It implies mostly: that they don't have anyone who can do "women hairstyles", don't offer hair coloring, has no feminine parfumes etc. It also oft implies that you can get barber services there too. I'd tag those `male=yes`+`female=no`. With few exceptions, usually much more spartan offers, much quicker turnaround time, and cheaper than ones for woman. 


  <details>

  <summary>pic</summary>

  ![ms](https://user-images.githubusercontent.com/156656/220413644-ddf2832d-8f80-4b42-8599-eb826dfebb43.jpg)

  </details>

- those which are **_unsigned_**. It is **not** to be assumed that they are for both man and women. I would not tag it, unless I intended to chat with employees if they do both man or women or not. If anything, it is to be assumed that is probably small single-person company (called "obrt" here), which is only advertising information required by law, usually in typized format like this: 

  <details>

  <summary>pic</summary>

  ![unsigned](https://user-images.githubusercontent.com/156656/220413690-951d7fd4-c41d-40f6-a7e4-b193a768c421.jpg)

  </details>

---

**So, I'd say in Croatia signage is probably mostly about the services available, and not about entrance restrictions / segregation based on sex (or even gender).** Similar to e.g. the Kosher restaurant -- you can enter and eat there even if you're not Jew, but do not expect to be able to order your favorite pork ribs.

In fact (AFAIK) in Croatia if you are registered for selling services to the public (i.e. you are not registered as private club with membership, where you can make up mostly any rules), and you are not covered by certain exceptions (mostly cases where genitalia or breasts or areas very close to it may be exposed - like toilets, saunas, massage parlors, gym communal showers / dressing rooms, doctors etc) **you are not legally allowed to refuse service dependent on protected discrimination criteria** (e.g. you may not refuse service because someone is black, or woman, or transgender, or of islamic religion, or minority, or living with partner outside of church marriage etc.). You _may_ still discriminate on non-protected differences (e.g. "suit&tie only", "no swimsuits" etc.)

**Comment by westnordost** [comment]
Yes. `male` and `female` on hairdressers is about hairstyles / barber services, that's clear.

Anyway, seems a useful thing to ask. I'd consider whether barber shops (i.e. "for men") should get tagged with just `male=yes` instead of also with `female=no` etc. because that's what usually on the sign. The sign will never say "not for women" but "for men".

**Comment by Discostu36** [comment]
So the question would be more like "What are the signed customers of this hairdresser"? But this would still leave the question of what to tag if there is none.

**Comment by westnordost** [comment]
Hm, I guess both `male:signed=no` and `female:signed=no`

**Comment by Discostu36** [comment]
Yeah, maybe.

**Comment by mnalis** [comment]
It seems to me mostly defined then. Only question that remains is:

- should the quest _permanently_ ignore any hairdressers which have `unisex=*` tag set, or
- should the quest be asked regardless of whether `unisex=*` is set,  and when user has chosen **current state** of the hairdresser set `male=*` / `female=*` tags and remove `unisex=*`.

As  [unisex=* wiki](https://wiki.openstreetmap.org/wiki/Key:unisex) says:

>   In case of conflict with other gender-based tags (e.g. [female](https://wiki.openstreetmap.org/wiki/Key:female)=*), resolve in favour of the more specific tag.

(which the user on the ground definitely knows the best what is the current situation).

---

Whatever the answer, it seems to be relatively easy quest to make. 
Are there any takers interested in [trying to implement this quest](https://github.com/streetcomplete/StreetComplete/blob/master/CONTRIBUTING_A_NEW_QUEST.md)?

**Comment by Discostu36** [comment]
> should the quest permanently ignore any hairdressers which have unisex=* tag set, or

I think it should ignore items with unisex=yes and ask for items with unisex=no. It should not delete unisex tags.

**Comment by mnalis** [comment]
As nobody else volunteered, I'll implement this quest. 

I'd still like @westnordost opinion on this choice: https://github.com/streetcomplete/StreetComplete/issues/4833#issuecomment-1464557177 (I myself and the wiki find it preferable to make situation unambiguous when we have the chance with mapper on the ground, rather then to simply _"sweep the problem under the rug"_ - but not everybody seems to agree).

**Comment by westnordost** [comment]
I agree with your statement. What better time to make something unambiguous than when someone is actually on-site. However, no point in fighting against windmills: If iD pushes a different tagging, it makes little sense to push the other way.
