### ISSUE TITLE
Support the "opening soon" lifecycle stage of shops

### ISSUE THREAD

**Issue by andrewharvey** [streetcomplete/StreetComplete#4855]
**Use case**
After shops are vacant it's common to see a "Coming Soon" sign about which shop will open next. Ideally we could capture this information.

**Proposed Solution**
In the UI where we currently have "It's vacant..." we could have an extra option "It's undergoing construction" and proceed to ask what kind of feature it is (optional) and also optionally the name.

The shop would be tagged with `construction:*=*`.

**Comment by matkoniecz** [comment]
https://overpass-turbo.eu/s/1s0m - around 2000 `construction:shop` and `construction:amenity`, more than expected though not all qualify for SC quest

**Comment by mnalis** [comment]
Yeah, while that information might be recorded, I don't see much use:
- it would complicate transition from `vacant` to `construction` (that extra `Other answer` should invoke  the form which  would ask two things (name + type, thus breaking _":atom_symbol: Atomic quests: Per quest, only one thing should need to be answered by the user"_ tenet)
- it would also complicate transition from `construction` to `active` (e.g. when feature is actually completed, the user would have first to confirm if recorded type and name are _actually correct_, or if it is _something else_ instead)
- so basically, the users would have to do work **twice**, with more complex interfaces, for no real extra benefit (most data consumers will just ignore `construction:shop=*`)

Only slight advantage I see from `It's undergoing construction` other answer that might be somewhat useful is that if it is marked as `construction:shop=yes` instead of `disused:shop=yes`/`shop=vacant`, then StreetComplete might ask **_more often_** quest `It was marked as vacant, what is there now?` (as vacant shops might stay vacant for years, one that is actively being constructed might be complete in weeks).

While that could be accomplished with simple `Other answer` which just changes `shop=vacant` to `construction:shop=yes` without most of the issues outlined above, I'm still not sure if it would be discoverable enough or useful enough.

**Comment by westnordost** [comment]
I agree with @mnalis and also do think that the low usage count of this tag is not worth the time to implement such a quest anway.
