### ISSUE TITLE
Location is not updating after unlocking phone

### ISSUE THREAD

**Issue by michalgwo** [streetcomplete/StreetComplete#4858]
While walking around with SteetComplete opened, when I lock it for some time, change location, and then unlock it in another location, the app doesn't update the location, even if I click the location button in the bottom right corner. The only solution I found to update the location is to restart the app.

**How to Reproduce**
1. Open StreetComplete, find, and zoom to your location
2. Lock your phone
3. Walk somewhere
4. Unlock your phone
5. Click the location button in the bottom right corner - the app still shows the location where I was before locking the phone

**Expected Behavior**
The app should show the current location

**Versions affected**
StreetComplete version: v51.0
Android 10
Xiaomi Redmi Note 7

**Comment by mnalis** [comment]
- if you keep waiting for some time after pressing location button, does it eventually move to correct location? Because, if the GPS was inactive while phone was locked, it might need more than a few seconds to re-acquire the location.
- can you try with `v51.1` if the situation is different? (there have been some changes related to location-acquiring in that version)
- might be related to aggressive power-saving features of your phone, see https://dontkillmyapp.com/ on possible workarounds to whitelist StreetComplete (if that powersaving is source of the problem)

**Comment by Helium314** [comment]
As far as I understand the location button does not start location updates.
Location updates are only requested in `MainFragment.onLocationIsEnabled`, which is called in the `onStart` lifecycle callback if location is allowed and enabled.

I would not expect 51.1 to fix this, at least not if GPS location worked properly before locking the phone.

**Comment by michalgwo** [comment]
I tried to replicate it on StreetComplete v51.1, but I couldn't, everything worked fine, but as this does not happen every time when I unlock the phone, I'm not sure if it was only my luck that the bug didn't occur this time.

**Comment by westnordost** [comment]
What @Helium314 wrote is correct. Only if the location was off (in the Android settings), the button would ask the user to turn on location. The app listens for changes on location enablement. The app starts requesting location on...
- start (i.e. the user tabs back into the app)
- location was enabled in the settings

So, what happened is that when you tabbed back into the app, the app started to request the location automatically but just didn't get any new location from the system (yet). The button has nothing to do with this.

Unlike @Helium314 , I do think that this issue might have been fixed in v51.1 because under certain circumstances (when the GPS reports back with a wrong timestamp for the current location) , StreetComplete would not accept that location as current location. @Helium314 fixed something so that the app would also accept locations with a wrong timestamp.
