### ISSUE TITLE
Ask if restaurants have a toilet

### ISSUE THREAD

**Issue by arrival-spring** [streetcomplete/StreetComplete#4860]
**Use case**

Mainly to open up the other toilet quests (changing table and wheelchair) it would be good to ask if restaurants (and cafes and fast food with indoor seating) have a toilet. In some countries, such places with indoor seating are required to have a toilet, so maybe this breaks the "no spam" rule.

It is currently enabled by default and is asked for
```
shop ~ mall|department_store
or highway ~ services|rest_area
or tourism ~ camp_site|caravan_site
```

and has the comment
```
// only for malls, big stores and rest areas because users should not need to go inside a non-public
// place to solve the quest. (Considering malls and department stores public enough)
```

Baby changing table (disabled by default) is asked for

`amenity ~ restaurant|cafe|fuel|fast_food or shop ~ mall|department_store`

Wheelchair quest (disabled by default) is asked for

`toilets=yes and name`

**Proposed Solution**

At least I feel this would qualify for a disabled by default quest, or could it be added in as is?

That is change to
```
shop ~ mall|department_store
or amenity=restaurant
or (amenity~cafe|fast_food and indoor_seating=yes)
or highway ~ services|rest_area
or tourism ~ camp_site|caravan_site
```

**Comment by matkoniecz** [comment]
See https://github.com/streetcomplete/StreetComplete/issues/391 and https://github.com/streetcomplete/StreetComplete/issues/1272

**Comment by arrival-spring** [comment]
#391 Seems to be saying not to ask for restaurant and cafe as it requires entering the place. This seems to be an argument for adding a new quest which is disabled by default.

#1272 I had not seen and I see the points that it is spammy to ask in some countries. However if we had such a list of countries where restaurants always have a toilet then in those countries we can just ask wheelchair and changing table straight away (and also add toilet=yes).

And in the other countries we add restaurant etc. to this quest.

(Actual implementation may be harder than I make it sound)

**Comment by rhhsm** [comment]
Why not ask if restaurants have a changing table/wheelchair accessible toilet directly? Answer options could be yes/no/there's no toilet at all

**Comment by arrival-spring** [comment]
In summary, how about the following?

In some countries (research to be done) it is safe to assume that all restaurants have a toilet (for customers). However, not all of these toilets will be wheelchair accessible or have a changing table. The latter is useful information. So in these countries, the wheelchair toilet accessibility quest and changing table quests should be extended to ask for `amenity=restaurant` and `amenity~cafe|fast_food` with seating (by checking either `indoor_seating` or not `takeaway=only`). The quest needs to add `toilet=yes` and add an other answers option for adding `toilet=no` (there is no toilet here).

In all other countries, restaurants may or may not have a toilet for customers, so `AddToiletAvailability` is basically duplicated, but disabled by default as it requires entering a place, and asks for restaurant, cafe and fast_food.

**Comment by westnordost** [comment]
The whole "disabled by default" thing got a bit out of hand. The original reason this was introduced is because when certain decisions on the quest guideline were made, it wasn't acceptable to just delete those quests that already got implemented but didn't comply with all the quest guidelines.

This quest suggestion does not only require you to go inside (and ask), I also seriously doubt the usefulness of adding this information to all the restaurants etc., even in countries where restaurants (etc) are not required to supply a toilet for customers. 

Given the low amount of people who change the enablement of quests, there is no way one could ever reach a comprehensive mapping of restaurant-custumer-toilets (and keep it up to date 😫). This is different from special interest things like diets (vegan, vegetarian, ...) because one can assume that some people care very much about this kind of data and will actively search for ways to add and maintain it. But I have not heard about any restaurant-toilet mappers. So, I do think it is a waste of time to implement and also a waste of time to map it at all because there is no way at all this will ever be comprehensive enough that it will be considered to be shown by data consumers.

**Comment by arrival-spring** [comment]
Fair enough.
However I would say that there are wheelchair accessibility mappers, and this information is already shown in a number of places. So how about extending the wheelchair toilet quest to asking for restaurants, bars and pubs and adding an other answer to say that there is no toilet?

**Comment by arrival-spring** [comment]
`AddWheelchairAccessToiletsPart`
Currently only asked for `toilets=yes`...

**Comment by arrival-spring** [comment]
Correct

**Comment by westnordost** [comment]
Could you put this into a new ticket and close this one, for better overview?

**Comment by arrival-spring** [comment]
Done in #4866
