### ISSUE TITLE
Add the possibiloty to have aerial imagery background

### ISSUE THREAD

**Issue by letypequividelespoubelles** [streetcomplete/StreetComplete#4865]
**Use case**
When I want to add shops with the shop overlay in India, most of the time I prefer not to, because of the poor OSM data : buildings aren't mapped (or very badly). So in SC's map I just see a road, and I don't know where to put shops. Therefore I'm using OsmAnd as an editor, but it's way less powerfull than SC overlay.

**Proposed Solution**
SC should enable the user to switch from map to aerial imagery background while in (shop, address) overlay mode. It would be even better to have aerial imagery background with OSM road data on top of it to check that OSM data and imagery are aligned.

Few things :
1.  how to deal when imagery and OSM data and imagery aren't aligned?
2. which imagery to use ? Global one like bing, or region specific (better but more work) ? 
3. do we give the possibility to the user to align imagery with osm data ?
4. to be honnest, if this is implemented, it will lead to a micromapping overlay, to add recycling, bench, hydrant, etc :) Is it the direction you want to give to SC ?

**Comment by matkoniecz** [comment]
See #56

**Comment by Helium314** [comment]
@letypequividelespoubelles if you have root access, you can actually enable satellite imagery by adding `<string name="theme.background_type">AERIAL</string>` to your StreetComplete shared preferences file (remove or switch to `MAP` for switching back).
But satellite / aerial imagery will not automatically download if you download quests for some area, which is one of the reasons it hasn't been enabled in the end.

**Comment by mnalis** [comment]
>  When I want to add shops with the shop overlay in India, most of the time I prefer not to, because of the poor OSM data : buildings aren't mapped (or very badly). So in SC's map I just see a road, and I don't know where to put shops. 

Are you on foot? In similar cases I usually just walk up to the door,  and in SC direction-field (as well as the trail drawn where I was walking beforehand) make it quite clear where a new POI needs to be positioned, even if map is totally blank otherwise -- just in front of that direction-field indicator.

Or, you might want to use time at home to map the buildings and other things visible from aerial view on desktop computer, in advance of your on-the ground surveys later (if you use [JOSM](https://wiki.openstreetmap.org/wiki/JOSM), [building_tools](https://wiki.openstreetmap.org/wiki/JOSM/Plugins/BuildingsTools) plugin makes mapping building extremely fast. Double your impact! :muscle: 

> Therefore I'm using OsmAnd as an editor, but it's way less powerfull than SC overlay.

If you still insist on aerial imagery, might I suggest you take a look at [Every Door](https://wiki.openstreetmap.org/wiki/Every_Door)? It works beautifully exactly in use cases you mention, and is quite simple to use, and is even faster (and more versatile) than StreetComplete for that purpose.
