### ISSUE TITLE
Hydrant diameter - confirmation misleading

### ISSUE THREAD

**Issue by webracer999** [streetcomplete/StreetComplete#4872]
String `quest_fireHydrant_confirmation_title` has the text:
> "Are you sure? Sometimes the diameter can be found on the hydrant itself."

This is misleading, the diameter seems not to be on the hydrant:
> Do not confuse the number printed on the sign with the number that is printed on the hydrant, that instead is generally the diameter of the flanged connection between the hydrant and the underground pipe. This diameter currently is NOT tagged. "
(https://wiki.openstreetmap.org/wiki/Key:fire_hydrant:diameter)

See also https://community.openstreetmap.org/t/nenndurchmesser-bei-hydranten/96659

**Comment by westnordost** [comment]
Do you have a suggestion for an improved wording?

Note that the diameter could very well be written on the hydrant itself. If not in (regions of?) Germany, then maybe elsewhere. However, the hint should not apply that any number written on the hydrant will surely be the diameter.
Also, an improved wording should probably mention that the diameter could also be written on the cover of an underground fire hydrant. (I've never seen it in Germany, but it is certainly possible)

**Comment by webracer999** [comment]
How can a user distinguish if the number on the hydrant is the diameter? I personally don't know it up to now.

I think this is the first thing we need to know before we can improve the wording.

**Comment by westnordost** [comment]
I am going to request in the linked topic about suggestions for a better wording. However, since the app and thus also the text is displayed in any country, the text should work for any country, too. I hope those involved in this forum discussion are sensible of that, it is the German forum after all.

StreetComplete users in general are already made to understand from the very beginning (in the tutorial that shows on first start) that if they are not sure about their answer, they should rather leave a note (with photo) in the tutorial. So I do not find it necessary to include such a warning in every hint text. (Maybe there could be an option to re-show the tutorial in the settings or about section?)

**Comment by daganzdaanda** [comment]
Maybe it needs to be a regional exemption for Germany:
In Germany, if it's a pillar, do not ask for diameter?

**Comment by westnordost** [comment]
This is not easily possible. Only what would be possible to exclude **all** pillar hydrants. However, there is no reason why it would not be possible to find hydrants that do have this information written on them.

**Comment by FloEdelmann** [comment]
In our municipality, pillar hydrants are also often additionally signed.

**Comment by westnordost** [comment]
Uhm, so there hasn't been any feedback on how to improve the wording neither in the forum nor here. I thought about this and decided to replace the hint _"Are you sure? Sometimes the diameter can be found on the hydrant itself."_ with just _"Are you sure?"_.

**Reasons**:
1. especially on pillar hydrants, there are also other numbers written on them - which can actually also be diameters, but different ones! There is a certain chance that the user will not leave a note instead if unsure and thus introduces incorrect data. It would be somewhat complicated to explain this to the user and suggest something like "only answer when you are sure this is really THE diameter that you would usually find on the sign!!". Such a hint would also be somewhat un-StreetComplete-like, suddenly demanding of the user that he has to be an expert now, only because he didn't find a sign (not his fault there is no sign!)

2. while there **are** hydrants where the diameter is written on e.g. the cover of the hydrant itself, like here <a href="https://commons.wikimedia.org/wiki/File:Birmingham_Fire_hydrant_cover_-_2020-07-24_-_Andy_Mabbett.png"><img src="https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Birmingham_Fire_hydrant_cover_-_2020-07-24_-_Andy_Mabbett.png/170px-Birmingham_Fire_hydrant_cover_-_2020-07-24_-_Andy_Mabbett.png"></a>, the severity of erroneously tagging that it is not `*:signed` when it actually is (on the hydrant itself) is much smaller than erroneously tagging a wrong hydrant diameter. Also, some people in the forum actually would not count such a label on the hydrant itself as `signed`, arguing that it is not a sign but a label 🤷
