### ISSUE TITLE
New quest: traffic_signals:minimap

### ISSUE THREAD

**Issue by BafDyce** [streetcomplete/StreetComplete#4895]
### General
Affected tag(s) to be modified/added: [traffic_signals:minimap](https://wiki.openstreetmap.org/wiki/Key:traffic_signals:minimap)
Question asked: **Does this traffic light pole have a tactile map for the blind?**

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/blob/master/QUEST_GUIDELINES.md)):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by any pedestrian from the outside but a survey is necessary
- [x] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of map data (Worth the effort)

### Ideas for implementation

**Element selection:** if `crossing=traffic_signals` (or, same as for "is there a sound signal for the blind" and "is there a tactile signal for the blind")

**Metadata needed:** 

**Proposed UI:** Very similarly designed to e.g., "Does this crosswalk have tactile paving on both sides?"

> Question: **Does this traffic light pole have a tactile map for the blind?**
> 
> *Usually looks like this:*
> [ example images from wiki ]
> 
> buttons: [ Other answers (but no idea which ones would make sense here) ]    [ No ]    [ Yes ]

**Comment by matkoniecz** [comment]
>  Not an overwhelming percentage of quests have the same answer (No spam)

In which countries it is true?

**Comment by BafDyce** [comment]
I think at least in Austria it is quite common. Unfortunately, Unfortunately, I dont know about other countries. A quick overpass turbo check for `traffic_signals:minimap=yes` shows that it seems to be mostly an Austrian thing though? https://overpass-turbo.eu/s/1sIB

**Comment by matkoniecz** [comment]
Is it Austria thing or Graz and Vienna thing? How widespread this feature is?

Maybe asking local community would make sense

**Comment by Helium314** [comment]
There are more countries where this is a thing, e.g. Sweden: http://www.apsguide.org/chapter10_sweden.cfm, and there was a test in New York a few years ago: https://www.scientificamerican.com/article/tactile-traffic-maps-could-help-blind-pedestrians-navigate/

**Comment by matkoniecz** [comment]
Though it should be not enabled in countries where less than 1% of street lights have this.

Not sure which % would be enough - 5%?

**Comment by BafDyce** [comment]
I understand your concerns and agreed that it should not be enabled for all countries. But I have no idea what a good percentage would be. Also on what numbers this would be based on. (e.g., a reason that the number of mapped items is so low could be that tools like StreetComplete do not offer them yet^^)

**Comment by westnordost** [comment]
You could ask the Austrian forum. The quest could also only be asked if e.g. traffic_signals:vibration or traffic_signals:sound is yes.

**Comment by Lukas458** [comment]
Whether or not such a minimap exists depends entirely on which model of pushbutton the local city/municipality/department chooses. In some cities, the minimaps are therefore found in larger numbers, in many, many (**most**) other cities, however, not at all.

In theory (!) you should only be able to activate the quest for certain cities that basically use a suitable model. And then it's worth querying every crossing, because some crossings already have the new model, but others don't. But that's only worth it **there**.

**Comment by BafDyce** [comment]
Yeah, I agree with @Lukas458 
The question would be how we can decide for which geographical area/city to enable this quest. Does StreetComplete even support anything more granular than on a country level. If not, then its probably not really worth to implement this quest (unless as a strictly disabled-by-default and opt-in-only quest).

But I am in no position to judge it whether the implementation effort would make sense for such a case.

**Comment by matkoniecz** [comment]
@BafDyce and others - has anyone located country where it is appearing and not just in one or two cities?

Has anyone asked Austria community how common it is outside Graz and Vienna?

 > Here in the city (Siegen, North Rhine-Westphalia, Germany) the pushbuttons of traffic lights are gradually being replaced. Therefore, I would like to see the task taken over in StreetComplete.

@Barriere-Scout Are new ones getting minimaps? Is it in general appearing across Germany?

**Comment by Lukas458** [comment]
> Is it in general appearing across Germany?

Across Germany (unfortunately) definitely not, many cities still choose a model where a minimap cannot be integrated in the pushbutton at all.

**Comment by Lukas458** [comment]
![20230401_114818](https://user-images.githubusercontent.com/35879422/230650412-9f0745c4-3bd3-41d7-9a79-0327e1caca01.jpg)

This model is still very popular in Germany, also being assembled at new traffic signal's poles. This model is not designed for a minimap.

**Comment by westnordost** [comment]
Closing due to no feedback from @BafDyce . It can be reopened if there is feedback and it turns out that the quest guidelines can be fulfilled at least for one country. For your information, it is not possible to show a quest only in certain cities and towns. It is however possible to show a quest only in certain countries.

The quest could be accepted (for that country) if:
- the community of that country is fine with this tag being asked for and thus mapped on potentially every single traffic light
- or the data already shows (e.g. use overpass) that a non-insignificant number of pedestrian traffic lights already do have such a minimap (in that country)
- or the data shows the above but conditional to another property, e.g. a non-insignificant number of pedestrian traffic lights that **already have a vibrating button** has such a minimap (in that country)
