### ISSUE TITLE
Allow tapping a street to select bus stop name

### ISSUE THREAD

**Issue by LonMcGregor** [streetcomplete/StreetComplete#4911]
**Use case**
Most bus stops near me are very often named according to a street. Often this is the street the stop is on, or a nearby side street going off a main road.
I find typing on a phone difficult, and I don't want to introduce transcription errors, trailing spaces, capitalisation problems etc when completing this quest.

**Proposed Solution**
I would propose when in a "What's the name of this stop" quest, allow the user to tap on a street, or potentially any named object, to auto-fill the name of the bus or other transport stop.
This would be similar to the address quests, where you can tap the street next to a building to autofill the street address.

I'm curious if other users would find this useful, or if this is too specific to my area to be widely useful.

**Comment by mnalis** [comment]
I'm not sure. 

On one hand, in Croatia, while stops are rarely called **just** by street name, they often have a street name (or neighborhood name, or square name, or park name) as **part of** bus stop name (e.g. closest housenumber, or combined names of two streets crossing, or some extra text/qualifier added to street name).

On the other hand, people might be more likely to misclick on street and mangle name, or find the UI confusing as they need to both click to pull in the streetname, and then click somewhere else to edit it...

**Comment by timothywashere** [comment]
This is the normal way of naming bus stops where I live too.

**Comment by rhhsm** [comment]
I agree with @mnalis : interesting idea, but it might create more problems than it solves. Maybe it could be tried out by some advanced users before it is released to the "beginners" version of SC?

**Comment by Helium314** [comment]
What kind of problems could it cause if you can click on a street?

The worst thing I found is that your current input gets replaced. But unintentionally tapping the map while entering a name is something I consider very unlikely.

**Comment by rhhsm** [comment]
> What kind of problems could it cause if you can click on a street?
> 
The stop name is quite often (in my experience) not exactly the same as the street name, so if not done carefully, copy-pasting might add wrong information.

**Comment by westnordost** [comment]
I have also not been sure about this and pondered it for a while. Ultimately I have now decided against this. 

Additionally to what @mnalis and @rhhsm wrote, another small reason is that the UI would be a _little bit_ inconsistent here because in the road name form (which looks/behaves similar) it is also not possible to select another road - only via dropdown. But IMO, a dropdown even more suggests a limited selection, i.e. disregards that the road name may just be part of the whole bus stop name.

(Speaking of inconsistencies, I guess nothing really speaks against that it could also be possible
- to select the road name in the road name quest by tapping on another road
- to select the road name in the address quest by selecting it from a dropdown
i.e. offer both possibilities at the same time. But anyway, that would be another ticket.
 )
