### ISSUE TITLE
No label / feature for post boxes

### ISSUE THREAD

**Issue by Helium314** [streetcomplete/StreetComplete#4916]
(works with iD presets 5.2.1)
Post boxes don't have a label (text below the question) any more, because the feature search returns nothing. This matters for the check existence quest, which requires a feature to be asked.

Search works when either using iD presets v5.2.1, or when searching by country (though results may obviously depend on country). Seems in iD presets 6.0.0 it's assumed post boxes are only a local thing for some reason...

Anyway, similar things might be happening for other features, just no one noticed. Maybe feature search should always specify a country?

**Comment by matkoniecz** [comment]
Seems to be about `amenity=post_box`

**Comment by Helium314** [comment]
https://github.com/streetcomplete/StreetComplete/blob/bb5a34485bd258b0fa898761264c068df0002af2/app/src/main/java/de/westnordost/streetcomplete/util/NameAndLocationLabel.kt#L74-L85
returns `null` for `amenity=post_box`.
But it works when providing a (any?) country using `.inCountry(countryOrSubdivisionCode)`.

Apparently this is because of `locationSet` that excludes GB and US in iD presets.
So in iD presets there is no generic world wide post box feature, and thus I see the point of osmfeatures not returning anything without specifying a country.

**Comment by westnordost** [comment]
That it doesn't work correctly in osmfeatures may have something to do with that finding features is done based on indices rather than rummaging through the whole and ever-growing list of presets (in particular, for NSI) - for performance reasons. Now, the indices are based on per-country-basis only for NSI features, not normal presets, because the assumption is that an OSM feature that can exist in one country can exist in another too.

And this assumption is still true: Postboxes in the US are not something different from postboxes elsewhere. They are only a separate feature in the iD presets now to shoehorn an additional suggested field into the preset - whether it is drive-through or not.
But I think this is semantically wrong, and also from an architectural point of view, a dead-end: Postboxes in the UK are not something else altogether from postboxes in other countries only because OpenStreetMappers like to tag the `royal_cipher` on it. Semantically, it is not the preset itself that is country-specific, but the individual fields are.
If one looks closely enough, as we in StreetComplete development regularly do, one will find that there are tons of fields that are only in use in specific countries and thus should only be suggested (by UI) to be added there. For example, `designation=*` with certain values, such as `barangay` are used in the Phillippines and in the Phillippines _only_. Now, using the same approach as for the post boxes would mean that many of the `highway=...` presets must be duplicated and one field be added. If one goes down this path more, the iD presets will quickly become an unmaintainable mess.

I'll create a ticket at the iD presets, hopefully the maintainers see the issue, too. In a nutshell: There should be suggested `fields` of presets that are country-specific.

**Comment by matkoniecz** [comment]
got response, it seems once https://github.com/openstreetmap/id-tagging-schema/commit/ae68feef3c3d8fc99de1b894f109a2ee34fee7a8 is released this will become unblocked

**Comment by westnordost** [comment]
I created an issue in osmfeatures.

**Comment by FloEdelmann** [comment]
For clarification (there was confusion e.g. in #5572): This issue still persists and is still blocked by https://github.com/westnordost/osmfeatures/issues/23.

**Comment by riQQ** [comment]
Meta: could someone with permissions please pin this to make it more visible?
