### ISSUE TITLE
address numbers are not shown in address overlay view

### ISSUE THREAD

**Issue by JZersche** [streetcomplete/StreetComplete#4970]
Addresses aren't being displayed while in "Address Overlay" view mode, despite the fact that the area has full address information available. Navigating to an area where addresses haven't been filled in, and then while in "Address Overlay" mode, you can start adding the house numbers, and they'll show up. But if you stay in address overlay mode and go to the area where you know addressing information is available, the addresses aren't visible until you leave the address overlay mode, in which case, navigating back to the original location where you just filled in addresses, they are no longer visible. 

So the house numbers don't show up while in overlay mode, unless you add them manually, in which case the area may already be properly addressed leading to unnecessary edits..

**Comment by arrival-spring** [comment]
Can you link to the area where this happens?

House numbers are meant to be shown in the overlay.

House numbers will also be shown on the map, when not in an overlay, when you're zoomed in a lot. However if you have only just added them then the map won't have updated yet.

**Comment by JZersche** [comment]
Baltimore: https://www.openstreetmap.org/?mlat=39.27499&mlon=-76.61317#map=17/39.27498/-76.61317

Pretty much all of Baltimore City, Maryland is completely mapped out in OSM, **but the addresses will only show you have you have overlay set to none.**

Setting the overlay to addresses will show addresses for any areas outside of Baltimore assuming there is data, actually I've found that anywhere I've looked there seems to be no address information other than Baltimore, but Cedar Hill Lane is an area outside of Baltimore where they started building new houses recently about 2 years ago and it's been filled in with data and works with address overlays enabled, and with overlays set to none.

https://www.openstreetmap.org/?mlat=39.21104&mlon=-76.61051#map=19/39.21104/-76.61051


Another area that has address information mapped out that only shows addresses if overlay is set to None is located here:
https://www.openstreetmap.org/?mlat=39.16620&mlon=-76.73059#map=19/39.16620/-76.73059

I can see addresses on those houses if I set overlays to none, but if I set it to addresses they disappear.

**Comment by Helium314** [comment]
Works nicely for me. With the address overlay, many more house numbers are shown than without.
Did you actually download the map data (means: you see quests) in the area where you have the issue?

**Comment by JZersche** [comment]
> Works nicely for me. With the address overlay, many more house numbers are shown than without. Did you actually download the map data (means: you see quests) in the area where you have the issue?

Can you give me a location so I can test it on my end and eliminate the potential that my recent addressing isn't the issue? Yes, I've tried updating and downloading new data.

**Comment by matkoniecz** [comment]
Area link: https://www.openstreetmap.org/way/60308912#map=18/39.10568/-76.70153

**Comment by matkoniecz** [comment]
> See image for example. In this case, I see it showing a quest for the house number of the building (area) but it's not displaying the address points that were placed.

But addresses are shown in address overlay, right?

> Another example with the Cedar Lane area

Here addresses are also showing in address overlay, right?

(discrepancy of addresses showing or not before data was downloaded looks weird and may qualify for a separate issue, but it is not "address numbers are not shown in address overlay view")

Is there any specific address not showing up in address overlay with data downloaded?

**Comment by matkoniecz** [comment]
> discrepancy of addresses showing or not before data was downloaded looks weird

That is because for https://www.openstreetmap.org/way/806269254#map=15/39.2109/-76.5996 you had Northern part of data downloaded and Southern not.

Maybe somehow marking area without data would be a good idea.

**Comment by JZersche** [comment]
> you had Northern part of data downloaded and Southern not.

I don't see any option to download data, only to delete the cache

**Comment by matkoniecz** [comment]
> I don't see any option to download data, only to delete the cache.

Data will download on its own if in area, can be requested via "Scan for quests here" in menu.

Maybe it should be renamed to make clear that it fetches data also for overlays.

> What is the cause of this issue?

Background map data is based on OSM data but updates with delay of about 7 days. They should appear within about seven days.

>  They are visible with Address Overlay

So "address numbers are not shown in address overlay view" is not actually happening?

**Comment by JZersche** [comment]
> So "address numbers are not shown in address overlay view" is not actually happening?

It is happening but it goes away when I initiate a scan for quests. So what's really going on then is:
> Data will download on its own if in area.

This is not happening automatically.

**Comment by matkoniecz** [comment]
> This is not happening automatically.

Is GPS showing you actual location (blue dot)? Is there scan progress (orange bar circling around star in top-left corner)?

>  Why is it that addresses will show up with the overlay view

They are manually displayed as part of overlay based on downloaded OSM data, not as part of showing background map.

> Is address overlays somehow pulling the address information directly from OSM data instantly, while None overlay requires a waiting period?

Yes, exactly. Overlays are based on raw OSM data from OSM editing API, while background map is using processed OSM data from external service based on OSM data.

> Also, I might ask how were those row homes in Cedar Hill Lane created? They're so uniform and symmetrical. There must be a way to create an area in JOSM and then slice it in to different subdivisions?

Yes, JOSM has some build-in tools and extra plugins like https://wiki.openstreetmap.org/wiki/JOSM/Plugins/BuildingsTools

Such data could be also imported but that not appear to apply in this specific case.

**Comment by JZersche** [comment]
I will assume this issue is resolved and can be closed, since it's likely due to the background data requiring more time to update. 

An entirely separate issue I'm still wondering if there is any insight towards is here

>Another thing I wanted to bring up is if you look at the address nodes placed on Cedar Hill Lane, you'll notice they're very close together and yet the address numbers show up with no problem. I've experienced an issue where if I place the nodes myself, and they're too close together, it will only show 1 of them and not the one next to it due to it being too close, I've had to stagger the nodes in a zig zag pattern as a work around for this, but I don't like doing this so I've just been mapping it normally like how Cedar Hill is done. I'm gonna switch to using JOSM soon once I learn more about all of this.

Otherwise, thanks for all who contributed towards solving my confusion.

**Comment by westnordost** [comment]
### To summarize the situation:

- The background map is based on OSM data and is updated every few days. It includes housenumbers
- The current OSM data is only shown when the area has been downloaded. This happens automatically for the area around your GPS location, for any other location, you need to tap "Scan for quests here" in the menu
- While the housenumber overlay is shown, the addresses from the background map are hidden and instead the housenumbers from the current downloaded OSM data are shown

### Issues with the current situation:
1. The housenumbers in the overlay and when not in the overlay are styled the same. There is no way for a user to know that these actually come from different data sources. This is relevant, as they are different, i.e. one lags behind the other a few days
2. It is not obvious to the user why no addresses are displayed in the overlay - because it is not visible to the user which area(s) have been downloaded and which not
3. It is not obvious to the user how to manually download data for overlays outside of the area around his own location

### Solutions:

1. 🤷 - not show housenumbers from the background map at all? But housenumbers are very important for orientation. An option may be to not show housenumbers from the background map at all **but** show the housenumbers from the downloaded current OSM data only. However, SC currently lacks the ability to show arbitrary OSM data outside of the context of overlays. In any case, overlaying more data will be a performance hit.

2. Demarcate the downloaded area somehow - e.g. everything outside is desaturated or made darker. However, I don't see how it is possible to do so with the tangram-es rendering library. Desaturation will not work. Making it darker may work by overlaying half-transparent black rectangles. However, we want to darken the area that has **not** been downloaded, i.e. everything except. *Maybe* what could work is to add in a layer a polygon that spans the whole world but has holes (and the holes are the downloaded area(s). Anyone interested in experimenting with that possibility? - it would be a very useful feature that I think has been requested before at least 1 time.

3. Rename the "Scan for quests here" item to something that better describes its function. "Download data and scan for quests here"?

**Comment by JZersche** [comment]
> 

2. I would suggest desaturation of non-downloaded areas.
3. Automatically download data based on camera position rather than GPS position.


> The housenumbers in the overlay and when not in the overlay are styled the same. There is no way for a user to know that these actually come from different data sources.

One possible solution would be to show the house numbers in red, and to indicate that a different data source is being used colorize the buildings tint to orange or magenta.

**Comment by westnordost** [comment]
(Currently) it is not possible to style the text differently for each overlay. If the color of text in overlays would be changed, it would have to be for every overlay.

**Comment by matkoniecz** [comment]
Also, it is not really self-explainable. We would get repeated "housenumber text styling is weird with address overlay".

**Comment by mnalis** [comment]
> While the housenumber overlay is shown, the addresses from the background map are hidden and instead the housenumbers from the current downloaded OSM data are shown

Why, though? What would happen if addresses from the background map would **continue to be be shown**, and housenumbers from currently downloaded OSM data would be shown **_over them_** at exact same places? 

Is it just some tiny performance loss for doing the same thing twice? Or are they not shown on exact same locations in exact same format, so they would create unreadable mess?

Because, if former, it would seem to me that fixing such source of confusion would outweigh that small performance loss?

**Comment by arrival-spring** [comment]
OSM data is always most up to date. There could be a mistake in the address data on the background map, which is then fixed, so it would be strange to see the old, wrong, data still, even after fixing it.
