### ISSUE TITLE
Multiple MainActivities when opening via sync notification

### ISSUE THREAD

**Issue by Helium314** [streetcomplete/StreetComplete#4975]
**How to Reproduce**
* Start StreetComplete
* scan for quests
* while scanning for quests, switch to a different app (so a SC notification appears)
* open SC by clicking the notification
* (optional) move map to a different position
* try going back to home screen by pressing back button
* still see StreetComplete (with the optional step, notice that map is now at earlier position)

**Expected Behavior**
Return to home screen when pressing back button, like it happens without the steps above

**Versions affected**
52.0 and likely older ones

Investigating what is going on reveals that `MainActivity.onCreate` is being called when the notification is clicked, but no `MainActivity` is destroyed before (this happens when pressing back button).
Further, `SelectedOverlayController` gets an additional `MainMapFragment` listener when opening SC via notification.

(I tried using various intent flags in `createSyncNotification` to re-use the existing `MainActivity`, but wasn't able to get it working)
Edit: works when using `android:launchMode="singleInstance"`, but this causes issues with StreetMeasure on some Android Versions, see https://github.com/Helium314/SCEE/issues/426. Though maybe that one could be avoided using some intent flags...

**Comment by westnordost** [comment]
Hm, this is bad. Does this mean that when pressing the equivalent of alt+tab, there'll be two StreetCompletes? Also, how bad is this really? When the other StreetComplete is also started, anyway since it is stopped, it should be inactive (no listeners etc).

Looking at the [documentation for `launchMode`](https://developer.android.com/guide/topics/manifest/activity-element#lmode), `singleTask` is indeed what we'd want to have. Or `singleInstance`? Hm, to be honest, I don't really understand it from the documentation alone. Really, what any application would want to have. Which is why this confuses me a bit. Why is this not standard?

**Comment by Helium314** [comment]
> Does this mean that when pressing the equivalent of alt+tab, there'll be two StreetCompletes?

Only when going back to SC using the notification

> no listeners etc

There is a `MainMapFragment` listener on `SelectedOverlayController` remaining. Could probably be avoided by adding/removing in `onResume` / `onPause`

> how bad is this really?

Maybe not that bad, because I assume it will happen very rarely (more of an issue for SCEE with the nearby quest monitor #48).
Though, could there be bad things if there is a quest open in the old ("hidden") `MainFragment`?

> singleTask is indeed what we'd want to have

I think so too... I'll have a look whether it does what we want.
(maybe there is a difference if the user goes to settings before clicking the notification?)

**Comment by Helium314** [comment]
> singleTask is indeed what we'd want to have

Definitely `singleTask`:
* `standard`: clicking notification from settings directs to `MainActivity`, and when pressing back we go to settings again, then on back go to the original `MainActivity`
* `singleInstance`: clicking notification from settings directs to `MainActivity`, and when pressing back we go to settings, then on back exit the app (very counter-intuitive)
* `singleTask`: clicking notification from settings directs to `MainActivity`, and when pressing back exit the app (like it happens normally)

So the next question is whether on some devices `singleTask` exits the app when starting StreetMeasure, like it happens with `singleInstance`.

**Comment by Helium314** [comment]
I had tried a lot of flags that are supposed to help (quite sure that was including `FLAG_ACTIVITY_CLEAR_TOP`), and always a new `MainActivity` was created.

**Comment by Helium314** [comment]
Oh, and currently GeoUris are not handled are only handled `onMapInitialized`, so not when using `singleInstance` or `singleTask`.

**Comment by westnordost** [comment]
> I would also argue that not removing all listeners when the Activity is in the background is a problem of its own.

I think @Helium314 was writing about the listeners that are used for communication between child fragments to their parents, no? Since this is dependent on the view, it seems logical to me to keep this during the view lifecycle.

Any listener that listens on data should already be cleared on `onStop`.

**Comment by westnordost** [comment]
This is indeed a problem and it should be corrected, albeit I think this is a different issue than described here(?). Additionally, what would solve this issue on a more fundamental level would be if the listeners were actually kept everywhere in a `Set` instead of a `CopyOnWriteArrayList`. This also helps with making the core logic parts of the app less platform dependent, as the `CopyOnWriteArrayList` is Java.

**Comment by Helium314** [comment]
The flags are supposed to go to the `intent` in `createSyncNotification`, right?
There they don't change anything for me.

**Comment by Helium314** [comment]
Thanks! Setting `0` instead if `FLAG_MUTABLE` helps for me.

With `FLAG_ACTIVITY_SINGLE_TOP` it works, but only if the main activity was last displayed. When going to settings and tapping sync notification, a new main activity is created. Back goes to settings, next back goes to the old main activity.
`FLAG_ACTIVITY_CLEAR_TOP` seems to behave the same in this respect.

**Comment by westnordost** [comment]
@Helium314 are you testing with SCEE or SC? Maybe there are some additional things for SCEE specifically to consider.

In any case, @tapetis , you are the one with the knowledge here, maybe you could just create a PR that changes the pending intent what it should be (from a Android UX best practice point of view)? I lost track of this a bit.

**Comment by Helium314** [comment]
I've been seeing this with both (SC only after SCEE wasn't working as expected). Maybe it's different on API 28 again? Or maybe my system doesn't behave properly here...
