### ISSUE TITLE
Are pedestrians forbidden to walk on this road here should require a sign (UK only)

### ISSUE THREAD

**Issue by rskedgell** [streetcomplete/StreetComplete#4998]
Could the question in quest_accessible_for_pedestrians be changed in the UK to something like:
"Is there a sign prohibiting pedestrians from walking on this road here?"

In the UK at least, if there isn't a "pedestrians prohibited" sign (TSRGD diagram 625.1 [1]) on a public highway, or the equivalent health and safety sign [2] on private land, then pedestrians are unlikely to be prohibited.

Some users appear to be answering the question as if it were a subjective question and cause foot=no to be inappropriately applied to ways where it would merely be unwise or unpleasant  to walk there. This is not what the tag means and may cause issues with pedestrian routing.

[1] https://www.legislation.gov.uk/uksi/2016/362/schedule/3/made#tgp1-tbl1-tbd1-tr22
[2] https://www.hse.gov.uk/workplacetransport/safetysigns/prohibitorypedestrians.htm

**Comment by westnordost** [comment]
I am sure there is no sign here: https://www.openstreetmap.org/way/964154105

Still, I am quite sure that pedestrians may not walk there.

**Comment by rskedgell** [comment]
> I am sure there is no sign here: https://www.openstreetmap.org/way/964154105
> 
> Still, I am quite sure that pedestrians may not walk there.

A pedestrian walking there would be silly to do so, even with traffic stopped at the traffic lights. However, it is not actually prohibited (and that section of urban trunk_link is tagged correctly in having no foot=* tag). You SHOULD NOT walk there, rather than MUST NOT.

**Comment by westnordost** [comment]
Do pedestrians not have to use the sidewalk if there is one?

**Comment by rskedgell** [comment]
> Do pedestrians not have to use the sidewalk if there is one?

No, in the UK it's a should, not a must. Rule 1 of the Highway Code (the UK's statutory guidance for road users) states:
"Pavements and footways (including any path along the side of a road) should be used if provided. [...]"

https://www.gov.uk/guidance/the-highway-code/rules-for-pedestrians-1-to-35 

Failure to follow guidance (should/should not) in the Highway Code is not an offence per se. Any rule which includes must/must not refers to a legal requirement and is cross-referenced to the relevant legislation. If you failed to follow the guidance and there were an accident, that can be taken into account in any civil or criminal proceedings. If I were to walk along the section of road in your example above and got run over, it probably wouldn't do me much good to try to sue the driver.

https://www.legislation.gov.uk/ukpga/1988/52/section/38

**Comment by timothywashere** [comment]
I favour taking in a practical way, not just a legal way. Changing the wording of the SC quest world not change how it answer it. It is already very clear what it means by using the word Forbidden

**Comment by westnordost** [comment]
Well, it would be obstruction of traffic and that is forbidden, isn't it?

**Comment by rskedgell** [comment]
> Well, it would be obstruction of traffic and that is forbidden, isn't it?

I suppose it could be in theory, but only in the same way that the driver of a vehicle moving excessively slowly along the centre of the carriageway could be accused of wilful obstruction. Taking an inadvisable short cut without the intent of obstructing traffic isn't going to, particularly if someone is walking at the side of the carriageway and traffic can pass. Of course, a bored police officer of the "PC Savage" type could always find some creative reason to arrest someone, but this is straying from the point.

We're not going to tag highways with access=no because someone could commit an offence. Access values describe legal permissions/restrictions and should follow ground truth; e.g., signage or legal ruling and not introduce guesswork. (from the wiki).

**Comment by rskedgell** [comment]
Rather than change the wording of the question, would an alternative be to add a supplementary question in countries where it applies (GB, maybe IE?), asking if there is a sign and adding something like source:foot=sign if the answer is yes?

**Comment by westnordost** [comment]
Hm, to be honest, I do not find this convincing. In the legislation text, it may not be "MUST NOT" forbidden to just walk anywhere on any road, but if you are held accountable if something happens ("SHOULD NOT") then I think `foot=no` is perfectly fine. This is after all not the "SHOULD NOT" as in "it is not advisable to do" but it is in legislation.
Pedestrian routers interpreting OSM data certainly should also not route pedestrians through any road where you share the blame if an accident happens (just for being there). Also, people just don't walk there.

> source:foot=sign if the answer is yes

What for? Who is going to use this data?

**Comment by rskedgell** [comment]
> > source:foot=sign if the answer is yes
> 
> What for? Who is going to use this data?

Who is going to use source:maxspeed, source:maxwidth, source:maxheight, source:width, which are already added by SC?

**Comment by Helium314** [comment]
When is `source:maxspeed` added by StreetComplete?

**Comment by rskedgell** [comment]
> When is `source:maxspeed` added by StreetComplete?

Sorry, that one is present in the StreetComplete source, in two classes, but not added to OSM. Apologies for a overly hasty grep.

**Comment by rskedgell** [comment]
Anyway, I'm giving up on this and closing the issue.

OSM access tags now mean a legal restriction except when they don't. Got it.

**Comment by riiga** [comment]
I had this exact same issue and have changed the Swedish translation accordingly. See discussion in #2729.

The currentl translation there is now: "Is there a signed prohibition [for pedestrians] to walk on this road?"

**Comment by NathanARF** [comment]
Clarifying there is a signed prohibition would be more apt indeed, as I've seen quite a few places where the tag `foot=no` is applied incorrectly via this quest. There is always the possibility of using `foot=discouraged` for such instances but I fear there would be a lot of ambiguity around what constitutes a route to be unsuitable.

**Comment by tommycrock** [comment]
See also #2895

**Comment by rskedgell** [comment]
Use/abuse of foot=no is also being discussed in the Talk-GB list, in the thread starting at https://lists.openstreetmap.org/pipermail/talk-gb/2024-March/031184.html

**Comment by mnalis** [comment]
I see three possible ways of improving situation (of SC users choosing answers which lead to incorrect tags being added to objects occasionally):

- **improved / additional wording in StreetComplete** - that should obviously happen in this issue tracker, and if people agree that new wording is better than the old one. Should be easiest to do, if one can suggest wording less likely to be misinterpreted (while also fitting in space/usability constraints).
- **region-specific community agreement** (as the one being discussed in Talk-GB mentioned above) might result in quest being enabled or disabled in StreetComplete for that specific country/region. More work, and someone involved should summarize here the balanced report when the discussion is done there.
- **global tagging agreements** (i.e. discussed via [Proposal Process](https://wiki.openstreetmap.org/wiki/Proposal_process) , on [Community forum](https://community.openstreetmap.org/c/general/tagging/70) , [tagging-ML](https://wiki.openstreetmap.org/wiki/Tagging_mailing_list) etc) **for new tags/values** which better describe the specific situation / allow for differentiating them (e.g. _"walking is forbidden by sign"_ vs. _"walking is discouraged by sign"_ vs. _"there is no explicit sign, but walking is forbidden by law here"_ vs. _"walking is not explicitly forbidden by law but is suicidal"_) might invent new tags / values, that might eventually result in new or improved StreetComplete quests (among other things), esp. if it got wider acceptance and use. See e.g. [foot=discouraged](https://taginfo.openstreetmap.org/tags/foot=discouraged) and [class:bicycle:*](https://wiki.openstreetmap.org/wiki/Key:class:bicycle) would be examples of somewhat related concepts (which however neither got _both_ wide use & wide support). Likely most work by far.

**Comment by tommycrock** [comment]
Although I would like to see the quest disabled in the UK given the available/ agreed tagging situation, I think it would be helpful for now to improve the wording. 
I think the best way would be to add a confirmation screen (like for no bridge weight). But I guess it can't be added because having one/not can't be country specific? 
If not, is it possible to use emoji in quests, like
🚷 ?
Suggested wording with or without emoji:
Is it illegal (signed 🚷) to walk in the road here?
Is there a sign that it is illegal to walk in the road here?
P.S. in British English people use 'walk in the road' to mean on the carriageway, not on islands, verge, pavement, etc

**Comment by westnordost** [comment]
Here is an example of a piece of road where pedestrians are forbidden and yet there is no sign:
https://www.openstreetmap.org/way/2521706#map=18/51.58977/-0.19724

**Comment by rskedgell** [comment]
> Here is an example of a piece of road where pedestrians are forbidden and yet there is no sign: https://www.openstreetmap.org/way/2521706

Pedestrians are *not* forbidden to walk on that section of road, so it's not an example. The absence of a sign and corresponding tragfic order matters in the UK.

**Comment by westnordost** [comment]
Isn't it forbidden to walk on the street if no sidepath exists?

**Comment by NathanARF** [comment]
In the UK pedestrians are allowed to walk along any public highway except motorways or where prohibited by a traffic sign (which usually has a traffic regulation order associated with it)

**Comment by westnordost** [comment]
Yes, sure, they can walk along it on the sidepath.

A turning lane is often drawn as an own way in OSM, especially if there is physical seperation. Does a turning lane then count as an own public highway according to UK law or rather as part of the (dual lane) public highway? The former sounds quite counterintuitive to me.

**Comment by tommycrock** [comment]
As NathanARF said, the presence or absence of a sidewalk is irrelevant to where people can walk. They have the right to walk in the middle of the carriageway although it may be inadvisable (unless a motorway or explicitly signed). It is rather the absence of a law, or new laws since sidewalks became common place. We have no jaywalking laws. Specifically regarding protests, we do now (as of last year) have laws against blocking 'vital infrastructure' including roads (of any class), but one person walking on it when it wasn't busy would not be blocking it. Why don't we have complete traffic chaos, common sense I guess. As a pedestrian I don't want to get run over or shouted at!

**Comment by westnordost** [comment]
UK has no special status when it comes to (the absence of) jaywalking laws.

Anyway, wouldn't it be obstruction of traffic and wouldnt that be an offense with which one could be fined if one walks in the middle of the carriageway when there is vehicle traffic?
I am not talking about crossing the road here.

**Comment by NathanARF** [comment]
Well it is only a legal right they can walk wherever they want in the carriageway. Pedestrians will still walk at the side of the road when there is no pavement provided. Here, in the example given earlier, a pedestrian could walk this blue route should they choose to do so. Only signage could legally stop them. Hence, the segment between the two carriageways should not have `foot=no` unless signage is in place prohibiting pedestrians.
![image](https://github.com/streetcomplete/StreetComplete/assets/125688464/65e726ff-e93b-4b7d-96e4-a9ebf0e7ea7e)

**Comment by tommycrock** [comment]
> UK has no special status when it comes to (the absence of) jaywalking laws.
Okay, well it also doesn't have laws requiring the use of a sidewalk when present. 

> Anyway, wouldn't it be obstruction of traffic and wouldnt that be an offense with which one could be fined if one walks in the middle of the carriageway when there is vehicle traffic? I am not talking about crossing the road here.
In extremis, if there was traffic and you were blocking it, yes, you may be committing an offence. But if it was quiet/ you were near the edge, no. There isn't a general prohibition.

**Comment by riiga** [comment]
> > The presence of a pavement does not change this as pedestrians are not legally required to walk along it.
> 
> Didnt read this the first time. So, uhh, what?! That does sound like a very odd law and I think would make UK quite special. If it is not forbidden, why is there not total traffic chaos? Police couldn't do anything if I walk on a public trunk road? Sounds like a great loophole to do unannounced demonstrations and the authorities can not even remove you. ("Im just walking here")

The same is true in Sweden as well. It's perfectly legal to walk on any road unless explicitly forbidden. In general you have to keep to the left and not walk in the middle of the lane, but there's nothing stopping you from choosing the most appropriate way to get to your destination, whatever that may be.

**Comment by westnordost** [comment]
To go the route marked in blue would be legal in most countries, though. (I.e. countries in which there is no jaywalking law.) You are not actually walking on the road there but along it on the whatever it is called - traffic island area? - , only crossing it in sections. I don't know how to tag that. 

---

Anyway, this seems to be a case of "it is legal as long is noone is doing it". As in - as soon as people will actually use this right (in mass), the law is going to quickly change.

So, StreetComplete asks its users whether it is prohibited to walk on that piece of road. From a correctness point of view, this is fine. It is on the users to answer this correctly. 

However, since the ticket was raised, the problem seems to be that I guess, many people in the UK do not actually know that it is not forbidden or at least the appropriate case law by precedent is missing (which may explain why it is not actually forbidden in the law yet). I.e. (some) users answer "yes, forbidden" in StreetComplete even if they do not see a sign.

So should the `foot` restriction in the UK be mapped according to written law or according to practiced law? You (four) seem to be unanimous in that it should be the written law and to be honest, it is easier to achieve a consensus for that than the latter because practiced law can be somewhat fuzzy.

E.g. is it legal to be (openly) gay in Russia? Well, there is no written law against it, but practiced law looks different because other laws can and are construed to prosecute you anyway. So, it's easier to go by written law, but still it may be problematic (for safety reasons) to tag `gay=*` on clubs in Russia.

Anyway, back to the UK. In the absence of tags like `foot=actually_yes_but_not_really`, e.g. router applications would likely continue to route pedestrians through such roads. And, well, I wouldn't want the router I use to give off ...

<img width="120" src="https://github.com/streetcomplete/StreetComplete/assets/4661658/03c680c7-ddd0-4009-ac79-2259bb5648ff" alt="Ackchyually"/>
...  you *may* walk here, hehe!"

...vibes. Cause, that's both not helpful and endangering myself if I choose to blindly trust this know-it-better router.

So, is there consensus in the UK community that the written law should be followed here? If yes, can you provide a link to the related discussion for reference?

**Comment by tommycrock** [comment]
So, for now, I'm just suggesting a wording that would make the quest more consistently completed and in line with the tag meaning of legal access. It currently says forbidden, but not by who. My mum might forbid me but I do it in some places and times. Illegal is much more explicit (and you could guide users better by pointing out that means signed). 

Personally, I would however prefer to not have the quest in the UK (so I have it disabled) because I think adding an explicit yes to such roads feels like router baiting. No is mistagging, yes is misleading. I think where it's guarded off by fences, foot=discouraged would be appropriate, but that's not a consensus position.

**Comment by rskedgell** [comment]
> Anyway, wouldn't it be obstruction of traffic and wouldnt that be an offense with which one could be fined if one walks in the middle of the carriageway when there is vehicle traffic? I am not talking about crossing the road here.

If the criterion for tagging foot=no is that one could potentially be prosecuted for creating a public nuisance by deliberately obstructing free passage, we can tag every public highway with foot=no.

**Comment by westnordost** [comment]
> If the criterion for tagging foot=no is that one could potentially be prosecuted for creating a public nuisance by deliberately obstructing free passage, we can tag every public highway with foot=no.

No. Only _potentially_ on those that amongst other things

1. have a `sidewalk` or a sidepath (`foot=use_sidepath`) or walkable shoulder, i.e. offer a designated place for pedestrians and
2. are not intended for frequent intermixed traffic (not alleys, living streets, residential streets)
3. are developed clearly for vehicle use (e.g. are paved)

It is not accidental that the StreetComplete quest is only asked for roads without sidewalk, sidepath or shoulder and also not asked for anything residential or unpaved.

**Comment by mnalis** [comment]
> If not, is it possible to use emoji in quests

Well, not really, kinda. That is, it is theoretically possible to use UTF-8 characters, but how they would get rendered (if at all) depends heavily on specific Android version and manufacturer. IIRC we've tried to do that is `surface quality` quest, and it didn't really work, so they had to be replaced by tiny vector images (which worked there where bicycle/car/skateboard/etc. icons were at specific positions; but I don't think would really work here, due to translations in this case where you'd want emoji in the middle of the text)

>  P.S. in British English people use 'walk in the road' to mean on the carriageway, not on islands, verge, pavement, etc

There is separate translation for UK English, so those specific language differences can be [updated](https://github.com/streetcomplete/StreetComplete/blob/master/CONTRIBUTING.md#translating-the-app) independently. 

For the record, there are two strings that relate to the quest and are available for translation/update; the main question _"quest_accessible_for_pedestrians_title_prohibited"_, which is currently:

> Are pedestrians forbidden to walk on this road here?

and the longer explanation _"quest_accessible_for_pedestrians_separate_sidewalk_explanation"_ that currently says:

> This street was tagged as having no sidewalk on either side. If there is a sidewalk but it is displayed as a separate way, please answer “sidewalk”.

Either or both could possibly be changed (but care should be taken so they don't get too long; as there are space limitations) .

**Comment by westnordost** [comment]
I do not recommend changing the translation because British English is also used in other countries. If this is country specific, then it must also be handled country-specific, not language-specific. For this reason, I will revert such deviations in translations whenever I detect that or it is pointed out to me as I consider that close to vandalism.

I already wrote that I would deactivate the quest for UK if it doesn't not make sense in the UK due to its apparently unique legislation. I just need a link to a discussion on a UK mailing list or UK forum discussion in which a consensus to this effect was reached for future reference.

See my last post for details: https://github.com/streetcomplete/StreetComplete/issues/4998#issuecomment-1986963078

**Comment by NathanARF** [comment]
I would suggest just disabling the quest in the UK. Simplest option.

**Comment by westnordost** [comment]
That's... literally what I wrote.

**Comment by westnordost** [comment]
No feedback, closing. Can be reopened once feedback was given, see my three last comments.

**Comment by rskedgell** [comment]
I have added a poll on the OSM community website. Hopefully we can finally resolve this.

https://community.openstreetmap.org/t/poll-should-streetcomplete/118387

**Comment by rskedgell** [comment]
> No feedback, closing. Can be reopened once the requested feedback was given, see my three last comments.

 @westnordost We have feedback on the community forum now, 14 votes to disable, none in favour of retaining. Please reopen.

**Comment by westnordost** [comment]
Thank you, that should suffice as documentation as to why the quest will be disabled in the UK.

I am not quite content with how you phrased it, but I hope that anyone that voted read [TrekClimbing's clarification](https://community.openstreetmap.org/t/poll-should-streetcomplete-disable-the-are-pedestrians-forbidden-to-walk-on-this-road-without-sidewalk-here-quest-in-the-uk/118387/10).
