### ISSUE TITLE
Wrong display of letters with marks above (ščžáé...) - on the map

### ISSUE THREAD

**Issue by CTJoriginal** [streetcomplete/StreetComplete#5006]
Street Complete displays text of letters with marks (čšžćá...) wrongly; instead of mark being above the letter it gets moved to right where it intercepts with next letter in line (check attached screenshots), which makes text verry hard to read. Issue only happens on text displayed on the map and not in input fields. 

![SmartSelect_20230508_101441_StreetComplete.jpg](https://user-images.githubusercontent.com/48687492/236774530-e08c237b-7460-455e-a2e8-a92eb2c574ad.jpg)

![SmartSelect_20230508_100930_StreetComplete.jpg](https://user-images.githubusercontent.com/48687492/236774631-d78b4e23-560f-4588-be00-2b64b9f6d0b3.jpg)

**How to Reproduce**
Create place (shop overlay) with name, that contains these letters

**Expected Behavior**
It's expected that these letters appear like this: ščžćáè... 

**Versions affected**
Android: 13, ONE UI 5.1
App: v51.2

**Comment by mnalis** [comment]
Yes, it would be interesting to know:
- what language is chosen in StreetComplete?
- at what location is that happening?

For me (SC v52.1, EMUI 12/Android 10?) with Croatian language, it works (and has always worked) just fine, e.g. at https://www.openstreetmap.org/way/591540390:


https://user-images.githubusercontent.com/156656/236921052-861c5f5f-687f-4c45-b382-c2f6305f4e5d.mp4

**Comment by Helium314** [comment]
Looks fine for me too (Android 9)
Could be that it's broken on Android 12+ only? There were some font issues previously: https://github.com/tangrams/tangram-es/issues/2303

**Comment by CTJoriginal** [comment]
It seems to happen in all languages for me
https://user-images.githubusercontent.com/48687492/237055928-65774bb9-8a08-4a12-a3fa-27bb2b8e11bf.mp4

I have attempted reinstalling app and issue persists. 



@Helium314 yes names display correctly when you open element

@mnalis It's happening in Slovenia

**Comment by matkoniecz** [comment]
Is it happening also with Polish letters? Such as Ś and ó?

https://www.openstreetmap.org/node/3009775614

https://www.openstreetmap.org/relation/2432115#map=15/50.1474/21.9713

**Comment by CTJoriginal** [comment]
I went ahead and tried all accents:

![SmartSelect_20230509_121334_StreetComplete.jpg](https://github.com/streetcomplete/StreetComplete/assets/48687492/80df9a7c-d9df-4e4d-8d00-f23bab359e21)

I also found out that names dont even display if they contain letters such as "ș ş" and any zalgo text (T̴̜͉̈́͐e̶̝̮̒ş̴̱̐̓t̵̙̐ ̴͔̹̍1̸̼̣̓2̷̳̞͛3̵̫̂). I guess it can't display text if it has marks bellow letter.

**Comment by westnordost** [comment]
Right, anyway,  the fact that it only happens for things rendered on the map but not in the UI means that it is a tangram-es issue and we can do nothing about this. So I'll close this as will-not-fix, as it is an upstream issue.

Unfortunately, [tangram-es](https://github.com/tangrams/tangram-es/) isn't really maintained anymore. I figure, you **could** post an issue there, but most probably it would just be for documentation purposes. It may also be just the same issue as https://github.com/tangrams/tangram-es/issues/2335, so you could also just add a comment there.

**Comment by CTJoriginal** [comment]
Alright, I guess we will just have to live with it then.

**Comment by mnalis** [comment]
@CTJoriginal you can try testing with testing `.apk` (can be run at the same time as original SC without affecting it) published in this issue:
- https://github.com/streetcomplete/StreetComplete/issues/3123#issuecomment-1467077352

If it works ok in MapLibre part of the screen, than those display issues may be an additional argument for making the move from Tangrem-ES to Maplibre (especially as more and more devices are going to be Android 12+, and many languages contain non-ASCII names)

**Comment by mnalis** [comment]
@soshial and what Android version is that (and what SC version)? 

For me (SC 53.3 on Android 10/EMUI 12) the same region displays fine:

![small_Screenshot_20230906_215309_de westnordost streetcomplete](https://github.com/streetcomplete/StreetComplete/assets/156656/cf86295f-17e0-41e6-8e0a-b80200fcaf71)

So far, it seem to be happening only on newer android versions. Unfortunately, as stated [above](https://github.com/streetcomplete/StreetComplete/issues/5006#issuecomment-1540017016), this is bug in Tangrem-es library, which seems to be abandoned, so it is very unlikely to be fixed.  Possible solution is porting StreetComplete to [use Maplibre instead of Tangrem-es](https://github.com/streetcomplete/StreetComplete/issues/5006#issuecomment-1540330735), but that is no small job.

**Comment by soshial** [comment]
> @soshial and what Android version is that (and what SC version)?

Street Complete v54.0
Samsung Galaxy S22 with Android 13

**Comment by RubenKelevra** [comment]
@soshial can you confirm that it's fixed in version 59.0 Alpha 1?

Here under Android 12 it looks fine now:

![Screenshot_2024-08-23-14-27-01-269-edit_de westnordost streetcomplete](https://github.com/user-attachments/assets/c31c3478-d29f-4774-9f18-91337d5b27b6)

**Comment by mnalis** [comment]
> For me (SC 53.3 on Android 10/EMUI 12) the same region displays fine:

And (again for me) on Android 14 it is broken (in all Tangrem-ES versions, i.e. anything _**below**_ `v59.0-alpha1`). 

**So it seems it broke around Android 13 or 14, and also it will be fixed with v59.0 release.** 

As  e.g. shown here in that  old testing version which displayed both Tangrem-ES and MapLibre at the same time:
![small_Screenshot_20240823_143514_ML StreetComplete](https://github.com/user-attachments/assets/a28602ed-9104-4347-8444-f90556fae2e6)

**Comment by soshial** [comment]
It looks like 59.0-alpha1 fixed it for my Samsuns S22 (Android 14).
Although, I haven't tested it with letters that have double diacritics (e.g. in Svan language or Livonian language). Have you tried it? Can't find such examples on a map.
Also, I couldn't find native titles on a map at all 🙃
