### ISSUE TITLE
Pedestrian/cyclist traffic signal timings

### ISSUE THREAD

**Issue by andrewharvey** [streetcomplete/StreetComplete#5047]
It would be useful for pedestrian and bicycle routing to know how long the wait is at traffic signals. This can be recorded with the interval=* tag, as the time between two change to greens, and the duration of the green symbol with the duration=* tag.

### General
Affected tag(s) to be modified/added: [interval=*](https://wiki.openstreetmap.org/wiki/Key:interval) [duration=*](https://wiki.openstreetmap.org/wiki/Key:duration)
Question asked: **What is timing of this (pedestrian|cyclist|shared) crossing signal?**

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/blob/master/QUEST_GUIDELINES.md)):
- [x] 🚧 To be added tag is established and has a useful purpose
The interval key is approved, has 17k uses and well defined wiki documentation.
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by any pedestrian from the outside but a survey is necessary
- [x] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of map data (Worth the effort)

### Ideas for implementation

**Element selection:** type=way AND highway=footway|cycleway AND footway|cycleway=crossing AND crossing=traffic_signals AND (!interval OR !duration)

**Metadata needed:** 

**Proposed UI:** I suggest incorporating a stopwatch function to automatically measure time the lights are green and time until it returns to green again, possibly rounding the result.

Inspired by @jakecoppinger's [Better Intersections](https://github.com/jakecoppinger/better-intersections)

**Comment by matkoniecz** [comment]
Are you sure about "Easily answerable by any pedestrian from the outside"?

Note that even recording single cycle is not enough as it may depend on vehicle/pedestrian detection (one of things that I repeatedly reported to local government was eternal red light where "smart" lights failed to detect cyclists).

Also there are cases where for example cycle is more complex (30s of green light, 60s of red light, 30s of green light, 200s of red one, repeat).

Also, cases where it is time dependent and changes across the day/week.

etc etc etc

**Comment by jakecoppinger** [comment]
Love the idea of this data living in OSM (I've licenced the crowd sourced data I generate with https://betterintersections.jakecoppinger.com as ODbL in case it can be migrated), but I'm starting to find there's so much variability.

As @matkoniecz said it can depend on:
- Time of day (step function? curve?)
- How many cars estimated by SCATS (https://en.wikipedia.org/wiki/Sydney_Coordinated_Adaptive_Traffic_System)
- If the cycle is more complex that one green light
- If location is outside automated boundary area or time (a subset of the council area: https://jakecoppinger.com/2022/12/sydney-cbd-is-bringing-back-pedestrian-beg-buttons/)

Maybe there is scope for a general OSM compatible API (using OSM node/way ids as keys) that I could implement (and others with crowdsourced data or gov data like in Victoria) could implement that given a time of day, estimates the cycle times based on past data (which could be used when routing somehow?)

**Comment by jakecoppinger** [comment]
That being said, I definitely think there are more traffic signal related things that could go into OSM via StreetComplete:

- Scramble crossings: `crossing:scramble = yes` and `crossing_ref = pedestrian_scramble` (https://lists.openstreetmap.org/pipermail/tagging/2022-January/063588.html, short discussion in OSM World Oceania: https://discord.com/channels/413070382636072960/471231032645910529/1111799480799465543)
- Digital countdown timer rather than flashing red (I haven't looked if there are tags for this)
- Whether an cycling/road intersection has a protected green phase at all (I assume no tag)
    - I would really prefer to avoid such intersections when on a bike
    - "Heading west, people on bikes and people in vehicles get a green light at the same time and there is now an almost 3-metre-wide pillar that creates a massive blind spot.": https://www.abc.net.au/news/2023-02-07/cyclist-death-prompts-calls-changes-west-melbourne-intersection/101937556
- Whether cars can cross a pedestrian's path on red (protected flashing red phase). This would be very useful for prioritising these routes for slow/elderly users

I'm curious what other things will pop up in the freeform notes that user might find notable about pedestrian crossings: https://docs.google.com/spreadsheets/d/1L08GNolPYjiRwLOL2d3lAZPqwCNe5vGr6SAOtH7hnNM/edit#gid=0

Though with the exception of scramble crossings, these ideas are probably out of scope of StreetComplete and more OSM proposal ideas though! Please let me know if you've heard of other existing tags.

**Comment by andrewharvey** [comment]
All good points here. I agree timings based on many factors which probably does limit how easy we can map these and design a SC quest for.

> Maybe there is scope for a general OSM compatible API (using OSM node/way ids as keys) that I could implement (and others with crowdsourced data or gov data like in Victoria) could implement that given a time of day, estimates the cycle times based on past data (which could be used when routing somehow?)

Yes that's probably better. Similar to how some vendors supply live traffic data against OSM node/way ids which is consumed by routers.

> Digital countdown timer rather than flashing red (I haven't looked if there are tags for this)

https://wiki.openstreetmap.org/wiki/Key:traffic_signals:countdown

> Whether cars can cross a pedestrian's path on red (protected flashing red phase). This would be very useful for prioritising these routes for slow/elderly users

Partly covered by `traffic_signals:turn=left_on_red` from https://wiki.openstreetmap.org/wiki/Proposal:Turn_signals

**Comment by andrewharvey** [comment]
> Also completely unnecessary for the UK. There are no conflicting pedestrian phases here. If you have a green pedestrian phase here the only traffic you need to worry about is emergency vehicles and red light jumpers.

That would just be concerning Jake's point:

> Whether an cycling/road intersection has a protected green phase at all (I assume no tag)

not the original quest proposal here.

**Comment by andrewharvey** [comment]
> Whether cars can cross a pedestrian's path on red (protected flashing red phase). This would be very useful for prioritising these routes for slow/elderly users

> Partly covered by traffic_signals:turn=left_on_red from https://wiki.openstreetmap.org/wiki/Proposal:Turn_signals

@jakecoppinger I misunderstood. You mean do cars have the green light during the time the pedestrian light is flashing red. `traffic_signals:turn=left_on_red` is when cars may proceed through a vehicle red light regardless of the pedestrian light colour.

**Comment by jakecoppinger** [comment]
@andrewharvey Yep all good - I realised you likely misunderstood while checking the docs.

I'll think about what sort of name I could use (and would make sense) for a protected pedestrian flashing red/orange countdown.

In the meantime - if you have any interest in adding any data points near where you work/live I would gladly host them! https://betterintersections.jakecoppinger.com/

Ideally long term I would implement a form with better UX but I don't have enough time to implement accounts & DB etc.

**Comment by westnordost** [comment]
See @matkoniecz and @jakecoppinger

**Comment by danieldegroot2** [comment]
@andrewharvey @jakecoppinger Feel free to start implementing feasible parts in [SCEE](https://github.com/Helium314/SCEE/issues). It can always be added here later.

**Comment by jakecoppinger** [comment]
FYI, there is significant complexity and drawbacks with evaluating user-generated traffic signal timing measurements (at least with the dynamic SCATS system I'm familiar with), and I don't believe this data (cycle times, or solid red times) should be input directly into OSM:

- Cycle times (and solid red durations) change every single cycle
- Cycle times change significantly between peak and off peak (on the order of doubling or tripling in some cases)
- Solid red times are dynamic, based on how many cars pass over the sensor
- Solid green times and flashing red (clearance) durations are typically constant (where "walk-for-green" is not enabled, in SCATS terminology - eg. adjacent to one-way roads)

The data is typically reproducible and is not "verifiable", so in cities/states where signals are dynamically operated (ie. not fixed phasing) I don't think this belongs in OSM. I expect most cities use dynamic phase operation - eg. SCATS operates in 216 cities in 33 countries. I'm not across SCOOT or Fusion, and other worldwide systems.

Due to this very large variance with no constant expected value, I think it's more suitable for samples of this data to be stored outside of OSM, but linked to it.

An exception to this is is perhaps solid green or flashing red durations, however these are challinging to measure to the exact second without taking multiple samples. This is more feasible with countdown timers, which actually *show* the number of seconds at the start of the count down - counting down the flashing-red/clearance interval in an Australian context. In Sydney I've started informally using `traffic_signals:countdown:maximum` for this, and am open to suggestions on better names for this (I'm talking single digit usage of this tag right now!) See usage here: https://overpass-turbo.eu/s/2nu5

See https://en.wikipedia.org/wiki/Sydney_Coordinated_Adaptive_Traffic_System and https://en.wikipedia.org/wiki/Traffic_signal_operation_in_New_South_Wales for background on Sydney's dynamic signal operation.

I've made sure every Better Intersections intersection links to the OSM node: https://betterintersections.jakecoppinger.com/). Better Intersections is AGPL-v3.0, and the data is licensed ODbL - you can download the JSON here: https://betterintersections.jakecoppinger.com/about). Better Intersections certainly needs some UX improvements - I've started work on this in a branch.

**Comment by danieldegroot2** [comment]
@jakecoppinger more so referring to adding for example `traffic_signals:countdown` quest.
