### ISSUE TITLE
Crash after restart app

### ISSUE THREAD

**Issue by Jean-BaptisteC** [streetcomplete/StreetComplete#5048]
**How to Reproduce**
- Close app
- Start app -> app crashed (never reproduce)
<img src="https://github.com/streetcomplete/StreetComplete/assets/87148630/2ac42fc8-30fc-482d-ba0c-0da7cc3a0599" height=500/>

**Versions affected**
Android 13 - v53.0

**Comment by westnordost** [comment]
What do you mean with "close app"?

**Comment by Jean-BaptisteC** [comment]
Go to list of app opened and swipe StreetComplete to close it

**Comment by westnordost** [comment]
This puzzles me, how can a crash happen on cold start of the app?

Anyway, I noticed that this is a problem in tangram-es, so an upstream issue.

This seems to happen extremely scarcely so I won't bother with some kind of workaround that may or may not work.

**Comment by Helium314** [comment]
@westnordost do you remember the reason for
https://github.com/streetcomplete/StreetComplete/blob/c456a05d9f3c46452600d2da7cc38f4e3e811eed/app/src/main/java/de/westnordost/streetcomplete/screens/main/map/components/DownloadedAreaMapComponent.kt#L16-L19

I tried removing the part above and 
```diff
-    private var layer: MapData? = null
+    private val layer: MapData = ctrl.addDataLayer(DOWNLOADED_AREA_LAYER)
```
and
```diff
+        layer.clear()
         layer.setFeatures(listOf(
             Polygon(
                 polygons.map { polygon -> polygon.map { it.toLngLat() } },
                 mapOf()
             )
         ))
-        this.layer = layer
```
and didn't have a crash so far (instead of once every ~10 app starts).

**Comment by westnordost** [comment]
What do you mean, reason for that? The reason is explained in the comment above.

Do you remember, we (still) have the issue that when you solve a quest and then zoom out, the solved quest seems to reappear (flickering, while zooming out) again, because apparently the pin is still in the cache for the other zooms or something. A similar phenomen only more noticeable (IIRC) could be seen with the downloaded area visualization.

**Comment by Helium314** [comment]
> The reason is explained in the comment above.

"tangram does not clear a layer properly on re-setting features on it" isn't particularly clear on the issues it causes, that's why I asked. Thanks for the clarification.

So it's occasional crashes at startup or flickering in non-downloaded areas...
Since it only happens on startup, maybe starting with an empty layer instead of null helps. I'll try that for a while.
