### ISSUE TITLE
Download quests along a gpx track

### ISSUE THREAD

**Issue by vnourdin** [streetcomplete/StreetComplete#5057]
**Use case**

I'm using StreetComplete without mobile data, because I haven't such plan.

Before going somewhere, I download quests at home.  
In my city it's OK, I can download 2 or 3 screen zones before going there.  
But when I'm on a trip, it's just too long to move the screen and download tens of quests zones, thus I don't contribute except with notes in OsmAnd.

In bike trip, lots of people disable their mobile data to keep a bit more battery, so I think this would be useful to lots of users.

**Proposed Solution**

It would be a great solution to load a track (gpx or other format) in SC and let it download every quests near the track !

I have no idea of the complexity of making that possible, but I'm eager to help if I can.

**Comment by westnordost** [comment]
In general, downloading from the OSM API is only possible via bounding box. Additionally, SC further limits this so that download is only done on zoom 14 (IIRC) slippy map tiles raster cells.

So, to find which bboxes to download, an algorithm first would need to find out which raster cells this GPX track passes through (+ reasonable buffer in meters). 

Also, since the GPX can potentially be absolutely huge, the user would also need to have the ability to cancel the current download (triggered by that functionality). If I remember correctly, this can't be done right now.

Finally, I am not sure if the app would need additional permissions (to access the file system). If it would need additional permissions, this would be a good reason to not have this for such a peripheral feature. If not any additional permissions are necessary (e.g. somehow one can "send" the GPX track to SC just like one can send a GPS position to SC), then adding this feature would be fine. However, I would not work on it, because for such a peripheral feature very few people will use, I find the effort much too high. To the point where I'd actually not keep this issue open rather than keep it open but would still accept

**Comment by Helium314** [comment]
The file permission can be worked around by prompting the user to provide a file using `Intent.ACTION_OPEN_DOCUMENT`.
I played with such download-along-atrack functionality a while ago, but found it too much effort to come up with a reliable solution.

The issues:
* downloading everything at once may easily get more data than can be handled (and much more than needed, as this would download a bbox containing the track)
* splitting into z16 bboxes (download "unit" in SC) may be slow; downloading (and processing) many small areas is _much_ slower than downloading a large one

So the required z16 tiles need to be determined, and then the area should be split into a number of of sections to find a good balance between the two issues above.

**Comment by riQQ** [comment]
Related to #473.

**Comment by westnordost** [comment]
I'll close this then.
