### ISSUE TITLE
westnordost.de is unavailable for some people

### ISSUE THREAD

**Issue by nata1993** [streetcomplete/StreetComplete#5063]
Creating a note within the app gives pop-up window, where you explain whats the problem on the field and also you can add photos of the problem. Once the photos are added and note is uploaded, the photos will be sent to special server. Server web address, which hosts the photos of the note, usually looks like this: 
https://westnordost.de/p/image.jpg

Clicking in OSM on the link used to open the image, but not anymore.

Similarly in v53.0 uploading a note fails probably because the hosting server is unavailable. The error is "Connection error while uploading answers". But uploading a change works, its the note uploading fails, even if you dont add photos to note.

Problem persists already for few days.

**How to Reproduce**

1. Open StreetComplete app.
2. Press and hold someone on the map until pop-up dialog opens.
3. Select "Create new note"
4. Fill the text area explaining the problem.
5. Click on the icon adding photo.
6. Make photo and click "Ok" on preview window.
7. Upload the note within StreetComplete app.
8. Open www.openstreetmap.org webpage.
9. Find and go to your freshly created note.
10. Open the note.
11. Within OSM webpage note you see description of the note and web links to photo hosting server. Click on one of the photos.
12. Photo should open.

**Expected Behavior**

Step 7  in "How to reproduce" should not return network error and upload note to OSM.
Step 12 in "How to reproduce" should open photo.

**Versions affected**

v53.0, v52.1

**Comment by Helium314** [comment]
Can you link to such a note where you got an error and no image is available?

**Comment by matkoniecz** [comment]
Also, note that this images are not listed forever - only for open notes. See also https://wiki.openstreetmap.org/wiki/Mechanical_Edits/Mateusz_Konieczny_-_bot_account/remove_links_to_temporary_files_hosted_on_westnordost.de

**Comment by mnalis** [comment]
It would be nice to have a photo (or more detailed descrption at least) of that _"network error"_ @nata1993 , but that sounds to me like a (temporary?) network connectivity problem - either at your side (e.g. bad wifi/mobile network) signal, or anywhere on the path between you and westnordost.de server (including the problems with the server itself).

If server is not reachable, you'll have problem both trying to upload pictures to it (step 7) as well as trying to download pictures from it (step 12), which seems to be exactly what is happening to you.

To confirm, if that still happens (for me currently https://westnordost.de works just fine), you could try opening in regular web browser https://westnordost.de -- it probably wouldn't open either.

Hopefully that was just weak signal reception or other temporary Internet issue and it now works; but if the problem persist for you, let us know (I can try to help with some basic troubleshooting to try to pinpoint where exactly the problem is happening)

**Comment by nata1993** [comment]
> Can you link to such a note where you got an error and no image is available?

https://www.openstreetmap.org/note/3720012

This is one of such notes I have added few days ago that I am in trouble of opening links on phone and on laptop.

> Also, note that this images are not listed forever - only for open notes.
> 
> See also https://wiki.openstreetmap.org/wiki/Mechanical_Edits/Mateusz_Konieczny_-_bot_account/remove_links_to_temporary_files_hosted_on_westnordost.de
> 
> See also [openstreetmap/iD#9302](https://github.com/openstreetmap/iD/issues/9302) and https://josm.openstreetmap.de/ticket/22397

This is not the issue because I am aware of that. Photos are done a lot sooner than supposed time before photos are deleted, even more so that notes are not closed yet.




> It would be nice to have a photo (or more detailed descrption at least) of that _"network error"_ @nata1993 , but that sounds to me like a (temporary?) network connectivity problem - either at your side (e.g. bad wifi/mobile network) signal, or anywhere on the path between you and westnordost.de server (including the problems with the server itself).
> 
> If server is not reachable, you'll have problem both trying to upload pictures to it (step 7) as well as trying to download pictures from it (step 12), which seems to be exactly what is happening to you.
> 
> To confirm, if that still happens (for me currently https://westnordost.de works just fine), you could try opening in regular web browser https://westnordost.de -- it probably wouldn't open either.
> 
> Hopefully that was just weak signal reception or other temporary Internet issue and it now works; but if the problem persist for you, let us know (I can try to help with some basic troubleshooting to try to pinpoint where exactly the problem is happening)

I would gladly create screenshot of such network error but since its a pop-up bubble in the app, it goes away pretty fast and when I click somewhere, it also goes away instantly, hence I cant just do screenshot with phone. Dont have another one near by also. The quoted network error phrase is only half of the exact text. However, laptop has same issue on same links and here is the text of the error:

The connection has timed out

An error occurred during a connection to westnordost.de.

    The site could be temporarily unavailable or too busy. Try again in a few moments.
    If you are unable to load any pages, check your computer’s network connection.
    If your computer or network is protected by a firewall or proxy, make sure that Firefox is permitted to access the web.

The problem is not with my network because I can freely use internet with any other app on the phone and even doing hotspot to the laptop which is also using any website freely as long as there is no serverside problems.

Opening https://westnordost.de/ in web browser (firefox) on laptop, gives same error - connection timeout.

![Screenshot 2023-06-11 at 18 14 40](https://github.com/streetcomplete/StreetComplete/assets/6074645/89b0611b-2385-462b-9e3c-951611954429)

**Comment by matkoniecz** [comment]
https://westnordost.de/ and image that I checked from linked note works fine for me

Can you check at school/library/work or on device of a friend?

**Comment by nata1993** [comment]
> https://westnordost.de/ and image that I checked from linked note works fine for me
> 
> Can you check at school/library/work or on device of a friend?

Tried out it on my sunshines iphone using Safari which returned "Safari could not open the page because the server stopped responding." and yet exactly same problem. Connection timeout either on https://westnordost.de/ or the image link within given note.

There is one thing that is same with me and my sunshine. We have same service provider: Elisa Eesti AS.
Apart from this, she never even used OpenStreetMap or any related software.

**Comment by westnordost** [comment]
Hm, not sure what I should do about that. Obviously, the server is available for others, and (at times?) also available to you, otherwise you wouldn't have been able to upload the pictures in the first place. Not sure, but maybe using `traceroute` (or `tracert` on Windows) in the commandline could help at which point it is blocked.

**Comment by Helium314** [comment]
> We have same service provider: Elisa Eesti AS

That's a good start. My first guess would be that westnordost.de might be on the provider's blocklist for whatever reason (though I'm not sure whether such a list may/must/must not exist in Estonia).
Maybe a different DNS server could work.

**Comment by mnalis** [comment]
> The problem is not with my network because I can freely use internet with any other app on the phone and even doing hotspot to the laptop which is also using any website freely as long as there is no serverside problems.

Quite likely correct conclusion. We can also conclude that the problem is **not** on westnordost.de server either, as all of other people can connect to it without problems (at the same time when you are having problems).

That indicates that the problem is somewhere in transit between those two endpoints. Your ISP should be able to confirm that and trace that issue down to add appropriate workarounds (different preference routing for affected target networks).

What I would suggest is to write to your service provider (I say write, because if you use phone, it is less likely that you'd reach people who could help), and explain that you cannot open https://westnordost.de/ (with copy of that error message!) on several of your devices using their ISP, while you have confirmation from other people across the world that can access the same server at the same time without problems.

The commands that @westnordost mentions would indeed help determine where the problem might be, but your ISP should be capable of running them on their own. 

Other than that, you can try opening https://westnordost.de/ from some other ISP (e.g. WiFi at cafe or similar)

<details>

<summary>here is example how it works OK from my side; should the ISP tech support be interested</summary>

```
% ping -c4 westnordost.de
PING westnordost.de (62.108.32.100) 56(84) bytes of data.
64 bytes from ha01s020.org-dns.com (62.108.32.100): icmp_seq=1 ttl=48 time=46.8 ms
64 bytes from ha01s020.org-dns.com (62.108.32.100): icmp_seq=2 ttl=48 time=61.5 ms
64 bytes from ha01s020.org-dns.com (62.108.32.100): icmp_seq=3 ttl=48 time=60.9 ms
64 bytes from ha01s020.org-dns.com (62.108.32.100): icmp_seq=4 ttl=48 time=58.9 ms

--- westnordost.de ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3004ms
rtt min/avg/max/mdev = 46.759/57.020/61.475/6.000 ms

% traceroute westnordost.de
traceroute to westnordost.de (62.108.32.100), 30 hops max, 60 byte packets
 1  192.168.43.1 (192.168.43.1)  5.015 ms  5.204 ms  5.681 ms
 2  172.31.166.58 (172.31.166.58)  19.188 ms * *
 3  172.31.167.57 (172.31.167.57)  23.210 ms 172.31.166.57 (172.31.166.57)  23.266 ms 172.31.167.57 (172.31.167.57)  26.175 ms
 4  195.29.224.45 (195.29.224.45)  31.836 ms hst11-gst02-3.ip.t-com.hr (195.29.241.41)  34.441 ms hst12-gst01-2.ip.t-com.hr (195.29.224.197)  38.181 ms
 5  hdr11-hst11-2.ip.t-com.hr (195.29.144.85)  36.823 ms hdr11-hst11.ip.t-com.hr (195.29.144.53)  37.139 ms hdr11-hst11-4.ip.t-com.hr (195.29.224.69)  33.964 ms
 6  gut20-hdr11.ip.t-com.hr (195.29.224.238)  33.599 ms  30.224 ms gut20-htr11.ip.t-com.hr (195.29.240.234)  27.967 ms
 7  * * *
 8  ha01s020.org-dns.com (62.108.32.100)  45.864 ms  43.759 ms  47.372 ms
% 

```

</details>


(Only if the ISP is unable/unwilling to help, there are other workarounds, but they are more technically demanding, so it would be best if you'd convince them to help).

**Comment by mnalis** [comment]
@westnordost it would be interesting if you could do `traceroute www.elisa.ee` from westnordost.de server (they're not pingable, but traceroute would be informative)

**Comment by westnordost** [comment]
It's just a webspace, I do not have direct access to a shell there.

**Comment by mnalis** [comment]
@nata1993 it definitely seems to be on "Elisa Eesti AS" side; you can also include this link when you contact them:

https://atlas.ripe.net/measurements/55347177/#probes

This is RIPE measument, which shows that everyone from Estonia can reach westnordost.de server, **except** [AS2586](https://stat.ripe.net/2586) -- which happens to be _"Elisa Eesti AS"_.

**Comment by nata1993** [comment]
Update: My sunshine connected connected to nearby wifi which is using other service provider namely STV. The wifi is connected by wire using 10/10Mbit connection. Now I could connect to the https://westnordost.de/ and also see photos from OSM note. Hence it seems it is confirmation that it is a problem with ISP.

**Comment by nata1993** [comment]
Wrote yesterday to Elisa Eesti AS about this situation, no answer, no connection to westnordost server, nothing. Guess have to wait longer and write once more a bit later about this problem.

**Comment by nata1993** [comment]
Final update: It is fixed now and notes and website is finnaly fully accessible once again. Thank you everyone for very quick problem resolving!
