### ISSUE TITLE
Add more categories

### ISSUE THREAD

**Issue by exonas** [streetcomplete/StreetComplete#5065]
Currently there are only limited number of categories for POI. Please add more categories for example tourist attraction or religious place etc.

**Comment by matkoniecz** [comment]
In which context? Shop overlay?

**Comment by exonas** [comment]
yes that's right. If you could add all the categories from OSM then we would be able to search and select from there

**Comment by westnordost** [comment]
Which features are you missing in the shop overlay?

**Comment by exonas** [comment]
I wanted to add a pharmacy, tourist spot and a religious sites

**Comment by westnordost** [comment]
What kind of tourist spot? Are you sure that you cannot add a pharmacy? Which language are you using?

**Comment by exonas** [comment]
sorry I can add pharmacy but no tourist spot or religious site. please see attachment
![Screenshot_20230612-190934](https://github.com/streetcomplete/StreetComplete/assets/17995708/11a0db8d-cbf7-4dc2-9ab4-dee6a2be0879)
![Screenshot_20230612-190948](https://github.com/streetcomplete/StreetComplete/assets/17995708/1a318f17-babb-402a-a3f8-aa4d33d50735)

**Comment by exonas** [comment]
and tourist spot or religious site should not go under shop category. I am using english

**Comment by exonas** [comment]
For example I want to add a lookout or a mosque or a church

**Comment by westnordost** [comment]
The current guideline for what features are shown in the shop overlay is:

> Tenant of retail or commercial rooms, e.g. a shop, an office etc.. Something that can occupy (a part) of a non-purpose-built building.
> So, no larger purpose-built things like malls, cinemas, theatres, zoos, aquariums, bowling alleys...

A lookout would be included in the proposed overlay "street furniture", see #4912

A church or mosque are usually in a purpose-built building, no?

**Comment by exonas** [comment]
I understand. May I know why purpose built buldings are not allowed to add?

**Comment by westnordost** [comment]
That is a good question. First, I'll have to look up where the filter is used.

It looks like the same filter is used in...

- when a shop has been marked as vacant and the user is asked what kind of shop is there now
- when a shop has been tagged only with `shop=yes` and the user is asked what kind of shop it is specifically
- when the user answers (for various quests) that a shop does not exist anymore and he is asked what is there now
- to find all shops within a mall / railway station / bus station / airport terminal needing a `level` tag
- to highlight nearby shops in the UI when a question is asked about a shop, e.g. if a restaurant has vegetarian food, if smoking is allowed, what opening hours a shop has etc. - in all cases, this is done primarily for orientation.
- and of course, the shop overlay

So, I guess, the goal has been primarily to limit the amount of POIs somehow to a manageable size.

Only because changing a vacant shop to a for example railway station or changing a single shop within a mall to also a mall doesn't make any sense is not a an exclusion criterion per se because in that case, the user would never actually do that. After all the POI types are not displayed to him in a list, but he has to text-search for them.

Since only things that can also be added in the shop overlay are also displayed on the map - and I guess this is the most important thing - it should not be surprising to the user what is displayed and what is not displayed. Because if it was surprising, we'd see a lot of notes like "there is a X here!" for things where the X is actually already mapped. We do want to avoid that.

To limit the things that are displayed to only shops + things that could be in shops seems a reasonable cut of what to include to me, especially for an overlay that is named "Shops".

**Comment by exonas** [comment]
I get it. Thank you for the detailed explanation

**Comment by westnordost** [comment]
I went through the list again and and considered what could all still be in shop/office rooms. I added places of worship (e.g. prayer rooms), casinos, animal shelters and animal boardings to the list.
