### ISSUE TITLE
These quests should be enabled for Colombia

### ISSUE THREAD

**Issue by angoca** [streetcomplete/StreetComplete#5078]
**Use case**
Some quests have a restriction based on NoCountriesExcept to hide them in some countries. However, in Colombia, the following quests should be enabled because we have those kinds of features:

* AddAcceptsCash
* AddEntranceReference
* AddBusStopRef
* AddCycleway
* AddFireHydrantDiameter
* AddFuelSelfService
* AddSummitCross
* AddTactilePavingBusStop
* AddTactilePavingCrosswalk

**Comment by FloEdelmann** [comment]
> AddAcceptsCash

Are there many places that do *not* accept cash? Otherwise, (nearly) every answer would be "yes", so this quest would not pass the "no spam" guideline.

> AddEntranceReference
> AddBusStopRef

Can you post a photo how those reference numbers look like?

> AddCycleway

So many streets do have cycleways?

> AddFireHydrantDiameter

Can you post a photo how the hydrant diameter sign looks like? Is nearly every hydrant signed by such a sign?

> AddFuelSelfService

So there are many fuel stations that do *not* allow self service? Otherwise, this would be spam again.

> AddTactilePavingBusStop
> AddTactilePavingCrosswalk

How common is tactile paving in Colombia?

**Comment by angoca** [comment]
Tactile paving: 
![20230617_161724](https://githu
![20230621_133603](https://github.com/str
![20230621_133621](https://github.com/streetcomplete/StreetComplete/assets/294317/197ca769-63bb-4adc-8ec4-d18a15f4adcb)
eetcomplete/StreetComplete/assets/294317/3d9fda83-4770-4598-8cac-4f6973f65826)

![20230621_133426](https://github.com/streetcomplete/StreetComplete/assets/294317/8273d4d2-5710-408c-9468-8419d449a265)
b.com/streetcomplete/StreetComplete/assets/294317/9c28f802-5ac8-40b6-b806-75c75aa6d5b1)

**Comment by angoca** [comment]
Cycleways:
![20230621_134244](https://git
![20230621_133659](https://github.com/streetcomplete/StreetComplete/assets/294317/bcc1f1fb-1dbd-4333-8e58-5d868baf56e9)
hub.com/streetcomplete/StreetComplete/assets/294317/e96b32f7-183e-49b1-8bb3-64dc821d9850)
![20230621_133959](https://github.com/streetcomplete/StreetComplete/assets/294317/62c1067d-b859-4f4e-b8ac-b18f4b1e0b22)

**Comment by matkoniecz** [comment]
> AddEntranceReference

Seems really rare: http://overpass-turbo.eu/s/1wtT http://overpass-turbo.eu/s/1wtU

**Comment by mnalis** [comment]
> However, in Colombia, the following quests should be enabled because we have those kinds of features

As noted above, it is not a question whether those features **exist**, but how **widespread** they are. If there are (looking at a country as a whole, as SC doesn't have more precise sub-divisions) either **too little** (e.g. 1%) or **too much** (e.g. 99%) of that feature, then it would be **problematic** as it would "spam" the users (which might likely lead to them giving up on using the app completely). 
Ideally, the quest should have about 20-80% **different answers** across some country (just an example, not a hard limit).


So, because of that, one of the [quest guidelines](https://github.com/streetcomplete/StreetComplete/blob/master/QUEST_GUIDELINES.md) is:

> - :zzz: No spam: It must be possible to determine whether the quest should reasonably be asked. A quest which is to be answered in 99% of the time with the same answer is not a good quest, don't bore the users. I.e. asking for any road if it is a one-way road, is silly, because the vast majority of all roads will not be one-ways.


@angoca So the question is, can you give an estimate how much in `%` would the answers change for Colombia for each of the mentioned quests? (it would be great if you can give some links or overpass queries to back it up, but even just estimates would help).

---

P.S. StreetComplete guidelines are not perfect, of course. For example, some city in Colombia might very well qualify for quest, but if the rest of the country doesn't, it is not possible to express in StreetComplete - it can only be enabled or disabled for whole country. There is always an option of forking and changing it to suit your particular case, it's [not that hard](https://github.com/streetcomplete/StreetComplete/blob/master/CONTRIBUTING_A_NEW_QUEST.md#alternative-to-android-studio) if there is a need for it. (at his point I actually usually recommend [SCEE](https://wiki.openstreetmap.org/wiki/SCEE) instead, but it seems not even there is overriding country blocks possible - would you think it would make sense @Helium314 ?)

**Comment by Helium314** [comment]
> it seems not even there is overriding country blocks possible

The main issue is that it would need to be allowed on a per-quest base.
Some quests like hydrant diameter or cycleway need to be adapted to actually use the correct signing (hydrant signs, cycleway markings).
For other quests like `AddAcceptsCash` this isn't necessary (though honestly I don't understand what is meant by "_we have those kinds of features_" in this context).

**Comment by FloEdelmann** [comment]
@angoca Could you please have a look at my questions (and also see @mnalis's explanation) and try to answer them?

**Comment by angoca** [comment]
The initial objective of this issue was to ask for the inclusion of Colombia in the mentioned quests.

For example, for the hydrants, in this line: https://github.com/streetcomplete/StreetComplete/blob/7434f6bdf8ff2137a61bed94091c0c87e3cd09a3/app/src/main/java/de/westnordost/streetcomplete/quests/fire_hydrant_diameter/AddFireHydrantDiameter.kt#L31

Currently, it only appears in these countries:

```
override val enabledInCountries = NoCountriesExcept("DE", "BE", "GB", "PL", "IE", "FI", "NL")
```

And for the cycleway in this line
https://github.com/streetcomplete/StreetComplete/blob/7434f6bdf8ff2137a61bed94091c0c87e3cd09a3/app/src/main/java/de/westnordost/streetcomplete/quests/cycleway/AddCycleway.kt#L50

```
override val enabledInCountries = NoCountriesExcept(
        // all of Northern and Western Europe, most of Central Europe, some of Southern Europe
        "NO", "SE", "FI", "IS", "DK",
        "GB", "IE", "NL", "BE", "FR", "LU",
        "DE", "PL", "CZ", "HU", "AT", "CH", "LI",
        "ES", "IT", "HR",
        // East Asia
        "JP", "KR", "TW",
        // some of China (East Coast)
        "CN-BJ", "CN-TJ", "CN-SD", "CN-JS", "CN-SH",
        "CN-ZJ", "CN-FJ", "CN-GD", "CN-CQ",
        // Australia etc
        "NZ", "AU",
        // some of Canada
        "CA-BC", "CA-QC", "CA-ON", "CA-NS", "CA-PE",
        // some of the US
        // West Coast, East Coast, Center, South
        "US-WA", "US-OR", "US-CA",
        "US-MA", "US-NJ", "US-NY", "US-DC", "US-CT", "US-FL",
        "US-MN", "US-MI", "US-IL", "US-WI", "US-IN",
        "US-AZ", "US-TX"
    )
```

And you asked me, "So many streets do have cycleway?". I already wrote that only Bogota has more than 500 Km of cycleways, and other cities have a lot of cycleways too. However, I don't know the total kilometers of cycleways, so we are mapping them.

Similar thing for hydrants, I don't know the total, but I know there are different types of diameters with the number on them (4 inches, 6 inches, 8 inches).

Regarding "AddAcceptsCash," many shops stop receiving cash only to receive cards, but I don't know the total number of shops accepting and not accepting cash.

"AddEntranceReference" could be used for houses with multiple doors with a different house number on each one, where a door connects directly to the second floor and another connection to another place in the house, for example. I know they exist, but I don't have details for the whole country.

The bus stops have a number on them, and "AddBusStopRef" could be used for that. I don't know how many bus stops do not have numbers across the country, but I know there are more than 6000 bus stops with a ref number only in Bogota.

In Colombia, self-service for fuel is not popular, so it is very important to identify the self-service stations with AddFuelSelfService.

In many mountains, the peak is marked with AddSummitCross, as we have Christian roots, so there are present everywhere, but I don't know how many peaks have a cross on them. And a quest like that at the peak won't be spam, as it could be the only available one in the area.

Also, some sidewalks and bus stops have tactile paving, but I don't know the proportion of sidewalks with and without tactile paving.

Initially, you asked if we have those features in Colombia, and I have shown they exist. But in the last comments, you wanted to give statistics about the proportion of the feature that exists or not to prevent spam which is almost impossible from a volunteer perspective.

**Comment by mnalis** [comment]
> And you asked me, "So many streets do have cycleway?". I already wrote that only Bogota has more than 500 Km of cycleways, and other cities have a lot of cycleways too

I think it is misunderstood, it was never about **absolute** number of cycleways (or their total length). It is about **ratio** of _"roads that has cycleways"_ to _"roads that don't have cycleways"_. In other words: _**"what percentage of answers to that quest would have same answer?"**_

So the information _"about 1 in 5 roads has cycleways"_ has great amount of wanted information (even if actual more precise number is _"1 in 3"_ or _"1 in 7"_ instead!), but _"there is 500km or cycleways"_ or _"there is 7k cycleways"_ would be useless, as it would not help answer the _"spamminess"_ question. 

> And a quest like that at the peak won't be spam, as it could be the only available one in the area.

That reasoning I agree with; for that particular quest; it there are even just a few crosses in peaks in whole country (which should certainly be possible to find out!), it should be enabled.

> Initially, you asked if we have those features in Colombia, and I have shown they exist. But in the last comments, you wanted to give statistics about the proportion of the feature that exists or not to prevent spam which is almost impossible from a volunteer perspective.

I understand that is is impossible to give exact percentage, but I don't think that anybody asked for that. But:
- one could ask for opinions of other people if that country on their contact forums, chats etc. what that ratio of yes/no (or whatever) answers would be in **their** regions/cities
- one has their own personal knowledge of cities they live in or have visited
- there might even be some municipality data available (e.g. if you can find there is 500km or cycleways, you may also be able to find out that there is some [200,000 km of roads](https://en.wikipedia.org/wiki/List_of_countries_by_road_network_size) and **roughly** estimate it is about `0.25%` of the roads).

I agree that it does need **_some effort_** to research, but it pales in comparison by how much **needless effort would be saved for all those Colombian mappers if spammy quest is not included**.

So I think based on that it should be possible to classify each quest roughly in two categories:
- average for that country is estimated to be between 10%-90% distribution of answers (those can be included in StreetComplete quests) 
- average for that country is estimated to be more like 99% (for either answer)

(In case of doubt, you should err on the side of assuming that quest would be spammy.)

---

Note that this "spam" problem is only related to StreetComplete **Quests**, which are asked on every element. 

Alternatives for quests which would be spammy data are:
- use  **StreetComplete Overlays** instead (if existing, of ask for them if they don't) - spam is not a problem there as you only edit exactly what you click on, instead of each and every road/ element.
- you can lobby [SCEE](https://github.com/Helium314/SCEE/issues) to allow overriding most of them (see abovehttps://github.com/streetcomplete/StreetComplete/issues/5078#issuecomment-1605589893)
- fork and build (and distribute to your fellow mappers who'd also want that) your own version without the limits (as noted above, it's easy even for non-programmers with few easy [clicks](https://github.com/streetcomplete/StreetComplete/blob/master/CONTRIBUTING_A_NEW_QUEST.md#alternative-to-android-studio))
- use alternative direct-user-action-based app instead of quest-based app (I'd recommend [Every Door](https://wiki.openstreetmap.org/wiki/Every_Door) for POI-based edits)

**Comment by FloEdelmann** [comment]
Let's maybe split this issue into several issues and discuss/enable the quests individually. I think that would make the individual issues more actionable and avoid long back-and-forth questions and answers.

**Comment by FloEdelmann** [comment]
I extracted all suggestions to separate issues (see the links above), so I'll close this now.

@angoca Please note that many of those quests probably ***are*** worth enabling in Colombia given your examples. We just want to make sure that the quests are not enabled if they are hard to answer or spammy, and thus lead to bad or useless answers or many opened notes. We don't do this to scare you away!
