### ISSUE TITLE
Shop name should also be asked in shop overlay

### ISSUE THREAD

**Issue by rhhsm** [streetcomplete/StreetComplete#5085]
**Use case**
When adding a new shop in the shop overlay, the nature and name of a shop is asked in one question, so usually they are answered at the same time. However, existing shops without name tag are not quested with the shop name quest, and as a consequence, the shop opening hours quest does not appear either. It often appears to me that all shops shown in the shop overlay are with complete information, and only after switching to another overlay later, it becomes clear there are still quests to be solved for some nameless shops (so that I have to walk back to those shops to solve their quests).

**Proposed Solution**
Shop name quest should be shown for shops without name tag in the shop overlay.

**Comment by matkoniecz** [comment]
see #4910

**Comment by arrival-spring** [comment]
How about highlighting shops without type or without name (and without name:signed=no etc.)?

That way the user is encouraged to check such shops, as otherwise such places are not so obvious.

**Comment by rhhsm** [comment]
Sorry for not doing a search before posting...

> How about highlighting shops without type or without name (and without name:signed=no etc.)?

They can be highlighted by showing the shop type or shop name quests. The user is familiar with these quests in other overlays and I don't see the logic of not showing these in the shop overlay.

I also don't see a reason not to ask for shop opening times for shops that have no name tag (yet). A quarter of the shops in the area I normally survey has no name sign.

**Comment by rhhsm** [comment]
Sorry to be unclear: I just wanted to say that it's far from exceptional that a shop has no name (I use the "There is no name sign" option a lot), so there is no reason to not ask for opening hours for a nameless shop.

**Comment by mnalis** [comment]
> Sorry to be unclear: I just wanted to say that it's far from exceptional that a shop has no name (I use the "There is no name sign" option a lot), so there is no reason to not ask for opening hours for a nameless shop.

Yeah, I suspected that might be the case, that's why added my example: it is also _"far from exceptional that some building has an address"_ (in fact, around here, it is quite more likely that they have address then not!), but I still (grudgingly) have to solve `building type` quest before I am allowed to proceed to solve `housenumber` quest. Same is in your case where `opening_hours` is blocked by `name` quest.

What I meant to say, it is a workflow, and _there are reasons_ why it was made that way. Perhaps that reason is less strong in your area (maybe you rarely/never have several shops one near another?), but the workflow should be made so it makes most sense worldwide in wide variety of cases.  
To me, it does make sense to **first request** shop name (even if the answer might be _"no name"_ relatively often), as it makes most sense for most cases _globally_ (i.e. as it reduces user mistagging errors and makes orientation much easier in all subsequent quests).

**Comment by rhhsm** [comment]
I agree that it's probably a good idea to rank the shop name quest above the opening hours quest, but it shouldn't be a condition that the shop name quest is solved first. All shops have opening hours (although they may be irregular and not displayed), but many building types don't have addresses. Anyway this is a very minor point, not worth discussing much... my main point is that shop type and shop name quests should be displayed in the shop overlay.

**Comment by matkoniecz** [comment]
>  it shouldn't be a condition that the shop name quest is solved first.

this may prevent some cases of confusion with shops which are missing name data and are misplaced/not existing, or simply name data is not yet collected

**Comment by mnalis** [comment]
> main point is that shop type and shop name quests should be displayed in the shop overlay.

That I agree with! Referenced issue says in _"https://github.com/streetcomplete/StreetComplete/issues/4910#issuecomment-1488329249"_:
>  If you don't enter the name in the overlay because you are not sure what is the correct one, the name quest doesn't help.

- However  that is **only** correct if your workflow is:
  - enter Shops overlay
  - add one shop
  - exit overlay & continue using SC

- The issue manifests if your workflow is instead (much more sensible, IMHO) like this:
  - Enter Shops overlay (for prolonged period of time!)
  - add one (or more) shop(s)
  - remain in overlay and expect you can still add missing data to **other** POIs (**not** the ones you've just added).

  If which case, **user would not expect** that `opening_hours`, `wheelchair_access`,  `accepts_cards` etc. quest would be hidden for all shops/amenities on the map just because they are in the mode that allows them to add new shops (and their names).

 
---

Possible solutions/workarounds that I see:
- **[Remove](https://github.com/streetcomplete/StreetComplete/issues/4910#issuecomment-1488386808) `name` checks from all quests** that use it (`opening_hours`, `opening_hours_signed`, `accepts_cash`, `wheelchair_access`, `accepts_cards` ). That would then rely or default ordering of quest (instead of hardcoded quest dependency) to fill `name` first in order to help user orient for subsequent quests, which should be enough.
  While hardcoded dependency might help with positioning, it is not used consistently, so this option would also solve that consistency problem  -- e.g. 5 quests above implement `name` check, but many others (`smoking`, `air_conditioning`, `vegeterian`, `vegan`, `kosher`, `halal` etc) do not.   
  Note that if this suggestion in not acceptable, we should probably add `name` check to **all** POI-related quests for consistency sake, and not just some of them. Also some check `noname=yes` in addition to `name:signed=no`, but others do not so that should be fixed too probably.

- **Remove `AddPlaceName` from `hidesQuestTypes` in `Shops overlay`.** This would then show `name` quest normally even if Shops overlay is active, which should not be too confusing (even if you can add the name in Shop Overlay quest, it is not its primary purpose -- like adding address in address quest is, for example)

- if even that is not acceptable, at least POIs that miss all of `name` / `noname=yes` /  `name:signed=no` should be **displayed in different (red?) color** in `Shops overlay` to indicate that they miss critical data (which will block other quests). Because currently while it is possible to see in Overlay that shop does not have label, it is **impossible** to say whether that is because it is tagged with `name:signed=no` or because such critical quest-skipping-tag is missing. Currently AFACT POI icons are always black, so that might need some extra code though.

- or, a **preference `Hide related quests while in overlay`** might be introduced (unlikely to happen for upstream SC, but might be an option for [SCEE](https://wiki.openstreetmap.org/wiki/SCEE)). That would allow users bothered with overlays hiding quests to override that behaviour (not just in this specific case, but in all of them).

**Comment by westnordost** [comment]
I am a fan of consistency. I will look into option a.

**Comment by westnordost** [comment]
Hm, it was actually added in #4448.

I want to avoid going forth and back about this. In Oct 2022 a decision was made, it would make no sense to revert that decision now without the situation having been changed.

**Comment by rhhsm** [comment]
> I am a fan of consistency. I will look into option a.

Me too, because it is usually more user-friendly. But if it isn't then user-friendliness should come first (see #4622 for instance). But above that, ensuring no wrong data are entered is most important. @mnalis second option would enhance both data quality and user-friendliness.

**Comment by westnordost** [comment]
Okay, I implemented to also hide the other quests in case no name is specified. However, only for quests that apply to a wildcard of shops, so not `AddVegetarian` etc. because it only applies to a very limited number of POIs where we can assume that they are present in the iD presets.
