### ISSUE TITLE
Add a warning when tapping to fill nearby road names

### ISSUE THREAD

**Issue by ppnplus** [streetcomplete/StreetComplete#5087]
**Use case**

Currently, in the "What's the name of this road?" quests, tapping on the empty field would allow users to fill names from other nearby roads. However, I've seen changes from users that have done this via StreetComplete without checking the road's actual names and apply them even when it's different or unnamed in real life: https://www.openstreetmap.org/changeset/119132179 & https://www.openstreetmap.org/changeset/129819931 (notice multiple roads with the same name; some have later been reverted)

**Proposed Solution**

I'd like StreetComplete to display a warning when trying to apply nearby road names to the quest with something like, "You're applying the name from other roads, which might have a different name than the one you're applying to. Have you surveyed the road's actual name?" to reduce chances of misunderstanding like this.

**Comment by matkoniecz** [comment]
>  However, I've seen changes from users that have done this via StreetComplete without checking the road's actual names and apply them even when it's different or unnamed in real life: https://www.openstreetmap.org/changeset/119132179 & https://www.openstreetmap.org/changeset/129819931

I would strongly recommend commenting on their changeset comments if they add fake data. And reverting their edits if data being added is actually fake.

In general, StreetComplete already asks to survey rather than guess and adding such warning before each edit will not stop vandals and fakers and will just annoy proper mappers.

Sadly, SC is not magical and cannot stop people adding fake data - and adding numerous "do not add fake data" warnings is unlikely to achieve that.

(if someone damages OSM data using StreetComplete and you do not know how to stop them I would be able to help you with that - especially by linking documentation how to handle vandals)
