### ISSUE TITLE
Add quest: Is Bitcoin still accepted here?

### ISSUE THREAD

**Issue by anton-isidore** [streetcomplete/StreetComplete#5097]
### General
This is loosely related to #4396

The world starts adopting Bitcoin for mayments and number of places that accepts it grows.

Here is great project that helps to tag all such places: https://btcmap.org/

But the problem is that sometimes, the place stops to accept Bitcoin for various reasons. Also, there is some egacy data, from times when Lightning Network was not available. Those places most likely don't accept Bitcoin anymore, but needs to be checked.

This quest tries to help to solve that.

--------

Affected tags:
- currency:XBT https://taginfo.openstreetmap.org/keys/currency:XBT#chronology
- payment:onchain https://taginfo.openstreetmap.org/keys/payment:onchain#chronology
- payment:lightning https://taginfo.openstreetmap.org/keys/payment:lightning#chronology
- payment:lightning_contactless https://taginfo.openstreetmap.org/keys/payment:lightning_contactless#chronology

### Checklist
Checklist for quest suggestions:

- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by any pedestrian from the outside but a survey is necessary
- [x] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of map data (Worth the effort)

The last checklist item may seem a bit controversial but I believe it's definitely worth the effort, Bitcoin adoption grows a lot and we need the up to date data. Most of the Bitcoiner are using OpenStreetMaps to find a Bitcoin accepting restaurants. **Please check those charts for tags, it's growing like crazy**.

### Ideas for implementation
Just simple question to display if those data are old (one or two years)?

"Is Bitcoin still accepted here"?

If answer is "no" just remove those tags. If answer is yes" just update date when it was last checked.

**Comment by westnordost** [comment]
I am sorry, but I've now decided that any tagging of `payment:*` where * is a specific payment service, from bitcoin, to paypal, to google pay, to mastercard, to debit card, shall not be done with this app. Generally.

The reasons are:

- **💵 Valuable surveyors:** Whether or not a shop accepts certain payment methods is a very volatile information that may change frequently or even without the shop's knowing. Volatile data necessitates more frequent re-checking which further draws on the limited resource of OpenStreetMap surveyors time.

- **🕵️ Publicly accessible on foot:** Especially non-hype currency is often not advertised on the outside. One may occasionally see a handwritten note sticked to the shop door "no card payment", or nothing, or the waiter telling you that card payment is (currently?) not possible, some may have a sticker with logos of accepted cards on their door, but not all. Plus, if e.g. google pay is missing from that sticker, it doesn't mean that it is not available, it just means that they didn't put the sticker there (yet).

- **🪧 Advertisement / 🚧 Established tags only:** Shops that accept hype currency such as the various cryptocurrencies or start-up payment processors are usually so few when compared to the total number of shops that mapping these at all feels like doing advertising for these

- **💤 No spam:** ... and of course, the answer the user gives will almost always be the same: no.

- **💵 Valuable surveyors:** Hype currency aside, every shop uses some kind of payment processor that accepts certain services, which may change over time. The number of payment processors in an area is much smaller than the number of shops. I find it questionable if tagging all payment services accepted _on each shop_ is the right approach here at all as the tagged information becomes wrong as soon as the payment processor used by the shop changes which services are accepted or the shop changes the payment processor. I am not advocating for tagging the payment processor instead, because this is even less 🕵️👨‍💻 publicly accessible, 

- **🤷 Useful purpose:** To be useful, the data has to have a certain coverage and needs to be kept up to date. However, I strongly doubt there will ever be a good enough coverage that the data will be useful because frankly, the effort involved in keeping this data correct and up to date is just too much. Maybe not if there was just one or two payment services on earth, but...

- **💵 Valuable surveyors:** It is a bottomless pit. There is an ever-growing mass of payment services out there, tagging them all and _keeping them up-to-date_ in OpenStreetMap is unrealistic. At most, what would be realistic is to make the distinction "card payments" / "cash payments", without specifying which kind of cards - cause that is rather dependent of the region you are in right now than the specific shop you are in. However, looking at taginfo, there is not really any single established value for specifying that unspecified "cards" are accepted
