### ISSUE TITLE
Automatically split long ways because they are hard to survey

### ISSUE THREAD

**Issue by Zaczero** [streetcomplete/StreetComplete#5101]
**Use case**

I am sometimes hesitant to answer quests on VERY long ways. I suppose I am not the only person. It would be very convenient for such ways to be automatically split. I know there is a split feature but deciding where to split from the pedestrian perspective is difficult in such cases. Doing it automatically would be a welcome feature.

**Proposed Solution**

When loading a quest, the way is automatically split above some threshold. Only the nearest part is then shown to the user as part of a quest. The split way is submitted to OSM once user answers the quest.

There should be a different limit for footways and roads. The split should prefer an intersection location, if such is nearby the threshold distance.

**Comment by westnordost** [comment]
I don't see how this could be done in a meaningful way automatically. And certainly, we don't want the app to be acting on its own, splitting ways "just in case" the user is going to answer it differently for the sections presented. The changes are made in the user's name after alll.

**Comment by matkoniecz** [comment]
> but deciding where to split from the pedestrian perspective is difficult in such cases

Split into surveyed and not surveyed part

**Comment by Zaczero** [comment]
If you both agree in this being a non-issue, maybe it's just me.

**Comment by amandasaurus** [comment]
I have this problem often when hiking, and I would like an easier way to split long ways. I don't think it should be done automatically, but I think it should be easier & quicker than it is now.

(a) When I'm hiking in the forest, some of the OSM ways are large, and I'm also uncertain about adding a tag to the whole thing in one second. If I could split a way into ~ 100m (?) sized ways, and then add the surface many times. A downside of this is that it makes many small OSM ways, which may, or may not, be needed in the end.

(b) Sometimes I walk past a junction, and can see the first ~50m(?) of the track. and can see the surface, or smoothness. I'm not walking down that path, so I can't say for certain. I'd like to be able to split the way into the first X m (?) quicker & easier than currently.

I think (b) (“Quickily split off first X m”) is few downsides, and would be benefitial. (a) (“Quickly split into X m sized chunks”) has downsides, and I'm unsure if the outways the benefits

**Comment by mnalis** [comment]
> (a) (“Quickly split into X m sized chunks”) has downsides, and I'm unsure if the outways the benefits

yes, that one is definitely too problematic IMHO, as it would _both_ create a ton of unneeded chunks _and_ would increase mapper load significantly.

> (b) (“Quickily split off first X m”) is few downsides, and would be benefitial. 

I'm all for making manual split quicker & easier, but I don't have an idea how design could look like which would accomplish that[^1]? Can you **detail how you envision this easier way would look like** in steps, @amandasaurus ?

But I personally do not do that (_"mark surface of first 50m of some way I do **not** intend to walk"_) because:
- only having _**50m**_ tagged _**does not really help**_ all that much
- if the rest of the **_way becomes worse_** (as it too often does in my experience, esp. for forest trails:  e.g. starts as compacted for 100m and then becomes ground after the house, or starts as an asphalt and then becomes compacted track later etc), it creates even worse situation then if I didn't map anything at all (as it will actively **_mislead people_**)
- it _**hides it from my (and other mappers) eyes**_ for the next time when I pass that crossing, making it **_less likely to get fully tagged_** eventually - as if I can see it is untagged yet, it is quite likely that I might modify my route to go _that way_ instead, even if it is longer or in completely wrong direction. If it however looks tagged (because first `50m` or whatever are mapped), I would likely just pass it...

So because of that I personally actually prefer to either tag the whole way correctly (splitting manually as needed to tag changes in properties), or at least significant part of it (e.g. 30-60% or whatever) for ways which are very long (e.g. dozen kilometers with several intersections).

[^1]: Only idea I personally can see how  this idea with _"first `X` m"_ might work, would be to have user have to select the way the want to split by clicking on it, and then entering number of meters (and direction, if it is not start of the way) , which seems to me to be even more complicated than current method of just clicking on the position of the way where you want to split it - so something better than that specific method would likely be needed to actually improve the situation.

**Comment by amandasaurus** [comment]
On Di, 12 Mär 2024 17:29 +01:00, Matija Nalis ***@***.***> wrote:
> yes, that one is definitely too problematic IMHO, as it would […] increase mapper load 
> significantly.

My suggested “Split every Xm” would only be done manually by the mapper, never automatically. Since the mapper has chosen this, it's no longer a bad thing for “increasing their work load”

-- 
Amanda

**Comment by matkoniecz** [comment]
I admit that I have no idea how interface for doing could look like - and be noticeable improvement to current one.

Occasionally I split overly long ways when I surveyed only part and this never seemed to be a real problem in mapping to me.

Can you propose which specific steps with new interface mapper would take to split way?

**Comment by mnalis** [comment]
> My suggested “Split every Xm” would only be done manually by the mapper, never automatically. Since the mapper has chosen this, it's no longer a bad thing for “increasing their work load”

My concern was if **that mapper _didn't_ end up walking 100%** of that path, it would negatively affect other mappers. 

E.g. if the mapper asked SC to split that path every `50m`, and the way was e.g. `1.5km` long, that would create `30` segments. But if they only ended up walking first e.g. `250m` and then took a turn (or even didn't go on that way at all, but only "saw" first `50`-`100m`) they'd only map `1`-`5` segments, leaving remaining `25`-`29` segments for someone else to solve, thus significantly **increasing the load of those _subsequent_ mappers.**

And **if they are 100% going to walk the whole way**, then I do not see the need for such auto-splitting-in-equal-chunks at all? Simply walk until you see the difference, and _only then_ split the way and tag it differently. That would create optimal (minimal)  amount of splits, thus producing better result for everyone. And it would reduce load for both current and subsequent mappers. Looks like win-win to me?

---

But perhaps I am misunderstanding what exactly are you suggesting :man_shrugging: ; could you please give us step-by-step example showing use case where your suggested new way of splitting whould be helping the mapper(s)?
