### ISSUE TITLE
Survey crossing:markings

### ISSUE THREAD

**Issue by Zaczero** [streetcomplete/StreetComplete#5102]
### General
Affected tag(s) to be modified/added: [](https://wiki.openstreetmap.org/wiki/Key:) crossing:markings=*
Question asked: **What markings are on this crossing?**

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/blob/master/QUEST_GUIDELINES.md)):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by any pedestrian from the outside but a survey is necessary
- [x] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of map data (Worth the effort)

### Ideas for implementation

**Element selection:**

nwr[crossing][!crossing:markings]

**Metadata needed:** 

**Proposed UI:**

The selection should be similar to the surface UI as there are quite many variations. Most popular are displayed on top: zebra, dots (for bicycle), lines, etc.

The tricky part would be to allow selection of up to 2 markings for segregated= cases. For example zebra;dots is a valid value.

**Comment by matkoniecz** [comment]
is there anything new compared to #4663 ?

See https://github.com/streetcomplete/StreetComplete/issues/4663#issuecomment-1335952083

**Comment by Zaczero** [comment]
In which format should such metadata be provided? I'll see whether I can prepare it. Does it need to be done for all countries? Or can I simply prepare it for e.g., TOP 90% of countries, and for other countries such task wouldn't simply be displayed? Thanks!

**Comment by westnordost** [comment]
I am closing this because:

- see #4663 
- #4886 will be done sooner or later anyway (but just with `crossing:markings=yes/no`, not with any of the more elaborate values)

**Comment by Zaczero** [comment]
> A new issue or this issue can be reopened if such documentation has been done.

As I said, I am willing to provide necessary metadata as long as you provide me with requirements for it.

I personally dislike your unwillingness on discussing issues, and quickly closing them, despite them being unresolved and in progress. Not nice.

**Comment by westnordost** [comment]
If you are willing to research it, I propose you document the findings in the openstreetmap wiki, given the sheer scope of such research.

In which form I can't say because this would require some overview over what the different markings in different countries may all signify. E.g. in Germany, zebra-like markings mean that pedestrians have right of way, dashed lines don't mean anything in terms of right of way (as far as I know) but it could be different and there could also be more categories in different countries.

So, the scope of research would be to find 1. which markings are used in different countries and 2. which they each signify. If there is some form of regularity there, I propose to put the information in a table (country x meaning in legislation = marking).
