### ISSUE TITLE
Lifeguard tower building type?

### ISSUE THREAD

**Issue by NeatNit** [streetcomplete/StreetComplete#5112]
SC asked me what kind of building this is: https://www.openstreetmap.org/way/1067695950

This is a lifeguard tower, built and designed solely for this purpose, and I found no option that feels right. Currently it's tagged: building=yes; emergency=lifeguard.

Photo: 
![20230702_110837](https://github.com/streetcomplete/StreetComplete/assets/2400026/d3c622d7-41df-4ec1-b2c2-55d3ed977ac3)

**This is most likely an OSM Wiki issue, not a StreetComplete issue, but I think posting it here will be the most helpful.**

Should it even have a building tag? It's certainly a building, but the wiki page for emergency=lifeguard and related pages don't specify how (or whether) to select the `building` tag. The closest option I could see on SC is "hut", which feels wrong. I didn't see anything like "watchtower" - which even that wouldn't feel quite correct.

- What should a StreetComplete user answer here?
- What should the wiki say about this?
- Should SC even ask this question?

**Comment by westnordost** [comment]
Well, of course StreetComplete cannot offer every single possible building type that exists in its UI, so that is why you can leave a note if you do not find anything fitting so people could discuss whether to just set `building=lifeguard_tower` or something.

However, what I'll also do is to not ask for the building type for buildings that have `emergency=*` tagged. Thanks for the hint.

**Comment by peternewman** [comment]
> However, what I'll also do is to not ask for the building type for buildings that have `emergency=*` tagged. Thanks for the hint.

Won't that potentially preclude people from tagging fire stations and hospitals in future?

**Comment by matkoniecz** [comment]
Only if poorly tagged as the same object as a building

**Comment by mnalis** [comment]
> Won't that potentially preclude people from tagging fire stations and hospitals in future?

Well, as far as I know, people were **never able to tag fire stations** (i.e. [amenity=fire_station](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dfire_station)) or hospitals (i.e. [amenity=hospital](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dhospital) or [healthcare=hospital](https://wiki.openstreetmap.org/wiki/Tag:healthcare%3Dhospital)) using StreetComplete anyway (although it would've been nice if `Shops overlay` was renamed & extended to allow people to do that, instead of leaving notes). 

What they could've tagged is that architectural type of specific building resembles architectural type of common fire station or a hospital (regardless of what that building is [actually being used](https://wiki.openstreetmap.org/wiki/Key:building:use) for) - which is AFAICT hardly used by any data consumer except maybe some advanced 3D renderers (and StreetComplete itself so it [doesn't ask address quests on e.g. sheds](https://github.com/streetcomplete/StreetComplete/issues/2464)). 

IOW, that [building type](https://wiki.openstreetmap.org/wiki/Key:building) information, even when recorded, certainly wouldn't (shouldn't) be used by router in your mobile app routing you to nearest hospital or anything like that.
