### ISSUE TITLE
Add MLC sign to max_weight quest

### ISSUE THREAD

**Issue by qugebert** [streetcomplete/StreetComplete#5115]
**Use case**

When asked what the maximum weight of a bridge is, I have a variety of signs to choose from. 
![Screenshot_20230702-145610](https://github.com/streetcomplete/StreetComplete/assets/44033795/2995fb07-0a17-463d-8ac4-469871a19ea2)

At least in my area, the maximum weight is often only signposted by the MLC sign. 
![158788](https://github.com/streetcomplete/StreetComplete/assets/44033795/e3991c3d-68c1-4759-bc95-000b4918a5d8)

This sign is currently not available for selection in StreetComplete. Now I can select "Shield looks different" and have to leave a note. At least in my area, this results in a lot of notes that need to be dealt with manually. 

Tagging of this sign can be found here:
OSM-Wiki:  https://wiki.openstreetmap.org/wiki/MLC

**Proposed Solution**

- Adding the MLC signs to the user interface, at least in countrys where these type of sign is used.
- When searching for max_weight-quests, ignore bridges which are already tagged with mlc

**Comment by westnordost** [comment]
How prevalent is this? According to https://taginfo.openstreetmap.org/search?q=mlc#keys it is barely tagged at all.

Given the many different variations and the very low number of currently tagged values, I do not think it is worth the time & effort to implement this.

It is always possible to leave a note when the question cannot be answered through the StreetComplete UI.

**Comment by westnordost** [comment]
Regarding

> When searching for max_weight-quests, ignore bridges which are already tagged with mlc

I am not sure which tags to look for. The documentation on wiki.osm.org is sparse and even the article on Wikipedia is quite short. E.g. what about the `maxweight:mlc*` keys? Is this a mistagging, or synonymous to the `mlc` keys?

**Comment by HolgerJeromin** [comment]
I think this is often not tagged because not many mappers know that this yellow sign (I just learned) is showing a max_weight.
This could be a problem with SC itself, because most mappers will hit "there is no sign" instead of "choose the sign".

**Comment by westnordost** [comment]
Which is not so much of a problem because the "not signed" refers to the `maxweight` which is somewhat correct, i.e. `maxweight:signed=no` is tagged (not `mlc:signed=no`).

Anyway, even if there were more than around 300 usages on OSM, that sign has something like 5 variations, so it is really not worth the effort to implement. As far as I understand, these signs are also mostly only used in West Germany (not at all in East Germany) and their number is declining because since 14 years, it is not mandatory to put them up.

So, I pondered not showing the maxweight quest if mlc is tagged, but I think it makes sense to ask for a "proper" maxweight sign anyway. Only because an MLC is signed doesn't mean that the normal maxweight/axle weight/... signs are not.
