### ISSUE TITLE
Ask AddCrossing for sidewalks

### ISSUE THREAD

**Issue by Helium314** [streetcomplete/StreetComplete#5160]
I recently found a place where _AddCrossing_ unexpectedly wasn't asked, and then stumbled upon https://github.com/streetcomplete/StreetComplete/blob/321ee53cd4502b1f24570818627266d4ac6f9300/app/src/main/java/de/westnordost/streetcomplete/quests/crossing/AddCrossing.kt#L33-L36

Would it be ok to just hide the `crossing=no` answer instead of not asking at all? Or maybe open a dialog asking to open a note and describe the situation?
This would enable the _AddCrossing_ and all the follow-up quests for many more ways.

**Comment by westnordost** [comment]
It might be a bit unexpected for users if the "no" answer was not available. But then again, in this case we kind of **want** to make the user uncertain so that he leaves a note. So, it would be fine by me.

**Comment by peternewman** [comment]
The complete absence of the answer is going to feel like a bug though surely, whereas a similar situation in another quest (I can't remember which one off hand), picking that option brings up a little dialogue explaining which option to pick instead.

A bit like House number>Other answers>Multiple house numbers.

**Comment by westnordost** [comment]
> (I can't remember which one off hand)

Hmm, ... if your point is about being consistent, then it would be very helpful if you could name the quest in which this was the case.

**Comment by Helium314** [comment]
The smoking quest also has different answers depending on the element. So far no one reported a bug that the `OUTSIDE` answer is sometimes missing.

**Comment by westnordost** [comment]
Hmm, nevertheless, reflecting on what Peter wrote, basically, the `crossing=informal` option would need to be removed too due to https://github.com/streetcomplete/StreetComplete/pull/2999#discussion_r681516203 , no? After all, a situation where there is no marking at all could - depending on the surveyor - be either interpreted as "no, forbidden" or "no official crossing but crossing is possible".

So either, there would only be one singular answer option, "yes", and this would surely look like a bug.

Or, if the "no official crossing but crossing is possible" options remains alongside "yes", maybe there is the danger that users will incorrectly chose that option instead of the "no, forbidden" one?

**Comment by westnordost** [comment]
An easy fix for that and I seem to remember it has been done elsewhere (maybe when answering that a place that is also a vertex does not exist, or something?) is to leave the option but prompt the user to leave a note in this case. Maybe there is already a text for that?
