### ISSUE TITLE
Strange string prompted when asking for shop names

### ISSUE THREAD

**Issue by hmartink** [streetcomplete/StreetComplete#5165]
![Screenshot_20230107-135323](https://github.com/streetcomplete/StreetComplete/assets/46402758/62c95469-7d6a-4104-b6b9-53ef9a265baa)

When I'm asked for shop names, I always get a "de" before the input prompt. I duly went poeditor.com, selected German but I cannot locate (find) a string which matches either in the original form or in the translation the string "de". Thus I'm providing the bug here.

**How to Reproduce**

Select a quest where the name of a shop is asked. 
(I don't know if German locale is required for reproduction, but this is what I use)

**Expected Behavior**
I would either expect a blank prompt or a string like "Name:" shown.

**Versions affected**
v53.3

**Comment by wielandb** [comment]
The "de" refers to the language the name is in. So in this case, it's asking you to enter the german name of the object.

This serves as a reminder for parts of the world with multiple dominant languages. If you are in a part of the world where it would be expected that a shop has two different names, AFAIK you would see two different input boxes with language codes next to them.

That beeing said, it never occured to me, but theese language codes are indeed something non-programmer people might not know about. Maybe there could be translations to say "Deutsch" instead of "de", or maybe even flags (although I think that could get out of hand fast...)

**Comment by HolgerJeromin** [comment]
> maybe even flags

Please not:
https://www.flagsarenotlanguages.com/blog/

This is difficult for german (DE, AT, CH?) and spanish (spain or brasil?) and gets worse with arabic.

**Comment by hmartink** [comment]
Of course, "de" means German, but I was not aware that this meant to indicate the language. And not, flags are not correct either.

That this is a language choice is (was) not obvious to me. I haven't so far encountered a quest asking me names in different languages (and I travelled in several countries). Even in Greece, where several shops/restaurants repeated their name in Greece I only got one input name (and I faithfully typed down the Greek letters).

Then either the question should be explicit:
What is the shop name in German / What is the shop name in the local language

Or maybe below the entry bar, in small letters: 
Please enter the name in the local language
or similar.

**Comment by westnordost** [comment]
"de" is not written out because the language name would be too long, I'd say. There'd be too little space for the actual input field, at least on small phones (~4.5" display) on which the app should still work well. The full name of the language is shown, if available, when one taps on the  button. Because there is not any other language to add, the button is disabled.

Adding names in multiple languages is only offered for countries or regions in which there are either several official languages (e.g. Brussels, Trentino-Südtirol, Catalonia, Ireland, ...) or it is very common to write the name of streets on official signs in several languages even if one of them is not an official language - common in countries with non-latin scripts, such as Thailand, Greece or Korea.
The information about official languages and additional languages commonly seen on street signs are maintained at 
- https://github.com/streetcomplete/countrymetadata/blob/master/data/officialLanguages.yml
- https://github.com/streetcomplete/countrymetadata/blob/master/data/additionalStreetsignLanguages.yml
, respectively.

That in Greece, you didn't have the option to add another name sounds like a bug. But maybe it is another misunderstanding.

**Comment by arrival-spring** [comment]
A plus button 'appears' when you can enter a name in other languages as well.

i.e. that is hidden when the country/region has only one language, so would it also make sense to hide the language code at such times as well (especially as only `name` is tagged anyway, so the language of the name doesn't affect the tagging).

**Comment by westnordost** [comment]
IIRC, the language code is just disabled and not hidden to give a (slight?) hint in which language the place / street name should be entered.

**Comment by rhhsm** [comment]
For information, this is what it looks like when I, using Dutch as my default language, am asked to enter a name in Bulgarian and optionally in "International" (which adds the name transliterated from Cyrillic in `int_name=`) (Internationaal label only appears when tapping the blue plus icon, and it needs to be tapped again to enter the value)
![Screenshot_20230731-194347~2](https://github.com/streetcomplete/StreetComplete/assets/69100427/2ff9f2b3-b2fa-4b2e-97fc-751196349ecb)
I think SC does an amazing job handling the many languages that need to be handled when using SC internationally.

**Comment by hmartink** [comment]
Great, I will look out for this on my next travel. It was simply not clear to me, "de" looked like a name part, not a language indication. But I don't have a good solution for this misunderstanding, sorry.
