### ISSUE TITLE
Tagging drinking water source types

### ISSUE THREAD

**Issue by meskobalazs** [streetcomplete/StreetComplete#5171]
The [AddDrinkingWaterType](https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/drinking_water_type/AddDrinkingWaterType.kt) quest handles disused elements in a non-intuitive way. One can specify that the source is still not in use by selecting the last option in the list, but I take issue with this:

1. It's not obvious from the quest, that it is currently tagged as disused in the first place.
2. Looking at the question, it suggests that it asks the type of the source, not if it works at all. These two things are conflated here.

So I have two possible suggestions:

* Simply do not touch disused water sources, and optionally have another quest to ask if the disused source is still disused.

OR

* Have a clearer question. Currently it says `How is drinking water provided here?`, I would suggest something along these lines `Is drinking water available here? If so, what is its source?`.

I believe the first one is the better option, but the second is much more easier to do, and it is good enough, I think.

**Comment by westnordost** [comment]
@matkoniecz this is your quest.

Generally, I agree with your reasoning.

**Comment by matkoniecz** [comment]
Both "have another quest to ask if the disused source is still disused" and retitling to "Is drinking water available here? If so, what is its source?" seems fine to me.

Not sure which one would be better.

**Comment by westnordost** [comment]
I think it is better to not ask again for disused water sources. Once a water source is disused, I am guessing that it is not likely to be made available again (anytime soon), and if, probably in a renovated manner (= the type may have changed, too).

**Comment by mnalis** [comment]
To me it makes sense to asks for disused water sources if they have become working again.

 I see them (`disused:amenity=drinking_water`) being off and came back on from time to time (e.g. being unavailable due to vandalism, or road works e.g. https://www.openstreetmap.org/note/3451060)  and drinking water is very important tag  (think rural areas, not middle of big cities where you can just go to nearest cafe), and it is not very spammy as implemented.

To me better wording seems good enough, but if people prefer cloned quest just for disused water source, that is also an option.

So I'd recommend it kept being asked for (if it is indeed abandoned for good, it can be re-tagged as `abandoned:amenity=drinking_water` instead)

**Comment by matkoniecz** [comment]
> Once a water source is disused, I am guessing that it is not likely to be made available again (anytime soon)

Very large part of them for disabled during COVID, it was tagged in some cases and the are coming back.

Also, many vandalised or damaged are reappearing after some time

**Comment by bkil** [comment]
Many (novice) mappers are tagging taps closed for the winter as "disused" if it did not work at the moment of their survey, while in reality, they should use the operational_status and seasonal tags instead. It is valuable to resurvey such "disused" taps from time to time to fix such an error.

**Comment by mnalis** [comment]
> Many (novice) mappers are tagging taps closed for the winter as "disused" if it did not work at the moment of their survey,

@bkil True, that is because they (especially being novice mappers!) can only say **what they see at the moment** - if it doesn't work, it is _"disused"_ -- _nobody_ can _guarantee_ whether it will work in the future, and very very few have multi-year experience with that specific water source to estimate whether most probably reason for it not working is because it is `seasonal=yes`.

> while in reality, they should use the operational_status 

Well,  `operational_status=*` has its own set of [problems](https://wiki.openstreetmap.org/wiki/Key:operational_status#Problems), so I would advice against using it...

> and seasonal tags instead.

Yes, but see above, it is hard for average user to know if it is `seasonal`. 

Perhaps `Uh...` answer `It's working in specific season only` to tag it as `seasonal=yes` might be acceptable, but very few SC users would discover and use it in any case. 
For its part, StreetComplete [skips asking the quest for those water sources already mapped as seasonal](https://github.com/streetcomplete/StreetComplete/blob/v58.2/app/src/main/java/de/westnordost/streetcomplete/quests/drinking_water_type/AddDrinkingWaterType.kt#L19), to reduce such errors being introduced by SC users.

> It is valuable to resurvey such "disused" taps from time to time to fix such an error.

Yes, `disused:amenity=drinking_water` is [re-asked after 1 year](https://github.com/streetcomplete/StreetComplete/blob/v58.2/app/src/main/java/de/westnordost/streetcomplete/quests/drinking_water_type/AddDrinkingWaterType.kt#L17). Or doesn't it work for you?

**Comment by matkoniecz** [comment]
I though about making description something like "permanently closed" or "forever inactive" reducing confusion for people aware that these are temporary (but making new issue for that may be a good idea)

**Comment by bkil** [comment]
@mnalis operational_status does not pose any problem at all and has no other viable substitute. The link mentions that life cycle prefix should be used (that we also recommend), but it does not make sense in many cases. Water taps needing maintenance is one such example, but the list goes on. See a traffic calming that is half broken (missing). You shouldn't tag it as disused/was/abandoned/removed either.

**Comment by matkoniecz** [comment]
@bkil `operational_status` is a terrible idea (as [trolltag](https://wiki.openstreetmap.org/wiki/Trolltag)), but either way it is not a good place to discuss it (would be happy to discuss it on tagging mailing list or community forum, feel free to ping me if topic would exist)

**Comment by bkil** [comment]
@matkoniecz I have already asked you nicely multiple times to stop talking to me. If this behavior continues, the case will have to be escalated.
