### ISSUE TITLE
Building Type quest should remove construction tag

### ISSUE THREAD

**Issue by ssotoen** [streetcomplete/StreetComplete#5179]
**Use case**

Over the years I’ve come across a bunch of objects tagged as `building=yes` and `construction=*`. For these objects, Streetcomplete’s “building type” quest only updates the `building` tag and completely ignores the `construction` tag.

**Proposed Solution**

The building type quest should remove orphaned `construction=*` tags because construction has finished at that point. In addition, we could suggest the tag’s value in the form since that’s the most likely answer.

**Comment by matkoniecz** [comment]
Can you gave example of affected objects?

From looking at https://github.com/streetcomplete/StreetComplete/blob/c456a05d9f3c46452600d2da7cc38f4e3e811eed/app/src/main/java/de/westnordost/streetcomplete/quests/construction/MarkCompletedConstructionUtils.kt#L7 and https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/construction/MarkCompletedBuildingConstruction.kt#L36C21-L36C53 I am confused how it is supposed to happen.

Maybe old versions were imperfect.

**Comment by Helium314** [comment]
It's not about `MarkCompletedBuildingConstruction`, but about `AddBuildingType` for e.g. `building=yes` and `construction=residential`

**Comment by matkoniecz** [comment]
I kind of feel that

- StreetComplete is not making things worse here
- if replacing `building=yes` `construction=foobar` with `building=foobar` or deleting from `building=foobar construction=qwerty` construction tag makes sense then it should be done with a bot edit
   - I would not feel sure enough to make such bot edit, so I also would prefer SC to not edit things this way

> The quest already provides a “still under construction” answer. 

A bit hidden one

**Comment by ssotoen** [comment]
In that case I agree with your suggestion to trigger the construction quest on these objects.

**Comment by westnordost** [comment]
I agree with @matkoniecz . Trying to account for and/or fix invalid tagging is a slippery slope to go down.

Firstly, in terms of scope of this project. If this precedent catches on / is to be expected of StreetComplete, there is no limit to the complexity of invalid and semi-invalid taggings StreetComplete is expected to handle (and correct).

Second, (to acknowledge what he wrote already), it may have been tagged like that not for the reason we think it has been tagged that way. Such automatic interpretations of what invalid tags should have meant are always risky. Maybe not so much in this case(?), but in others, surely. Another reason not to get into that "business". Better leave that stuff to osmose et al, which just indicate the problems rather than also provide an automatic "fix" for them.
