### ISSUE TITLE
Check bus stops for existence when no route serves them

### ISSUE THREAD

**Issue by BalooUriza** [streetcomplete/StreetComplete#5186]
### General
Affected tag(s) to be modified/added: highway=bus_stop
Question asked: **Does this bus stop still exist?**

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/blob/master/QUEST_GUIDELINES.md)):
- [x] 🚧 To be added tag is established and has a useful purpose
To be removed actually. 
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by any pedestrian from the outside but a survey is necessary
- [x] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of map data (Worth the effort)

### Ideas for implementation

**Element selection:** 
Bus stops that ARE NOT a member of a bus route relation.

**Metadata needed:** 
Has not been recently checked.

**Proposed UI:**
A simple picker of Yes, No, or Can't Say.

Yes adds a check date. 
No deletes the bus stop.
Can't Say offers to create a note or hide.

**Comment by rhhsm** [comment]
What about areas where bus stops are mapped, but bus routes not (yet)?

**Comment by Helium314** [comment]
This may have difficulties in some areas where bus stops exist, but are not signed in any way (not sure where, but I think it came up in some discussion on this issue tracker).

And possibly there is also the bus stopping location that should be removed too if there is no bus stop.

> What about areas where bus stops are mapped, but bus routes not (yet)?

Then I would assume the user answers _yes_ to the question whether the bus stop exists.

**Comment by mnalis** [comment]
>>   What about areas where bus stops are mapped, but bus routes not (yet)?
>
>Then I would assume the user answers yes to the question whether the bus stop exists.

But how would that answer be **tagged**? @BalooUriza says _"Yes adds a check date"_, but element selection does not mention check date, so the quest would just pop up immediately (not only for that user and also all other users).

Perhaps it might work if **Element selection** was upgraded to instead be:

> Bus stops that ARE NOT a member of a bus route relation ***and the element is older than 3 years*** 

... or whatever value sound reasonable lifetime of an average bus stop (i.e. how often to re-check if bus stop still exists). That way answering _"yes"_ would skip that quest for few years (when it would be re-asked, unless someone added it to the relation in the meantime. But much better than asking the quest again _immediately_ after it was asked!)

Additional things to consider:
- does it **really happen that often** to be worth of quest (_"no spam"_)? Over here bus stops disappear only very rarely; and besides the capital and an odd city or two, many bust stop do not have relations mapped. So in most of the Croatia that would likely be _spammy_. 
  The only other use case for _"phantom bus stops"_  I can see is that if someone did botched very-low-quality import (without checking which bus stops are already manually mapped and if import data is actually valid and up-to-date); but then such import should probably be reverted instead, and done better (or just given up on, if it is of too low quality) instead of dispatching mappers on the ground to fix it.
- if disappearing bus stops are thing that happens often enough, and we must check for age anyway (see problem with _element selection_ at the top), then shouldn't we just **check all bust stops if they still exist** after few years (regardless if they are part of any relation or not)? e.g. Why would bus stop be more persistent on the ground based on the fact that someone had time to record it's route relation?  
- is the error rate low enough to be more useful then harmful (e.g. user **erroneously removes bus station** because it is not well marked / has no physical infrastructure / is not marked at very precise location ?)
- Might it actually be better to get rid of `Yes` answer altogether? So only allow removing the bus station if it does not exist, **or** leaving a note with picture and/or text detailing what bus lines that stop *is part of*, **so the relations could be created**  (creating relations and members is way too complex a task for StreetComplete alone, but if we accept the premise that bus routes should preferably always be recorded, than this is ideal time for on-the-ground mapper to record that information in a Note at least)

**Comment by rhhsm** [comment]
There must be statistics on which % of bus stops are part of a route relation in various parts of the world? I suspect that in the evolution of mapping an area, bus stops are mapped much earlier than bus routes. In an area where mapping has just begun, not even bus stops are mapped. As mapping advances, most bus stops added will not be part of a route relation for a long time, and here checking their existence would be very spammy and useless. As mapping approaches completion, most bus stops are likely to be part of a route relation, and here it makes sense to check their existence (or at least increase their existence checking frequency).

**Comment by mnalis** [comment]
> statistics on which % of bus stops are part of a route relation in various parts of the world

Overpass could be used probably (but it might fail for too big areas?); e.g. https://wiki.openstreetmap.org/wiki/Overpass_API/Overpass_API_by_Example#Find_all_bus_stops_which_are_not_included_in_a_relation

**Comment by westnordost** [comment]
Anyway, I am closing this as per @rhhsm's first comment as I do not see this can be solved. Removing only the platform but not the stop position would be an incomplete change/fix.

**Comment by BalooUriza** [comment]
> > > What about areas where bus stops are mapped, but bus routes not (yet)?
> > 
> > 
> > Then I would assume the user answers yes to the question whether the bus stop exists.
> 
> But how would that answer be **tagged**? @BalooUriza says _"Yes adds a check date"_, but element selection does not mention check date, so the quest would just pop up immediately (not only for that user but also all other users).
> 
> Perhaps it might work if **Element selection** was upgraded to instead be:
> 
> > Bus stops that ARE NOT a member of a bus route relation _**and the element is older than 3 years**_
> 
> ... or whatever value sound reasonable lifetime of an average bus stop (i.e. how often to re-check if bus stop still exists). That way answering _"yes"_ would skip that quest for few years (when it would be re-asked, unless someone added it to the relation in the meantime. But much better than asking the quest again _immediately_ after it was asked!)

I like that, though based on my experience watching various transit agencies, probably closer to 6 months would be a good lead out time.  Like no relation and hasn't been checked/changed in at least 6 months would be a good criteria.

> Additional things to consider:
> 
>     * does it **really happen that often** to be worth of quest (_"no spam"_)? Over here bus stops disappear only very rarely; and besides the capital and an odd city or two, many bust stop do not have relations mapped. So in most of the Croatia that would likely be _spammy_.

But, how many bus stops are not part of a route?
