### ISSUE TITLE
Edit opening hours of a shop

### ISSUE THREAD

**Issue by flovo** [streetcomplete/StreetComplete#5189]
When I select an existing shop in the shop overlay, I can change its type and name.
![Screenshot_20230814-002742_Street­Complete](https://github.com/streetcomplete/StreetComplete/assets/4864182/9333c2c5-66d2-442e-af3e-ac6295009e65)

It would be helpful to also be able to review and edit the opening hours. I'm not aware of any way to change the opening hours when the review quest is not active.

**Comment by Helium314** [comment]
When you set resurvey interval to ask more often, opening hours are asked every 6 months already. Does this place change opening hours more frequently?

**Comment by flovo** [comment]
No, but the frequency a shop changes its name or type is even less frequent and has this feature. 

The opening hours can change at any time within the 6 months. When I see

**Comment by westnordost** [comment]
Changing opening hours in StreetComplete is not possible in the shops overlay and also not planned. The only possibility to maintain opening hours in streetComplete is to wait for it to ask you about it. Which is one year by default or half a year if you change that setting.

Otherwise, you need to use another editor for this task, for example EveryDoor.

**Comment by HolgerJeromin** [comment]
Duplicate of #4516
