### ISSUE TITLE
Does this caravaning area have a ... ? 

### ISSUE THREAD

**Issue by petitminion** [streetcomplete/StreetComplete#5205]
The above quests would be to improve the quality of [caravan_site](https://wiki.openstreetmap.org/wiki/Tag:tourism%3Dcaravan_site)

- Does this caravan area have a [fee](https://wiki.openstreetmap.org/wiki/Key:fee)  ? 
- Does this caravan area have a [anitary_dump_station](https://wiki.openstreetmap.org/wiki/Key:sanitary_dump_station)
- Does this caravan area have a [water_point](https://wiki.openstreetmap.org/wiki/Key:water_point)
- Does this caravan area have a  [power_supply](https://wiki.openstreetmap.org/wiki/Key:power_supply)

**Comment by westnordost** [comment]
Hey @petitminion , sorry I have to close this one because you should use the quest suggestion template when making a quest suggestion, so use that instead: https://github.com/streetcomplete/StreetComplete/issues/new?assignees=&labels=&projects=&template=quest-suggestion.md

It exists because it links to the relevant quest suggestion guidelines which you should read before posting such a suggestion.
