### ISSUE TITLE
1st menu item (on map) "neuen Hinweis erstellen" don't find my camera app (not system app)

### ISSUE THREAD

**Issue by itsbrody** [streetcomplete/StreetComplete#5207]
I wanted to create a new note and for better documentation to take a photo of the surrounding, but touching that blue button  on bottom left of the dialog only gives the error message "Keine Kamera-App verfügbar".

_**Remark:**_ I've disabled the system camera app for some circumstances (by the mobile phone producer, he couldn't solve) and since then using the "Open Camera" App.

**How to Reproduce**
see above, if mobile is equipped same or has only a replacement of system APP ready for use.

**Expected Behavior**
using "my camera APP" or in general "having the possibility to equip notes with fotos (don't know, how some other APPs achieve this withoutout the system's camera APP)

**Versions affected**
Android 11
StreetComplete V53.3

**Comment by matkoniecz** [comment]
See https://github.com/streetcomplete/StreetComplete/issues/4281#issuecomment-1212218420

> The "Open Camera" app is apparently not registered as being able to take a picture. This is rather an issue of that app, StreetComplete just asks the Android system to take a picture (with the default camera app):

**Comment by itsbrody** [comment]
Might be the reason, but there are other APPs (e.g. Flora Incognita, Pilze App) who are able to work with that setup.

Am 21. August 2023 15:48:22 MESZ schrieb Mateusz Konieczny ***@***.***>:

**Comment by matkoniecz** [comment]
have you tried other open source camera app? can you go into Open Camera settings and check is there some button to make it default camera app? Or into phone settings? (not entirely sure which one will help, also it may depend on what your phone producer did with basic Android, some make silly modifications).

**Comment by itsbrody** [comment]
I installed that camera app on hint of the phone producer, because his provided app didn't work any more and he was not able or not willing to fix it; as a sinc then permanent workaround he provided "OpenCamera App", which is much more handy with more functions and thus I didn't go back anyway to the stock app. I'm neither mobile phone tester nor app tester, except I want to do this.

Further  there are apps who do their work with that camera app, which implies for me that there is nothing to do on my side - but I'll check in the camera app settings if there is any achievable regards "default camera app".

 
 

Gesendet: Montag, 21. August 2023 um 16:06 Uhr
Von: "Mateusz Konieczny" ***@***.***>
An: "streetcomplete/StreetComplete" ***@***.***>
Cc: "Wolfgang" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [streetcomplete/StreetComplete] 1st menu item (on map) "neuen Hinweis erstellen" don't find my camera app (not system app) (Issue #5207)


 

have you tried other open source camera app? can you go into Open Camera settings and check is there some button to make it default camera app? Or into phone settings? (not entirely sure which one will help, also it may depend on what your phone producer did with basic Android, some make silly modifications).

**Comment by pkoby** [comment]
I use Open Camera, and it opens in SC for notes without problems. I have a Moto X4, unmodded. I did remove all defaults from the stock camera app.

Some things you could try:

- check in settings for default apps and see if there's an option for camera.
- long press on open camera, view info, and see if there are defaults set for it. I cannot see what defaults there are for it, but it says there are some. You could try clearing defaults and then see if trying to open the camera from SC works. However, any other defaults would also be reset, so do this with caution.

**Comment by mnalis** [comment]
I use OpenCamera on StreetComplete on Android 10 (Huawei P30 Pro, stock EMUI 12.0.0) without problems too. 

I've had to make it default camera app first in _Android system settings_ under `Apps` / `Default apps` / `More defaults` / `Camera` (otherwise SC would keep opening system EMUI camera)

**Comment by itsbrody** [comment]
Thanks a lot to pkoby and Matija for their hints. I checked them, but didn't find any fitting settings anyway. Will setup an request on FP3's forum therefor.

21.08.2023 20:34:50 pkoby ***@***.***>:

**Comment by westnordost** [comment]
Very well

**Comment by itsbrody** [comment]
@westnordost , why closed - its not solved for that mobile.

**Comment by westnordost** [comment]
Because it has nothing to do with StreetComplete. Whatever the problem is, it is either a problem of OpenCamera or your particular smartphone (configuration). StreetComplete just uses an Android System API to query the default camera app. If the system API does not return anything, there is nothing we can do about that.

**Comment by itsbrody** [comment]
> Because it has nothing to do with StreetComplete. Whatever the problem is, it is either a problem of OpenCamera or your particular smartphone (configuration). StreetComplete just uses an Android System API to query the default camera app. If the system API does not return anything, there is nothing we can do about that.

Hmm, in general I would go on your arguments, when not other APPs I stated above by their names have the same working environement, but find that camera and use it.

So I'd would image its something inbetween SC and Operating System. One idea could be that SC uses an elder API call or misses a parameter or the like, which came first with a newer Android OS version (Android SDK). 

I think that could be checked here on this issue from developers.

**Comment by westnordost** [comment]
Flora Incognita does not use the system's camera app. It has its own camera.

**Comment by mnalis** [comment]
@itsbrody If you don't get solution on that FP3 (Fairphone 3?) forum, and  you still wish to track it down further, do note that it will be somewhat demanding / time consuming. 
For reference, this is what (I think) StreetComplete uses, see code around here: 
https://github.com/streetcomplete/StreetComplete/blob/796631aa007a63bdaa09fdf2fc23e157ed9d129c/app/src/main/java/de/westnordost/streetcomplete/quests/note_discussion/AttachPhotoFragment.kt#L55
 
You can find another opensource app which uses external camera and works for you, and see what mechanism it uses and how it differs (search the code for text "camera"), and then come back with that information / pointer to that code.

---

And/Or, you can go experimental way (which may also fix the problem in process):
- backup all the data you care about
- doublecheck that all the data you care about is correctly backed up
- factory reset your phone (that will irrecoverably DESTROY all data on the phone)
- install StreetComplete
- start StreetComplete and try to take a picture. Does it invoke system camera correctly?
- install OpenCamera
- reboot
- start StreetComplete and try to take a picture. Does it invoke camera correctly? Which one?
- disable / uninstall system camera (BTW how do you do that exactly?)
- reboot
- start StreetComplete and try to take a picture. Does it invoke camera correctly? Which one?
- if the problem is solved, then you can proceed to restore your other apps and data (and if not, answers to the questions above would help pinpoint the exact source of the problem)

**Comment by westnordost** [comment]
You linked the wrong code section (correct file, though). The relevant line(s) of code are basically

https://github.com/streetcomplete/StreetComplete/blob/796631aa007a63bdaa09fdf2fc23e157ed9d129c/app/src/main/java/de/westnordost/streetcomplete/quests/note_discussion/AttachPhotoFragment.kt#L36

https://github.com/streetcomplete/StreetComplete/blob/796631aa007a63bdaa09fdf2fc23e157ed9d129c/app/src/main/java/de/westnordost/streetcomplete/quests/note_discussion/AttachPhotoFragment.kt#L83-L87

i.e. simplified:
- launch the intent to take a picture (using the default camera app)
- show an error message about that a camera app cannot be found when this is the case

You see, the Android System API for that is... small. 

The solution to the problem is to make OpenCamera the default camera app. Where you find this setting in the settings depends on your Android version and manufacturer.

**Comment by itsbrody** [comment]
Thank @mnalis , @westnordost  for your further guidance. I understand that piece of code and your detailed instructions.
I can sum up that the "time and resource consuming way" will not be mine, but yest I stated on Fairphone Community forum for my FP3, if they have a solution, especially setting another camera APP es default as the system camera APP. A next and final step if that will not help, will be contacting the support directly around this, because they were the root cause.

When this all will fail, SC's notes from my side will need to live without pictures (It was now one time of may notes usages that I wanted to do so). Further SC documenting from my side will go on as usual.

**Comment by mnalis** [comment]
Understandable, @itsbrody. Hopefully they will produce a fix. 
Would you add here link to that post of yours on FP3 forum, so interested parties can follow the discussion (and maybe provide further information)?

**Comment by itsbrody** [comment]
Good idea - here it is: https://forum.fairphone.com/t/how-to-set-opencamera-app-as-default-camera-app/99094

**Comment by mnalis** [comment]
Unfortunately, on Android 11+ and newer, it is no longer possible to change default camera. So apps like StreetComplete that want to use non-system camera  (like e.g. OpenCamera)  would needs to support them manually. See https://github.com/streetcomplete/StreetComplete/discussions/6190#discussioncomment-12847500 for more details.

**Comment by itsbrody** [comment]
I find that a pretty shallow excuse, because there are enough APPs that can easily find this camera app (yes I use OpenCamera). Among them are- PeakView- Flora Incognita
Since I haven't configured anything for it in either APP, but it just works, there seem to be viable solutions. Since SC (actually) emphasises photos of the documented situation, SC should also support it (just as) easily as the APPs mentioned.
Translated with DeepL.com (free version)

**Comment by westnordost** [comment]
I didn't know that. I'd accept a PR that allows to use Open Camera when it is installed. Maybe there is a library for that already. It should be multiplatform-capable or at least not get in the way towards making the app multiplatform.

**Comment by mnalis** [comment]
> because there are enough APPs that can easily find this camera app (yes I use OpenCamera). Among them are- PeakView- Flora Incognita

@itsbrody and @AAnderl - are any of Android apps which successfully automatically find your non-system camera app (like OpenCamera) open source? (if they are also multiplatform, i.e. iOS+Android, that would be even greater!). I'm asking in order to try to implement such functionality in https://github.com/streetcomplete/StreetComplete/issues/6222

Thanks in advance for any pointers!

**Comment by itsbrody** [comment]
Thank you for your followup Matija and the valuable offer to adopt that functionallity.I checked both APPs I mentioned: They seem not to be OpenSource, but have contact data / a "living" website.
Peakview is maintained by:
CHIEH-YUN LU
***@***.***
新東街66巷5號 2樓 松山區 台北市, Taiwan 105

 
Website: https://www.peakviewer.com/Flora Incognita is maintained by:

Technische Universität Ilmenau
***@***.***
Max-Planck-Ring 14 98693 Ilmenau Germany
+49 170 5084726


Website: https://floraincognita.de/As the latter is maintened by an University it seems to be a research project.From this information I guess that they would maybe more helpful, but who knows....Message ID: ***@***.***>
