### ISSUE TITLE
Move quest selection to options

### ISSUE THREAD

**Issue by 501Ghost** [streetcomplete/StreetComplete#5242]
Since the overlay tab now has its own button on the screen, there's an empty spot in the options tab (the 3 horizontal stripes, idk what you call that internally). I think it would be nice to move the quest selection from the list of settings to there, to make it more accessible by saving a click.

**Comment by mnalis** [comment]
Do you mean `Profile selection` (which chooses which preset of quests to use)? That would make sense to me!

Or do you mean ***individual*** quest selection inside currently selected profile?

**Comment by 501Ghost** [comment]
I mean this: 

![SC_Screenshot_2023-09-11-17-06-20-33_8a0120479a21d3140f77758520f645bd](https://github.com/streetcomplete/StreetComplete/assets/61314579/97b0c7d3-8fef-4f1b-a2c5-ee072be770e1)

**Comment by mnalis** [comment]
Thanks for the picture, but that part was clear to me. 

What I am unsure is what you'd like to open when you click on that triangle in your picture? 

I.e. do you want it to open menu `A` or menu `B` in this screenshot:

![small_Screenshot_20230912_004935_de westnordost streetcomplete_ab](https://github.com/streetcomplete/StreetComplete/assets/156656/9afcab92-f4bf-4a4a-b1ef-10226032f7ef)

I think `A` makes a lot of sense (since you might often be switching between quest presets when you have several of them)  and `B` doesn't (because if you have multiple use cases, you should just create preset of each of them _once_ and then change presets later, and never again go select quests manually); but your opinion might differ.

**Comment by 501Ghost** [comment]
My personal preference would be B, because I frequently change the selection and priority of individual quests. For example, I turn on the "is this lit?" quest only for roads that I'm very sure of, skipping partially or indirectly lit roads. 
But I'm not opposed to having A in that spot. It would probably give me a good reason to start making my own presets.

**Comment by westnordost** [comment]
TBH, rather not. No strong reason, but on the other hand, there is also no strong reason to add any particular screen from the settings there (it's just one tap more): I don't like to have several ways in the UI to reach the same screen. (Also, whether A or B seems to be preferred by different people...)
