### ISSUE TITLE
Motorway links don't show in surface overlay

### ISSUE THREAD

**Issue by rhhsm** [streetcomplete/StreetComplete#5247]
**How to Reproduce**
Switch to surface overlay near a motorway junction. The motorway link ways are not displayed and cannot be selected for editing. See screenshot 
![Screenshot (13 sep](https://github.com/streetcomplete/StreetComplete/assets/69100427/665bd109-9ea3-4a73-b449-deb9daace367)
(exit 25 Montbonnot - Domène on A41 near Grenoble shown)

**Expected Behavior**
Motorway link ways show and can be edited like other highways

**Versions affected**
54.0

**Comment by Helium314** [comment]
This is strange, so you can edit motorways but not motorway links?
According to code (and what happens on my device) both motorways and motorway links should not be colored, but still selectable.

**Comment by arrival-spring** [comment]
This way (https://www.openstreetmap.org/way/27210910) is selectable and editable for me. I am also using v54.0

**Comment by qugebert** [comment]
I think the way is not painted on the overlay, because it has no surface but you can click on it and edit the surface.
And once surface is tagged, the way is painted to the overlay 

I think this is the expected behaviour


![surface](https://github.com/streetcomplete/StreetComplete/assets/44033795/13ad5fe7-02ab-426a-b6a6-c6851f1660eb)

**Comment by westnordost** [comment]
See @qugebert

**Comment by rhhsm** [comment]
I double-checked and found that they are indeed selectable and editable. I often find it hard to select a way in overlays (where they don't have big quest pins) but that's another matter.
I think the expected behaviour is that all highways that do not have surface tags are shown in red, including motorways and motorway links. See screenshot of junction A33/A330 south of Nancy 
![Screenshot (13 sep 2](https://github.com/streetcomplete/StreetComplete/assets/69100427/96daa813-674b-42df-9f0a-f0778758a54b)
If you switch to lighting overlay, all roads here show red because they don't have `lit` tags. All roads without `surface` tag should also show red here in the surface overlay but motorway and motorway link highways don't.

**Comment by FloEdelmann** [comment]
Related: https://github.com/streetcomplete/StreetComplete/issues/262

**Comment by matkoniecz** [comment]
>  I think the expected behaviour is that all highways that do not have surface tags are shown in red, including motorways and motorway links. See screenshot of junction A33/A330 south of Nancy

it is deliberate to not complain about missing surface data for motorway and motorway_link as adding this info there is only barely useful (these can be assumed to be well paved with asphalt or concrete)

**Comment by rhhsm** [comment]
Primary roads are also generally paved with asphalt or concrete, and so are secondary roads, etc. I think `surface` should be asked of any road. How well they are paved also varies: I've tagged motorways in Bulgaria with `smoothness=intermediary` and links with `smoothness=bad` (in iD). I haven't done much motorway surveying until recently so haven't noticed if `smoothness` is asked from motorways, but I think it should be because it can't be assumed to be always `smoothness=excellent`

**Comment by mnalis** [comment]
> Primary roads are also generally paved with asphalt or concrete, and so are secondary roads

Well, there is difference between "in most cases" and "virtually always". If you go on taginfo for [highway=motorway](https://taginfo.openstreetmap.org/tags/highway=motorway#combinations) and filter by surface, you'll find that there is only less `0.01%` surfaces which are **not** `asphalt|concrete|concrete_plates|paved` - few dozen worldwide. And most of those are things like `chipseal`, `metal`, `construction` etc. 

If you do the same for [highway=secondary](https://taginfo.openstreetmap.org/tags/highway=secondary#combinations), you'll find it is about `1.54%`, which is (especially when you take higher number of such way) more than 3 orders of magnitude more uses (at least 76k+ values for just that 4 most popular paved types).

---

That being said, I understand that it is confusing and unfortunate that such things are visually hidden from  user in overlay UI.

But I also understand the reasoning why it was done (i.e. we don't want to encourage people to add lots of data which is of very low usefulness and same or similar in > 99.99% cases; and marking those ways red _would_ encourage that).

**Comment by matkoniecz** [comment]
alternative is to:

- do not display surface for motorway* at all
- do not allow changing surface for them

**Comment by rhhsm** [comment]
My apologies for reacting with a delay: I've been exploring European motorways extensively these weeks (driving from Bulgaria to the Netherlands and back via France and Italy) and have just returned home.
I think there a few good reasons to encourage mapping of motorway and motorway link surfaces and show all highways with unknown surface as red in the surface overlay:

1. Just more than half of all motorways already have a surface tag, showing that mappers find this interesting enough to spend efforts on it.
2. Professional map users are interested in adding surface data, for instance this Maproulette challenge initiated by TomTom https://maproulette.org/browse/challenges/39297 I started on it and found that many tasks are about link roads including motorway links.
3. It would look weird if apps showing surface data such as GraphHopper and OsmAnd would show the surfaces of motorways as unknown, as these would be expected to be the best mapped roads in a country and be mapped in detail.
4. I understand that motorways are not shown in the sidewalks and cycle paths overlays because there are legal reasons why motorways are very unlikely to have them. There is no such reason for the surface overlay.
5. StreetComplete is sometimes seen as an app to be used by pedestrians, who don't have access to motorways. But StreetComplete is also used for mapping from a moving vehicle (car or public transport; several issues here mentioned this way of using SC).
6. I agree that there's little practical difference between asphalt and concrete surfaces for motorways, but I think in general `surface` is not a very interesting property of a road, especially when `smoothness` is also mapped. This is an argument for not mapping `surface` at all, but focus on `smoothness` (and quest the `smoothness` of motorways).

**Comment by mnalis** [comment]
Actually, after taking a more detailed look at the statistics, I'd agree with enabling coloring for `motorway` / `motorway_link` too.

> it is deliberate to not complain about missing surface data for motorway and motorway_link as adding this info there is only barely useful (these can be assumed to be well paved with asphalt or concrete)

I agree data consumers could assume that, but that would require special case implementation in any data consumer. It would also at least _sometimes_ guess wrong, which would make making such assumptions a bad idea (whole point of such features like OsmAnd's painting of road surfaces is to paint "known state" against "unknown states").

Also, [more than 50%](https://taginfo.openstreetmap.org/tags/highway=motorway#combinations) of `highway=motorway` **already** has `surface=*` tagged, [as does more than 41%](https://taginfo.openstreetmap.org/tags/highway=motorway_link#combinations) of `highway=motorway_link`. So obviously **many mappers think it is information worth adding**, and since so much of it is _already_ added, I do not see benefits in intentionally trying to prevent people from finishing adding surface information (as I would have, if for example only `~1%` of `surface` was tagged on motorways/motorway_links).

And since this is an Overlay and not a Quest, and thus _"spam effect"_ is much less of a problem (if at all), I do think `highway=motorway` and `highway=motorway_link` without `surface` should also be colored red, for the benefit of (quite many of) those who would like to add that information where missing.

**Comment by westnordost** [comment]
To be honest, I do not have a strong opinion about it. And if than 50% of motorways are already tagged, that's fine then.

I changed it now.
