### ISSUE TITLE
Add option to input multiple values to level number quest

### ISSUE THREAD

**Issue by draeklae** [streetcomplete/StreetComplete#5255]
**Use case**
Some large stores (e.g., department stores) in shopping malls, etc. span multiple levels. Right now the app only supports inputting a single level.

**Proposed Solution**
Allow input such as specified [here](https://wiki.openstreetmap.org/wiki/Key:level#Multiple_values).

**Comment by peternewman** [comment]
Yeah I've had this issue too, also with a department store, but just hadn't got round to raising an issue about it yet.

**Comment by westnordost** [comment]
This is rare enough that I consider this as a case where the user should leave a note instead.

The reason is that if the shop actually spans multiple stories, then it is possible that the geometry actually needs to be corrected. 
Many stores that span multiple levels have a different outline on these stories. What exactly to do with this has as far as I know not really been determined yet. I've seen someone create a multipolygon for this, but rest assured no single software (be it validator or indoor-renderer) interpreted this correctly. So what I have been doing is to define the shop just for one of these levels and leave the other room empty (especially if it only has an entrance on one level).

Now, when the shop is mapped just as a node, it would in theory be easier, but then this still might need cleanup because maybe the shop has been mapped twice? (once for each level)

**Comment by peternewman** [comment]
In which case would it be worth adding an other answer directing people to add a note so that they know they aren't just missing some special input syntax (e.g. with house numbers)?

**Comment by westnordost** [comment]
I don't think so. The other answer exists in the housenumber quest to advise users of the validity of writing something like "1-7". For the level quest, it would be the other way around. Generally, the user already got the instruction to leave a note when for one reason or another, he is not able to answer the question correctly using the form supplied.
