### ISSUE TITLE
Enable all layers / see what's not completed on hidden layers

### ISSUE THREAD

**Issue by thany** [streetcomplete/StreetComplete#5261]
**Use case**
Say I want to map all quests in a smallish area. Maybe I'm visiting for just one or two days. I would currently have to remember to switch layers around to see if I haven't missed anything.

**Proposed Solution**
Add an option to enable all layers, or to somehow point out things on hidden layers that still need to be mapped.

Honestly I prefer the old way, where there weren't any layers to be had, but every quest was just a pin on the map that I can tap to fill out. I guess the majority user base has overruled me regarding this preference.

**Comment by rhhsm** [comment]
"The old way" still exists, it's the top of the list choice on the overlay selection list ("Geen" in Dutch, above "Straatverlichting"). Doesn't that work for you?

**Comment by westnordost** [comment]
Additionally what has been said by @rhhsm (you can just enable all the quests in the settings):

In general, I think StreetComplete is not the right choice to "map all the things, at once": It is not very efficient with this app. And I dare say, not very efficient in general. I think EveryDoor is designed to be more like that, at least for POIs. Because, if you wanted to add all the things at once, you could just use Vespucci - but as it turns out, for being on the go, it's all a bit too involved, so less things get done in that app.

StreetComplete rather encourages convenient additions on the side, here and there. This goal directly conflicts with wanting to add all the information at once, at least with overlays, which specifically show only *one aspect* at a time. As I wrote, an overlay that showed all the overlays at once... well, that would be Vespucci or any other editor that just shows and lets you edit everything.

**Comment by thany** [comment]
Okay, but I really don't think it's all that outlandish to work on, say, lighting and path surfaces at the same time. I guess what I'm trying to say is the layer are "too distinct" from one another. I really think it's not that weird to have the option to enable several layers, or maybe just 2 at most, at the same time.

And let me be clear: I'm not out to map EVERYTHING, just to map everything StreetComplete offers to map, within my profile of enabled quests.

Btw, I don't get the reference to Vespucci; it's all the way on the far end of the spectrum. You can't even compare it StreetComplete, imo. It's like comparing the SATA specification with trying to cat a file in the terminal.

**Comment by westnordost** [comment]
Right, I absolutely get it. I catch myself switching between overlays often when there are no quests nearby, too. But, showing several overlays ad once... I can really not imagine how that could work. The colors for the overlays are completely different, so one will not end up with an understandable coloring. Also, it's one more tap to select which overlay one actually wants to edit after selecting an element.

A really nice solution would be an overlay that combines several overlays without making the interface (too) complex. But that's a challenge. We do not even have a desktop editor yet that displays and lets you edit for example the street layout (lanes / width, bus lanes, cycleway, sidewalk, ....more) in a nice UI yet. For mobile, it is even more difficult.
The closest thing I have seen that comes near (but is not an editor) is A/B street, as you have somewhat of a WYSIWYG interface there.

In general, I think for visualization on the map of such combined overlays, more advanced (WYSIWYG) visualizations are necessary first which are neither available with the tangram-es library nor (as far as I know) maplibre.

... I guess, when there were no limitations on what could be rendered on the map, there'd be many more opportunities to make the interface and display even better. For example something like a building overlay could display building type via color, height+roof height+roof shape directly on the map itself plus their numerical values labelled on the site when selected. When editing, the map just zooms in to and focuses that particular building while the user gets some slim controls to edit these values in-line.

But, well, that's all rather unicorny.

**Comment by mnalis** [comment]
Yeah, I too unfortunately do not see an easy way to do it... 

- For highlighting part, it would need to be severely reduced in function to be able to support multiple-overlays-at-once. I.e. only `red` for some-data-is-missing and `green` for all-data-is-present might be used. Or perhaps third shade for all-data-is-missing.  Anything more complex that (like we currently support different colors for asphalt vs. unpaved etc) would result in total chaos (for example, use OsmAnd and try to set it to display at the same time road type, surface, smoothness, lit, and cycleway + hiking routes -- you would need many months of study just to be able to understand what the rendering means!)

  [SCEE](https://wiki.openstreetmap.org/wiki/SCEE) fork of StreetComplete kind-of supports that part with it's custom overlays, e.g.

  ![small_Screenshot_20230926_201429_de westnordost streetcomplete expert](https://github.com/streetcomplete/StreetComplete/assets/156656/545f20ce-082f-44f0-84ac-d2059c383a1e) ![small_Screenshot_20230926_201422_de westnordost streetcomplete expert](https://github.com/streetcomplete/StreetComplete/assets/156656/7607a471-cd1c-448b-af50-6b1bcb60fd8b)

- much more complex would UI for what to show for the quest answer. SCEE _"sidesteps"_ that issue by only allowing raw tags editor for custom overlays (i.e. `SHOW / EDIT TAGS` button above), but that is obviously not very user friendly (even less so then Vespucci UI). 
  Current way of overlays (nice pictures etc.) would most probably have to go away. Something like [EveryDoor](https://wiki.openstreetmap.org/wiki/Every_Door) text-only user interface (like for POIs) might be possible as middle ground for ease of use, but that is still noticeably less user-friendly than StreetComplete, especially for beginners:

  ![small_Screenshot_20230926_204111_info zverev ilya every_door](https://github.com/streetcomplete/StreetComplete/assets/156656/a4c8d557-5928-4fca-9c42-240b6d15f5b6)

  But if that would be the way to go, I'd probably rather have EveryDoor support ways too (and not just POIs), instead of StreetComplete Overlays emulating EveryDoor.

But if someone sees how such multiple-overlays-at-once UI could be accomplished (with less effort then writing new app from scratch) and would make detailed explanation / mockup screenshots of how it would look like, they could open a [GitHub discussion](https://github.com/streetcomplete/StreetComplete/discussions) about that; I would certainly be interested in participating.

But as it is, I can only see perhaps some very specific very related overlays being extended / merged (e.g. `surface` + `smoothness`); and even that with lot of effort, but nothing general.

**Comment by thany** [comment]
Afore we start designing complex UI, let me propose a simple alternative: opt out of the layer functionality.

I understand a LOT of work went into developing this, and I don't mean any disrespect. It's just not for me, for my style of mapping. I would much rather be slightly overwhelmed with quests, then run the risk of missing a huge number of them because they are obscured away (to me) on layers that are not currently visible.

I understand that there's a valid use case for layers, like "Today I'm going to map all lighting-related quests" or "Today I'm going to map only surface types" or what have you. But as said before, that's not always a luxury one can afford to work with. If you're in a cool area just for a bit, cool enough that you feel passionate about having it mapped & tagged properly on OSM, wouldn't you rather be able to be presented all the things in a single view?

I'd be more than happy if this wasn't the default (and it isn't), but a way to see everything that's on layers just like normal quests pointers (like from before layers existed) would be perfectly good for me. I was happy with the app back then, and I imagine many other people were, too. Not everyone, but surely more than a few.

**Comment by matkoniecz** [comment]
>  opt out of the layer functionality.

you can do it (almost?) entirely by enabling quests disabled by default

for example if you want to keep seeing building quest, you can reenable it

**Comment by mnalis** [comment]
> I'd be more than happy if this wasn't the default (and it isn't), but a way to see everything that's on layers just like normal quests pointers (like from before layers existed) would be perfectly good for me. I was happy with the app back then, and I imagine many other people were, too. Not everyone, but surely more than a few.

I read that  you prefer Quest-based StreetComplete to Overlay-based StreetComplete - I do too! 
And like you @thany , I also absolutely do not like the idea of `Quests` being **permanently removed** in favor of `Overlays` (see e.g. https://github.com/streetcomplete/StreetComplete/issues/5486#issuecomment-1950516052) in the future.

> (edit: reason I'm living up this issue again, is because I see more layers have got added, and quests pointers get disabled because of them - and I would greatly appreciate if this issue could be reopened, for it is not actually resolved)

But I am not sure I understand you here:
- you seem to be under impression that `Quests` are already being **removed** in favor of `Overlays`. I might be mistaken, but I do not think that this is happening. `Quests` do become **disabled-by-default**, but you can still re-enable them yourself manually in the `Settings` / `Quest selection and display order`. Or have some `Quests` been completely/permanently removed already, so you cannot re-enable them? Or do you just not know how to re-enable them? Or is something else a problem?
- I've understand this issue to be about special type of `Overlay` which could display multiple `Overlays` (if that is what you mean by their original name `Layers`?) at the same time.  But looking at your new posts and rereading old ones, **perhaps the issue of what you want has been completely misunderstood**? This post of yours seems to imply that there were things you could do in the past with older versions of StreetComplete, but which you no longer can do with newer versions? If I understood that correctly, could you give concrete example of such a things? That would help me better understand (English is not my native language).  Or are you suggesting some new enhancement that StreetComplete never had, but you wish it would?

**Comment by westnordost** [comment]
Okay, fine.

**Comment by thany** [comment]
> But I am not sure I understand you here:
> 
>     * you seem to be under impression that `Quests` are already being **removed** in favor of `Overlays`. I might be mistaken, but I do not think that this is happening. `Quests` do become **disabled-by-default**, but you can still re-enable them yourself manually in the `Settings` / `Quest selection and display order`. Or have some `Quests` been completely/permanently removed already, so you cannot re-enable them? Or do you just not know how to re-enable them? Or is something else a problem?

Indeed, I am under this impression. Is it not correct? It's hard to tell when quests are being removed, as it doesn't usually stand out. Especially after not having used the app for a while. However, I feel the app should respect custom profiles, and modifications to the default profile, by not retroactively disabling quests in existing installs, but this does seem to be happening. I could be mistaken. 
 
>     * I've understand this issue to be about special type of `Overlay` which could display multiple `Overlays` (if that is what you mean by their original name `Layers`?) at the same time.  But looking at your new posts and rereading old ones, **perhaps the issue of what you want has been completely misunderstood**? This post of yours seems to imply that there were things you could do in the past with older versions of StreetComplete, but which you no longer can do with newer versions? If I understood that correctly, could you give concrete example of such a things? That would help me better understand (English is not my native language).  Or are you suggesting some new enhancement that StreetComplete never had, but you wish it would?

The goal is to see all the things that can be done in a given area. Whatever the means is to get to that goal, is up for grabs. Whether it be showing all quests as pointers on map, showing a layer that combines all other layers, or showing stuff from currently inactive layers somehow. I'm just letting you guys know what my usecase is, and what my personal preference would be to fulfill that usecase. Maybe the title of this issue prematurely contains a suggested solution, which I now realise was wrong of me to do.

**Comment by Helium314** [comment]
> Indeed, I am under this impression. Is it not correct?

Which quest do you think has been removed? All overlay-related quests still exist.

> Especially after not having used the app for a while

I recommend checking the changelog, e.g. 57.0 mentions that crossing quest has been split (implying old quest has been removed)

>  I feel the app should respect custom profiles

The app can only know that you _want_ a quest enabled/disabled when you actively enable/disable it (then changing the default already has no effect as far as I know).
You can use the _disable all quests_ option and then enable the ones you're interested in to ensure everything is set manually.

> The goal is to see all the things that can be done in a given area. Whatever the means is to get to that goal, is up for grabs.

This is simply impossible. Showing all overlays will clash for usually obvious reasons, and even if it worked the result would be too confusing for the target audience of SC.

**Comment by mnalis** [comment]
>>you seem to be under impression that Quests are already being removed in favor of Overlays

> Indeed, I am under this impression. Is it not correct?

As far as I know, it is indeed not correct. Quest just get disabled in default profile, and you can re-enable them yourself in `Settings` / `Quest selection and display order ` (or use non-default, i.e. user custom profiles, which should retain your preferences over upgrades[^1]).

> However, I feel the app should respect custom profiles,

I feel the same! But unless I am wrong, SC **_does_ already respect custom** (i.e. non-Default) **profiles** (i.e. the ones that you created via `Settings` / `Manage presets` / `+` or `Duplicate`).

> and modifications to the default profile,

hmmm, well, I think modifications `Default` profile will change as `Default` changes. That is the whole meaning / special casing of having `Default` profile, yes? 
So, if you prefer your profile not to get changes that StreetComplete _"recommends"_ by default, you should create and select your own profile named e.g. `My Profile` and make changes to it instead instead of using `Default` profile.

> The goal is to see all the things that can be done in a given area. Whatever the means is to get to that goal, is up for grabs. Whether it be showing all quests as pointers on map

Thanks @thany, it is much clearer now! What you seem to prefer is using only simpler `Quests` (which were the only option in older StreetComplete releases) and ignoring newer `Overlays` (which is newer _additional_ [**not** replacement!] and more advanced/complex way of editing the map). 

Many users do (myself included). There is no blockage for you continuing to use only `Quests`. Have fun!

> Maybe the title of this issue prematurely contains a suggested solution, which I now realise was wrong of me to do.

Thanks for clarification, and no worries! :heart: There is nothing wrong in suggesting possible solutions (although, of course, such proposed solutions are sometimes unfeasible for various reasons, as it happened to be the case here). 

It was just confusing to some people as its original wording seemed to imply that you have considered _and rejected_ just using `Quests` for some reason (like maybe them not being advanced enough or something). I'm glad that it was cleared out!


[^1]: except in rare complex situations. If e.g. some quest is replaced by two new quests (which replicate and improve on old quest functionality), that actually means that the old quest will be removed and two new quests  got created. In such case obviously old quest will be gone from custom profiles too (as it does not exist anymore!), but two new ones would need user interaction to decide whether the user wants some of them or not.

**Comment by thany** [comment]
So in short, the `Default` profile should be considered 'volatile' from update to update, any only be used as the recommended or initial set of quests. Got it 👍🏻

It does make me wonder how an update deals with modifications made to the `Default` profile by the user. It doesn't seem to just overwrite the whole thing. But I could be imagining this, since I hadn't used the app for a few months until a few days ago.
