### ISSUE TITLE
Other local ways are hidden while split

### ISSUE THREAD

**Issue by HolgerJeromin** [streetcomplete/StreetComplete#5296]
**How to Reproduce**

The problem is there with quests and overlay. But easy to reproduce and very visible with overlays:

* Have a lot of new ways (which are NOT in jawg tiles!).
* Show lit overlay
* select a way (all local osm ways are visible)
* Try to split a way -> local data is hidden, only jawg tiles are shown -> split context (way crossings) is completely invisible (or outdated)

Try this one (till jawg is updated)
https://www.openstreetmap.org/way/1212207388
Edit: jawg was updated with this ways, but not in my sc cache.

**Expected Behavior**

The local ways should be shown instead of jawg ways. The ways could be moved compared to the tiles, too!

**Versions affected**

Android 13, sc v54.1

**Comment by HolgerJeromin** [comment]
![Screenshot_20231009-000806](https://github.com/streetcomplete/StreetComplete/assets/2410353/43a8459c-d9d3-43ae-8509-d513f36b65da)
![Screenshot_20231009-000823](https://github.com/streetcomplete/StreetComplete/assets/2410353/36015abc-d5c2-4905-9e46-3acd27f0e8dc)

**Comment by westnordost** [comment]
It's not a bug, if at all, a missing feature.

It also amounts to, in my opinion, at most an inconvenience that should happen quite rarely, as a StreetComplete mapper needs to visit a place just after it was mapped with another editor. (Probably by the same mapper.)

Thinking what could be done about it, first of all, vector data could be more current. Now, this is out of our control, but I still got my hopes up about that there will be an official vector tile server by the OSMF for use by the the community one day and that this one will have very short update intervals. (I followed some threads in the forum and I remember @ZeLonewolf presenting a setup with very frequent updates)

Finally, as we should switch from tangram-es to MapLibre sooner or later anyway, I would not like to build even more stuff about map rendering around tangram-es, as it will only make migration more effortful.

Anyway, the way it could work is to use the `StyleableOverlayMapComponent` (the component that shows the overlays) to render all the roads and ways on top of the background map but without highlighting while the split-way form is open. This would require to make the mentioned component... not coupled to overlays anymore. 
But as I wrote, I do not think this is worth the extra complexity and of course time investment. If you think otherwise, you are free to look into it and in the unlikely case that in the end it turns out it would just add a few lines of code, I'd very likely also merge it.

**Comment by HolgerJeromin** [comment]
Ok. These are fair points.

But jawg got updates, but they were not shown. Perhaps sc could update more often. I have no idea how this is decided.
Reducing the size of the map cache seems not the parameter to tune as a user (AFAIU this is more about coverage).

**Comment by mnalis** [comment]
> (I followed some threads in the forum and I remember @ZeLonewolf presenting a setup with very frequent updates)

Maybe https://community.openstreetmap.org/t/minutely-updated-vector-tiles/104197 ?

> But jawg got updates, but they were not shown. Perhaps sc could update more often

AFAIK, one workaround is `Settings` / `Delete cache` (followed by closing / swiping away the app and restarting it) which should force StreetComplete to re-download stuff (both tiles from jawg, and quests from OSM API)

**Comment by HolgerJeromin** [comment]
The point is:
Begin of holiday, add all footways in the hotel via vespucci. :)
I do not know when the jawg data is now updated and dont want to clear data every day just to check.

I am even not sure if "delete cache" clears jawg data, too.

**Comment by westnordost** [comment]
Yes, it deletes jawg data, too.
