### ISSUE TITLE
Allow existing photos to be attached to a note

### ISSUE THREAD

**Issue by davidgeary** [streetcomplete/StreetComplete#5302]
**Use case**
Currently, when you add a note, you are encouraged to include a photo to make the note more useful.  I came across a building that I knew was missing from the map, but I wasn't in a position to add via the app at that time.  So I took a photo of it so I could add a note with the photo when I had time.  But when I created the note later, the option to add a photo only allowed me to open the camera so a *new* photo could be taken.  There was no way to attach an existing photo.

**Proposed Solution**
When you click the 'Add Photo' button, it would be useful if there were options both for taking a new photo and also selecting an existing one.  This would have allowed me to attach the photo I'd taken earlier.

**Comment by matkoniecz** [comment]
See #3476, https://github.com/streetcomplete/StreetComplete/issues/1567, https://github.com/streetcomplete/StreetComplete/issues/1730, https://github.com/streetcomplete/StreetComplete/issues/2813, https://github.com/streetcomplete/StreetComplete/issues/3014.

See also https://wiki.openstreetmap.org/wiki/StreetComplete/FAQ#Can_I_choose_photos_from_the_gallery_for_uploading_to_notes.2C_instead_of_using_camera.3F

Yes, this limitations blocks some legitimate uses but exists to reduce need for reviewing of media uploaded to StreetComplete servers.


See also 

* https://wiki.openstreetmap.org/wiki/Category:Media_without_a_proper_attribution
* https://wiki.openstreetmap.org/wiki/Category:Media_without_a_license
* https://wiki.openstreetmap.org/w/index.php?title=Special:UncategorizedFiles&limit=500&offset=3000
 
Just OSM Wiki has thousands of images waiting for content review/replacement/deletion. With things improving very slowly (at current rate it will take at least decades to process just already known problems).

Due to combination of effects this kind of review is something that almost noone wants to do and is necessary to avoid procedural/legal risks related to hosting files.

Note that this image server exists after framapic was shut down due to abuse (see #1161) and one of their recommended replacement (https://wtf.roflcopter.fr/maintenance.html ) is also already shut down for the same reason.
