### ISSUE TITLE
AddSummitCross and separately mapped crosses

### ISSUE THREAD

**Issue by Helium314** [streetcomplete/StreetComplete#5311]
I answered _AddSummitCross_ with yes  on a peak where the summit cross is mapped separately and located a few meters away from the peak.
A user [commented](https://www.openstreetmap.org/changeset/140139216) that tagging `summit:cross=yes` is not correct in that case.

The [wiki page](https://wiki.openstreetmap.org/wiki/Tag:summit:cross%3Dyes) contains very little information, and I guess `summit:cross=yes` could also be interpreted similar to `bin=yes` at a bus stop, i.e. the feature may or may not be mapped separately.

Anyway, maybe the quest should not be asked if there is a `man_made=cross` nearby?

**Comment by Luzandro** [comment]
It's poorly documented, but I guess the different levels of abstraction aren't necessarily wrong ("does this summit have a summit cross?" vs. "the actual summit cross object"). Anyway, it's quite common in the data: https://overpass-turbo.eu/s/1BZT

Frequently also on the same node (where it's questionable if for example the name applies to the cross): https://overpass-turbo.eu/s/1BZU

**Comment by westnordost** [comment]
@Luzandro could you document your findings in the wiki?

**Comment by Luzandro** [comment]
https://community.openstreetmap.org/t/summit-cross-yes-and-separately-mapped-crosses/105091

**Comment by westnordost** [comment]
I actually meant documenting your findings when you looked at the state via overpass: Since it hasn't been documented in the wiki before, we now have a de-facto situation how the tag is used and I think it is worth documenting that. Posting in the forum will get you mostly opinions how things _should_ be. Either way, I do not think there is a strong reason why it should be tagged one way ("duplicate, bus stop bin-like") or the other ("no summit cross on summit when mapped nearby") - but, we'll see.

**Comment by Luzandro** [comment]
yeah, well it would be useful to be able to write a better documentation than just, "no one knows exactly what it's for, just put both tags on the peak"

**Comment by matkoniecz** [comment]
note that there could be cases where summit cross is not exactly on summit but offset a bit

**Comment by westnordost** [comment]
I see the discussion more or less has been concluded and the wiki has been updated. Due to the outcome, I will close this issue.
