### ISSUE TITLE
New quest: Can bicycles be transported in this elevator? (`bicycle=*` on `highway=elevator`)

### ISSUE THREAD

**Issue by mcliquid** [streetcomplete/StreetComplete#5315]
### General
Affected tag(s) to be modified/added: [bicycle](https://wiki.openstreetmap.org/wiki/Key:bicycle)
Question asked: **Can bicycles be transported in this elevator?**

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/blob/master/QUEST_GUIDELINES.md)):
- [x] 🚧 To be added tag is established and has a useful purpose
The usage of `bicycle` on `highway=elevator` is already documented in the [wiki](https://wiki.openstreetmap.org/wiki/Tag:highway%3Delevator).
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
One can answer "Yes" (`bicycle=yes`) or "No" (`bicycle=no`) - both Values are documented.
- [x] 🐿️ Easily answerable by any pedestrian from the outside but a survey is necessary
No more difficult than the toilet or wheelchair quest.
- [x] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
If the filter logic is well tuned, most of the obvious "no" responses should disappear.
- [x] 🕓 Applies to a reasonable number of map data (Worth the effort)
In Germany, 4502 objects are eligible, of which 791 already have information about bicycle transport. This means that ~83 % of all elevators lack this information.
3712 

### Ideas for implementation

**Element selection:** 
OverpassTurbo for Germany: https://overpass-turbo.eu/s/1C0i

```
nodes, ways with
highway = elevator
and access !~ private|no
and !bicycle

// LAZY AROUND 500m FILTER
nodes, ways with
railway ~ station|halt
or aerialway ~ station
and access !~ private|no
```

In ski resorts this information is also relevant, because in summer most but not all ski lifts (gondola/cable cars) carry bicycles.

**Proposed UI:**
Simple "Yes/No" question (`YesNoQuestForm`), comparable to `WheelchairAccess` Quest.

### Potential circumstances

- It must be assumed that the "around" approach also selects nearby elevators that do not belong to the station but are located in a nearby private house. For this it would be helpful to assign an `access=private` to these elevators via "More answers".
- Unsure if `access=customers` should be excluded. Basically, passengers are also customers.
- Unsure if bus stops should be included. Presumably most (rural) do not have elevators.

I couldn't find a quest with an Around filter in a hurry, but if that feature already exists, I might take it up.

**Comment by matkoniecz** [comment]
note that for elevators in Poland this is typically not really clear at all, is never signed from what I have seen and main limitation in practice is whether bicycle will fir (possibly upright)

> No more difficult than the toilet or wheelchair quest.

Not really, checking for wheelchair ramp/platform/elevator is much easier.

**Comment by mnalis** [comment]
As in Poland, it would by very rare in Croatia to see it signed whether it is legal / acceptable to take bicycle in the lift in majority of the cases, so there is big [Verifiability](https://wiki.openstreetmap.org/wiki/Verifiability) issue there. 
Thus, the quest (as proposed) would likely fail _"🐿️ Easily answerable by any pedestrian"_ in Croatia for common SC mapper (unless the different tag is to be used, see below).

I see you say:

> One can answer "Yes" (bicycle=yes) or "No" (bicycle=no) - both Values are documented.

and

> In my research I did not find a photo where it is forbidden to carry bicycles in the elevator, so instead of "Is it legally allowed to carry bicycles in this elevator?" I chose "Can bicycles be transported in this elevator?".
Alternatively, it can be "Is it possible to transport a bicycle in this elevator?"

That sounds useful, but that is completely different question, and one that explicitly is **not** to be answered with [bicycle=*](https://wiki.openstreetmap.org/wiki/Key:bicycle)  tag  (which is, as all other [access](https://wiki.openstreetmap.org/wiki/Key:access) tags, explicitly about _"**Legal** restriction for cyclists"_). 

So if one wanted to tag whether bicycle _fits physically_ (regardless of whether it is _legally allowed_), they would have to find and use some other tag for that purpose. There have been few uses of (still undocumented) [bicycle:physical=*](https://taginfo.openstreetmap.org/keys/bicycle:physical) , so perhaps something like that is an option, or one might choose to use more versatile and much more verifiable [width=*](https://wiki.openstreetmap.org/wiki/Key:width), [length=*](https://wiki.openstreetmap.org/wiki/Key:length) and [height=*](https://wiki.openstreetmap.org/wiki/Key:height) (which also happen to be much more popular; and which I would recommend too -- e.g. just because your 26" MTB might fit in some elevator, does not mean my cargo bike will fit too). 

----

That being said, while some people (including myself) might be fine with adding `bicycle=no` on places where it is physically impossible to use bicycle (as no human law can ever trump physical laws,  whether something which is impossible is legally allowed or not is a moot point, as it would not make the slightest difference for any data consumers), there are many people who would object there too, just on the basis of principle of things.

But absolutely huge majority (definitely including me) would vehemently disagree with idea of adding `bicycle=yes` on places where bicycle **fits just fine physically**, but it is **legally actually not allowed** (even if there is only an infinitesimally small chance that you might actually get fined in practice).

**Comment by matkoniecz** [comment]
Also, question "is bicycle fitting into this elevator" is not easy to answer and obvious - even for cyclists!

For start, what about cases when bicycle fits but only in upright position?

**Comment by westnordost** [comment]
> // LAZY AROUND 500m FILTER

Actually, I this will not work in this app. Data is downloaded in small tiles, what's 500m in any direction of a tile is unknown. 

So... it will only work partially: A quest will be created if there is a train stop within the downloaded area and max 500m away from the elevator, but if the train stop happens to not be in the downloaded area even though it may be very close by, no quest will be created.

**Comment by westnordost** [comment]
Also, to solve this quest, you probably would need to have a bicycle (of standard size) with you, no? Sounds like a huge requirement, few people use StreetComplete while pushing a bike.

**Comment by Helium314** [comment]
To be honest, sometimes with narrow doors at store entrances it would be quite useful.

**Comment by matkoniecz** [comment]
> Do you need a wheelchair to answer wheelchair quests?

Sometimes yes, that is why I keep it disabled most of the time.

But many cases are more clear-cut due to either steps or constructions mandated by legal standards of wheelchair access - when it is built then it is typically clearly accessible.

**Comment by mnalis** [comment]
>  According to this argument a modern elevator, which is designed for more than 8 people, is also typically designed for the transport of a bicycle.

Perhaps better quest might be then _**"How many people fit in this elevator?"**_ 

At least in Croatia, it is AFAICT (almost?) always signed on a table in elevator (probably legal requirement so elevator is not overloaded; it usually specifies _both_ `max persons` and `total kg` here. I don't have huge experience with elevators in other countries though, but the ones I recall also had such limits signed); and ***max number of people*** (as you note) is relatively good **proxy** for ***will my bike fit physically*** (e.g. elevator for `8 persons` will quite likely fit my 28" trekking bike horizontally, while one for `4 persons` will likely require that I put it upright, and one for `2 persons` I'd best avoid).

And there is [capacity=*](https://wiki.openstreetmap.org/wiki/Key:capacity) (or [capacity:persons](https://wiki.openstreetmap.org/wiki/Key:capacity:persons)=*) tag that we can already use there (unlike [bicycle=*](https://wiki.openstreetmap.org/wiki/Key:bicycle) which we can't use to tag whether bicycle fits, as it means completely different thing).

**Comment by westnordost** [comment]
While `capacity:persons` may be useful, I think it is actually a proxy to `maxweight` rather than the available space in the elevator.

Here is a "pictures of elevators" blog

https://fahrstuhlbilder.blogspot.com/2020/09/aufzug_88.html

On the label, it says "carrying capacity 630kg or 8 persons". Sounds to me that the number of persons is just displayed as a convenience, using some key to translate kg to person.

**Comment by westnordost** [comment]
So I'll close the original issue (ask for whether bicycles may be transported in the elevator). For the alternative suggestion to ask for the elevators capacity in persons, create a new quest suggestion ticket. In any case, this may struggle with "🤷 Useful purpose" and with the "🕵️ Publicly accessible on foot" (because you need to go inside to see the sign that notes the capacity) quest guideline.
