### ISSUE TITLE
Remove lanes quest

### ISSUE THREAD

**Issue by BalooUriza** [streetcomplete/StreetComplete#5317]
**Use case**

Lanes tagging provided by StreetComplete incorrectly does not incorporate all lanes, nor does it ask for access permissions per lane.

**Proposed Solution**

Remove lanes functionality entirely.

**Comment by mnalis** [comment]
> Lanes tagging provided by StreetComplete incorrectly does not incorporate all lanes

Could you link to specific change where StreetComplete tagged number of [lanes=*](https://wiki.openstreetmap.org/wiki/Key:lanes) incorrectly, and what you think would've been correct tagging (and why), @BalooUriza? 

- (possibly related: https://github.com/streetcomplete/StreetComplete/issues/5240#issuecomment-1712674484 and rest of the issue; might be wording problem?)

**Comment by matkoniecz** [comment]
> Lanes tagging provided by StreetComplete incorrectly does not incorporate all lanes

are you complaining about StreetComplete not matching your personally preferred definition of `lanes` tag?

or are you complaining about StreetComplete not matching "Total number of traffic lanes available for motorised traffic." definition of `lanes` tag?

**Comment by BalooUriza** [comment]
Any time a motorcycle or bicycle lane comes up, StreetComplete falls short by a minimum of one lane and fails to apply the correct access.  This is harmful.

**Comment by matkoniecz** [comment]
This is not a place to redefine meaning of `lanes` tag.

I am aware of your long-standing dream of changing meaning of `lanes` tag - but that should be discussed at place representing general OSM community like https://community.openstreetmap.org/ (and attempt to redefine such widely used tag will likely fail).

**Comment by BalooUriza** [comment]
Super loving the positive attitude.  It really makes people feel welcome to be a part of a community and not like rude gatekeeping in any way whatsoever.

**Comment by mnalis** [comment]
@BalooUriza I'm not too happy either (to say the least) that people who invented `lanes=*` tag were car-centric and made that tag car-centric too (in actuality, our city-planers and car-oriented civilization is likely primarily to blame), but it is what it is. 

But that **popular `lanes=*` tag has been clearly defined to be car-centric for decades, so (as the saying goes) that cat has been out of the bag for some time now**, and any attempt to catch it and put it back in the bag is only going to earn you nasty scratches at best.

As @matkoniecz noted, **_redefining what wildly use tag means is basically impossible_** due to abysmal practical efforts (for starters, one should modify all pieces of software ever invented, included the ones used on devices unable to use newer versions of software, redact/update all docs, talks and videos that mention it, and then reach out to many thousands to millions of editors still using old definitions. Even if that was your single wish in life, and you had lots of money to burn, and supporters and decades of your life to dedicate completely to it, it might still not be guaranteed to work. Probably not a good hill to die on, IMHO - this is just a friendly advice, you're of course welcome to choose your own destiny)

---

The **best that can be done in practice, is to invent completely new tag** which is correctly and clearly defined from start to allow for **_all_** subdivisions of paths/tracks/roads and their placement and (so bus lanes, car lanes, bicycle lanes, pedestrian lanes, kerbs, lanes used for parking, sidewalks, bicycle tracks, horse/carriage etc), promote use of that new tag (might I suggest something feature-rich akin to: `highway_divisions=verge|sidewalk|kerb|bicycle_track_rev|kerb|parking_rev|motor_vehicle_rev|motor_vehicle_fwd|bicycle_lane_fwd|shoulder_fwd|kerb|sidewalk|verge` ?), and then when https://taghistory.raifer.tech shows the new tag is significantly more popular than old tags, propose to deprecate old tags.

That too would take a much effort and time, mind you, and is not guaranteed to work (depending on promoter advocacy skills and actual needs of people), but is _at least_ theoretically possible. I'd gladly participate to help discuss and promote such idea at [Community forum Tagging category](https://community.openstreetmap.org/c/general/tagging/70/)  or [tagging-Mailing list](https://wiki.openstreetmap.org/wiki/Tagging_mailing_list), but I definitely do not intend to be its proponent and main advocate (too many other, more important things in OSM to do for me, not to mention that I have few other things in life with even higher priority than OSM). 

Such community discussion is paramount to catch all the use cases and possible issue, lest lost of time and effort is completely wasted on new tag which only solves some problems but not others (e.g. which supports lanes for bicycles  but does not support electric scooters, so it too has to be thrown away to implement yet another new tag)

---

As for StreetComplete, it is intended to allow users to add **community-accepted tags** with their defined definitions from the https://wiki.osm.org. Once the whole OSM (not just StreetComplete!) community consensus is reached that `lanes=*` tag should be deprecated, then this request to remove (or update) StreetComplete Quest that sets `lanes=*` tags can be revisited. 

If you want to start tagging with such new, better non-car-centric lane divisions tag (as soon as it is discussed & clearly defined on wiki) **before it is wildly accepted**, I can recommend [SCEE](https://wiki.openstreetmap.org/wiki/SCEE) and [Vespucci](https://wiki.openstreetmap.org/wiki/Vespucci) editors for mobile, or [JOSM](https://wiki.openstreetmap.org/wiki/JOSM) for desktop to do so. That will allow you to build usage, needed to convince other mappers and data consumers to eventually start supporting that tag.

**Comment by matkoniecz** [comment]
I see that https://community.openstreetmap.org/t/making-lanes-orthagonal-and-consistent/105033 was created
