### ISSUE TITLE
Away from visual evaluation of smoothness

### ISSUE THREAD

**Issue by rhhsm** [streetcomplete/StreetComplete#5325]
Since it’s possible to add `smoothness` to the map with SC, I’ve had mixed feelings about it. On one hand I’m very happy that it’s possible to add this very useful tag to ways while in the field with such a user-friendly app. However, I feel that in the way it’s been implemented in SC, it deviates too much from the intented evaluation of the tag as described in the wiki.

Smoothness is meant to describe “_whether the way is usable_” by certain wheeled vehicles, and I think the best way to do that is to _imagine using_ that vehicle on that way and describing the expected experience using the available tag values. The photos on the wiki are “examples ONLY!” and so is the descriptive text that was added later (mostly by me). The evaluation in SC, however, relies mostly on the photos, so that users are tempted to compare the visual appearance of the way with the photos given by SC. I think this deviates too much from the intention of the wiki.

I propose that we change the photos given by SC so there is more focus on the vehicles and less on the visual appearance of the surface, and to no longer adjust the given photos to the already tagged surface. I expect in this way the mapper will more likely try to imagine what it’s like to use the way (we can add a text telling him to do so). I’ve done a search for license free photos and found these:
![320px-Racing_skaters_(Unsplash)](https://github.com/streetcomplete/StreetComplete/assets/69100427/eb228f24-c680-49b6-8079-ee838525d7a2)
`smoothness=excellent` (a surface so smooth that you can use it to race down it on a skateboard…)

![image-from-rawpixel-id-5928164-jpeg](https://github.com/streetcomplete/StreetComplete/assets/69100427/05e8c58f-33db-42b0-8984-f51714fdbbab)
`smoothness=good`

![Nishiki_207_city_hybrid_bike](https://github.com/streetcomplete/StreetComplete/assets/69100427/5896bcc8-ac01-4d4d-982f-52c8557d7125)
`smoothness=intermediate` (shows a typical city bike on `surface=sett` which is typically `smoothness=intermediate`)

![road-car-hole-volkswagen-van-asphalt-481555-pxhere com](https://github.com/streetcomplete/StreetComplete/assets/69100427/71e5b26c-59de-4524-b995-537834a24c99)
`smoothness=bad` (I would have preferred the potholes to be a bit deeper, I think this case is at the “good end” of `smoothness=bad`)

![pxfuel com](https://github.com/streetcomplete/StreetComplete/assets/69100427/99e5a483-7f56-4532-b6c0-fbad9d8f11b8)
`smoothness=very_bad` (nice to have an example from a non-European setting)

![off-road-4x4-mud-adventure-off-road-driving](https://github.com/streetcomplete/StreetComplete/assets/69100427/ecac2af1-7afe-444a-82a2-a5ca40346dd1)
`smoothness=horrible`

![Tractor_in_the_mud_-_geograph org uk_-_578481](https://github.com/streetcomplete/StreetComplete/assets/69100427/b100c9ce-0f35-4b95-8784-898c3e2c28e3)
`smoothness=very_horrible` (I use this tag value mostly on tracks that have been destroyed by logging equipment)

An additional advantage is that in this way we can also quest `smoothness` on ways with `surface=*` that we don’t have pictures of, and on ways that don’t have `surface=` at all (in Bulgaria there are many roads that are tagged with smoothness but not surface, probably thanks to this project www.roads-bg.eu). Smoothness gets critical when driving with a car on a track, but most tracks have `surface=ground`, `dirt`, etc for which we don’t have photos so they are not quested in SC ☹ (for me this application is the main reason why I’m so interested in this tag).

I realise and appreciate that a lot of effort has been invested to find photos of different smoothness values for many kinds of surfaces. However, this should not be a reason to reject changes.

**Comment by HolgerJeromin** [comment]
Just to reference the implementing PR: #3617  (I know you participated in this discussion) and the [wiki gallery](https://wiki.openstreetmap.org/wiki/Key:smoothness/Gallery) which was created for that.

> Smoothness is meant to describe “whether the way is usable” by certain wheeled vehicles

The quest has small icons in it, but we also have pictures and text.

**Comment by rhhsm** [comment]
I don't think implementing the pictures I proposed will be a significant effort compared to how much you and others already put into creating the gallery. Getting consensus on which 7 pictures to use for the different smoothness levels _no matter what the surface is_ (so no need to show the surface clearly) is already less effort than doing this for approx. 5 pictures for `ground` and `dirt` each (10 in total). I am wiling to spend the effort on putting them up for discussion on the OSM community forum, if we reach consensus here that it is a good idea to quest `smoothness` in this way on SC.

**Comment by westnordost** [comment]
> different smoothness levels no matter what the surface is 

I wasn't clear about this, so: I do think to have just one set of images for all surface would be a massive step backward. I wouldn't accept such a PR.

Pictures for ground, dirt and earth may be the same, that'd be fine.

**Comment by rhhsm** [comment]
What we should discuss first is if we share my worry that the way SC quests smoothness is too much reliant on the visual appearance of the road surface, and not enough on the _usability_ of the road by imagining using the road. What do others think about this?
If we have consensus on that, how to improve the quest is next up for discussion, and I'm open to other ways of improvement.
The third issue is then how to implement any proposed improvements.

**Comment by westnordost** [comment]
Well, we had this discussion already. And we concluded it. From what I remember, ...

Usability by vehicle type is...

- more subjective than visual comparison with the surface in question because what path is still usable for any one person by any one vehicle type is largely dependent on his experience and opinion. Even prefixing it with e.g. "usable ok" or "usable well" does not solve this, because, it is still, or is even more, subjective.

- less well verifiable because to properly see what's usable (well) for one vehicle type, you'd need to use that vehicle type. E.g. an asphalt road of certain coarseness might seem quite alright for a bike, but get your roller skates and find out that the asphalt is too coarse to be enjoyable. Surveyors don't usually carry around a vehicle park in a magic bag, so it is inherently less precise  as users will then either go by gut feeling or effectively record their data from the point of view of the vehicle they are currently riding

- worse yet, when the focus is on usable-by-vehicle type, it turns out that the understanding of what smoothness any given road should have can largely differ depending on whether one person looks at it from the point of view of a car driver or another person from the point of view of a bicyclist. We found that out during discussion (of the current pictures) where it became really difficult to bridge the disconnect that was primarily predicated on different points of view (car, bicycle) - in the end, it helped to refer to the actually verifiable and objective indicators: How the road looks like and what kind damages and/or irregularities are present.

So, vehicle type as a primary indicator for the smoothness - sorry, no, this will not be done. I hope you can understand this decision. 
That being said, you know that an icon of a vehicle type **is** actually shown in the selection option, but this is not the focus, the focus is most of all on the physical description of the surface and its visual appearance.

**Comment by jonpsp** [comment]
I think usage by bicycles can be a problem - I take bicycle to mean a road bike and will put up with smoothness=intermediate myself, but some mountain bikers might think that "bicycle" includes their specialist bikes.

**Comment by westnordost** [comment]
For at least the instances you name: No. For the same reasons. E.g. slow down 50% from which speed, with which vehicle? This description sounds really unhelpful and ambiguous. Skateboards, well as I said, a user that doesn't have a skateboard at hand will not be able to give an accurate answer to that inquiry. And, shown at random, uhm wow, that would be really bad UI ...not sure if you are still serious... but I guess you are...

Well anyway, as I wrote above, contribution of pictures (and later, short descriptions) for ground/dirt-based roads would be welcome.

**Comment by mnalis** [comment]
I too think that current implementation is better then suggested replacement for all the reasons mentioned; and we already do have (albeit small!) icons roughly indicating by which vehicle type such smoothness is usable (which seems to be main idea behind this request, just with much bigger photos).

As for possible improvements; I seem to recall the idea (cannot find the issue now) where (on the quest form) there would be an icon with a link to page with more details about the feature, where users could be educated with more verbose text and pictures and extra examples how to answer some quest.

**Comment by Helium314** [comment]
> cannot find the issue now

Maybe in #1913?
