### ISSUE TITLE
Way with complicated surface tag shows as without surface tag

### ISSUE THREAD

**Issue by rhhsm** [streetcomplete/StreetComplete#5330]
This way https://www.openstreetmap.org/way/787847733 and the oneway ways the the northeast have a rather complicated surface that is different for different lanes. However, on SC its surface is quested and in the surface overlay it shows red, i.e. as if its surface has not been tagged yet.
![Screenshot (23 okt](https://github.com/streetcomplete/StreetComplete/assets/69100427/0453c5a7-2ee3-4462-b684-4503bffd57d4)

This creates the risk that an unsuspecting user will decide that it's "mostly asphalt" or "mostly sett" and will answer the quest like this, which would be wrong.
Probably a very rare occasion so not very urgent... 

**Expected Behavior**
Ways that have a more complicated surface tag (for instance `surface:lanes:*=*|*`; there may be others) should not be considered as being without surface tag. No surface quest should appear, and they should not appear as red in the surface overlay.

**Versions affected**
54.1

**Comment by matkoniecz** [comment]
> This creates the risk that an unsuspecting user will decide that it's "mostly asphalt" or "mostly sett" and will answer the quest like this, which would be wrong.

Expected answer is `surface=paved` which even has as example concrete and asphalt on one surface area.

**Comment by rhhsm** [comment]
If the surface was indeed unknown, that would be the correct answer, or even better if a note was created. But here the surface is already described, so it would be useless to add another description of the surface in words. I'm afraid, however, that many users would be tempted to enter a wrong answer.

**Comment by matkoniecz** [comment]
Is there any case of this problem actually happening anywhere?

**Comment by rhhsm** [comment]
It's probably very rare, so solving it has low priority.

**Comment by HolgerJeromin** [comment]
> But here the surface is already described, so it would be useless to add another description of the surface in words.

I am not sure. Perhaps not in SC, but in the data it would be useful for programs which are not able to parse this information.

**Comment by Helium314** [comment]
In most cases I found, `surface` was tagged before someone added `surface:lanes[:*]`. But there are some cases where StreetComplete users only tagged one of the surfaces, changed `paved` to one of the surfaces, or even a added a surface different to any of the lane surfaces, e.g. https://www.openstreetmap.org/way/1004372340/history, https://www.openstreetmap.org/way/1030195917, https://www.openstreetmap.org/way/241497124/history

(and I noticed that in northeastern Germany, `surface:lanes` seems to be used for single lane tracks)

**Comment by mnalis** [comment]
I agree with @rhhsm about not coloring in `red` such already detail-mapped cases; as it basically  _invites users to **lower the OSM data quality**_ (and also _needlessly wastes mapper time_, but that is much lower-priority issue in this case)

**Comment by matkoniecz** [comment]
I plan to look how many such places exist worldwide, maybe manual handling will take less time than extra filtering.

For now I commented on https://www.openstreetmap.org/changeset/122193302 https://www.openstreetmap.org/changeset/142930527 https://www.openstreetmap.org/changeset/136056524

**Comment by rhhsm** [comment]
> > But here the surface is already described, so it would be useless to add another description of the surface in words.
> 
> I am not sure. Perhaps not in SC, but in the data it would be useful for programs which are not able to parse this information.

A written description would be even more difficult to parse for programs.

The best answer in the cases described above would be to reply with `surface=paved`, but that cannot be done in SC without also adding a description.
I added `surface=paved` to the above ways with iD, but that doesn't help much because SC still shows them as red in the overlay and quests them for surface.

**Comment by matkoniecz** [comment]
`surface:note=different lanes have different surfaces` or other `surface:note` tag will change display.

**Comment by matkoniecz** [comment]
@rhhsm What you think about tagging such as https://www.openstreetmap.org/way/4708393/history ? Would you consider it as preferable to omitting `surface` ?

(I do not want to apply weird tagging as workaround, but I think that it is genuinely better than no `surface` tag AND it solves problem raised here)

**Comment by rhhsm** [comment]
If we should not tag for the renderer, we should certainly not tag for the OSM editor app :) So I think we should add `surface` info as we like and see fit, even if it needs to be done with a `surface:lanes` tag. That such a tag is ignored by an app (and probably also by many humans because it's usually not very visible) is someone else's problem. And I'm afraid a `surface:note` tag will likely be ignored as well (though it might work for SC).

**Comment by matkoniecz** [comment]
> If we should not tag for the renderer, we should certainly not tag for the OSM editor app :)

I agree, that is why asked

> Would you consider it as preferable to omitting surface ?

and commented

> I do not want to apply weird tagging as workaround, but I think that it is genuinely better than no surface tag AND it solves problem raised here

**Comment by mnalis** [comment]
> Just because it is supported by app it does not mean that using this tagging scheme is incorrect.

I agree; in hindsight it was bad idea to name this principle as _"Do not tag for the renderer"_, as the [actual meaning](https://wiki.openstreetmap.org/wiki/Tagging_for_the_renderer) of the phrase is _"Do not **mis**tag for the renderer"_; and its popular phrasing makes it frequently misunderstood.

_Tagging (correctly) for the renderer_ (and for any other data consumer) is not only accepted, it is in fact the whole purpose of OSM existence :smiley: 

> I plan to look how many such places exist worldwide, maybe manual handling will take less time than extra filtering.

You mean human time to implement extra filtering functionality (i.e. adding extra tag [surface:lanes](https://taginfo.openstreetmap.org/keys/surface%3Alanes#overview) to ignore-coloring-as-red; which seems easy to me, although I have not looked at the code yet) or CPU-time (i.e. cumulative slowdown affecting UI, which I would think should also not being the issue)?

**Comment by matkoniecz** [comment]
> You mean human time to implement extra filtering functionality (i.e. adding extra tag [surface:lanes](https://taginfo.openstreetmap.org/keys/surface%3Alanes#overview) to ignore-coloring-as-red

and surface:lanes:backward and surface:lanes:forward and skipping in surface quest and tests and maintaining even more complex code (it is already on edge of what I can understand)

it is also about precedent - there are many cases where such similar detail may appear, and would be solved by `surface` and `surface:note`

**Comment by mnalis** [comment]
I'm not sure if we're talking about same thing, I was thinking more about just **not coloring in _red_ such already-complexly-mapped surfaces in Surface overlay**; not about fixing strange values or attempting to consolidate them, nor changing quests etc.

IOW It would not prevent people who decide on changing the surface; but it would **not invite** them to do so (which it currently does by waving that red cloth in front of mapper eyes :smile_cat:).

E.g. adding extra check to this:

https://github.com/streetcomplete/StreetComplete/blob/eade1b329165f76a4d40063b295ffeb864dbfa0f/app/src/main/java/de/westnordost/streetcomplete/overlays/surface/SurfaceColorMapping.kt#L70-L72

via something like this (I have not checked syntax / tried to compile, just an example):

```diff
- if (isIndoor(element.tags) || isPrivateOnFoot(element) || isLink(element.tags)) { 
+ if (isIndoor(element.tags) || isPrivateOnFoot(element) || isLink(element.tags) || isComplexSurface(element.tags)) { 

[...]

+ private fun isComplexSurface(tags: Map<String, String>): Boolean =
+    tags["surface:lanes"] || tags["surface:lanes:forward"] || tags["surface:lanes:backward"] || tags["surface:lanes:both_lanes"]
```

And adding a test or two for this case. It does not seem to me to raise the complexity significantly? Or would that not work (I have not tried writing overlays yet)? Or are we simply talking about different things?

I would be willing to write and test that code to reduce load on main devs, if such a fix is deemed acceptable?

> it is also about precedent - there are many cases where such similar detail may appear, and could be solved by tagging surface and surface:note

Sure, but I'm not talking here about having StreetComplete use something else - `surface:note` usage is just fine. But  convincing every mapper on planet to use that method (instead of `surface:lanes` etc what they use currently) is surely going to be way more complex and time consuming than those few lines of code change above? 

> Note that I am right now processing fixme=surface and preparing bot edit for weird surface values, see say https://forum.openstreetmap.fr/t/review-requested-before-proposing-bot-edit-for-automated-fixing-of-surface-values/18419

Nice effort, thanks for that!

> doing all that in StreetComplete would not work well

Which is why I'm not proposing anything like that :smiley_cat:

**Comment by matkoniecz** [comment]
> instead of surface:lanes etc what they use currently

I am not proposing to do it instead of perfectly valid `surface:lanes` but in addition to it

> I would be willing to write and test that code to reduce load on main devs, if such a fix is deemed acceptable?

I think that such surface should be rather shown as complex (in black, like `surface=paved` with `surface:note`), rather than not at all but in principle it would work. Note that also SurfaceQuest would need to be modified.

I am not enthusiastic as from own experience I expect that there will be an endless parade of similar ideas. I was dealing with it in some places.

**Comment by mnalis** [comment]
> I am not proposing to do it instead of perfectly valid `surface:lanes` but in addition to it

So (if I'm understanding it correctly), e.g. taking the example from the top of the issue, if the way was tagged:
```
surface:lanes:forward=asphalt|sett
surface:lanes:backward=asphalt|sett
```

you would *leave those existing tags in place but also add* `surface:note=*`  (with text akin to `in each direction, outermost (right) lanes are sett,  and innermost (left) lanes are asphalt` or similar)?

Am I understanding that correctly? If so, what would be the advantage of doing that human-readable transcription of machine-readable tags? (and if there are clear advantages, should we be doing such human-readable tags transcription for other tags too?) 

Dunno :shrug:, to me it would seem to have more problems then it solves (adding useless duplication is lesser of the problems; breaking [2NF](https://en.wikipedia.org/wiki/2NF) in that way would require endless effort to keep those tags in sync should any of them change, which might not be possible to automate in 100% of the cases, thus requiring possible separate database for storing exceptions, human time for reviews, bot upgrades & maintenance for new cases etc.)

> I think that such surface should be rather shown as complex (in black, like surface=paved with surface:note), rather than not at all but in principle it would work. 

Makes sense, thanks.

> Note that also SurfaceQuest would need to be modified.

Yes, good point, the quest also should not be asked on such already-detailed-surfaces.

---

If nobody objects (or prefers to do it themselves!), I could give it a try.

**Comment by westnordost** [comment]
The following PR would be accepted:

(In a nutshell: `surface:lanes` (etc.) as treated as if a `surface:note` was present. In detail:)

- change surface quests so that when specifying `paved` or another general value on a way that has `surface:lanes` (etc.) a `surface:note` is not be required when selecting such a general value. Conversely, a general value plus `surface:lanes` (etc.) but without `surface:note` shall not trigger the creation of the quest
- + Tests
- change surface overlay in the same way. For coloring: Red if `surface` is missing, the same color as when both `surface` and `surface:note` are present if `surface` and `surface:lanes` (etc.) are present.

**Comment by westnordost** [comment]
Do you intend to implement it, @mnalis ?

**Comment by mnalis** [comment]
OK, I'll give it a go

**Comment by Dimitar5555** [comment]
> Expected answer is `surface=paved` which even has as example concrete and asphalt on one surface area.

After some time SC asks the user what is the surface again (or the user uses the surface overlay) and we are back at square one. See version 35 of https://www.openstreetmap.org/way/275480468/history.

**Comment by westnordost** [comment]
Are you sure? I think it should ask the surface again immediately, because when a general surface like `paved` is selected, it always expects a note.

**Comment by westnordost** [comment]
I have been rummaging through @mnalis draft PR with the intention to finish it.

However, with heavy heart, I have now reached a point where I'd actually rather close this issue as will-not-fix with the advice to always add a `surface:note` in cases where a generic `surface` has to be tagged because different lanes have different surfaces, regardless of the presence of `surface:lanes`.

The reason is, in a nutshell, that it would add too much complexity to the code.

In particular, it adds too many asterisks to the code, in the sense that having to handle `surface:lanes` as sufficient replacement for `surface:note` in case a generic surface was specified breaks a lots of abstractions made in the code:
`surface` can be applied to many things - roads, paths, pitches, sidewalks (left and right), cycleways (left and right) - , so the code has been written to accommodate that. But _only_ for roads, `surface:lanes` is relevant.
So basically, we would end up with "but for roads that have `surface:lanes` tagged..."-exceptions basically everywhere where anything with `surface` is done. **Or** refactor it all to be even more generic in order to accommodate this somehow in a clean manner, but this is even more effort.

(By the way, if there only was the surface quests, it wouldn't be such an issue, but to accommodate it in the overlay is a real PITA.)

So, anyway, sorry that this is not going to be implemented and also sorry to @mnalis that he poured some work into this already.

---

But, there is something that came to my mind when reviewing the whole "generic surfaces plus `surface:note` thing".

Do we really *need* to require a `surface:note` when a generic `surface` is set? If I remember correctly, the following things changed since the decision was made to require a note when a surface is under-specified:

1. surfaces are no longer grouped by paved, unpaved, ground and these general values are displayed at the very bottom of the list

2. the surface quest is asked again every X years. SC always gives a warning when the surface is under-specified, so it is very likely that on re-survey, users will specify a specific surface.¹

3. we have the surface overlay with which it is somewhat easy to spot and correct under-specified surfaces

¹ _However_, surface quests are rarely re-asked because they are only re-asked if the road hasn't been touched in X years. Roads are generally touched more often, so this mechanic isn't working well and never did, TBH

**Comment by westnordost** [comment]
@matkoniecz what do you think about this?

**Comment by matkoniecz** [comment]
In general, personally I am not really liking when editors are pushing some tagging in one direction or another with primary justification as "it would add too much complexity to the code"

But in this case I think that I would use `surface:note` or `note` also as a human editor, so I consider it as fine here.

**Comment by westnordost** [comment]
I rather meant, what do you think about the latter part of my previous post. Think about why we require `surface:note` for in the first place: We want (SC) users to resurvey places where the surface type has been under-specified. And if this is our motivation to do this, there is another solution for it. E.g., something like this in the quest filter:

```diff
- or surface ~ paved|unpaved and !surface:note
+ or surface ~ paved|unpaved and !check_date:surface
```
This forces SC users to re-survey any road with a generic surface **_once_**.

**Comment by matkoniecz** [comment]
I agree with this idea and I like it.
