### ISSUE TITLE
Consider explicitly tagging "always open" opening hours

### ISSUE THREAD

**Issue by Cj-Malone** [streetcomplete/StreetComplete#5355]
I'm now wondering if SC "Always open" should fill the UI with "Mo-Su 00:00-24:00", allow the user to edit (Add PH, remove Sa Su, etc) then tag the more explicit value.

_Originally posted by @Cj-Malone in https://github.com/streetcomplete/StreetComplete/issues/5354#issuecomment-1793403056_

**Comment by westnordost** [comment]
Why, always open means 24/7, doesn't it? In any case, if this is not accurate, the *wording* should be changed to say explicitly 24/7.

An ATM is often "always open", i.e. 24/7, also on the weekend and also on holidays.

**Comment by Cj-Malone** [comment]
I meant to say "Mo-Su 00:00-24:00".

**Comment by Cj-Malone** [comment]
> always open means 24/7, doesn't it?

It's not actually that clear what `opening_hours=24/7` means.
https://en.osm.town/@CjMalone/111351863388241366

**Comment by simonpoole** [comment]
The spec has always been crystal clear that 24/7 is "always".

**Comment by Cj-Malone** [comment]
> The spec has always been crystal clear that 24/7 is "always".

And yet more people on the OSM Mastodon think it means "Mo-Su 00:00-24:00" than "Mo-Su,PH 00:00-24:00".

I'm not arguing that it means one or the other, I didn't even vote. I'm simply saying it may be better to be explicit.

**Comment by westnordost** [comment]
I see. Well, if ithe opening hours are specified explicitly on the shop, then it is possible to also write it that way in StreetComplete. In fact, I recommended to always write the hours in the same way as they are written on the sign.

Otherwise, if the user specifies that it is always open, it should be tagged that way. " always means always".

So, I see no reason to change anything here.
