### ISSUE TITLE
[Quest] How are these level crossing gates opened?

### ISSUE THREAD

**Issue by arrival-spring** [streetcomplete/StreetComplete#5356]
### General
Affected tag(s) to be modified/added: [crossing:activation](https://wiki.openstreetmap.org/wiki/Key:crossing:activation)
Question asked: **How are these level crossing gates opened?**

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/blob/master/QUEST_GUIDELINES.md)):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [ ] 🐿️ Easily answerable by any pedestrian from the outside but a survey is necessary
- Difference between `automatic` and `remote` is probably not obvious
- [x] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
- (with appropriate filtering)
- [x] 🕓 Applies to a reasonable number of map data (Worth the effort)
- (almost 175000 level crossings, only 21000 tagged with crossing:activation)

### Ideas for implementation

**Element selection:** 
`railway=level_crossing and crossing:barrier=* and crossing:barrier!=no`
AND
On some sort of small `highway`, e.g. only paths, tracks and service roads. "Big roads" can be assumed to have automatic barriers in most countries.

**Metadata needed:** 
Maybe disabled in some countries, or adjust road filter in some countries.

I used https://overpass-turbo.eu/s/1CT8 to try to get an idea of the state in different countries of the usage of crossing:activation.

**Proposed UI:**
List select:
* Opens automatically (`automatic`)
* Opened by railway staff (`local`)
* Has to be opened by the person who wants to cross (`user`)

**Comment by mnalis** [comment]
> [x]  🚧 To be added tag is established and has a useful purpose

It would be nice to elaborate on that a little as it is non-obvious (to me at least); e.g. how is that tag being used, which data consumers use it (and how), what does it help with, or similar. (given number of railway fans, there is obviously _motivation_ to tag all things railway-related, but is there also a _useful purpose_ to it?)

>  On some sort of small highway, e.g. only paths, tracks and service roads. "Big roads" can be assumed to have automatic barriers in most countries.

`[citation needed]` ? I'm not a really a huge railway aficionado (although I have recently surveyed some abandoned railway tracks), so I have not payed too much attention to it, but for example in Croatia, in my experience it seems relatively common for "normal" roads (`residential`,  `unclassified`, `tertiary`) to still have stuff operating them manually, even in capital of Zagreb. e.g. this tertiary road in my neighborhood: https://www.openstreetmap.org/way/876406766 

Those on higher priority roads (`secondary`, `primary`, `motorway`)  are often done in such a way that crossing is avoided altogether (e.g. bridges / underpasses) as an long-term better alternative to automating them.

> Difference between `automatic` and `remote` is probably not obvious

Yes, I guess only hard-core railway fans would be able to distinguish those values. Too bad there doesn't seem to be less-precise documented tag in use which would encompass both (i.e. with a meaning _"neither user-activated nor manually operated by local staff, but seems to be activated in some way indeterminable by average passerby"_). Perhaps it exists but hasn't been documented?

To pic a correct one seems to me like quite problematic burden to be put on a regular StreetComplete user. But I'm even more  **disliking the idea** of effectively _burning_ the value of `automatic` by **redefining it within SC** to mean _"Opens automatically"_ instead of documented wiki value of _"(automatically activated) by treadle or contacts detecting a train"_ (as opposed to `remote` which is _"remotely operated by railway staff (e.g., signalman)"_). Both are action on a distance, but the _actual_ source of the signal is quite unlikely to be known to average SC user.

----

Thus, IMHO [SCEE](https://wiki.openstreetmap.org/wiki/SCEE) fork (which allows for quest that require _domain expert knowledge_) seems like a better fit (with **_all_** documented values being offered with their precise wiki explanations,  including `automatic` and `remote`).

**Comment by arrival-spring** [comment]
> [x]  🚧 To be added tag is established and has a useful purpose

I think it is useful in terms of a greater routing penalty when you have to open and close the gates yourself, and also for analysing safety of crossings. I don't know that it is being used at the moment, although taginfo shows that OSMAnd is using it "to create maps (POI)", so maybe there are different icons or something?

> `[citation needed]` ? I'm not a really a huge railway aficionado (although I have recently surveyed some abandoned railway tracks), so I have not payed too much attention to it, but for example in Croatia, in my experience it seems relatively common for "normal" roads (`residential`, `unclassified`, `tertiary`) to still have stuff operating them manually, even in capital of Zagreb. e.g. this tertiary road in my neighborhood: https://www.openstreetmap.org/way/876406766

Ok, so that would need to be adjusted per country. Looking at the overpass link e.g. on Germany shows almost everything as `automatic` (and a lot mapped). 

> Difference between `automatic` and `remote` is probably not obvious

I have asked about the difference [on the forum](https://community.openstreetmap.org/t/how-to-tell-the-difference-between-automatic-and-remote-operated-level-crossings/105673)

The wiki vaguely mentions combining values, and there is a little bit of usage of such values, including `remote;automatic` 4 times, but it's not so clear what that means in real terms.

**Comment by westnordost** [comment]
Hm well, see @mnalis.

> 🐿️ Easily answerable by any pedestrian from the outside but a survey is necessary
> Difference between automatic and remote is probably not obvious

Generally, for a quest to be included, it is necessary for all guidelines to be fulfilled. It does not look like all possible answers are surveyable. *In the vast majority of cases*, the crossing gates are automatic, but the app will not be possible to tag it because the user is not able to ascertain out on-site if it is "automatic" or "remote controlled" (whatever the difference between the two should be 🤷).

Let's say on the forums/ML a consensus is reached that `remote` is deprecated and/or considered synonymous to `automatic`. Then, it seems to me, that it is still difficult to ascertain because one would need to wait at the crossing until it opens and closes to see how it is operated. Asking for the presence of some kind of crank does also not cut it, because also automatic ones might have something like that as a fallback/emergency mechanism. Conversely, a manually operated one may also not have a obvious crank but just some hole in which the operator inserts a crank (I don't know... 🤷 ... it's all possible)

For less frequented crossings, that may take half a day or longer. I don't even know how it would need to look like for `user`.

So, I'll close this.
