### ISSUE TITLE
Quest CyclewayOverlay removes `oneway:bicycle=no`

### ISSUE THREAD

**Issue by tordans** [streetcomplete/StreetComplete#5367]
**How to Reproduce**

It looks like, in some cases the Quest CyclewayOverlay removes `oneway:bicycle=no`.

This was reported in https://www.openstreetmap.org/changeset/141434793 ([OSMCha](https://osmcha.org/changesets/141434793/)) for [this way "Schlangenbader Straße"](https://osmlab.github.io/osm-deep-history/#/way/4395528)

* Version 27 is SC
* Version 28+29 are the manual fix

<img width="814" alt="image" src="https://github.com/streetcomplete/StreetComplete/assets/111561/c52bcebf-7b7c-4adb-82bf-9638efedc63b">

**Expected Behavior**

User Mopshase12 founds this to be an unexpected change. In the [changeset discussion](https://www.openstreetmap.org/changeset/141434793) he said an additionale question might be needed to make sure this change is intended.

**Versions affected**

The version used was StreetComplete 54.0

**Comment by westnordost** [comment]
The fact that `oneway:bicycle` _can_ be removed with StreetComplete is not a bug.

Please provide additional information on what is the current behavior of the app and what is the expected behavior of the app.

**Comment by Helium314** [comment]
Tried in SCEE 55.0, so I can modify tags. There are no relevant changes compared to SC 54.0 in the cycleway overlay.

From the changes it appears the user only set the western cycleway (right side in OSM) to none, I can't reproduce the tagging otherwise.
When clicking ok, there is a dialog with "_Are you sure that cyclists are not allowed to use this one-way street in both directions? If you’re unsure, look for a sign at the end of the street._", so the user clearly knew they were marking the road as one-way for cyclists.

However, the user answered only for `cycleway:right` and left the other side undefined, where they might have to check for a sign at the end of the street. SC adding a change related to the other side is unexpected here.

**Comment by westnordost** [comment]
Mh, so I understand correctly that it was both a mistake by the user but also a bug in the app?

I.e. the app should not assume any one-way-ness for cyclists as long as the cycleway on the contra-flow side of the oneway is not set? (Best start with a test case, to see what's going on. There must be some reason why SC interprets the situation that way)

**Comment by Helium314** [comment]
> I.e. the app should not assume any one-way-ness for cyclists as long as the cycleway on the contra-flow side of the oneway is not set?

I guess so, but as you mention: there might be a reason for the current behavior. Maybe related to the possibility of having both directions on one side.

**Comment by westnordost** [comment]
No, it was a bug alright. The algorithm that would determine if a road is a now also a oneway for cyclists didn't take into account (correctly) that the user is able to also define the cycleway for only one side. In that case, the side that likely doesn't matter for the contraflow.
