### ISSUE TITLE
Maxheight quest shows wrong sign template in US, v55.0

### ISSUE THREAD

**Issue by pkoby** [streetcomplete/StreetComplete#5384]
Recently, I've been seeing the wrong sign shape for the maxheight quest. I think until last version it was as expected, being a rectangular yellow sign with ft and in options. Now it's showing an oval with a red outline and black triangles top and bottom, but still with ft and in.

**How to Reproduce**

Clicking any maxheight (non-AR style) quest at least in the Philadelphia area has this issue.

**Expected Behavior**

Would like the yellow rectangle back.

**Versions affected**

At least v 55.0. Don't remember it before this version.
![2023-11-23 09 07 40](https://github.com/streetcomplete/StreetComplete/assets/7786285/241cfbfb-294d-45c2-a02d-fb67f98b1887)

**Comment by westnordost** [comment]
Caused by https://github.com/streetcomplete/StreetComplete/commit/d94b433a6a4f7940233608e6d269e926f6f1a3e7 , possibly affects maxspeed and maxweight sign too.

ping @FloEdelmann

**Comment by westnordost** [comment]
I've looked at how to fix this but decided in the end to revert the change made in https://github.com/streetcomplete/StreetComplete/commit/d94b433a6a4f7940233608e6d269e926f6f1a3e7 because the way the code is structured there (dealing with layout ids rather than with actual layouts) it makes dealing with this somewhat awkward: First inflate it, then remember that you still need to adapt the color of the sign, which could be a completely different place in the code  (as with the maxweight sign quest form) .

Inflating the correct layout and setting the background image should be done at the same place, but that would require quite the refactor.

**Comment by FloEdelmann** [comment]
Thanks for finding and for fixing this! I agree that reverting that commit is a good fix; now the layouts are duplicated but it's at least consistent everywhere.
