### ISSUE TITLE
Non permanent objects: exception to "Survey if places still exist" question

### ISSUE THREAD

**Issue by Kalepom** [streetcomplete/StreetComplete#5394]
Hello, 

That's not really a bug, but nor a new question suggestion. I hope I'm not posting in the wrong place.

The "Survey if places still exist" quest should make an exception on items with the permanent=no tag. 
I'm thinking in particular of election boards (advertising=board message=political permanent=no) which are not permanently present. By answering the question "Is this object still here?", a user could risk deleting it from the database, even though the cyclicity is well defined. 

Thanks

**Comment by matkoniecz** [comment]
neither https://wiki.openstreetmap.org/w/index.php?title=Key:permanent&action=edit&redlink=1 nor https://wiki.openstreetmap.org/w/index.php?title=Tag:permanent%3Dno&action=edit&redlink=1 seems documented

**Comment by mnalis** [comment]
> Why would it be wrong to delete a non-permanent object that has been removed?

I've tried to document in PR text edit: the panels are removable, but their location is permanent because they are anchored in the ground (see  e.g. https://projetdumois.fr/projects/2017-04_electionboard). So they get removed and reinstalled at the exact same place.

Another way to look at it is that it basically maps _"board stand"_, which may or may not have (at some specific time) _"board panel"_ installed on it. But when the users goes there "out of season", they might not look hard enough (i.e. from a distance) and declare that it is missing, while in fact it is still there. 

(this is how it differs from e.g. [temporary=yes](https://wiki.openstreetmap.org/wiki/Key:temporary), which I've also considered [and rejected], as for those it is expected to be removed and it is even welcome for SC to remove it when it is no longer present there).
