### ISSUE TITLE
Ask what sort of boats can be rented

### ISSUE THREAD

**Issue by arrival-spring** [streetcomplete/StreetComplete#5426]
### General
Affected tag(s) to be modified/added: [`*_rental=*`](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dboat_rental)
Question asked: **What sort of boats can be rented here?**

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/blob/master/QUEST_GUIDELINES.md)):
- [x] 🚧 To be added tag is established and has a useful purpose
Canoe rental is very different to motorboat rental, it is important to be able to distinguish these
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by any pedestrian from the outside but a survey is necessary
- [x] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of map data (Worth the effort)
Only just over 5000 `amenity=boat_rental` but many (>~75%?) do not have a `_rental` tag.

### Ideas for implementation

**Element selection:** 
`amenity = boat_rental` and `*_rental != *`

**Metadata needed:** 
Don't think so. Maybe different boats in different countries?

**Proposed UI:**
Picture/icon multi-select for kayak, canoe, stand-up paddleboard, sailing boat, dinghy, motorboat and pedalboat.

**Comment by westnordost** [comment]
Sounds useful.

It should be checked if anything is missing from the list in the wiki and be added.

The biggest part of implementation will be to find icons for this that each fit and have the same style. Maybe requires drawing some oneself. I had a look:
- with people: https://www.svgrepo.com/collection/water-sports-flat-icons/  (<- may also give a hint which rentals are missing and/or which "other answers" should be added)
- kayak: https://www.svgrepo.com/svg/277547/kayak
- houseboat: could maybe use the building icon
- canoe: https://www.svgrepo.com/svg/276850/kayak-canoe 
- sailboat: https://www.svgrepo.com/svg/275483/sailboat

**Comment by westnordost** [comment]
Aw, too bad you didn't work on this in the end, I would have liked a new quest with fun new icons to select from. But for anyone who reads this, (including arrival-spring ofc), feel free to pick this up.

**Comment by kmpoppe** [comment]
@westnordost could you assign this issue to me, please?

**Comment by westnordost** [comment]
Awesome! You know, I just bought a SUP because it's so fun to paddle in the summer and I was leaving too much money at the rentals...

The biggest part of the implementation will be to determine which kind of boats can be rented (and then finding icons for it), anyone can help here.

As my contribution to this, I checked various rentals for which boats they rent. In fat, boats that may be more rare:
- [SUP Club Hamburg](https://www.supclubhamburg.de/): SUPs, kajaks, canadian canoes, pedal boats
- [Supperclub](https://supperclub.de/): SUPs, kajaks, canadian canoes, pedal boats, row boats
- [Anleger Hamburg](https://www.anleger-hamburg.de/): SUPs, kajaks, canadian canoes, pedal boats, **dragon boats** (basically very large canadian canoes)
- [Bootshaus Silwar](https://bootshaus-silwar.com/): kajaks, canadian canoes, pedal boats, row boats
- [Marina Marienhof](https://www.marina-marienhof.de/): SUPs, kajaks, canadian canoes
- [Bobby Reich](http://www.bobbyreich.de/): sailboats (up to 4p), row boats, canadian canoes
- [Segelschule Pieper](https://segelschule-pieper.de/bootsverleih#/): sailboats (up to 5p), pedal boats
- [Käpt'n Prüsse Segelschule](https://pruesse.de/toerns-chartern/bootmiete-alster/): sailboats
- [Seehaus Hamburg](https://www.seehaus-hamburg.de/boot-supverleih/): pedal boats, SUPs
- [Hansa-Steg](https://www.hansa-steg.de/bootsvermietung/): pedal boats, row boats, canadian canoes, SUPs
- [SUP-Legion](https://www.sup-legion.com/): SUPs
- [Heiuki Mühlenkamp](https://heiuki.com/standorte/deutschland/hamburg/winterhude-muehlenkamp/): SUPS, kajaks
- [Heiuki Bille](https://heiuki.com/standorte/deutschland/hamburg/bille/): SUPS
- [Bootsvermietung Dornheim "Zur Gondel"](https://www.bootsvermietung-dornheim.de/): kajaks, canadian canoes, row boats, pedal boats, [**(venetian) gondolas**](https://en.wikipedia.org/wiki/Gondola), **dragon boats** (or very large canoes, one for 13p, one for 18p)
- [1. Hamburger Drachenboot-Club e.V.](https://www.hamburgallstars.de/vermietung/): **dragon boats**
- [SUP 2 go](https://www.sup2go.de/sup-verleih-hamburg): SUPs
- [Bootsvermietung auf der Liebesinsel](https://www.stadtparksee.de/): row boats, pedal boats, canadian canoes
- Bootsvermietung Cafè Sommerterassen: canadian canoes
- [Paddel Meier](https://www.paddel-meier.de/): kajaks, canadian canoes, SUPs
- [Bootsvermietung Hamburg](https://www.bootszentrum-hamburg.de/): pedal boats, **motor boats**
- [Kanu-Hafen Bergedorf](https://kanu-hafen.de/): kajaks, canadian canoes
- [Bootshaus Bergedorf](http://bootshaus-bergedorf.com/): kajaks, canadian canoes, SUPs, pedal boats
- [Elbgänger SUP](https://www.elbgaenger-sup.de/#verleih): SUPs
- [Wasserski Hamburg](https://wasserski-hamburg.de): **Water ski**, **wakeboard** (TBH not really sure if this should be tagged as a boat rental. You don't really rent the water ski and then go your way... very different from other boat rentals)
- [Hausboot.Hamburg](https://www.hausboot-hamburg.de/): **_moored_ houseboats**
- [Hausboot Schwan](https://hausboot-schwan.de/): **_moored_ houseboats**
- [Hamburg Boats](https://hamburgboats.de/hausboote): **_probably moored_ houseboats** (but they look more boat-like)
- [Hausboot Hafen Hamburg](https://hausboot-charter-hamburg.de/): **_probably moored_ houseboats**, **rafts**

This list got much longer than I expected. Anyway.

So, from looking through all this, I have a few comments:

- There should probably be a "Not a rental" option, because some places that may look like rentals either exclusively offer berths and/or storeroom for owned boats (i.e. a marina, a "parking lot" for boats) and/or are water sports clubs (that don't additionally do rentals, very few do). On the other hand, one could leave a note...

- a sailboat is not a sailboat. There should be some distinction between a sailboat you can rent for a few hours with a capacity of a few people and a sailboat that you treat basically like a camper van on water. Maybe a good line to draw would be whether the boats have a cabin or not, i.e. you can go below deck. On the other hand, of the rentals above, there was not a single one that would rent out big sailboats in which you could spend the night.

- I have doubts whether houseboat rentals should be treated as boat rentals, they are much more alike accommodation rentals like chalets or stationary caravans. All houseboat rentals I have found (see list above) are all moored or are probably moored.
