### ISSUE TITLE
Unable to split ways at current location dot

### ISSUE THREAD

**Issue by moebelwagen** [streetcomplete/StreetComplete#5435]
When splitting ways, I can't set a split marker on top of the current location dot. I don't mean the bigger circle showing the location accuracy, but the inner dot. Sometimes I would walk aside just to be able to set the marker at my previous location.

**How to Reproduce**
The behavior is the same whether you use overlays or solve a quest. So e.g. open a road surface quest. Click that it is different along the way and confirm that you want to split the way. Position yourself so that the current location dot is exact on the road. Try to set a split marker at that location.

**Expected Behavior**
Split marker should be set.

**Versions affected**
My current version is 56.0. I am pretty sure though that I have seen this behavior for several versions.

**Comment by westnordost** [comment]
The tap seems to be consumed by the location dot (IIRC tapping on it will focus the map on the location dot).

One way to solve this would be to change the split way UI to be similar to the UI when placing nodes, i.e. a crosshair + ✂️-button. I think this would be the best solution, as
- it is then consistent with the other UI
- it is slightly more convenient because you can usually move the map and press the button with just your thumb (one-handed)
- it is slightly more precise, as your finger currently obscures the precise position you are pressing

**Comment by mnalis** [comment]
While I agree that crosshair might be little more precise, I too **don't** think it would be more convenient. 

(It might also have another advantage for left-handed people as it might allow them to use it more easily one-handed, but I'm right handed and have too big a phone, so one-handed crosshair doesn't work for me at all)

In any case, I'm not particularly fond of crosshair UI. For example, SCEE has alternative way to add new POIs (long press on location, choose `Add POI` in menu - similarly like you would leave a Note for example) and I find I use that approach almost exclusively, even when I have Shop overlay open (and it would be one less click to add POI via crosshair and `+` icon)!

I don't know why that is, though. Certainly `+` icon being on inconvenient place (for me, as we [lack left/right handed preference](https://github.com/streetcomplete/StreetComplete/issues/4464#issuecomment-1268184975)) doesn't help, but whole crosshair UI seem somehow unappealing / unintuitive to me. :man_shrugging:

**Comment by westnordost** [comment]
I was wrong, tapping on the location dot doesn't actually do anything. So, the dot does not need to consume the event.
