### ISSUE TITLE
Continuous crossings

### ISSUE THREAD

**Issue by osmuser63783** [streetcomplete/StreetComplete#5443]
**Use case**
When a footway/path meets a road, the user is asked: "Is there a crossing here?" The answer options are:
* Yes (e.g. the kerb is lowered here or there are markings)
* No, but crossing is possible
* No, crossing is prohibited or impossible

A scenario not covered by the above options is a "continuous footway", "continuous sidewalk", "continuous pavement", "continuous crossing" or "Copenhagen crossing" (it goes by many names):
![Ryland_Road_continuous_footway](https://github.com/streetcomplete/StreetComplete/assets/127188803/ea398aaa-98a8-491d-aabb-60c884d8d26c)

At least in one case a mapper was asked the StreetComplete quest for this type of situation and answered "No, but crossing is possible". It's understandable why they chose this option, but it results in tagging `crossing=informal` which is not right at all.

**Proposed Solution**
We now have an approved tag [`crossing:continuous=yes`](https://wiki.openstreetmap.org/wiki/Key:crossing:continuous) for the above situation. 

I suggest adding a fourth option to the question "Is there a crossing here?"
* Yes (e.g. the kerb is lowered here or there are markings)
* No, but crossing **the road** is possible (-> slight tweak to the wording)
* No, crossing is prohibited or impossible
* **The path just continues uninterrupted across the road.**

Selecting the new option should set `crossing:continuous=yes`.

Other options for phrasing it:
* "Yes, it is a continuous crossing [sidewalk/pavement/cycleway]" (though that assumes that mappers are familiar with the term)
* "Yes, but drivers have to cross a section of footway [cycleway], instead of pedestrians [cyclists] having to cross the road"

The exact phrasing could maybe depend on the tagging of the path (e.g. if it's a footway or cycleway or shared), to make sure it's clear. (It's clearer to say "The sidewalk just continues uninterrupted" than to say "The path...")

Because the situation is much more common with sidewalks than elsewhere, another soluation might be to only show the fourth option for paths, footways and cycleways with tags such as `footway=sidewalk` and `is_sidepath`.

**Comment by westnordost** [comment]
That sounds like a good idea.

In German, one would probably say something along the lines of "Die Straße kreuzt den Bürgersteig" -> "the street crosses the sidewalk". Your suggestion sounds a bit odd to my (German) ears and unfortunately we only have text to display the options (currently) - a picture like yours above would make it very clear what is meant.

**Comment by osmuser63783** [comment]
Example from Germany:

![20231105_132132](https://github.com/streetcomplete/StreetComplete/assets/127188803/61c597ec-662e-430e-b52f-566ec3839ec1)

My first language is also German. If I was describing the situation in German I would probably say something like "der Bürgersteig geht einfach weiter". 

The phrasing could definitely be tweaked. Maybe we could make a poll in the community forum to ask what people would find clearest?

> On the other hand, the kerb is lowered here, so I wonder why the mapper answered "No, but crossing is possible"

The convention is that the `kerb` on `highway=crossing` is about the kerb that the pedestrian has to cross. So I would tag the above as `kerb=no`.

**Comment by westnordost** [comment]
> The convention is that the kerb on highway=crossing is about the kerb that the pedestrian has to cross. So I would tag the above as kerb=no.

That's quite irrelevant though, users are not asked about or shown OSM tags.

**Comment by osmuser63783** [comment]
That's true. But similarly, even a StreetComplete user who has never looked at OSM tags could be used to the "kerb" in the question - and the one in the crossing kerb height quest - being the one that you cross as a pedestrian, from the sidewalk onto the carriageway. When they see the option "Yes (e.g. the kerb is lowered here or there are markings)", the user might conclude, the kerb isn't lowered, because there isn't a kerb at all, nor are there markings, so the first choice isn't right.

I'm not sure, just guessing!

**Comment by westnordost** [comment]
Hm.

Well, the suggestion is currently based on one user misunderstanding the question, so we don't know whether this is a systematic misunderstanding or not.

And, reviewing this, it seems to me, that whether the road crosses the sidewalk or the sidewalk crosses the road is a property that is orthogonal to the other answers. In other words, I fear that if such an answer option was to be introduced, the potential for misunderstanding might actually increase, rather than decrease, especially since the quest is (currently) text only.

So, I'd rather close this. If this indeed turns out to be a systematic misunderstanding, the UI would probably need to be reimplemented to actually show pictures to help identifying which option should be selected.

**Comment by vfosnar** [comment]
I came across the same situation and I'd too expect people to make the mistake as described here. Maybe reopen with the possibility to implement the quest using photos like it was alr mentioned here?

**Comment by MaledictYtb** [comment]
I am really confused when I'm asked asked "Does this crossing have markings across the roadway ?". 

Should I say Yes or No ? 
I want to say Yes because I can see the crossing, but is it really marked ? 
If I say no it also feels wrong since I can see the crossing on the road. 

If we look at the OSM Doc, we should say it isn't marked, which feels wrong to me. 
https://wiki.openstreetmap.org/wiki/Key:crossing:continuous (See the first example). 

I think it would be a lot less confusing if there was a third option "This is a Continuous Crosswalk".
