### ISSUE TITLE
Questing should stop after hiding an Existence quest

### ISSUE THREAD

**Issue by rhhsm** [streetcomplete/StreetComplete#5450]
I was asked if an office still exists, to which I replied "Can’t say… - Hide" (it's often impossible to see from the street if a small office in an apartment building doesn't exist any more or is just not visible). I was then asked for its opening hours.

**How to Reproduce**
Look for this node https://www.openstreetmap.org/node/5988388737 . Reply "Can’t say… - Hide". The Opening Hours quest appears.

**Expected Behavior**
After hiding an Existence quest, it is uncertain if the PoI still exists, so SC should assume it doesn't and no further quests should appear about it.

**Versions affected**
10/v56.0

**Comment by westnordost** [comment]
Ah, yes, well. Actually not a bug. It would be a bug if you left a note at that place and any other quests would still be asked. As for the hide-feature, this is more fine-grained: Hiding one quest really does only hide that one quest and not blocks all quests for that element.

I am not inclined to change this because for both behaviors (block all for this element / hide only this quest) one could equally argue for and in that case, I prefer to leave it as it is:
If you decide you cannot or don't want to answer a quest for an object now, it does not follow that you don't want or can't answer any other quest for that object.

**Comment by rhhsm** [comment]
Not a bug indeed, but I can't find out how to add other labels like "enhancement"...

I agree with you in general, but shouldn't there be an exception to this rule for the Existence quest? If the existence of the object is doubtful, any other quest for that object will also be doubtful. Shouldn't the existence of an object be confirmed first before asking more quests?

**Comment by matkoniecz** [comment]
If existence is doubtful then I would assume that mapper would make a note with a photo.

**Comment by westnordost** [comment]
> Not a bug indeed, but I can't find out how to add other labels like "enhancement"...

You can just open a blank issue (bottom link).

Anyway, yes, you have a point, from the perspective of this particular use case, it seems to make sense to hide all the quests for elements for which you cannot answer the check-existence quest.

However, I it would be quite a big of an exception from the technical point of view, which means the effort to implement and maintain need to be weighted against its advantages even more than usual. And here, I don't see that the advantages of changing this behavior for specifically this quest only is worth it. To be honest, even if the cost of implementing this behavior would be zero, I would be somewhat critical to introduce this exception because UI consistency is important. The UI being "smart" (at times) can quickly tilt towards the UI feeling buggy.
