### ISSUE TITLE
Address heatmap when zooming out in Address overlay

### ISSUE THREAD

**Issue by RedAuburn** [streetcomplete/StreetComplete#5452]
**Use case**
Currently, it's difficult to figure out what areas need housenumbers without checking on a PC beforehand. Right now, I have time to kill so want to map some addresses, having a heatmap would allow easily finding areas with no house numbers.

**Proposed Solution**
A red-green heatmap when zooming out in the address overlay, showing where housenumbers are mapped and where they are missing.

**Comment by westnordost** [comment]
Hm well, this is not possible with the map render library we use (tangram-es). We are looking into changing the map renderer to maplibre, maybe it will be possible then. But first, that has to happen, so right now, this is a will-not-fix.

What you could do instead if you want to complete housenumbers is to activate the building type quest and the address quest. These appear automatically where information is missing.

**Comment by mnalis** [comment]
@RedAuburn  Nice idea! 
Would you mind sharing how do you _currently_ figure out what areas need housenumbers **on a PC**?

> What you could do instead if you want to complete housenumbers is to activate the building type quest and the address quest. These appear automatically where information is missing.

That workaround approach is however likely quite problematic, because:
-  as you note, one needs to _also_ enable `building type` quest, and that is going to give [a lot of false positives](https://overpass-turbo.eu/s/1GgK) for places which has addresses mapped but buildings are only tagged `building=yes` (and one unfortunately cannot enable _just_ `address` quest due to https://github.com/streetcomplete/StreetComplete/issues/2464)
- heatmaps are usually employed at more zoomed-out levels to be useful in use cases like this, and that would require that mapper have firstly manually downloaded in StreetComplete _all the areas they wanted to check_ (which would likely be very time consuming and impractical, esp. due to maximum download area limits)

> Hm well, this is not possible with the map render library we use (tangram-es).

What might be more easily possible [^1] is to allow to switching to alternate (or additional) map provider / map overlay. For this particular use case, https://qa.poole.ch/ has **_"no address"_ overlay**, which seems to be what @RedAuburn would want.

Although showing alternate map has been proposed before in StreetComplete (i.e. https://github.com/streetcomplete/StreetComplete/issues/56), I'm not sure if it such customizable TMS URL would be good fit for vanilla StreetComplete (being oriented toward newbies etc.) But perhaps hardcoding that one specific overlay as a preference (or automagically when only building type+Addresses quests are enabled?)  might be acceptable solution -- as I do agree that it is very worthy use case, which I would like to use too. But I'm also not 100% sure if Tangram-ES supports base layer + overlay layer display at once?


[^1]:  especially in [SCEE](https://wiki.openstreetmap.org/wiki/SCEE) fork, as it already has alternate map. Although it is currently hardcoded to Esri aerials, I guess it would not be too much work to allow custom TMS to be used. Even better would be for allowing multiple underlay/base/overlay layers (like [Vespucci](https://wiki.openstreetmap.org/wiki/Vespucci) does), but that might be taking this too far...
