### ISSUE TITLE
Quest: Has this toilet free menstrual products available?

### ISSUE THREAD

**Issue by moan0s** [streetcomplete/StreetComplete#5485]
### General
Affected tag(s) to be modified/added: [Key:toilets:menstrual_products](https://wiki.openstreetmap.org/wiki/Key:toilets:menstrual_products)
Question asked: **Has this toilet free menstrual products available?**
* `yes`: A toilet has menstrual products available for everyone that uses the amenity.
* `limited`: Parts of the toilet have menstrual products available (e.g. menstrual products are only available in women-only stalls)
* `no`: no menstrual products are available

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/blob/master/QUEST_GUIDELINES.md)):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [ ] 🐿️ Easily answerable by any pedestrian from the outside but a survey is necessary
- [x] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of map data (Worth the effort)

To answer the first question fully: This tag is newly created after community debate and a previous suboptimal solution (tagging via vending machine). It was approved via the proposal process and is therefore established as I'd understand. A counterargument can be made that the tag is not used a widley yet.

The quest would not be able to be easily answerable by any pedestrian so I'd suggest to disable it by default [as done for wheelchair access](https://github.com/streetcomplete/StreetComplete/issues/1391)

Regarding the last two questions: I think the answer to these depend on the region. Some jurisdictions require menstrual products in toilets \[[1](https://www.gov.scot/policies/poverty-and-social-justice/access-to-free-period-products/)\]\[[2](https://www.swr.de/swraktuell/baden-wuerttemberg/kostenlose-tampons-karlsruhe-heidelberg-tuebingen-100.html)\], and in some others this will be unheard of. I don't know how granular an activation of a quest can be but ideally I'd activate it in germany and Scotland only to see how users deal with it. 

### Ideas for implementation

**Element selection:**
I guess this would be every `amenity=toilet`? But i might misunderstand

**Metadata needed:** I don't thinks so?

**Proposed UI:**
![UI mockup](https://github.com/streetcomplete/StreetComplete/assets/25753802/605b2c24-5827-4efe-836a-697e6329aaaf)

The second picture is licensed under CC-BY-SA by @macst3r@mastodon.social

### Development

I could see myself diving in and trying to implement this quest but I happily let others have the fun if they feel like it! In any case I'll wait for a bit of feedback here before starting.

**Comment by matkoniecz** [comment]
> Easily answerable by any pedestrian from the outside but a survey is necessary

Note extra complexity that you need to survey both female and male stalls to answer that fully.

Not sure should SC ask to do that....

**Comment by moan0s** [comment]
> Note extra complexity that you need to survey both female and male stalls to answer that fully.

Yes I am aware of that and I know this will be one of the harder tasks. A similar problem is with changing tables where SC asks for the location. What do you think about adding a disclaimer like this?

> Only enter bathrooms where you are comfortable and allowed in.

This doesn't help the mapper much in completing the task but it makes them feel they "play the game right" even though they don't answer the quest and we don't encourage unwanted behavior.

**Comment by westnordost** [comment]
Hm, the possibility to disable quests by default was never meant as a method to bypass the quest guidelines in parts. And anyway, it looks like, there are more guidelines that are not met:

> 🚧 To be added tag is established and has a useful purpose

- It is not established at all. In general, new tags should not be pushed by StreetComplete.

- The useful purpose would only (theoretically) exist when this feature was mapped comprehensively because only then there'd be a chance that this feature would be included in popular map apps and one could theoretically explicitly search for toilets with that feature and have success doing so. That this is entirely unrealistic even when disregarding the hen and egg problem is revealed by the fact that the vast majority of toilets are not actually mapped (yet) on OSM - toilets in restaurants, cafés etc.. Incidentally, I expect that the chance for these to have such a feature (out of hospitality) is quite a lot higher than for public toilets.

- The tag itself describes a pretty volatile feature - whether or not such a box is supplied could change from day to day, just like whether hand sanitizer is available (and not empty) or even if there's (enough) toilet paper. Granted, the comparison with toilet paper is hyperbole, but it should illustrate that its volatility leads to a problem with the _verifiability_ and effort to _maintain up-to-dateness_ of this feature - after all, it should not be retagged to `no` only because coincidentally that one day the box was missing.
  (The wiki article shows a photo of a vending machine, this would be non-volatile, however, I suggest to rather tag such things as `amenity=vending_machine` with the appropriate subtag rather than trying to tag the presence of it on every single toilet )

> 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)

If the user spotted such a feature in the women's toilet but not the ante-room, would it be `limited`? Or would the user also have to check the men's toilet? Previous comments seem to suggest that they'd have to check the men's toilet too, although that makes no sense to me.

If this is true however, then this quest guideline can also not be met, because women just checking the women's toilet wouldn't be able to answer "yes" or "limited" because the tagging schema demands that you check everywhere. So, it would only be answerable for the owner. 

> 🐿️ Easily answerable by any pedestrian from the outside but a survey is necessary

- Not answerable from outside.

> 💤 Not an overwhelming percentage of quests have the same answer (No spam)

- No experience here, of course. I asked a friend how often it exists, she told me (sic) "never....! Very, very rarely, ... almost never". May vary by region, of course.

----

So, there are several reasons why this cannot be a quest. If you are interested in mapping and promoting to map such things, I propose you rather stick to mapping [`amenity=vending_machine` + `vending=feminine_hygiene`](https://wiki.openstreetmap.org/wiki/Tag%3Avending%3Dfeminine_hygiene) instead, it doesn't have the issues described above.

**Comment by matkoniecz** [comment]
> The values were chosen after various discussions in the community to make mapping in a variety of situations possible.

Maybe splitting this tag into two independent parts would make more sense, to enable survey without going into both section or asking others for help (though that would not exactly solve SC problem)

**Comment by matkoniecz** [comment]
> SC could also decide to only activate the feature on gender neutral/unisex toilets.

Good point though some of other concerns remain
