### ISSUE TITLE
Add ability to add power substation with things overlay

### ISSUE THREAD

**Issue by Jean-BaptisteC** [streetcomplete/StreetComplete#5503]
**Use case**
In France, we have minor substations too tiny to be draw with building or integrated inside a building
Some examples here:
- https://wiki.openstreetmap.org/wiki/File:20140501_165031.jpg
- https://wiki.openstreetmap.org/wiki/File:French_substation_pssb.jpg
- https://commons.wikimedia.org/wiki/File:Transformateur_immeuble_Palaiseau.jpg
- https://www.enwl.co.uk/globalassets/safety--incident-reporting/images/images/substations2.jpg

**Proposed Solution**
I suggest to give ability to add power substation with things overlay.

**Comment by westnordost** [comment]
`power=substation`? Doesn't look like it is eligible.

See the description in https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/osm/Things.kt

Mainly because according to the [wiki page](https://wiki.openstreetmap.org/wiki/Tag:power=substation), also larger substations that rather classify as landuses than "things" also full under `power=substation`. This is the reason why `man_made=antenna` is also not included, because while a small antenna for mobile network on top of a roof might classify as a "thing", the tag also includes antennas that rather classify as structures.

Also, even the pictures you link rather look like a structure to me, i.e. rather should go into the buildings overlay. Which they are already implicitly because `building=service` is included.

What could go into the things overlay would be `man_made=street_cabinet`.

**Comment by westnordost** [comment]
Ping @matkoniecz : Why is `man_made=street_cabinet` not included, by the way? Why do you think it is so similar to a post box?

**Comment by matkoniecz** [comment]
I will need to recheck it but I am pretty sure that it is included

And post boxes were skipped only because of id preset issues specific to them

**Comment by Jean-BaptisteC** [comment]
Yes street cabinet are included in things overlay

**Comment by matkoniecz** [comment]
Oh  right - it is disabled. That is because one of street cabinets has post box role

**Comment by matkoniecz** [comment]
I made https://github.com/streetcomplete/StreetComplete/commit/4cc2e2aaf190906654cfb3d131608069a1cb6b9c to reduce confusion. Likely can be made better

**Comment by westnordost** [comment]
Ah right. So, power-"street cabinets" are already included. This concludes this issue from my point of view.
