### ISSUE TITLE
Overlay Dinge

### ISSUE THREAD

**Issue by woodyBu** [streetcomplete/StreetComplete#5543]
die neue Funktion "Dinge" macht in meinen Augen keinen Sinn solange man keine Luftaufnahem einblenden kann. Die so eingetragenen Objekte liegen zum Teil soweit weg vom eigentlich Standort, das es einfach sinnlos ist damit zu arbeiten. Das ist doch nur raten.

**Comment by matkoniecz** [comment]
Are you being unable to use them or are you complaining about low quality of edits being made with it?

(I am using it in well mapped area where you can reliably position things using already mapped features such as buildings)

**Comment by Helium314** [comment]
In my experience when surrounding geometry is mapped with reasonable accuracy, placing objects within 2-3m can be done rather easily.

**Comment by HolgerJeromin** [comment]
Aerial images can (in the sense of: nearly always) have an offset. 
So using them would give a false feeling of accuracy.

**Comment by westnordost** [comment]
Right, so to summarize, without a satellite imagery the overlay still makes sense, as you see your own location including the GPS accuracy, buildings and other street furniture on the map to locate where things should go. 
That having said, nothing speaks against implementing being able to choose aerial imagery as background map in StreetComplete. It just has to be done by someone. I believe there is an open ticket for that around somewhere.
(In case you or someone else feels this is a good motivation to work on it right now, please post your intention first in that ticket, because there are a few things to consider before starting with that task I will write about then.)

**Comment by HolgerJeromin** [comment]
> I believe there is an open ticket for that around somewhere.

ref #56
