### ISSUE TITLE
Decrease resurvey interval of `amenity=taxi`

### ISSUE THREAD

**Issue by Dimitar5555** [streetcomplete/StreetComplete#5546]
Currently `amenity=taxi` is surveyed once every 10 years (according to https://github.com/streetcomplete/StreetComplete/blob/4435ec4267f5af8a38e37be057ef97e884becea0/app/src/main/java/de/westnordost/streetcomplete/quests/existence/CheckExistence.kt#L68-L72). Maybe it should be moved down to 2 years? For context, in some countries taxi stands are literally a sign on a stand and can be moved in very little time.

![image](https://github.com/streetcomplete/StreetComplete/assets/19364673/ecc54cef-779a-4b90-860e-78f47dbb5ba8)

**Comment by matkoniecz** [comment]
How often it is answered as not existing, depending on time since it was last edited?

In https://github.com/streetcomplete/StreetComplete/commit/47f41be11cf7a65165a96d4fbdaeff78026779d3 I actually checked this and adjusted check time from 12 to 10.

Code to create statistics was a bit silly and inefficient but if anyone wants to rerun analysis I can find and share it.

Also, if anyone wants - feel free to run own analysis. Maybe situation changed since then. But I would not expect that asking earlier would make a lot of sense.

I will close it, feel free to open new one if it is based on some analysis of how often people answer that these features are gone. (it turns out that actual global answer patterns does not really match what I expected from my local area)

> For context, in some countries taxi stands are literally a sign on a stand and can be moved in very little time.

The question is how often mapped ones are actually moved without being updated in OSM, which may give a different answer.

Closing as already done. Though more analysis is welcome.

**Comment by FloEdelmann** [comment]
Also note that you can shorten the resurvey intervals for yourself only in the app settings.

**Comment by matkoniecz** [comment]
Though this works on all quests, so if someone is in area where they want to adjust only taxis only forking remains as an option... (unless you could somehow do it in SCEE?)

**Comment by mnalis** [comment]
> [...] unless you could somehow do it in SCEE?

Yes, [SCEE](https://wiki.openstreetmap.org/wiki/SCEE) (StreetComplete _"Expert Edition"_ fork) does allow editing quest query by user in the quest settings, and thus changing taxi resurvey interval too, so @Dimitar5555 may want to try that. SCEE can coexist with regular StreetComplete without any ill affects, and by default looks pretty much the some as regular SC, just with more options in preferences. But you can enable all kinds of extra things and more powerful (and more cluttered :smile: display) _if you choose to do so_.

For this particular case, one would go to `Quest selection and display order`, find green `Is it still here?` quest (there is a brown one too!) and after clicking a gear ( :gear: ) icon on it, one can change its query:

![small_Screenshot_20240322_124910_SCEE](https://github.com/streetcomplete/StreetComplete/assets/156656/c6eb78d6-f32c-4bee-b77b-771624702023)

So simply changing those six `-10 years` to `-2 years` below _"taxi"_ would be easiest, but would affect bicycle and motorcycle parkings too and not just taxi stands (but of course one could also split that query part to two different ones - one for bicycle/motorcycle parkings and one for taxi stands, but with different resurvey interval -- but of course, the more changes one wants, the more complex it becomes)
