### ISSUE TITLE
Misleading display for historic buildings in building overlay

### ISSUE THREAD

**Issue by gdabski** [streetcomplete/StreetComplete#5547]
**How to Reproduce**
Find a building tagged with `building=*` and `historic=yes`, e.g. [1831089](https://www.openstreetmap.org/relation/1831089). Open the buildings overlay. Note that the building is displayed in grey, with the type described as _Historic: building of historic value, constructed for an unknown or unclear purpose_.

Change building type, perhaps even to the one corresponding with the already existing `building=*` tag. Observe after uploading changes that the `historic=yes` tag is gone.

**Expected Behavior**
Contrary to the description hinting at _an unknown or unclear purpose_, the type of building is precisely specified in existing tags. The building should be displayed in SC according to the building type specified in `building=*`. The value for `historic=*` should not be altered when using the SC buildings overlay.

**Versions affected**
SC 57.1.

**Comment by westnordost** [comment]
The description provided in "expected behavior" doesn't sound like a good solution to me, as then, it would be possible to *add* `historic=yes`, but not remove it again if one selects another type (for whatever reason, e.g. realizing a mistake, realizing that actually it isn't historic at all but only looks like it etc.). That handling would also be inconsistent when compared to e.g. `ruined=yes` - surely, `ruined=yes` should be removed when selecting another building type?

The best solution would be #5506 I think, i.e. have two fields - "it used to be... X" and "and it is now... Y" (e.g. "it used to be a civic building and now it is historic")

As long as that is not implemented, I would propose to change the description instead, make it either "Historic: building of historic value" or  "Historic: building of historic value, regardless for which purpose it was constructed."

**Comment by gdabski** [comment]
I don't really get why a historic building cannot be an `apartments`, `hotel`, `office` or `detached` building at the same time. To me, `historic` is a value in a completely different enumeration and something like _it used to be a civic building and now it is historic_ doesn't really make sense. The shape of the building doesn't change just because we begin to consider it historic at some point.

> The description provided in "expected behavior" doesn't sound like a good solution to me, as then, it would be possible to add historic=yes

Maybe I didn't make myself clear, but I would not have SC touch the `historic` tag at all. Or at least not in (the current shape of) the buildings overlay, as one of options for building type. If it was to be editable, for me it would be something like a checkbox next to the building type.

**Comment by westnordost** [comment]
> Maybe I didn't make myself clear, but I would not have SC touch the historic tag at all. Or at least not in (the current shape of) the buildings overlay, as one of options for building type. If it was to be editable, for me it would be something like a checkbox next to the building type.

Well, this comes from the building quest, which asks which kind of building this is. For historic buildings, it is difficult to say, so that's why the _"Historic: building of historic value, constructed for an unknown or unclear purpose."_-option was added then.

Do you think it made sense if the option was shown only for the quest, but not for the overlay? It might feel somewhat like a bug / inconsistent (but I do understand where you are coming from).

**Comment by gdabski** [comment]
I don't know about the quest, because I disabled it long ago for the very reasons that made you implement the overlay :sweat_smile: 

I perfectly agree that for buildings from before the era of modernism in architecture you often need to be a PhD in architecture or local historian to correctly describe the building types. I would myself not allow users to just slap `historic` and move on. 

But that is not even the point of the bug report. I wanted to understand why a `building=apartments` + `historic=yes` is coloured gray not blue in the overlay. And why is `historic=yes` getting removed when I choose _flats_ as a building type for that building in the overlay.

**Comment by westnordost** [comment]
So maybe "historic" should not be selectable in the overlay. Instead, buildings with `historic=yes` and `building=yes` should be displayed as red and the overlay does not touch that tag.
The building quest on the other hand needs this option to discourage users from guessing the building type when they have no idea, because it is a historic building whose original purpose is unknown or unclear to the user.

**Comment by matkoniecz** [comment]
> I don't really get why a historic building cannot be an apartments, hotel, office or detached building at the same time. 

It can have! This option existed as option in building quest for cases where building type is very unclear but it is clear that building is historic.

And yes, it is not ideal that right now in overlay you cannot make `building=*` more specific for `historic=yes` buildings.

> Instead, buildings with historic=yes and building=yes should be displayed as red and the overlay does not touch that tag.

+1, just ignore `historic=yes` in overlay (at least until #5506)

**Comment by westnordost** [comment]
Question, what about buildings tagged with `abandoned=yes` and `ruins=yes`? Should this also not be selectable?

**Comment by westnordost** [comment]
ping. What do you think?

**Comment by matkoniecz** [comment]
> Question, what about buildings tagged with abandoned=yes and ruins=yes? Should this also not be selectable?

Ideally? There would be an option to still mark their form and not remove `abandoned=yes` `ruins=yes`

But making them uneditable for now makes sense. Maybe allow selecting which would allow showing their situation?

**Comment by westnordost** [comment]
I mean, if the same solution is applied for these, they would be selectable in the quest but not in the overlay.
In the overlay, buildings tagged with abandoned or ruins would be shown as red (information missing)

**Comment by westnordost** [comment]
Alright, in the end I made it so that _historic_ is still selectable in the overlay for consistency with the quest, but selecting a different building type when _historic_ was selected before does not delete `historic=yes` but instead just adds the selected building type. Specifically selecting _historic_ will also set `building` to `yes`.

This is because the description of the _historic_ option in SC is _"building of historic value, constructed for an unknown or unclear purpose"_.
