### ISSUE TITLE
Don't use disused:shop=yes on non-shops

### ISSUE THREAD

**Issue by Discostu36** [streetcomplete/StreetComplete#5548]
When an amenity, healthcare facility, etc. is closed, SC adds `disused:shop=yes`. See, for example, [here](https://www.openstreetmap.org/node/7043155278/history). This is adding wrong data, as the lifecycle prefix should match the former tag.

**How to Reproduce**

I guess this happens every time that you mark a location as vacant.

**Expected Behavior**

The (former) main tag of the facility should be altered by adding a `disused:` in front, like [explained in the wiki](https://wiki.openstreetmap.org/wiki/Lifecycle_prefix).

**Versions affected**

SC 56.0, probably also later, there was no mention in the changelogs.

**Comment by Discostu36** [comment]
If you want to avoid using the value because it could be incorrect, as @matkoniecz argued in https://github.com/streetcomplete/StreetComplete/issues/2707#issuecomment-816471983, at least the key should be preserved, e.g. `disused:amenity=yes`.

**Comment by westnordost** [comment]
This is more of a missing feature than a bug, but I agree, it should be done. (Or, use `shop=vacant` after all.)

Unfortunately, the code for this is quite scattered right now and assumes that tags like `disused:amenity` (...office, club, craft, ... ) are not used, so this all should be handled in a newly to be defined function named e.g. `fun makeDisused(tags: Tag)` or similar in `de/westnordost/osm/Lifecycle.kt` (or similar).

**Comment by matkoniecz** [comment]
> This is more of a missing feature than a bug, but I agree, it should be done. (Or, use shop=vacant after all.)

If `disused:shop=yes` is bad in case of emptied amenity then surely `shop=vacant` is also bad?

For shop-like amenities `disused:shop=yes` seems not worse than `disused:amenity=yes` to me.

**Comment by Helium314** [comment]
For disused amenities I think it's be better to keep the value. `disused:amenity=yes` could also be a disused waste bin, vending machine or car park.

**Comment by matkoniecz** [comment]
That runs into problem that `disused:amenity=doctor` claims that there are still visible remains of doctor office there.

**Comment by westnordost** [comment]
> That runs into problem that disused:amenity=doctor claims that there are still visible remains of doctor office there.

Can you link to the documentation that claims this? I didn't know that remains of the previous place need to be visible for `disused:shop=*` to be tagged.

**Comment by matkoniecz** [comment]
OK, they do not be visible by surveyor but they still need to be there. If there are no traces at all then it no longer qualifies. And asking user about this seems to much. See https://wiki.openstreetmap.org/wiki/Key:disused:amenity and https://wiki.openstreetmap.org/wiki/Lifecycle_prefix and https://wiki.openstreetmap.org/wiki/Key:disused:*

(I have not edited too much this pages IIRC)

**Comment by westnordost** [comment]
Right. I read this as - in this case - the shop _space_ still exists.

**Comment by matkoniecz** [comment]
I would say *shop space* still exists - if everything like signs and equipment was scrubbed and former bakery cannot be distinguished from former doctor office, then it is not say `disused:amenity=doctor`

**Comment by westnordost** [comment]
Err, I am at a loss. Can you cite the documentation that claims this? And if so, how do you propose to project that into StreetComplete?

**Comment by Discostu36** [comment]
I also can't find in the documentation that a `disused:` shop or amenity must still be recognizable as this specific kind of feature. 

If we wanted to be very exact whe could, in a case where a user selects that the feature isn't there anymore, ask, if there are any traces left (e.g. a vacant shop) or not (e.g. it has been turned into an apartment). For the latter case you could use `abandoned:` instead. 

But maybe this is more complex than necessary. I don't see a problem if SC used `disused:` in a case where another lifecycle prefix might be more fitting. The main purpose of these prefixes is to remove objects from the map temporarily, it is in my opinion not very important that the exact prefix is used.

**Comment by westnordost** [comment]
Right, fine. So, it is irrelevant for us, and so is this discussion. In the app you can state that it is _vacant_ now. If the place was ruined now, i.e. the building it was contained within is ruined, then nobody would answer that it is _vacant_ now.

The cited sentence does not mean that it must be recognizable as an ex-bakery, an ex-doctors' office or whatever.

**Comment by westnordost** [comment]
I am contemplating whether to return using `shop=vacant`. The tag is not going to go away, after all, so might as well use it. Its meaning is more broad, i.e. other than `disused:shop=yes` I'd say it includes

- shops that have always been vacant (e.g. newly constructed shops), i.e. never had a tenant

- it describes the shop space being vacant, i.e. the **now**, rather than what it was **before** (`disused:*`)

**Comment by mnalis** [comment]
If you're looking for a feedback, I do not like either `shop=vacant` _or_ (hardcoded) `disused:shop=yes`. For example, I am asked if `tourism=guest_house` is still here, and when I answered `no`, it got tagged `disused:shop=yes`. 

That is highly misleading (one might even argue it's flat out incorrect), as this issue notes, and the situation wouldn't be any better if it was tagged `shop=vacant` instead... 

**I'd much rather if just `disused:` prefix was prepended to main tag** (i.e. `amenity`, `shop`, `tourism`, `leisure`?), e.g. in this case if it become `disused:tourism=guest_house` instead of `tourism=guest_house` . If is probably little more work, but I guess not much so, and for someone with command of Kotlin those maybe dozen lines of code would produce code which would IMHO be **much better** --- IOW not only more precise (which is always good thing IMHO), but more importantly it wouldn't blatantly lie and misrepresent the situation.

![small_Screenshot_20240616_012543_StreetComplete](https://github.com/streetcomplete/StreetComplete/assets/156656/48d1e3bc-ec58-47f5-bc83-a1a9d03e8475)


>  shops that have always been vacant (e.g. newly constructed shops), i.e. never had a tenant

But, if it has _**always**_ been vacant, then StreetComplete will never change it's tagging anyway (to either `shop=vacant` _or_ `disused:shop=yes`), so I don't think it applies to SC use case, right?

> it describes the shop space being vacant, i.e. the **now**, rather than what it was **before** (`disused:*`)

Well, it abuses the tag (in many cases). Guest house which is no longer available for rent is hardly _"vacant shop space"_ **now**.

**Comment by matkoniecz** [comment]
`disused:tourism=guest_house` this would be also wrong if space would be emptied to the point being generic empty commercial space, rather than being empty, currently unused, guest house

**Comment by westnordost** [comment]
Alright.

**Comment by natrius** [comment]
I just would like to add the discussion of https://community.openstreetmap.org/t/welche-fragen-stellt-streetcomplete-wem/114863/ about `amenity=school` turned to `disused:shop=yes` to be complete and because nobody else has done so. 

Thanks for all your work!
