### ISSUE TITLE
"Bollard" is called "Bollard Row"

### ISSUE THREAD

**Issue by wielandb** [streetcomplete/StreetComplete#5549]
**How to Reproduce**
Select an instance of the quest "What kind of bollard is this?". You will be asked "What kind of bollard is this?", and in the object description, the bollard will be called "Bollard Row". Other bollards in the vicinity will also have the bollard row icon.

| ![photo_2024-03-24_01-18-45](https://github.com/streetcomplete/StreetComplete/assets/29458682/757682b2-b905-4726-ac2d-28205c087415) | ![photo_2024-03-24_01-18-47](https://github.com/streetcomplete/StreetComplete/assets/29458682/25d8b4cb-7eab-4bd4-9f74-d2c795dccd9d) |
|:-:|:-:|

**Expected Behavior**
The bollard will be called bollard and other bollards will have the bollard icon.

**Additional info**
- `barrier=bollard` is somewhat special in that it should receive different names depending on how it is used. A node with `barrier=bollard` should be called "Bollard" (also if it is a node that is part of a way). But a way itself with the tag should be called "Bollard Row"
- I noticed this first in the german translation, but it's the same in english, so I don't think it's a problem with the translations
- I thought it may be a problem in the `id-tagging-scheme`, but ID will correctly call a node "Bollard" and a way "Bollard Row"
- My best guess is that maybe SC incorrectly thinks a node that has `barrier=bollard` that is _part of the way_ is the same as _beeing the way_ that has the tag and so thinks bollard row is the appropriate string.

**Versions affected**
Observed in v57.1

**Comment by westnordost** [comment]
The issue is that iD presets distinguish nodes and vertices (= nodes of ways) while StreetComplete (doesn't have the data model to) distinguish these. So, when looking which `Feature` matches a set of tags on an element and the element is of type `Node`, it does not constraint the search to only nodes, because the given `Node` could be a vertex, too

https://github.com/streetcomplete/StreetComplete/blob/4435ec4267f5af8a38e37be057ef97e884becea0/app/src/main/java/de/westnordost/streetcomplete/util/ktx/FeatureDictionary.kt#L13-L14

Since changing the whole data model is out of the question, to be honest, I am unsure how to solve this.

**Comment by pkoby** [comment]
If SC doesn't pull directly from the presets and it can be manually adjusted, could this be labeled "Bollard(s)" and equivalents in different languages?

**Comment by westnordost** [comment]
It does pull directly from the presets.

**Comment by matkoniecz** [comment]
>  So, when looking which Feature matches a set of tags on an element and the element is of type Node, it does not constraint the search to only nodes, because the given Node could be a vertex, too

Maybe we can prefer Node over Vertex over anything else?
