### ISSUE TITLE
New type of public well

### ISSUE THREAD

**Issue by kaboca77** [streetcomplete/StreetComplete#5560]
**Use case**
Almost all settlements in Hungary have many public wells. They all have the same design, they are the "blue public wells". It would be great if we could record them with a single click. (Photos: https://www.google.com/search?q=k%C3%B6zk%C3%BAt&tbm=isch )

**Proposed Solution**
A new picture by the "Drinking water" question with this data:
amenity=drinking_water
man_made=water_tap
colour=blue
dog=designated
seasonal=spring;summer;autumn
bottle=yes
handle=lever

**Comment by HolgerJeromin** [comment]
Please see these old issues:
#5329

**Comment by matkoniecz** [comment]
> It would be great if we could record them with a single click.

Where? In things overlay? Somewhere else?

**Comment by matkoniecz** [comment]
> Please see these old issues:

I think they are not proposing photo collection

**Comment by 66zio66** [comment]
I would not include dog=designated and seasonal=spring;summer;autumn as not all well is good for dogs to drink (there is a bowl) and which are, the bowl is not there because of the dogs. There is a hole in it where the water can escape.
The seasonal tag is almost the same issue. There are wells which works in the winter too, etc.

**Comment by westnordost** [comment]
For the drinking water quest, we are not going to implement drinking water wells this specific as options within the app, sorry.
