### ISSUE TITLE
Enable Tactile Paving quest in Colombia 

### ISSUE THREAD

**Issue by oyes77** [streetcomplete/StreetComplete#5579]
Tactile Paving is disabled in Colombia, however it is present in multiple capital cities so it's worth enabling. *Examples are Bogotá and Medellín, from where I can contribute.*
![Screenshot_20240413_153402_StreetComplete](https://github.com/streetcomplete/StreetComplete/assets/53545025/92b26326-8beb-4755-9bc0-eaba2ab8c858)

**Comment by mnalis** [comment]
related: https://github.com/streetcomplete/StreetComplete/issues/5129

**Comment by westnordost** [comment]
> Examples are Bogotá and Medellín, from where I can contribute.

What examples? I don't see any. Could you linke some pictures from Google StreetView or similar? Also,

To enable this quest and not violate the "No spam" rule, neither "yes" nor "no" should be the correct answer in more than 90% of all quests. Do you think this is realistic?

**Comment by oyes77** [comment]
I think that it's realistic that "yes" or "no" would be a correct answer as that is a city effort to add tactile pavement throughout the main streets, so either full streets have them, or they don't, the hoods still haven't in many cases, that's why I think it's important to clarify where there is and isn't tactile pavement, a variable I've seen as a pattern is that those pavements have their yellow paint worn off/wasn't painted in, though.

https://www.google.com/maps/@6.2607296,-75.5690658,3a,41.1y,181.87h,77.37t/data=!3m6!1e1!3m4!1sHy17YdjbnkkJgYb2gjwiFA!2e0!7i16384!8i8192?entry=ttu

https://www.google.com/maps/@6.2754036,-75.5644911,3a,75y,339.12h,20.67t/data=!3m6!1e1!3m4!1sRLPkhQDKsZ5BDSPsA4TnHg!2e0!7i13312!8i6656?entry=ttu

https://www.google.com/maps/@6.2778518,-75.5720737,3a,15y,75.62h,77.53t/data=!3m6!1e1!3m4!1sH0_ABsVkN8ZbnTTWDQktyQ!2e0!7i16384!8i8192?entry=ttu

https://www.google.com/maps/@4.7117421,-74.070496,3a,71.3y,269.89h,71.2t/data=!3m6!1e1!3m4!1sh20hz3TQdW6ilYdmG2wi3w!2e0!7i16384!8i8192?entry=ttu

https://www.google.com/maps/@4.7337608,-74.0629191,3a,18.9y,194.9h,82.52t/data=!3m7!1e1!3m5!1sipODqNJs1v15s-F5i9PxWA!2e0!6shttps:%2F%2Fstreetviewpixels-pa.googleapis.com%2Fv1%2Fthumbnail%3Fpanoid%3DipODqNJs1v15s-F5i9PxWA%26cb_client%3Dsearch.revgeo_and_fetch.gps%26w%3D96%26h%3D64%26yaw%3D1.5188352%26pitch%3D0%26thumbfov%3D100!7i16384!8i8192?entry=ttu

**Comment by mnalis** [comment]
Hmmm @oyes77 I think there is some misunderstanding here. There is ***no*** StreetComplete Quest to tag whether pavement/sidewalk/footway has tactile paving (for any country, not just Colombia), so that cannot be enabled as it does not exist. That might be an idea for some new [Overlay](https://github.com/streetcomplete/StreetComplete/blob/master/OVERLAY_GUIDELINES.md), but it does not exist yet.

There ***are*** several [StreetComplete Quests](https://wiki.openstreetmap.org/wiki/StreetComplete/Quests) related to tactile paving:
1. _"Does this stop have tactile paving?"_ - only asked for public transport stops
2. _"Does this crosswalk have tactile paving on both ends?"_ - only asked for pedestrian crosswalks
3. _"Is there tactile paving at the top and bottom of these steps?"_ - only asked on top and bottom of steps
4. _"Is there tactile paving on this curb here?"_ - only asked on manually mapped curb/kerb

So the question is which of those 4 specific Quests (if any) would make sense to be enabled in Colombia?

Note that [Quest Guidelines](https://github.com/streetcomplete/StreetComplete/blob/master/QUEST_GUIDELINES.md) asks among other thing this:

- _💤 No spam: It must be possible to determine whether the quest should reasonably be asked. A quest which is to be answered in 99% of the time with the same answer is not a good quest, don't bore the users. I.e. asking for any road if it is a one-way road, is silly, because the vast majority of all roads will not be one-ways._

So, for example, if 99% of pedestrian crosswalks in Colombia **have** tactile paving, then it is **bad** quest, as it will "spam" the user, making them question why the app is needlessly wasting user time for something that is obviously almost always there (and likely resulting in the user uninstalling the StreetComplete to everyones loss). But, as another example, if 99% of public transport stops **don't have** tactile paving, then it is equally **bad** quest, as the user will wonder why they have to answer "no" all the time for something that basically never exists.

---

I hope I had managed to clarify. 

So what we'd like from you @oyes77 (as someone who has experience in Colombia) is to tell us your estimate, for each of the 4 Quests above, would the answer `yes` be in the range `10%`-`90%` of the cases, or outside it (i.e. below `10%` _or_ over `90%`).

**Comment by westnordost** [comment]
Interesting, I haven't seen such a complete tactile paving along the sidewalk before. Ironic, though, that at least in this example, there is this tactile paving along the sidewalk, but neither at the bus stop nor at the crossing %-)

https://www.google.com/maps/@6.2761815,-75.564352,3a,75y,30.72h,78.42t/data=!3m6!1e1!3m4!1sHQVPDJNrfxkelaxxE5x-YQ!2e0!7i13312!8i6656?entry=ttu

**Comment by oyes77** [comment]
Thanks for the clarifications.

*"Does this stop have tactile paving?" - only asked for public transport stops*in Medellín, many have, not so many in Bogotá,  outside those two cities, so smaller cities, don't have at all in my experience, I think that's inside the 90-10 rule in those cities specifically.
*"Does this crosswalk have tactile paving on both ends?" - only asked for pedestrian crosswalks* they do have in both ends, if you mean through the crosswalk, I've never seen that, I'd include it into the 90-10 rule.
*"Is there tactile paving at the top and bottom of these steps?" - only asked on top and bottom of steps* most steps don't have tactile paving. So it's outside the 90-10 rule.
*"Is there tactile paving on this curb here?" - only asked on manually mapped curb/kerb* there is tactile paving on curbs, it's inside the 90-10 rule.

It's important to note that there's "blocks" of the city that have tactile paving in most places, and other (usually more residential blocks or not central in general) that luckily have any, so regarding user experience, there is still the case that in 99% of their inmediate surroundings, the answer will always be yes or no.

**Comment by westnordost** [comment]
Unfortunately, we can only enable the quest on a per-country basis, not on a per-city or even per-province basis. Also, I just had a look at the code, and actually we either enable all these four quests or none, per country. Currently, it is enabled in the following countries:

https://ent8r.github.io/blacklistr/?data=NO,SE,DK,SI,GB,IE,NL,BE,FR,ES,IT,DE,PL,CZ,SK,HU,AT,CH,LV,LT,EE,LU,RU,HR,PT,US,CA,AR,HK,SG,KR,JP,AU,NZ

Given this information, considering we don't want to bore your fellow Columbian StreetComplete mappers with pointless quests, would you say that the quests should be enabled in Columbia at this time?

**Comment by oyes77** [comment]
I wrote a mail to the INCI (Colombian National Blindess Institute) regarding this, hopefully they facilitate me reliable information about this, so I can say with more confidence wether enable it or not.

**Comment by westnordost** [comment]
Oh, that's... cool! FWIW, for me, your personal assessment as a Columbian resident would also be enough.

**Comment by oyes77** [comment]
Hi! I haven't got a significant response from them, only that my request was recieved, and is being currently processed. 
As far as my personal assessment goes, I do think that it's worth it to enable the quest, thanks ^^

**Comment by westnordost** [comment]
Well, then let's do that then.
