### ISSUE TITLE
Awards and links has disappear

### ISSUE THREAD

**Issue by Jean-BaptisteC** [streetcomplete/StreetComplete#5580]
**How to Reproduce**
- Start app
- Go to your profile -> awards and links is not present (you need to scroll in blank space to see awards and links)

**Expected Behavior**
- Awards and links is visible when we switch to their tab

**Versions affected**
Android 14 - v57.2

**Comment by westnordost** [comment]
Hm yeah, can reproduce. It kind of feels like a bug in RecyclerView. A quick search turns up 
https://stackoverflow.com/questions/45167282/recyclerview-doesnt-show-items-until-scrolling

However, maybe the awards and links should just be one of the first things I migrate to Jetpack Compose framework, instead of fixing code that is going to be thrown out, anyway.

**Comment by westnordost** [comment]
Will be fixed when I merge the compose1 branch because these views are the first ones I migrated to Jetpack Compose.

**Comment by westnordost** [comment]
Fixed by #5607
