### ISSUE TITLE
Poor positions when adding hints/notes

### ISSUE THREAD

**Issue by sjvudp** [streetcomplete/StreetComplete#5581]
**How to Reproduce**

Walk along, place an OSM hint/note.
After upload to OSM, the hints are significantly misplaced, For example: #4191986, #4191985
Maybe the reason is that position updates are seemingly "damped" a lot

**Expected Behavior**

Hint will be filed with correct "long-tap position"

**Versions affected**

v57.1

**Comment by matkoniecz** [comment]
https://www.openstreetmap.org/note/4191986 https://www.openstreetmap.org/note/4191985

**Comment by westnordost** [comment]
Can not reproduce (v57.2, but nothing changed in this respect, as far as I know). I long-pressed and created a note at the southern vertex of this house. The note pin dropped at exactly this position. I didn't move the map and the note pin stayed at this position regardless of whether I had the keyboard open or not. When the note was uploaded, it also appeared exactly where I tapped the map.

https://www.openstreetmap.org/note/4199534#map=19/53.58427/9.94380&layers=N

Maybe this is based on a misunderstanding? Were you expecting that the note is created at your current GPS position rather than at the position you tap on the map?

**Comment by mnalis** [comment]
- Or might perhaps be related to this GPS positioning issue introduced in `v57.1` - https://github.com/streetcomplete/StreetComplete/pull/5516 ? If so, `v57.2` should fix it.

**Comment by riQQ** [comment]
> * Or might perhaps be related to this GPS positioning issue introduced in `v57.1` - [Improve location elapsed time difference calculation #5516](https://github.com/streetcomplete/StreetComplete/pull/5516) if _'position updates are seemingly "damped" a lot'_ is referring to that ?
>       If so, `v57.2` should fix it.

This was never part of 57.1 StreetComplete proper. Only SCEE had it in 57.1. 83d7991ca037e3b02be0566b67b98ffd9132058a only is part of the tag 57.2 and not 57.1.

**Comment by sjvudp** [comment]
> Maybe this is based on a misunderstanding? Were you expecting that the note is created at your current GPS position rather than at the position you tap on the map?

I don't think so. The point is: I create hints/notes offline, then upload them to OSM, and eventually find them in https://www.openstreetmap.org/ with a significant offset. For example https://www.openstreetmap.org/note/4198670#map=19/49.19970/12.28992&layers=N

**Comment by riQQ** [comment]
Is this happening with all notes? If yes, you could take a screenshot of StreetComplete with the note visible before uploading and post a link to the uploaded note on osm.org to compare both.

Another idea: is your map view in StreetComplete tilted? Or are you using the birds eye view (straight from the top)?

**Comment by westnordost** [comment]
I can also not reproduce it with a tilted map, nor a rotated map, nor when first placing the note and then while the form is open, rotating the screen. Closing as not reproducible.

The only thing I could imagine what happened is that due to the buildings being displayed in 3D, there was confusion on where the building actually starts.

**Comment by westnordost** [comment]
(Updated my previous comment)

**Comment by mnalis** [comment]
Yes, the current user position can be off more than displayed, not only due to GPS line-of-sight, but because majority of users have _"Improve accuracy"_ enabled by default.  And that option often does completely the opposite, easily throwing users location by dozens (and in some cases hundreds) of meters. 
But while incorrect user position  is one possible interpretation of this issue, it could be read differently.

---

So it would still be very interesting if @sjvudp could make a screenshot just before they click on that orange checkmark :white_check_mark:  button to create the note, and then we can compare that to the actual position of the Note in the OSM map. 

Because, if they placed the note in the middle of some building, and it ends up on the other side of the street outside of a building, it is then the issue unrelated to GPS/location accuracy issue.

**Comment by sjvudp** [comment]
I f have some interesting updates:
First I don't know whether that's the intended way to add a note, but I long-tap on a position on the map, then select "create new note" from the popup-menu, then enter some text, and finally tap the "check mark" to close it.
When I wanted to create a test-note today, it turned out that I could create a real note with a photo attached.
Doing so, I realized that the position had a significant offset after having closed the camera app (i.e.: pressed the check mark). After a while the position indicator "walked back" to the position when I had entered the camera app. Somewhat later I found out that this effect also happens when I temporarily switch to any other app.
Here's screenshot of the situation (the German texts says "taking a photo causes a position shift"):
![Screenshot showing position offset while creating a note](https://github.com/streetcomplete/StreetComplete/assets/6734808/c037c153-6d43-4fc4-8cfa-0958faa874b1)

As one of the examples given earlier also involved taking a photo, this might explain the issue **if** the position saved with the note is **not** the tap position, but the GPS position (which would be kind of nonsense IMHO), and the user finishes the note before the GPS position has returned to the original position.
The note was uploaded as  https://www.openstreetmap.org/note/4207187#map=19/49.18988/12.26118&layers=N.

**Comment by sjvudp** [comment]
Another thing I noticed was that Street Complete works with obsolete OSM data (for example see the parking area at https://www.openstreetmap.org/edit?note=4207189#map=19/49.19334/12.26630).

OSM (ID Editor) vs. Street Complete:
![OSM Map](https://github.com/streetcomplete/StreetComplete/assets/6734808/e1c9c533-b1d5-445d-844a-906b7e794204) ![Street Complete Map](https://github.com/streetcomplete/StreetComplete/assets/6734808/e1f0c8b5-fbdd-4fb8-a9f9-f7fd3204c3c4)

**Comment by matkoniecz** [comment]
> Another thing I noticed was that Street Complete works with obsolete OSM data (for example see the parking area at https://www.openstreetmap.org/edit?note=4207189#map=19/49.19334/12.26630).

Background map tiles show processed map data shown with delay, quests are based on live data (fetched via editing API, in case of conflicts edits are not applied)

> if the position saved with the note is not the tap position, but the GPS position 

what is saved is position marked on map

>  First I don't know whether that's the intended way to add a note, but I long-tap on a position on the map, then select "create new note" from the popup-menu, then enter some text, and finally tap the "check mark" to close it.

Yes. You can also create notes instead answering a quest but then mapper cannot select location

>  Doing so, I realized that the position had a significant offset after having closed the camera app (i.e.: pressed the check mark). After a while the position indicator "walked back" to the position when I had entered the camera app. Somewhat later I found out that this effect also happens when I temporarily switch to any other app.

this is based on GPS location as reported by phone

**Comment by mnalis** [comment]
> Another thing I noticed was that Street Complete works with obsolete OSM data

Let's discuss that in separately opened #5590. Generally, for each separate problem, one should open separate GitHub issue (otherwise it becomes impossible to track what is resolved and what is not). If they are related, they can be referenced by putting e.g. `#5590` in the text (like I did here), so GitHub will cross-reference them automatically.

> Doesn't Street Complete display the "circle of confusion"?

It does, if Android OS reports it. See for example [this picture](https://user-images.githubusercontent.com/156656/133169704-62c46d02-b05c-4768-b92c-54f6b3d8e152.png) which shows it (but as noted above, that "circle of confusion" may be very imprecise)

> Even if not, couldn't it save it (or a corresponding value provided by the Android API) together with the note (so we could decide whether it's poor GPS reception)?

If there was a need, one could create a separate version just for you which adds such debug. See for example https://github.com/streetcomplete/StreetComplete/issues/3312 for similar problem with notes location (also if you're inclined, you may want to read it to give you ideas how StreetComplete works / what one could try). We should collect some other information fist; see my questions at the bottom of this message

> When I wanted to create a test-note today, it turned out that I could create a real note with a photo attached.
Doing so, I realized that the position had a significant offset after having closed the camera app (i.e.: pressed the check mark). After a while the position indicator "walked back" to the position when I had entered the camera app. Somewhat later I found out that this effect also happens when I temporarily switch to any other app.

Ah, that sounds interesting. I'll try to play with that a little; there might be problems if you move while StreetComplete is not application in the foreground (e.g. while camera app is opened).

What would be interesting is you @sjvudp  could answer those:
- if you do not move at all during the note taking (i.e. from initial long press, until you click checkmark in an orange circle to confirm saving note), can you reproduce the problem?
- if you move between the moment you long-pressed to open a dialog, and the moment you clicked checkmark in an orange circle to confirm saving note, but DID NOT USE THE CAMERA, can you reproduce the problem? If so, can you provide detailed step-by-step instructions how to reproduce it,  what you expected, and what happened instead?
- knowing your phone Android version and manufacturer/model might be helpful too
- if you long-press on Location/GPS icon in Android drawer (not in StreetComplete app!) and disable _"Improve accuracy"_ / _"Use Google"_ / _"Use Bluetooth and Wi-Fi"_ or however it might be called; does that fix the location issue? 
- Do you sometimes run some application which **reliably** does track logging while running _in the **background**_ (like e.g. [OsmAnd](https://wiki.openstreetmap.org/wiki/OsmAnd) `record track`)? If you does the problem disappear (or change) if your run that track recording application in the background at the same time you run StreetComplete in the foreground? Does the track recorded also get broken?

**Comment by sjvudp** [comment]
I'll answer and comment _some_ of the question:

> what is saved is note position marked on map

> this is based on GPS location as reported by phone

That is very bad IMHO, specifically as OsmAnd works differently: In OsmAnd the position of the tap is the position of the hint.
Despite of that the current behavior means you cannot add a hint for a place you cannot enter (I don't want to climb the root of a house just to be able to place a note on it).
I'll change the issue summary/title accordingly.

> * if you do not move at all during the note taking (i.e. from initial long press, until you click checkmark in an orange circle to confirm saving note), can you reproduce the problem?

For the case described I did not more (more than 50cm).

> * if you long-press on Location/GPS icon in Android drawer (not in StreetComplete app!) and disable _"Improve accuracy"_ / _"Use Google"_ / _"Use Bluetooth and Wi-Fi"_ or however it might be called; does that fix the location issue?

I did not enable "improve accuracy".

**Comment by matkoniecz** [comment]
> That is very bad IMHO, specifically as OsmAnd works differently: In OsmAnd the position of the tap is the position of the hint.

note is placed on long tap location (or elsewhere if note was moved), or on object location if triggered from quest answer

blue dot is based on GPS location as reported by phone

>  Despite of that the current behavior means you cannot add a hint for a place you cannot enter (I don't want to climb the root of a house just to be able to place a note on it).

you can

**Comment by mnalis** [comment]
>  Despite of that the current behavior means you cannot add a hint for a place you cannot enter (I don't want to climb the root of a house just to be able to place a note on it).

I think there is misunderstanding. I understood _"this"_ in @matkoniecz comment _"**this** is based on GPS location as reported by phone"_ to refer to _"position indicator"_ (i.e. that little blue circle with white outline :large_blue_circle: showing where the phone thinks you are currently located at) and **not** to _"note position marked on map"_ (i.e. that white exclamation mark in big red circle, which is a place where note would be placed).

In other words: yes, you absolutely should be able to long at any location you wish and the map and leave an OSM Note there, **_regardless_** of where you are currently physically located (i.e. where little blue circle is positioned).

> For the case described I did not more (more than 50cm).

Thanks. I'd love to know if you can get some _"**background** gpx track record"_ app working. 
Explanation: my working theory is that running it might fix the problem (i.e. the issue might be that when you switch out of StreetComplete which has location permission elsewhere, the phone decides to save power by immediately turning the power off to GPS, and so when you switch back to StreetComplete, it tries to reestablish location, and it takes some time with high error while it reacquires reliable GPS signal). 

If it happens like that, the problem likely lies with your Android phone system software (and should be happening with other foreground-location apps too). Tweaking power saving settings perhaps might help with that, but no guarantee (some instructions about quite complicated power savings might be found at https://dontkillmyapp.com/ for some more popular phone manufacturers)

What would also help trying to reproduce the problem is if you can share _"screen recording"_ video of the bug happening in real time @sjvudp .

**Comment by mnalis** [comment]
Heads-up: this might be genuine bug in Notes location (perhaps introduced around 57.x?); I've just experienced similar bug in SCEE at https://github.com/Helium314/SCEE/issues/543 where note was created some 200m off the location where I was creating it.

**Comment by sjvudp** [comment]
Well, leaving aside whether there is a bug or not, but considering the interface is intended to be simple, the user interface probably needs improvements:

- The user assumes that after long-tapping a point on the map and selecting "add note" (or whatever the exact phrase is) that the note is placed exactly where they tapped the map.
- However it's not quite clear whether the position can still be changed (unintended also) while or after having entered the note text
- There seems to be a crosshair (or red exclamation sign) that can be re-positioned after having entered the text (i.e.: before tapping of the accept/check mark).

If the user tried to pan the map (maybe to see something on the map while entering text), the note will be re-positioned, most likely without the user being aware of it.

(In contrast OsmAnd keeps the initial position, but allows to relocate the note in a later step. I think that would be much more preferrable.)

If there were an undo function for notes, I would make some experiments, but I don't want to annoy other people with "test notes".

I don't know whether a "GPS position walking off" has any influence on note placement, but I realized that switching apps causes exactly such "GPS position walking off". One example would be using StreetMeasure.
[For example I wasn't walking off the road, but just used StreetMeasure here (and there were no walls nearby)](https://github.com/streetcomplete/StreetComplete/assets/6734808/1d194c11-c5f4-469b-b41a-ddaeb8f032b5)


For completeness I was using ColorOS 13.1 (Android 13, CPH2371_13.1.0.607(EX01) on a CPH2371_11 (Oppo Find X5 Lite)

**Comment by HolgerJeromin** [comment]
we could delay uploading (the first 5?) notes and show an undo for 10 seconds.
not sure this is a goon idea

**Comment by sjvudp** [comment]
Another example for a severely mis-place note from this afternoon, making the note practically useless: https://www.openstreetmap.org/edit?note=4224996#map=19/49.18939/12.27518

The red arrow indicates where the note should have been:
![grafik](https://github.com/streetcomplete/StreetComplete/assets/6734808/532842ab-e267-4bca-b609-1ff80df1c931)

**Comment by matkoniecz** [comment]
can you capture video of note creation process? or is it happening only very occasionally?

**Comment by mnalis** [comment]
I found this related issue, where pressing the compass icon (maybe even accidentally)  messes up note location: https://github.com/streetcomplete/StreetComplete/issues/3101

**Comment by sjvudp** [comment]
> can you capture video of note creation process? or is it happening only very occasionally?

The point is: It does not occur all the time, and videos fill the storage quite fast (especially when long or many).

**Comment by matkoniecz** [comment]
Well, if given video has not captured it then you can delete it rather than keeping it forever.

So storage is needed for one screen capture.

**Comment by sjvudp** [comment]
To make things easier, it would be nice if a note would be displayed a few seconds (like 3) after it was filed, so the user could see where the note was actually placed, and if he/she could tap on that marker to re-open or re-position it, it would be nice.

**Comment by SomeoneElseOSM** [comment]
Just for info - I uploaded a bunch of notes with pictures a couple of days ago, from https://www.openstreetmap.org/note/4252536 onwards.  In most cases notes were actually uploaded later, due to lack of phone signal.  You can see that the note numbering is sequential even though the notes are hundreds of meters and several minutes apart.

In all cases the note position was correct - I recorded Garmin waypoints at the same time, and the positions match within a few meters.

I suspect that the reported problem here is more likely due to the user's phone misreporting the actual position (which can happen for all sorts of reasons).  Perhaps the reported could verify that with some (external to StreetComplete) position tracking software?

**Comment by sjvudp** [comment]
@SomeoneElseOSM It's hard to tell whether the phone mis-reports the current position. I used several apps to verify the position accuracy, and it looked all very well. I don't know how the API to read the current position works, but I could imagine the API being used incorrectly, maybe. Specifically if there are multiple "consumers" (i.e. different apps requesting the position at different intervals).

**Comment by sjvudp** [comment]
Today I was riding the bus and turned on GNSS (the US (GPS), the Russians (GLONASS), the Chinese (BeiDou) and the Europeans (Galileo) all had receivable signals, so I guessed the position should be quite accurate). However watching the position indicated the bus seemed to drive "zigzag" where not even roads were (it became somewhat better after a while). So I was wondering whether some "smoothing algorithm" causes that effect. I don't think there was a GPS jammer active.
(If you think the bus was too fast, I had recorded a track while inside a plane (using a different app), and that worked quite well (no "zigzag"))

**Comment by sjvudp** [comment]
Well, the problem is either still there or back (in v63.1):
Today I was cycling and collecting some info when I added a note (hint).
After that (actually somewhat too late) I realized that the position was significantly off (more than 500m) while GPS reception should have been close to perfect (clear sky, open field).
So I started to experiment:

- First I ran GPStest that immediately showed a locked position and a huge set of available SVs (GPS satellites)
- When switching back to Street Complete (SC), the position seemed fixed also, so I stopped GPStest
- However, I found that the position was wrong again shortly after, so I terminated the app and restarted it
- After that the position was still wrong!
- So I started GPStest again and let it run until the end of my survey. The positions seemed OK then

After all this left a very bad impression as if SC is querying or processing the position incorrectly. However until I had added the particular text note I did not notice that the position would be incorrect.

Unfortunately due to my confusion not realizing that the position was badly wrong, I added some hints for roads that do not apply. This brought up the idea of a new feature: Draw an area on the screen allowing to review all my pending updates stored there (the undo history doesn't make that task easy). A fix for the defect would be really needed.

OS: Android 13 (Patch Jan 2026)
HW: Oppo CPH2371 (Find X5 Lite)
I had the energy-saving function activated during my tour.

I browsed the SC logs, but could not find any error message related to position.
Here is a comparison of positions in two screenshots (wrong and correct positions):

<img width="939" height="1024" alt="Street Complete Screenshots (combined)" src="https://github.com/user-attachments/assets/35db3fb5-7322-4758-a613-ca042d841f3c" />

As I did record the route in parallel using "Mi Fitness", it did not show any anomalies (the "linear segment" in the GPX is due to pausing track recording while repairing the bike, and then forgetting to resume recording in time):

<img width="1363" height="835" alt="GPX Track in OSM ID Editor" src="https://github.com/user-attachments/assets/1e9b2013-8378-4fe5-9ae4-e7ba68f4616b" />

The relevant points recorded around the time of problem were (Mi Fitness has a bug that exports local time while claiming to export Zulu (UTC)):
```
<trkpt lat="49.209678649902344" lon="12.231051445007324">
<time>2026-05-01T18:37:48.000Z</time>
</trkpt>
<trkpt lat="49.20969009399414" lon="12.231084823608398">
<time>2026-05-01T18:47:50.000Z</time>
</trkpt>
```
So unfortunately the problem was exactly in between those samples
Maybe the problem was triggered when Mi Fitness stopped to query position updates, but I don't know.

**Comment by Helium314** [comment]
> After all this leaved a very bad impression as if SC is querying or processing the position incorrectly. However until I had added the particular text note I did not notice that the position would be incorrect.

How SC decides whether a new location is better than the previous one: https://github.com/streetcomplete/StreetComplete/blob/master/app/src/androidMain/kotlin/de/westnordost/streetcomplete/util/location/LocationUtils.kt
Providers are GNSS  or network, requested via [`requestUpdates`](https://github.com/streetcomplete/StreetComplete/blob/master/app/src/androidMain/kotlin/de/westnordost/streetcomplete/util/location/FineLocationManager.kt#L56). Update intervals are 0 s for GNSS and 5 s, minDistance is 1 m.
So if you get a location from the network provider that's "much newer" than your old location, it is used even if it has bad accuracy (your left screenshot). If your phone delivers a GNSS update to SC after this, it will be used unless something goes very wrong.

**Comment by sjvudp** [comment]
> > After all this leaved a very bad impression as if SC is querying or processing the position incorrectly. However until I had added the particular text note I did not notice that the position would be incorrect.
> 
> How SC decides whether a new location is better than the previous one: https://github.com/streetcomplete/StreetComplete/blob/master/app/src/androidMain/kotlin/de/westnordost/streetcomplete/util/location/LocationUtils.kt Providers are GNSS or network, requested via [`requestUpdates`](https://github.com/streetcomplete/StreetComplete/blob/master/app/src/androidMain/kotlin/de/westnordost/streetcomplete/util/location/FineLocationManager.kt#L56). Update intervals are 0 s for GNSS and 5 s, minDistance is 1 m. So if you get a location from the network provider that's "much newer" than your old location, it is used even if it has bad accuracy (your left screenshot). If your phone delivers a GNSS update to SC after this, it will be used unless something goes very wrong.

I don't fully understand the details of the code, but I wonder:

- Can't the "blue location dot" indicate the source of the location (like a white capital letter), e.g. "G" for GNSS (GPS, etc), "W" for WLAN, "M" for mobile network?
- If the location came from the network provider, shouldn't the "circle of confusion" (uncertainty) be so large that the actual position is inside that circle (wasn't in my case)
- Still it's not obvious why the GPS/Galileo/Beidou/GLONAS wasn't used. The logic in `LocationUtils.kt` doesn't look wrong, but I wonder why the network location is queried *after* the GPS; wouldn't the last position succeed?

I found some different code to get the location:
[How Can You Accurately Estimate Location Using Three Android Location Providers?](https://codingtechroom.com/question/-accurate-location-estimation-android)
[How to Get Current Location in Android?](https://www.geeksforgeeks.org/android/how-to-get-current-location-in-android/)
[How do I get the current GPS location programmatically in Android?](https://stackoverflow.com/questions/1513485/how-do-i-get-the-current-gps-location-programmatically-in-android) ([Answer](https://stackoverflow.com/a/10917500))

**Comment by matkoniecz** [comment]
> Can't the "blue location dot" indicate the source of the location (like a white capital letter), e.g. "G" for GNSS (GPS, etc), "W" for WLAN, "M" for mobile network?

that would add incomprehensible complexity to interface

> If the location came from the network provider, shouldn't the "circle of confusion" (uncertainty) be so large that the actual position is inside that circle (wasn't in my case)

yes, but claimed certainty levels provided to app are often blatant lies - it is not app's fault

GPS certainty levels provided to apps are often also hilariously faulty underestimates

**Comment by westnordost** [comment]
> If the location came from the network provider, shouldn't the "circle of confusion" (uncertainty) be so large that the actual position is inside that circle (wasn't in my case)

Not lies. No, it's the result of a calculation on the basis of a triangulation in which there is a 2/3rd probability that the actual location is within the circle, iirc. (It's a gaussian curve, so the probability that the user's location is at the center of the circle is highest, then first falls off slowly, then quickly until the cut-off at 33.3% probability to be even further away).

**Comment by matkoniecz** [comment]
though at least on some low-quality phones I used in past claimed estimates were persistently overoptimistic (and actual position was outside circle about 80% of time, maybe 90%)

**Comment by Helium314** [comment]
>> If the location came from the network provider, shouldn't the "circle of confusion" (uncertainty) be so large that the actual position is inside that circle (wasn't in my case)

> Not lies. No, it's the result of a calculation on the basis of a triangulation in which there is a 2/3rd probability that the actual location is within the circle, iirc. (It's a gaussian curve, so the probability that the user's location is at the center of the circle is highest, then first falls off slowly, then quickly until the cut-off at 33.3% probability to be even further away).

That would be the ideal, but of course depends on how the network location provider does the calculations...
Further it's easy to have only incomplete information about cell coverage, or getting a spurious signal from a far away cell that completely messes up your location.

**Comment by mnalis** [comment]
Could we perhaps add a `Log.d()` debug log entry when SC decides to use Network location instead of GPS, with its reasoning why it did so? It should not be happening in regular use (good GPS coverage), and I think would provide valuable information on tracking this down.
