### ISSUE TITLE
housenumbers not displayed reliably

### ISSUE THREAD

**Issue by sjvudp** [streetcomplete/StreetComplete#5583]
**How to Reproduce**

I had been walking at high zoom level when most hoses had displayed the house number inside the buildings (unsure about "address" objects that are not buildings)
When I saw a building without a number, I added a hint with the number.
In several cases the number was already present in OSM, however. So I assume StreetComplete just did not display it.

**Expected Behavior**

Consistent display of housenumber if present in OSM.

**Versions affected**

v57.1

**Comment by mnalis** [comment]
Could you give us an example (location on the map or OSM Note number) where  exactly that happened? Perhaps also a screenshot what your StreetComplete shows at that location? That would help narrow it down.

There are several reasons why house number might not be shown:
- the map might be too zoomed-out (e.g. one might have just made a tiny zoom change and numbers appear/disappear. Try zooming in more, do numbers appear?)
- there might be a Quest icon at that location or nearby which prevents housenumber to be shown  (try solving or hiding that quest so nothing obscures that building even partially)
- the housenumber might have been added only very recently (in last few days), so background map still was not  yet updated to show it.  You could try enabling `Addresses overlay` -- that should show addresses even if background map was still stale.

**Comment by matkoniecz** [comment]
>  When I saw a building without a number, I added a hint with the number.
> In several cases the number was already present in OSM, however. So I assume StreetComplete just did not display it.

If you want to make this kind of contributions then Address overlay will be useful  have you tried it?

**Comment by westnordost** [comment]
I'll close this as "question answered" by @mnalis . There is no bug. To summarize:

- addresses appear only when zoomed-in and only if no quest pin obscures it
- for contributing addresses, the most efficient and convenient tool is to activate the address overlay (tap the button left of the main menu button -> select "Addresses")

**Comment by sjvudp** [comment]
> Could you give us an example (location on the map or OSM Note number) where exactly that happened? Perhaps also a screenshot what your StreetComplete shows at that location? That would help narrow it down.

I tried to reproduce this way:
Zoom in until numbers appear; then pan the map. On another part of the map the numbers do not show.

Example:
![Screenshot_HouseNumbers-1](https://github.com/streetcomplete/StreetComplete/assets/6734808/60358c96-f440-4c05-ac88-3c08b1bf9678)

![Screenshot_HouseNumbers-2](https://github.com/streetcomplete/StreetComplete/assets/6734808/e8c3964f-741e-4f23-8550-3e424b8b8500)


> If you want to make this kind of contributions then Address overlay will be useful have you tried it?

That "view" certainly helps, but it also hides other details, right?

**Comment by matkoniecz** [comment]
https://www.openstreetmap.org/way/505925893/history#map=19/49.19981/12.28128 were added within last days, so tiles are likely not yet updated

> That "view" certainly helps, but it also hides other details, right?

compared to no overlay at all? AFAIK no.

**Comment by sjvudp** [comment]
> https://www.openstreetmap.org/way/505925893/history#map=19/49.19981/12.28128 were added within last days, so tiles are likely not yet updated

The issue is the other way round: You add seemingly missing house numbers because you don't saw them. And when the hints eventually arrive, those hints are closed with an "already there" comment. So time for at least two persons is wasted: 1:The one entering the numbers and 2:the one having to read the redundant notes/hints and close them (at least).

Maybe the example given was not well-chosen; consider this one where the zoom level had been changed only slightly:

![Screenshot showing buildings with house numbers](https://github.com/streetcomplete/StreetComplete/assets/6734808/dfed4b4e-eea3-4493-ba6b-8956fc66a5b1) ![Screenshot showing buildings without house numbers](https://github.com/streetcomplete/StreetComplete/assets/6734808/b16606d5-230a-41de-9e2d-6eb18e656559)

**Comment by Helium314** [comment]
The trick is to use the address overlay.

**Comment by matkoniecz** [comment]
> You add seemingly missing house numbers because you don't saw them. And when the hints eventually arrive, those hints are closed with an "already there" comment.

Adding notes about something missing in SC is not a good idea for addresses, objects and shops. You should add them with relevant overlay.

Maybe note creation should make it more clear if people create notes for addresses instead of using address overlay.

**Comment by matkoniecz** [comment]
Adding notes about missing objects makes sense for roads/buildings/forests/islands etc, though in limited amount (if city has no buildings mapped then making 10 000 notes about missing buildings does not help)

**Comment by mnalis** [comment]
I agree that missing addresses should be added via _Address overlay_ instead of leaving Notes. (Although I must admit that I also sometimes go the Notes route - as it is much quicker if I'm already using some other overlay, or I want to merge it into entrance etc.)

However I also see where @sjvudp is coming from:

- it is not necessarily about him personally (who has asked here, and had feedback, so can learn to use Address overlay instead of Notes); it is more about a lot of other newbie users who will _also_ miss that preferred way as it is not obvious. 
 As there are already like 4+ lines of text instructions for creating a note; I'm afraid that if we add even more text there (explaining to use address overlay instead of notes etc), it is probably more likely that people will completely ignore that wall of text, instead of gaining knowledge from it.


  Perhaps at least, when creating Notes, we could alter zoom level for displaying addresses too (much like we disable 3D tilt when creating Note) -- that should help with the overlooked housenumbers, i.e.. show them at same zooms as Address Overlay does:
  ![small_Screenshot_20240418_002501_StreetComplete](https://github.com/streetcomplete/StreetComplete/assets/156656/9f263fba-eced-4de9-ad3d-6ec492711b3d) ![small_Screenshot_20240418_002454_StreetComplete](https://github.com/streetcomplete/StreetComplete/assets/156656/ef26948a-a688-42ea-9384-bb0ac0711360)


- also, that small zoom difference is making housenumbers disappear rather abruptly. Could [Maplibre](https://github.com/streetcomplete/StreetComplete/issues/3123) perhaps change our capabilities there? I'm wondering if we can make house numbers become smaller (even if unreadable, but visible), instead of them **disappearing abruptly** by tiny zoom change?

  https://github.com/streetcomplete/StreetComplete/assets/156656/51e94ed3-74c7-4930-9dd9-869863497c18

**Comment by sjvudp** [comment]
Having played with the address overlay a bit recently, I'd like to add to @mnalis comments:
Even with the address overlay and the buildings being "large enough" to hold the number, some buildings are displayed without a number (until zooming-in more). So the address overly is better than no overlay to see the numbers, but still it's not the solution to see all numbers (while at a "reasonable" zoom level). The situation can be seen best where there are different sizes of buildings nearby.

**Comment by mnalis** [comment]
Also, as noted elsewhere: When StreetComplete [transitions to MapLibre](https://github.com/streetcomplete/StreetComplete/issues/3123#issuecomment-2057956692) from Tangram-ES rendering library (which is in progress already), _all_ rendering issues are likely to change (hopefully mostly for the better) - so this enhancement request should be reopened then by interested parties, _**if**_ the issue still exists after we transition to MapLibre.

So read release notes shown on app startup after that major upgrade, and let us know how by comment here how it fares after MapLibre happens.

(p.s. thanks for all your efforts @sjvudp  :heart: on indicating confusing parts of the UI and other issues you're having with StreetComplete! Such newcomer insight is much appreciated, as those of us using the app longer cannot even see them, as our brains have already been hardwired to do the things reflexively by now)
