### ISSUE TITLE
Incorrect tagging for maxspeed:type in the UK

### ISSUE THREAD

**Issue by NathanARF** [streetcomplete/StreetComplete#5592]
I've seen a few changesets where a user has answered the speed limits quest, and the tag `maxspeed:type=GB:zone30` has been applied to the map. This tag is incorrect as 30 zones do not exist in the UK, only 20 zones and 40 zones. Users should be prevented from inputting any values other than 20 or 40 to answer speed limit quests in the UK with a speed limit zone.

**Comment by NathanARF** [comment]
Sorry, missed a : in there.

Actually, if a user types in 19, a message will come up saying "Are you sure? This speed limit looks implausible", so there is a level of prevention that needs to be applied to the 30 value, just with a different message perhaps - users may not understand exactly how 30 mph speed limits should be tagged

**Comment by FloEdelmann** [comment]
Could you link to some of the changesets in question? Have you already asked the user about this?

**Comment by NathanARF** [comment]
Three users in the past few days
https://www.openstreetmap.org/changeset/150269316#map=18/50.69686/-2.10863
https://www.openstreetmap.org/changeset/149670842#map=14/50.4130/-4.2552
https://www.openstreetmap.org/changeset/150346330#map=19/51.64014/-2.35272
https://www.openstreetmap.org/changeset/149992725#map=18/51.74024/-2.22937

**Comment by westnordost** [comment]
This is not a bug. It is what the user(s) selected. The following video shows what the user has to select and input in order for this to be tagged:

https://github.com/streetcomplete/StreetComplete/assets/4661658/03247f09-54db-4be9-81b2-7eb2331013b2

I.e. the users answered that it is within a slow zone and a picture of the sign was shown for them to input what they see on that sign.

**Comment by NathanARF** [comment]
Yes, I understand the process works as intended, but that should not be the case as a 30 zone does not exist in the UK. Only the tags `maxspeed:type=GB:nsl_restricted` and `maxspeed:type=sign` should be used with `maxspeed=30 mph`.

**Comment by westnordost** [comment]
So, you would like us to add a sanity check alike the "this speed limit looks implausible, are you sure?" in regards to slow zones.

How do you think such a check should look like?

**Comment by NathanARF** [comment]
Something along the lines of "Are you sure this is a speed limit zone? Please check you can see a speed limit zone sign"?

**Comment by westnordost** [comment]
I meant, when should this warning appear? Under which circumstances / given which user input?

**Comment by NathanARF** [comment]
Well 30 is likely the most common mistake due to the way 30 mph speed limits work in the UK. A message for that input should be fine.

**Comment by westnordost** [comment]
Well, we need to think worldwide, because the quest is available worldwide. And surely, the same message should also be shown for an input of 31, 40 etc., no?

**Comment by NathanARF** [comment]
Well, those are likely mistakes, whereas the 30 zone tag has been applied by multiple people, showing a bigger issue. I think the "Are you sure?" message covered by strange numbers is fine for the other values, it's just the 30 that appears to be the issue.

**Comment by westnordost** [comment]
But an input of 30 should not lead to a warning message everywhere in the world, right??

**Comment by NathanARF** [comment]
Well, this is only an issue in the UK

**Comment by westnordost** [comment]
Sigh... it seems I fail in bringing across what I want from you.

I am not going to add special rules in the code for every single country code, like `if (country == UK && input == 30) showWarning()` because this approach would just be an endless source of similar requests: What about an input of 29 or 31? What about Jersey (not part of the UK)? What about input of 50 (etc?) in non-mph-countries? What about the US, Liberia?

Anyway, I can think of something myself, but then I would like to know from you why especially the input of 30 is that common of a mistake in the UK? You started changeset discussions on some of these changesets, so hopefully the users will be able to answer this.

**Comment by RubenKelevra** [comment]
@westnordost alright, what about adding a positive list for existing zones per country and warn if the user inputs something else?

There's the [default speed limit](https://wiki.openstreetmap.org/wiki/Default_speed_limits) article which is supposed to be machine readable in the OSM wiki. 

I think it could be extended to list the zones in each country (or this could be added in some other article) and imported into SC while creating a new version.

This way there's no need to maintain this data in SC.

**Comment by matkoniecz** [comment]
Maybe it can go into country data? And if there is list defined complain about ones outside the list.

**Comment by westnordost** [comment]
That sounds like a huge effort for a small "Are you sure?" dialog.

Also, what hinders road authorities to come up with new limits for speed signs on the spot? 30kmh zone is well known, but I don't see a reason why there shouldn't be a 20kmh zone, a 10 kmh zone, a 15kmh zone, etc.

**Comment by RubenKelevra** [comment]
> Maybe it can go into country data? And if there is list defined complain about ones outside the list.

Yeah sure, but that would need continuous maintenance, compared to a wiki approach where people would maintain it for you.

**Comment by RubenKelevra** [comment]
> That sounds like a huge effort for a small "Are you sure?" dialog. (Not only initial, but also continuous - maintenance.)
> 
> Also, what hinders road authorities to come up with new limits for speed signs on the spot? 30kmh zone is well known, but I don't see a reason why there shouldn't be a 20kmh zone, a 10 kmh zone, a 15kmh zone, etc.

Germany already got 20 km/h zones... and there were 10 km/h 😇

![images.jpg](https://github.com/streetcomplete/StreetComplete/assets/614929/3f0ad27c-7e7a-49af-98fc-b32e6d8690da)

![berlin-verkehrsschild-temposchild-10km---h-mit-ausgewiesener-geschwindigkeit-von-10-kilometern-pro-stunde--gesehen-in-berlin-mitte---spandauer-vorstadt-foto-doris-spiekermann-klaas.jpeg](https://github.com/streetcomplete/StreetComplete/assets/614929/a8494752-51ec-4a99-8434-7fb24e1ee6d6)

**Comment by mnalis** [comment]
> There's the [default speed limit](https://wiki.openstreetmap.org/wiki/Default_speed_limits) article which is supposed to be machine readable in the OSM wiki.

Perhaps I am misunderstanding, but how would that specific wiki page help @RubenKelevra ? 

That page says it is about _"Legal default speed limits apply if **no explicit** speed limits are set by appropriate signs"_. I.e. what is **default** speed limit for _urban_, _rural_, _motorway_ etc. road if ***no sign is present***. 

If some kind of **speed limit sign is present** (i.e. `maxspeed:type=sign`, `maxspeed:type=CC:zoneXX` etc), I would guess that it is usually because the current street has speed limit which is **different** then those present in _default speed limit_ wiki? 

For example, when I count [different `maxspeed`s used in Croatia](https://overpass-turbo.eu/s/1KKz), majority of them are **not** present in that wiki.

And when I [count different `maxspeed:type`](https://overpass-turbo.eu/s/1KKn) (to get zones, which this issue seems to be about) literally **none** of the Croatian zones (`zone10`,`zone20`,`zone30`,`zone40`) are present in  [default speed limit](https://wiki.openstreetmap.org/wiki/Default_speed_limits) wiki. So, at least here, it would always give a confirmation warning for any zone (which would suck)? (that is, if I understood the idea correctly in the first place, which is not given :smiley:) 


---

Better automated solution might IMHO be that on-new-release we build a list of allowable `maxspeed:type` (e.g. by looking up all  values which have 50+ (or whatever) uses, e.g. [this taginfo for United Kingdom](https://taginfo.openstreetmap.org.uk/keys/maxspeed:type#values)), and warn on anything not in the list, but:
- I have not checked if all countries have [per-country taginfo](https://taginfo.geofabrik.de/) database
- there is still the possibility that there be 50+ incorrect values on OSM at the moment of the release
- as noted by BDFL, I'm also not sure if the effort would be worth it. 
  I think SC does something similar for  _ATM operators_, but that one saves **a lot** of typing and mistakes (but has same problem as point above -- if OSM has several variations of operator name, all of them will be present in the search. Which is currently the case in Croatia, for example. Mechanical edit would be relatively easy to fix them, but the sheer bureaucracy around doing that makes me postpone those fixes every time :cry:)

---

Also, perhaps it might be useful to actually contact those users who mapped wrong non-existent values (esp. if they same user did that same error several times or more) and check with them why it might be happening? Sure, fat fingers are one explanation, but there might be others...

**Comment by NathanARF** [comment]
> Better automated solution might IMHO be that on-new-release we build a list of allowable `maxspeed:type` (e.g. by looking up all values which have 50+ (or whatever) uses, e.g. [this taginfo for United Kingdom](https://taginfo.openstreetmap.org.uk/keys/maxspeed:type#values)), and warn on anything not in the list

All those listed there, except `maxspeed:type=construction` are the only tags that should be used in the UK (with the `maxspeed:type=GB-WLS:nsl_restricted` only being somewhat adopted after a discussion on TalkGB). I recently spent time removing/fixing incorrect tags, hence why I brought this up in the first place.

> Also, perhaps it might be useful to actually contact those users who mapped wrong non-existent values (esp. if they same user did that same error several times or more) and check with them why it might be happening? Sure, fat fingers are one explanation, but there might be others...

I did contact those who made the mistakes but the only reply thus far is a comment linking to this exact thread.

**Comment by westnordost** [comment]
> I did contact those who made the mistakes but the only reply thus far is a comment linking to this exact thread.

Ok, let's wait a bit. Did you actually ask them or have a hunch why they answered this way?

**Comment by NathanARF** [comment]
I suspect because it's somewhat common to say "30 zone" to refer to general widespread 30 mph speed limits in the UK, and so these users selected the zone sign when answering the quest as a result.

**Comment by westnordost** [comment]
Are these "30 zones" signed in some way or are they set implicitly by the presence of street lighting?

**Comment by NathanARF** [comment]
Many of the incorrect tags were applied to 30 mph speed limits where there are no repeater signs due to the presence of street lights (where the correct tag is `maxspeed:type=GB:nsl_restricted`) although one example was an unlit road (where the correct tag is `maxspeed:type=sign`)

**Comment by westnordost** [comment]
So, would changing the wording to "It's within a **signed** (slow) zone" make it clear?

**Comment by NathanARF** [comment]
Potentially

**Comment by westnordost** [comment]
I implemented showing a warning on entering a not-really-slower-than-normal speed limit in the slow-zone sign input, also shown for odd values such as "17" etc.

**Comment by riQQ** [comment]
The wording change was reverted in b89db4a50b1e149f3338e34c8d684464b2b83f7e.

**Comment by westnordost** [comment]
because looking at the translations, some are already a bit awkward, with that "(slow)" in there. Adding another adjective will result in even more awkward wording for some translations that may end up being confusing.
More importantly, adding the word may evoke the wrong notion that for a slow zone to be tagged as such, there needs to be a sign **on that street**, which is usually not the case with slow zones - there are only signs at the entrance and at the exit to such zones.
