### ISSUE TITLE
Tag `width` asked, when `width:lanes` is already present

### ISSUE THREAD

**Issue by ohrie** [streetcomplete/StreetComplete#5593]
I came across [this changeset](https://www.openstreetmap.org/changeset/149289513), which added `width` tags, while the tag `width:lanes` was already present a long time. I guess, StreetComplete has shown the question, because the tag `width:lanes` is not processed. As of the [OSM Wiki](https://wiki.openstreetmap.org/wiki/Key:width), this tagging is valid. [Taginfo](https://taginfo.openstreetmap.org/keys/width%3Alanes#overview) shows a usage of around 8.000 times in the whole world.

**How to Reproduce**
Enable and use question type `AddRoadWidth` and watch for streets with the `width:lanes`

**Expected Behavior**
The question is not shown, since the width tag is present.

**Versions affected**
The mentioned changeset was made with version 57.1.

**Comment by matkoniecz** [comment]
> I came across [this changeset](https://www.openstreetmap.org/changeset/149289513), which added width tags, while the tag width:lanes was already present a long time

on which object?

**Comment by ohrie** [comment]
> on which object?

All of them, except Werderstraße.

**Comment by westnordost** [comment]
`width` includes also e.g. parking lanes, bike lanes and shoulders while `width:lanes` only includes full-width through-traffic lanes. This means that adding `width` on a road with already `width:lanes` set is not necessarily superfluous. In the changeset you linked for example I see some bike lanes.

(Could it be that `width:lanes` was actually tagged incorrectly? On the bing aerial imagery, I don't see two lanes, I see only one, plus the bike lane. The documentation on `width:lanes` is quite scarce, but I assume it follows the [`lanes`](https://wiki.openstreetmap.org/wiki/Key:lanes)-schema. Neither parking lanes nor bike lanes should be mentioned in `lanes` according to the wiki).

**Comment by westnordost** [comment]
Oh nevermind, `width:lanes` actually uses the [`*:lanes`](https://wiki.openstreetmap.org/wiki/Lanes) schema, so, includes bike lanes.

But I don't read anything about shoulders and parking lanes. I suppose the schema only covers through-traffic lanes?

**Comment by ohrie** [comment]
> I suppose the schema only covers through-traffic lanes?

I guess, so, as the [German Wiki Page](https://wiki.openstreetmap.org/wiki/DE:Fahrspuren) also suggests: *"The :lanes subkey covers all types of lanes (= flowing traffic) for all types of vehicles [...]"*. There's nothing about lanes without flowing traffic.

But nevertheless, if there are no shoulders and/or parking lanes, the sum of all `width:lanes` values is `width`. So maybe the more correct description is: 

> **Expected Behavior**
> The question about `width` of streets is not shown, if the `width:lanes` is present, except `shoulder!=no` or (`parking:right!=no` and `parking:left!=no` and `parking:both!=no`) is present.

**Comment by westnordost** [comment]
Plus `shoulder:right/left/both != no`. Plus, some parkings are completely off the road, while others are half-on-the-road. In the end, it is going to be a pretty long filter to achieve the behavior described in the starter post.

That's fine, if it was really important to exclude asking for the width of roads where `width:lanes` is already tagged. At the moment, I don't really see it. As `width` is the vastly more used tag by _3 orders of magnitude_, I would expect many data consumers to disregard such relatively fringe tags when processing width data for one use case or another. So, also recording width in addition to `width:lanes` may actually be useful, and at worst, just superfluous.

I also wonder how to tag the area in between the outermost lane and the kerb (/ end of paved area) is tagged... i.e. the gutter ... probably not at all because it is usually not broad enough to be considered by most mappers as a shoulder and usually there is no outer lane marking when there is a kerb. Might depend on the country though. At least in (parts of) London, I remember there are lines like that.
In a nutshell, even when there is no parking lane and no shoulder there might still be a difference between `width` and the sum of all `width:lanes` albeit probably small (I guess usually 20cm to at most half a meter - anything beyond that would probably be tagged as a shoulder).

---

Taking a step back, it looks like the issue came up first due to another issue: A user quite grossly mismeasured the width of a road. He tagged "4" but it should be "5", at least according to `width:lanes` tagged earlier. That is more than 20% difference.

So IMO this is really a separate issue: It looks like the user should rather correct whatever measuring method he is using (again: if the previous `width:lanes` was correct). It appears that he wasn't using StreetMeasure to measure it (otherwise a `source:width=ARCore` is set), was he just estimating?

**Comment by westnordost** [comment]
Anyway, I will close this as will not fix.
