### ISSUE TITLE
Some issues for Taiwanese users

### ISSUE THREAD

**Issue by Sylvia0476** [streetcomplete/StreetComplete#5598]
Sorry, my English is not very well, so I use Google Translate. If you don’t understand what I mean, Please tell me. Thank you!

1. Taiwanese law stipulates that the passage of bicycles is prohibited on the sidewalks, but on StreetCompete, there are only "allowed" and "Path".

2. In Taiwan ,a lot of maxspeed is marked on the road surface. But StreetCompete  only have “sign” or ”no sign”

3. In “place” mode, I can’t add Chinese name in other countries’ place. And I can’t add the address

4. In “Things” mode, I don’t see the “Survey point”

5. In Taiwan, some pavement material of roads or sidewalks is “Tiles” or “terrazzo”, but I haven’t seen in OSM.

6. In Taiwan ,we have many “areca store” and “Chinese medicine shop” 

Sorry to brother you again ,but I just want StreetCompete  is not only useful but also meet the needs of Taiwanese users. 

Thanks!
Best wishes!
Edison Lu

**Comment by westnordost** [comment]
> 1. Taiwanese law stipulates that the passage of bicycles is prohibited on the sidewalks, but on StreetCompete, there are only "allowed" and "Path".

I am not sure what exactly you mean. (Posting a screenshot could help). If you mean the cycleway overlay: In case there is no explicit sign, select "Not designated for cyclists". That is the second option from the top.

> 2. In Taiwan ,a lot of maxspeed is marked on the road surface. But StreetCompete  only have “sign” or ”no sign”

See Mateusz, maxspeed marked on the road surface is also a sign.

If the _Chinese (Traditional)_ translation is not clear in this regard, feel free to improve it.

You can contribute to the translation(s) here: https://poeditor.com/join/project/IE4GC127Ki - ìf you do not understand English at all, you can change the reference language from which you translate into traditional Chinese in the settings. For example, maybe you understand Chinese (Simplified).

> 3. In “place” mode, I can’t add Chinese name in other countries’ place. And I can’t add the address

Google Translate is not making clear what you mean. Just so that we understand each other:

1. You should use this app only on-site, do not map in places where you are not currently present
2. In the "place" mode, you can only add names in the languages that are official or semi-official in the country the place is in. For example, in Taiwan, in Chinese and in English. In Belgium, only in French and Dutch, et cetera.
3. You can add addresses in the separate addresses-overlay

> 4. In “Things” mode, I don’t see the “Survey point”

That's correct. It is not possible to add survey points with StreetComplete. Your only option if you really want to add such survey points is to either add a note or use another app for this.
The reason they are not shown and it is not possible to add them is that they are usually so small that they are difficult to see. If they were shown, some users might delete them because they don't see them.

**Comment by westnordost** [comment]
I will close this broadly as "questions answered" and/or not actionable (e.g. point 6 would be for https://github.com/openstreetmap/id-tagging-schema) but feel free to continue posting comments here.
