### ISSUE TITLE
Tap-Hold-Move gesture after zooming out increases the zoom again

### ISSUE THREAD

**Issue by deevroman** [streetcomplete/StreetComplete#5601]
**How to Reproduce**

Quickly tap on the map, tap and hold again, and swipe up without releasing it. The zoom decreased briefly, but the map zoomed in again

https://github.com/streetcomplete/StreetComplete/assets/25708359/70378f08-cadc-424e-905a-8b261dc2f25a

**Expected Behavior**

The zoom should only decrease

**Versions affected**

StreetCompelete 57.2
Samsung A52
Android 14 OneUI 6.0

I suspect that the problem occurs due to a conflict between the double-tap gesture that zooms in on the map.

p. s. two years ago, I reported this in discussions https://github.com/streetcomplete/StreetComplete/discussions/4414, but it seems issue was not opened

**Comment by westnordost** [comment]
I can reproduce this. However, this is an upstream issue (in tangram-es) which will not get fixed. It will get fixed by moving to another map renderer, MapLibre. There is an open pull request in progress for this: https://github.com/Helium314/SCEE/pull/516 .

A, well, workaround is to not use the fling-gesture but tap-and-hold, use it like a slider. This works fine in tangram-es. TBH I didn't know a fling-gesture existed and not sure a fling-gesture for zooming exists in MapLibre.

In any case, this will not get fixed.
