### ISSUE TITLE
"Is the route forbidden?" Clearer answers

### ISSUE THREAD

**Issue by coolmule0** [streetcomplete/StreetComplete#5610]
**Use case**
"Are pedestrians forbidden to walk on this road here? Answers include "yes" and "no".
I feel like there could be added clarity to the binary choice. "forbidden, yes" takes me a moment to parse, and I feel like there are more clear answer possibilities.

**Proposed Solution**
Suggest changing these answers to "Forbidden" and "permitted" in English. (While keeping the other options "sidewalk" and "uh...").

P.s. love the software

**Comment by westnordost** [comment]
ωell, there are many quests which have yes/no answers. However, I agree, forbidden having a negative connotation, it takes a moment to parse in that case and writing out the answer would be better.

Also, it is awkward that the "sidewalk" answer needs explanation. Better put the explanation in the actual answer option.

**Comment by westnordost** [comment]
![imagen](https://github.com/streetcomplete/StreetComplete/assets/4661658/6d49e182-0dff-4604-af3a-1b88dae12970)

**Comment by westnordost** [comment]
Hm, actually, going to drop the "yes," and "no,"

**Comment by mnalis** [comment]
One possibilty to make it easier to parse for humans would be leaving `yes` / `no` answers, but changing the question to _"Are pedestrians **allowed** to walk on this road here?"_, and reversing the meaning of answers -  then it is quite readable IMHO: _"yes; it is allowed"_ or _"no; it is not allowed"_

---

However I seem to recall that there were an quite and lengthy discussions before where it was changed to this text with _**"forbidden"**_ because there were mistaggings due to ambiguity about whether there needs to be explicit sign forbidding, or one need to know the local law to know what is implied for each road type (or something along those lines) so this formulation was found to be least problematic. E.g. https://github.com/streetcomplete/StreetComplete/issues/4998, https://github.com/streetcomplete/StreetComplete/issues/3316, https://github.com/streetcomplete/StreetComplete/issues/2895, https://github.com/streetcomplete/StreetComplete/issues/2472, https://github.com/streetcomplete/StreetComplete/issues/1342 and probably more...

So special care should be taken when making the decision if order not to break those again

**Comment by westnordost** [comment]
Yes, I will not touch that.
