### ISSUE TITLE
"Is there a socket for loading your devices in this café|library|waiting room?"

### ISSUE THREAD

**Issue by rugk** [streetcomplete/StreetComplete#5627]
### General
Affected tag(s) to be modified/added: [`socket:`](https://wiki.openstreetmap.org/wiki/Key:socket)
Question asked: **Is there a socket for loading your devices in this café|library|waiting room|…?**

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/blob/master/QUEST_GUIDELINES.md)):
- [x] 🚧 To be added tag is established and has a useful purpose – finding places where you cab load your mobile devices like smartphones
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one) — unsure, how to tag none, but should be solvable by `socket=none` or so, though that is not established yet AFAIK
- [ ] 🐿️ Easily answerable by any pedestrian from the outside but a survey is necessary – no, very likely (expect for waiting rooms maybe) one needs to go inside, unless signed. This, it soups probably be disabled by default line vegetarian etc. quests, it's kinda similar in that sense
  * for `amenity=device_charging_station` this should also be answerable because even if you need to pay, you likely most know before paying whether you can accrual charge your device there. For this, it could always be enabled. 
- [ ] 💤 Not an overwhelming percentage of quests have the same answer (No spam) – unsure, at least in cafes is quite a thing you can charge your services. That said maybe a country filter may be useful here to not ask this where charging is anyway never a thing? 
- [x] 🕓 Applies to a reasonable number of map data (Worth the effort)

### Ideas for implementation

**Element selection:** cafes, libraries, waiting rooms at train stations etc. + `amenity=device_charging_station`

**Metadata needed:** maybe yes, no idea where to get it from

**Proposed UI:** you likely just want an image selection quest:
* with the local plug type (e.g. `schuko` in Germany) 
* and with USB-A
* and USB-C
* and wireless (qi) charging

The OSM Wiki lists these and they are easily detectable even for non technical users with an image. These options should cover 90% of what may be there, likely. 
Possibly add lightning and micro USB though these are legacy products and thus likely not often supported.
Important if not obvious, multiple options should be selectable.

---

This idea came [from Mastodon](https://en.osm.town/@amapanda/112410552730647930).

**Comment by rugk** [comment]
Urg accidentally hit that button, give me a second

**Comment by westnordost** [comment]
Uff, so many not fulfilled quest guidelines with this suggestion...

> **🚧 Established tags only**

If someone on Mastodon states that _OSM needs a tag to say “this cafe has a plugs where you can power your laptop”"_, then this sounds very much like `socket:` is **not** an established tag for this use case. taginfo confirms this.

As for the eligibility of that tag for this usage:
1. It doesn't say anything about whether these sockets are OK for public use. (Because, of course, every shop will have electricity sockets)
2. (🐿️ Easy answer / 🕓 Effort vs impact) Electricity sockets in one country are standardized, so to specify the socket **type** (e.g. `schuko`) in order to denote whether this ... hmmm... service exists adds more/orthogonal information than you want to record. To not require users to fill that useless information themselves, StreetComplete would need to have metadata about socket (types) per country, which is unnecessary extra effort for implementers. Even then, it would be a hassle in countries where more than one socket types are common - for users because they always have to select which and for implementers to always offer these options, including pictures.
3. (🤔 No unanswerable quests) `socket=none` does exist. New tagging schemes should not be proposed on this issue tracker.

In conclusion, the tag is not only not established, it is also not eligible at all for this use case, even with additions (that would need to be discussed in the community first).

> **💤 No spam**

You already didn't check that box. I can't think of any definition of a prospective "you can charge your devices here"-tag by which this question would not be spam. If it is defined by "there are dedicated facilities", then the answer will almost always be no, if it means that you might find a socket on the wall, then the answer will almost always be "yes"...

> **🐿️ Easy answer**

... not to mention the vast area of "there are sockets, and to use these is neither explicitly forbidden nor allowed, i.e. depends on the owner". This additionally would make it quite difficult to answer.

> **🕵️ Publicly accessible on foot**

Additionally to users having to enter the facility in the first place, finding sockets on walls is also more intrusive than taking a peek at the menu, for example.
