### ISSUE TITLE
Enable autorepeat on +/- buttons in Addresses overlay

### ISSUE THREAD

**Issue by JohnVeness** [streetcomplete/StreetComplete#5633]
**Use case**
Often when I'm using the Addresses overlay (screenshot below) to add house numbers to a road, I need to add numbers that are some way apart from each other. E.g. I might need to enter 12, 18, 27, 40 etc. This might happen if I was travelling too quickly to note every single house, or if I was filling in gaps in a partially-surveyed road.

![Screenshot_20240510_213952_StreetComplete](https://github.com/streetcomplete/StreetComplete/assets/2512915/512d2699-c52a-40d2-b526-f2f846230175)

At the moment, if we need to change a number we can single tap on the + and - buttons multiple times (can get annoying if you have to tap a lot), or we can tap on the number field to bring up the onscreen keyboard (can be fiddly). I'd like to propose something in addition to both of those.

**Proposed Solution**
It would be very useful if the + and - buttons would autorepeat when held, so that for example if it's currently showing 27 and I wanted 40 I could hold + for a little while until it approached or overshot 40, then single-tap + or - until it's correct if necessary. This would be preferable to having to tap + 13 times, or bringing up the onscreen keyboard and typing 40 (although both those options would still be present).

Thanks for reading!

**Comment by westnordost** [comment]
Hmm. Controls that work like that are very hard to get right, or maybe impossible. I think I've never come across a control like that that felt convenient to use. Sometimes they are too fast and you rush past the desired value, sometimes it's too slow and you'd be faster just tapping, sometimes there is some weird acceleration in it so it seems fine at the start and then accelerates that it is impossible to hit the correct value. I believe this is very hard to balance out, considering also that everyone has a different reflex time and degree of impatience.

Maybe it is a personal dislike, but I also do not like controls that require you to keep pressing down while monitoring the screen state to time correctly when to let go. It's... uh... (can't find a better word) un-relaxed / on-edge.

I don't know when I last used the arrow-up or arrow-down button of a scroll-bar. But I remember drag-and-dropping things into other windows but not wanting to drop it at the current scroll position but further up or down. It is always an unbelievable hassle because the scroll speed with a file "in-hand" is just never right - too slow, accelerating exponentially, uff. It's also completely inconsistent, so one never knows what behavior one can now expect.

So, anyway, I don't think this is a good idea.

**Comment by westnordost** [comment]
I figure someone could implement that and play around with it whether it feels right. But I don't have high hopes for that.

**Comment by Helium314** [comment]
@JohnVeness if you want to get a few users for trying, you could do a PR in SCEE.
