### ISSUE TITLE
When searching for Things in Things Overlay, show matched alternative name too

### ISSUE THREAD

**Issue by mnalis** [streetcomplete/StreetComplete#5636]
**Use case**
Currently, opening a Things overlay and searching for main term match, it is very nice. I.e. searching for `play r` will list:
- **Play R**oundabout

With search term nicely emphasized!

However searching for `merry` (to find `merry-go-round`) lists:
- Play roundabout
- Carousel

(and without any emphasizing) which is confusing, as it is unclear how those things matched search term `merry`

**Proposed Solution**
When search matches one of iD alternative terms, add that term in italics in parentheses and emphasize match string too. E.g. for `merry` it should list:

- Play roundabout _(**merry**-go-round)_
- Carousel _(**merry**-go-round)_

(of course is search matches the main term, no changes are needed)

**Comment by mnalis** [comment]
(probably the same thing applies to Places overlay too)

**Comment by Helium314** [comment]
I think with _alternative names_ you mean the (search) _terms_, and I don't think they are meant for showing.
Search terms are always lowercase, so showing them will result in issues about capitalization by German speakers.
Some objects have __many__ search terms, e.g. a [`historic=memorial, memorial=plaque`](https://github.com/openstreetmap/id-tagging-schema/blob/main/data/presets/historic/memorial/plaque.json) would show as _Commemorative Plaque (dedicatory, epitaph, historical marker, remember, remembrance, memory)_ when using US English.

**Comment by westnordost** [comment]
Correct, see @Helium314 . Terms are never shown, because they are just search terms. E.g. `amenity=bank` has probably "money" as a term. Displaying that would not make sense.
On the other hand, IIRC, if your search term matches an **alias**, the alias is highlighted as if it was the name. Because an alias is an _alternative name_. That also means that something that is actually either a subcategory or subcategory of a preset or could be several different presets is **not** an alias. E.g. a _barber_ is not an alias for a _hairdresser_, because it is more specific (regardless of whether there already a separate preset for this or not) and a _road_ is not an alias for an _unclassified road_, because it is less specific.
As merry-go-rounds could either be a play roundabout, a carousel or maybe other things, I think it's classification as a term, rather than an alias, is correct.

**Comment by mnalis** [comment]
> Some objects have many search terms, e.g. a [historic=memorial, memorial=plaque](https://github.com/openstreetmap/id-tagging-schema/blob/main/data/presets/historic/memorial/plaque.json) would show as Commemorative Plaque (dedicatory, epitaph, historical marker, remember, remembrance, memory) when using US English.

Yes, I meant displaying only the _one_ matching what the user has searched for, not all of them. For example:

- if they searched for `histor`, they would be shown "Commemorative Plaque _(**histor**ical marker)_", but
- if they searched for `epita`, they would be shown "Commemorative Plaque _(**epita**ph)_" instead.

But yeah, I see the point for `bank` where it probably wouldn't work too well.
