### ISSUE TITLE
Add new quest: Is this smoothness still accurate?

### ISSUE THREAD

**Issue by danik292** [streetcomplete/StreetComplete#5643]
### General
Affected tag(s) to be modified/added: [](https://wiki.openstreetmap.org/wiki/Key:smoothness)
Question asked: Is this level of smoothness still accurate?

If yes leave the smoothness tag as it does and add information about the survey date.
If no let user choose new one and add information about survey date.

This check can be done every two years.

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/blob/master/QUEST_GUIDELINES.md)):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by any pedestrian from the outside but a survey is necessary
- [x] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of map data (Worth the effort)

### Ideas for implementation

**Element selection:** 

**Metadata needed:** 

**Proposed UI:**

**Comment by rhhsm** [comment]
I like this, but I like a smoothness overlay #5486 even more. An overlay would make an accuracy check unnecessary. @qugebert was going to work on it...

**Comment by westnordost** [comment]
Exactly, it is already implemented.

**Comment by danik292** [comment]
@westnordost  thank you for reply

**Comment by westnordost** [comment]
Note however that it may not work as one might expect. It is true that it is asked every 4 years, but only if the road hasn't been modified in 4 years **or** a `check_date:smoothness` has been set and is older than 4 years. Since roads are often updated due to other reasons *and* `check_date:smoothness` is set on roads very rarely, de-facto it will rarely be asked again.

The solution (IMO) would be to (instead of a quest) have an overlay, so users can check and correct the smoothness any time. But someone would need to implement this - #5486 - and I myself am busy with other things.

**Comment by qugebert** [comment]
> I like this, but I like a smoothness overlay #5486 even more. An overlay would make an accuracy check unnecessary. @qugebert was going to work on it...

Thanks for the reminder. I totally forgot about that. I'll have to see when I can find the time, but I want to look into it soon.

**Comment by qugebert** [comment]
@danik292 I don't know if you are already familiar with SCEE (a StreetComplete fork), but there you can customize the filter settings. So, if you currently need more frequent intervals for resurveys, you could try that.
