### ISSUE TITLE
Additional answer (power=terminal) for PowerPolesMaterial-Quest

### ISSUE THREAD

**Issue by qugebert** [streetcomplete/StreetComplete#5657]
### General

From time to time i come across notes like 'This is not a power pole; the line is anchored to the tower.' ([Example Note](https://www.openstreetmap.org/note/4255525))
So this is not power=pole but [power=terminal](https://wiki.openstreetmap.org/wiki/Tag%3Apower%3Dterminal)
Apparently, there are some mappers who record these as power poles. Therefore, I would like to suggest adding another option with a picture that sets power=terminal.

Possible CC0-Picture from OSM-Wiki
![](https://wiki.openstreetmap.org/w/images/a/a6/Trafohaus.jpg)

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/blob/master/QUEST_GUIDELINES.md)):
- [X] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
 --> Adds an answer that is currently not covered
- [X] 🐿️ Easily answerable by any pedestrian from the outside but a survey is necessary
- [X] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
- [X] 🕓 Applies to a reasonable number of map data (Worth the effort)

### Ideas for implementation

**Element selection:** 

**Metadata needed:** 

**Proposed UI:**

**Comment by qugebert** [comment]
> Some data collected from [this overpass query](https://overpass-turbo.eu/s/1M0U) how common this is:
> Country 	`power=pole`s 	Poles that are part of a building 	Percentage (truncated)
> France 	1155264 	210 	0.01
> Croatia 	6738 	2 	0.02
> Italy 	188268 	256 	0.13
> Austria 	261189 	307 	0.11
> Germany 	717486 	4176 	0.58
> Sweden 	61492 	16 	0.02
> 
> How common this kind of tagging is varies greatly by country. Even in Germany, the number of poles that are connected to a building is quite small (in spam territory, I'd say). This makes me think that adding an option in the "Uh..." submenu makes more sense than adding a option for every pole (or is it possible to add this option only for poles that are connected to a building or are not connected to any other ways?). Maybe something like "Not a pole, this line ends in a building"?

Thank you for the overpass-query, i had no idea how to write such query.
I think adding the option only for suspicious nodes would be too complicated for me to implement and not worth the effort. 
Maybe i could manage to write a completely new quest (Is this really a power pole or is it a terminal?) with the filter i used in the IsAmenityIndoor-Quest, but i'm, not sure if a new quest that affects such few nodes would be accepted. 

To the spam point: I think it might reduce "spam", because there are fewer notes that need to be queued manually.

**Comment by westnordost** [comment]
Looking at the numbers, thank you @mnalis , I would actually say it is not worth the effort to even _have_ an other answer. The 250 or-so occurrences of such tagging could just as well be fixed by a motivated mapper using JOSM.

**Comment by burrscurr** [comment]
(not mnalis, but similar profile picture)

I agree that the numbers are fairly low for many countries – except Germany. I think, however, that it makes sense to add a "other answers" option:

- The numbers only capture the cases where there is a building mapped. Since power lines are mainly mapped from aerial imagery, it can be difficult to identify transformer towers correctly as buildings. Instead, one might just add a `power=pole`, despite actually being a `power=terminal` connected to a transformer tower (or similar).
- Not sure "fixing" this with JOSM would be a great idea, maybe there *are* cases where a pole connected to a building could be legit? Surveying seems helpful here.
- Typically, the "fake" poles would be where power lines end, typically close to other buildings and thus more likely to SC mappers to encounter, rather than a pole somewhere on a field.

Is 0.1 to 0.5% likelihood an unusual range for "other answers" options? Are there any particular downsides to adding such option?

**Comment by matkoniecz** [comment]
> Are there any particular downsides to adding such option?

Needs to be implemented, increased maintenance effort for future, each new text needs to be translated into every single language. From what I see at https://github.com/westnordost/StreetComplete/blob/master/CONTRIBUTING.md#translating-the-app currently there are attempts to translate app into 70 languages.

> Is 0.1 to 0.5% likelihood an unusual range for "other answers" options?

I would say it is on the low end? But getting into range (but it is a guess, I have not made proper measurement)

**Comment by qugebert** [comment]
Have I now understood correctly that it should be implemented as 'other answer'? And regarding the aspect mentioned by matkoniecz that some transformer towers are just not mapped: Wouldn't it be sensible in such cases to create a note about the missing building? Maybe, an additional dialog 'Is this building already shown on the map?' ?

**Comment by westnordost** [comment]
Yes, as an other answer, because the answer is a bit orthogonal to the question: "What material is this power pole?" - "It is actually not a power pole but the line is attached to a building here.". (The other-answer option's text must be much more succinct, of course, but you get the idea.)

Regarding leaving a note because a building is missing: I don't think this is necessary or it should be encouraged to leave notes when buildings are missing. These will be mapped from aerial imagery by people who like to map that and if the detail of the aerial imagery allows it. A note is not going to help.

**Comment by rhhsm** [comment]
A more common tagging mistake (in my experience) is that some poles are actually lattice towers that should have been tagged with `power=tower`. They typically occur where a minor power line splits or changes direction (example here https://www.openstreetmap.org/way/845380419). It's hard to see on imagery that these are different. So far I answered the quest with "steel" and then changed these to `power=tower` when home again (if I remembered) but it would be nice if I could change them within SC.
