### ISSUE TITLE
'Is this still here' asked immediatly after 'opening hours' are filled in

### ISSUE THREAD

**Issue by Nick-Tallguy** [streetcomplete/StreetComplete#5674]
For a shop that needs its opening hours completing, after completing that quest, often asked 'is the shop still there?"

**How to Reproduce**  
Locate a shop that needs it's opening hours added   
Add those opening hours  
Quest may now be displayed asking if the shop is still there.  

**Expected Behavior**  
If the opening hours are being added, the shop must still be there, and the 'is it still present' quest is not needed.  

**Versions affected**
Android version 14  
StreetComplete v 58.0

**Comment by westnordost** [comment]
Can you post an example of a shop for which this was happening?

**Comment by Nick-Tallguy** [comment]
https://www.openstreetmap.org/changeset/152236067#map=17/51.39741/0.17268&layers=N

is a changeset for me today, I think most of them asked me if they were still present after I added the opening hours. It's not only shops - I was asked in relation to a tennis court and a children's play area

Screenshot of part of my surveying history showing some of the instances.  

![Screenshot_20240604-170422](https://github.com/streetcomplete/StreetComplete/assets/6763965/443a27aa-8ab6-45c5-a8e9-c139ba472bdc)

Please let me know if any logs or other data is available in my history that could be helpful.

**Comment by matkoniecz** [comment]
Have you disabled automatic upload?

**Comment by Nick-Tallguy** [comment]
Hi,

No, automatic upload still happening

Regards

Nick

**Comment by mnalis** [comment]
Yeah, I'd too say that should not be happening.

> Please let me know if any logs or other data is available in my history that could be helpful.

I'm not sure if they contain useful data in this particular case, but making a copy of logs (`menu` / `Show logs` / `share`) as soon as possible (i.e. before they expire) after that happens always sounds like a good idea.

Might not be related, but this (quest not being recognized as solved before same or related quest pops up) reminds me of https://github.com/streetcomplete/StreetComplete/issues/4258

**Comment by westnordost** [comment]
Ok so for example for Motties this was happening.

The opening hours quest looks at the shop's last modification date or `check_date:opening_hours`, whatever is older, to determine whether to show the quest. If set previously, `check_date:opening_hours` is set to today after the quest has been answered.

The existence quest looks at the shop's last modification date or `check_date`, including any variants like `survey:date`, whichever is older, to determine whether to show the quest. If it still exists, it will then set the `check_date` to today.

So, this happens because this concerns two separate tags. The opening hours quest is asked first because it has a higher priority in the list.

So, this is not a bug, but maybe something could still be done about it to make it not inconvenient to the users.

For example, would it make sense if StreetComplete updated the `check_date` tag also to today if **any** `check_date:*` is set to today?

**Comment by mnalis** [comment]
> For example, would it make sense if StreetComplete updated the check_date tag also to today if any check_date:* is set to today?

For **existence quest**, I'd say yes - any `check_date:*` implies that the element existed at the time. (Well - mostly any. if there was `shop=*` tagged on `building=*` polygon; and there was e.g. `check_date:building`, that might still be today even if the shop stopped existing years ago).

---

But I'm still unclear why it happened. Sure, v11 only updated `check_date:opening_hours=2024-06-04` which isn't checked by  existence quest, but by nature of things it also updated node 714261374 metadata last modified timestamp, right?

And existence quest should've checked (in absence of `check_date`) that node metadata timestamp and seen that it is today? Seems to me like updating the last modified timestamp metadata didn't update the quest cache timestamps or something?

**Comment by westnordost** [comment]
A survey:date was specified before.

**Comment by Nick-Tallguy** [comment]
I have recovered the Street complete log from my phone for yesterday's
surveying period if you would like it.

**Comment by westnordost** [comment]
No, this is unnecesary. I already explained why this happens. mnalis and matkoniecz tried to be helpful, but it was unnecessary.
