### ISSUE TITLE
Changesets can become bigger than the atlantic

### ISSUE THREAD

**Issue by gfm-rock-solid** [streetcomplete/StreetComplete#5697]
https://www.openstreetmap.org/changeset/152794534#map=3/15.52/-15.79

This should not happen.

**How to Reproduce**
Solve questions. Travel by plane. Continue solving questions. Have a big changeset.

**Expected Behavior**
Before adding an item to a changeset, streetcomplete must check the size of the bounding box. If too big. Close changeset and open a new one.

**Versions affected**
50.1

**Comment by matkoniecz** [comment]
Have you enabled manual upload?

**Comment by Helium314** [comment]
This is with 50.1, iirc should be already fixed if the user is actually close to the edited places while doing edits

**Comment by westnordost** [comment]
You should update to a current version. See https://github.com/streetcomplete/StreetComplete/pull/5474, closing as duplicate.

**Comment by jarek** [comment]
We saw multi-continent changesets again with `StreetComplete 61.3` in https://www.openstreetmap.org/changeset/173750946 - I'm not familiar with how StreetComplete would try to handle this: is this a result of explicit user action somehow, or a StreetComplete regression?

edit for my own reference: see also discussion in https://github.com/streetcomplete/StreetComplete/issues/4582

**Comment by mnalis** [comment]
> I'm not familiar with how StreetComplete would try to handle this

See https://github.com/streetcomplete/StreetComplete/pull/5474#issuecomment-1927641429 for how changeset splitting is supposed to work (and when it intentionally **doesn't** work -- so problematic mappings can be caught by people checking overly large changesets).


> We saw multi-continent changesets again with `StreetComplete 61.3` in https://www.openstreetmap.org/changeset/173750946

It seems the user generally mapped in Germany (and down to Italy), but then they had some edits in Mexico. It also happened 2 hours ago for them to map building numbers in Morocco (https://www.openstreetmap.org/changeset/173851006). While it might be possible that they travel a lot, it is more likely something else. 

It happens rare enough so I would not suspect any malice on the user part (i.e. trying to gain higher SC "score"). 

@jarek It would be useful for you to check with them (in their changesets) whether they really did travel to those places, or if not, how/why they edited there (as StreetComplete should've warned them to only edit places they have physically visited). Their answers might lead to discover what they were doing, and consequently if those large changeset were intentional...
