### ISSUE TITLE
Tactile paving primitive or incorrect

### ISSUE THREAD

**Issue by alex8065** [streetcomplete/StreetComplete#5705]
**Use case**
Currently we can only tag tactile paving as `tactile_paving=yes` and `tactile_paving=no`, but could be interesting to also tag the very common `tactile_paving=primitive` or even `tactile_paving=incorrect`  (see the [wiki](https://wiki.openstreetmap.org/wiki/Key:tactile_paving) for a detailed explanation).
**Proposed Solution**
Add `tactile_paving=primitive` and other relevant tags with explanation pictures, potentially.

**Comment by mnalis** [comment]
Firstly, thanks for caring about mapping tactile paving infrastructure! 
Tactile paving is indeed big help to blind and visually impaired persons!

Secondly, note that quest `Does this crosswalk have tactile paving on both ends` already has `Uh...` answer of `Only on one side`, which **will** tag `tactile_paving=incorrect`, so that one is at least somewhat implemented.

Also, StreetComplete has **4 different** [quests](https://wiki.openstreetmap.org/wiki/StreetComplete/Quests) regarding tactile paving; so if you're talking about only some of them, it would be good to be specific which ones.
 
---

As for `tactile_paving=primitive`, defined as _"Where any water drain or decorative tactile element can be used for orientation accidentally, but no typical tactile ground elements are used."_, considering [Quest guidelines](https://github.com/streetcomplete/StreetComplete/blob/master/QUEST_GUIDELINES.md) quoted in **"bold"** below, here are few of my personal  opinions/questions:
 
- `tactile_paving=primitive` seems weakly defined, and thus might have [verifiability](https://wiki.openstreetmap.org/wiki/Verifiability) issues. If the intention is _"accidentally (i.e. not intentionally/by design) help orientation"_, than a wastebasket or advertising totem or bus_stop shelter might serve as well? Or is it only water drains? How about manhole covers? Or `asphalt` -> `paving_stones` transition (common in my little places on the world on crossings for example)? Or any kerb which makes detectable height change? How about bench or fire hydrant or steps? Do those fall under _"(accidental) decorative tactile elements"_? 
  And unless everyone has a same answer to those and similar questions, is it still an "**Easy answer**" then?
  
- while it has some ~1.2k uses, that is still only [0.03%](https://taginfo.openstreetmap.org/keys/tactile_paving#values) of `tactile_paving=*` uses, which seems small. Would it tick the **Established tags only** checkbox?

- is there any app which actually uses that value to give different feedback to blind users? Or do you have some other insight about that particular tag values being somehow useful to blind users? IOW is there "**Useful purpose**" for that particular value?

- on the other hand, I do see why some people would like to tag some value between `yes` and `no` in cases when they are uncertain. So perhaps it might at least be used as a way to skip re-asking quest and mark such dubious locations.
  I'm just afraid that it:
  - might be very subjective (i.e. produce different answers depending which mapper you ask), and that
  - it wouldn't really help blind person unless you tell them **exactly** what to expect (e.g. _"... and then after about 100m you might locate **something** after which you should immediately turn 90 degrees left"_ it would likely not help at all. But if you specify exactly exactly what to expect - a step, a metal manhole, a water drain, a tree in the middle of the sidewalk; then it might be of help)

**Comment by westnordost** [comment]
If I remember correctly, additional tag values (such as `primitive`, if it existed back when it was implemented) were considered but ultimately rejected. @mnalis mentions some reasons for that (🐿️, 🚧) and I would add that the most important point (for StreetComplete) is that it would require **👨‍💻 expert knowledge** to know whether a tactile paving is present, but incorrect.

**Comment by dreirund** [comment]
I want to add to this:

> *Hence, only the physical presence of paving is asked for, not whether it is incomplete or primitive.*

From [this discussion](https://community.openstreetmap.org/t/129339) it emerges that an incorrect paving should definitely not be tagged as `yes` (because incorrect paving does not really help).

So, if we do not want to allow the `primitive` answer, the rationale should rather be:

"*only the physical presence of _correct_ paving should be asked for.*" and the question formulated correspondingly (strict!).
