### ISSUE TITLE
Cycleway overlay marks both sides of roundabout as missing

### ISSUE THREAD

**Issue by FloEdelmann** [streetcomplete/StreetComplete#5716]
**How to Reproduce**
For https://osm.org/way/492794174 (OSM element version 11), the cycleway quest correctly recognizes that it's a oneway street ([implied](https://wiki.openstreetmap.org/wiki/Tag:junction%3Droundabout#How_to_map) by [`junction=roundabout`](https://wiki.openstreetmap.org/wiki/Tag:junction%253Droundabout) but not explicitly set with [`oneway=yes`](https://wiki.openstreetmap.org/wiki/Tag:oneway%3Dyes)). The cycleway overlay however does not recognize this and marks both sides as red:

<img alt="Screenshot_20240702-141300_Street­Complete" src="https://github.com/streetcomplete/StreetComplete/assets/202916/49a1ea6a-9a94-46dd-9c04-7cdb0a54236d" width="300"> <img alt="Screenshot_20240702-141318_Street­Complete" src="https://github.com/streetcomplete/StreetComplete/assets/202916/2a1e23a8-052d-4066-a88a-6c0e9a90bfc5" width="300">

**Expected Behavior**
The cycleway overlay should also only mark the outer side as red, and possibly also only allow setting the outer side.

**Versions affected**
StreetComplete v58.1, Android 13

**Comment by FloEdelmann** [comment]
Tangentially relevant: There is still some special behavior left in the cycleway parser for `opposite` tags: https://github.com/streetcomplete/StreetComplete/blob/05ef7ce4564e8eba42220ae02e38f87f0e7b6aa5/app/src/main/java/de/westnordost/streetcomplete/osm/cycleway/CyclewayParser.kt#L18
Maybe that can be removed/simplified now?

**Comment by westnordost** [comment]
> Tangentially relevant: There is still some special behavior left in the cycleway parser for `opposite` tags: https://github.com/streetcomplete/StreetComplete/blob/05ef7ce4564e8eba42220ae02e38f87f0e7b6aa5/app/src/main/java/de/westnordost/streetcomplete/osm/cycleway/CyclewayParser.kt#L18
Maybe that can be removed/simplified now?

(Unfortunately) no, this is still necessary to parse correctly for which side a `cycleway=*` (without sides given) in oneways is meant for. `opposite` is deprecated, and it should be marked a such, but still it must be handled correctly when it is tagged.

**Comment by westnordost** [comment]
Short answer: Will not fix.

Long answer:
In the quest, oneways (which include roundabouts) are treated specially, to not (uselessly) ask for cycle tracks in contraflow of oneways as most oneways do not have that. This is not done for overlays because overlays should offer a more immediate interface for setting and updating the cycleway infrastructure tagging. I don't think it is necessary to add complexity here to *hide* stuff from the user as it would be done for quests.

**Comment by westnordost** [comment]
I just noticed that we already do some filtering where cycletracks are not expected and that these are then shown as transparent instead of red. E.g. motorroads missing `cycleway` are not highlighted red (but transparent).

So, while not a bug, it can certainly be an improvement to add this. Additionally, I would say that the following taggings are all equally unlikely to have cycle tracks in contraflow:
- roundabouts
- oneways with `dual_carriageway=yes`
- oneways that are a `*_link` roads
