### ISSUE TITLE
Street­Complete on OpenAPK

### ISSUE THREAD

**Issue by mobilenetworkltd** [streetcomplete/StreetComplete#5732]
Hey,

I'm running a open source repo for Android apps at https://www.openapk.net and I am very proud to have Street­Complete listed in the repo. Please review the listing at https://www.openapk.net/streetcomplete/de.westnordost.streetcomplete/

It is hooked to your GitHub repo so all the updates are automatically pushed to OpenAPK. Let me know if its ok !

If you are interested you can link to it and use our download banners ( https://www.openapk.net/images/openapk-badge.png )

**Comment by HolgerJeromin** [comment]
> Street­Complete is [Navigation](https://www.openapk.net/category/navigation/) application that is open source under the GPL-3.0-only license.

Not a navigation app...

> StreetComplete is an easy to use editor of...

This is correct...

**Comment by mobilenetworkltd** [comment]
BTW i love that you have fixed the option to login with Google.

**Comment by HolgerJeromin** [comment]
> Which category can you suggest to put your app?

If you rename the category to "map stuff" this would work for all. But it could confuse, too.
Similar problem with:

* SCEE
* cgeo (geocaching is not navigation)
* vespucci, "every door" (other osm editors)
* streetmeasure (helper app for streetcomple, perhaps better in "SCIENCE & EDUCATION")
* some gps loggers
* tower collector

**Comment by mobilenetworkltd** [comment]
Thank you very much for these remarks. I will remove this sentence as you stated it is clearly visible from above. As for the categorization this is general ones with which we started developing the site. We are in the process of making them more precise and think we will manage to do it in the next month for all the apps. I truly appreciate your feedback and would love to hear more if you have some suggestions of how to make OpenAPK more transparent and what we can include to satisfy the standards of respected open source developers like you.

**Comment by mnalis** [comment]
> I'm running a open source repo for Android apps at https://www.openapk.net/ 

Is it an _"open source repo for Android apps"_, or a _"closed source repo for open source Android apps"_?

I've tried looking at https://github.com/mobilenetworkltd/openapk but could not find any source for generating that repo content, only few images and markdown files? Or am I looking at wrong place?

**Comment by westnordost** [comment]
Cool, I didn't know about OpenAPK yet. So it is kind of curated by hand? Are you doing this in your free time, or do you intend to build some business around it? I like how you (apparently) get the star count from github :-). Did you write scripts to automatically also pull apps from other forges, like gitlab, codeberg or whatever?

Anyway, regarding the navigation category, IIRC it is also sorted under that category in Google Play – because no (other) category fit quite right. You could, for example, rename the category to "Navigation and Maps" and it would be more fitting for more apps.

**Comment by westnordost** [comment]
> BTW i love that you have fixed the option to login with Google.

Yeah, it's a bit embarrassing that this went under the radar that long - I think it might have broken starting with v57.0 - but it wasn't reported until recently.

**Comment by westnordost** [comment]
Ah I see, sounds cool! What's AndroidFreeware? I can't find anything about it on Duckduckgo (at least not in the first few results).

**Comment by westnordost** [comment]
Anyway, chat can continue in this ticket, so some comments to close this issue:

- the app is distributed under GPL-3.0 which requires that the source is provided with the distribution. Since a link to the source repository is provided on the download page, I don't see an issue with this, but IANAL. If you want to be very sure that you adhere to GPL-3.0, it might be better to provide the source code somewhere alongside the binary download for each version. I.e. like it is done on GitHub.

- To link to OpenAPK from this repo would not make sense at this time because
  1. they can already be downloaded from this repo 
  2. there is no advantage over downloading directly from this repo 
  3. I can not guarantee that the APKs over at OpenAPK are the same as here.

  Point two could be solved if eventually there would be an app that would allow updating via OpenAPK (like the F-Droid app). Point three could be solved by if OpenAPK would actually not host the APKs themselves but just link to the files attached to the releases on GitHub/GitLab/... etc.

**Comment by mobilenetworkltd** [comment]
@westnordost we are working on a F-droid repo that will do that. We also link directly to the Github releases, we don't build APK files or store them to avoid situations that talk about. Looking forward for your comments.
