### ISSUE TITLE
Notes show up twice if I add two photos

### ISSUE THREAD

**Issue by hofmannu** [streetcomplete/StreetComplete#5751]
At the moment it looks like that if I add two photos to a note, it will create two separate notes on OSM with the comments duplicated.

**How to Reproduce**
Just add a note somewhere, take two photos and upload.

**Expected Behavior**
Make one note with two links on openstreetmap. Two comments need to be resolved separately otherwise.

**Versions affected**
StreetComplete 58.2
Android 14, LineageOS 21-20240619-NIGHTLY-FP4

**Comment by matkoniecz** [comment]
can you link example doubled note?

**Comment by westnordost** [comment]
Is this always reproducible?

**Comment by mnalis** [comment]
- ref: https://github.com/streetcomplete/StreetComplete/issues/4853

**Comment by hofmannu** [comment]
It was reproducible twice to me, examples are

4338164, 4338171

As well as

4337695, 4337559

**Comment by hofmannu** [comment]
Ok i cannot reproduce the issue somehow, should i close it for now and reopen it once i can reproduce?

**Comment by matkoniecz** [comment]
Feel free to reopen once you have some example (to recheck that you use recent SC version and not say SCEE and so on)

**Comment by westnordost** [comment]
I've looked in the code. Uploading notes twice (with the same images attached) can happen if on the first upload, an error occurs, e.g. a HTTP timeout. In that case, StreetComplete will try again later.

So it is possible that the OSM API returned an error even though it accepted the creation of a new note or that the OSM API accepted the creation of the new note but the HTTP response of its success didn't reach your device through a timeout or whatever.

IF two notes were created and each had a different photo attached (but otherwise the same text), that would be a different bug (or the user just wrote the same note twice, maybe due to some misunderstanidng), but I understand that this is not the case here.
