### ISSUE TITLE
Confusing icon for parcel locker pickup quest

### ISSUE THREAD

**Issue by margin-auto** [streetcomplete/StreetComplete#5757]
The new quest for adding the parcel_pickup tag to parcel lockers shows a parcel with an blue arrow pointing upwards away from the parcel. Seeing this I'd think of sending a parcel. Not of receiving or pick up one.

![tempFileForShare_20240721-080610](https://github.com/user-attachments/assets/85481d83-592b-4487-bc5b-3234cdbc48b6)

**Comment by westnordost** [comment]
Hm, depends on the point of view... You pick it up **from** the station.

**Comment by westnordost** [comment]
I didn't think about it before. I guess I chose the icons as they are now because of the naming of the OSM tags: pick up and drop off.
I.e. you don't send your parcel, you drop it off.

There is potential for misunderstanding either way. I think I would only make it worse if I switched the icons. If something should be done about it, then rather create completely new icons that do not have this potential for misunderstanding.

In the end, it is the question that counts, the icon is mostly there to distinguish the different quests.

Given my statements above, I will close this as will not fix. But if someone wants to try creating clearer icons, go ahead.

**Comment by westnordost** [comment]
Yeah, I am contemplating whether these quests should be removed again. 
Asking whether parcels can be received seems a bit pointless because that is literally the purpose of these stations and whether sending is possible may have a verifiability issue. (Someone claimed that it is not written on the machine)
