### ISSUE TITLE
Defining names of POIs in Things overlay 

### ISSUE THREAD

**Issue by martinrieder** [streetcomplete/StreetComplete#5761]
**Use case**

When creating or editing some POIs in the Things overlay, their name should be editable, i.e. memorials, artwork or a trail marker. You can currently only see their name displayed without the possibility to change it:

<img alt="Screenshot_20240722-235643~2.png" src="https://github.com/user-attachments/assets/f9e10bb3-bd5d-4386-ad81-a7eb844e8776" width="360">

 
**Proposed Solution**

Show a text field for defining the name of a POI in the Things overlay. The same feature is already available in the Places overlay:

<img alt="Screenshot_20240722-232923~2.png" src="https://github.com/user-attachments/assets/e9168ea2-6e05-4bdd-9e2c-2b755d30f999" width="360">

**Comment by mnalis** [comment]
Hmmm... It makes sense to allow changing the name that is being shown; although, that would also mean asking for name when adding any new memorial, artwork or a trail marker, etc.  Since the name can be left empty, that is hopefully not a huge issue, but could be confusing if it is often empty.

However, also note that that **label can show _other_ tags** than `name` too [AFAICT](https://github.com/streetcomplete/StreetComplete/blob/8636a3b62f5d464cc87cb98899bc9b403e7cbaef/app/src/main/java/de/westnordost/streetcomplete/util/NameAndLocationLabel.kt#L92-L93) (like `ref`, `brand`, `operator` etc.) and  those tags are **never editable** when adding a Thing / Shop in Overlays, so even if `name` editing is added on those Things, it would only address the issue partially...

**Comment by matkoniecz** [comment]
I think it was discussed when things overlay was created and rejected then

**Comment by westnordost** [comment]
Places generally have names, Things generally don't have names. 

A few types of things may have names, such as memorials, artworks etc. but most (e.g. benches, trees, bicycle parkings, bins, ...) don't and thus it would be inappropriate and confusing to show the name field for those. Might even lead to some users adding "Bench" or something as names. So, if this was implemented at all, it would need to be conditional on which type of thing was selected, which both is effort (to implement and also to maintain) plus also feels like an inconsistent or even buggy UI - because also things that usually have no name can in rare cases have a name after all or the other way round. Or the "usually has a name" list is not complete and the user is confused where the name-input field went.

I don't think this is worth the additional maintenance burden, source for more issues and UI inconsistency.

Also, remember that we have a quest that specifically asks about the name of a place. This quest is asked for places and things that usually have a name. So if you add a thing that usually has a name, the name quest should pop up right after.
This quest can always be extended to include more things that usually have names.
If you are going to suggest some things to include in this quest `AddPlaceName`, please research with taginfo beforehand for each to-be-added thing whether the data really suggests that a thing usually has a name and include the findings in the issue.
