### ISSUE TITLE
Ability to send packages from parcel locker not surveyable

### ISSUE THREAD

**Issue by Prillan** [streetcomplete/StreetComplete#5763]
The title pretty much says it all.

It's not possible to know for the locker itself (in the cases I've seen) if it's possible to send packages or not. I had to look it up on the website to realize that you can actually _return_ packages. Additionally, that option is currently located in the "other answers" menu instead of being a simple third option.

Anyway, my worry is that SC users will _think_ that it's not possible to send packages (or returns) and just assume that it's not. Because there's no way to verify it on-the-ground, we risk having incorrect data produced.

Furthermore, if a locker gains the ability to do returns, that'd only be a software update and again not surveyable. So there's no way to know if the state has changed for `parcel_mail_in`.

**Comment by Prillan** [comment]
PostNord (Swedish post service).

![20240726_183759.jpg](https://github.com/user-attachments/assets/20d6f4bc-3617-4153-b1c7-786b44293957)

**Comment by westnordost** [comment]
Well, maybe both quests should be removed again. I mused about this a few days ago

>  Asking whether parcels can be received seems a bit pointless because that is literally the purpose of these stations and whether sending is possible may have a verifiability issue.

https://github.com/streetcomplete/StreetComplete/issues/5757#issuecomment-2246157976

**Comment by Prillan** [comment]
> Well, maybe both quests should be removed again. I mused about this a few days ago
> 
> >  Asking whether parcels can be received seems a bit pointless because that is literally the purpose of these stations and whether sending is possible may have a verifiability issue.
> 
> https://github.com/streetcomplete/StreetComplete/issues/5757#issuecomment-2246157976

Nothing more to add really. Receiving is what they're there for, sending is hard (or impossible) to verify.

**Comment by hmartink** [comment]
I agree, I have seen (and placed) in both Germany and Austria. While they all mentioned the receiving side, but none mentioned about pickup.

So yes, I agree, placing them in the overlay and answering "Is this still here" is probably sufficient for parcel lockers, i.e. no dedicated quest needed.

**Comment by hmartink** [comment]
Well, I can only state my experience from Germany and Austria, mainly DHL and Amazon (but in Vienna also other companies I do not remember atm). I never touched the monitor, but on the written outside only "receiving" was mentioned. So maybe my sample is skewed.

**Comment by hmartink** [comment]
I don't know, I can only observer what's written outside (or in the future, what the monitor tells me). But for Amazon, I could *imagine* that you can drop returns there. But again, this was not visible to me.

**Comment by rhhsm** [comment]
> Well, maybe both quests should be removed again. I mused about this a few days ago

I was going to write an issue requesting this, so please keep musing!

I think the parcel locker pickup and send quests should never have been implemented because they don't comply to the guidelines for new quests. The issue raised here is that it's apparently not "Easily answerable" for some brands of lockers. The quests are also very spammy ("Not an overwhelming percentage of quests have the same answer") when considered for each brand of parcel locker separately. Afaik all parcel lockers can be used to receive parcels (that's their reason for existing, isn't it?) and whether they can be used for sending or returning parcels depends only on the brand's policy (i.e. it's the same for all parcel lockers of a particular brand, so once you know the brand, you know the answer to the quest). There may be exceptions, but they are probably extremely rare, or temporary (malfunction of a particular locker), and we should not waste the efforts of SC users to find these.

This information is much easier to add by going to the website of the locker brand and see how they function (it's always described in general terms, afaik), and then adding this info to the brand preset of the locker. Maybe this should be an additional criterion for new quests: "The quest should not try to collect information through survey that can be obtained much easier and reliably by another way (such as visiting a website)"?

**Comment by Helium314** [comment]
Sure, would be fine if the quest is removed from SC.
