### ISSUE TITLE
building construction on complete is changed to building=building if it was tagged building=construction construction=building

### ISSUE THREAD

**Issue by sekerob** [streetcomplete/StreetComplete#5767]
Used SC yesterday to report a building construction complete (was per history tagged as building=construction). SC changed it to building=building. No good per ID and Osmose.

There show 481 entries per TagInfo in the OSM database.
https://taginfo.openstreetmap.org/search?q=building%3Dbuilding#tags

(Maybe the construction=house tag could be used to transfer the tag value to building=* and remove the construction tag on the go but if it's construction=building, more than often since there are 75k of these per T,, change the building tag to building=yes on completion.).

(Originally misreported on Osmose Backend GitHub)

**Comment by Cj-Malone** [comment]
https://www.openstreetmap.org/way/1054145799/history#map=19/42.48951/14.17729

SC moves the `construction` value to `building`, someone had tagged it as `construction=building`

**Comment by matkoniecz** [comment]
`building=construction construction=building` is silly tagging, I am not convinced that it should have special support from StreetComplete to handle it

in general, if tagging was silly/wrong already then SC is not trying to fix all such problems

**Comment by matkoniecz** [comment]
In other words, tagging here was bad and SC neither made it worse nor introduced any new problem

thanks for spotting and fixing it

**Comment by matkoniecz** [comment]
similarly if tagging would be `building=construction construction=hoouse` before then new value, after marking it as constructed, would be `building=hoouse`

**Comment by sekerob** [comment]
Removed quest from SC

**Comment by matkoniecz** [comment]
> Removed quest from SC

not entirely sure what you mean here...

in related news, this combination (see http://overpass-turbo.eu/s/1OLi ) seems relatively popular with more than 3000 uses so cleaning it (maybe manually, maybe with approved bot edit) seems to make sense

**Comment by mnalis** [comment]
> (Maybe the construction=house tag could be used to transfer the tag value to building=* and remove the construction tag on the go but if it's construction=building, 

Yes, that is exactly what is happening - and apparently what should be happening, according to: https://wiki.openstreetmap.org/wiki/Key:construction#Buildings

After building was confirmed completed, SC took `construction=X`, and changed it to `building=X`.
Problem is that if `X` was wrong/confusing/undocumented initially for `construction=*`, it will also be wrong/confusing/undocumented after it was moved to `building=*`.

> more than often since there are 75k of these per T,, change the building tag to building=yes on completion.).

Sure, technically SC might implement some logic to fix some originally incorrect tags (like `construction=building`), but:
- it adds complexity permanently, which increases ongoing maintenance costs
- where does it stop? There are thousands of `construction=*` values, with probably hundreds of confusing/undocumented/illogical ones
- it would only fix the symptoms, and **not** fix the core issue: which is incorrect/confusing/undocumented `construction=*` data in OSM.

> in related news, this combination (see http://overpass-turbo.eu/s/1OLi ) seems relatively popular with more than 3000 uses so cleaning it (maybe manually, maybe with approved bot edit) seems to make sense

Given above, I agree with @matkoniecz that mechanical edit is probably better solution - if that `construction=building`  is indeed useless on `building=construction` (which should be verified on community forum/wiki talk page), it should **better be removed automatically via [mechanical edit](https://wiki.openstreetmap.org/wiki/Mechanical_Edits)**. It seems that `construction=building`:
- is not documented on the [wiki](https://wiki.openstreetmap.org/wiki/Key%3Aconstruction#Buildings)
- [history](https://taginfo.openstreetmap.org/tags/construction=building#chronology) shows it is likely results of some big imports (which people were removing more slowly later on)?
- iD currently offerts that value for `construction=*` even if not documented/enumerated in [id-tagging-schema](https://github.com/mnalis/id-tagging-schema/blob/main/data/fields/construction.json), probably because of its use in the wild. If so, mechanical edit would then fix that issue too.


> (Originally misreported on Osmose Backend GitHub)

- (ref. https://github.com/osm-fr/osmose-backend/issues/2275)
