### ISSUE TITLE
Don't edit wrong osm object

### ISSUE THREAD

**Issue by NVBWSeifert** [streetcomplete/StreetComplete#5769]
User Dinkelhuhn! edited at 2024-04-14 in changeset https://www.openstreetmap.org/changeset/150006300 the osm way https://www.openstreetmap.org/way/413437000

Previously, this objects was a footway between an elevator and a way, parallel to a steps object.
After the edit with streetcomplete, the object was changed to highway=steps and in further changesets, some steps related tags were added.

I assume, streetcomplete either
* found the existing highway=steps, asked for missing details, but during changeset, it didn't change the steps object, but took the wrong, very closly highway=footway object and changed it to highway=steps.,
* or i didn't find the existing highway=steps objects and assumed a missing steps object when analysed neighbor objects with differenent level=* tags.

The result was a routing error for disabled persons, who needs to use the elevator.

**Expected Behavior**
Please improve either your analysation process or the process to find the correct object to edit.

**Versions affected**
StreetComplete 57.1
as of changeset info

**Comment by Helium314** [comment]
> Please improve either your analysation process or the process to find the correct object to edit.

What happened here: the footway didn't have a surface tagged, and a user tried to answer the surface quest. The user then chose the "these are steps" answer, upon which StreetComplete changed the footway to steps.
Can you suggest what exactly to improve?

**Comment by matkoniecz** [comment]
> i didn't find the existing highway=steps objects and assumed a missing steps object

are you user Dinkelhuhn who made this edit or a different person?

>  Please improve either your analysation process or the process to find the correct object to edit.

why you assume that it was a StreetComplete bug rather than user answering incorrectly? SC is not magic, if user answer with incorrect data it cannot guess that user answered incorrectly

(though it would be bug if it confused mapper into doing this or tagged steps where user has not claimed way to be steps)

**Comment by westnordost** [comment]
That would be quite the critical bug. Thankfully, that is not what happened.

What happened was that the user re-tagged a footway to a steps. It is possible to do in StreetComplete:

![Screenshot_20240728-120849_Street­Complete](https://github.com/user-attachments/assets/008ed82f-1ae9-4911-a7fd-b042ebcfb3d1)

I think this user mistake was caused by that in StreetComplete, indoor paths are not shown at all, for clarity. (You know how messy any multi-storey mall looks on the OSM carto website.) However, in this case, only some ways within the train station were tagged as being indoor, resulting in a display within the app that looks like one way is missing.

![Screenshot_20240728-121033_Street­Complete](https://github.com/user-attachments/assets/ef9dc111-060a-4788-bb10-5dce00e6d290)

 The user likely thought that the (only) way he saw (because they are that close together) was the steps, so he re-tagged it.

So, this misunderstanding can be solved by tagging all indoor paths consistently as indoor paths (or none as indoor paths). I see no action that can be taken by us - displaying indoor paths is usually too messy to be helpful without some sort of 3D or layered rendering.

**Comment by westnordost** [comment]
Great, we all replied at the same time. Well.
