### ISSUE TITLE
Visualize all features of mapped objects and allow their modification 

### ISSUE THREAD

**Issue by heavelock** [streetcomplete/StreetComplete#5770]
**Use case**
I spotted multiple streets around me that are marked as a residential streets which is accurate. However, they are marked as two way streets instead of one way. I would like to modify it and change it to be accurate with the reality. 

**Proposed Solution**
It would be nice if it would be possible to change some existing features of map nodes. I would propose adding an overlay that would allow for selecting mapped objects and show all their tags. I think it would be useful also to validate features of already mapped objects. 

BTW, thanks a lot for the project, I was longing for an easy way of modifying data in OSM as I got myself stranded quite a few times while cycling and trusting Komoot a bit too much.

**Comment by matkoniecz** [comment]
Hello! I have good news and bad news.

Bad news is that functionality was proposed, discussed and rejected already, see #471

Good news is that [SCEE](https://github.com/Helium314/SCEE) fork has support for editing raw tags directly. Obviously, it requires ability to edit them directly. (which goes against "StreetComplete is an easy to use editor of OpenStreetMap data available for Android. It can be used without any OpenStreetMap-specific knowledge." which is why this feature was rejected)

**Comment by heavelock** [comment]
Makes sense!
Thanks for the link to SCEE, I will head there and see if it's what I was looking for.
