### ISSUE TITLE
include highway=secondary in POSSIBLY_SLOWZONE_ROADS

### ISSUE THREAD

**Issue by olecky** [streetcomplete/StreetComplete#5771]
The option to choose zone sign as the source of the speed limit is only available for certain categories of the roads (POSSIBLY_SLOWZONE_ROADS, up to tertiary). But cycling across France this summer I came across quite a few places where a secondary road was included in zone 30, see for example the attached picture ([location](https://www.openstreetmap.org/way/137112794)):

![IMG_20240709_150312](https://github.com/user-attachments/assets/782562cb-8e20-4dcc-adc5-f0473a55db97)

It also seems to happen in other countries, for example [here](https://www.openstreetmap.org/way/422614185). In my hometown, Warsaw, we used to have a really huge zone 50 that included a lot of secondary roads.

Is the restriction really beneficial?

**Comment by matkoniecz** [comment]
This restriction is not because there are no roads whatsoever of this type getting zone markings, but because it was considered to be extremely unusual, to the point of causing more problems than helping.

Though if such roads are actually present more often than expected then missing option can be causing more damage than being helpful.

**Comment by matkoniecz** [comment]
@olecky 

> POSSIBLY_SLOWZONE_ROADS too restrictive?

would "include highway=secondary in POSSIBLY_SLOWZONE_ROADS" match what you propose here?

**Comment by olecky** [comment]
> @olecky
> would "include highway=secondary in POSSIBLY_SLOWZONE_ROADS" match what you propose here?

yes, to a large degree. Slow zones on primary roads also happen (examples: [Austria](https://www.openstreetmap.org/way/30109113), [France](https://www.openstreetmap.org/way/26052765), [Germany](https://www.openstreetmap.org/way/28340560)), but these are indeed quite rare.

**Comment by westnordost** [comment]
IIRC in German traffic regulations, 30 zones cannot be priority roads. So, is even tagging such roads as `tertiary`, `secondary` or `primary` correct if they are 30 zones?

**Comment by matkoniecz** [comment]
> IIRC in German traffic regulations, 30 zones cannot be priority roads.

maybe it is different in France? And anyway I guess that road connecting small town may drop in city center to 30 zone with crossing that give no priority to anyone in attempt to reduce car speeds and therefore severity of accidents.

**Comment by westnordost** [comment]
Well that would mean that possibly any road, maybe even `highway=trunk` could be a slow zone road. 

`POSSIBLY_SLOWZONE_ROADS` triggers two things:
1. xx Zone is displayed as a selectable option when selecting the sign
2. when selecting "no sign", a dialog with this text is shown 
  
![imagen](https://github.com/user-attachments/assets/c657afab-2ff0-46b1-af17-4edd782b9019)

For non-residential roads, it is miles more probable that there is really no sign and that there is no slow zone sign. So, if that list is extended with `secondary`, etc. it would make contributing with this quest much more annoying and since that dialog would be displayed basically always if you select "no sign", users will form a habit to always click it away without reading.

**Comment by westnordost** [comment]
The solution that comes to my mind is to display the xx-zone option for all roads up to... I guess... `secondary`... or more(?) and only display that warning on `highway=residential` (before it was `residential` + `unclassified`).
