### ISSUE TITLE
Please improve storage of login data

### ISSUE THREAD

**Issue by hmartink** [streetcomplete/StreetComplete#5773]
On May 10th I was on the (beginning of a 3 week) holiday together with another mapper. On that day I noticed that openstreetmap.org had some troubles, using the website caused Cloud Fare error messages to appear.

Later that day I went mapping. I don't know if this is related to the aforementioned OSM troubles, but SC crashed several times during mapping that afternoon. Afterwards I was asked to login into OSM. This I could not do, because on this multiple country trip I did not have access to my OSM credentials. Of course, I could (and did) still map anonymously, but this reduced the vacation fun with the other mapper, as I only could upload it about 2.5 weeks later (which worked) and not "interact" with the other mapper.

In SC I now tried to review the logs, but the search is empty. Probably SC overwrites the logs after some time?

I have no idea how to reproduce this (SC crashes very seldom and I have never seen the OSM troubles described above before or since). 

So maybe you can check/improve the storage of the OSM credentials within SC or add a notice that mappers should have access to their credentials during all times (i.e. do not rely on the storage in SC), though this is the first time SC lost my credentials. For my next travel, I'll keep access to this credentials, of course.

This is on SC v58.2.

**Comment by westnordost** [comment]
StreetComplete logs out the user when on upload, the OSM API returns a HTTP 403 (Forbidden) or similar response (HTTP 401, ...). It is expected that the OSM API returns this error code when the login credentials are not correct and/or if the OAuth access token has been invalidated.
(StreetComplete does not store your credentials, only the OAuth access token, which can be revoked on the openstreetmap.org website.)

Hence, the current behavior of StreetComplete is correct and meaningful. I find it little helpful if the app would instead smack that error message into the user's face and otherwise do nothing.

Some weeks ago, OpenStreetMap was under attack by a DDOS attack, maybe other things. In that time, the OSM API basically rejected most requests (with that error code) as part of the DDOS attack response. Unfortunately, that meant that mapping activities were also hampered that way.

In regards to the crashes, I should be able to see them in the backend. Will have a look before the next release if there is anything I can fix.
