### ISSUE TITLE
Uh... "Road is private" option

### ISSUE THREAD

**Issue by goteusz-maszyk** [streetcomplete/StreetComplete#5780]
**Use case**
Sometimes when mapping areas I come across roads with questions that I'm unable to answer because I can see the road (for example cars or sth) but I can't answer the question. The only option then is to either add a note or hide it.

**Proposed Solution**
There should also be option "this area/road/etc is inaccessible". It should prompt user with options from [here](https://wiki.openstreetmap.org/wiki/Key:access).

**Comment by matkoniecz** [comment]
> "this area/road/etc is inaccessible". It should prompt user with options from [here](https://wiki.openstreetmap.org/wiki/Key:access).

the problem here is that sometimes other actions need to be taken, including ones not doable in OSM

you may have a lot of extra fun if road undergoes construction, was realigned, is out temporarily, has relations on it etc

this is too complex to handle in SC

**Comment by goteusz-maszyk** [comment]
> > "this area/road/etc is inaccessible". It should prompt user with options from [here](https://wiki.openstreetmap.org/wiki/Key:access).
> 
> the problem here is that sometimes other actions need to be taken, including ones not doable in OSM
> 
> you may have a lot of extra fun if road undergoes construction, was realigned, is out temporarily, has relations on it etc
> 
> this is too complex to handle in SC

But it's possible to add something like "this road is private" when it has a gate that you literally can't go through?

**Comment by goteusz-maszyk** [comment]
@matkoniecz it is doable, at least at partially. Please reopen

**Comment by riQQ** [comment]
What about adding the option 'Uh...' -> ~ 'this is private'?

**Comment by matkoniecz** [comment]
was discussed in #2051

if reasons for closure no longer apply, please open a new issue describing what changed since then

**Comment by matkoniecz** [comment]
Also, SCEE may have such answer or at least access to raw tags, but you need to take care to not add wrong data.

**Comment by mnalis** [comment]
Even without  using raw tag editor functionality, [SCEE](https://wiki.openstreetmap.org/wiki/SCEE) _"Expert Edition"_ fork offers `Add access` submenu to such quests, in which one can choose both general (e.g. `access=private`) as well as more detailed (e.g. `motor_vehicle=no`) access rights. 

Note that it comes with responsibilty - just because there is closed gate, does not imply it is private (it might be public but with specific opening hours, or it may be `permit` instead of `private` etc. By using "expert" fork, it is expected that you know how to handle those situations)

SCEE even supports updating  [conditional restrictions](https://wiki.openstreetmap.org/wiki/Conditional_restrictions) if one wants. As well as inserting `barrier=gate` into the way.

(Of course, it goes without saying that the more features one wants, the more complex it becomes)
