### ISSUE TITLE
Feature request: Duplicate objects

### ISSUE THREAD

**Issue by cyberchrime** [streetcomplete/StreetComplete#5787]
**Use case**
I sometimes find places where I create multiple benches, all of them having the same properties. Currently, I have to create each bench separately and solve the same quest for different benches, which is quite cumbersome. Instead, I would rather like to simply duplicate the previous bench and place it at the correct position.  

**Proposed Solution**
A very nice feature would be the possibility in Things overlay (possibly in other overlays too) to select and object, duplicate it by pressing an easily accessible button and move the duplicated object to the correct position. It would help saving a lot of time while mapping the same object multiple times at slightly different positions.

**Comment by HolgerJeromin** [comment]
You could try https://vespucci.io/

**Comment by westnordost** [comment]
As suggested, it would be quite problematic, because StreetComplete does not show what else is tagged on a POI, it only shows the type of feature.

However, to enable a sort of "duplicate this object" functionality, it would be necessary for the user to review it. E.g. there's a tree and the user wants to duplicate that tree also onto the other side of the path. But that tree could have the `genus` specified, or the trunk circumference, the year it was planted or have some `fixme` etc etc and any of these tags may not be accurate for that other tree on the other side of the path.

So, to duplicate **the whole** object, with all of its tags, won't work in StreetComplete, because the app never confronts its users with the tags or expects its users to understand them. But looking and understanding all the tags is necessary to avoid mistakes.

Now, copying just the type of object (e.g. a bench) without any further tags would in theory work in StreetComplete, but this is explicitly not what your use case is about, you want to *avoid* answering all those follow-up quests. 

<details>
<summary>
Not sure if we want to expand the discussion towards that (because it doesn't solve your use case)...
</summary>
..but regarding this, I have some comments which may also make it hard to find an implementation that is a net plus:

- UI in StreetComplete should be self-explanatory. Such a copy icon is not really self-explanatory, especially because it is unclear whether the whole object is copied or just the feature type. 
- In any case, the ✅ button is something like a primary action button, i.e. it should be alone for clarity. Other buttons, if any, should be smaller and have different shapes, i.e. call less attention.
- It could be possible to add an option to the "..." menu named "Create new feature of this type" or similar, but that would then be one more click, making it less useful
- Finally, making it faster to add (certain) presets has already been discussed here #5622 - IIRC it would be fine by me if it was implemented in the way described.

</details>

**Comment by Helium314** [comment]
@cyberchrime seeing you're already a user of SCEE: in SCEE you can (sort of) duplicate an object when creating it using the long-press -> add POI functionality. After selecting a feature, there is a "redo" button next at the bottom that sets the same tags as you had the last time when creating a feature of that type.
(Of course that's not part of any overlay, and will result in a very generic changeset comment)

**Comment by cyberchrime** [comment]
alright, thanks for your comment on this. I see that a feature like a duplicate button is quite dangerous on StreetComplete, especially because of the missing tags editor. As I definitely want to copy the full object, it is important to see and edit the tags.

@Helium314 I did not know about the "redo" button yet. Although it is a relief, it's not as convenient as a duplicate button for my use case. As SCEE implements a tag editor, do you think a duplicate button would fit into SCEE? If so, we could move to the SCEE repo and discuss how it could be implemented there.

**Comment by Helium314** [comment]
Since for duplication you need to check the tags, such a button should probably be in the tag editor. You can certainly open an issue, but I can't promise anything.
