### ISSUE TITLE
feature request: allow me to dynamically filter quests 

### ISSUE THREAD

**Issue by cascer1** [streetcomplete/StreetComplete#5789]
**Use case**

In my neighborhood, the app shows a quest to ask for bike paths on all the residential roads. So, there are no bike paths required. There is no way to enter this in the app

**Proposed Solution**

I'd like a way to perhaps make a filter that excludes the bicycle lane quest (or any quest for that matter) based on certain conditions. In this case, I'd exclude it for `highway=residential`.

This idea was sparked after the following discussion: https://www.openstreetmap.org/note/4366390

**Comment by Helium314** [comment]
The quest should not be asked for residential roads with [slow maxspeeds (<33)](https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/cycleway/AddCycleway.kt#L136), but in this case seems to be asked because `zone:traffic=NL:urban` is recognized as [`isImplicitMaxSpeedButNotSlowZone`](https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/osm/Maxspeed.kt#L19).

**Comment by mnalis** [comment]
As for that specific note, answering that _"there are no bicycle lanes present"_ will only tag [cycleway:both=no](https://wiki.openstreetmap.org/wiki/Key:cycleway:both), so bicycle routers should still use it - i.e. `cycleway:both=no` only indicates that there is **no specifically marked bicycle infrastructure**; and ***not*** that bicycles are forbidden there (which e.g. [bicycle=no](https://wiki.openstreetmap.org/wiki/Tag:bicycle=no) would mean).

So no worries, you can safely answer that there are none bicycle lanes/tracks there, and bicycle routers should still route you there (buy only maybe with somewhat lower preference if there is better bicycle infrastructure nearby going in right direction; depending on the router)
