### ISSUE TITLE
Building overlay does not refresh colors immediately (v59.0-alpha1)

### ISSUE THREAD

**Issue by pkoby** [streetcomplete/StreetComplete#5828]
**How to Reproduce**
In building overlay, select a building, change its type. The icon updates, but color doesn't change, even on map move.

**Expected Behavior**
Color should change immediately.

**Versions affected**
Android 9, SC v59.0-alpha1

**Comment by Helium314** [comment]
Interestingly it's only the extruded (3D) part of the buliding that doesn't change color. You can see a faint outline on the bottom that correctly switches color immediately. Looks like a MapLibre bug to me.

**Comment by westnordost** [comment]
Question is whether this MapLibre bug is annoying enough that while it persists, buildings should not be displayed in 3D at all?

**Comment by westnordost** [comment]
Reported here: https://github.com/maplibre/maplibre-native/issues/2746

I think I will indeed disable 3D buildings for now because of this, because the extrusion is mostly just a nice gimmick but does not serve any real use case. (The gimmick being that you should immediately see the height changes when you answer the level quests)

**Comment by pkoby** [comment]
I agree with this change for now, also because without the different color on the 3D part, it's hard to distinguish individual buildings when they're connected (e.g. rowhomes).

**Comment by riQQ** [comment]
Workaround implemented in f110c3151a9e9d5b4f260d06fde95e63e83a7f6f
