### ISSUE TITLE
(Maplibre) SC abruptly jumps to clustering

### ISSUE THREAD

**Issue by mnalis** [streetcomplete/StreetComplete#5835]
**Use case**
When zooming out, in MapLibre SC (v59.0-alpha1), quest pins are sometimes nicely reduced to just small white dots, but then at some cutoff point, whole map is **abruptly** converted to big "**clustered**" circles with values (and strange values at that (e.g. in video below at that top left part of the screen where there were 2 pins, they got replaced by number `6` when zooming out). 

That is quite distracting / disorienting and makes it hard to reconcile oneself what they are seeing... e.g.

https://github.com/user-attachments/assets/16429fb1-6b68-4e1c-8893-dd3473367e7d

**Proposed Solution**
It would be much nicer if quest pins were fist reduced to small white dots, and numbered-clusters only appearing at places where multiple  white dots are closeby. But I don't know if that is possible with MapLibre.

**Comment by westnordost** [comment]
Well, I urge you to try it out and get accustomed to it first. You have been using the previous approach for many many years, so of course you are predisposed towards how it looked and felt before. MapLibre is a different map rendering framework with different features and different behavior and we tried our best to mirror the behavior as before.

Regarding the long yearned-for cluster feature, at some point during development, the zoom levels in which quest pins and in which clusters were shown overlapped, but ultimately we ended up with a clear cut-off zoom level that switches between clusters+dots and pins+dots at a set zoom level.
I don't recall exactly the reason(s) why we ended up with this, whether there were technical difficulties or whether it just didn't feel right mixing clusters with pins, but rest assured we tested it out already and compared different alternatives. **I am not willing to change this for the time being.** (Which is why I am closing this issue as WNF)

IIRC initially the plan was to not have the dots at all anymore and to always cluster if several pins are close, but that turned out too inconvenient because sometimes you'd have to zoom in really really far for the 2+pins to appear. So in the end, we (re-)introduced the dots again at high zoom levels and only used the clusters at a certain low zoom level (below 16).
Again, not sure if there were additionally technical reasons to not show quest pins at all below zoom 16, but three UX reasons come to my mind right now why allowing quest pins to appear on lower zoom levels too I found less ideal:

- On low zoom levels, the map display would get really busy with all those pins around. It just looks odd if there are those clusters and then in the middle of these clusters, there is one pin with a specific quest because by chance, the algorithm that merges the pins into clusters didn't pick that one up as it was slightly further away from the rest. 
- One goal for having the clusters at all was to visually clear the "quest forest" on lower zooms, because that is really overwhelming for users and might be the reason why many users quit before even really starting to map. Having just clusters (and dots) on lower zoom levels achieves this effect, but mixing in full-size quest pins does not.
- To actually solve any quest, one needs to zoom in further anyway for the vast majority of quests. So it doesn't really make sense for the vast majority of quests to prominently display what exact kind of quest type it is from several parallel roads away.

**Comment by mnalis** [comment]
> Well, I urge you to try it out and get accustomed to it first

Sure, I'll try.  It does not seem like _**huge**_  dealbreaker to me at the moment, but since this is alpha, I've thought out to report it as it feels awkward and wrong (and contrary to all other maps which implement clustering that I've used). 

For example, EveryDoor also has such a "jump" where it switches from "map-only" on low zooms to "map+dots" on higher zooms, and that instantaneous switch _always_ feels wrong to me (even as it has been like that for years, from the very start AFAICT). It is the **abruptness of the switch** that is unsettling; like someone _unexpectedly_ pulled a rug under you and replaced it with paving stones (and _not_ that I prefer rugs to paving stones).



> The clustering feature is one of these tweaks.

Oh, I love clustering as the idea, and it is surely a nice improvement for all the reasons you mention.

> Regarding the long yearned-for cluster feature, at some point during development, the zoom levels in which quest pins and in which clusters were shown indeed overlapped, but ultimately we ended up with a clear cut-off zoom level that switches between clusters+dots and pins+dots at a set zoom level.

Exactly this issue - it is just that **abrupt** (as opposed as progressive, "smooth" switch, as other maps employing clustering usually do it) that is feeling quite awkward to me.

But maybe it happens rare enough not to be annoying in the actual use; time will tell :shrug:

**Comment by mnalis** [comment]
>  (and strange values at that (e.g. in video below at that top left part of the screen where there were 2 pins, they got replaced by number 6 when zooming out).

Ah, also, I remembered discussion about this part now... 

Even if there are only `2` pins displayed, "under" one pin there is just `1` quest, but under second pin there are `5` quests, so MapLibre clustering displays that (`1+5=6`) as `6` quests pending there (and not as `2` pins pending). Sounds confusing at first look, but actually makes sense I guess
