### ISSUE TITLE
Sidewalk overlay: cannot select road if adjacent sidewalks are too close

### ISSUE THREAD

**Issue by pkoby** [streetcomplete/StreetComplete#5849]
In the sidewalk overlay, at lower zoom levels or where sidewalks are close to the street centerline, it seems like it's impossible to select the road. It looks like the sidewalks are unselectable, but buffered and layered above the streets.

I wanted to wait until this next version came out to make sure I didn't overwhelm with MapLibre-related issues.

**How to Reproduce**

Try to tap on a road with adjacent sidewalks. If you do select it, zoom out and try again.

**Versions affected**

v59.0-alpha2

**Comment by westnordost** [comment]
I don't quite understand. Why don't you zoom in more, then?

**Comment by pkoby** [comment]
If there are no separately mapped sidewalks, it's no problem to select a road at any zoom level. Separately mapped sidewalks are useful reference lines, but you can't select them in the sidewalk overlay. As far as I can tell, the separate sidewalks are blocking me from selecting a road.

Yes, I can zoom in to select it, but in some instances I'm zooming in pretty far before it's not blocked by the sidewalks.

**Comment by pkoby** [comment]
As an example, at this level of zoom I can only select the road with a precise tap right on the center of the line, not buffered like I expect. The little service road without sidewalks is much easier to select.

![2024-08-28 17 58 49](https://github.com/user-attachments/assets/cb7fc0ba-6317-4d2e-aa4c-1786a13ce93b)

**Comment by mnalis** [comment]
I can see that hitting the road in `v59.0-alpha2` is harder than it was in Tangram-ES versions, but I do not see that roads _without_ adjacent sidewalk are somehow easier to hit. They seem equally hard to me. Video:


https://github.com/user-attachments/assets/8011596b-7f09-4651-bbd9-5a2f8ec036d6

**Comment by westnordost** [comment]
Well, all highlighted overlay lines have a tap buffer, otherwise they would hardly be tappable at all (the area would be just too small). Now, IIRC the separate lines should take precedence because otherwise they would sometimes not tappable at all when they are very close to the road line, as the buffer of the road line would overlap the actual separately mapped sidewalk/cyclway.

I think nothing can be changed in regards to that if a highlighted way does not respond to a tap event, the tap should instead go to the next element.

But from your video, I see that something definitely seems to be wrong regarding the calculation of the buffer. Does the buffer scale with the zoom? It shouldn't, it should always be just a few pixels to left and right of the way so that the tap area is about as big as a map button.

**Comment by westnordost** [comment]
I checked. The buffer does not scale with the zoom. But, intuitively, the tap does only register on the **center** of the line plus the fixed "fat finger" radius of 24px around the tapped point. So, intuitively zooming in does not help. I created a feature request at MapLibre: https://github.com/maplibre/maplibre-native/issues/2781

Furthermore, I worked around the issue that on lower zooms a feature is sometimes selected even if one exactly tapped on the center of another feature. This happens when two lines are close by and the "fat finger" radius is larger than the distance between these two features.
