### ISSUE TITLE
Quest suggestion: What is the title of this information board?

### ISSUE THREAD

**Issue by Vuizur** [streetcomplete/StreetComplete#5871]
### General
Affected tag(s) to be modified/added: [name=](https://wiki.openstreetmap.org/wiki/Key:name)
Question asked: **What is the title of this information board?**

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/blob/master/QUEST_GUIDELINES.md)):
- [x] 🚧 To be added tag is established and has a useful purpose - it is displayed in Organic Maps and Tracestack Topo by default without having to click on anything and about 60 percent of information boards already have it
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one) - one could add noname=yes to the minority of boards that don't have a name
- [x] 🐿️ Easily answerable by any pedestrian from the outside but a survey is necessary
- [x] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of map data (Worth the effort) - applies to maybe 100k items

### Ideas for implementation

**Element selection:**  
I think you need all tourism=information + information=board that have neither name=* or board:title=* or board_type=notice (I think most notice boards have probably no name.)

**Proposed UI:** It should be similar to other name quests. It would maybe be important to have an option like "It doesn't have a title (rather only text or illustrations)" visibly displayed.

I hope this isn't a duplicate, I couldn't find anything. Maybe one could also extend the already existing "What is the name of this?" quest instead of implementing a new one. Another thing that might be interesting are the names of information=map nodes.

PS: Thanks a lot for developing this amazing app!

**Comment by mnalis** [comment]
How many information boards do not have the name? (and how to tag it?)

**Comment by Vuizur** [comment]
355 000 boards exist, 212 000 have a name key, 27 000 are notice boards, 11 000 have board:title. (https://taginfo.openstreetmap.org/tags/information=board#combinations)

So about 105 000 boards would be affected by the quest.

I would tag them with name=, and the ones without a name with noname=yes.

**Comment by westnordost** [comment]
Sounds useful.

**Comment by flohoff** [comment]
Just as a hint. On information/board the title of the board should ne in "board:title" not in "name" as name should really only be used for names, not for descriptive issues.

As a link to a discussion i started yesterday because i saw a huge amount of SC changesets coming in:

https://community.openstreetmap.org/t/name-vs-board-title-streetcomplete/132707/1

https://wiki.openstreetmap.org/wiki/Key:board:title

**Comment by matkoniecz** [comment]
The question here is whether board title is also its name.

Clearly bad descriptive names would be say "information board, 9th on way from castle to lake".

From what I remember it was discussed few times on mailing list without agreement whether `board:title` is preferable.

`name` is at least not wrong.

BTW, if SC needs to be changed: new issue would be better. Comments in old PRs/issues are likely lost (though commenting in PR about followup issue would be fine and may be a good idea)

**Comment by mnalis** [comment]
> Just as a hint. On information/board the title of the board should ne in "board:title" not in "name" as name should really only be used for names, not for descriptive issues.

It seems that it was me who implemented PR https://github.com/streetcomplete/StreetComplete/pull/5882 😅 

Taginfo shows `name` is used order of magnitude more times then `board:title` in combination with `information=board`, and it has been there longer. However, rereading the wiki and discussions, I personally would tentatively agree that much newer `board:title` _does_ make more sense (see e.g. [this ML post](https://lists.openstreetmap.org/pipermail/tagging/2021-January/059087.html)).

However,  that quest was copy/paste of some other, and I'm not a Kotlin programmer, so I have no idea how to make it use `board:title:LANG` instead of `name:LANG` when using multiple languages support (i.e. most board titles around here are in at least 2 languages), which I'd guess probably contributed significantly in making the decision which tag to use. 🤷 

So, if/when the community reaches some consensus that `board:title` is indeed to be preferred and `name` should be discouraged on information boards (maybe at least put up a Discourse vote there in that thread, if  [proposal process](https://wiki.openstreetmap.org/wiki/Proposal_process) is too troublesome?), I'd too recommend doing what @matkoniecz said above: <strike>opening a new GitHub issue, so it can be properly tracked.</strike> -- **Update:** we now have such ticket at https://github.com/streetcomplete/StreetComplete/issues/6941
