### ISSUE TITLE
Don't ask for `cycleway:surface` or `footway:surface` if `surface` is already set on ways with `segregated=yes`

### ISSUE THREAD

**Issue by jdhoek** [streetcomplete/StreetComplete#5878]
Some mappers have noted that StreetComplete is asking users to specify the the cycleway and footway surfaces of ways tagged with `segregated=yes`, even when a valid `surface` tag is already present. For example:

https://www.openstreetmap.org/way/969241822

```
foot=yes
highway=cycleway
segregated=yes
surface=asphalt
```

This way raises both this question about the cycleway part, and another for the footway part:

![ed42b2024f9dc4dde3f3b63b1711f660ba172c8b_2_243x500](https://github.com/user-attachments/assets/cb43b590-1034-4824-b2d5-402a27aa2737)

![Screenshot from 2024-09-07 15-11-01](https://github.com/user-attachments/assets/821a85c6-9b29-41e4-82e7-79d86d437412)

However, when both parts of a segregated way have the same surface, and `surface` already specifies this, asking users to add separate `cycleway:surface` and `footway:surface` values leads to redundant information which is subsequently removed by mappers working in that area (because `surface` is already correct and the other two superfluous), leading to ways constantly flip-flopping equal tags over the course of time.

Please omit ways already tagged with a suitable `surface` tag from this question. `surface` already covers the whole width of the way if nothing more specific is tagged.

**Comment by matkoniecz** [comment]
Note that in many areas such surface values are actually incorrect (for example using what cycleway has despite footway having different one).

**Comment by jdhoek** [comment]
> Note that in many areas such surface values are actually incorrect (for example using what cycleway has despite footway having different one).

How is that relevant here? If StreetComplete wants to check if `surface=*` is correct a different question should be asked.

**Comment by matkoniecz** [comment]
Because people being asked about single surface often give confused answers which is happening less on more specific question. 

Main decision here is that extra tags is worth catching this errors. 

I guess one can research how often answer given differed from claimed surface.

**Comment by jdhoek** [comment]
In that case please improve the phrasing of the question, and stop splitting up `surface` into `footway:surface` and `cycleway:surface` when `surface` is correct. Valid tagging should not be retagged if it will lead to people deduplicating those tags later.

It's like splitting up `lit` into `cycleway:lit` and `footway:lit`: nice if that is the case, but completely unwanted if `lit` is the same for both.

**Comment by jdhoek** [comment]
(Or just stop asking these questions when `surface` is set.)

**Comment by mnalis** [comment]
Please see also:
- [SC FAQ: Why does StreetComplete add redundant tags like surface?](https://wiki.openstreetmap.org/wiki/StreetComplete/FAQ#Why_does_StreetComplete_add_redundant_tags_like_surface?) on the wiki
- https://github.com/streetcomplete/StreetComplete/discussions/4645
- https://github.com/streetcomplete/StreetComplete/issues/4526
- https://github.com/streetcomplete/StreetComplete/issues/3222
- https://github.com/streetcomplete/StreetComplete/issues/3238


Yes, the current solution is not perfect. Yet, the **alternatives** (included the ones proposed here so far) are deemed to be **even worse** (see the provided links for reasoning and discussions). No perfect solution seems to be possible, so current behaviour (adding some redundancy which is not always needed) is _least problematic_ solution.

_(given previous issues, I think it can be closed as a duplicate, as it seems to bring no new information. But if after reading the linked issues you feel there is new information that might change the decision, feel free to add it to this issue. Thanks!)_

**Comment by jdhoek** [comment]
Is there an open issue for this now?

Causing edit wars between different tools/mappers is not imperfect, it is harmful.

It looks like several other people have complained about this overtagging: at some point it would be nice if the conclusion is drawn that this is unwanted and unneeded behaviour.

A way tagged like this:

```
foot=yes
highway=cycleway
segregated=yes
surface=asphalt
```

…should not trigger a question about the surface of that way.

**Comment by mnalis** [comment]
> Is there an open issue for this now?

This one is (currently) still open...

> Causing edit wars between different tools/mappers is not imperfect, it is harmful.

In cases when _some_ people think some information is useful, and _other_ people feel it is useless, I would **always** advise to **leave** the "useless"/allegedly-redundant-information as it is (action which is _not_ harmful to either side) instead of removing said information (action which is harmful to one side).

> at some point it would be nice if the conclusion is drawn that this is unwanted and unneeded behaviour.

One might argue the opposite: that it would be nice if at some point the conclusion is drawn that this is wanted and needed behaviour. :wink:   (in fact; it has already been concluded so after long considerations; which is why I urge you to read the linked discussions - to get a full picture why it is deemed so)

**Comment by jdhoek** [comment]
> Long story short: How is StreetComplete supposed to know whether the mapped surface value is correct or not?

That is really not something for StreetComplete to bother with. `surface` is there, so please assume it is complete. For this question StreetComplete should complete ways lacking *any* surface-tag, or only one of `cycleway:surface` and `footway:surface`. Right now it is asking users 'which surface is this?' for a way *where this work was already done*. That is wasteful in the best case, and annoying if it leads to mappers wondering why additional tags not adding anything to the data except marking it is as complete for StreetComplete are added.

> In cases when _some_ people think some information is useful, and _other_ people feel it is useless, I would **always** advise to **leave** the "useless"/allegedly-redundant-information as it is (action which is _not_ harmful to either side) instead of removing said information (action which is harmful to one side).

I don't mind people tagging it one way or the other, I object to users being asked to answer a question as if that wasn't answered already and pretending that a segregated way tagged with `surface=*` does not provide sufficient information on the surface of the way. That goes against the conventional use of the `surface` tag. This is not an ambiguous tag like `sidewalk=yes` where `sidewalk=right` or `sidewalk:right=yes` with `sidewalk:left=separate` provide increasingly more information. The only thing this does is marking a way as complete for StreetComplete.

**Comment by jdhoek** [comment]
> If I now delete `cycleway:surface` and `footway:surface` here, what value do you then assign to `surface` assuming that the StreetComplete Quest would be deactivated?

Why would I not use `cycleway:surface` and `footway:surface` if they are indeed different?

> And I repeat my question: how do you know that the value is correct for both 'sides' of the way?

How do you know any `cycleway:surface` and `footway:surface` tagged are correct? That question makes no sense. `surface=*` is not ambiguous. If someone maps a way with `segregated=yes` and `surface=asphalt`, then I would assume they used those tags correctly unless I was specifically mapping that area, or engaging in some bug hunting quest. That is not what these StreetComplete questions imply they are about though. There the focus is on providing missing information, but instead they are ignoring the information already present, and now we have mappers asking why you, the StreetComplete user, are changing tags about which were already set correctly.

If I have a oneway road with two lanes I don't need to explicitly specify `hgv:lanes=no|no` if that whole road is `hgv=no`. `segregated=yes` does not change necessitate the need to specify the surfaces for the foot and cycleways either.

**Comment by mnalis** [comment]
> Why would I not use cycleway:surface and footway:surface instead of surface if they are indeed different?

Better question would be _"how would I know whether cycleway and footway surfaces of that segregated=yes way **are** same **or** different?"_ - you cannot without extra information. 
While one could invent special values like `cycleway:surface=same_as_surface` and `footway:surface=same_as_surface` (or some extra tag like `surface_is_the_same_for_both_cycleway_and_footway_of_this_segragated_way=yes`) in addition to that `surface=asphalt` (or whatever), it is much simpler, more supported, and more efficient and understandable (for everybody) to simply tag them explicitly, _even if in **some** cases it **might** be implied_. 

That is good rule of thumb everywhere in OSM -- when some tag meaning is ambiguous, you ***should add tags that make it non-ambiguous***. Good recent example is community discussion about what `oneway=yes` means on `highway=path` (i.e. does it [apply to pedestrians or not](https://community.openstreetmap.org/t/effect-of-oneway-on-pedestrians/7631)). For some the answer seems non-ambiguous, to others it seems ambiguous. 
Logical conclusion **_when some people find something ambiguous, and others find it non-ambiguous, is that it IS ambiguous afterall._** (no matter what the subject actually is).

Also, you seem to be re-asking questions which have been answered and discussed at length in previous issues (which you have been pointed to). It would help the discussion if you read them.

> There the focus is on providing missing information, but instead they are ignoring the information already present

That is one of the focuses, yes. Another is correcting/updating information (i.e. surface information is being periodically re-asked by SC, even if it was already correctly set and detailed).

Another is providing extra/updated information even if only _some_ some details are missing (e.g. when `building:levels` is provided but `roof:levels` isn't, SC will ask to enter/confirm **both**. Same as when `surface` is present on `segregated=yes` way, but `footway:surface` or `cycleway:surface` are not, or when surface value is generic e.g. "paved" SC will ask for details to put in `surface:note`)

> why you, the StreetComplete user, are changing tags about which were already set correctly.

This does not compute. If the tags _were already set correctly_, StreetComplete would not be _changing_ them (_"changing"_ meaning that new value of the surface tags _differs_ from previous ones). 


> This is not an ambiguous tag like sidewalk=yes 

Actually, it is pretty much ambiguous like that. In presence of `segregated=yes`, having only `surface=*` **_is ambiguous_** (which is why that quest is only asked on `segregated=yes` ways).

**Comment by westnordost** [comment]
I've read through this discussion and I'd agree that it has been discussed before. Closing as duplicate.

**Comment by matkoniecz** [comment]
See also https://github.com/streetcomplete/StreetComplete/issues/5877#issuecomment-2336484209 - it was reported that other location where this design issue was reported `surface` was actually wrong

**Comment by apophenic-treehugger** [comment]
I don't contest that SC makes a positive contribution to OSM

However, I've come across cases where SC does not adhere to generally accepted OSM standards; and when the developers are notified about this, they don't change the apps behaviour but reply "We can't implement the correct behaviour, so we decide to keep the incorrect behaviour and the rest of the OSM universe better adapt to _our_ standards from now on."

I don't find this good spirit. Openstreetmap is not just Streetcomplete.

**Comment by matkoniecz** [comment]
If such case happens it is useful to create an issue.

If you complain about `cycleway:surface` repeating `surface` (given where comment is) then your description of situation is not fully matching reality.
