### ISSUE TITLE
pedestrian crossing signal quests have confusing imagery

### ISSUE THREAD

**Issue by TinfoilSubmarine** [streetcomplete/StreetComplete#5893]
**Use case**

Better prompt users to understand what the crossing signal quests are about at a glance.

**Proposed Solution**

The crossing:signals quest currently uses an icon that is reminiscent of the traffic signals used for cars:
![image](https://github.com/user-attachments/assets/0464325e-a78b-43fe-9caf-e682e7f3a435)

 The rest of the quests related to traffic lights for crossings use a different, but still confusing, traffic light that is still reminiscent of car-oriented signals:
![image](https://github.com/user-attachments/assets/0b9520f5-d742-4cd0-a333-f2d6aa6111ab)

After doing some searching online across different regions, I have the impression that the predominant design features of pedestrian traffic signals are:
- Colored icons/portraits instead of simple lights
- Icons/portraits that clearly differentiate when pedestrians should and should not cross
- (Optional, maybe opportunity for another quest) Timer counting down how much longer the pedestrian has
![image](https://github.com/user-attachments/assets/e71f8272-e93c-4122-b531-005872503fe1)
![image](https://github.com/user-attachments/assets/204e7b62-84f9-468a-bc4b-4479a7e899ab)
![image](https://github.com/user-attachments/assets/e83f4673-db4f-44b2-9404-2a502bf5d59c)

It would be great if we could improve these icons to better represent what the user is likely looking at on the ground. I would be happy to assist with further brainstorming, or even designing the icons, but am not super familiar with the tools needed.

**Comment by westnordost** [comment]
The hand in that icon is for the hand that should push the button, though :-)

**Comment by TinfoilSubmarine** [comment]
Sure, but that doesn't have anything to do with the fact that an icon already exists with a hand in it, and there are no concerns about its visibility:
> Changing the circle to a hand or a little man would be too much detail for the icon that would barely be visible.

**Comment by westnordost** [comment]
Oh I see, that was your point. Well, the red and green circles in the traffic signals are much smaller than that hand.

**Comment by westnordost** [comment]
StreetComplete tags `crossing:signals=yes/no`

**Comment by westnordost** [comment]
I've decided this as will-not-fix. 

While it would be possible to replace the current icon with an icon that more represents pedestrian-style traffic lights like seen in the second picture in the starter post, it would still have the potential to confuse users that don't live in areas where there are European-style pedestrian traffic lights. To find a pedestrian-style traffic lights icon that would be recognizable easily in any region might be difficult.

But this doesn't matter that much in the end, because the quest's question _doesn't actually ask about **dedicated**_ pedestrian traffic signals, and this is **deliberate** specifically because of the mentioned proposal. I.e. users should answer "yes" (or at least: "Can't say") if there are _any_ traffic lights at that intersection that also pertain to pedestrians. So, it can very much be like in this diagram.

<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Diagram_of_signalized_crosswalks_at_four-way_intersection%2C_vehicular_signals_only.svg/240px-Diagram_of_signalized_crosswalks_at_four-way_intersection%2C_vehicular_signals_only.svg.png">

So, in this light, the current icon is actually (very slightly) helpful.
