### ISSUE TITLE
Exclusive vs. advisory bike lanes metadata seems wrong for Switzerland

### ISSUE THREAD

**Issue by delroth** [streetcomplete/StreetComplete#5894]
The [per country metadata for CH](https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/assets/country_metadata/CH.yml) currently indicates:

```
exclusiveCycleLaneStyle: yellow dashes
hasAdvisoryCycleLane: false
```

By my reading of what the "advisory" tag means and of the swiss road traffic ordinances, I think this is wrong. Per [SSV art. 74a](https://www.fedlex.admin.ch/eli/cc/1979/1961_1961_1961/de#art_74_a), only bike lanes with continuous yellow lines are exclusive. Bike lanes with dashed yellow lines can be crossed into by vehicles when necessary.

> Radstreifen sowie Fahrstreifen auf Radwegen werden durch eine unterbrochene oder ununterbrochene gelbe Linie abgegrenzt (6.09). Die ununterbrochene Linie darf von Fahrzeugen weder überfahren noch überquert werden.

*Update: VRV art. 40 is even clearer, see later comment in this thread: https://github.com/streetcomplete/StreetComplete/issues/5894#issuecomment-2345274659*

(Note, because I was confused myself: "advisory" has nothing to do with any requirements for the *cyclists* to use or not use the bike lane, and I personally think it is very oddly named. In CH, all bike lanes are mandatory to use for cyclists when they exist, but that has nothing to do with "advisory" vs. "exclusive" tagging. As far as I understand from the docs.)

Bike lanes with continuous yellow lines are sadly rare, but they do exist. In Zürich for example, a recent renovation of a very used bike route next to the main station uses a continuous yellow line. This can be seen in pictures on https://www.bikeable.ch/spots/9673 .

Unfortunately, since StreetComplete has only been allowing users to mark bike lanes as "exclusive" (when it should likely have been "advisory", and that option was not even given to users), there's now a bunch of bike lanes that are wrongly tagged :-(

**Comment by FloEdelmann** [comment]
These country metadata are stored in https://github.com/streetcomplete/countrymetadata, and indeed, `exclusiveCycleLaneStyle` and `hasAdvisoryCycleLane` don't have an explicit value for Switzerland (`CH`) and thus use the default. Would you like to open a pull request there that adds the relevant data? Maybe also other cycling-related data are wrong?

**Comment by Marc-marc-marc** [comment]
we're discussing it on the [Swiss channel](https://app.element.io/#/room/#_oftc_#osm-ch:matrix.org), it's not at all certain that the interpretation is correct, my reading of 74a.4 says that the dashed lines are for crossing another road (to allow those on the perpendicular road to cross the line and not to drive in the direction of the lane).

**Comment by delroth** [comment]
As we just found out: [VRV art. 40](https://www.fedlex.admin.ch/eli/cc/1962/1364_1409_1420/de#art_40) actually makes it very clear once we managed to actually find it:

> Führer anderer Fahrzeuge dürfen auf dem mit einer unterbrochenen Linie abgegrenzten Radstreifen (6.09) fahren, sofern sie den Fahrradverkehr dadurch nicht behindern.

That seems to definitely confirm the difference between dashed lines ("advisory", can be crossed by other vehicles) and continuous lines ("exclusive", for cyclists only).

I'll leave this open a bit longer before sending the PR just in case we find more things for/against this, but happy to take care of effecting the change myself once I'm convinced we have consensus.

**Comment by delroth** [comment]
Hmm, the documentation for "advisory" cycle lanes in https://github.com/streetcomplete/countrymetadata/blob/master/data/advisoryCycleLaneStyle.yml and https://github.com/streetcomplete/countrymetadata/blob/master/data/hasAdvisoryCycleLane.yml don't seem to match what I understand of the tag and what I see documented on the wiki. The header at the top of those files imply that "advisory" needs to be tagged when **both** 1. cars can drive on the cycle lane; 2. bikes are not mandated to use the cycle lane. CH is in the case where dashed cycle lanes are (1) but not (2). This seems to qualify as "advisory" per [the tag documentation on the wiki](https://wiki.openstreetmap.org/wiki/Key:cycleway:lane), which says:

> In **most** countries where they exist, these cycle lanes are not obligatory for cyclists

My emphasis on "most", which does not seem to exclude the case where the "advisory" cycle lanes are mandatory for cyclists.

Since @westnordost both introduced this data to StreetComplete and also made [the initial proposal](https://community.openstreetmap.org/t/dashed-soft-cycle-lanes/82357/53) I'm hoping this can be clarified! IMO the doc header in StreetComplete's country metadata should be fixed. Happy to take care of that along the way when I send the CH change.

**Comment by westnordost** [comment]
So, `hasAdvisoryCycleLane` is maybe not ideally named. The "full" name would be `hasConceptOfDifferentiationBetweenTwoTypesOfCycleLanesOfWhichOneIsMerelyAdvisory`. 

The categorization exclusive vs advisory is not a fine one and the details will differ in different countries. It **usually** means:

**Advisory** is not mandatory for cyclists (except for the obligation of cyclists to keep to the right side of the road), cars may cross and even stop on it, if they need to, and since they are not mandatory for cyclists, they do not need to satisfy certain minimum safety criteria, such as minimum width or minimum distance to parking cars.

**Exclusive** are usually mandatory for cyclists and cars may not use this lane in any way. Note, though, that on e.g. intersections, exclusive cycle lanes may be crossed by cars when they don't obstruct cyclists. Usually they are dashed in those sections, that doesn't mean, however, that these sections are advisory, they are just dashed sections of exclusive cycle lane.

If for a country the value in `hasAdvisoryCycleLane` is `false`, it means that StreetComplete will not show any distinction between exclusive and advisory cycle lanes in it's UI, and also don't call the possible selection "Exclusive cycle lane" but just "cycle lane".

That's why I asked, if there is actually any confusion or problem with what StreetComplete tags or how it displays it in the UI.

**Comment by westnordost** [comment]
So, an "advisory" cycle lane is definitely a second class cycle lane, depending on whom you ask (and in which region), either worse than nothing or worse than a normal cycle lane.

Now, as I understand it, the dashed cycle lane in Switzerland is not a second class cycle lane, because that is basically the only cycle lane you have and for which safety requirements (min width, min distance to parking lanes, ...) are indeed in place, i.e. they are proper cycle lanes. So, even if a few cycle lanes with a continuous line exist in Switzerland, I don't think the solution to tag all others as "advisory" would be correct.

**Comment by westnordost** [comment]
> The UI is confusing because "advisory" lanes are shown as dashed white lines (doesn't exist in CH)

They shouldn't be shown at all in Switzerland.

**Comment by delroth** [comment]
> that is basically the only cycle lane you have

That is not the case, as quoted above the Swiss Verkehrsregelnverordnung clearly defines two types, and I posted in the initial comment a link to a spot that uses continuous yellow lines aka. exclusive lanes. They're not frequent but they exist, both by law and in practice.

> and for which safety requirements (min width, min distance to parking lanes, ...) are indeed in place

I wish, but no, there are no such things for dashed lines lanes. Maybe min width, but not min distance to parking lanes, and it's common to see cars drive in them when they need to.

**Comment by westnordost** [comment]
Anyway, to summarize:

I am of the opinion that the distinction between advisory and exclusive cycle lanes (with `cycleway:lane=advisory/exclusive`) does not make sense in Switzerland because the dashed cycle lane (the normal one) is not a second class cycle lane, as was explained to me by a Swiss person. (If this is incorrect, ...)

This can be changed in StreetComplete of course, following a local community consensus. Then, both options will be available - the cycle lanes with dashed markings (advisory) and the ones with continuous markings (exclusive).

**This however means that after this change, all cycle lanes in Switzerland will be displayed as missing/incomplete** in the app, because the distinction between advisory and exclusive will be missing for most roads. I.e. red in the overlay and a quest will be asked for that.

So, please open a discussion in the Swiss community forum (and mailing list) about this whether this is something the Swiss community really wants to change. You can post the link to the discussion here for reference.
