### ISSUE TITLE
Quest suggestion: How long does this escalator take?

### ISSUE THREAD

**Issue by k-yle** [streetcomplete/StreetComplete#5904]
### General
Affected tag(s) to be modified/added: [`duration=*`](https://osm.wiki/Key:duration)
Question asked: **How long does this [escalator/travelator] take?**

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/blob/master/QUEST_GUIDELINES.md)):
- [x] 🚧 To be added tag is established and has a useful purpose
  - _established:_ routing engines like GraphHopper already consider the `duration` tag[^1]
  - _useful purpose:_ there is no correlation between an escalator's length and duration, since escalators are programmed to different speeds[^2]
    [![image](https://github.com/user-attachments/assets/4033db9e-3aed-48fb-830c-c241c45a6b89)](https://gistcdn.githack.com/k-yle/5e7bb15fc2c711bca36160fb7932233b/raw/2b6b807a8bf625b47bab3cac0ac56bf5dbcc223d/graph.html)

- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by any pedestrian from the outside but a survey is necessary
- [x] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of map data (Worth the effort)
  - There are over 28,000 escalators/travelators in the database (`conveying=*`)[^4]

### Ideas for implementation

**Element selection:** if [`highway=*`](https://osm.wiki/Key:highway) & [`conveying≠no`](https://osm.wiki/Key:duration) & no [`duration`](https://osm.wiki/Key:duration) tag

**Metadata needed:** none

**Proposed UI:** TimePicker (`mm:ss` format). As a bonus, the quest UI could include a stopwatch, but this is probably overkill

[^1]: https://github.com/graphhopper/graphhopper/blob/05b2db5732352f9c4a7cd75f77129a68dbd60116/core/src/main/java/com/graphhopper/reader/osm/OSMReader.java#L501-L531
[^2]: See [this graph](https://gistcdn.githack.com/k-yle/5e7bb15fc2c711bca36160fb7932233b/raw/2b6b807a8bf625b47bab3cac0ac56bf5dbcc223d/graph.html) (and [the source code](https://gist.github.com/k-yle/5e7bb15fc2c711bca36160fb7932233b))
[^4]: [taginfo for `conveying`≠`no`](https://taginfo.osm.org/keys/conveying#values)

**Comment by westnordost** [comment]
Can you give more information on the element selection? Currently, it looks like as if you envision this quest to be asked for just about any road.

**Comment by matkoniecz** [comment]
`conveying=*` is mentioned and should cut down strongly on selected values

**Comment by k-yle** [comment]
Yes, I imagine this quest would only apply to features that already have `highway=*` and `conveying=yes`/`forward`/`backward`/`reversible`. 

If you want to limit it even more, `highway=*` could be replaced with `highway=steps`/`footway`,  since these are values that the iD presets use for "Escalator" and "Travelator"

**Comment by westnordost** [comment]
Oh, I misread. I thought this was about elevators.

**Comment by kmpoppe** [comment]
I wonder, do we (also) think it would be helpful to have a quest that applys to `conveying=yes` to ask for the direction? There is (was) an example of an implementation with the one-way quest I could imagine for that.

Would only affect 13k objects though 🤔💭

**Comment by FloEdelmann** [comment]
@kmpoppe see #4857. I'll hide your and my comment as off-topic here, we can continue in the other issue.

**Comment by westnordost** [comment]
Overall, I don't think it is worth to implement and also not worth the time for users to answer.

Reasons:

- The deviation from the mean, i.e. the estimation that would be used by routers is really small. Maybe not relatively, but absolutely. It isn't going to matter much if the time estimation of a pedestrian path is 10 seconds off.

- it is difficult to answer because places with escalators are usually indoor in multi-storey places (malls, terminals, train stations, ...) which cannot be displayed in a clear manner in STreetComplete. (I.e. it is always a question which floor exactly is meant, which direction etc.)

- it's not clear whether there is proper router software support for setting such multi-storey places as start- or endpoint of a journey, i.e. end e.g. at a shop that is situated on the 4th floor of a particular mall

In any case, if this issue is at one time reconsidered, should also look at #4857
