### ISSUE TITLE
Auto theme gone in SC v59

### ISSUE THREAD

**Issue by Atrate** [streetcomplete/StreetComplete#5905]
I've looked through the closed issues by searching "auto theme" and I couldn't find any reasoning behind the removal of the "Automatic" theme option from SC. Why was it removed? It was very useful for me and "System default" does not provide the same functionality.

**Comment by FloEdelmann** [comment]
It was removed in #5719:

> Removed the "auto" theme setting, which would change the theme based on time of day. Users that selected that option before will follow the system setting now. (As of June 2024, 95% of active installs from google play use an Android where AUTO setting is deprecated)

**Comment by Atrate** [comment]
> It was removed in #5719:
> 
> > Removed the "auto" theme setting, which would change the theme based on time of day. Users that selected that option before will follow the system setting now. (As of June 2024, 95% of active installs from google play use an Android where AUTO setting is deprecated)

Thanks for the reference. Is there any reasoning behind that, though? I prefer my device to be in dark theme always but SC and OsmAnd (and some other apps) to switch based on day-night automatically regardless.

**Comment by matkoniecz** [comment]
"As of June 2024, 95% of active installs from google play use an Android where AUTO setting is deprecated" - so it was likely not worth expanding extra effort to reimplement something that is scheduled for removal anyway

**Comment by westnordost** [comment]
Yup, I removed it due to the reasons cited. I am sorry to hear that you actively and consciously used that feature.

I (too) much prefer the light map display, even though I have my phone on dark mode usually.

I wonder if **_instead_** of a setting to change the app's theme away from the system default (I don't see a reason to have the about, settings, quest forms etc. screen appear in a different theme than the system default), there could be a setting to only switch the map theme between light and dark.

Although, that would be inconsistent to other map apps. OrganicMaps has "auto" by default, which however seems to be not working, it is always "light" for me. If I change the theme, indeed all UI is changed, not only the map. Google Maps is by default also always "light". Available for selection, there is only "light", "dark", and "system default", like in SC now, but it also changes all the UI, not only the map.

**Comment by Atrate** [comment]
> I wonder if instead of a setting to change the app's theme away from the system default (I don't see a reason to have the about, settings, quest forms etc. screen appear in a different theme than the system default), there could be a setting to only switch the map theme between light and dark.

That's how OSMAnd can do it and I like that functionality too.

> the default theme could be switched to the light theme. I certainly would like that

I don't know about others, but one reason I dislike the dark theme in SC and much prefer the dark one is the fact that the dark theme has so much less contrast and shows way fewer details (like grass/forest areas, which are just a shade or two different from the bg). Do you think it would be good to incorporate a higher-contrast version of the dark theme, maybe kind of like SCEE does it? That would also help with accessibility IMO.

**Comment by matkoniecz** [comment]
If theme can get its readability improved I would try it first with regular dark theme.

Looking at https://github.com/streetcomplete/StreetComplete/blob/master/CONTRIBUTING.md#issues-with-dependencies has https://github.com/streetcomplete/maplibre-streetcomplete-style link

maybe there were also attempts in old style? See https://github.com/streetcomplete/streetcomplete-mapstyle/pulls

**Comment by Atrate** [comment]
>  I.e. they necessary need to be uglier than normal dark theme

I find that completely subjective, IMO the SCEE high-contrast dark theme looks significantly better than the normal dark theme.

**Comment by matkoniecz** [comment]
If someone has ideas for high-contrast style that would make regular dark mode worse, it would be best to create issue at https://github.com/streetcomplete/maplibre-streetcomplete-style

The same for improvements to dark style, including porting changes from SCEE

(I am not using dark styling at all in general)

**Comment by westnordost** [comment]
Rather than create an issue, better check out that project and play around with the colors yourself. It's all a simple HTML at the end, so it is dead simple to experiment with it.
