### ISSUE TITLE
Clearly state that "No, but crossing is possible" means it's informal

### ISSUE THREAD

**Issue by vfosnar** [streetcomplete/StreetComplete#5913]
I almost made the mistake of using this option to map weird driveway-sidewalk crossings because it wasn't clear it's for informal crossings only.

Let's add a little more description, like "Not formally, but crossing is possible (e.g. a path crossing a road)"

**Comment by goldfndr** [comment]
#5443 ?

**Comment by vfosnar** [comment]
Thanks for pointing me to this issue, that's exactly my problem. Sorry, I tried searching for similar issues but didn't find this one.

**Comment by mnalis** [comment]
I think it would be better that you reopen this issue @vfosnar  (and link the old one as it already does), instead of adding comments to old closed issue (comments on closed issues have a high chance of being missed / forgotten).

 But do make your case what you think is different than the old issue (e.g. any new information, your use case, suggestion for a fix which were not rejected before, etc)

**Comment by vfosnar** [comment]
I'd rather reopen the old issue as it has more relevant discussion and has been closed because there is not enough evidence.
