### ISSUE TITLE
Quest pin flashes a moment after selecting quest

### ISSUE THREAD

**Issue by riQQ** [streetcomplete/StreetComplete#5923]
**How to Reproduce**

https://github.com/user-attachments/assets/02abfcc3-9a40-47a3-bf74-fd634b218d84

**Expected Behavior**

No flashing.

**Versions affected**

59.0

**Comment by westnordost** [comment]
With flashing, you mean that it vanishes for a tiny moment only to pop up larger later?

This happens because the pins are being hidden while at the same time, a new layer is added that only displays the pin and its enlarging animation.

I don't think this can be fixed, I would not even say this is a bug, rather it is an imperfection.

So why does the layer 2 not immediately show when layer 1 is turned invisible? This could either be an internal thing in MapLibre, or it could also be caused by StreetComplete: The selected pin layer is added not immediately in that call but first checks in the background if the displayed icon has been loaded into MapLibre yet (and if not, do it). In any case, as I wrote, I don't think anything could be changed here. (You are welcome to try though, see `MapFragment::highlightPins`)

**Comment by westnordost** [comment]
I noticed that for you, the enlarge-animation doesn't play at all. The reason for that could be that there's too much happening on the UI thread (including e.g. having the debugger connected) or you have animations off.

**Comment by westnordost** [comment]
In case you have animations off, this issue should be reopened because in that case it is possible there is some problem with the animation (i.e. it doesn't show at all until after the animation ended)

**Comment by riQQ** [comment]
> With flashing, you mean that it vanishes for a tiny moment only to pop up larger later?

Exactly

> I noticed that for you, the enlarge-animation doesn't play at all. The reason for that could be that there's too much happening on the UI thread (including e.g. having the debugger connected) or you have animations off.

I think that is my bad. The video is actually from alpha4 as I have recorded already awhile ago. But I reproduced the issue with 59.0 and there the enlarge-animation is shown.

**Comment by westnordost** [comment]
Oh, interesting, I didn't remember that I changed anything there recently.

**Comment by riQQ** [comment]
This made me go back to alpha4 and the enlarge-animation is there, too. So there must be some edge case that breaks this animation, because animations are enabled on my phone and I have never changed the animation settings.

**Comment by westnordost** [comment]
No, I think there's just too much happening on the main thread (e.g. opening of the quest form)
