### ISSUE TITLE
What's new pop-up is too big

### ISSUE THREAD

**Issue by Jean-BaptisteC** [streetcomplete/StreetComplete#5925]
**How to Reproduce**
- Install latest update and open app
- Press what's new pop-up

**Expected Behavior**

Pop-up have an adapted size following size of changelog text

**Versions affected**
v59.1

<img src="https://github.com/user-attachments/assets/78275783-8aed-4e6f-8a18-98352428dad8" height=300 />

**Comment by westnordost** [comment]
This is not possible in Jetpack Compose (yet). Either the dialog is scrollable and extends to the full size (or a previously set fixed size) or it is not scrollable at all. The changelog dialog needs to be scrollable.

To me, this is a bug and/or missing feature in Jetpack Compose. See https://issuetracker.google.com/issues/217151230

I already put some work into working around that dialogs in Jetpack Compose are not scrollable, but this comes with the mentioned caveats, unfortunately. So, I am not up to improving further on something that I hope will get fixed some day upstream.

If others are interested in solving this, have a look at `ScrollableAlertDialog.kt`. An option would also be to instead open the "What's new" dialog full screen so that it is not a dialog. However, since that would be quite disruptive, there should be some dialog-like window first similar to when you get a message about having mails in your OSM inbox. Only after tapping the "show me what's new" button, then the changelog would be displayed in a new screen.

**Comment by westnordost** [comment]
But I noticed that the dividers are duplicate. That's why you see a divider just below the changelog HTML and another at the bottom. I just removed them.

**Comment by HolgerJeromin** [comment]
ref 947196eaebe934782193b34f005f3ab404906d3f
