### ISSUE TITLE
Clearly state surface=compacted is only for machine compacted tracks

### ISSUE THREAD

**Issue by vfosnar** [streetcomplete/StreetComplete#5927]
Compacted surface can be easily confused with dirt for paths and smaller roads. It should be clearly stated that compacted is only for machine compacted tracks, for example by changing the name to "Compacted (with a roller)"

I can do a quick PR if this gets a pass and add Czech translation too

https://wiki.openstreetmap.org/wiki/Tag:surface%3Dcompacted
https://wiki.openstreetmap.org/wiki/Tag:surface%3Ddirt

**Comment by westnordost** [comment]
I don't see this statement made in the wiki. The wiki states "compacted **e.g.** with a roller", not "compacted with a roller".

It doesn't matter how the compacted surface was made.

If it looks like a duck, swims like a duck, and quacks like a duck, then it probably is a duck.

**Comment by matkoniecz** [comment]
"Compacted gravel" is probably more important appendum as some used it for compacted earth/dirt

(still not sure about adding it and is it actually more clear)

**Comment by westnordost** [comment]
Probably, yeah. May be difficult for the German translation, because "gravel" translated to German is this:

https://duckduckgo.com/?t=ffab&q=kies&iax=images&ia=images

I.e. always quite large stones, whilst "compacted" should be a mix of sand, small gravel etc.

**Comment by matkoniecz** [comment]
Though "mix of small and larger gravel and loose elements such as sand/clay/dirt that was compacted, typically with a roller" is hard to shorten otherwise and keep clear

(unless someone has any great idea?)

------------------------------------------

I though about adding expanded description of surfaces, but sadly `hint` and `hintImages` are not a good fit here ( https://github.com/streetcomplete/StreetComplete/blob/f99db3d1962c21d59d1dade6ece65cd96ebff237/app/src/main/java/de/westnordost/streetcomplete/quests/tactile_paving/AddTactilePavingSteps.kt#L33 )

and it would require some more dedicated form element

When I observed less experienced people using StreetComplete I noticed that many of them were confused by surfaces - and attempts were made to find better images but it was not fully eliminated. Maybe making description of surfaces available in app, as suggested at https://eeee.no/@erik/112894257072009817 would help?

**Comment by mnalis** [comment]
> It doesn't matter how the compacted surface was made.

Agreed, hand-operated vibrating plate compactors / rammer compactors are often used instead of roller compactors...

But it perhaps could be clarified just by adding that _"e.g."_ (i.e. as _**"Compacted (e.g. with a roller)"**_, but it any case it looks quite long, and probably would eat up most of the picture (3 lines would eat about half of a picture on my device), which would be annoying/confusing in it itself...

> Though "mix of small and larger gravel and loose elements such as sand/clay/dirt that was compacted, typically with a roller" is hard to shorten otherwise and keep clear

In Croatian, we call those compacted gravel surfaces _"Makadam"_ (likely the same source as for [Macadam](https://en.wikipedia.org/wiki/Macadam)),  but I'm not sure if it is well understood in English commonly (and seems it can be confused, as there were apparently things called _"tar-bound macadam"_ which become popular by trade name _"tarmac"_) - Croatian apparently picked it up well before it got to that phase...

> Maybe making description of surfaces available in app, as suggested at https://eeee.no/@erik/112894257072009817 would help?

Maybe, but (apart from significant extra translator work), there remains the question of how it would be invoked (long press on a picture? separate info button on each picture?)

Perhaps easiest might be to add regular `(i)nfo` button, and explain just that confusing case of `compacted`? (and perhaps other bigger confusions if we have them)?

**Comment by mnalis** [comment]
> https://eeee.no/@erik/112894257072009817 

That one is informative... there is common confusion between several types of gravel, and it is not the first time I've seen it.

Perhaps renaming in English:
- "compacted" -> "compacted gravel"
- "fine gravel" -> "loose fine gravel"
- "gravel" -> "coarse(r) gravel"

And giving instruction for translators in POedit how they should translate those (i.e. not literally word-by-word, but by how are those named in their language, to keep it clearly distinguishable from one another). 

> Probably, yeah. May be difficult for the German translation, because "gravel" translated to German is this:
> I.e. always quite large stones, whilst "compacted" should be a mix of sand, small gravel etc.

Giving instructions to translators would hopefully help with that issue.

**Comment by RubenKelevra** [comment]
> Probably, yeah. May be difficult for the German translation, because "gravel" translated to German is this:
> 
> https://duckduckgo.com/?t=ffab&q=kies&iax=images&ia=images
> 
> I.e. always quite large stones, whilst "compacted" should be a mix of sand, small gravel etc.

Nope, gravel *might* be translated to this, but actually it's more a false friend. Kies referres more to what you would find in a river bed - pebbles in English. The right term in German is Schotter, which refers to "Bruchstein" - crushed stones with sharp edges, compared to round edges of pebbles.

**Comment by matkoniecz** [comment]
> Adding more "hint" texts and similar would just blow the interface out of proportion and ultimately make it take longer to find the value one is looking for.

even if they would be hidden by default like other hints are nowadays?

**Comment by RubenKelevra** [comment]
> Hm, let's rename it to "compacted gravel", then.
> 
> Adding more "hint" texts and similar would just blow the interface out of proportion and ultimately make it take longer to find the value one is looking for.
> 
> Regarding translations to other languages - this is rather something to worry about for the translators. E.g. if the current German translation is fine, it stays fine.

Yeah, it's fine (had to check, I'm using SC in English) 😬 

![Screenshot_2024-09-27-06-57-36-159-edit_de westnordost streetcomplete expert](https://github.com/user-attachments/assets/3bc35b7a-bb74-4c3c-8cb8-ff31854e25f1)

**Comment by matkoniecz** [comment]
> Yeah, it's fine (had to check, I'm using SC in English) 😬

this looks like SCEE to me

**Comment by RubenKelevra** [comment]
> > Yeah, it's fine (had to check, I'm using SC in English) 😬
> 
> this looks like SCEE to me

That's true. SC refused to start for me atm, again. See https://github.com/streetcomplete/StreetComplete/issues/5850 ;)

**Comment by RubenKelevra** [comment]
> Good, so the German translation can be "Verdichteter Splitt"

I think the right technical term for this would be "Splitttragschicht" or "Schottertragschicht" depending on the size. 

Here's an example how this looks:

https://rohstoffgewinner.com/referenz-schotter-waldwegneubau-oberwiesenthal/

But for me your suggestion sounds fine. :)

**Comment by Bauer33333** [comment]
> I think the right technical term for this would be "Splitttragschicht" or "Schottertragschicht" depending on the size.

Schottertragschicht is the gravel you put below a (for example asphalt or paving stones) topping, you link says that it will get 14 cm of asphalt on top. A Splittragschicht does not exist, the material is completely unsuited for thick layers.
The technical term you are searching is "wasserbundene Deckschicht", but I guess the majority of the poulation does not understand that. 
There also is a "hydraulisch gebundene Deckschicht", looks about the same but the fine gravel is glued together, eg. with cement.

Sorry for bumping this, but it is right down my alley.
