### ISSUE TITLE
Add previous tag value to answer history details

### ISSUE THREAD

**Issue by riQQ** [streetcomplete/StreetComplete#5971]
**Use case**
As an experienced OSM user I want to quickly see the previously tagged value directly in the app to root out possible misunderstandings or possible software bugs without having to resort to using another (web) app.
If a value was already previously tagged, StreetComplete doesn't show it in the question form in all cases.

**Proposed Solution**
Add the previous value to the answer details in the answer history. The benefit of this solution is that it doesn't clutter the already crammed question form for every user. There is enough space in the answer details form to add this additional information and the additional information isn't harmful as the answer history details are only check on a few occasions.

**Current answer details form**
![Screenshot StreetComplete answer details](https://github.com/user-attachments/assets/78e1347a-b7f3-458d-bf92-21f87df20d7e)

**Comment by westnordost** [comment]
Well, I am not convinced.

Obviously, there is not much space in that dialog. Imagine how the dialog would look like for an `opening_hours` update when the hours are updated - (even less) barely readable.

So, I don't quite get your use case. How does it matter what was tagged before, when you were just there, and checked the situation, and answered accordingly?

**Comment by riQQ** [comment]
> Obviously, there is not much space in that dialog. Imagine how the dialog would look like for an opening_hours update when the hours are updated - (even less) barely readable.

There's plenty of space imo, the form can even grow to the top and bottom (and these screenshots are with bigger than default text size). Tag values are limited by the API to ~255 characters:
![Screenshot opening hours answer detail](https://github.com/user-attachments/assets/3454e7c5-1dd3-43cc-91bb-1f25c4364f1e)

> So, I don't quite get your use case. How does it matter what was tagged before, when you were just there, and checked the situation, and answered accordingly?

As I wrote above, maybe I made a mistake or misunderstood something. It would also help advanced users in the case of #5883. I also tried to look it up after getting a track type conflict dialog.

**Comment by westnordost** [comment]
Okay, so the use case is that a user either 
- realized that he probably just made a mistake or
- doesn't fully trust whether he correctly understood an answer but is an experienced OSM user and knows how things should be tagged.

So, for any of the two, I don't see how displaying the previous value should help. An experienced user who wants to do quality assurance or has doubts about what SC tags can also (later) check the OSM history. The tags are displayed for two reasons: 1. for educational purposes for OSM newcomers and 2. to assist in finding the correct edit to undo when one realized that one just made a mistake.

> I also tried to look it up after getting a track type conflict dialog.

Which I intend to remove. It doesn't help at all. I am not "finished" with #5883 yet, but I do lean towards the attitude that if it was e.g. `surface=dirt` + `tracktype=grade4` before and now it is asphalted and `surface=asphalt` is does not introduce error if it stayed `tracktype=grade4` because up until the point where the mapper updated the surface, *both* tags were wrong, now only one of the two tags is wrong. So, at most, it is a missed opportunity to also correct the tracktype, but it does not _introduce_ an error.
Or in short, that dialog, it doesn't help. Knowing before the surface and tracktype of the object shouldn't influence the user in answering what he now sees, and it is not his responsibility to worry about that these two OSM tags are in sync or review what OSM tags are being tagged.
