### ISSUE TITLE
Option "access is private" for surface requests

### ISSUE THREAD

**Issue by W-T-Developer** [streetcomplete/StreetComplete#5975]
**Use case**
Some streets, esp. of type service, are not marked as access = private even if they are, so StreetComplete asks to set a surface type.

**Proposed Solution**
In the 3-dot-menu there should be an option "this street is private".

**Comment by westnordost** [comment]
"this street is private" is orthogonal to the question asked. The question asked is "What's the surface here?", so whether or not it is accessible for the mapper is not even asked, hence it would be out of place to provide that answer option.
(Rather, or more precisely,  it would have to be "Can't say because I may not access the street because it is private")

So, "can't say" should cover that. Usually, if it is e.g. just a private driveway, you'll still be able to answer it, even if it is private. If it is about larger areas, then several roads might need to have `access=private` added, maybe gates added, etc.. So, I think to leave a note in such a case is fine. So far, as far as I know, noone complained that SC users create too many notes about that they cannot solve quests because they may not access a road/area.

I am so quick in disregarding this feature request here because such an option would then need to be added to just about any quest at least on ways to be consistent, because just about any quest filter out private elements. And I don't think that it is worth the effort and UI clutter to do this.

**Comment by matkoniecz** [comment]
Also, this was discussed some time ago.

**Comment by mnalis** [comment]
> Also, this was discussed some time ago.

Yes, see  https://github.com/streetcomplete/StreetComplete/issues/5780#issuecomment-2265773074 (includes a workaround for how to directly set access to private)...
