### ISSUE TITLE
access=permissive

### ISSUE THREAD

**Issue by joernheissler** [streetcomplete/StreetComplete#5987]
**Use case**
Hi, #1114 added the "access" question for `leisure=playground`. I'm missing the option `permissive`.
Use case is privately operated playgrounds where the public is not kept out by fences or signs.

Pro:
* I started a discussion on those in the [forums](https://community.openstreetmap.org/t/sind-privat-betriebene-spielplatze-offentlich-nutzbar/120712/12) (German). Most answers tend towards `permissive`.
* https://wiki.openstreetmap.org/wiki/Key:access states:
  * `yes`: "The public has an official, legally-enshrined right of access"
  * `permissive`: "Open to general traffic until such time as the owner revokes the permission which they are legally allowed to do at any time in the future."

  In my opinion, the operators are indeed allowed to put up a sign like "Only children from this block of flats, and their visitors, may play here." or if neighbours complain about noise, the private operators may legally forbid individual children to use the playground.

Con:
* https://wiki.openstreetmap.org/wiki/Tag:leisure=playground does not mention `access=permissive`.
* Taginfo counts 2_675 uses of `access=permissive` which is only 1.2%, so it's not used too much.

**Proposed Solution**
Add the fourth option `permissive`. The text for `quest_access_permissive` could be a bit tricky to avoid confusion. Best (but too verbose) I can come up with is: "There are currently no restrictions, but the operator could impose some at any time."

**Comment by matkoniecz** [comment]
How mapper is supposed to distinguish yes and permissive?

Is there is even equivalent of right of way for playgrounds? 

Also, note that the same applies for parkings.

**Comment by matkoniecz** [comment]
> There might be sign that a playground's operator is municipal -> yes.

Why that instead permissive?

**Comment by joernheissler** [comment]
> Why [`yes`] instead permissive?

It's not that much different from a street or path. A municipally operated way is usually `yes` (perhaps only for some modes of transportation). A privately operated way is often `permissive`.

> Municipal playground can become limited in access or only for children from school or sold.

Again, same goes for ways. They can be razed or closed for some traffic, etc, but we still tag them `yes`.

The difference is that the operator of a private way or playground may close it for the public at any time without giving any reason, hence `permissive`.

A municipal operator however can't just close a way or playground to the public or for specific people without giving a good reason.

**Comment by matkoniecz** [comment]
> The difference is that the operator of a private way or playground may close it for the public at any time without giving any reason, hence permissive.

municipal operator can do the same 

And requirement for stating reason does not differentiate between `yes` and `permissive`.

`yes` `permissive` distinction is for "legally protected right of the public to pass and re-pass on specific paths" - https://en.wikipedia.org/wiki/Rights_of_way_in_England_and_Wales

See also https://wiki.openstreetmap.org/wiki/Access_provisions_in_the_United_Kingdom

if such thing does not apply, then `yes` and `permissive` is effectively the same

And for playgrounds it happens so rarely that I would not expect that person tagging `access=yes` meant legally enshrined right to access of playground that cannot be easily terminated.

**Comment by matkoniecz** [comment]
Is there indicator that statutory legal right of access is applicable to playgrounds?

And it is tagged using `access=yes` `access=permissive` distinction?

Also, note https://wiki.openstreetmap.org/wiki/Key:operator:type - if someone wants to differentiate between public and privately run playgrounds.

**Comment by matkoniecz** [comment]
Also, maybe someone German-capable can look through linked https://community.openstreetmap.org/t/sind-privat-betriebene-spielplatze-offentlich-nutzbar/120712/12 ?

I can try but it sounds like case where automated translation can easily mangle things without warning.

**Comment by matkoniecz** [comment]
> `access=permissive' should be used if the playground is neither fenced in (physical ban) nor prohibited by a sign (written ban)

that is fine, but `access=yes` would be (AFAIK) equally fine here

Also, municipal playgrounds also can be not fenced, without prohibition sign.

**Comment by matkoniecz** [comment]
> As far as I understand the statements from the thread correctly, access=yes (at least in Germany) should be used in public playgrounds that are usually signposted like [this](https://commons.wikimedia.org/wiki/File:Spielplatzschild_Wirbel_(Metzingen).jpg) or [this](https://commons.wikimedia.org/wiki/File:Schild_am_Spielplatz_Dreikreuzenstra%C3%9Fe_in_Hannover-Linden_S%C3%BCd.jpg).

that is redefinition of `access=yes` and `access=permissive`

Is there indicator that statutory legal right of access is applicable to playgrounds in Germany?

**Comment by matkoniecz** [comment]
I assume that publicly signposted playgrounds can be torn down, turned into playground accessible only by children from some specific school etc. Is this right?

**Comment by westnordost** [comment]
Note that this is not only about playgrounds. A lot more things are (most probably) on private property, yet their usage is accessible to the public because there is neither a sign nor a barrier that prevents them to use it. E.g. [the bicycle parking directly in front of house 3 here](https://www.google.de/maps/@53.5733977,9.9444254,3a,51.6y,299.58h,92.78t/data=!3m7!1e1!3m5!1sowz5WL--er_R5W7ueF9lhQ!2e0!6shttps:%2F%2Fstreetviewpixels-pa.googleapis.com%2Fv1%2Fthumbnail%3Fcb_client%3Dmaps_sv.tactile%26w%3D900%26h%3D600%26pitch%3D-2.7786999246403212%26panoid%3Dowz5WL--er_R5W7ueF9lhQ%26yaw%3D299.57983614665955!7i16384!8i8192?coh=205410&entry=ttu&g_ep=EgoyMDI0MTAyNy4wIKXMDSoASAFQAw%3D%3D). So, that would be the definition of `access=permissive`, I'd say.

But I am not sure if I want to require StreetComplete users to make that distinction because it can in many cases be pretty difficult to decide whether it is really on private property or not. After all, `permissive` is rather a subcategory of `yes`, as for pretty much all intents and purposes, it can be treated as the same.
Plus, the selection options are already now quite a lot of text (at least compared to "yes"/"no")

![grafik](https://github.com/user-attachments/assets/2374b6c4-d6d9-436c-81ca-8669f6033884)

**Comment by mnalis** [comment]
> (I also wonder what made us choose such a complicated wording - "Any member of the general public"... so, "Anyone"?

AFAICT, it probably originated around here: https://github.com/streetcomplete/StreetComplete/issues/3433#issuecomment-956290904

> And if you are not super-strict then =yes and =permissive is exchangeable in this context.

Yes, I'd agree... And if the situation is _"it's complicated"_, for SC use case it is probably better to leave a note (so one can e.g. fill-in `operator=*`, `owner=*`, `operator:type=*` from a picture of a sign, or add `access:conditional=*` or `description=*` to define the rules more exactly, etc.)

I'm afraid that burdening the SC mapper with having to make such distinction between `access=yes` and `access=permissive` on playgrounds would be very burdensome and counterproductive, while not improving the tagging much in any way which would actually be useful in practice. (think: what would be a realistic use case in which data consumer would e.g. decide to decline to visit a playground A in favor of playground B because it is `access=permissive` instead of `access=yes`?)

---

Take another example: car parking in front of shopping center which is currently free and open to public (often the case here), but owners may decide tomorrow (and sometimes do) to mark it as customers only, or fee only, or both, and something even more complex (e.g. free for up to 2 hours, or pay-only buy fee is waived if you bought more than x € etc). 

Should most open shopping center parkings then be tagged as `access=permissive` instead of `access=yes`?  After all, owner may decide in any moment to change the rules. But until such moment as they do, it is equally well tagged as `access=yes`.

**Comment by matkoniecz** [comment]
Posted, closing this one as won't fix unless there will be some serious indication that I was wrong. 

(If someone wants detailed analysis of permissive vs yes and is it applying here - I would ask on talk-gb or at least international forum)
