### ISSUE TITLE
Confusing icon for gate width

### ISSUE THREAD

**Issue by mxxcon** [streetcomplete/StreetComplete#6002]
I think this quest icon is a bit confusing. This gate is entrance into a parking lot, yet icon is of wheelchair as if this is a pedestrian feature.

Perhaps update this icon with something like 2 poles instead of a wheelchair? To make it more general purpose than just for pedestrian.
![Screenshot_20241108_123431_StreetComplete](https://github.com/user-attachments/assets/acb90e19-9c5a-4dea-ae3e-c5061caf8c97)

**Comment by westnordost** [comment]
Well, the quest is asked for any kind of gate.

To have a different icon for gates on different ways (i.e. gate on footway vs gate on road), we'd have to have two different quests. This seems unnecessary for me.

In the end, the quest is only going to _matter_ for wheelchairists because the expectation for gates on roads is that cars can always fit through (cause it's a road).

@Nick-Tallguy , you created this quest, would you say it makes sense to only ask for gates on footways, paths, etc?

**Comment by westnordost** [comment]
Do you have an idea for a more generic icon? What kind of poles do you mean?

**Comment by Nick-Tallguy** [comment]
![width](https://github.com/user-attachments/assets/13a2aefd-6c04-40d4-97a0-1c23511ca028)

![width_generic](https://github.com/user-attachments/assets/7fc64c0f-0e59-49a5-80cd-09694e79bb63)

The quest includes entrances, gateways, bollards, blocks and single cycle barriers - the common feature is that we are interested in the available width of the opening. Perhaps just use the width part of the icon? Or perhaps a new icon

**Comment by westnordost** [comment]
Thanks for the input, but idk, looks weird. You know, these two triangles on the circle, that's the "contents" of the "maxwidth" sign in countries that follow the Vienna convention of street signs. so at least to me it looks weird to see it without the red outline. E.g. the "contents" are only a circle because the sign itself is a circle.

**Comment by westnordost** [comment]
> Gate width might be relevant for cars too in cases where an entrance is too narrow for large trucks.

Is this a thing? Why would the gate be narrower than the road itself? That would mean that the poles for the road would need to be *on* the road surface, too. Do you know an example?

**Comment by mxxcon** [comment]
Entrance to some parking lot wouldn't be on the road.. unless I'm misunderstanding what you are saying.

Also here on the beach ramps up to the boardwalk have been blocked off with bollards and gates for service vehicles. Regular cars won't fit but Parks Department's golf cart-like cars will..

**Comment by westnordost** [comment]
With road surface, I mean the part of the road for cars, i.e. the road lanes.

Anyway, I tend to change it towards not asking for gate width for gates on (service) roads.
