### ISSUE TITLE
visibility of bicycle=yes at pedestrian zones

### ISSUE THREAD

**Issue by SebSeb11** [streetcomplete/StreetComplete#6016]
**Use case**
There is a pedestrian zone with allowed bicycle access (bicycle=yes, bicycle:signed=yes). In cycling mode of StreetComplete this way is not shown.
(https://www.openstreetmap.org/way/59038921)

**Proposed Solution**
Show pedestrian zone (highway=pedestrian, but also if tagged as area) in the same color like footways with bicycle=yes bicycle:signed=yes.

**Comment by westnordost** [comment]
Makes sense to me

**Comment by westnordost** [comment]
What should be shown when one clicks on it, though?

For the bicycle boulevard, instead of the normal UI, we have some sign and an "other answer" option to say that it isn't a bicycle boulevard, after all.

**Comment by SebSeb11** [comment]
Is there a reason why a highway=pedestrian way is not shown at the moment?
It could already be shown like a highway=footway because it's nearly the same.
("Scope of this tag may overlap with highway=footway" from [Wiki](https://wiki.openstreetmap.org/wiki/Tag:highway%3Dpedestrian))


How it could be implemented (focus on ways only (not area) because of its importance for routing):

1. Like the "It is (not) a Bicycle boulevard", add a "It is (not) a pedestrian zone" options (to pavement mode (?)).
2. Once a highway (way) is a pedestrian zone:
	2.1 clicking on it in pavement mode shows the pedestrian zone sign.
	2.2 clicking on it in cycleway mode shows the pedestrian zone sign. There should be an option to select between the "pedestrian zone" sign and one with additional small "bicycle ok" sign.
3. implementing 2.1/2.2 removes the options to add sidewalks in pavement mode and cycleways in cycleways mode. (Should be ok, not needed for pedestrian zones)

One more thought:
Since the presence of pedestrian zones does not change frequently, step 1. is not absolutely necessary. Then there would only be the option of adding or removing the well-known bicycle access to pedestrian zones.

**Comment by westnordost** [comment]
> Is there a reason why a highway=pedestrian way is not shown at the moment?
It could already be shown like a highway=footway because it's nearly the same.
("Scope of this tag may overlap with highway=footway" from [Wiki](https://wiki.openstreetmap.org/wiki/Tag:highway%3Dpedestrian))

Yes, it could be colored like a footway.

But the coloring is just one thing. The other thing is what UI to display when one clicks on a pedestrian road.

**Comment by SebSeb11** [comment]
<img src="https://github.com/user-attachments/assets/51976a1c-68b1-42d3-bcac-866e6f49e196" width="300"> <img src="https://github.com/user-attachments/assets/8d356ab9-7e63-465d-9647-0e4b5e004a28" width="300">
Maybe there is a more generic symbol for pedestrian zones.

For the bicycle boulevard case -> sidewalks can be added in pavement mode.
Analogous to this, in our pedestrian case -> cycleways could still be added in cycleway mode. But I think that's not needed because the concept of a pedestrian zone is not to contain or being crossed by cycleways.

**Comment by westnordost** [comment]
Hm, so there are some pedestrian zones which do also have cycle tracks. I looked at some via overpass, and most are of the following types:
- used to be a normal road, with sidewalks, but it has been made inaccessible to cars. The center part of the now pedestrianized road could be used by bikes
- it is actually a very wide footway, which also has a bike path next to it (through parks etc)
- a few are actually normal pedestrian zones in shopping districts that _do_ have a cycle track right in the middle of it (e.g. [here](https://www.google.de/maps/@46.0698929,23.561245,3a,75y,305.17h,75.86t/data=!3m8!1e1!3m6!1sAF1QipOue2K0iI1_QlUnWy0tW8OIzmRdxD9HaLN7mqzD!2e10!3e11!6shttps:%2F%2Flh5.googleusercontent.com%2Fp%2FAF1QipOue2K0iI1_QlUnWy0tW8OIzmRdxD9HaLN7mqzD%3Dw900-h600-k-no-pi14.142124176364788-ya305.17007725226426-ro0-fo100!7i5660!8i2830?entry=ttu&g_ep=EgoyMDI0MTExOC4wIKXMDSoASAFQAw%3D%3D))

So, since it isn't impossible for a pedestrian zone to have a cycle track, showing a big pedestrian sign icon in place of the normal street side UI would be problematic for those cases.

**Comment by westnordost** [comment]
Hm, also quite a few roads that are tagged as pedestrian zones exist that are legally non-segregated foot+bicycleways. E.g. the entire[ Weserpromenade in Bremen](https://www.google.de/maps/@53.0798471,8.7952894,3a,28.9y,263.29h,84.65t/data=!3m7!1e1!3m5!1s0gu_B_nif--GSlcybn8Ovg!2e0!6shttps:%2F%2Fstreetviewpixels-pa.googleapis.com%2Fv1%2Fthumbnail%3Fcb_client%3Dmaps_sv.tactile%26w%3D900%26h%3D600%26pitch%3D5.353913324610687%26panoid%3D0gu_B_nif--GSlcybn8Ovg%26yaw%3D263.29198288027135!7i16384!8i8192?entry=ttu&g_ep=EgoyMDI0MTExOC4wIKXMDSoASAFQAw%3D%3D)

So there would need to be three options: nothing signed, signed that yes, and designated (but not segregated, because that would be tagged with `cycleway:<side>=track`)

**Comment by SebSeb11** [comment]
The Weserpromenade is a good example that tagging of pedestrian zones is not clearly defined (when area/way). There is (partly) a pedestrian zone and a foot/cycleway through it. In that case I would create an area for the zone and a separately tagged way for the normal foot&cycleway.

My idea was not to implement options for every possible case in SC to keep the app simple to use. Your examples show a lot of possible combinations, but I see a danger in different users frequently switching tags between for example "pedestrian"/"footway". Especially if pedestrian areas are not visible and tagging is not clearly defined.

That's why I suggested only the two options pedestrian with or without bicycle=yes, which is a common combination of the pedestrian zone sign.

Until now it was ok for me to add pedestrian zones outside of SC. That could still be the case for any more complex problems.

The only thing that was irritating was the invisible way with bicycle=ok, because it looked like a gap when following a bicycle route.

So another suggestion is to make the way (highway=pedestrian) visible (it is clickable already) without changing anything else. 
A clickable and invisible way is a strange combination. That would be it for this issue.

If wanted, new issues could be about:
- pedestrian zone options to SC?
- keep cycleway UI for highway=pedestrian?
- where to put bicycle=yes option (3 dot menu)?
- switch: any highway <-> pedestrian
-...

SC is perfect for features that can be tagged clearly. If not, I would not force to add additional options for them to the app.

**Comment by westnordost** [comment]
My current plan is this (have been working on it last night, not committed yet):

- Colors for pedestrian roads: black by default, cyan dashed if bicycles designated, aquamarine dashed if if signed that bicycles are OK
- replace modal UI for bicycle boulevards with just showing that bicycle boulevard sign half-transparent in front of the normal UI. I.e. it is still possible to also specify the left and right side
- don't show the bicycle boulevard other answer option for pedestrian roads
- for pedestrian roads, show answer options for yes and designated. Choosing any of those will also just display a sign/icon on top of the normal UI

**Comment by SebSeb11** [comment]
Wow, that sounds good. Especially the way you found to keep the normal UI. :)

**Comment by westnordost** [comment]
See https://github.com/streetcomplete/StreetComplete/pull/6020
