### ISSUE TITLE
Make StreetComplete registered for josm: links?

### ISSUE THREAD

**Issue by matkoniecz** [streetcomplete/StreetComplete#6028]
It would become possible to open it (once installed) from edit button at osm.org, if See https://github.com/openstreetmap/openstreetmap-website/pull/5351 would be merged.

**Comment by AntonKhorev** [comment]
> Why josm:?

Ask Vespucci developers https://vespucci.io/tutorials/vespucci_intents/#supported-intents

Of course it only makes sense for apps that support (a subset of) remote control commands. But maybe everyone can agree to support `load_and_zoom`. Then we can have an URI scheme that would run any editor registered by the system on the user's end.

**Comment by HolgerJeromin** [comment]
Opening SC via geo uri on osm.org already works...

**Comment by westnordost** [comment]
Neither of these make sense for StreetComplete, though.

**Comment by westnordost** [comment]
So, basically, first it should be a policy decision by openstreetmap-website maintainers (or OSMF??) whether to include any editor software that are not (mostly) fully-fledged general-purpose editors on their respective platform (JOSM, iD, Vespucci, Go Map!!).

If adding other editor software is fine, I would be happy to implement whatever makes sense for such a link to StreetComplete. For example, it is conceivable to directly activate a certain overlay (e.g. Places overlay, things overlay, cycleway overlay, ...) and/or preset(s), and instead link to streetcomplete.app if the user hasn't installed StreetComplete yet.

Until then, this is a will not fix because 1. see @HolgerJeromin  and 2. see my previous comment.
