### ISSUE TITLE
Menu [...] has no entries with the thing overlay with new node

### ISSUE THREAD

**Issue by HolgerJeromin** [streetcomplete/StreetComplete#6034]
Open thing overlay.
Hit + Button to add new thing.
There is a menu entry which is always empty/not doing anything.
This is a bit confusing.

With selecting an existing streetlamp for example I have some entries in the menu (which all make no sense while creating a new one).

**Versions affected**

58.2 and v60.0-beta1

**Comment by westnordost** [comment]
Can you post a screenshot?

**Comment by HolgerJeromin** [comment]
I meant the menu on the bottom left:
![IMG_20241203_061947_(500_x_400_pixel)](https://github.com/user-attachments/assets/438fc377-da22-4df9-ad5c-74e8ded644b4)

**Comment by westnordost** [comment]
Oh, I see.

So you say, if there are not items in the menu, the button should be hidden?

**Comment by westnordost** [comment]
Hm, this'll be will not fix, for now.

The other-answers are constructed at the moment you tap on that button. The form doesn't know beforehand if there will be anything inside. So to disable the button or hide it, the form would need to construct the answer items and see if the resulting list is empty. This is doable of course, but the issue is that which answer items are displayed may differ depending on the state of the form, i.e. any change in state to the answer form may lead to different items being displayed.

After migrating the forms to ViewModel + Compose, this may be revisited, for now, it would be far too troublesome to implement.

**Comment by mnalis** [comment]
Or the confusion could simply be avoided by making sure there is always at least one option in that menu - e.g. _"Leave note"_ (which might even help with hard discoverability of current long-press-to-leave-note-here)

**Comment by matkoniecz** [comment]
I am not sure whether I would want to encourage freeform notes even more
