### ISSUE TITLE
Object unseen on ground answer for many/all quests

### ISSUE THREAD

**Issue by flacombe** [streetcomplete/StreetComplete#6038]
Sorry for potential duplicate, this sounds very simple to me and had probably been already discussed but I'm unable to find where.

**Use case**
In many quests, StreetComplete may ask user to answer questions about objects or features that may been removed from ground and still there in OSM.

**Proposed Solution**
Add a global option "this feature isn't there any more" which leads to add a note in OSM to indicate there are features to remove.

StreetComplete is unlikely to remove directly features since it could lead to important geometry rework and most of the time out of the scope of the selected quest.

**Comment by mnalis** [comment]
>  In many quests, StreetComplete may ask user to answer questions about objects or features that may been removed from ground and still there in OSM.

In which quest(s) _specifically_ did you have this problem? Can you explain that specific situation in more detail?
If clicked on `Uh...` did you not have `It does not exists...` answer there? (Or you were not aware of that option?)

> StreetComplete is unlikely to remove directly features since it could lead to important geometry rework and most of the time out of the scope of the selected quest.

In cases  simple removing is possible - e.g. missing benches, trashcans and the like.

When it is not possible or likely problematic because problem is more complex, under `Uh...` menu StreetComplete already always offers `Can't say answer` item, which allows mapper to leave OSM Note (text and pictures if needed) to explain the situation in more detail (e.g. whole building or even whole area is being torn down / reconstructed, or there is new shopping mall there now instead, or playground has been replaced with something else, or geometry of the feature has changed  etc.) so it can be fixed in some more full featured editor.

Also, Overlays (second icon to the left from top right corner) offer similar functionality under three vertical dots menu; and a user can even long-press anywhere on the map and choose `Create new note` (useful e.g. for newly build features which were not mapped previously and which cannot be added via "Places" or "Things" overlay).

**Comment by westnordost** [comment]
Closing because there has been not feedback.

In general, the requested feature already exists. It is however only displayed for point features.
