### ISSUE TITLE
Crosshair and Node marker positions are out of sync

### ISSUE THREAD

**Issue by Strubbl** [streetcomplete/StreetComplete#6039]
**How to Reproduce**
E.g. go into the things overlay. Use the crosshair to add a new node at the desired position. Press the button to add a new node.

**Expected Behavior**
The node is placed in the middle of the crosshair cursor, which i used for aiming.

**Current Behavior**
The node is placed in the bottom mid position of the cursor. You can see this already because the markers' bottom ace is also in the bottom mid.

![Screenshot_20241206_170055_StreetComplete](https://github.com/user-attachments/assets/92a62982-7156-4e20-864f-2d8de252ea83)

This affects my current usage of the app, because i aim at the position for the new node with the crosshair and then add the node only. But then it gets placed a meter too much south.

**Versions affected**

v60.0-beta1

**Comment by westnordost** [comment]
can reproduce.... so weird, I thought I fixed that, for the second time now

**Comment by mnalis** [comment]
> can reproduce.... so weird, I thought I fixed that, for the second time now

Interesting. I could reproduce the problem in 60.0-alpha2 (https://github.com/streetcomplete/StreetComplete/issues/6003#issuecomment-2466745427), but 60.0-beta1 seems to have fixed it for me. 

Here is video of SC 60.0-beta1 on my Android 14 device working just fine (see e.g. `0:09`):


https://github.com/user-attachments/assets/4a799f2c-9555-4d70-b395-0558458dea7f

**Comment by mnalis** [comment]
What is your android version, @Strubbl ?

**Comment by westnordost** [comment]
Not reproducible on a Pixel 6 emulator (Android 10), but reproducible on my Samsung S10e (Android 13)

**Comment by Strubbl** [comment]
I use Android 14

**Comment by westnordost** [comment]
Alright, I found the issue:

So the situation is that the crosshair is part of the Compose-based UI, while the pin is part of the Android View-based UI.

They are placed independently from another, but using the same logic (for portrait screen orientation):

Center in the screen, but first apply a bottom padding of...
- 442dp if the screen height is greater than 720dp
- 352dp otherwise

(this logic exists because the quest form is allowed to take up more vertical space initially on non-tiny screens. 442dp / 352dp is the "peek height" of the quest form)

For the compose part (the crosshair), the logic is here:
https://github.com/streetcomplete/StreetComplete/blob/f533924bbdf98a479c353ad0e6a2a95f559d4832/app/src/main/java/de/westnordost/streetcomplete/ui/theme/Dimensions.kt#L11-L14

For the Android view-based part, the logic is in the XML files, making use of the [Android resource system](https://developer.android.com/guide/topics/resources/providing-resources):

https://github.com/streetcomplete/StreetComplete/blob/f533924bbdf98a479c353ad0e6a2a95f559d4832/app/src/main/res/values/dimens.xml#L22
and
https://github.com/streetcomplete/StreetComplete/blob/f533924bbdf98a479c353ad0e6a2a95f559d4832/app/src/main/res/values-h720dp/dimens.xml#L3

Now, the issue is the following. Citation from the docs for the Android resource system directory names:

> The values exclude the area occupied by [Window insets](https://developer.android.com/reference/android/view/WindowInsets), so if the device has persistent UI elements on the edges of the display, the values for width and height are smaller than the real screen dimensions, even when the app is displayed edge to edge using

So, h720dp means "Height of >= 720dp minus the navigation bar and system bar".

Any device that has a screen resolution of >=720dp in total but <720dp minus navigation and system bar, the paddings will differ... :-(
