### ISSUE TITLE
Wrong country used

### ISSUE THREAD

**Issue by Helium314** [streetcomplete/StreetComplete#6059]
Close to the border it looks like the wrong country might be detected.

**How to Reproduce**
1. Open the name/title quest for https://www.openstreetmap.org/node/11194059313
2. see __cs__ as language for the information board title

**Expected Behavior**
In step 2, __de__ should be shown instead of __cs__. In the given example there is no effect on tagging, but the displayed language might confuse users.
For other quests like AddCycleway, detecting the correct country is more relevant.

**Versions affected**
SC 60.0 (F-Droid)

**Comment by westnordost** [comment]
It's not a bug of streetcomplete and not a bug of the https://github.com/westnordost/countryboundaries library used. Instead, this is due to the source data for country boundaries - see https://github.com/westnordost/countryboundaries?tab=readme-ov-file#data - not being so precise. But this is expected. The expected precision of those boundaries is that every hamlet is on the right side of the border and more or less every road. Paths, or signposts may be on the wrong side of the border.

The file size for precise offline reverse country geocoding (i.e. copy the geometry from OpenStreetMap directly) would be too large for a mobile app.

So, there is not really anything that can be done about this, but the impact is also quite insignificant.
