### ISSUE TITLE
Quest: Parking lane

### ISSUE THREAD

**Issue by rugk** [streetcomplete/StreetComplete#771]
### General
Affected key(s) (or tags) to be modified: [parking:lane](https://wiki.openstreetmap.org/wiki/Key:parking:lane)
Question asked: **Are there an parking lanes at the side of the street?**

The quest is quite similar to the cycleway quest (https://github.com/westnordost/StreetComplete/issues/139).

### Checklist
Checklist for quest suggestions (see guidelines):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary (especially if cars are actually parking)
- [x] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of elements (Worth the effort)

### Ideas for implementation

**Element selection:** all streets (maybe limit to some bigger street types), where parking is not tagged as disallowed and `parking:lane` not set

**Metadata needed:** possibly, likely at least for street signs

**Proposed GUI:** very similar to the Cycleways quest, with basic options (parallel, perpendicular, …)

Also `no_parking` and `no_stopping` should also be in there, and be represented by the street signs.

**Comment by matkoniecz** [comment]
> all streets (maybe limit to some bigger street types)

So which highway=* values? For example asking that would be absurd for highway=motorway.

Note that you need to exclude roads with nearby amenity=parking areas, some tag these kind of parkings as an areas.

**Comment by rugk** [comment]
> some tag these kind of parkings as an areas.

Well, that's totally incorrect, so… to tag it correctly may not be bad. (One may just need to remove the parking area)

**Comment by matkoniecz** [comment]
Whatever it is incorrect or not is topic for other discussion - if somebody wishes to retag it is easier to do with JOSM and aerial images + existing OSM data rather than resurveying.

> One may just need to remove the parking area

Certainly not, if such tagging is unacceptable then one should retag it (area:highway or something), not remove it.

**Comment by matkoniecz** [comment]
Example location: https://www.openstreetmap.org/?mlat=52.23883&mlon=20.96935#map=19/52.23883/20.96935

**Comment by westnordost** [comment]
Even if it were totally incorrect (which is not the point), StreetComplete may not ignore that data but rather fix than duplicate that data. To fix it automatically, however, lies outside of the capabilities of the app.

So, Mateusz is correct in saying that streets must be excluded that have a parking area very close-by, using the same mechanism as for cycleways.

Also, care must be taken that all possible findings in the real world for quests are representable in tags. Again, think world-wide. There are many different types of streets.

Am 15. Januar 2018 11:30:11 MEZ schrieb Mateusz Konieczny <notifications@github.com>:
>Whatever it is incorrect or not is topic for other discussion - if
>somebody wishes to retag it is easier to do with JOSM and aerial images
>+ existing OSM data rather than resurveying.
>
>> One may just need to remove the parking area
>
>Certainly not, if such tagging is unacceptable then one should retag it
>(area:highway or something), not remove it.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/771#issuecomment-357643026

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by HolgerJeromin** [comment]
One main problem IMO is that often you have to split the road (to limit the `parking:lane` range) which is out of scope for this app.

**Comment by lokaman** [comment]
Just want to add that parking space - especially in cities in Germany - is ristricted because of the amount of space a car needs. Sometimes you need to live in the certain area ("Anwohnerparken"), there are restrictions how long you are allowed to park, or when. Sometimes you need to pay something - sometimes not. Sometimes it's a wild combination. https://www.nuernberg.de/imperia/md/verkehrsplanung/bilder/vpl/bewohnerparken_02.jpg

**Comment by lokaman** [comment]
Just want to add that parking space - especially in cities in Germany - is ristricted because of the amount of space a car needs. Sometimes you need to live in the certain area ("Anwohnerparken"), there are restrictions how long you are allowed to park, or when. Sometimes you need to pay something - sometimes not. Sometimes it's a wild combination. https://www.nuernberg.de/imperia/md/verkehrsplanung/bilder/vpl/bewohnerparken_02.jpg

**Comment by lokaman** [comment]
Just want to add that parking space - especially in cities in Germany - is ristricted because of the amount of space a car needs. Sometimes you need to live in the certain area ("Anwohnerparken"), there are restrictions how long you are allowed to park, or when. Sometimes you need to pay something - sometimes not. Sometimes it's a wild combination. https://www.nuernberg.de/imperia/md/verkehrsplanung/bilder/vpl/bewohnerparken_02.jpg

**Comment by rugk** [comment]
You posted this three times :blush:.
Basically yeah, most things are even taggable. Some may not, but in any case we only care for the majority of quests here, everything else is a case for the note feature.

**Comment by lokaman** [comment]
@rugk seems like the server got it now despite the error messages in fasthub. "alle guten dinge sind 3" :wink:

**Comment by matkoniecz** [comment]
@rugk Can you check whatever it is typically taggable (at least in your area) without splitting ways representing roads?

**Comment by rugk** [comment]
Yes, it is. I'd say in most big cities ways are split enough.

**Comment by matkoniecz** [comment]
I thought about making PR for this quest, but in my opinion this will have far too many "no" and "splitting required" answers.

**Comment by rugk** [comment]
Why do you think it would be more than, say e.g. the maxspeed quest?

**Comment by matkoniecz** [comment]
Parking lane status tends to be split more than maxspeed limits (at least in areas that I know).

All roads have some sort of maxspeed info to tag.

**Comment by pietervdvn** [comment]
Hey everyone,

I'm gonna bump this quest. For a project where we are measuring street widths, (from curb to curb), this has turned out to be a relevant factor, so I implemented this in a private fork. This project has a limited scope, so that helps to relax some of the tougher questions above.

I've implemented it only for 'parallel_parking' and without the check for parking nearby on `residential`, `unclassified` and `tertiary` roads as these are the relevant ones we need.

And yes, sometimes it is a bit of a mess and requires quite some cutting, which have become in scope of the app by now!

If there is interest in adding this quest, I'll clean up the code and do a PR

![signal-attachment-2020-06-05-014946](https://user-images.githubusercontent.com/1466478/83821541-f6a98500-a6ce-11ea-8a0a-320322731f90.png)

**Comment by matkoniecz** [comment]
@pietervdvn 

I think that it should work not only for parallel parking (if answering yes to that questions gets recorded as parallel parking then it will result in mistakes). But I am interested in graphics (if P graphics are not included in SC already).

ABstreet makes this quest interesting for me and it is possible that I will work on it

**Comment by westnordost** [comment]
Does someone know a source where one can find **cc-licensed** svg art, in particular in this case cars from the top? Most of these icon-finder websites do not actually have free licenses for their art, because there is at least a clause that says "you may not bundle this icon and put or sell it onto your own website".

I know openclipart.org, but there is very little and nothing that looks good. I know that some emoji-sets are cc-licensed (twemoji, some others) but there are no emojis that show cars from the top.

**Comment by matkoniecz** [comment]
It seems that most of work was done by implementing of bikeway quest and remaining part is making graphics.

Test code without graphics is at https://github.com/westnordost/StreetComplete/compare/master...matkoniecz:parking_lane?expand=1

**Comment by westnordost** [comment]
> It seems that most of work was done by implementing of bikeway quest and remaining part is making graphics.

You don't say!

**Comment by westnordost** [comment]
Regarding your code:
1. as opposed to sidewalk tagging, I can not find any information on whether mapping parking lanes as areas is accepted practice as well (in certain areas). So maybe the complicated overpass query is not necessary?
2. Ctrl+F "cycle" in your code
3. special handling of oneway roads is necessary - if only for display reasons (orientation of graphics that show the cars)
4. for the "no parking", "no stopping" and "fire lane" graphics, the graphics should be based on the appropriate street sign, so we need to find the different graphics from over the world for that.
5. maybe limit to places where the is a sidewalk (and surface= something paved?)

**Comment by matkoniecz** [comment]
> special handling of oneway roads is necessary - if only for display reasons

**Comment by matkoniecz** [comment]
> Does someone know a source where one can find cc-licensed svg art, in particular in this case cars from the top? Most of these icon-finder websites do not actually have free licenses for their art, because there is at least a clause that says "you may not bundle this icon and put or sell it onto your own website".

https://thenounproject.com/term/car/1728119/ https://thenounproject.com/term/car/2855626/ (CC-BY) - (suggested by Ketch Ar from the Telegram group)

**Comment by pietervdvn** [comment]
> @pietervdvn
> 
> I think that it should work not only for parallel parking (if answering yes to that questions gets recorded as parallel parking then it will result in mistakes). But I am interested in graphics (if P graphics are not included in SC already).
> 
> ABstreet makes this quest interesting for me and it is possible that I will work on it

Yes, my tweak only records parallell parking, other types of parking are recorded manually for our project. You can find my graphics here: https://github.com/pietervdvn/StreetComplete/blob/c749364f60cf92d48ecb328aeb8b031491ef498b/app/src/main/res/drawable/ic_parking_lane_puzzle_yes.xml , consider them CC-BY

**Comment by matkoniecz** [comment]
> maybe limit to places where the is a sidewalk (and surface= something paved?)

It is tricky, because asking it in rural areas is often pointless while cities may have roadside parking even without sidewalk...

But I think that requiring would be unfortunately a good idea, even at cost of missing some answers.

On the other hand for A/B Street it would be nice to have full coverage, but probably having two quests of a different intensity would be an overkill.

**Comment by matkoniecz** [comment]
>  can not find any information on whether mapping parking lanes as areas is accepted practice as well (in certain areas)

At least in Poland it is often done this way. Not sure whatever it is accepted/preferred (see say https://www.openstreetmap.org/#map=19/52.23125/21.01400 )

**Comment by westnordost** [comment]
Drew some cars today, was fun

![image](https://user-images.githubusercontent.com/4661658/98376365-a9498f00-2043-11eb-8275-5cd853040152.png)

**Comment by pietervdvn** [comment]
Cool. Might steal them one day ;)

**Comment by rugk** [comment]
Why do we need so many cars? :see_no_evil: 
Should it cycle randomly between the car image displayed on the street in the icon/selectable image? :wink:

**Comment by naposm** [comment]
Now that we have a lane quest this quest would be very useful. Maybe it could be asked before the lanes one so it would be easier to assume the width of the street 🤔 (thinking about this comment: https://github.com/westnordost/StreetComplete/pull/2269#issuecomment-728580077)

> 
> 
> Why do we need so many cars? 🙈
> Should it cycle randomly between the car image displayed on the street in the icon/selectable image? 😉

I'd put them randomly on a "P" space once the user selects the answer, like this:

![Screenshot with cars on "P" spots](https://user-images.githubusercontent.com/63296731/100450674-fdc5b480-30ad-11eb-8dff-4f9f57c04a0e.png)

I think that maybe it would look "cool"

(By the way OT `@westnordost`: Thank you very much for the lanes/oneway quests, they were very useful to me! 🤗 Writing here so I don't update a closed issue )

**Comment by andrewharvey** [comment]
https://en.wikipedia.org/wiki/Road_signs_in_Australia has signs for Australia, there might be similar wikipedia pages for other regions. Though personally I don't think the signs have to be exact (that could come later to improve localisation).

How I see this quest working is like the cycleway/sidewalk quest.

Ask: Is there a parking lane here? What type?

Illustration shows both sides of the road with `?`.

Upon selecting a side you have options from https://wiki.openstreetmap.org/wiki/Key:parking:lane#Parking_spaces

- Can't say (eg no signage?)
- parallel
- diagonal
- perpendicular
- marked
- no_parking
- no_stopping
- fire_lane
- no
- separate

Then immediatly ask again for that selected parking, what is the parking position?

- on_street
- half_on_kerb
- on_kerb
- street_side
- etc.

Parking condition would be left to another quest that is unlocked after answering parking lane.

**Comment by jakecoppinger** [comment]
Is there anything I could work on to help move this forward? :) I haven't done any Kotlin dev before unfortunately, I write TypeScript for work, but might be able to have a crack.

Is this the current closest to ready PR? https://github.com/streetcomplete/StreetComplete/compare/master...matkoniecz:parking_lane?expand=1

I've been working on https://openparkingmap.com (a fork of `zlant/parking-lanes` with Australian parking signs) so I'm keen to add more parking lane info.

**Comment by westnordost** [comment]
It's on the roadmap. Right now, I have no idea how you can help.

What will be a problem, as usual, is to display only roads to the user where it is reasonable to ask if there is a parking lane or not. E.g. outside of towns, parking is not expected, but there is no tag that states whether a road is in or outside of a settlement.

**Comment by mnalis** [comment]
Perhaps it could be asked only on streets with `maxspeed:type=XX:urban`? It is far from perfect, of course, as it would only catch a subset of eligible streets, but it would catch some of them, and there would be little or no false positives. It might possibly also be extended with `maxspeed <= 60` or similar to catch probably-inside-of-settlement streets. 

In addition, `highway=residential` and `highway=living_street` maybe might be assumed to be inside a settlement?

The quest, if implemented, might still be disabled by default IMHO, as it might generate _too many_ quests. The bigger issue that what roads are inside settlements is how to **exclude** the road if there is [nearby parking already mapped](https://github.com/streetcomplete/StreetComplete/issues/771#issuecomment-357645239).

**Comment by westnordost** [comment]
https://user-images.githubusercontent.com/4661658/145690602-6a771c02-6767-461b-ae84-d67dbe819e28.mp4

**Comment by westnordost** [comment]
Since StreetComplete directly tags `parking:lane:<side>=no_parking`, `no_standing` and `no_stopping` or otherwise (no sign) `no`, the biggest effort was to display to the user the signs and/or road markings appropriate for the country he is mapping in.

A few examples:

| United States | Switzerland |
| ---- | ---- |
| ![device-2021-12-11-210545](https://user-images.githubusercontent.com/4661658/145690718-154525e7-eb62-4b8f-8a19-57dd269fb9d0.png) | ![device-2021-12-11-210649](https://user-images.githubusercontent.com/4661658/145690720-836bf208-a629-4ca1-8dd3-3e675cfea15f.png) |

| South Africa | Thailand |
| ---- | ---- |
| ![device-2021-12-11-211439](https://user-images.githubusercontent.com/4661658/145690722-edc00998-707a-4d21-a7a7-687275a702bc.png) | ![device-2021-12-11-210401](https://user-images.githubusercontent.com/4661658/145690725-2912b6ee-882b-4b4c-b8d8-b90cf2868cea.png)

**Comment by BalooUriza** [comment]
In the US, it's more common for places that paint the curbs to use red as
no stopping and yellow as no parking.

**Comment by westnordost** [comment]
According to my research,  that depends very much on the state. If you can link to relevant legislation or "photo evidence" (streetview, mapillary showing such markings and in context), i can include it for the state you live in or know about.

**Comment by 1ec5** [comment]
By the way, this quest reflects [the current description](https://wiki.openstreetmap.org/wiki/Special:Diff/2226925) of `no_parking` and `no_stopping` (which are also consistent with [this tagging overhaul](https://wiki.openstreetmap.org/wiki/Proposed_features/Parking_lane_conditionals)). Previously, the documentation made inaccurate claims regarding the United States that would have resulted in “No Parking” being interpreted as `no_stopping` and “Loading Zone” as `no_parking`.

**Comment by fabzgy** [comment]
Thunbs up for this quest from Freiburg, Germany. Our city has no idea how many parking spots do exist.
