### ISSUE TITLE
Surveillance camera properties

### ISSUE THREAD

**Issue by PanderMusubi** [streetcomplete/StreetComplete#87]
Support surveillance camera properties as is also discussed in https://github.com/DaylightingSociety/WhereAreTheEyes/issues/3 and https://github.com/DaylightingSociety/WhereAreTheEyes/issues/15 and specifically https://github.com/DaylightingSociety/WhereAreTheEyes/issues/3#issuecomment-264463712 and https://kamba4.crux.uberspace.de/

**Comment by westnordost** [comment]
Are surveillance camera (properties) documented and approved in the OSM wiki? I wouldn't want to add quests that add data that isn't

**Comment by forteller** [comment]
https://wiki.openstreetmap.org/wiki/Tag:man_made%3Dsurveillance

**Comment by rugk** [comment]
They are. See https://kamba4.crux.uberspace.de/ for a great use of them.

When you also want to include such things as [camera:direction](https://wiki.openstreetmap.org/wiki/Proposed_features/Extended_tags_for_Key:Surveillance#Camera) and [angle](https://wiki.openstreetmap.org/wiki/Proposed_features/Extended_tags_for_Key:Surveillance#Camera) (in addition to [camera type](https://wiki.openstreetmap.org/wiki/Proposed_features/Extended_tags_for_Key:Surveillance#Camera), [height](https://wiki.openstreetmap.org/wiki/Key:height), etc.), you might want to make a special "input method" for the angle and using the accelerometer… :smiley: 
(I often find it difficult to guess the angle used for the camera and there you can just compare it with the angle of your phone, and maybe also include the direction the phone is pointing to)

I think when making separate quests for this, they should be asked one-after-one in a logical order (beginning with simple things such as type and ending with this angle e.g.) when they are not set yet, so that you do not have to select the quest icon again and again.

**Comment by rugk** [comment]
Wow, this is the most upvoted issue currently. :laughing:

**Comment by rugk** [comment]
Actually, 2017, but yeah do not actually remember it and it may be a good base for a re-implementation of this quest. (I e.g. like the quest icon and the image assets.)

**Comment by matkoniecz** [comment]
`surveillance=indoor/outdoor/public` ( https://wiki.openstreetmap.org/wiki/Proposed_features/Key:Surveillance#Values ) and `camera:type=fixed/panning/dome` ( https://wiki.openstreetmap.org/wiki/Tag:man_made%3Dsurveillance#Tags_to_use_in_combination ) look as a good candidates for a start.

Main potential stoppers: is `surveillance=indoor/outdoor/public` something easily derivable from position of camera? I think not, it may depend on where camera is directed.

`camera:type=fixed/panning/dome` - is fixes and panning always easy to distinguish?

How we can skip/tag cameras in locations inaccessible to general public?

**Comment by m-rey** [comment]
> is fixes and panning always easy to distinguish?

In my experience, it can't be distinguished easily.
Dome cameras however can be recognized easily.

**Comment by goldfndr** [comment]
Looking at [EFF's page](https://www.eff.org/pages/surveillance-cameras), fixed cameras have the *axles* (or whatever the pivots are called) exposed to the elements, and pan/tilt cameras have their mechanisms protected; I wouldn't be surprised if there are a few step-down gears in some of them.

**Comment by Dosenpfand** [comment]
If no one else is working on this, I would like to give the implementation of this quest a try.

> Main potential stoppers: is surveillance=indoor/outdoor/public something easily derivable from position of camera? I think not, it may depend on where camera is directed.

Could this be resolved by phrasing the question that way? E.g. "Where does this surveillance camera point?"

> is fixes and panning always easy to distinguish?

So this might still need some research, to determine if it is easy to distinguish and if it could be made clear in the UI.

> How we can skip/tag cameras in locations inaccessible to general public?

Is this really a blocker? I regularly get quests in StreetComplete for features that are not publicly accessible, e.g. house numbers for buildings on private streets, sports questions for school sport pitches, etc. Isn't it the surveyors responsibility to determine if solving a quest is possible from public property? Additionally, I would assume that not many surveillance cameras are present in OSM that can not be seen from public property. Because this would raise the question of who added them in the first place.

**Comment by westnordost** [comment]
It kind of is a blocker, see the quest guidelines. Additionally, it is difficult to ask the user "here is a camera, is it inside or outside?" because the user might then not even know which camera is meant - if it is not even known where the camera is supposed to be.

Furthermore, I have reservations against collecting data about surveillance for private property, so any other than **surveillance=public**.

So a good start is to only ask for cameras that have been tagged as being **public** whether they are fixed, panned or dome. Most difficult thing will be to find a good illustration for this. By the way, animated vector drawables (for panned) would also be an option, if you dare to grapple the subject.
Next up could be to find the direction for public non-dome cameras.

**Comment by rugk** [comment]
>  Most difficult thing will be to find a good illustration for this. 

The old PR at https://github.com/westnordost/StreetComplete/pull/299 had some illustrations that are quite acceptable IMHO.

**Comment by westnordost** [comment]
Hm.

**Comment by Binnette** [comment]
Hi @westnordost, If you want I can "update" my PR #299. Test if my code is still working. And also, i will need to make my icons more "StreetComplete style" conpliants.

**Comment by westnordost** [comment]
It wilp not work anymore, too many things changed in the meantime

**Comment by Helium314** [comment]
@Binnette 
are you still interested in updating your PR?

<details>
 <summary>Here is updated AddCameraType.kt</summary>

```kotlin
package de.westnordost.streetcomplete.quests.camera_type

import de.westnordost.streetcomplete.R
import de.westnordost.streetcomplete.data.osm.edits.update_tags.StringMapChangesBuilder
import de.westnordost.streetcomplete.data.osm.osmquests.OsmFilterQuestType


class AddCameraType : OsmFilterQuestType<CameraType>() {

    override val elementFilter = "nodes with surveillance:type = camera and !camera:type"
    override val commitMessage = "Add camera type"
    override val wikiLink = "Tag:surveillance:type"
    override val icon = R.drawable.ic_quest_camera_type

    override fun getTitle(tags: Map<String, String>) = R.string.quest_camera_type_title

    override fun createForm() = AddCameraTypeForm()

    override fun applyAnswerTo(answer: CameraType, changes: StringMapChangesBuilder) {
        changes.add("camera:type", answer.osmValue)
    }
}
```
</details>

<details>
 <summary>and AddCameraTypeForm.kt</summary>

```kotlin
package de.westnordost.streetcomplete.quests.camera_type

import de.westnordost.streetcomplete.R
import de.westnordost.streetcomplete.quests.AImageListQuestAnswerFragment
import de.westnordost.streetcomplete.quests.camera_type.CameraType.*
import de.westnordost.streetcomplete.view.image_select.Item

class AddCameraTypeForm : AImageListQuestAnswerFragment<CameraType, CameraType>() {

    override val items = listOf(
        Item(DOME, R.drawable.ic_camera_type_dome, R.string.quest_camera_type_dome),
        Item(FIXED, R.drawable.ic_camera_type_fixed, R.string.quest_camera_type_fixed),
        Item(PANNING, R.drawable.ic_camera_type_panning, R.string.quest_camera_type_panning)
    )

    override val itemsPerRow = 3

    override fun onClickOk(selectedItems: List<CameraType>) {
        applyAnswer(selectedItems.single())
    }
}
```
</details>

<details>
 <summary>and CameraType.kt</summary>

```kotlin
package de.westnordost.streetcomplete.quests.camera_type

enum class CameraType(val osmValue: String) {
    DOME("dome"),
    FIXED("fixed"),
    PANNING("panning"),
}
```
</details>

dome/fixed/panning strings need to be added, quest icon extracted from the SVG, and maybe the images could be updated.
And the element selection could limited to public/outdoor cameras.

**Comment by Helium314** [comment]
This is what it currently looks like:
![Screenshot_20210501-091552_Street�Complete](https://user-images.githubusercontent.com/43007630/116776414-95b63880-aa68-11eb-9910-be018c683e5a.png)

**Comment by westnordost** [comment]
You might just as well create an own PR for that with your code.

**Comment by Helium314** [comment]
Actually I'm not sure whether it's ok if I simply re-use @Binnette's icons, that's why wrote here instead of directly creating a PR.
