### ISSUE TITLE
Request: Ask levels for each building part

### ISSUE THREAD

**Issue by LivInTheLookingGlass** [streetcomplete/StreetComplete#985]
### General
Affected tag(s) to be modified/added: [building:levels](https://wiki.openstreetmap.org/wiki/Key:building:levels)
Question asked: **How many levels are in this part of {building name}?**

### Checklist
Checklist for quest suggestions (see guidelines):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary 
- [x] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of elements (Worth the effort)

### Ideas for implementation
When scanning for buildings, also include a search for building:part. 

**Element selection:** 

I forget if you can do key regex in overpass. If so, replace [these lines](https://github.com/westnordost/StreetComplete/blob/205cd4ca8461a782ffcba9d875beefd5c6c53348/app/src/main/java/de/westnordost/streetcomplete/quests/building_levels/AddBuildingLevels.java#L23) with:

```java
" ways, relations with " +
" building | building:part ~ house|residential|apartments|detached|terrace|farm|hotel|dormitory|houseboat|" +
"school|civic|college|university|public|hospital|kindergarten|transportation|train_station|"+
"retail|commercial|warehouse|industrial|manufacture" +
" and !building:levels and !height and !building:height";
```

**Metadata needed:**  None

**Proposed GUI:** Simply reuse the GUI from the current level quest

**Comment by ENT8R** [comment]
Kind of related, but not the same: #579

**Comment by gappleto97** [comment]
I do think that we should do that, but having the global levels value is technically correct, so it makes more sense to me to ask it on a per-part basis before trying to push that sort of thing.

**Comment by HolgerJeromin** [comment]
A complex building can be made up from arbitrary shaped `building:part` for 3D modeling (See "Aachener Dom"/"Kölner Dom"). 
I dont think a user is able to answer this quest from the outside with the given precision the rendering has.

**Comment by matkoniecz** [comment]
How one may distinguish building:parts that have levels and ones that have not (for example columns)?

Given that building:part is supposed to be for ultra-detailed 3D mapping - it it useful to provide levels count? I think that in this case height would be necessary.

> Applies to a reasonable number of elements (Worth the effort)

In some places 3D mappers sliced buildings in absurd amount of parts (I may find some examples if that would be useful).

**Comment by westnordost** [comment]
Hmm, two comments about that:

1. It is not common for building:parts to have anything else as value than "yes". But with just "yes" tagged, it may be a kind of building (part) that does not reasonably have any levels 

2. Building parts are usually only used for 3D-mapping, thus, it is very rare to find building parts that have neither a levels nor a height set because the person who adds these building parts usually adds them specifically to map the different building heights/levels.

So, i dont really think this would make sense as a quest.

On 23 March 2018 09:09:39 CET, Mateusz Konieczny <notifications@github.com> wrote:
>How one may distinguish building:parts that have levels and ones that
>have not (for example columns)?
>
>Given that building:part is supposed to be for ultra-detailed 3D
>mapping - it it useful to provide levels count? I think that in this
>case height would be necessary.
>
>> Applies to a reasonable number of elements (Worth the effort)
>
>In some places 3D mappers sliced buildings in absurd amount of parts (I
>may find some examples if that would be useful).
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/985#issuecomment-375574793

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by ENT8R** [comment]
> It is not common for building:parts to have anything else as value than "yes".

[Taginfo](https://taginfo.openstreetmap.org/keys/building%3Apart#values) says that about **80%** of all values of `building:part` is tagged only with `yes`. And another 10% are `building:part=roof` which has AFAIK very often only one level...

**Comment by westnordost** [comment]
According to info on taginfo, only about 3% of all elements tagged as `building:part` have a tag that would make them theoretically eligible for this quest. But about 85% of all elements tagged with `building:part` already have either a height or levels tagged, thus making this quest theoretically eligible for only 0.45% of building parts, or 2500 elements.
Theoretically, because it is also legal tagging to have situations where there is i.e. a `retail` building part in the first few floors and have a `residential` building part on top of it (with  building:min_level). Without a special UI that can display this correctly, letting users answer in these situations would lead to mistakes.

**Comment by riQQ** [comment]
For reference, the building quest was initially also asked on `building:part` elements, but this was later removed in #79 / e4897e9bfd46801ebae6ba080974ff857bc647cb)
